### ISSUE TITLE
resolve __file__

### ISSUE THREAD

**Issue by cnsgsz** [jorgenschaefer/elpy#1008]
my workflow often involve `elpy-shell-send-region-or-buffer ` and the \__file\__ variable is not set in the buffer as expected. is it easy to replace that with the filename of the buffer if possible when the buffer is sent to python?

**Comment by jorgenschaefer** [comment]
`elpy-shell-send-region-or-buffer` send your buffer to the inferior process much like typing them into a Python shell would do. `__file__` is not even defined there. So this is actually the expected behavior.

If you want to use `__file__`, could I suggest using `M-x compile` to run the script?

**Comment by cnsgsz** [comment]
yes, thanks for the suggestion and offering this great package!
