### ISSUE TITLE
elpy cannot find rope and jedi

### ISSUE THREAD

**Issue by zeeshansayyed** [jorgenschaefer/elpy#1010]
Hi,

I installed 

Elpy Configuration all the required dependencies using anaconda. But still elpy isn't able to find them. Am I supposed to be changing the environment variables?

My PATH variable already points to anaconda2/bin

Virtualenv........: None
RPC Python........: 2.7.12 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: Not found (0.9.0 available)
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.2.4 available)
Yapf..............: Not found (0.12.2 available)
Syntax checker....: Not found (pyflakes)

**Comment by jorgenschaefer** [comment]
I do not know or use Anaconda. From what I hear, that project creates a virtualenv. Try using `M-x pyvenv-activate` to activate the virtualenv.

**Comment by zeeshansayyed** [comment]
Thanks. So I couldn't figure out where the default virtual_env for conda is created. So I created a new virtual_env and switched to it in emacs and installed the required packages. I guess, I should be using the default conda space. I should use virtual_envs even for general work.
