### ISSUE TITLE
Looking for file in project is going to root directory

### ISSUE THREAD

**Issue by dav009** [jorgenschaefer/elpy#1011]
Even tho I set  project folder via: `M-x elpy-set-project-root` to `~/source/projectA`

whenever I do `C-c C-f` it inspects all the files from `~/` and it takes a long time, since the root folder contains a lot of files/subfolders.

I checked that the elpy project variable was set to   `~/source/projectA`.

**Comment by jorgenschaefer** [comment]
Thanks for the report. What's the result of `M-: (elpy-project-root)`? What version of `find-file-in-project` do you have installed?

**Comment by dav009** [comment]
`M-: (elpy-project-root) `shows the right folder

```
Status: Installed in ‘find-file-in-project-20160909.1355/’ (unsigned).
    Version: 20160909.1355
```

**Comment by jorgenschaefer** [comment]
That's weird. `elpy-find-file` calls `find-file-in-project` with `ffip-project-root` bound to the result of `(elpy-project-root)`. Could you edit elpy.el, the end of `elpy-find-file`, and add a `(message "ffip-project-root: %S / %S" ffip-project-root (elpy-project-root))` line before `(find-file-in-project)`? That should give some output when being called.

**Comment by dav009** [comment]
just did that, restarted emacs.
Did all the steps, got no message.

Im a beginner with emacs, not sure fi I am missing something. i.e: "recompiling" `elpy.el` file ?

**Comment by jorgenschaefer** [comment]
Try `M-x load-file RET ..../elpy.el RET`, or even just `C-x C-e` after the full function form.

**Comment by dav009** [comment]
well, actually reloading `elpy.el` fixed the issue..
