### ISSUE TITLE
Faster auto complete in ELPY ?

### ISSUE THREAD

**Issue by dineshadepu** [jorgenschaefer/elpy#1015]
Elpy shows suggestions after typing three letters, but auto complete shows suggestions after typing a single letter. How to change ELPY such that I could get that auto complete functionality. If it is not possible
then please let me know how to disable ELPY auto complete.

**Comment by ChillarAnand** [comment]
Elpy uses company for autocomplete. You can set 

    (setq company-minimum-prefix-length 1)

in your config to start autocomplete after 1st char.

**Comment by dineshadepu** [comment]
Thanks, it worked
