### ISSUE TITLE
Testing that elpy works well

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#1018]
Hi,

Sometimes `elpy-goto-definition` does not take me to the definition (even if it is in the same file). I wonder if there is a command I could run to make sure Elpy can find all the modules and packages it needs.

Does the package ship with any tests I could run?

**Comment by jorgenschaefer** [comment]
Elpy uses a backend – usually Jedi or Rope – to determine the location of a definition. Python being the dynamic language that it is, this is not trivial, so it can sometimes fail. That's a "bug" in the backend you are using. You can file a report there if you like.

At least Jedi has extensive tests, too.

**Comment by humitos** [comment]
Sometimes the problem, at least for myself, was the RPC took too much time to return a response and that was the issue. So, I increased this time adding this in my emacs configuration

    ;; Set timeout for backend rpc
    (setq elpy-rpc-timeout 3)

**Comment by amelio-vazquez-reina** [comment]
Thanks all. The problem that I keep encountering is "definition not found" even if I do this on a  function defined right there in the same buffer, e.g.:

``` python
def foo():
  print('hello')


a = 2
b = 3
foo()  # <- I get "No definition found" 
```

How would you suggest I go about debugging this problem? @humitos  @jorgenschaefer

**Comment by ChillarAnand** [comment]
Jedi works well for this. Try adding this to your config and test again.

    (setq elpy-rpc-backend "jedi")

**Comment by amelio-vazquez-reina** [comment]
Thanks @ChillarAnand  As it turns out, I had commented out that line!! All good now :). Thanks!
