### ISSUE TITLE
Autocompletion disabled inside of virtualenvs

### ISSUE THREAD

**Issue by amirteymuri** [jorgenschaefer/elpy#1020]
Inside of virtualenvs there is no active code autocompletion. I activate the envs with `pyvenv-activate`, then start the RPC with `C-c C-z`, but typing inside the source file shows no completions. What should i do?

**Comment by jorgenschaefer** [comment]
Please run `M-x elpy-config` and see if that suggests possible fixes. If not, post the output here. :-)

**Comment by amirteymuri** [comment]
Thanks, i should install jedi for each environment again. This solved the autocompletion problem.
