### ISSUE TITLE
elpy-shell-send-current-statement is missing?

### ISSUE THREAD

**Issue by henningsway** [jorgenschaefer/elpy#1021]
Dear Jorgen,

thank you for your efforts with the elpy package. I am new to python and look for an ESS-feel and a very interactive code evaluation. It seems that `C-c Ret` (`elpy-shell-send-current-statement`) seems to be what I want, but the function itself doesn't seem to exist (if I search with `M-x`).

This is the python related part of .emacs-file:
```
  (package-initialize)
  (elpy-enable)
  ;(setq elpy-rpc-python-command "python3")
  (elpy-use-ipython)
  (setq python-shell-interpreter "ipython"
   python-shell-interpreter-args "--simple-prompt -i")

  (defun set-exec-path-from-shell-PATH ()
  (interactive)
  (let ((path-from-shell (replace-regexp-in-string "^.*\n.*shell\n" "" (shell-command-to-string "$SHELL --login -i -c 'echo $PATH'"))))
  (setenv "PATH" path-from-shell)
  (setq exec-path (split-string path-from-shell path-separator))))

  (set-exec-path-from-shell-PATH)
```

I use Emacs 24.5.1

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! What's the output of `M-x elpy-config`?

**Comment by henningsway** [comment]
Dear Jorgen,

thank you for looking into this. This is what `elpy-config` returns

```
Virtualenv........: None
RPC Python........: 3.5.2 (/home/hb/anaconda3/bin/python)
Interactive Python: ipython (/home/hb/anaconda3/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Syntax checker....: pyflakes (/home/hb/anaconda3/bin/pyflakes)
```

Kind regards
Henning

**Comment by jorgenschaefer** [comment]
> `Elpy..............: 1.8.0`

The current version is 1.13.0, could you upgrade and see if it works then?

**Comment by henningsway** [comment]
The function is there now and it totally seems to work. Thank you very much. :-D
