### ISSUE TITLE
Disable too many unneccessary warnings? 

### ISSUE THREAD

**Issue by dineshadepu** [jorgenschaefer/elpy#1023]
Elpy shows too many unnecessary warnings. To disable  

[invalid-name]
[docstring needed]
[redefined outer-name]

Generally warnings coming with blue, yellow underlined score. How to disable such warnings?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Elpy uses `flake8` and `flymake` by default to generate warnings. If you have not changed that, please check the documentation of flake8 on how to configure it.

**Comment by dineshadepu** [comment]
By disabling rope and import magic, I solved the problem. Thank you.
