### ISSUE TITLE
Elpy Version Mismatch

### ISSUE THREAD

**Issue by humitos** [jorgenschaefer/elpy#1024]
I'm using `master` branch of elpy. After the latest commit (https://github.com/jorgenschaefer/elpy/commit/5c900ff6b5524e216247f52ed4085734d815dacb) I started to receive this message:

```
Elpy Version Mismatch

You are not using the same version of Elpy in Emacs Lisp compared to
Python. This can cause random problems. Please do make sure to use
compatible versions.

Elpy Emacs Lisp version: 1.13.0
Elpy Python version....: 1.12.0
```

It makes sense to me because a new version of elpy emacs lisp was bumped but not an elpy python version. So, are you planning to release the 1.13.0 version of the elpy python module?

On the other hand, can I disable this warning at the moment? I didn't find the way.

**Comment by humitos** [comment]
The buffer is prompted up and it uses half of the screen, maybe a good idea will be to show the message in the `*Messages*` buffer as Magit does:

    Cannot determine Magit’s version (error "/home/humitos/.emacs.d/packages/magit.el" repo static elpa debug)

**Comment by ChillarAnand** [comment]
Elpy python 1.13.0 was already released. You can upgrade with 

    pip install --upgrade elpy

**Comment by humitos** [comment]
Sorry, my mistake. I changed some config some days ago and I had activated the incorrect virtualenv.

**Comment by ChillarAnand** [comment]
No problem. Glad your issue is solved. Enjoy elpy :-)
