### ISSUE TITLE
elpy-goto-definition, not able to locate definitions when working with "Abstract super-classes"

### ISSUE THREAD

**Issue by mk-rahal** [jorgenschaefer/elpy#1025]
I have been working with abstract super-classes and have noticed that "elpy-goto-definition", is not able to locate definitions when working with a super class that expects part of its behavior (a method) to be determined by a sub class. 

I have attached a small piece of code to help reproduce the issue. In a nutshell, "elpy-goto-definition" is unable to locate the definition of the "func2" method that implements code expected by the super-class' "func1" method. In this example the call to the "func2" method within the "Super" class invokes a new inheritance tree search from bottom-up, which locates "func2" within the "Child" class. 

    class Super():
        def func1(self, data):
            self.word = data
            print "Now within Super class - func1 method and self.word contains %s" % (self.word)
            self.func2()

    class Child(Super):
        def func2(self):
            print "Now within Child class - func2 method, self.word contains %s" % (self.word)

    i = Child()
    i.func1("test")

When the user attempts to jump to definition from the "self.func2" method call on line 5 (using M-.) elpy returns "No definition found". I think the issue here is that elpy does not re-initiate an independent inheritance tree search to locate the definition, but rather expects it to be defined before the call.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Elpy does not implement code introspection itself, but uses libraries (either Jedi or Rope) to do this. Please report this problem to the upstream library that you are using. :-)

**Comment by mk-rahal** [comment]
Good to know, I will report it to the upstream library devs at once. Thank you for your input.
