### ISSUE TITLE
Disabling loading specific packages?

### ISSUE THREAD

**Issue by aalmah** [jorgenschaefer/elpy#1027]
Hi,

I have recently installed tensorflow package, and since then I am getting this error message from Elpy backend whenever I open a python file:
```
Output from Backend

There was some unexpected output from the Elpy backend. This is
usually some module that does not use correct logging, but might
indicate a configuration problem.

Output
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.
```

It seems that it's loading tensorflow automatically, which prints out spurious messages. Is there a way to disable loading tensorflow specifically? Thanks!

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! Elpy only loads packages when importmagic is installed. This module needs to load modules to find possible completions. Please ask at their repository for how to configure the library: https://github.com/alecthomas/importmagic

**Comment by aalmah** [comment]
Thanks for your reply @jorgenschaefer. It seems that this is a known issue in tensorflow, so I was thinking that maybe the easiest solution to me is to try to avoid the "Output from Backend" warning buffer from elpy. Do you think this is possible?
And sorry for the late follow up, but I lived with this message for a while and then uninstalled tensorflow all together when I finished the thing I'm working on, but now I need it again :-)

**Comment by jorgenschaefer** [comment]
> avoid the "Output from Backend" warning buffer from elpy. Do you think this is possible?

Tricky. Elpy does not know what the output might mean – could be important to you, after all. You should be able to just hide the buffer (hide, not kill), it should not pop up again.

**Comment by aalmah** [comment]
Can't we match the warning string and hide/kill the buffer automatically?

**Comment by aalmah** [comment]
Since these logging messages are result of importing tensorflow package, one way to avoid (manually) is to set an environment variable as described here: https://github.com/tensorflow/tensorflow/issues/5537
This should hide those logs when importing tensorflow from my script, so I thought if I would put it in my .bashrc it would also hide then when importmagic imports tensorflow, but that didn't work. Do you have any idea why it doesn't work here?

**Comment by jorgenschaefer** [comment]
Are you starting your Emacs from a desktop environment without bash?

Try `(setenv "VARIABLE" "VALUE")` in your init.el :-)

**Comment by aalmah** [comment]
I'm starting it from bash. I also tried (setenv "TF_CPP_MIN_LOG_LEVEL" "3") but still getting the messages :(

**Comment by jorgenschaefer** [comment]
Does setting that environment variable have the desired effect outside of Emacs?

**Comment by aalmah** [comment]
It does not. Thanks for pointing this out. I think the reason it's not working is because I am using an old release of tensorflow. My bad.

**Comment by gopar** [comment]
Seems to be related to importmgic, and since we dropped support for that. Closing this issue
