### ISSUE TITLE
Unused function: elpy-flymake--standard-value

### ISSUE THREAD

**Issue by sam-s** [jorgenschaefer/elpy#1034]
what is `elpy-flymake--standard-value` for?
it is never used.

**Comment by jorgenschaefer** [comment]
Oh, good catch. Forgot to remove this when I removed a (mis-)feature that tried not to override a user setting, but override a default value. Can safely be removed. Will do so when I find the time. :-D

**Comment by sam-s** [comment]
there are many such things in the code, I can fix them after you merge the other MR

**Comment by jorgenschaefer** [comment]
Removed in 142e37, thanks for noticing!
