### ISSUE TITLE
lose kill-ring on save

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#1043]

**Comment by kootenpv** [comment]
After a very long debugging session, I discovered that py-autopep8 was the problem. You're having an old version.

Remove py-auotpep8 and elpy as installed emacs packages. Then reinstall from MELPA. This should solve it.

**Comment by jorgenschaefer** [comment]
Heh. Thanks for debugging this yourself and updating the issue! I hope you enjoy Elpy :-)
