### ISSUE TITLE
Make find-file-in-project and highlight-indentation optional instead of a depedancy

### ISSUE THREAD

**Issue by CSRaghunandan** [jorgenschaefer/elpy#1045]
The whole point of using emacs is because of it's freedom in choice and extensibility. 

I use [`highlight-indent-guides`](https://github.com/DarthFennec/highlight-indent-guides) and `projectile-find-file` to achieve the same functionality as the above mentioned packages. I feel `highlight-indent-guides` to be a superior alternative to `highlight-indentation` and I do not like the fact that `elpy` uses it as default.

I know it's easy to disable `highlight-indentation` and `find-file-in-project` for elpy with the help of hooks. But, shouldn't the user be given a choice on what to use instead of being forced to install said packages as dependencies ?

**Comment by jorgenschaefer** [comment]
> But, shouldn't the user be given a choice on what to use instead of being forced to install said packages as dependencies ?

As that would make life more difficult for those who want to use the default configuration – no, I think users can easily afford wasting a few kilobytes of hard drive and memory use.

**Comment by c02y** [comment]
> I use highlight-indent-guides and projectile-find-file to achieve the same functionality as the above mentioned packages. I feel highlight-indent-guides to be a superior alternative to highlight-indentation and I do not like the fact that elpy uses it as default.

+1

So do I, and I think `elpy` should only do the python things, `highlight-indent-guides` and `projectile-find-file` have nothing to do with Python programming.

**Comment by brotzeitmacher** [comment]
> As that would make life more difficult for those who want to use the default configuration – no, I think users can easily afford wasting a few kilobytes of hard drive and memory use.> 

In my opinion this is not the "emacs way". I think most users started with emacs, because they don't want to use a default configuration. I use company, but I don't see any reason why it has to be a dependency.

**Comment by jorgenschaefer** [comment]
> don't want to use a default configuration.

That's ok, you do not have to use Elpy! :-)

You can disable all extensions Elpy enables by default by configuring `elpy-modules`. A very quick look at the packages that come with Emacs by default will make it hard to argue that "the Emacs way" is to install only the most minimal set possible.

**Comment by brotzeitmacher** [comment]
I don't think the most minimal solution is the best, but elpy is kind of the opposite extreme. Don't get me wrong, elpy is one of the best emacs packages I know and I'm using most requirements myself. But I think most of them are personal preferences that shouldn't be included by default. This is probably the reason why anaconda is still being used by many users. Never mind. Thanks for the package!
