### ISSUE TITLE
Can't install elpy on Emacs26

### ISSUE THREAD

**Issue by moesy** [jorgenschaefer/elpy#1047]
When attempting to use elpy in emacs26 (ubuntu) I get the following error:
```(file-missing "Cannot open load file" "No such file or directory" "s")```

init.el
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("elpy" . "https://jorgenschaefer.github.io/packages/"))
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))

(package-initialize)
(elpy-enable)
```

I believe this is likely a version issue as I have no problems running the same config on my retina Macbook pro in an earlier version of emacs I have no issues.

**Comment by gopar** [comment]
Do you have the latest elpy version? There was a commit that fixed this issue

**Comment by moesy** [comment]
@gopar Do you mean by manually cloning the repo? I'm currently installing it by just adding the elpy link to package-archives.

**Comment by jorgenschaefer** [comment]
What's the output of `M-x elpy-config`?

**Comment by moesy** [comment]
@jorgenschaefer "Cannot open load file: No such file or directory, s "

**Comment by jorgenschaefer** [comment]
D'oh, of course. How did you install elpy? MELPA? Can you upgrade using the same method?

**Comment by moesy** [comment]
Ah good point however even when I refactor the init.el file to update before loading elpy with 
```(when (not package-archive-contents)
  (package-refresh-contents))
`` I get the same error.

**Comment by moesy** [comment]
@jorgenschaefer do you have any more suggestions as to what may be going on?

**Comment by jorgenschaefer** [comment]
@moesy Last time I asked whether you can upgrade to the latest version of Elpy. You can check the installed version in M-x list-packages, and you can upgrade by hitting U on the line with elpy in that list, and then x.

**Comment by brianjohnhaas** [comment]
I'm using GNU Emacs 26.2 and getting the same error:

"File is missing: Cannot open load file, No such file or directory, s"

and I'm using the latest code from 	git@github.com:jorgenschaefer/elpy.git

**Comment by galaunay** [comment]
If you get Elpy  from github, you have to install the dependencies manually.
Here is the list:
- company
- highlight-indentation
- pyvenv
- yasnippet
- s

I am closing this, but feel free to ping me here if it still doesn't work after installing `s` and others.
