### ISSUE TITLE
M-x pyenv-activate does not work

### ISSUE THREAD

**Issue by palbarede** [jorgenschaefer/elpy#1049]
Hello,

I  have just installed elpy on Emacs25 on MacOS X.  
The Python || Elpy mode works.

M-x elpy-config works and says 
"You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env."

However, M-x pyenv-activate and M-x pyvenv-workon do not exist.

After M-x package-install pyenv with I get commands pyenv-mode*  but no pyenv-activate or pyenv-workon.

How can I activate a virtual env as advised ?

Thanks.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. When installing Elpy from MELPA, the package `pyvenv` is installed as a dependency, which provides `pyvenv-activate` and `pyvenv-workon` (note the py-v-env, not py-env). How did you install Elpy? Is the `pyvenv` package installed?

**Comment by palbarede** [comment]
`note the py-v-env, not py-env`

That was my mistake.  I apologize and wish you the best.
