### ISSUE TITLE
Using Python 3.6

### ISSUE THREAD

**Issue by esteclobo** [jorgenschaefer/elpy#1051]
I can't set elpy to use python3.6 without making it not recognize Jedi, rope, importmagic, etc.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Could you please provide details, i.e. how exactly did you "set Elpy to use python3.6", and what was the output of `M-x elpy-config` then?

**Comment by esteclobo** [comment]
I'm sorry, was sleepy and didn't my question was so very badly formatted, barely put out any information.

Well, when I put the line `(setq elpy-rpc-python-command "python3")` in my`.emacs`, my `M-x elpy-config` displays:
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.0 (/usr/local/bin/python3)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.13.0
Jedi..............: Not found
Rope..............: Not found
Importmagic.......: Not found
Autopep8..........: Not found
Yapf..............: Not found
Syntax checker....: flake8 (/usr/local/bin/flake8)
```
My current python version as specified by `python3 --version` is 3.6

So, when insted I use `(setq elpy-rpc-python-command "python3.5")` to tell it to use python 3.5, the `elpy-config` displays

```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/usr/bin/python3.5)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.13.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.14.0
Syntax checker....: flake8 (/usr/local/bin/flake8)


```
And is all normal. Also, maybe it's important to say that I'm now facing other problem, every package I try to install with `pip3` i got an error `Can't connect to HTTPS URL because the SSL module is not available. - skipping`, and I think is also related to python 3.6, because `pip` works normally. But this problem I stated here happened before the SSL one, I even installed all those modules (jedi, rope,etc.) using pip3.

**Comment by gopar** [comment]
Hmm when  using pip, don't you specify which version you want? Like for py3.5 you would use pip3.5 and for py3.6 use pip3.6? Or am I completely wrong? Cause what I'm thinking is that pip3 points to pip3.5 and that's why it's not showing up when you check against py3.6

**Comment by jorgenschaefer** [comment]
Your python 3.6 installation can not find the respective modules. Make sure they are installed for that interpreter, not just for the 3.5 one. As gopar says, you might need to use the correct pip program there.

**Comment by esteclobo** [comment]
pip3.6 returns me the same SSL error. But yeah, if I get this fixed, it's problably going to work just fine. Thanks for the help.

**Comment by esteclobo** [comment]
All right, just solved the problem of pip3 and installed all the modules. I used `which python3` to see that my python3 path was actually `/usr/local/bin/python3`, and not `/usr/bin/python3`. Now it's all solved, thanks!!
