### ISSUE TITLE
Auto-completion not working despite installation of all dependencies verified

### ISSUE THREAD

**Issue by csheaff** [jorgenschaefer/elpy#1054]
Hello,

Autocompletion does not function for me despite the following printout from elpy-config. I've paid heed to the warning regarding my PATH, but I've verified ~/.local/bin has been added using

$echo $PATH
~/.local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Any assistance would be much appreciated.

-------------------------
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/usr/bin/python3)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.13.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.14.0
Syntax checker....: flake8 (/usr/local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH.
---------------------------

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Could you be a bit more specific with what "does not work" means? Does autocompletion not work at all, or just not for specific modules? Does manual autocompletion work, but idle suggestion does not?

Did you restart Emacs after changing your configuration, or at least run `M-x elpy-rpc-restart`?

When you open a new file, add `import json` and then in a separate line, `json.` and hit `M-TAB`, does that provide suggestions?

**Comment by csheaff** [comment]
Hi Jorgen,

Thanks for the response. So for example, if I create a list and search for it's methods using period-tab, no suggestions are made. It does appear that suggestions are provided for json, but it does not with other libraries such as numpy. Is additional configuration required for non-standard modules?

**Comment by jorgenschaefer** [comment]
If autocompletion works in general, but not in specific situations, the backend you are using could not find possible completions. Python being the dynamic language it is, it's not easy to guess possible completions. You can try the other backend by changing `elpy-rpc-backend`. You might also just be out of luck in those situations.

**Comment by csheaff** [comment]
Thanks Jorgen, changing the backend to jedi appears to have resolved my issues.
