### ISSUE TITLE
How do I get a similar completion with anaconda-mode？

### ISSUE THREAD

**Issue by honmaple** [jorgenschaefer/elpy#1056]
just like this
![_2017-01-04_10-58-23](https://cloud.githubusercontent.com/assets/12235570/21632562/975115c4-d282-11e6-832b-d38fb287d30f.png)

not just show **function** or **keyword**  

![_2017-01-04_11-40-09](https://cloud.githubusercontent.com/assets/12235570/21632583/b7969688-d282-11e6-8ea8-9e97b778fb03.png)

And sometime the completion list show error information like **deprecationWarning** rather than **DeprecationWarning**

My config:  
```
   (setenv "PYTHONPATH" "$PYTHONPATH:/usr/lib/python3.5/site-packages")
    (setq python-shell-completion-native-enable nil)
    (setq python-shell-interpreter "ipython"
          python-shell-interpreter-args "--simple-prompt -i")
    (remove-hook 'elpy-modules 'elpy-module-flymake)
    ;; (setq elpy-rpc-backend "jedi")
    ;; (remove-hook 'elpy-modules 'elpy-module-company)
    (setq shell-file-name "/bin/bash")
    (elpy-enable)
```

And elpy config
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 25.1.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.2 (1.2.4 available)
Yapf..............: 0.12.1 (0.14.0 available)
Syntax checker....: flake8 (/usr/bin/flake8)
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! There is currently no way to change the way Elpy displays possible completions I'm afraid.

As for the other one, I do not know how or when that happens. I've seen it before, and it seems to be a very rare problem in company-mode. If you manage to reproduce it reliably, a good bug report would be greatly appreciated. :-(
