### ISSUE TITLE
is there a way to specify pwd of interactive shell?

### ISSUE THREAD

**Issue by cnsgsz** [jorgenschaefer/elpy#1057]
When using elpy-shell-send-region-or-buffer and there is no existing python subprocess, will it be nice to start a new one with the directory of the file of the buffer (if exist) as the pwd? That way, more context seems to  get retained (e.g. relative paths in the buffer will be evaluated more naturally)?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Isn't this the default?

**Comment by cnsgsz** [comment]
It seems to be the directory of the 1st file evaluated. If I evaluate a 2nd file in a different directory (even if I kill the previous python subshell with ctrl-d), the pwd still seems to be from the 1st file.

**Comment by jorgenschaefer** [comment]
Yes, buffers have a working directory. Can you just kill the buffer (C-x k)?

**Comment by cnsgsz** [comment]
thanks, elpy works like a charm!
