### ISSUE TITLE
Failed to download `elpy' archive.

### ISSUE THREAD

**Issue by maxbeegee** [jorgenschaefer/elpy#1058]
Hello!
After following the installation instructions on the webpage and running `M-x package-refresh-contents` the following error message occurs:

> Failed to download `elpy' archive.

The output of ` openssl s_client -connect jorgenschaefer.github.io:443` ends with

> Verify return code: 0 (ok)

My emacs version is

> GNU Emacs 24.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.14.13) of 2015-10-07 on x86-019.build.eng.bos.redhat.com

Thanks for the help!

Best,
Max

**Comment by jorgenschaefer** [comment]
I do not know what the problem mit be. "Verify return code: 0 (ok)" does not sound too problematic to me. Have you tried again? Github was having some issues recently.

**Comment by maxbeegee** [comment]
Sorry. I fixed it.
It was due to another (unreachable) entry in the list  `package-archives`.
