### ISSUE TITLE
elpy-yapf-fix-code fails to find .style.yapf config in current directories

### ISSUE THREAD

**Issue by dangirsh** [jorgenschaefer/elpy#1062]
Adding a .yapf.style file in the directory of the file I'm formatting (or one of it's parent directories) has no effect on the formatting (the default style is used). The yapf docs mention that the ~/.config/yapf/style location is also searched. Moving my file there fixed the issue - now elpy-yapf-fix-code respects my configuration.

yapf version is 0.14.0
elpy version is 1.13.0
emacs version is 25.1.1

I checked that yapf has no issue finding config files when used directly via its cli.

**Comment by dangirsh** [comment]
Not that it should matter, but here's the config I tried:

```
[style]
based_on_style = google
split_before_first_argument = false
column_limit = 120
```

**Comment by ChillarAnand** [comment]
@dangirsh Thanks for submitting report. elpy currently doesn't `.yapf.style` config. I submit a patch for that.

**Comment by ChillarAnand** [comment]
I just verified that elpy/yapf do support  `.yapf.style` config. 

[For me](https://github.com/google/yapf/issues/360), yapf fails to find `.yapf.style` in current directories.

**Comment by ChillarAnand** [comment]
@dangirsh File should be named `.style.yapf`.
