### ISSUE TITLE
elpy-django not found in the package served by https://jorgenschaefer.github.io/packages/

### ISSUE THREAD

**Issue by 0x210F** [jorgenschaefer/elpy#1064]
A fresh install of elpy (version 1.14.0) from https://jorgenschaefer.github.io/packages/ does not include elpy-django.el file. melpa-stable serves the same 1.14.0 version of the package but it does include elpy-django. There may be other differences between the contents of the package served by the two archives.

**Comment by gnurenga** [comment]
# Compile-Log for the above issue
Leaving directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.0'

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.0/elpy-pkg.el at Wed Feb  1 06:53:50 2017
Entering directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.0/'

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.0/elpy-refactor.el at Wed Feb  1 06:53:50 2017

In end of data:
elpy-refactor.el:298:1:Warning: the following functions are not known to be defined: caddr,
    elpy-rpc, elpy-importmagic-fixup, elpy-autopep8-fix-code

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.0/elpy.el at Wed Feb  1 06:53:50 2017
elpy.el:47:1:Error: Cannot open load file: no such file or directory, elpy-django
Leaving directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.0/'

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.0/snippets/python-mode/.yas-setup.el at Wed Feb  1 06:53:50 2017
Entering directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.0/snippets/python-mode/'

In elpy-snippet-init-assignments:
.yas-setup.el:36:48:Warning: reference to free variable `start-point'

In elpy-snippet-super-form:
.yas-setup.el:59:70:Warning: reference to free variable
    `elpy-rpc-python-command'

**Comment by jorgenschaefer** [comment]
This should be fixed now, too. Can you confirm?

**Comment by gnurenga** [comment]
@jorgenschaefer Still compilation error is there

## emacs compile log

Leaving directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.1'

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.1/elpy-django.el at Wed Feb  1 19:26:56 2017
Entering directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.1/'

In elpy-django--get-commands:
elpy-django.el:117:87:Warning: `replace-regexp' is for interactive use only;
    use `re-search-forward' and `replace-match' instead.

In end of data:
elpy-django.el:171:1:Warning: the following functions are not known to be defined: -remove,
    elpy-project-root

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.1/elpy-pkg.el at Wed Feb  1 19:26:56 2017

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.1/elpy-refactor.el at Wed Feb  1 19:26:56 2017

In end of data:
elpy-refactor.el:298:1:Warning: the following functions are not known to be defined: caddr,
    elpy-rpc, elpy-importmagic-fixup, elpy-autopep8-fix-code

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.1/elpy.el at Wed Feb  1 19:26:56 2017
elpy.el:151:2:Warning: make-obsolete-variable called with 2 arguments, but
    requires 3-4
elpy.el:1105:1:Warning: Unused lexical argument `name'
elpy.el:1189:1:Warning: Unused lexical argument `event'
elpy.el:1362:1:Warning: Unused lexical variable `ffip-project-root'
elpy.el:1362:1:Warning: Unused lexical variable `ffip-prune-patterns'

In elpy-use-ipython:
elpy.el:1515:11:Warning: `python-shell-completion-module-string-code' is an
    obsolete variable (as of 24.4); use `python-shell-completion-string-code'
    instead.
elpy.el:1530:51:Warning: assignment to free variable `+'

In elpy-use-cpython:
elpy.el:1576:11:Warning: `python-shell-completion-module-string-code' is an
    obsolete variable (as of 24.4); use `python-shell-completion-string-code'
    instead.

In elpy-shell-kill-all:
elpy.el:1671:11:Warning: reference to free variable `for'
elpy.el:1671:15:Warning: reference to free variable `buffer'
elpy.el:1671:22:Warning: reference to free variable `being'
elpy.el:1671:28:Warning: reference to free variable `the'
elpy.el:1671:32:Warning: reference to free variable `buffers'
elpy.el:1671:40:Warning: reference to free variable `do'
elpy.el:1688:28:Warning: reference to free variable `in'
elpy.el:1743:1:Warning: Lexical argument shadows the dynamic variable mode-name
elpy.el:1976:1:Warning: Unused lexical argument `count'
elpy.el:1988:1:Warning: Unused lexical argument `count'
elpy.el:2089:1:Warning: Lexical argument shadows the dynamic variable top-level
elpy.el:2116:1:Warning: Unused lexical argument `file'
elpy.el:2131:1:Warning: Unused lexical argument `file'
elpy.el:2159:1:Warning: Unused lexical argument `file'
elpy.el:2176:1:Warning: Unused lexical argument `file'
elpy.el:2218:1:Warning: Unused lexical variable `symbol-at-point'

In elpy-importmagic-fixup:
**elpy.el:2358:24:Error: `add-to-list' can't use lexical var
    `unresolved-aliases'; use `push' or `cl-pushnew'**
elpy.el:2363:23:Warning: `format' called with 2 args to fill 1 format field(s)
elpy.el:2456:1:Warning: Unused lexical argument `pre-change-length'
elpy.el:2456:1:Warning: Unused lexical argument `end'
elpy.el:2456:1:Warning: Unused lexical argument `beg'
elpy.el:2539:1:Warning: Unused lexical argument `value'
elpy.el:2931:1:Warning: Unused lexical argument `call-id'
elpy.el:2949:1:Warning: Unused lexical argument `err'
elpy.el:3336:1:Warning: Lexical argument shadows the dynamic variable mode-name
elpy.el:3359:1:Warning: Unused lexical argument `args'
elpy.el:3374:1:Warning: Unused lexical argument `args'

In elpy-module-company:
elpy.el:3380:18:Warning: reference to free variable `company-active-map'
elpy.el:3403:28:Warning: assignment to free variable `company-idle-delay'
elpy.el:3391:11:Warning: assignment to free variable
    `company-tooltip-align-annotations'
elpy.el:3390:33:Warning: assignment to free variable
    `company-dabbrev-code-everywhere'
elpy.el:3399:54:Warning: reference to free variable `company-backends'
elpy.el:3405:28:Warning: assignment to free variable `company-backends'

In elpy-company-backend:
elpy.el:3572:36:Warning: reference to free variable
    `company-minimum-prefix-length'
elpy.el:3631:1:Warning: Unused lexical argument `args'

In elpy-eldoc-documentation:
elpy.el:3681:7:Warning: reference to free variable `eldoc-last-message'
elpy.el:3686:1:Warning: Unused lexical argument `args'

In elpy-module-flymake:
elpy.el:3696:20:Warning: reference to free variable
    `flymake-allowed-file-name-masks'
elpy.el:3696:20:Warning: assignment to free variable
    `flymake-allowed-file-name-masks'
elpy.el:3725:28:Warning: assignment to free variable
    `flymake-no-changes-timeout'
elpy.el:3712:11:Warning: assignment to free variable
    `flymake-start-syntax-check-on-newline'
elpy.el:3730:30:Warning: assignment to free variable `flymake-warning-re'
elpy.el:3777:1:Warning: Unused lexical argument `args'
elpy.el:3790:1:Warning: Unused lexical argument `args'
elpy.el:3801:1:Warning: Unused lexical argument `args'

In elpy-module-yasnippet:
elpy.el:3812:24:Warning: reference to free variable `yas-snippet-dirs'
elpy.el:3813:37:Warning: assignment to free variable `yas-snippet-dirs'
elpy.el:3834:1:Warning: Unused lexical argument `args'
elpy.el:3870:1:Warning: Unused lexical argument `dedicated'
elpy.el:3878:5:Warning: reference to free variable `python-python-command'
elpy.el:3880:1:Warning: Unused lexical argument `arg'
elpy.el:3947:17:Warning: reference to free variable `highlight-indent-active'

In end of data:
elpy.el:3956:1:Warning: the following functions are not known to be defined:
    projectile-project-root, loop, company-begin-backend,
    company-in-string-or-comment, company-grab-symbol-cons,
    company-doc-buffer, eldoc-message,
    flymake-init-create-temp-buffer-copy, flymake-goto-next-error,
    flymake-goto-prev-error, flymake-find-err-info, flymake-ler-text,
    yas-reload-all, python-send-buffer, highlight-indentation
Leaving directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.1/'

Compiling file /home/rengaraj/.emacs.d/elpa/elpy-1.14.1/snippets/python-mode/.yas-setup.el at Wed Feb  1 19:26:56 2017
Entering directory `/home/rengaraj/.emacs.d/elpa/elpy-1.14.1/snippets/python-mode/'

In elpy-snippet-init-assignments:
.yas-setup.el:36:48:Warning: reference to free variable `start-point'

In elpy-snippet-super-form:
.yas-setup.el:59:70:Warning: reference to free variable
    `elpy-rpc-python-command'

**Comment by jorgenschaefer** [comment]
This is a different error. Thanks for notifying me about it.

**Comment by jorgenschaefer** [comment]
The latter is now dixed in master

**Comment by 0x210F** [comment]
Thanks!
