### ISSUE TITLE
Package s new in elpy 1.14.0

### ISSUE THREAD

**Issue by brandm** [jorgenschaefer/elpy#1066]
Hi Jorgen

First thank you very much for your effort dedicated to this very useful project!

My question: Isn't the package archive
https://jorgenschaefer.github.io/packages
supposed to provide all dependencies for elpy self-included? Trying to upgrade with the elpy installation instructions from elpy 1.13.0 to 1.14.0 resulted in "Package s-1.10.0 is unavailable" (package s: "The long lost Emacs string manipulation library").

Michael

**Comment by jorgenschaefer** [comment]
Thank you for the report! Could you check if this works now?

**Comment by letuananh** [comment]
I checked just now on Emacs 25.1.1. It works. Thanks a lot for your efforts 👍

**Comment by jorgenschaefer** [comment]
Great, thank you for checking! :-)

**Comment by brandm** [comment]
Same here, package s is now also in the description at the end of ~/.emacs.d/elpa/archives/elpy/archive-contents. Thanks for the quick fix.
