### ISSUE TITLE
Make elpy-rpc-python-command wiser?

### ISSUE THREAD

**Issue by hongxuchen** [jorgenschaefer/elpy#107]
Some Python developers are using both Python2 and Python3, but elpy seems cannot recognize shebang line in Python script to use the right interpreter specified by `elpy-rpc-python-command`. 
Is it possible to make `elpy-rpc-python-command` buffer local and defaults to the value shebang specifies?

**Comment by galaunay** [comment]
If it is still relevant, the RPC python version doesn't need to be the same as the python version you are working with.
I would recommend setting the rpc to python3. It will work whatever the python version of your projects.
