### ISSUE TITLE
Warn when disabling completion due to buffer size

### ISSUE THREAD

**Issue by teoric** [jorgenschaefer/elpy#1073]
Would it be possible to emit a warning if the buffer ist so large that completion does not work?  It took me surprisingly long to find the reason why `elpy` worked in some files but not others. It would have been enough to get something like `Buffer larger than elpy-rpc-ignored-buffer-size -- disabling completion`.  

The variable does not appear to be [in the docs](http://elpy.readthedocs.io/en/latest/), either, it's only in the NEWS.

(Cannot have a look right now, but might look into a pull request if you don't beat me to it.)

**Comment by gopar** [comment]
Should this issue be closed?  PR is already merged.

**Comment by jorgenschaefer** [comment]
Thanks for noticing :-)
