### ISSUE TITLE
wrong highlighting with flake8

### ISSUE THREAD

**Issue by djbajic** [jorgenschaefer/elpy#1075]
Hi, 

I am having an issue with highlighting python code when flake8. For example, this is how I see it with **flake8 not installed**:
![image](https://cloud.githubusercontent.com/assets/20704857/22832978/217c03fe-ef7e-11e6-84c2-524de3686c27.png)

and this is with **flake8 installed**:
![image](https://cloud.githubusercontent.com/assets/20704857/22833032/5cdf802e-ef7e-11e6-8486-60c20907d484.png)

The mode line says only python (not python || elpy as it should, I think), but elpy is enabled I think, as variable python-mode-hook is:
python-mode-hook is a variable defined in 'python.el'.
Its value is ((lambda nil
   (set
    (make-local-variable 'yas-indent-line)
    'fixed))
 elpy-mode)`

Currently, my Elpy Configuration is:

Virtualenv........: None
RPC Python........: 2.7.12 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.14.1
Jedi..............: 0.10.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.16.0
Syntax checker....: Not found (flake8)

Thanks a lot for any help!

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. This looks like flake8 is trying to tell you that there's a problem with your code. Have you moved point ontop of those lines and checked the echo area? It should say something like "should have two lines between imports and code" or something. You can also use `C-c C-v` for a full listing of all problems.

**Comment by djbajic** [comment]
OK, did not know that flake8 does indeed highlight style errors. Fancy feature. Thanks a lot for the help.
