### ISSUE TITLE
 elpy-rpc--default-error-callback

### ISSUE THREAD

**Issue by fisgithub** [jorgenschaefer/elpy#1083]
Here is the error displayed on messages:
```
error in process sentinel: elpy-rpc--default-error-callback: peculiar error: "segmentation fault (core dumped)"
error in process sentinel: peculiar error: "segmentation fault (core dumped)"
```
An here is the config:
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/usr/bin/python3)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 25.1.1
Elpy..............: 1.14.1
Jedi..............: 0.10.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.16.0
Syntax checker....: flake8 (/usr/bin/flake8)
```
The error occurs in the following situations, all of them involve auto completion:
When try to use import, like `from foo import module`.
When try to use `foo.function`.
When try to use keyword parameters, like `func(kargs=par)`.

I don't know if it has anything to do with the error, I use company mode to do auto completion. The same error occurs in the previous versions of elpy too (Sorry, I can't name the last working version).
The information I provide here might not be enough, anything else I can do to help?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Can you deinstall importmagic and see if that fixes the problem?

importmagic imports all packages you have installed, and with some packages written in C, simply importing them can trigger bugs, causing such a segfault …

**Comment by fisgithub** [comment]
Wow, that works. 
Thanks for the help. Your work is great.

**Comment by jorgenschaefer** [comment]
Glad it works. It's a bit annoying that importmagic causes such problems, but it's difficult to avoid when doing what it does … In any case, enjoy Elpy! :-)
