### ISSUE TITLE
Elpy-doc completion breaks with ivy

### ISSUE THREAD

**Issue by jmercouris** [jorgenschaefer/elpy#1084]
**To replicate:**

M-x ivy-mode
M-x elpy-doc

type: 'datetime' + TAB, or try to expand to datetime.datetime, and you will find that you cannot. You can still type the full string 'datetime.datetime', and retrieve results, but somehow elpy-doc is not giving the appropriate readline info to ivy for completion after the first chunk of text. Similar behavior has been observed for helm as well.

**Possible solutions:**

- hook to enable and disable ivy-mode, or helm when calling elpy-doc
- force ido-mode in elpy-doc somehow

**Comment by drym3r** [comment]
I'll just add that it happens to me, as well.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Why do you think this is a problem that Elpy should fix, and not, ivy-mode? Elpy seems to work fine?

**Comment by jmercouris** [comment]
I believe it to be that helm and ivy are using standard interfaces for interacting with completion, so I guess elpy-doc should be utilizing these, I can't be sure. One of the greater motivations for reporting here was due to your responsiveness

**Comment by drym3r** [comment]
I also don't know if helm and ivy use standard interfaces, but none of them work, so if is not an elpy related issue, it is related to both helm and ivy.

**Comment by jorgenschaefer** [comment]
`elpy-doc` uses `completing-read` with dynamic completion tables, a standard interface in Emacs (see `elpy-doc--read-identifier-from-minibuffer`). Both ivy and helm interfere with this standard interface to provide a different completion interface. I'm quite happy to add code to improve the use of the standard interface of Emacs, but I'm not willing to add code to cater to non-standard completion packages implementing standard facilities badly …

**Comment by jmercouris** [comment]
well, I wouldn't say the are implementing standard facilities badly, almost literally every other function in emacs works with completion via ivy. though I understand your hesitation to include anything not standard/core to emacs. In the interim, do you know of a workaround to wrap elpy-doc? e.g. force a completion mechanism just for elpy-doc? maybe I should write a mini function that turns ivy on and off before/after calling elpy-doc?

**Comment by jorgenschaefer** [comment]
You could try an around-advice? I'm afraid I do not know ivy, and only use helm for very specific functions, so I do not know how to disable them for the parts of Emacs that they do not work with.

**Comment by jmercouris** [comment]
I'll keep you updated if I come up with anything, thanks for your help

**Comment by jmercouris** [comment]
issue opened in ivy: https://github.com/abo-abo/swiper/issues/892

**Comment by abo-abo** [comment]
> elpy-doc uses completing-read with dynamic completion tables, a standard interface in Emacs

In my opinion, dynamic completion tables are a goofy interface that add an unnecessary layer of indirection.

> Similar behavior has been observed for helm as well.

Both helm and ivy sometimes have difficulty with this interface, because it often assumes that the default completion is being used.

I suggest to migrate to the collection as a function interface:

```elisp
(defun elpy-doc--read-identifier-from-minibuffer (initial)
  "Read a pydoc-able identifier from the minibuffer."
  (completing-read "Pydoc for: "
                   (lambda (str pred _)
                     (elpy-rpc-get-pydoc-completions str))
                   nil nil initial 'elpy-doc-history))
```

The above approach is better for introspection as well, provided `elpy-rpc-get-pydoc-completions` can be called in place of the lambda wrapper.

**Comment by jmercouris** [comment]
I'm not sure I understood all of your response, but I put it in a buffer and eval'd it, it did substitute the function, but no improvement in behavior was observed

**Comment by jorgenschaefer** [comment]
No, `elpy-rpc-get-pydoc-completion` does not follow the function interface of `completing-read` because that requires also knowing about buffer positions. That's what completion tables are for, goofy or not.

If you do not implement the full interface of the functionality you replace in core Emacs, I would suggest you to provide a way for your users to disable your mode where it breaks.

**Comment by jorgenschaefer** [comment]
(`completion-table-dynamic` returns a function, incidentally.)

**Comment by abo-abo** [comment]
> No, elpy-rpc-get-pydoc-completion does not follow the function interface of completing-read because that requires also knowing about buffer positions. That's what completion tables are for, goofy or not.

I prefer the `completion-at-point-functions` interface, along with `complete-symbol` for this. Works great with `helm` and `ivy` since you can scroll through the candidates and each time you scroll, the old code is removed from the buffer and the new one is inserted.

**Comment by jorgenschaefer** [comment]
I have to admit, "adheres to the interface preferred by the author of ivy" is not exactly high up on my list of reasons for choosing certain APIs over others.

**Comment by jmercouris** [comment]
There's no need to escalate this, let's all remain calm :D 
we don't need these kinds of wars within the community itself :)
we're on the same team here

**Comment by abo-abo** [comment]
@jorgenschaefer Just making a suggestion to improve your package. The alternative for your users is to employ crutches that turn off their preferred completion type, just because you're being suborn.

**Comment by jorgenschaefer** [comment]
Suggested solution to this problem: Use helm instead of ivy, as helm allows disabling the package where it does not implement the APIs it replaced correctly.
