### ISSUE TITLE
pyvenv-activate doesn't keep changes to PATH environment variable in emacs session

### ISSUE THREAD

**Issue by PatternMatching** [jorgenschaefer/elpy#1086]
Elpy version: 1.14.1
Emacs version: 25.1.1
OS: Windows 7

Upon startup of emacs, I use setenv to prepend an entry to my PATH environment variable:

    (setenv "PATH" (concat "C:\\MinGW\\msys\\1.0\\bin" ";" (getenv "PATH")))

When I go to activate a virtualenv using pyvenv-activate, the change made at startup does not propagate to the resulting path with virtualenv prepended.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is some unlucky interaction between various features in Emacs … Emacs uses the `exec-path` variable to look for executables. It is initialized from `PATH` on startup. pyvenv uses this variable to set the PATH for subprocesses. I suspect it should use `PATH` for that … hm. Fascinating. :-)

**Comment by jorgenschaefer** [comment]
I just pushed a commit to pyvenv that should fix this – once MELPA updates, or if you use the Elpy repo already now, you should be able to install pyvenv 1.10. Could you see if that fixes the problem?

**Comment by PatternMatching** [comment]
Thanks Jorgen!  I will test this out ASAP.  Really appreciate the quick turnaround...

**Comment by PatternMatching** [comment]
Looks great!  PATH is in tact as I would expect!  Thanks again.
