### ISSUE TITLE
No more autu-completition when using python3

### ISSUE THREAD

**Issue by ChrisDaumer** [jorgenschaefer/elpy#1089]
Hi, 
Thanks for all the work !
When I use elpy with starting configuration it works (that is to say with python 2)
Then I set it up for python 3, using:
(setq elpy-rpc-python-command "python3")
And auto-completition doesn't work anymore.

Any ideas ?

**Comment by gopar** [comment]
Hey :)

Did you install the required packages for python3? What is most likely happening here is that you have the required packages installed for python2 but not for python3. When you do `pip install ....` make sure that it's pip3.x and not pip2. I believe you can check by doing `pip --version`.

**Comment by gopar** [comment]
You can also run `M-x elpy-config` and choose the option where elpy will install the packages for you \o/

**Comment by ChrisDaumer** [comment]
YES it works ! thanks a lot :dancing_men:

**Comment by gopar** [comment]
Looks like you accidentally re-opened the issue. Mind closing it? :)
