### ISSUE TITLE
elpy ipython interactive buffer 'historical' auto-complete

### ISSUE THREAD

**Issue by marty0801** [jorgenschaefer/elpy#1091]
Jorgen,

Your elpy is wonderful! I have a small wrinkle...Ipython has the nice feature that typing the beginning of a previously executed command, followed by the 'up' arrow, will automatically complete to consistent historical commands. This doesn't function in my emacs. Using the 'comint-previous-input' (bound to M-p) simply rotates through all previous commands.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Ipython provides a lot of interactive commands when run in an actual terminal emulator. Emacs' normal comint mode does not provide full terminal emulation, so these features do not work. You have a few options there. First, you can just use `C-r` and search for a previous command in the Emacs buffer – hitting `RET` on a previous input will execute it again. Second, you can try `M-x comint-previous-matching-input`, which will let you enter a regexp. You can of course bind this to a key. Third, you can reimplement the functionality you describe in comint. And fourth, you can just use ipython in an external terminal emulator. You lose the integration with Emacs, but you gain all the interactive functionality of ipython.

I do realize that none of these is ideal. Hope you can find something that's "good enough", though :-)

**Comment by marty0801** [comment]
Thanks for the suggestion! C-r works perfectly--not sure why I didn't think of this before...
