### ISSUE TITLE
Encoding error during file execution

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [jorgenschaefer/elpy#1096]
I have posted [a question on Emacs StackExchange](http://emacs.stackexchange.com/questions/31282/executing-python-with-encoding-error-in-emacs-not-in-terminal), but am also linking it here to maybe get a second opinion.

The issue is encoding during file execution using Elpy in Emacs 24.5.1.  I do not get the issue when performing exactly the same command in Terminal directly.

I think it is an Emacs issue, rather than Elpy specific, so please feel free to simply remove this issue if nobody has any input. I just thought it might be something that Elpy could address, assuming a solution is found. Or perhaps it is already solved somehow with Elpy, and I just don't know about it??

**Comment by Nicholas-Mitchell** [comment]
In my post on Emacs StackExchange above, I have posted the answer I eventually found.

Stick some encoding defaults into you `.emacs` file (or export them for your terminal as necessary):

    I tried a solution [proposed here][2] for a UnicodeDecodingError, did work:

    (setenv "LANG" "en_US.UTF-8")
    (setenv "LC_ALL" "en_US.UTF-8")
    (setenv "LC_CTYPE" "en_US.UTF-8")

I only actually required the first of the three lines.

Another possibility:

    (setenv "PYTHONIOENCODING" "utf-8")

**Comment by jorgenschaefer** [comment]
Nice detective work, thank you for this! :-)
