### ISSUE TITLE
Shell native completion is disabled, using fallback

### ISSUE THREAD

**Issue by mambolevis** [jorgenschaefer/elpy#1104]
I built emacs-25.2-rc2 with release flags. When using `elpy-shell-send-region-or-buffer` the following Message appears:
`Shell native completion is disabled, using fallback`

I also tested `emacs-25.2-rc2` from `Index of /gnu/emacs/pretest/windows` and the same message is shown.

**Comment by jorgenschaefer** [comment]
Thank you for the report. As you know, we already have an issue for this at #887, and I still would like to keep the discussion about this Emacs bug in a single location, so please comment there.
