### ISSUE TITLE
C-c C-d (elpy-doc) and pydoc

### ISSUE THREAD

**Issue by brandm** [jorgenschaefer/elpy#1105]
Hi

`C-c C-d` `(elpy-doc)` on a call of a function defined in the same module displays its docstring as expected:

```
Documentation for my_module.my_func:

my_func()

My function.
```

`C-c C-d` on `print` displays the header without docstring:

```
Documentation for print:
```

The following is happening in the `print` case: `elpy-rpc-get-docstring` in `elpy-doc` returns non-`nil` and therefore `elpy-doc` does not reach `elpy-rpc-get-pydoc-documentation`. When I override `elpy-rpc-get-docstring` to `nil` as a temporary experiment the expected docstring for `print` is displayed.

elpy: 1.14.1, jedi: 0.10.0, rope: not installed, (Python: 3.4.5 or 3.6.0).

Am I doing something wrong?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report (and nice debugging!) – the "problem" here is that Elpy relies on the backend (Jedi or Rope) to give good documentation results. Only if the backend does not give any documentation will Elpy try and fall back to using pydoc (which can easily fail). In your case, apparently the documentation from the backend is worse than the pydoc one, but Elpy has no way of knowing that that is the case.

A workaround might be to use `C-u C-c C-d` – this will force pydoc usage, but also prompt for the symbol first. So this needs another `RET`.

Does this help?

**Comment by brandm** [comment]
The workaround helps, thanks.

I would prefer if the fallback mechanism that already exists in `elpy` would also work for `print`. It seems like Elpy and/or the backend does not comply to their interface definition for this case. Depending on this interface definition this code

```elisp
(when (and doc (string= ""
                        ;; Reduce doc to content below its header.
                        (replace-regexp-in-string
                         "\\(.*?\n\\).*" "" doc nil nil 1)))
  (setq doc nil))
```

placed in `elpy-doc` after the first `(setq doc (elpy-rpc-get-docstring))` is a first approach for the desired behaviour. In my case with Jedi as backend it works as expected. Is there a way in this direction or maybe better into the direction of changing Jedi and if necessary also Rope to say sorry, no doc for `print`?

**Comment by jorgenschaefer** [comment]
So you ignore the documentation from the backend if it's only a single line? That seems like a weird heuristic.

Wouldn't it make more sense to improve the backend to provide better documentation?

**Comment by brandm** [comment]
> So you ignore the documentation from the backend if it's only a single line? That seems like a weird heuristic.

For a first approach to ignore a header without a single following line, yes. I don't consider the current
```
Documentation for print:
```
from Jedi a documentation or in any other way helpful.

> Wouldn't it make more sense to improve the backend to provide better documentation?

Probably yes.

Not sure if you want to keep the current issue open, otherwise please just close it.

**Comment by jorgenschaefer** [comment]
Yeah, this seems to be a problem in Elpy's jedi backend, actually. Looking at [the source](https://github.com/jorgenschaefer/elpy/blob/master/elpy/jedibackend.py#L70-L74), I suspect that check needs to be a bit more elaborate. `docstring()` for print returns an empty string. If you change line 70 to `if locations and locations[-1].docstring():`, does that exhibit the behavior you expect?

**Comment by brandm** [comment]
> I suspect that check needs to be a bit more elaborate. docstring() for print returns an empty string. If you change line 70 to if locations and locations[-1].docstring():, does that exhibit the behavior you expect?

You are right. Yes it does.

**Comment by jorgenschaefer** [comment]
Great! Should be fixed in the next release, then :-) Thank you for the report and the debugging!

**Comment by brandm** [comment]
Thank you for the fix.
