### ISSUE TITLE
Junk character issue in Emacs 25.1

### ISSUE THREAD

**Issue by rsuhada** [jorgenschaefer/elpy#1106]
I've updated to Emacs 25.1 and freshly installed elpy from melpa.
Now I'm getting junk characters:

```
> Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 5.3.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> [JIn [1]: print("hello")[22D
> [Jhello
> 
> [6n[JIn [2]: [8D[8C[8D[J[6n[JIn [2]: [8D[8C[8D[J[6n[JIn [2]: [8D[8C[8D[J[6n[JIn [2]: [8D[8C[8D[J[6n[JIn [2]: [8D[8C[8D[J[6n[JIn [2]: [8D[8C[8D[JIn [2]: print("hello")[22D
```

Here is my `elpy-config`:

> Elpy Configuration
> 
> Virtualenv........: None
> RPC Python........: 2.7.10 (/usr/bin/python)
> Interactive Python: ipython (/usr/local/bin/ipython)
> Emacs.............: 25.1.1
> Elpy..............: 1.14.1
> Jedi..............: 0.9.0 (0.10.0 available)
> Rope..............: 0.10.5
> Importmagic.......: Not found (0.1.7 available)
> Autopep8..........: Not found (1.3.1 available)
> Yapf..............: Not found (0.16.1 available)
> Syntax checker....: Not found (flake8)

This happens for local shell (ipython). For remote shell I get the "no prompt detected" error...

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! These are terminal control characters IPython sends to manipulate the prompt etc. I do not know why this happens to you but not others. IPython should detect `TERM` being "dumb" and not try this.

Does `(setq ansi-color-for-comint-mode t)` help?

Does disabling IPython and just using normal Python help?

**Comment by rsuhada** [comment]
Just an update - Emacs 25.1 is a red herring - I've reverted back to 24.5 and I'm getting the same junk characters... :(

**Comment by rsuhada** [comment]
Normal python works. ansi-color-for-comint-mode doesn't help.
I've just noticed that on initial contact to ipython I get these messages:

> Making python-shell-interpreter local to *Python* while let-bound!
> Making python-shell-interpreter-args local to *Python* while let-bound!
> Sent python-shell-completion-setup-code
> Sent python-ffap-setup-code
> Sent python-eldoc-setup-code

Is this expected (I don't know, never noticed this before)?

**Comment by jorgenschaefer** [comment]
More or less expected, yes. At least, unrelated to this problem.

**Comment by rsuhada** [comment]
I'm a bit confused about what is going on... I was using Emacs 24.5 and my eply was from Melpa (elpy-20170303.621) and everything worked splendidly: python/ipython/pyspark on both local and remote machines. 

After update to Emacs 25.1 only python works. Even if I replace my elpa/ directory with the previous one and go back to 24.5, ipython and pyspark don't work anymore. This is odd and possibly has actually nothing to do with elpy?

It would be a huge loss for my work if I could no longer use elpy with pyspark on remotes... despite the great improvements with use-package etc. upgrading emacs or the packages always comes with a lot of pain for me... (this of course has nothing to do with elpy specifically :) just a lamentation of a tired emacs user)

**Comment by jorgenschaefer** [comment]
I'm afraid I have no idea what might be going wrong here :-( You could try removing the .emacs.d/elpa directory and reinstalling all packages.

**Comment by RobinTournemenne** [comment]
the problem comes from ipython 5, you have to add this line in your init emac file:
(setq  python-shell-interpreter-args "--simple-prompt -i")

Source: https://emacs.stackexchange.com/questions/24453/weird-shell-output-when-using-ipython-5

**Comment by galaunay** [comment]
Thanks @RobinTournemenne, it has been added to elpy documentation last month.
Just waiting for python-mode to catch up now I guess.

I think we can close this now.
