### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mambolevis** [jorgenschaefer/elpy#1111]
My current elpy-config look like this:
```
Virtualenv........: None
RPC Python........: 3.5.2 (c:/Anaconda3/envs/py35/pythonw.exe)
Interactive Python: ipython (c:/Anaconda3/envs/py35/Scripts/ipython.exe)
Emacs.............: 25.2.1
Elpy..............: 1.14.1
Jedi..............: 0.10.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.7
Autopep8..........: 1.3.1
Yapf..............: 0.16.1
Syntax checker....: flake8.exe (c:/Anaconda3/envs/py35/Scripts/flake8.exe)
```
As you see, the only parameter pending for configuration is  `Virtualenv`

1 . Could you explain me how to configure Virtualenv in elpy?
2. Do you have any recommendation or advice when working with Virtualenv and elpy?

Thanks,
Grüß

**Comment by jorgenschaefer** [comment]
> 1 . Could you explain me how to configure Virtualenv in elpy?

`M-x pyvenv-activate` or `M-x pyvenv-workon` :-)

> 2. Do you have any recommendation or advice when working with Virtualenv and elpy?

Do it the same way you do it without Elpy. There should be no difference to the normal workflow.

**Comment by mambolevis** [comment]
In my workflow, I activate an Anaconda environment `(c:/Anaconda3/envs/py35/pythonw.exe)` using 
a batch file before lunching emacs (in the same batch file). 

Question:
Is it necessary to setup a variable with the path to the `(c:/Anaconda3/envs/py35/pythonw.exe)` before using `M-x pyvenv-activate `or `M-x pyvenv-workon`?
Thanks

**Comment by jorgenschaefer** [comment]
I do not know what "activating an Anaconda environment" entails. If you do not use standard methods for virtualenvs, you should not be surprised if Elpy fails to know what you are doing.

You need to set `elpy-rpc-python-command` and `python-shell-interpreter` to a command that runs the python program you want to use. How you do that is up to you. Using pyvenv is a common, easy solution, but certainly not required.

**Comment by mambolevis** [comment]
`I do not know what "activating an Anaconda environment" entails. If you do not use standard methods for virtualenvs, you should not be surprised if Elpy fails to know what you are doing.`
- In fact Elpy is working fine in my workflow with anaconda, I am very happy with the Package. Nonetheless, I would like to use the standard methods for virtualenvs.  When you said standard methods it means the setup of `elpy-rpc-python-command` and `python-shell-interpreter`, or do you mean something else?

- I would like to take advantage as much as possible of elpy. Can you send me a link to a python project that take advantage of all/many elpy capabilities?

Gruß!

**Comment by jorgenschaefer** [comment]
The standard method of using virtualenvs is the same as `M-x pyvenv-workon` or `M-x pyvenv-activate`. This does not require changing anything else, and does not require batchfiles before starting Emacs.

You can read about best practices for Python here: http://python-guide.readthedocs.io/en/latest/
