### ISSUE TITLE
tab to indent dwim

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#1112]
It should be quite easy to calculate that it is not possible to go "deeper" than 1 more level, so should it not be possible to cycle then instead of allowing to make deeper indentation?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! I do not understand what you are asking for. Could you describe more clearly 1) what exactly you are doing, 2) what exactly you expect to happen, and 3) what exactly is actually happening? Thanks!

**Comment by kootenpv** [comment]
Tab width in spaces is 4.

You use tab to indent elpy right. 

When you are tabbing 10 times, you are 40 spaces deep. When you are at top level this does not make sense. In fact, it is a syntax error to be 8 spaces (2 levels) deeper than a current level. 

Proposal: enable cycling/wrapping around a sentence 

Have indenting go back to a reasonable indentation level when impossible. 

I actually got the idea from emacs Haskell; they underline and cycle through a context dependent usually 3 levels or so. 

Did that clarify? If not I could make a gif.

**Comment by jorgenschaefer** [comment]
> When you are tabbing 10 times, you are 40 spaces deep.

When I hit `TAB` in an empty Python file, nothing happens. Have you tried this with a minimal setup? Maybe there is a misconfiguration at your end?

**Comment by kootenpv** [comment]
@jorgenschaefer My apologies, forgot to mention that I have the following setup:

- `TAB` is bound to `py-shift-right`
- `S-TAB` is bound to `py-shift-left`

**Comment by kootenpv** [comment]
Added a screenshot of just pressing TAB in haskell mode:

![cycle_tab](https://cloud.githubusercontent.com/assets/2746227/25042902/159ed92e-211c-11e7-885c-b9806d60f7d2.gif)

**Comment by jorgenschaefer** [comment]
> Still, I would say it makes even more sense to have a cycling indentation.

I fully agree. That's why that is the default. You change the default in your configuration. If you do not like that, do not change the default.

**Comment by kootenpv** [comment]
Wow! I never noticed that that is the default behavior by having it masked from before elpy. I've been looking for an elpy command that could potentially do it, but I noticed it is `py-indent-or-complete` that does it. What a great functionality :)

Thanks a lot for the follow up.

**Comment by jorgenschaefer** [comment]
Glad this works for you :-)

**Comment by potholiday** [comment]
I am also facing the same  problem. I want to use tab form moving 4 spaces what should I do.  What should I do with `py-indent-or-complete`.  I added in my init.el file my nothing happened
