### ISSUE TITLE
Elp: readline & inline plots

### ISSUE THREAD

**Issue by temok-mx** [jorgenschaefer/elpy#1113]
Dear Jorgen, 

When I run a python script within Emacs on Elpy-mode and python-mode, using `C-c C-c`,  I get the following warning,
> Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 

I wonde if this is related to Elpy.  If not, would you mind giving me some pointers to clean up this warning?

Also: if a python script that produces plots is run within Emacs (`C-c C-c`), then the plots pop up in a separate window. Is it possible to have this plots displayed "inline"? 

Thank you,
Temok

**Comment by jorgenschaefer** [comment]
The first is a bug in Emacs which should be fixed now, and the next release of Elpy should also enable some workarounds.

The latter is expected. You can try [ein](https://tkf.github.io/emacs-ipython-notebook/) for better integration with IPython.

**Comment by temok-mx** [comment]
Thank you Jorgen!

**Comment by saltycraig** [comment]
Was this ever fixed (or workarounds enabled)? I still get this warning on Windows every I run C-c C-z the first time, and I'd like to get rid of the warning.
