### ISSUE TITLE
Autocomplete constants is appending logical operators at the end

### ISSUE THREAD

**Issue by gshellikeri** [jorgenschaefer/elpy#1115]
Hi,

Thanks for all your work on elpy. It is a pleasure to use!
I am seeing that autocomplete wants to change my constants by appending logical operators at the end. I have attached a screenshot of this happening. This is very bothersome to say the least!

![screen shot 2017-04-06 at 2 47 06 pm](https://cloud.githubusercontent.com/assets/1213796/24776916/d5d1d7f0-1ad7-11e7-9e65-143f75361184.png)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Yes, this looks really weird. I have seen this before, but I have not been able to reproduce it. It does not always happen to me. Have you tried `M-x elpy-rpc-restart` to see if that fixes it?

**Comment by lgp171188** [comment]
I ran `M-x elpy-rpc-restart` but this happens even after that.

**Comment by jorgenschaefer** [comment]
Yeah, this seems to be a bug in Jedi (see the #1123 comments) – reported upstream …

**Comment by davidhalter** [comment]
1and"" is valid code :) There's way weirder stuff without spaces that works in Python: br''or.0jif.1else-....

I gave a talk about it. It's not a perfect one, but some some parts are interesting and fun :) https://www.youtube.com/watch?v=6NVUbO7pFtA

**Comment by jorgenschaefer** [comment]
It might be valid code, but is it useful to offer as a suggestion?

Oh well, I guess Elpy can just avoid asking Jedi for completions when the symbol before point is a number …

**Comment by davidhalter** [comment]
I can understand your concerns, but I don't think it's Jedi's job to choose when to show completions. I think it's Jedi's job to be correct.

**Comment by abred** [comment]
the behaviour in my case (#1123) is slightly different, it doesn't append the keyword to the number, it changes the number to the keyword (might be because of autocomplete vs company?)

**Comment by jorgenschaefer** [comment]
Hm. Elpy does not use autocomplete, so that shouldn't be an issue. Possibly some confusion in Elpy, because the suggested completions do not start with the symbol before point.

**Comment by jsoishi** [comment]
I am also having this problem. I've noticed that it only happens on numbers with three or more digits. I also see the replacement rather than append 
![elpy_bug](https://user-images.githubusercontent.com/4137953/35118149-ec156900-fc5e-11e7-95a6-97fafd98972c.png)

**Comment by jorgenschaefer** [comment]
IIRC, the Jedi people said at some point that this is valid Python (there is no required space between the number and the operator, even if the operator is `and`), so this is a correct completion. I guess Elpy could avoid asking for completions if the symbol before point is entirely made up of digits.
