### ISSUE TITLE
`elpy-test-django-with-manage` flag is ignored if not in test file.

### ISSUE THREAD

**Issue by kurtwheeler** [jorgenschaefer/elpy#1117]
I am working on a Django project and I am able to successfully run tests from a test file with `C-c C-t`. I am using the `elpy-test-django-runner-manage-command` by setting `elpy-test-django-with-manage` to true. However when I try to run tests from a non-test file with `C-c C-t` it fails because it no longer uses the `elpy-test-django-runner-manage-command` and instead reverts to the `elpy-test-django-runner-command`.

I have looked at the source code and I think I've figured out why this is. In the `elpy-test-at-point` function the module name is checked to see if it contains "test" here: https://github.com/jorgenschaefer/elpy/blob/master/elpy.el#L2085. Since I'm not in a test file this is obviously going to return false, so module will be set to nil when the `elpy-test-django-runner` runs. However within that function whether the module is nil or not is checked BEFORE the `elpy-test-django-with-manage` flag in the `elpy-test-django-runner` function here: https://github.com/jorgenschaefer/elpy/blob/master/elpy.el#L2147. This means that if the module your buffer is in does not contain "test" in it's name the `elpy-test-django-with-manage` flag will never even be looked at.

I would like to always use the `elpy-test-django-runner-manage-command` whether I'm trying to run tests from a test file or not. Would it be possible to change the logic to support this?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report and the very nice bug hunting! Yes, this logic definitely should be fixed :-)

**Comment by jorgenschaefer** [comment]
Was this fixed with #1118 ?

**Comment by kurtwheeler** [comment]
Hmm, I'm not sure. How can I install the new code to test this before a new release is made?

**Comment by jorgenschaefer** [comment]
You can clone the git repository, add it to your `load-path`, and use `M-x load-library RET elpy RET` … for this case, it might be easier to just download the current version of `elpy.el` and use `M-x load-file` on it. :-)

**Comment by kurtwheeler** [comment]
Sorry it took me so long to test this out but it was in fact fixed by #1118. Thank you!
