### ISSUE TITLE
I think it would be great if narrow-to-defun show the function decorators too

### ISSUE THREAD

**Issue by Sukonnik-Illia** [jorgenschaefer/elpy#1120]
When I narrow-to-defun, decorators of function are hidden.
I.e.:
```python
print('narrow-example')

@my_decorator
def f():
    pass

print('end-of-narrow-example')
```
narrowed to:
```python
def f():
    pass
```
But I think it should be:
```python
@my_decorator
def f():
    pass
```

**Comment by jorgenschaefer** [comment]
Yeah, that sounds sensible. This is nothing Elpy does, though, but instead `python.el`'s work – could you file a report against Emacs?

**Comment by Sukonnik-Illia** [comment]
Thanks for the answer.
I did the report.
https://github.com/fgallina/python.el/issues/159
