### ISSUE TITLE
Let me disable importmagic

### ISSUE THREAD

**Issue by LogicalDash** [jorgenschaefer/elpy#1121]
I'm using the [Kivy](https://kivy.org) application framework. I'd like to edit my source in Elpy, but whenever I open a source file with it, an empty Kivy window is created. I think this is a result of importmagic scanning the Kivy module; ``kivy.core.window`` creates a window upon import, which is a misfeature, but not one that's so easy to fix.

I can work around this by keeping Kivy in a virtualenv and *not* activating it in elpy, but I don't think I should have to do that. Perhaps elpy could give me some configuration options for what modules importmagic should scan, or at least disable importmagic entirely, the same way you can with flymake, autopep8 and so forth.

**Comment by jorgenschaefer** [comment]
You do not have to install importmagic to use Elpy. Have you tried simply uninstalling it?

**Comment by LogicalDash** [comment]
Huh, I guess that works fine. Thanks!
