### ISSUE TITLE
Constant eldoc error in echo area

### ISSUE THREAD

**Issue by ZedThree** [jorgenschaefer/elpy#1124]
I continually have this message in the echo area:

> eldoc error: (void-function flymake-find-err-info)

The debug log is as follows:

> Debugger entered--Lisp error: (void-function flymake-find-err-info)
>   flymake-find-err-info(nil 551)
>   elpy-flymake-error-at-point()
>   elpy-eldoc-documentation()
>   eldoc-print-current-symbol-info()

My elpy config is as follows:

> Virtualenv........: bin (/home/peter/Codes/orangutan/bin)
> RPC Python........: 3.4.5 (/usr/bin/python3)
> Interactive Python: python (/usr/bin/python)
> Emacs.............: 25.1.1
> Elpy..............: 1.14.1
> Jedi..............: 0.10.2
> Rope..............: 0.9.4-1
> Importmagic.......: 0.1.7
> Autopep8..........: 1.3.1
> Yapf..............: 0.16.1
> Syntax checker....: flake8 (/home/peter/.local/bin/flake8)

I'm just using the builtin flymake -- do I need to install a newer version from somewhere?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Does `C-h f flymake-find-err-info` work? Does it work after `M-x load-library RET flymake RET`?

**Comment by ZedThree** [comment]
Nope. When I try `load-library`, I get:

> Debugger entered--Lisp error: (error "Don’t know how to make a localized variable an alias")
>   defvaralias(flymake-warning-re flymake-warning-predicate nil)
>   ...

which is a bit odd. I thought flymake was bundled with emacs?

**Comment by jorgenschaefer** [comment]
Yes, it is. Looks like you have some packages installed that redefine Flymake symbols?

**Comment by ZedThree** [comment]
Well, embarrassingly, the problem seems to have solved itself. I must've rebooted and updated enough things.

**Comment by jorgenschaefer** [comment]
Nothing to be embarassed about, technology has become complex enough to be impossible to fully understand sometimes. Glad it works now!
