### ISSUE TITLE
Needed to install elpy-profile.el manually

### ISSUE THREAD

**Issue by timehaven** [jorgenschaefer/elpy#1129]
To upgrade today, I:
- `rm ~/.emacs.d/elpa/elpy*`
- Added
```
(add-to-list 'package-archives '("elpy" . "https://jorgenschaefer.github.io/packages/"))
```
- refreshed packages with `package-refresh-contents`
- installed with   
```
(use-package elpy
    :ensure t
    :bind (:map elpy-mode-map
		([f12] . elpy-shell-send-region-or-buffer)))
  (elpy-enable)
```
and received an error that `elpy-profile.el` did not exist.  

I then copied the file manually from github and placed in my new `~/.emacs.d/elpa/elpy-1.15.0/` dir and everything works fine (at least startup).

**Comment by ajsteven130** [comment]
I can confirm this. I had exactly the same problem using the same package archive and installation method. I resolved it by cloning the git repo and installing from there.

**Comment by vincentmwong** [comment]
I can confirm as well. I also copied `elpy-profile.el` from github and inserted it manually, and it seems to work. (I'm new to emacs and elpy so I don't know what to test for, but I can test anything if needed.)

**Comment by soupault** [comment]
Can confirm this. Was not an issue for 1.14. Started to see this with an update to 1.15.

**Comment by jorgenschaefer** [comment]
I just released Elpy 1.15.1, does this fix the problem?

**Comment by soupault** [comment]
No issues so far with the clean installation of 1.15.1.

**Comment by soupault** [comment]
I think this should be closed. Everything still looks good in `elpy 1.16.0`.

**Comment by jorgenschaefer** [comment]
True, thank you for reminding me :-)
