### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#1135]
That makes it easier to know what [has changed in updates](https://emacs.stackexchange.com/questions/32877/cannot-find-elpy-format-code/32911#comment50827_32911).

**Comment by jorgenschaefer** [comment]
You can use the command `git log` to see the change log. Alternatively, `M-x elpy-news` for the high-level stuff. If you need to find out something like the thing in the question, you can use `git bisect run`, which will tell you that this was added in the commit.

If with "changelog" you mean the GNU ChangeLog, that is an ancient practice from the times when version control systems did not exist or were very limited. It has no place in any software developed in the 21st century.
