### ISSUE TITLE
pyvenv activate isn't showing the activate file

### ISSUE THREAD

**Issue by TheShadow29** [jorgenschaefer/elpy#1140]
I have a virtualenv named myproj. I usually activate it using `source my_proj/bin/activate'. I am trying to do the same in elpy using `M-x pyvenv activate RET my_proj/bin/'. But elpy is not showing the activate file for some reason. It only shows `./ and ../` as the possibilities.
What am I doing wrong?

**Comment by jorgenschaefer** [comment]
The virtualenv is the directory where the `bin/activate` script lies. That should _not_ be the same as your project. Does this help?

**Comment by TheShadow29** [comment]
My bad. I should have been more clear. `my_proj` is the name of my virtual environment.

**Comment by jorgenschaefer** [comment]
So, does selecting the virtualenv (i.e. the directory) work? :-)

**Comment by TheShadow29** [comment]
Yes it works. I should have tried some more permutation. Thanks a lot.

**Comment by jorgenschaefer** [comment]
Glad it works, and enjoy Elpy! I'll close this issue, please do not hesitate to open a new one if you have further problems :-)
