### ISSUE TITLE
Possible clash of elpy with auto-complete

### ISSUE THREAD

**Issue by TheShadow29** [jorgenschaefer/elpy#1142]
I am using emacs with auto-complete-mode as well as elpy-mode. The issue is that sometimes there is a conflict of the two and the options are slightly distorted. Here is the image : 
![screenshot from 2017-06-08 15-04-58](https://user-images.githubusercontent.com/10602903/26989970-eaff5350-4d09-11e7-847f-09f619d595c7.png)
Now even when I select either option, the text returned is not the same. The only option I see is to disable auto-complete mode for a temporary fix, but I would like to know if there is a more elegant solution.

**Comment by jorgenschaefer** [comment]
Yes, Elpy uses company-mode and does not work with auto-complete. Please do not enable auto-complete in Python buffers. :-) You can do that by removing `python-mode` from `ac-modes`, e.g. using

`(setq ac-modes (delq 'python-mode ac-modes))`

Let me know if this fixes things for you!

**Comment by TheShadow29** [comment]
Yes I removed python-mode from ac-modes and I have yet to re-encounter the problem, thanks a lot.

**Comment by jorgenschaefer** [comment]
Great! I'll close this, then. Please do not hesitate to open a new issue if you have further problems. :-)
