### ISSUE TITLE
garbled ipython output (non ASCII junk)

### ISSUE THREAD

**Issue by palbarede** [jorgenschaefer/elpy#1143]
I open a simple Python script (printing text lines) in (Python || Elpy) mode and run it with C-c C-c.

It works, except that the text output is garbled like this 

[79Cf
[79Cr
[79Ce
[79C;
   ...: [8D
[Jthis
is
awesome!
bonjour2

[6n[JIn [8]: [8D[8C

This is GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2017-04-21

elpy
    Version: 20170519.1544

In ~/.emacs :

(elpy-enable)
(elpy-use-ipython)

How to get normal ipython output ?

**Comment by jorgenschaefer** [comment]
Those are escape codes for coloring output, and moving point. Does `(setq ansi-color-for-comint-mode t)` help?

**Comment by palbarede** [comment]
More exactly with the init :

(package-initialize)
(setq ansi-color-for-comint-mode t)
(elpy-enable)
(elpy-use-ipython)

the problem persists, unfortunately.

**Comment by jorgenschaefer** [comment]
IPython 5 changed some stuff with the prompt, I suspect that's it. Not sure this still works, apparently they were thinking about removing this feature, but try: `(setenv "IPY_TEST_SIMPLE_PROMPT" "1")`

**Comment by palbarede** [comment]
The problem was with ipython 5.  I do not remember the precise version number since I have upgraded to ipython 6.1.0.

(setenv "IPY_TEST_SIMPLE_PROMPT" "1")
(elpy-enable)
(elpy-use-ipython)

This eliminates the problem indeed.  Thanks.

**Comment by jorgenschaefer** [comment]
I just pushed some changes to master that should do that automatically in the future :-)
