### ISSUE TITLE
elpy process eating all the RAM

### ISSUE THREAD

**Issue by emanuele** [jorgenschaefer/elpy#1151]
Hi,
first of all big congratulations for elpy! It really improves my emacs-Python daily life!
Since recently, I'm experiencing the following problem: as soon as I start typing Python code (even just "import numpy as np"), a Python process starts, requesting 100% CPU (no big deal) and using a rapidly growing amount of memory (big deal): in a minute or two, it fills up the 16Gb of RAM of my laptop (Ubuntu 16.04). The hungry process is the following: /usr/bin/python -W ignore -m elpy.__main__
This is my current elpy-config:
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.12 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.15.1
Jedi..............: 0.10.2
Rope..............: 0.10.5
Importmagic.......: 0.1.7
Autopep8..........: 1.3.2
Yapf..............: 0.16.2
Syntax checker....: flake8 (/usr/bin/flake8)

I'm looking at the issue tracker and, maybe, my issue could be similar to #1061 , however I do not experience any freeze. if you have any suggestion on what to do to solve this issue, I'd be extremely happy.

Best,

Emanuele

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Could you try uninstalling importmagic and see if that solves the problem?

**Comment by emanuele** [comment]
Sorry for the late reply and thank you for answering. Indeed uninstalling the Python package importmagic completely solves the problem! Thank you very much!
I'm still trying to figure out what is the exact role of importmagic (and the differences with importmagic.el...) with respect to the observed bug. Could you shed some light?

**Comment by jorgenschaefer** [comment]
I do not know `importmagic.el`. Elpy uses the importmagic package to provide import suggestions and import fixups. It's not necessary for the core functionality, like completions and documentation.

**Comment by emanuele** [comment]
Thank you for the explanation. BTW, am I the only one experiencing excessive memory (and CPU) use because of importmagic? I can reproduce the problems on all 5 Ubuntu 16.04 machines I'm using.

**Comment by jorgenschaefer** [comment]
I do not have that issue, but could you report it with importmagic directly?

**Comment by gopar** [comment]
Closing since we no longer support importmagic
