### ISSUE TITLE
elpy doesn't follow path to ipython, Anaconda Python install, Windows 10

### ISSUE THREAD

**Issue by notuntoward** [jorgenschaefer/elpy#1156]
Does elpy have a problem following windows links or paths with spaces in them?  Or, is its search case sensitive?  Here's what I'm seeing:

When emacs 25.2.1 starts up, I get this error message:

`error: Command "ipython" not found`

I don't get this error if I uncomment this line in my .emacs

`(elpy-use-ipython) `

My Windows PATH environment variable points to the folder where Anaconda installed ipython:

`C:\Users\scotto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)`

In this folder is the file` IPython.lnk`; if I click on it in File Explorer, it starts the ipython console.  The ipython console also runs if, in the Windows cmd.exe window, I type:

`C:\Users\scotto\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)\IPython.lnk`

**Comment by jorgenschaefer** [comment]
`elpy-use-ipython` tells Elpy to use a program named `"ipython"` for the subprocess. Otherwise, it will use `"python"`. Did you configure it in some form other than this?

Also, Elpy will try and find the programs in your standard search path (`PATH` under unix, I think also under Windows). If the directory is not there, it won't find the programs.

I'm afraid I do not have a Windows system so I can not give you much of any detail here.

**Comment by notuntoward** [comment]
Thanks for the reply.  For the record, I eventually understood that Windows Emacs can't follow Windows links (IPython.lnk); I needed to follow the link myself and add this to my path instead:

%USERPROFILE%\Anaconda3\Scripts 

(a.k.a C:\Users\scotto\Anaconda3\Scripts)

**Comment by jorgenschaefer** [comment]
Very nice! Does this mean it works now for you? :-)

**Comment by notuntoward** [comment]
Yes, thanks, so I guess I should close this.   Done.

**Comment by diazgilberto** [comment]
I have all these packages installed and my python `PATH` as well `export PATH="$HOME/anaconda3/bin:$PATH"`


```
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.17.0
Jedi..............: Not found (0.11.1 available)
Rope..............: Not found (0.10.7 available)
Autopep8..........: Not found (1.3.3 available)
Yapf..............: Not found (0.20.0 available)
Syntax checker....: Not found (flake8)
```

Elpy doesn't see system PATH?

**Comment by jorgenschaefer** [comment]
Does Emacs? On OS X and desktop environments, Emacs is often not started from a shell and does not see a shell's environment. You can use the `exec-path-from-shell` package to fix that.
