### ISSUE TITLE
Error when attempting to auto format

### ISSUE THREAD

**Issue by cammil** [jorgenschaefer/elpy#1158]
`C-c C-r f` produces the following error:

`elpy-rpc--default-error-callback: Elpy error: Error during formatting: ’ParseError’ object has no attribute ’message’`

This is some of the output of `(elpy-config)`:

```
Elpy Configuration

Virtualenv........: dt05 (/Users/cammil/anaconda/envs/dt05)
RPC Python........: 3.6.1 (/Users/cammil/anaconda/envs/dt05/bin/python)
Interactive Python: python (/Users/cammil/anaconda/envs/dt05/bin/python)
Emacs.............: 25.2.1
Elpy..............: 1.13.0
Jedi..............: 0.10.2
Rope..............: 0.9.4-1
Importmagic.......: 0.1.7
Autopep8..........: 1.3.2
Yapf..............: 0.16.3
Syntax checker....: flake8 (/Users/cammil/anaconda/envs/dt05/bin/flake8)
```

What am I doing wrong?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Could you set `elpy-disable-backend-error-display` to `nil` and see if that provides better error output? Also, does running `yapf` from the command line give the same error?

**Comment by cammil** [comment]
I upgraded to python 3.6.2 and that seems to have stopped the error. Not sure how I can go back to 3.6.1 so that I can carry out the checks you requested.

Would you like me to attempt to downgrade to carry out the checks, or is the fact that 3.6.2 seems to fix the problem good enough?

New `(elpy-config)` output for info:

```
Elpy Configuration

Virtualenv........: dt05 (/Users/cammil/anaconda/envs/dt05)
RPC Python........: 3.6.2 (/Users/cammil/anaconda/envs/dt05/bin/python)
Interactive Python: python (/Users/cammil/anaconda/envs/dt05/bin/python)
Emacs.............: 25.2.1
Elpy..............: 1.13.0
Jedi..............: 0.10.2
Rope..............: 0.9.4-1
Importmagic.......: 0.1.7
Autopep8..........: 1.3.2
Yapf..............: 0.16.3
Syntax checker....: flake8 (/Users/cammil/anaconda/envs/dt05/bin/flake8)
```

**Comment by jorgenschaefer** [comment]
Thank you for the offer, but if the newer version fixes it, I'm fine with that :-) I'll close this issue then – please do not hesitate to open a new issue if you have any further problems!

**Comment by cammil** [comment]
Ok no probs. FYI, if I had to speculate, I believe this is fixed due to an update in lib2to3. See [https://bugs.python.org/issue23894](https://bugs.python.org/issue23894)
