### ISSUE TITLE
`flymake` and `elpy` do not like `prospector` on `pyenv` 

### ISSUE THREAD

**Issue by pmatos** [jorgenschaefer/elpy#1161]
I use `pyenv` to manage my environments. I am happy at the moment with `pyenv` emacs integration through `pyenv-mode-auto`. However, I can't seem to run `prospector` as the syntax checker of elpy:

```
;; Syntax check with prospector
(setq python-check-command "/home/pmatos/.pyenv/shims/prospector --output-format emacs")
```

When I enable `flymake` with `flymake-mode`, I get:
```
Flymake: Configuration error has occurred while running .... Flymake will be switched OFF
```

Well, at this point I am not sure this is even related to `elpy`. My guess is that is might where `flymake` runs the syntax check from. It probably needs to run it from inside the virtualenv, or activate the virtualenv properly for the `pyenv` shim to work.

**Comment by jorgenschaefer** [comment]
You can try `M-x pyvenv-activate` to activate a virtualenv … but this might be related to `python-check-command` being assumed to be a single command, not a command line. I'd suggest just using flycheck instead of flymake. I want to go that way for Elpy anyhow.

**Comment by pmatos** [comment]
@jorgenschaefer Thanks. What's the current way to use flycheck with elpy?

**Comment by jorgenschaefer** [comment]
Remove `elpy-module-flymake` from `elpy-modules` and just use flycheck as per that package's normal documentation. :-)

**Comment by pmatos** [comment]
@jorgenschaefer that works. Now moved to flycheck. Thanks.

**Comment by jorgenschaefer** [comment]
Glad to hear this … there's #137 to track the integration of flycheck, so I'll close this issue. Enjoy Elpy! :-)
