### ISSUE TITLE
elpy-shell-switch-to-shell: Error message

### ISSUE THREAD

**Issue by student-sx** [jorgenschaefer/elpy#1163]
If I execute  C-c C-z (elpy-shell-switch-to-shell) i get the follwing error message

elpy-shell-get-or-create-process: Wrong number of arguments: #[(dedicated cmd) "ÂÃ	!Ä#	" [cmd dedicated python-shell-make-comint python-shell-get-process-name t] 4 ("/home/myuser/.emacs.d/elpa/python-20120402/python.elc" . 37370) (byte-code "

Elpy version: 1.16.0

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! You are using a very old `python.el` modules (2012!), please use a current version. :-)

**Comment by student-sx** [comment]
Thanks, problem solved. Initially I struggled with updating python.el (which was in ~/.emacs.d/elpa/python-20120402/) but then I realized that python.el moved to emacs core some time ago and that deleting ~/.emacs.d/elpa/python-... will solve it since this is a python.el version I installed probably before it was moved to emacs core.

**Comment by jorgenschaefer** [comment]
Glad this is solved. Please do not hesitate to open new issues if you have further problems, and enjoy Elpy!
