### ISSUE TITLE
Set the path of the python enviroment to anaconda binaries

### ISSUE THREAD

**Issue by Feneco** [jorgenschaefer/elpy#1166]
This is more of a question than an issue, cause I'm quite a noob.

I have installed anaconda3 in my computer and I use it on a basis, and i want Elpy to use the anaconda binaries, where all the needed modules(Jedi, Rope, pip, etc) are.

This is the result of the M-X elpy-config
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.13 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.15.1
Jedi..............: Not found (0.10.2 available)
Rope..............: Not found (0.10.5 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.3.2 available)
Yapf..............: Not found (0.16.3 available)
Syntax checker....: Not found (flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH.

There is no backend available. Please install either Rope or Jedi.See
https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-should-i-use-rope-or-jedi
for guidance.

[run] 
```

How do I set the elpy to use my anaconda3 folder?

**Comment by jorgenschaefer** [comment]
I do not use anaconda, but I think it's just virtualenvs? If so, `M-x pyvenv-activate` should work. If not, how do you configure your other work environments to use anaconda?

**Comment by jacob-lee** [comment]
I use anaconda, and I was able to get it working by putting the following in my init file:

```
(setq elpy-rpc-python-command "path/to/my/python")
(setq python-shell-interpreter "path/to/my/python")
```
Everything is fine, except! now running command `M-x elpy-config` causes emacs to freeze until I kill the process.

**Comment by jacob-lee** [comment]
I have managed to get elpy to work with my anaconda installation either by making sure my anaconda python is on system path, or by modifying the `elpy-rpc-python-command` variable to point to it. Everything then works, EXCEPT, `M-x elpy-config` causes emacs to stall until I kill the process using `C-g`.

**Comment by jorgenschaefer** [comment]
Hm. Any idea why `elpy-config` would hang? That seems weird to me. Can you check what the process is doing using `strace` maybe?

Sorry for the lack of help here. :-(

**Comment by jacob-lee** [comment]
I evaluated (setq debug-on-quit t), and called elpy-config, until I
decided to kill the process using C-g. Here is the backtrace:

Debugger entered--Lisp error: (quit)
  call-process("python" nil #<buffer  *temp*> nil "-c" "import
json\nimport sys\n\ntry:\n    import xmlrpclib\nexcept ImportError:\n
  import xmlrpc.client as xmlrpclib\n\nfrom distutils.version import
LooseVersion\n\n\ndef latest(package, version=None):\n    try:\n
 pypi = xmlrpclib.ServerProxy('https://pypi.python.org/pypi')\n
latest = pypi.package_releases(package)[0]\n        if version is None
or LooseVersion(version) < LooseVersion(latest):\n            return
latest\n        else:\n            return None\n    except:\n
return None\n\n\nconfig = {}\nconfig['python_version'] =
('{major}.{minor}.{micro}'\n
.format(major=sys.version_info[0],\n
 minor=sys.version_info[1],\n
micro=sys.version_info[2]))\n\ntry:\n    import elpy\n
config['elpy_version'] = elpy.__version__\nexcept:\n
config['elpy_version'] = None\n\ntry:\n    import jedi\n    if
isinstance(jedi.__version__, tuple):\n        config['jedi_version'] =
'.'.join(str(x) for x in jedi.__version__)\n    else:\n
config['jedi_version'] = jedi.__version__\n    config['jedi_latest'] =
latest('jedi', config['jedi_version'])\nexcept:\n
config['jedi_version'] = None\n    config['jedi_latest'] =
latest('jedi')\n\ntry:\n    import rope\n    config['rope_version'] =
rope.VERSION\n    if sys.version_info[0] <= 2:\n
config['rope_latest'] = latest('rope', config['rope_version'])\n
else:\n        config['rope_latest'] = latest('rope_py3k',
config['rope_version'])\nexcept:\n    config['rope_version'] = None\n
  config['rope_latest'] = latest('rope')\n\ntry:\n    import
importmagic\n    config['importmagic_version'] =
importmagic.__version__\n    config['importmagic_latest'] =
latest('importmagic', config['importmagic_version'])\nexcept:\n
config['importmagic_version'] = None\n    config['importmagic_latest']
= latest('importmagic')\n\ntry:\n    import autopep8\n
config['autopep8_version'] = autopep8.__version__\n
config['autopep8_latest'] = latest('autopep8',
config['autopep8_version'])\nexcept:\n    config['autopep8_version'] =
None\n    config['autopep8_latest'] = latest('autopep8')\n\ntry:\n
import yapf\n    config['yapf_version'] = yapf.__version__\n
config['yapf_latest'] = latest('yapf',
config['yapf_version'])\nexcept:\n    config['yapf_version'] = None\n
  config['yapf_latest'] = latest('yapf')\n\njson.dump(config,
sys.stdout)\n")
  elpy-config--get-config()
  elpy-config()
  funcall-interactively(elpy-config)
  call-interactively(elpy-config record nil)
  command-execute(elpy-config record)
  #[257 "\304\305!\203\f\306\307 !!\210  \307 !\211  \310\307 !\311\")\207"
[current-prefix-arg prefix-arg this-command real-this-command featurep
smex smex-rank intern command-execute record] 4 "\n\n(fn
CMD)"]("elpy-config")
  ivy-call()
  ivy-read("M-x " [avy--overlays-lead yas/about elpy-module-flymake
neo-vc-up-to-date-face ac-linum-update-workaround ffap-newsgroup-p
magit-bisect-bad debugger-previous-window
yas--mirror-transform--cmacro newsticker-new-item-face preferred-width
eshell-under-windows-p company-pre-command helm-source-header
yas/trigger-symbol smex-initialized-p web-mode-css-rule-face
newsticker-date-face python-imenu--build-tree
er--copy-region-to-register wl-highlight-summary-thread-top-face
cl--loop-result-explicit counsel-git-grep-cmd sml/discharging
popup-face--cmacro egg-diff-del which-key--start-paging-timer
buffer-or-list auto-complete-mode-off-hook id-found
rainbow-colorize-by-assoc which-key-command-description-face
org-agenda-date-today info-string ac-comphist-deserialize
counsel--gg-count popup-aif bm-fringe-face yas/table-parent
popup-line-overlay cfw:face-periods ac-define-source
git-gutter:deleted info-variable-ref-item org-time-grid
counsel-faces-action-describe speedbar-directory-face
magit-diff-file-heading-selection js2-instance-member
ac-windows-remote-file-p ...] :predicate commandp :require-match t
:history extended-command-history :action #[257
"\304\305!\203\f\306\307 !!\210  \307 !\211  \310\307 !\311\")\207"
[current-prefix-arg prefix-arg this-command real-this-command featurep
smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort
t :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 .
counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by Feneco** [comment]
Sorry for the late response, but i kinda solved the problem some time afterwards.

I noticed that when i started emacs via the shell, this problem would not happen, whereas when i open with the desktop icon (The usual way i do) it won't load my user PATH variable to emacs, because anaconda put it's folder atop of the system PATH for my user.

I changed my system PATH, but i did not like this solution because it might interfere with some stuff that linux have with python and i don't know if anaconda is stable for that.

**Comment by jorgenschaefer** [comment]
Great you solved the problem! You can look at the `exec-path-from-shell` package, which might be a good solution for you :-)

**Comment by sungwonida** [comment]
> I do not use anaconda, but I think it's just virtualenvs? If so, `M-x pyvenv-activate` should work. If not, how do you configure your other work environments to use anaconda?

That solved my problem. I've been using package `conda` and I usually activate my environment by `M-x conda-env-activate RET my-venv RET` but `elpy` hasn't been recognizing `yapf`. Finally `M-x pyvenv-activate RET /home/user/miniconda3/envs/my-venv RET` solved the issue. Though I wish there's a nice workaround between `conda` and `elpy`.  Anyway, thanks!
