### ISSUE TITLE
Switch shell for current buffer in elpy

### ISSUE THREAD

**Issue by ganesh-krishnan** [jorgenschaefer/elpy#1168]
I'd like to be able to switch the shell being used for the current buffer. As an example, let's say I have two buffers, A and B. Each of these buffers has their associated python process. I then decide that I want buffer B to share the python process with buffer A. How do I switch the python process used by buffer B to that used by A? Is there a command that I'm not aware of? 

I'm aware that I could start off by having them share the same process. But I'd like to switch the shell afterwards.

**Comment by jorgenschaefer** [comment]
Hm. I'm not sure I understand the question. Elpy (and python.el) support two modes: Either one globally-shared Python shell, or one Python shell per buffer. This association is created via the shell buffer name. The only way to change between the two is by changing the value of `elpy-dedicated-shells`.

Is this what you are talking about?

**Comment by ganesh-krishnan** [comment]
@jorgenschaefer Yes that is exactly what I was talking about. I'm coming from the ESS world where I can change the shell for any buffer, so I was thinking it works the same in elpy. Thanks for clarifying!
