### ISSUE TITLE
Missing parentheses in elpy-pkg.el

### ISSUE THREAD

**Issue by renatocan** [jorgenschaefer/elpy#1169]
There is a parenthesis missing in elpy-pkg.el. I think this is causing a problem when trying to install it using el-get.

Thanks,

[ ],

Renato.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! I don't see a parenthesis missing in elpy-pkg.el, could you be more specific?

**Comment by renatocan** [comment]
One at the end of the file, to close the one of the beginning (define-package

**Comment by jorgenschaefer** [comment]
You are entirely right, sorry for being obtuse. I had forgotten to pull a recently-merged PR locally. The problem should be fixed now. :-)
