### ISSUE TITLE
Elpy debug bug. Loss of prompt

### ISSUE THREAD

**Issue by mankoff** [jorgenschaefer/elpy#117]
I keep losing the iPython prompt from elpy. I can re-create it with the following buggy code and steps.

I have 

```
python-shell-interpreter "ipython"
python-shell-interpreter-args "--pylab --pdb"
```

1) Run this:

```
data = arange(256).reshape(16,16)
imshow(data[0], interpolation='none')
```

2) The python buffer goes to `pdb>` and the editor buffer now loads `image.py` and shows where the crash occurred. All good so far.

3) Kill the editor buffer (C-x k RET). 

4) Go back to the iPython PDB buffer.

5) Hit CTRL+D to exit the debugger and return to the iPython prompt.

It crashes. The prompt becomes:

```
^[[0;34mIn [^[[1;34m7^[[0;34m]: ^[[0m
```

And the tiny one-line buffer at the bottom (I forget the name) says: 

```
error in process filter: Selecting deleted buffer
```

**Comment by kootenpv** [comment]
@offby1 I think I'm having this problem. It is not exactly clear how you solved it?

**Comment by offby1** [comment]
@kootenpv I'm afraid you've mentioned the wrong nick!  @offbyone , Pascal has a question for you :-)

**Comment by kootenpv** [comment]
Haha I guess I was only off by one though.
