### ISSUE TITLE
Elpy C-c C-c calls REPL from module directory

### ISSUE THREAD

**Issue by mashu** [jorgenschaefer/elpy#1170]
Hi,

I have a problem with C-c C-c, it is not respecting project directory, but trying to execute my code from module directory with __init__.py file.

Here is full example https://github.com/mashu/ElpyExample and steps to reproduce.

Looking forward to solution,
Thanks a lot

**Comment by jorgenschaefer** [comment]
Hello, and thanks for this really awesome and extensive report! I wish more people would file bug reports like this one :-)

Sadly, elpy right now just uses the current directory when starting a new shell. This is what some people want, but I understand why it's confusing. I created a new issue (see above) to change this behavior. For the time being, you can simply start the REPL from your project root by opening a file there and doing `M-x run-python` – future calls to the shell will use that one.

**Comment by rgemulla** [comment]
Fixed with PR #1209.
