### ISSUE TITLE
Eshell does not recognize activated virtual env

### ISSUE THREAD

**Issue by clearmisp** [jorgenschaefer/elpy#1172]
If I open a new eshell when having a virtual env activated the eshell does not recognize the virtual environment. Is this supposed to work or have I configured elpy incorrectly?

Regards, Micke.

**Comment by clearmisp** [comment]
Opening a shell (M-x shell instead of M-x eshell) works, the new shell uses the activated virtual environment.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is strange. pyvenv sets `exec-path`, which should affect eshell, too. How do you notice that eshell is not recognizing the virtualenv?

**Comment by clearmisp** [comment]
1. I activate the virtual environment using M-x pyvenv-activate.

**Comment by clearmisp** [comment]
1. I activate the environment using M-x pyvenv-activate.
2. I open a new eshell using M-x eshell.
3. In the new eshell I do 'which python', I get '/usr/bin/python' which of course is incorrect. If I do 'python --version' in the eshell I get 2.7.13, it should be 3.4.6.
4. elpy-config shows correct values of everything (I think).
5. The bin dir of the virtual env is prepended to exec-path, still I do not get the correct python in eshell.

I have tried to illustrate all this in a screenshot, I hope you can see all the info.

![emacs-pyvenv](https://user-images.githubusercontent.com/8569604/30744300-c114d462-9fa1-11e7-8450-669a779105c6.png)

**Comment by jorgenschaefer** [comment]
Does `M-: (executable-find "python")` find the Python interpreter in the virtualenv?

**Comment by clearmisp** [comment]
It seem so. I evaluated (executable-find "python") in the *scratch* buffer and printed the result. At the same time eshell finds my system installed python, not the one in the virtualenv.

![emacs-exe-find](https://user-images.githubusercontent.com/8569604/30780762-f8d2259a-a112-11e7-98c0-15c172cddef1.png)

**Comment by clearmisp** [comment]
This is even more strange; executable-find evaluated in eshell returns the python in the virtualenv but the python command in eshell returns the system wide installed python.

![emacs-exe-find-eshell](https://user-images.githubusercontent.com/8569604/30780836-9c48f838-a114-11e7-97bd-4dba11cb1dab.png)

**Comment by jorgenschaefer** [comment]
That seems to be a problem of eshell, I'm afraid …

**Comment by gopar** [comment]
@clearmisp I recommend using https://github.com/porterjamesj/virtualenvwrapper.el if you're using virtualenvwrapper. I've been using ti for a while and it works

**Comment by jorgenschaefer** [comment]
Hm. I'd be curious what virtualenvwrapper.el does that pyvenv.el does not, because Elpy recommends the latter. And I wrote the latter because there was nothing around that really worked well back then. If that changed, Elpy might want to switch suggested venv packages. Or some features could be added to pyvenv.

**Comment by gopar** [comment]
virtualenvwrapper will only work on eshell, it doesn't affect anything else. So pyenv is still the better route to go

**Comment by jorgenschaefer** [comment]
Oh. That's interesting, thank you :-)

**Comment by seanfarley** [comment]
It would seem that there is a missing `eshell-modify-global-environment` for pyvenv to work. The following works for me:

```emacs
(setq eshell-modify-global-environment t)
(defun smf/post-venv-hook ()
  (setq eshell-path-env (mapconcat 'identity exec-path ":")))

(add-hook 'pyvenv-post-activate-hooks #'smf/post-venv-hook)
(add-hook 'pyvenv-post-deactivate-hooks #'smf/post-venv-hook)
```

It even works after the eshell buffer has started :-)

**Comment by jorgenschaefer** [comment]
Nice. Filed a feature request with pyvenv. I won't be able to work on this in the near future, so any help would be welcome :-)

**Comment by rafiks** [comment]
> It would seem that there is a missing `eshell-modify-global-environment` for pyvenv to work. The following works for me:
> 
> ```emacs-lisp
> (setq eshell-modify-global-environment t)
> (defun smf/post-venv-hook ()
>   (setq eshell-path-env (mapconcat 'identity exec-path ":")))
> 
> (add-hook 'pyvenv-post-activate-hooks #'smf/post-venv-hook)
> (add-hook 'pyvenv-post-deactivate-hooks #'smf/post-venv-hook)
> ```
> 
> It even works after the eshell buffer has started :-)

this didn't work for me but virtualenvwrapper did.

**Comment by galaunay** [comment]
Apparently the associated [PR](https://github.com/jorgenschaefer/pyvenv/pull/65) in pyvenv has been merged.

**Comment by renatgalimov** [comment]
In case anybody needs it after the emacs 29.1 updates, which deprecated `eshell-path-env` in favor of `eshell-get-path`:

This approach invalidates eshell cache whenever pyvenv activate/deactivate is called.
```
(defvar r/eshell-path-env-list-revision 0
  "Use it to tell eshell when the env-list should be recalculated.")

(defvar-local r/eshell-path-env-list-local-revision 0
  "Local eshell path revision should match the global revision.")

(defun r/eshell-get-path-check-revision (&rest args)
  "Check if we need to recalculate eshell path, ARGS is ignored."
  (unless (eq r/eshell-path-env-list-local-revision r/eshell-path-env-list-revision)
    (setq-local eshell-path-env-list nil)
    (setq-local r/eshell-path-env-list-local-revision r/eshell-path-env-list-revision)))

(advice-add 'eshell-get-path :before #'r/eshell-get-path-check-revision)

(add-hook 'pyvenv-post-activate-hooks (lambda () (setq r/eshell-path-env-list-revision (+ r/eshell-path-env-list-revision  1))))
(add-hook 'pyvenv-post-deactivate-hooks (lambda () (setq r/eshell-path-env-list-revision (+ r/eshell-path-env-list-revision  1))))
```
