### ISSUE TITLE
Questions: company-elpy-backend and  IPython REPL

### ISSUE THREAD

**Issue by mambolevis** [jorgenschaefer/elpy#1174]
Hi,

I have to questions related to python completion.:

1. I'm using company-elpy-backend for completion, and the following picture shows an example:
![image](https://user-images.githubusercontent.com/13024208/30522465-b5b902f2-9bd0-11e7-9bd9-e2846045bd6f.png)
As you see both completion candidates and their description are together. How can I separate them?
 I found an example with the desired output:
![image](https://user-images.githubusercontent.com/13024208/30522564-7a1ff0e6-9bd2-11e7-898e-97f6b6990050.png)

2. It is possible to get completion in the IPython REPL?
![image](https://user-images.githubusercontent.com/13024208/30269034-ddbc2e34-96e7-11e7-9a0b-84de4f12f6b7.png)

Thanks

**Comment by jorgenschaefer** [comment]
> As you see both completion candidates and their description are together. How can I separate them?

That seems weird. That's not how it looks like here. :-( How are you configuring Elpy and company?

> It is possible to get completion in the IPython REPL?

Not at the moment, beyond what Emacs does by default.

**Comment by mambolevis** [comment]
The elpy configuration;
```
(use-package elpy
  :ensure t
  :defer t
  :init
  (add-hook 'python-mode-hook #'elpy-mode)
  :config
  (progn
    ;; Use Flycheck instead of Flymake
    (when (require 'flycheck nil t)
      (remove-hook 'elpy-modules 'elpy-module-flymake)
      (remove-hook 'elpy-modules 'elpy-module-yasnippet)
      (remove-hook 'elpy-mode-hook 'elpy-module-highlight-indentation)
      (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
      (add-hook 'elpy-mode-hook 'flycheck-mode))
    (setq elpy-modules (delq 'elpy-module-company elpy-modules))
    ;; elpy uses rope by defaul for autocompletion.
    ;; You can permanently prefer jedi by setting this
    (setq elpy-rpc-backend "jedi")
    ;;--------------------------------------------------------------------------
    ;;;  comment/uncoment the block to consider python or ipython
    ;;--------------------------------------------------------------------------
    (if (executable-find "ipython")
        (elpy-use-ipython)
      )
    ;;--------------------------------------------------------------------------
    ;;(elpy-use-cpython)
    (elpy-enable)
    (add-to-list 'company-backends
                 (company-mode/backend-with-yas 'elpy-company-backend))
    )
  )

```
Company configuration:
```
(use-package company
  :ensure t
  :config
  (setq company-minimum-prefix-length 1
        ;; company delay until suggestions are shown
        ;;company-idle-delay 0.1
        company-idle-delay 0
        ;; weight by frequency
        company-transformers '(company-sort-by-occurrence))
  (global-set-key (kbd "C-<tab>") 'company-manual-begin)
  (define-key company-active-map (kbd "C-n") 'company-select-next)
  (define-key company-active-map (kbd "C-p") 'company-select-previous)
  ;;(define-key company-active-map (kbd "TAB") 'company-complete-selection)
  ;;(define-key company-active-map (kbd "<tab>") 'company-complete-selection)
  (define-key company-active-map (kbd "RET") 'company-complete-common)
  ;;(define-key company-active-map (kbd "<return>") nil)
  ;;(define-key company-active-map (kbd "RET") nil)
  (global-company-mode)
  )
```
Please, notice the results obtained when I comment  `elpy-company-backend` and `use company-jedi`
```
;; (add-to-list 'company-backends
;;              (company-mode/backend-with-yas 'elpy-company-backend))
```
```
(use-package company-jedi
  :ensure t
  :defer t
  :after python
  :config
  (add-to-list 'company-backends
               (company-mode/backend-with-yas 'company-jedi))
  )

```
![image](https://user-images.githubusercontent.com/13024208/30742955-e3d11d2c-9f9b-11e7-99ea-e9f213248c72.png)

**Comment by jorgenschaefer** [comment]
You are removing Elpy's company module, thereby preventing Elpy from configuring Company for you. Please see the definition of `elpy-module-company` for what options should be set, in particular see `company-tooltip-align-annotations`. Does this help?

**Comment by mambolevis** [comment]
Yes, that's the problem. How can I get the completion with yasnippet? please see my results:

1. The company-backends for 1,2 and 3
![image](https://user-images.githubusercontent.com/13024208/30744530-c4d9f6d0-9fa2-11e7-9aa0-a81fd4374b64.png)


2.  completion using `elpy-company-backend`
![image](https://user-images.githubusercontent.com/13024208/30744561-e10887ea-9fa2-11e7-93fa-71fe7c863098.png)

3. completion using `elpy-company-backend ` and ` (setq elpy-rpc-backend "jedi"`)
![image](https://user-images.githubusercontent.com/13024208/30744700-990542f2-9fa3-11e7-8ed8-cb8528dbd913.png)

4.  y ahora removing elpy's company module `(setq elpy-modules (delq 'elpy-module-company elpy-modules))
`
![image](https://user-images.githubusercontent.com/13024208/30744862-42e00b36-9fa4-11e7-8807-2f2c12736e10.png)

![image](https://user-images.githubusercontent.com/13024208/30744921-77adc84e-9fa4-11e7-97d6-8b0b6e335df5.png)

**Comment by jorgenschaefer** [comment]
I don't know. Have you tried changing `company-tooltip-align-annotations` as I suggested?

**Comment by mambolevis** [comment]
- using  `elpy-company-backend`, `(setq elpy-rpc-backend "jedi")` and `company-tooltip-align-annotations` solve the problem. There is only one disadvantage: It is not possible to differentiate the yasnippet options
![image](https://user-images.githubusercontent.com/13024208/30753267-1b1ffa78-9fbf-11e7-9882-9262912f6e2b.png)

- using `elpy-company-backend` , `(setq elpy-rpc-backend "jedi")`  but without `company-tooltip-align-annotations` the yasnippet options are with arrows:
![image](https://user-images.githubusercontent.com/13024208/30753549-e5db7f30-9fbf-11e7-82d4-441af0eae521.png)

- using the package `company-jedi` instead without `company-tooltip-align-annotations`
![image](https://user-images.githubusercontent.com/13024208/30754066-91de4942-9fc1-11e7-99c4-751708578841.png)

It looks like the last one is the best option in combination with yasnippet. But it has the disadvantage of requiring the extra package `company-jedi` and its server installation. What do you think about it?

**Comment by jorgenschaefer** [comment]
If that solves your problem, that's fine with me. There's probably a better solution, but you'd have to figure that out yourself, as I'm not using yasnippet in this way :-)

**Comment by mambolevis** [comment]
Thank you!
