### ISSUE TITLE
Error: ‘add-to-list’ can’t use lexical var ‘table’; use ‘push’ or ‘cl-pushnew’

### ISSUE THREAD

**Issue by sam-s** [jorgenschaefer/elpy#1177]
[`add-to-list`](https://www.gnu.org/software/emacs/manual/html_node/elisp/List-Variables.html) cannot be used on lexical variables for obvious reasons.

**Comment by jorgenschaefer** [comment]
Correct. Where is it used on lexical variables?

**Comment by sam-s** [comment]
https://github.com/sam-s/elpy/commit/617a1d805e7fd64caf5ddc1aa0c52be51574b4bc

**Comment by jorgenschaefer** [comment]
Thank you!
