### ISSUE TITLE
Start new shells from the library root

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#1178]
It would be less confusing if new shells were started with the current directory being the library root, just like tests are. See e.g. #1170 for an example of the confusion.

**Comment by galaunay** [comment]
Do you think this should be done by default (seems fine for me, but this could confuse some users) or activated through an elpy option ?

**Comment by jorgenschaefer** [comment]
I think default would be fine.

**Comment by rgemulla** [comment]
Fixed with PR #1209.
