### ISSUE TITLE
Followed steps for quick installation, stuck at the package-install step.

### ISSUE THREAD

**Issue by daydreamerZzz** [jorgenschaefer/elpy#1181]
I executed `M-x package-install RET elpy RET`. The installation seems to terminate with the following error message
`mapcar: Symbol's function definition is void: macroexp-quote`.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! What version of Emacs are you using?

**Comment by daydreamerZzz** [comment]
I'm using emacs 24.5.1.

**Comment by jorgenschaefer** [comment]
Is it possible that you have elisp files compiled with a different Emacs somewhere? Elpy does not use `macroexp-quote` anywhere, and that's not used in Emacs 24.5, either.

**Comment by daydreamerZzz** [comment]
Thanks for checking the issue for me. I have no idea where the elisp file that triggered the problem might be. I just reinstalled emacs (a different version) and the problem is gone!
