### ISSUE TITLE
Improvements for use with interactive Python

### ISSUE THREAD

**Issue by rgemulla** [jorgenschaefer/elpy#1182]
I created a Spacemacs layer that integrates ```elpy``` with Spacemacs. The layer allows to use ```elpy``` in a style similar to [ESS](https://ess.r-project.org/) and extends some of its capabilities. Additions include more flexible evaluation commands, echoing of inputs sent to the Python shell in the shell buffer, echoing of Python shell outputs in the echo area, flashing of statements being evaluated, as well as a few minor bugfixes/improvements of ```elpy``` and ```python``` packages. See [here](https://github.com/rgemulla/spacemacs-layers/tree/master/+lang/elpy) for a more detailed description and source code.

Almost all of this functionality is not Spacemacs-specific, and I feel it may be useful for ```elpy``` users in general. I am opening this issue to gauge whether there is interest to directly integrate some of these additions into ```elpy```.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for all your work! It is greatly appreciated :-)

Generally, I'm quite interested in new features, given they are useful for many people and they do not add too much of a maintainability burden … small helper functions are great. As Python's use case between (less-interactive) application development and (more-interactive) numpy/scipy use differs quite a bit, do you think it would make sense to have a separate minor mode for the more-interactive functions? I do not know if there's enough room for them to get a default key binding otherwise.

**Comment by rgemulla** [comment]
If you feel that there is enough interest (or have enough interest yourself), I'd be happy to help integrating. It shouldn't be that much work.

I fully agree that application developers won't care much about these additions (and wouldn't even notice them). They are tailored for interactive use and (in my eyes) allow for much higher editing and evaluation efficiency than by, say, using Jupyter notebooks.

The "echoing" additions go well with elpy and do not require new keybindings. I already created custom variables in the elpy group that control those features:

```lisp
(defcustom elpy/shell-display-buffer-after-send nil
  "Whether to show the Python shell after sending something to it."
  :type 'boolean
  :group 'elpy)

(defcustom elpy/shell-echo-output 'when-shell-not-visible
  "Whether to echo the Python shell output in the echo area after input has been sent to the shell.

  Possible choices are nil (=never), when-shell-not-visible, or
  t (=always)."
  :type '(choice (const :tag "Never" nil)
                 (const :tag "When shell not visible" when-shell-not-visible)
                 (const :tag "Always" t))
  :group 'elpy)

(defcustom elpy/shell-echo-input t
  "Whether to echo input sent to the Python shell in the shell buffer."
  :type 'boolean
  :group 'elpy)

(defcustom elpy/shell-echo-input-cont-prompt t
  "Whether to show a continuation prompt when echoing to the Python shell."
  :type 'boolean
  :group 'elpy)

(defcustom elpy/shell-echo-input-lines-head 10
  "Maximum number of lines to show before truncating echoed input in the Python shell."
  :type 'integer
  :group 'elpy)

(defcustom elpy/shell-echo-input-lines-tail 10
  "Maximum number of lines to show after truncating echoed input in the Python shell."
  :type 'integer
  :group 'elpy)
```

The same holds for briefly highlighting expressions sent to the shell:  whenever ```eval-sexp-fu-flash-mode``` is active, hightlighting takes place, otherwise not. There is no dependency on the ```eval-sexp-fu``` package.

The other additions really just affect what is sent to the shell. I am using these as replacements, rather than additions, of the corresponding elpy commands. The main difference is that these new functions try to interpret "statement" the Python way: e.g., a line ```Else:``` is not a statement, and we'd never really want to send just ```Else:``` to the shell. What the commands do is try to figure out which Python statement the point is one (or which top-level statement or group of top-level statements) and send useful input to the shell. Navigation itself is otherwise unaffected.

As for keybindings, I don't have that problem in Spacemacs ;). One option might be to only provide the "step-and-go" bindings that Elpy has right now. From there on, one may build a minor mode, as you suggest, which provides additional bindings.

**Comment by rgemulla** [comment]
Note that there is some overlap with #1079.

**Comment by jorgenschaefer** [comment]
> If you feel that there is enough interest (or have enough interest yourself)

Well-meaning suggestions: Only work on stuff you enjoy, not on stuff you think someone else enjoys. :-)

If _you_ want this in Elpy, please go ahead.

One note, the `elpy/` prefix convention is not how Elpy works right now. Either use `elpy-` for exported names, or `elpy--` for internal names (or other prefix, depending on what you're working on).

**Comment by rgemulla** [comment]
I do that! :)

Nevertheless, I won't spent time integrating anything into elpy if there is no interest from the community or chances are that these features are not ultimately added. I do enjoy these features and make heavy use of them, but I do not need to burn time. I like having them added to elpy, so that they can evolve better. 

The ```elpy/``` convention is Spacemacs convention (for the "elpy layer" not the elpy package) and has the advantage that it does not clash with ```elpy-``` right now. If any of this gets integrated into elpy, naming conventions etc have to change, of course.

**Comment by jorgenschaefer** [comment]
> Nevertheless, I won't spent time integrating anything into elpy if there is no interest from the community 

I basically never send individual statements from a Python file to the interpreter, so these are not particularly useful to me. I can not speak for "the community" – you saw the bug reports, there certainly seem to be people out there who want them. I do not know how many.

> or chances are that these features are not ultimately added.

I'm quite interested in these changes, as long as they do not make Elpy less useful for people who do not use them. :-) The only reason to reject such changes would be if the coding style is really terrible (highly doubtful). Tests are appreciated, but not mandatory.

**Comment by rgemulla** [comment]
That's great! 

I don't have time to do tests, unfortunately. But I am willing to help maintaining the interactive shell parts because I do use them a lot.

I created pull request #1185. Nothing should change for non-interactive Python users, as desired. Once the PR is ready and integrated, I can create a few lines of documentation.

**Comment by rgemulla** [comment]
Since #1185 has been merged, this issue can be closed.
