### ISSUE TITLE
annoying error regarding elpy backend even after re-installation

### ISSUE THREAD

**Issue by kirk86** [jorgenschaefer/elpy#1183]
Hi could anyone give me some hints on the following annoying error, that I'm getting:

```
There was some unexpected output from the Elpy backend. This is       
usually some module that does not use correct logging, but might      
indicate a configuration problem.                                     
                                                                      
Output                                                                
^[[?1034h{"result": "Pool.join()", "id": 13}
```
I'm on mac os using emacs 25. I've read the posts regarding this error from previous years but those solutions didn't work for me.

Any hints?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. That looks like some command emitting console codes. What's the value of `elpy-rpc-python-command`?

**Comment by kirk86** [comment]
@jorgenschaefer the output is "python". It seems that there was an error between iterm2 and bash-it. I've updated iterm2 and bash-it and it seems that the problem is not evident any more. I'll close the issue for now and if I see the issue is persistent I'll report back.
Thanks.
