### ISSUE TITLE
How to enable xref with elpy?

### ISSUE THREAD

**Issue by trivialfis** [jorgenschaefer/elpy#1186]
I use Emacs 25.3.1 which comes with xref. The doc says that elpy would configure the xref appropriately if xref is presented. But it doesn't seem like I can get it to work.
 
"M-." is bound to (elpy-goto-definition) and "M-?" asks me to visit tags table, I think elpy didn't try to configure the xref backend.

Here is my elpy configuration:

> Elpy Configuration
> 
> Virtualenv........: None
> RPC Python........: 3.6.2 (/usr/bin/python3)
> Interactive Python: python3 (/usr/bin/python3)
> Emacs.............: 25.3.1
> Elpy..............: 1.16.1
> Jedi..............: 0.11.0
> Rope..............: 0.10.7
> Importmagic.......: Not found (0.1.7 available)
> Autopep8..........: 1.3.2
> Yapf..............: 0.18.0
> Syntax checker....: flake8 (/usr/bin/flake8)

The importmagic is not installed due to this  #1083 . And I installed elpy via mepla.
Is the xref integration ready? If yes, is there any other information I can provide to help?

**Comment by trivialfis** [comment]
I solved the problem by adding the following line to my configuration file:

`(setq elpy-rpc-backend "jedi")`

Though this is resolved, but I think the documentation is lacking.

**Comment by jorgenschaefer** [comment]
Hello, and sorry this caused confusion. Elpy uses xref by default, just rope does not provide all of the necessary functionality. There's #329 and also the idea of just getting rid of Rope, though …

**Comment by trivialfis** [comment]
@jorgenschaefer Thanks for the reply. I think this can be close. And surely, thanks for all the hard work, I love Elpy very much.
