### ISSUE TITLE
Overriding (or changing) keyboard shortcuts made by Elpy

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#1188]
Elpy seems to bind e.g. `(elpy-shell-send-current-statement)` to `<C-return>`. How can I override (specifically deactivate) this particular binding?

**Comment by amelio-vazquez-reina** [comment]
The answer seems to be:

``` lisp
(eval-after-load "elpy"
  '(cl-dolist (key '("C-<return>"))
     (define-key elpy-mode-map (kbd key) nil)))
```

**Comment by jorgenschaefer** [comment]
Hello, and glad you found the solution! Please do enjoy Elpy! :-)
