### ISSUE TITLE
/usr/bin/pythonw is used even if a virtualenv is activated

### ISSUE THREAD

**Issue by rakanalh** [jorgenschaefer/elpy#1189]
Hello,

On the most recent version of elpy on melpa, elpy is not detecting installed dependencies such as jedi, yapf .. etc.
![screenshot](https://i.imgur.com/M9oWyAul.png)

Am not sure if you latest commit (https://github.com/jorgenschaefer/elpy/commit/2d6dc9f31de8805f2b7630c874942fb7e8fb5bd3) causes this or not but i find it weird that /usr/bin/pythonw is used as the version i am using with pyenv is 3.6.2 as apparent on the screenshot.

Edit: The issue is resolved by
```
(setq elpy-rpc-python-command "~/.pyenv/versions/x/bin/python")
```
My pyenv doesn't contain pythonw or py executables so maybe virtualenvs should have a different lookup priority?

Thanks

**Comment by igroen** [comment]
Same problem here.
@rakanalh Yes you're right, must be that commit. 
On OS X /usr/bin/pythonw is available. Because the system-type check is removed in this commit the rpc-python is set to pythonw.

**Comment by hotpxl** [comment]
Same problem here. In virtualenv, elpy would find the system-wide `pythonw`, and will not find packages installed in the virtualenv anymore.

Comment out commit 2d6dc9f31de8805f2b7630c874942fb7e8fb5bd3 fixes this problem. In `elpy-config`, it will find the correct "RPC Python" as in the virtualenv.

**Comment by rakanalh** [comment]
@jorgenschaefer seems like multiple people are having this issue... could you please consider a fix? we can revert the commit if you're ok with that approach.

**Comment by widdowquinn** [comment]
+1 here, too.

**Comment by jorgenschaefer** [comment]
… wtf is pythonw available anywhere but Windows? Why is Windows such a pain? :-D Sorry for the inconvenience. As a workaround, you can `(setq elpy-rpc-python-command "python")` and things should work out. I'm currently without sensible internet access, so I'll not get around to a real fix until later I'm afraid.

**Comment by hotpxl** [comment]
I'm using Mac. So the system does have a `pythonw`, but the one in virtualenv doesn't. That's causing the problem. `elpy` finds the outside `pythonw`.

**Comment by jorgenschaefer** [comment]
I just pushed 90c659e – does that fix this problem?

**Comment by igroen** [comment]
@jorgenschaefer [90c659e](https://github.com/jorgenschaefer/elpy/commit/90c659e4c504d0272e0be8ad0534370a3d41b6f0) fixes this bug on OS X

**Comment by rakanalh** [comment]
Yup... the fix works... thanks @jorgenschaefer
