### ISSUE TITLE
error elpy doesn't support files without a local project root

### ISSUE THREAD

**Issue by kirk86** [jorgenschaefer/elpy#1190]
Hi,
can someone give me some hints on the following error that I keep getting whenever I edit remote files with `tramp`.

```
error in process filter: Elpy error: rope does not support files without a local project root
```

I've noticed that since this error everything starts to hang, and emacs becomes excruciating unresponsive and impossible to work with.

Are there any workarounds or hints on how to prevent this?

**Comment by jorgenschaefer** [comment]
Hello! Rope (and indeed Elpy) does not really support editing remotely with Tramp. You can try sshfs instead if you like, though I'd recommend just editing files locally in any case.

**Comment by kirk86** [comment]
@jorgenschaefer Hi, thanks for the response. But it seems somehow strange that elpy doesn't have this ability since the file gets rendered in the buffer, if I'm correct. Then again I don't know the internals of elpy or rope for that matter, so maybe I'm just saying sth dump here.

**Comment by jorgenschaefer** [comment]
Elpy runs Python processes outside of Emacs on those files. While Tramp has the ability to run these remotely, it requires a lot of fiddly work translating file names. Elpy simply does not do this. Tramp, in essence, is a big hack that happens to work often. It breaks down here.

(Patches welcome of course, but it's an annoying amount of work :-))

**Comment by kirk86** [comment]
@jorgenschaefer Thanks a lot for the response. I'm closing this issue since I already got my answer.
Thanks again!
