### ISSUE TITLE
delay in publishing 1.16.1 on PyPi?

### ISSUE THREAD

**Issue by ViktorHaag** [jorgenschaefer/elpy#1191]
It seems that 1.16.1 is not yet published on PyPi; is there a reason for this? The unavailability on PyPi is starting to result in me getting periodic warnings from Emacs that I'm using a different version of the Emacs package and the back-end elpy python package.

**Comment by jorgenschaefer** [comment]
Oops, should be fixed now :-)

In general, though, you should not need to install Elpy from PyPI except in some weird situations, Elpy for Emacs ships with the Python code for a while now.

**Comment by ViktorHaag** [comment]
Looks like a duplicate of #1137, so we might well want to just close this in favour of that. Thanks for updating!

**Comment by jorgenschaefer** [comment]
No worries, I rather have one issue too many than one too few! Enjoy Elpy :-)
