### ISSUE TITLE
Matplotib plots not displaying in Emacs from elpy

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jorgenschaefer/elpy#1193]
There is another ticked (closed one) with the same title; however, I tried all what is mentioned there. Still Matplotlib does not plot even after using ipython.

**Comment by jorgenschaefer** [comment]
Feel free to reference said other ticket here. I have no idea about matplotlib. Does it work without Elpy?

**Comment by DrWaleedAYousef** [comment]
I mean this ticket:

https://github.com/jorgenschaefer/elpy/issues/909

**Comment by galaunay** [comment]
Could you be more specific about what happen:
- Is matplotlib able to make plots from a terminal ?
- Is matplotlib able to make plots without elpy enabled (in `python-mode`) ?
- What is the python output for a simple script like this one:
```python
import matplotlib.pyplot as plt
plt.figure()
plt.plot(range(10), range(10))
plt.show()  # or 'plt.savefig('image.png')', depending on your matplotlib backend
```

**Comment by DrWaleedAYousef** [comment]
Thanks so much for your reply,

* yes, matplotlib plots from the shell; I ran the simple plot script
your listed below and I attached the screenshot of the output.

* When I write the script below in tmp.py and run with elpy mode enabled
(using C-c C-l) or (using C-c C-c for the selected code) the same plot
appears.

My question is that, while using the elpy mode I need the shell be
cell-based (ipython) and be able to see the figures in the emacs buffer
of that shell.

One more related question: does elpy have something like "%%%" as in
Matlab, which I put it before and after some code in the buffer so that
i can execute this only code instead of the whole buffer. (or instead
off keeping highlighting this code to evaluate with C-c C-c)

Thanks so much for your support.

**Comment by galaunay** [comment]
If you want to have the figure to be displayed directly in emacs buffers (in the shell buffer I presume), [EIN](https://github.com/tkf/emacs-ipython-notebook) may be what you are looking for.

Regarding executing blocks of code in a Matlab fashion, I don't think elpy provides a function to do it, but you can implement it relatively easily in emacs with something like that:
```Lisp
(defun elpy-shell-send-cell ()
  "Send the current block of lines delimited by '# %%%'."
  (interactive)
  (save-excursion 
    (if (not (re-search-backward "^# %%%" nil t))
        (error "Not in a cell")
      (forward-line)
      (beginning-of-line)
      (set-mark (point))
      (if (not (re-search-forward "^# %%%" nil t))
          (progn
            (deactivate-mark)
            (error "Not in a cell"))
        (forward-line -1)
        (end-of-line)
        (elpy-shell-send-region-or-buffer)
        (deactivate-mark)))))
```

Hope it helps.

**Comment by DrWaleedAYousef** [comment]
Thanks so much;

EIN has some bugs (at least with me). elpy is more natural. However,
should I get what I want if I use ipython option with elpy?

**Comment by galaunay** [comment]
I don't think you can have figures displayed directly in emacs with Elpy.
Mainly because Elpy relies on `python.el` that does not support this feature
(@jorgenschaefer will confirm ?).

It also seems quite challenging to implement, so I will not bet on an implementation of this in the near future :).

**Comment by DrWaleedAYousef** [comment]
I mean displaying in the ipython-shell buffer not the .py buffer

**Comment by jorgenschaefer** [comment]
I confirm the above, yes. Both for the .py buffer and the ipython-shell buffer. This is not something that Elpy supports right now, and highly unlikely to support ever.

**Comment by rgemulla** [comment]
For executing blocks of code, see the new features introduced with #1185. elpy still does not support custom code blocks, but that's a feature that I also find useful. As discussed in #1185, I'll probably make a PR for this sometime soon.

**Comment by DrWaleedAYousef** [comment]
Thanks so much for your time and reply;
FYI, please look at this mode; it is ready made python-cell:
https://github.com/thisch/python-cell.el

**Comment by rgemulla** [comment]
Yes, see PR #1226. Is this what you intended?

(Only difference seems to be that #1226 uses ```###``` as cell boundary and does not allow additional comments on the line. But that default can still be changed and the boundary definition is customizable.)

**Comment by DrWaleedAYousef** [comment]
But is this option enabled in elpy current version? I tried but it seems not working? what is the function or the keybinding?

**Comment by rgemulla** [comment]
It's not yet committed ;) --- hopefully sometime soon

**Comment by DrWaleedAYousef** [comment]
Great; thanks so much

**Comment by rgemulla** [comment]
You can check out PR #1226; once its merged (gone), the functionality is in.

**Comment by rgemulla** [comment]
The PR is merged in and should be on MELPA soon. Documention is at https://elpy.readthedocs.io/en/latest/ide.html#interactive-python (will slightly change soon). To try it, use for example ```C-c C-y W```.

**Comment by mahyaret** [comment]
You can use different back-end:
```
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt 
```
Other GUI backends:

  * ```TkAgg```
  * ```WX```
  * ```QTAgg```
  * ```QT4Agg```

If you are using Elpy run your code using ```C-u C-c C-c```
