### ISSUE TITLE
multiple python session

### ISSUE THREAD

**Issue by yitang** [jorgenschaefer/elpy#1197]
Hi, 

if there a way to switch between python session? by default, we use *Python* session, is there an easy way to start a different session, say *Python2*, and switch between them? 

Thanks,

Yi

**Comment by yitang** [comment]
I will update elpy

**Comment by yitang** [comment]
reopen because i cannot find a way to do it..

**Comment by galaunay** [comment]
Elpy identifies the shell by using the name of its buffer (i.e. `*Python*` by default), so if you rename the shell buffer (to `*Python_2*` for example), elpy will use a new `*Python*` buffer  and you wiil be able to switch between `*Python*` and `*Python_2*` by renaming them.

Something like that should work if you only need 2 sessions:
```Lisp
(defun elpy-switch-python-session ()
  (interactive)
  (if (string= python-shell-buffer-name "Python")
      (setq python-shell-buffer-name "Python_2")
    (setq python-shell-buffer-name "Python")))
```

Ps: I don't know why you need several python sessions, but if you set `elpy-dedicated-shells` to `t`, elpy will create one session per python file.

**Comment by jorgenschaefer** [comment]
I'm not sure what "session" means, either. If you mean which Python interpreter to use, Elpy supports virtualenvs, which are a standard Python practice (you can find documentation on them elsewhere if you never used them). You can switch virtualenvs with `M-x pyvenv-activate` or `M-x pyvenv-workon`. Does this help?

**Comment by yitang** [comment]
hi guys, I am asking because it's quite easy to do in ESS for R. When i use R for data analysis, i usually have multiple R sessions or instances running simultaneously, to run different experiments.

to do that in ESS, I could use C-c C-s (ess-switch-process) to choose which R session to send the code for evaluation.

![image](https://user-images.githubusercontent.com/6054101/31862652-4efa7aa8-b739-11e7-912e-581f4be06985.png)

is there an easy way to do this in elpy? All .py scripts are binded to *Python*, which is not useful for running multiple data analysis project.

if not, I have to use something like elpy-switch-python-session function.

**Comment by galaunay** [comment]
If you intend to have one session per script, you can use `elpy-dedicated-shells`.
Else, I think an enhanced version of `elpy-switch-python-session` should give you the same behavior as `ess-switch-process`.

**Comment by yitang** [comment]
@galaunay I am trying ob-ipython. it let me run python scripts in org-mode. it's good for data analysis. it uses Jupiter kernel for connecting src block with the python session. and it also let me use the linked python process interactively, by using C-c C-v C-z (org-babel-switch-to-session); it will give me a process buffer *py_test*, if i name the session *py_test*.

but i'd prefer to use elpy for editing, and sometimes run a line or a chunk of code (C-c C-c), but it will send to *Python* buffer always. 

so i wonder if you could implement an enhanced `elpy-switch-python-session` in the future? or if it's easy, maybe send me a snippet so i could try it out?

Thanks

**Comment by galaunay** [comment]
The following code should do what you want:
```Lisp
(setq elpy-dedicated-shells nil)   ; Ensure no conflict with dedicated shells

(defvar elpy-shell-python-shell-names '("Python")
  "List of existing python shell names.")

(defun elpy-shell-switch-python-shell (&optional dont-display)
  "Switch to another Python shell.

Create a new one if it does not exist.
If DONT-DISPLAY is non nil, do not display the python shell afterwards."
  (interactive)
  (let ((shell-name (completing-read "Python shell name: "
                                     'elpy-shell-python-shell-names)))
    (setq python-shell-buffer-name shell-name)
    (add-to-list 'elpy-shell-python-shell-names shell-name t)
    (when (not dont-display)
      (elpy-shell-display-buffer))))
```
Just do `M-x elpy-shell-switch-python-shell` when you need to change of session.
It is not perfect, but it should work decently, let me know if something goes wrong.
I will try to come with a proper implementation of this, and make a pull request.

**Comment by yitang** [comment]
@galaunay wow! that's awesome! I feel like i'm pro now.

Thank you very much. have a good day.

**Comment by rgemulla** [comment]
@galaunay: I also think this is useful. 

My suggestion would be to track all shells created by elpy in a variable (instead of asking users to provide it as in the quick draft above). Perhaps one can also dynamically collect them by iterating over all buffers. 

One may then have a "elpy-shell-switch-to-shell" command, which provides all existing shell buffer names for auto-completion (e.g., for ido/ivy/helm); if a new name is entered, a new shell is started. Likewise, the use-dedicated-shells customization variable could have three options: nil (just use one shell), ask (ask which one to use whenever the first piece of code is sent from a Python buffer), or t (new shell per buffer).

**Comment by galaunay** [comment]
> My suggestion would be to track all shells created by elpy in a variable (instead of asking users to provide it as in the quick draft above). Perhaps one can also dynamically collect them by iterating over all buffers.
> One may then have a "elpy-shell-switch-to-shell" command, which provides all existing shell buffer names for auto-completion (e.g., for ido/ivy/helm); if a new name is entered, a new shell is started.

The previous snippet already tracks created shells and store them in `elpy-shell-python-shell-names`.
They are re-used to propose shell names when using `elpy-shell-switch-python-shell` (using `completing-read` so that it uses the user preferred completion system).

 > Likewise, the use-dedicated-shells customization variable could have three options: nil (just use one shell), ask (ask which one to use whenever the first piece of code is sent from a Python buffer), or t (new shell per buffer).

This is an interesting idea, the `ask` options will need to store locally (for each buffer) the associated shell, but it seems doable. I should be able to come with a pull request soon.

@yitang, as you are a real user of this functionality, could I contact you when the pull request is done to do some testing on it ?

**Comment by yitang** [comment]
@galaunay  sure of course. id love to.

btw, using your script, all py scripts are bind to a specified python buffer. i found it's actually easier to work with. ESS bind each R scripts to a default process depend on the scripts' directory (package directory), and when i work on 4-5 scripts and more than one process, i start losing tracks. so i ended up using `ess-switch-process` whenever i switch window to an R buffer..... 

so all buffer to one process is an actually good idea.

**Comment by rgemulla** [comment]
Hmm, this is getting complex. I also realized that this is closely related to #1100, see the discussion there. I think we should try to find the simple, low-maintenance solution. 

Here is a suggestion: Add a custom variable ```elpy-shell-shell-buffer-name-function```, holding a function that takes a Python buffer and produces a Python shell buffer name. With this, we can have a function for single shell (always returns ```nil```, see below), for project-shell (as in #1100), and (if really needed) for dedicated shell. It also becomes customizable from the outside.

Furthermore, we may interpret return value ```nil``` as "default shell buffer".  And this one we can switch with the ```elpy-shell-set-default-shell-buffer-name``` discussed here. 

For all other buffers, the shell can't be switched so one needs to resort to renaming, if really needed. If we wanted this, things would get complex. And at least I don't see a strong use case.

**Comment by rgemulla** [comment]
Another option might be to customize ```elpy-shell-switch-to-shell``` / ```elpy-shell-get-or-create-shell``` along the lines discussed above. Then one can execute custom code during shell creation as in #1100.

**Comment by galaunay** [comment]
I am closing this to avoid duplicate discussion with #1232.
