### ISSUE TITLE
error installing from elpy

### ISSUE THREAD

**Issue by aalmah** [jorgenschaefer/elpy#1199]
I'm getting the following error when installing elpy on a remote server:
`process epg no longer connected to pipe; closed it
`
I did `M-x toggle-debug-on-error` and I got a detailed error which I'm attaching here. I would appreciate help in fixing this. Thanks!
[elpy_error.txt](https://github.com/jorgenschaefer/elpy/files/1407645/elpy_error.txt)

**Comment by jorgenschaefer** [comment]
The error you are receiving happens because your Emacs is trying to verify the yasnippet package from GNU ELPA. There is something misconfigured with your verification, or the epg setup. I'm afraid this has  nothing to do with Elpy.
