### ISSUE TITLE
elpy-test-django-runner should raise an error when it can't find the manage command

### ISSUE THREAD

**Issue by twhaples** [jorgenschaefer/elpy#1201]
I have a fresh installation of emacs-prelude and have just loaded elpy. I have set the elpy testrunner to Django Discover. It attempts to use django-admin to run my tests. This does not work, because my python system is not set up like that. I therefore set `elpy-test-django-with-manage` to `t`.

This has resulted in elpy-test failing to execute, instead raising an error.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  elpy-test-django-runner("~/Envs/redacted/lib/python2.7/site-packages/" nil nil nil)
  apply(elpy-test-django-runner ("~/Envs/redacted/lib/python2.7/site-packages/" nil nil nil))
  elpy-test(nil)
  funcall-interactively(elpy-test nil)
  call-interactively(elpy-test record nil)
  command-execute(elpy-test record)
  execute-extended-command(nil "elpy-test" nil)
  funcall-interactively(execute-extended-command nil "elpy-test" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I am in possession of a workaround that involves
```
(setq elpy-test-django-runner-command '("./manage.py" "test" "--noinput"))
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Yeah, stuff can break if a system is set up in an unusual way. You can also use `(setq elpy-test-django-with-manage t)` to deal with your situation if you like. Does this help?

**Comment by twhaples** [comment]
@jorgenschaefer No, no, no, this is not a support request looking for `(setq elpy-test-django-with-manage t)`. I've already found that. This is specifically a **bug report** about elisp crashes in the code which is affected by the flag. :)

**Comment by twhaples** [comment]
> I therefore set `elpy-test-django-with-manage` to `t`.

**Comment by jorgenschaefer** [comment]
Got it, sorry. Yeah, `elpy-test-django-runner` should check the result of `locate-dominating-file` there …

**Comment by gopar** [comment]
@twhaples would you mind sharing how your project structure looks like? 

Do you have `manage.py` at the root of your project? if not, where? From what I know, most people have `manage.py` on root, (and the function that tries to find it assumes that is true for all django projects)

**Comment by twhaples** [comment]
My current project structure is a git repo containing several subdirectories, several of which may have Django roots within them. If I run `(elpy-project-root)` from `/Users/thomaswhaples/code/project/subprojectone/manage.py` it outputs `"/Users/thomaswhaples/code/project/"`. (I suppose this is not useful for running Django anythings in subproject one).

**Comment by gopar** [comment]
Oh, you have multiple Django projects. If you have one "main" `manage.py` (or maybe you just have one) you can set the project root by `(setq elpy-project-root "path/you/want")` and that should be able to find the `manage.py` file.

You can also set the variable via `M-x elpy-set-project-variable` and selecting `elpy-project-root`. That way you don't have to set it every time you jump onto emacs or switch buffers. 

Does that work for you?

**Comment by gopar** [comment]
No update. Closing issue
