### ISSUE TITLE
Clear Python buffer when C-c C-c

### ISSUE THREAD

**Issue by petey33** [jorgenschaefer/elpy#1204]
Hi,

I think it would be nice if  C-c C-c cleared the python buffer. It's easier for the eyes :-).

Thanks for an awesome plugin!

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the suggestion! I think that would not work for everyone – some people like to see their previous output as they incrementally send new things to the Python process :-)

But you can do this yourself! Put this in your `init.el`:

```Lisp
(defadvice elpy-shell-send-region-or-buffer (before petey/clear-python-buffer activate)
  (with-current-buffer (process-buffer (elpy-shell-get-or-create-process))
    (comint-clear-buffer)))
```

Does this help?

**Comment by petey33** [comment]
Thank you very much! It works perfectly :-).
