### ISSUE TITLE
`elpy-shell-send-statement-and-step` hangs when evaluating time-consuming commands

### ISSUE THREAD

**Issue by zhuzhongshu** [jorgenschaefer/elpy#1205]
Hello, 

I find serval spurious changes when I update  elpy to 1.17.0. For example, when I  run command `elpy-shell-send-statement-and-step` , the whole editor will be blockd and I can do nothing until the python shell finish this evaluation.  If I press C-g, it wil send  python shell a `KeyboardInterrupt` and stop the evaluation. 

Besides, `elpy-shell-send-statement-and-step` now seems rely on the  `eval-sexp-fu` package and I have to install it to make elpy-shell commands work.

Thanks!

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Are you using MELPA (as opposed to the official elpy or MELPA stable) to install the package?

Could you do `M-x toggle-debug-on-quit`, hit `C-g` when your editor hangs, and post the resulting backtrace here?

And what makes you think that the command depends on `eval-sexp-fu`?

**Comment by zhuzhongshu** [comment]
I use MELPA to install the elpy and backtrace is as follow:
`Debugger entered--Lisp error: (quit)
  elpy-shell-send-region-or-buffer-and-step()
  funcall-interactively(elpy-shell-send-region-or-buffer-and-step)
  call-interactively(elpy-shell-send-region-or-buffer-and-step)
  elpy-shell--send-with-step-go(elpy-shell-send-region-or-buffer-and-step nil nil)
  elpy-shell-send-region-or-buffer()
  funcall-interactively(elpy-shell-send-region-or-buffer)
  call-interactively(elpy-shell-send-region-or-buffer nil nil)
  command-execute(elpy-shell-send-region-or-buffer)
 `

Before I install `eval-sexp-fu`, the command `shell-send-statement` will raise an error of 
`symbol's value as variable is void: eval-sexp-fu-flash-duration`. So I install package `eval-sexp-fu`. But it seems that `eval-sexp-fu`is incompatiable with `elpy`.

**Comment by jorgenschaefer** [comment]
Nothing in Elpy requires `eval-sexp-fu` – is it possible that something in your configuration or other installed packages do this?

@rgemulla Any ideas on the hanging?

**Comment by zhuzhongshu** [comment]
I find following code in `elpy-shell.el` ,so I think it is because of `eval-sexp-fu`
>;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Flash input sent to shell

;; functions for flashing a region; only flashes when package eval-sexp-fu is
;; loaded and its minor mode enabled
(defun elpy-shell--flash-and-message-region (begin end)
  "Displays information about code fragments sent to the shell.

BEGIN and END refer to the region of the current buffer containing the code being sent. Displays a message with the first line of that region. If `eval-sexp-fu-flash-mode' is active, additionally flashes that region briefly."
  (when (> end begin)
    (save-excursion
      (goto-char begin)
      (end-of-line)
      (if (<= end (point))
          (message "Sent: %s" (string-trim (thing-at-point 'line)))
        (message "Sent: %s..." (string-trim (thing-at-point 'line)))))
    (when (bound-and-true-p eval-sexp-fu-flash-mode)
      (multiple-value-bind (bounds hi unhi eflash) (eval-sexp-fu-flash (cons begin end))
        (eval-sexp-fu-flash-doit (lambda () t) hi unhi)))))

**Comment by rgemulla** [comment]
Thanks for pointing this out!

```eval-sexp-fu``` is used to briefly highlight the region of the Python file sent to the shell. This is only done when ```eval-sexp-fu-flash-mode``` is active. 

@zhuzhongshu I'd appreciate if you could enable this mode and see whether everything works and regions are flashed when being sent.

When the ```eval-sexp-fu``` package is not installed or ```eval-sexp-fu-flash-mode``` is not active, things should still work (without flashing regions, of course). Due to a small bug, the error above occurred then, however. I created PR #1206 to fix this issue.

**Comment by jorgenschaefer** [comment]
Oops, sorry, for some reason my grep here did not return that occurrence :-(

**Comment by jorgenschaefer** [comment]
The bugfix is merged in master, so this should be fixed in the next rebuild on MELPA.

**Comment by rgemulla** [comment]
One more comment: When a Python statement is run and the Python buffer is not visible, ```elpy``` will wait for the statement to finish and post its output in the message area. This is fine (and very useful) when the statement executes quickly. When the statement is long-running, however, Emacs blocks until it finishes. 

To avoid this behavior, either keep the Python shell buffer visible or customize ```elpy-shell-echo-output``` to ```nil```. 

I'll try to document these options soon. We may also change the default value of ```elpy-shell-echo-output``` to ```nil``` to get the old behavior by default.

**Comment by zhuzhongshu** [comment]
Many thanks for your kind help. I will set `elpy-shell-echo-output` to nil~

**Comment by jorgenschaefer** [comment]
> We may also change the default value of ```elpy-shell-echo-output``` to ```nil``` to get the old behavior by default.

Would it be possible to have some kind of timer? If the statement returns within, say, 0.5s, echo, otherwise, don't?

**Comment by rgemulla** [comment]
Perhaps better: make it asynchronous so that it does not block at all. I am on it.

**Comment by rgemulla** [comment]
I created PR #1208 to fix this issue. Now sending something to the shell never blocks. 

@zhuzhongshu With this, you can leave ```elpy-shell-echo-output``` as is (and benefit from it) without the blocking issue.
