### ISSUE TITLE
"go to assignment" function?

### ISSUE THREAD

**Issue by cryptomaniac512** [jorgenschaefer/elpy#1214]
I am not always need to go to definition, for this situations jedi implements "go to assignment". How can I use it with this package?

**Comment by galaunay** [comment]
It's not currently implemented,
I made a pull request to add this feature #1216.
Any idea of a convenient keybinding for this function ?

**Comment by cryptomaniac512** [comment]
Hm... Maybe `C-M-,`?

**Comment by cryptomaniac512** [comment]
Hi there! What about this feature? =)

**Comment by galaunay** [comment]
The code is written :), just waiting for @jorgenschaefer to review and merge it.
If you want it now, you can install elpy from the pull request branch:
[Add-goto-assignment-function](https://github.com/galaunay/elpy/tree/Add-goto-assignment-function).
If you do so and find any bug/unexpected behavior, please post them here #1216 so I can fix it.

**Comment by cryptomaniac512** [comment]
Okay, thanks! You're cool! =)

**Comment by jorgenschaefer** [comment]
The fellow did the same, sorry for the delay :-)
