### ISSUE TITLE
Flake8 not being found if additional arguments provided

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [jorgenschaefer/elpy#1215]
I have been struggling to get Elpy working together with Flake8. I am looking for a reliable setup of Flake8 with Flymake, including some custom flags to the `elpy-check` and `python-check-command` function calls. The custom flags seem to be the issue.

Here is my `elpy-config` output:

```
Virtualenv........: env-name (/home/user/anaconda3/envs/env-name)
RPC Python........: 3.5.2 (/home/user/anaconda3/envs/env-name/bin/python3)
Interactive Python: ipython (/home/user/anaconda3/envs/env-name/bin/ipython)
Emacs.............: 25.3.2
Elpy..............: 1.16.1
Jedi..............: 0.10.2 (0.11.0 available)
Rope..............: Not found (0.10.7 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.3.3
Yapf..............: Not found (0.19.0 available)
Syntax checker....: Not found (flake8 --ignore=F403,F405,E266 --max-line-length=100)

There is a newer version of Jedi available.

[run] python3 -m pip install --upgrade jedi

The yapf package is not available. Commands using this will not work.

[run] python3 -m pip install yapf

The configured syntax checker could not be found. Elpy uses this
program to provide syntax checks of your programs, so you might want
to install one. Elpy by default uses flake8.

[run] python3 -m pip install flake8
```
I tried installing everything, but was told that everything was present.

Working on a different machine, and a different environment, and `flake8` is not being found in `elpy-config`. In the envirnoment (in termnal), running: `flake8 --version` returns:

```
flake8 --version
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.4.5 on Linux
```

I installed Jedi, autopep8 and flake8 in the envirnoment at the same time, then restarted Emacs. Jedi and autopep8 were then found, but flake8 is not found. I then installed `importmagic`, which was immediately found by `elpy-config`, but `flake8` still wasn't.

I noticed that the config output doesn't tell me which version of Flake8 is available, rather just my command which includes the additional arguments (ignoring certain style errors). So I removed the additional arguments, leaving the command as `flake8`, which allowed Elpy to find and use it! But still things like Flymake don't work.

The `elpy-config` shows:

```
....
Emacs.............: 25.1.1
Elpy..............: 1.16.1
Jedi..............: 0.11.0
Rope..............: Not found (0.10.7 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.3.3
Yapf..............: Not found (0.19.0 available)
Syntax checker....: flake8 (/home/user/anaconda3/envs/env-name/bin/flake8)
....
```

Is there a recommended way to combine custom settings for flake8 with Elpy? Via config file, perhaps - but it seems Emacs doesn't like any additional argument being passes to `python-check-command`.

I can run the command: `elpy-check` and I get the expected compilation check output (errors according to my setup) e.g. "E501 line too long". I have seen this similar issue from a few years ago: https://github.com/jorgenschaefer/elpy/issues/878

Otherwise I don't know what I can do to help Elpy.

**Comment by Nicholas-Mitchell** [comment]
I tried using a config file for Flake8, as according to their documentation: putting a file in my home directory like this:

```
[flake8]
ignore = E226
max-line-length = 100
```

Unfortunately this is not being taken into account automagicay flake8 (called from Elpy).

I changed the `python-check-command` to include the `--config=/path/to/config/file/flake8` flag, but this causes Flymake to crash. The error message hints that the entire command is being interpreted as the name of the programme to execute, not as the programme plus some arguments.

I then tried setting hard paths to the base installation of flake8 (not in an env), but this lead to Flymake simply saying it cannot run due to a condiguration error.

@jorgenschaefer - any ideas?  How do this set up?

**Comment by jorgenschaefer** [comment]
Make sure to use the correct pip command corresponding to the virtualenv you use. Make sure that Emacs has the correct `PATH` to see the `flake8` binary, not just your terminal. Does that help?

**Comment by Nicholas-Mitchell** [comment]
OP here - I definitely needed a primer on where to put setup files in general. Also learnt that you can mix the settings of various parsers into one file. I now use something like this (silly example):

```
[pep8]
max-line-length=110

[yapf]
based_on_style = pep8
spaces_before_comment = 4
column_limit = 110

```

Thanks for the help @jorgenschaefer
