### ISSUE TITLE
Discussion: automated function/method generation, code prototype included

### ISSUE THREAD

**Issue by vkazanov** [jorgenschaefer/elpy#1218]
I've been playing with an idea of automatically generating stub functions when definitions are not found by `(elpy-goto-definition)`. My Elisp felt useful when writing code in a top-down manner.

Now I wonder if there's interest in such code on the Elpy's maintainers side. Obviously the prototype code can be improved (e.g., extended to support class methods) and polished.

Here's the prototype code:

```emacs-lisp

(defconst vlk-varname-re "[a-zA-Z]\\w*")

(defun vlk-implement-function (name arglist)
  (interactive
   (list
    (read-string "Name: " (vlk-get-def-name))
    (read-string "Arglist: " (vlk-get-arglist))))
  (when (and name arglist)
    (vlk-find-insert-place)
    (open-line 2)
    (insert (vlk-format-function name arglist))))

(defun vlk-get-def-name ()
  (with-syntax-table python-dotty-syntax-table
    (when-let ((funname (thing-at-point 'symbol)))
      (substring-no-properties funname))))

(defun vlk-get-arglist ()
  (save-excursion
    (with-syntax-table python-dotty-syntax-table
      (when (symbol-at-point)
        (end-of-thing 'symbol)
        (skip-chars-forward "[:space:]")
        (when-let ((sexp (thing-at-point 'sexp)))
          (vlk-format-args
           (vlk-parse-arg-str sexp)))))))

(defun vlk-parse-arg-str (arg-str)
  (split-string (substring-no-properties arg-str 1 -1)
                "," t split-string-default-separators))

(defun vlk-format-args (arg-list)
  (let ((counter 0))
    (cl-flet* ((varname-p (str) (string-match-p vlk-varname-re arg))
               (format-arg (arg) (if (varname-p arg) arg
                                   (incf counter)
                                   (concat "arg" (number-to-string counter)))))
      (string-join (mapcar #'format-arg arg-list) ", "))))

(defun vlk-format-function (name args)
  (format "def %s(%s):\n    pass" name args))

(defun vlk-format-method (name args)
  (format "def %s(self, %s):\n    pass" name args))

(defun vlk-find-insert-place ()
  (while (not (equal 0 (current-indentation)))
    (if (python-info-current-defun)
        (beginning-of-defun)
      (python-nav-beginning-of-block)))
  (beginning-of-line))
```

The entry point  is `(vlk-implement-function)`, which tries to get the current symbol, checks if there's an arglist after the symbol - and inserts  a function stub right above the current function, or a above code block if there's no current defun around the point.

Thanks you for Elpy, BTW, it's awesome.

**Comment by rgemulla** [comment]
Another option might be to use ```yasnippet```. In my point of view, this functionality, if integrated, should be disabled by default.

**Comment by vkazanov** [comment]
@rgemulla The difference with `yasnippet` is that this code automatically extracts both args and the function name, formats 'em and finds a suitable function template insertion point, with no additional typing needed.

`yasnippet` needs a bunch of additional text to be written (args, funname) while this code doesn't.

And, surely, this is just a prototype meant only to ignite a discussion.

**Comment by rgemulla** [comment]
Yes! This was by no means meant to discourage this work. 

What I actually intended to say (but failed to express clearly) is that yasnippet could be used to insert, say, the function definition above the current function with the placeholders being prefilled as you do above (and an option for the user to change it in the usual yasnippet way).

Also for discussion: I feel that such a feature should not be bound to goto-definition, but to a separate command. Otherwise, things can get confusing (in particular, if there is a definition somewhere but goto-definition fails to find it).

**Comment by vkazanov** [comment]
Well... I sort of agree about having it switched on for `goto-definition` all the time. It's literally impossible to find definitions in Python reliably. 

But still I want to avoid introducing a bunch of `implement` function as the whole point is to make this as automated as possible and avoid additional, em, cognitive load with new commands and key bindings. 

And yes, `yasnippet` might be reasonable. Here I just came up with the quickest possible solution to find out if people are interested in such things in one way or another.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the contribution and ideas! Would this make sense as a separate package?

Incidentally, I think you can use yasnippet and even have it pre-populate fields with defaults, nor not require any typing at all.

**Comment by vkazanov** [comment]
@jorgenschaefer 
Yes, it might be reasonable to have a separate package. 

Initially I thought I might need some code from Elpy but currently only the builtin `python.el` + `yasnippets` are used.

I am slowly working on a cleaner version of the prototype above, wanna dogfood it for a while first, share next, either as a separate package, or a PR for Elpy.

**Comment by jorgenschaefer** [comment]
Sounds great! :-)

**Comment by vkazanov** [comment]
I've actually ended up implementing a separate package ([elpygen](https://github.com/vkazanov/elpygen)) - no code from Elpy was used.

Thanks for the tips and the joy that Elpy has become! I think this issue can be closed now.

**Comment by rgemulla** [comment]
Looks nice! Thanks a lot!
