### ISSUE TITLE
Process filter Error on Elpy

### ISSUE THREAD

**Issue by kenyamash** [jorgenschaefer/elpy#1219]
Hello,

I have problem on Elpy environment.
I saw folowd error when execute my python code.
"error in process filter: symbol's function definition is void :python-shell-comint-end-of-output-p"

*How to Reproduce the problem
1)Run any python source code byy (C-c C-c)
2)Checking syntax by (C-C C-v)
3)Re-run any python source code byy (C-c C-c)
 
Please help me!

*My environment is 
  Emacs 25.1 on Windows10.
*Here is my init.el:
 '(custom-enabled-themes (quote (manoj-dark)))
 '(elpy-syntax-check-command "C:\\Python/Scripts/flake8")
 '(flycheck-display-errors-function (function flycheck-pos-tip-error-messages))
 '(python-check-command "C:\\Python\\Scripts\\flake8")
 '(python-shell-exec-path (quote ("C:\\Python\\Scripts")))
 '(python-shell-interpreter "C:\\Python\\python.exe")
 '(show-paren-mode t)
 '(tool-bar-mode nil))
*Elpy Configuration
Virtualenv........: None
RPC Python........: 3.6.3 (c:/WINDOWS/py.exe)
Interactive Python: C:\Python\python.exe (c:/Python/python.exe)
Emacs.............: 24.5.1
Elpy..............: 1.17.0
Jedi..............: 0.11.0
Rope..............: Not found (0.10.7 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.3.3
Yapf..............: 0.19.0 (0.20.0 available)
Syntax checker....: flake8.exe (c:/Python/Scripts/flake8.exe)
*Debbuger message
Debugger entered--Lisp error: (void-function python-shell-comint-end-of-output-p)
  python-shell-comint-end-of-output-p("<_ast.Expr object at 0x000001DDF87AF080>\n----\n1\n----\n4\n----\n9\n123\nrange(1, 10, 2)\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\nc:\\tmp\nabc\\dewf\n__file__\n------\nc:\\tmp\\__file__\n__path__\nc:\\tmp\nc:\\tmp\\iii.txt\n2017-11-18 17:19:21,497 - simple_example - DEBUG - debug message\n2017-11-18 17:19:21,497 - simple_example - DEBUG - debug message\n2017-11-18 17:19:21,497 - simple_example - INFO - info message\n2017-11-18 17:19:21,497 - simple_example - INFO - info message\n2017-11-18 17:19:21,498 - simple_example - WARNING - warn message\n2017-11-18 17:19:21,498 - simple_example - WARNING - warn message\n2017-11-18 17:19:21,498 - simple_example - ERROR - error message\n2017-11-18 17:19:21,498 - simple_example - ERROR - error message\n2017-11-18 17:19:21,498 - simple_example - CRITICAL - critical message\n2017-11-18 17:19:21,498 - simple_example - CRITICAL - critical message\n>>> ")
  elpy-shell--shell-output-filter("<_ast.Expr object at 0x000001DDF87AF080>\n----\n1\n----\n4\n----\n9\n123\nrange(1, 10, 2)\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\nc:\\tmp\nabc\\dewf\n__file__\n------\nc:\\tmp\\__file__\n__path__\nc:\\tmp\nc:\\tmp\\iii.txt\n2017-11-18 17:19:21,497 - simple_example - DEBUG - debug message\n2017-11-18 17:19:21,497 - simple_example - DEBUG - debug message\n2017-11-18 17:19:21,497 - simple_example - INFO - info message\n2017-11-18 17:19:21,497 - simple_example - INFO - info message\n2017-11-18 17:19:21,498 - simple_example - WARNING - warn message\n2017-11-18 17:19:21,498 - simple_example - WARNING - warn message\n2017-11-18 17:19:21,498 - simple_example - ERROR - error message\n2017-11-18 17:19:21,498 - simple_example - ERROR - error message\n2017-11-18 17:19:21,498 - simple_example - CRITICAL - critical message\n2017-11-18 17:19:21,498 - simple_example - CRITICAL - critical message\n>>> ")
  comint-output-filter(#<process Python> "<_ast.Expr object at 0x000001DDF87AF080>\n----\n1\n----\n4\n----\n9\n123\nrange(1, 10, 2)\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\nc:\\tmp\nabc\\dewf\n__file__\n------\nc:\\tmp\\__file__\n__path__\nc:\\tmp\nc:\\tmp\\iii.txt\n2017-11-18 17:19:21,497 - simple_example - DEBUG - debug message\n2017-11-18 17:19:21,497 - simple_example - DEBUG - debug message\n2017-11-18 17:19:21,497 - simple_example - INFO - info message\n2017-11-18 17:19:21,497 - simple_example - INFO - info message\n2017-11-18 17:19:21,498 - simple_example - WARNING - warn message\n2017-11-18 17:19:21,498 - simple_example - WARNING - warn message\n2017-11-18 17:19:21,498 - simple_example - ERROR - error message\n2017-11-18 17:19:21,498 - simple_example - ERROR - error message\n2017-11-18 17:19:21,498 - simple_example - CRITICAL - critical message\n2017-11-18 17:19:21,498 - simple_example - CRITICAL - critical message\n>>> ")
  accept-process-output(#<process Python>)
  #[0 "\306\307 \210\203

**Comment by rgemulla** [comment]
This is a compatibility issue with python.el of Emacs 24. Thanks for reporting! 

I added a fix to PR #1208. Until this PR is merged, setting ```elpy-shell-echo-output``` to nil should fix this issue, too.

**Comment by kenyamash** [comment]
Thank you Rgemulla.
I have fixed my problem according your advice!.
(setq  elpy-shell-echo-output nil)
