### ISSUE TITLE
No syntax check when I save a python file

### ISSUE THREAD

**Issue by Dicridon** [jorgenschaefer/elpy#1220]
Hi there,
I work on two computers, one is openSUSE and one is Ubuntu.
I copied my emacs.d from openSUSE to Ubuntu days ago. However, elpy doesn't do syntax checking when I press C-x C-s automatically in Ubuntu, I need to press C-c C-v to invoke syntax checking. 
Below is my settings 

![screenshot from 2017-11-23 11-37-28](https://user-images.githubusercontent.com/24477137/33158331-0db19c06-d044-11e7-80f0-4d12295eba28.png)
Can you give me any tips?

**Comment by Dicridon** [comment]
Well, Emacs and Elpy suddenly worked quite good, I don't know why.

**Comment by jorgenschaefer** [comment]
Emacs figured out it likes you, and change its mind! :-D Enjoy Elpy!
