### ISSUE TITLE
Appropriate configuration to use elpy and ipython3?

### ISSUE THREAD

**Issue by avigan** [jorgenschaefer/elpy#1221]
Hello,

I am having some issues with elpy and ipython3, in particular when using matplotlib interactively (see below). I went through the documentation on readthedocs but I cannot really find how to configure emacs and elpy to make it work properly with ipython3.

First of all, here is my setup running on Mac OS X 10.13.1:
```
Virtualenv........: None
RPC Python........: 3.6.3 (/Users/avigan/anaconda3/bin/python)
Interactive Python: jupyter (/Users/avigan/anaconda3/bin/jupyter)
Emacs.............: 25.3.1
Elpy..............: 1.17.0
Jedi..............: 0.10.2 (0.11.0 available)
Rope..............: 0.10.7
Importmagic.......: 0.1.7
Autopep8..........: 1.3.3
Yapf..............: 0.19.0 (0.20.0 available)
Syntax checker....: flake8 (/Users/avigan/anaconda3/bin/flake8)
```

And here are the lines concerning elpy in my ```.emacs``` (see #1041):
```lisp
(elpy-enable)

(setq python-shell-interpreter "ipython3"
      python-shell-interpreter-args "--simple-prompt --pprint")
(setq elpy-shell-send-region-or-buffer 0)
(setq elpy-shell-switch-to-shell 0)

(setenv "JUPYTER_CONSOLE_TEST" "1")
(add-to-list 'python-shell-completion-native-disabled-interpreters "ipython3")
(add-to-list 'python-shell-completion-native-disabled-interpreters "jupyter")
(setq
 python-shell-prompt-detect-enabled nil
 python-shell-interpreter "jupyter"
 python-shell-interpreter-args "console"
 )
```

This configuration was working fine until recently when I upgraded emacs and/or my conda installation. Now when I start an IPython shell from emacs I get the following error:
```python
[IPKernelApp] WARNING | Config option `autoindent` not recognized by `ZMQInteractiveShell`.
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x111ebb598>)
Traceback (most recent call last):
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 265, in enter_eventloop
    self.eventloop(self)
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/ipykernel/eventloops.py", line 277, in loop_cocoa
    show.mainloop()
AttributeError: 'function' object has no attribute 'mainloop'
Jupyter console 5.2.0

Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 18:10:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
```

The problem is that now matplotlib (v2.1.0) seems completely unable to display any window. Nothing happens when I do this:

```python
In [1]: import matplotlib.pyplot as plt

In [4]: %matplotlib osx

In [7]: plt.figure(0)
Out[7]: <matplotlib.figure.Figure at 0x10d7c63c8>

In [8]: plt.plot(np.arange(100))
Out[8]: [<matplotlib.lines.Line2D at 0x113ee3b00>]
```
Even if I use ```plt.show()```, which I did not have to use before, nothing happens...

Maybe it's me not using elpy properly... Should I just use the standard python shell instead of ipython?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. I have no idea what matplotlib does usually. Does this work in stock Emacs without Elpy installed?

**Comment by avigan** [comment]
If I do not activate elpy but still use ```ipython3``` as the shell interpreter the above code works. However there is the issue described in ticket #1041: the matplotlib windows are frozen. The configurations lines that solve this problem are:

```lisp
(setq
 python-shell-interpreter "jupyter"
 python-shell-interpreter-args "console"
 )
```

But these lines also seem to be the ones that trigger the error message that I describe above. So I don't really think it is a matplotlib issue.

**Comment by jorgenschaefer** [comment]
I have no idea I'm afraid. The IPython/Jupyter people have done a whole lot of stuff with IPython that makes it hard to use from Emacs. I do not use IPython/Jupyter at all, so I really have no idea what Elpy would have to do there. :-(

**Comment by avigan** [comment]
Ok, thanks for letting me know. I will maybe ask around in the IPython community.

From that I understand that elpy is supposed to be used with the standard python shell, correct?

**Comment by jorgenschaefer** [comment]
> From that I understand that elpy is supposed to be used with the standard python shell, correct?

I use it with standard CPython, which means it's easier for me to help there. ;-) Elpy uses `python.el` which comes with Emacs. That mode supports ipython, and Elpy tries to make it a bit easier to use that. There's nothing IPython-specific Elpy does.

**Comment by avigan** [comment]
Ah ok, I understand better now. So I should definitely seek help somewhere else then :) Thanks a lot.

**Comment by jorgenschaefer** [comment]
Sorry for the trouble – if you find out what the problem is, and if Elpy can make this easier for the user, I'm more than happy to change Elpy to do so!

**Comment by rgemulla** [comment]
As another piece of information: I am using elpy with the Jupyter console and matplotlib without any issues (on both Windows and Linux). I do not use ```elpy-enable```; my setup is:

```elisp
(setenv "IPY_TEST_SIMPLE_PROMPT" "1")
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"))
```

To plot, I use
```python
%matplotlib
import matplotlib.pylab as plt
plt.plot([1,2,3])
```

Your error message refers to a package called ```tornado```. Does it work if you uninstall this package?

**Comment by avigan** [comment]
@rgemulla unfortunately that doesn't work for me on Mac OS, but it works fine in linux. It's probably a platform specific issue then. I've opened a ticket on the jupyter repository.

Unfortunately I cannot remove this ```tornado``` package: all the ```ipython```, ```jupyter``` or ```matplotlib``` packages depend on it! I've opened a ticket (https://github.com/tornadoweb/tornado/issues/2203)
