### ISSUE TITLE
Green testrunner

### ISSUE THREAD

**Issue by siwica** [jorgenschaefer/elpy#1222]
Would it be possible to support the [green testrunner](https://github.com/CleanCut/green) that allows for colored test output?

**Comment by galaunay** [comment]
As it is not so different from the unittest runner, it is fairly easy to implement, 
I made a PR #1233.
Could you test it to see if it works as expected ?
Apparently coverage woks as well by setting `(setq elpy-test-green-runner-command '("green" "-r"))`, could you confirm ?

**Comment by galaunay** [comment]
Discussion continue in #1233.
