### ISSUE TITLE
flymake-proc alway running while edit python file

### ISSUE THREAD

**Issue by chenpoyang** [jorgenschaefer/elpy#1223]
while edit python file in elpy-mode, an applet always pop up(ps aux | grep python), in emacs, it's flymake-proc(flake8 maybe), and Elpy Output:
<pre>
Output from Backend

There was some unexpected output from the Elpy backend. This is usually some
module that does not use correct logging, but might indicate a configuration
problem.

Output

(process:86782): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
</pre>
LC_ALL is: en_US.UTF-8
LANG is: en_US.UTF-8
how to fix it?

**Comment by galaunay** [comment]
Just to be sure this is an Elpy related problem:
 - Is this also appearing for other gtk applications ?
 - the `Gtk-WARNING **: Locale not supported by C library.` is well known, have you tried some of the solutions proposed for example [here](https://askubuntu.com/questions/359753/gtk-warning-locale-not-supported-by-c-library-when-starting-apps-from-th#359932).

As this is only a warning, I suppose that flake8 still works ?
So you are just annoyed by the pop-up ?

If it is really annoying, you can add the following snippet to your "init.el" to prevent elpy for popping up messages (as a temporary solution):
```Elisp
(defun elpy-rpc--handle-unexpected-line (line)
  "Handle an unexpected line from the backend.

This is usually an error or backtrace."
  (message "[Elpy backend output] %s" line)) 
```
(should work, untested)

**Comment by chenpoyang** [comment]
still pop-up an applet, after i add the code to init.el:
<pre>
(defun elpy-rpc--handle-unexpected-line (line)
  "Handle an unexpected line from the backend.

This is usually an error or backtrace."
  (message "[Elpy backend output] %s" line)) 
</pre>

emacs Elpy Output is:
<pre>
Output from Backend

There was some unexpected output from the Elpy backend. This is usually some
module that does not use correct logging, but might indicate a configuration
problem.

Output

(process:54183): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
2017-12-06 08:01:33.077 Python[54183:9772687] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
</pre>
the applet in docky's image like:<a href="https://www.google.as/search?hl=en&biw=1440&bih=766&tbm=isch&sa=1&ei=TzYnWoWsJIj78QXy-qPwDQ&q=python+rocket&oq=python+rocket&gs_l=psy-ab.3..0i24k1l8.55243.56416.0.56756.7.7.0.0.0.0.260.698.0j1j2.3.0....0...1c.1.64.psy-ab..4.3.696...0j0i67k1.0.xqlcIttdcC8#imgrc=ahNJ64TnUy_1MM:">python applet<a/>

**Comment by galaunay** [comment]
You should add it after Elpy is loaded, to overwrite the real `python-shell-send-region`.
But as I said, this is a temporary solution, you really should go to the bottom of your gtk error.

**Comment by chenpoyang** [comment]
while run emacs in terminal instead of xemacs, just a python process launch(an applet pop):
<pre>
2017-12-06 08:01:33.077 Python[54183:9772687] *** WARNING: Method userSpaceScaleFactor 
in class NSView is deprecated on 10.7 and later. It should not be used in new applications. 
Use convertRectToBacking: instead.
</pre>
the process id is :54183

so the problem may be:
<pre>
There was some unexpected output from the Elpy backend. This is usually some
module that does not use correct logging, but might indicate a configuration
problem.
</pre>

**Comment by chenpoyang** [comment]
i remove the modules i recently installed, and reinstall it , it works, it doesn't pop an applet.
<pre>
sudo pip install rope
sudo pip install jedi
sudo pip install flake8
sudo pip install importmagic
sudo pip install autopep8
sudo pip install virtualenv
sudo pip install pygtksourceview
sudo pip install pygtk
sudo pip install scrapy
sudo pip install argparse
sudo pip install sh
sudo pip install suds
sudo pip install requests
sudo pip install pelican
sudo pip install markdoc
sudo pip install pep8
sudo pip install Pygments
sudo pip install itertools
sudo pip install paramiko
sudo pip install selenium
sudo pip install lxml
sudo pip install mechanize
sudo pip install pycurl
sudo pip install Fabric
sudo pip install xmltodict
sudo pip install urllib3
sudo pip install ipdb
sudo pip install redis
sudo pip install pymongo
sudo pip install mako
sudo pip install numpy
sudo pip install matplotlib
sudo pip install scrapy
sudo pip install tornado
sudo pip install web.py
sudo pip install web2py
sudo pip install uliweb
sudo pip install flask
sudo pip install twisted
sudo pip install bottle
sudo pip install cherrypy
sudo pip install vinta
sudo pip install gtksourceview
sudo pip install pygments
sudo pip install elpy
</pre>

and there no pygtksourceview, and pygtk in mac, may be it's the problem.
