### ISSUE TITLE
delete *flymake.py

### ISSUE THREAD

**Issue by yitang** [jorgenschaefer/elpy#1228]
Hi, somehow i have a couple of *flymake.py next to *.py. When I use C-c C-t for running unit test, i got errors saying SyntaxError: unexpected EOF while parsing for the *flymake.py files.

I need to manually deleted all the *flymake.py but sometimes they come back.... there's must be a way to stop saving those files... what should i do? 

Thanks, 

this is my config.

Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/usr/local/bin/python3)
Interactive Python: ipython3 (/usr/local/bin/ipython3)
Emacs.............: 25.1.50.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0 (0.11.0 available)
Rope..............: Not found (0.10.7 available)
Importmagic.......: 0.1.7
Autopep8..........: Not found (1.3.3 available)
Yapf..............: 0.11.0 (0.20.0 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH.

There is a newer version of Jedi available.

[run] python3 -m pip install --user --upgrade jedi

The autopep8 package is not available. Commands using this will not
work.

[run] python3 -m pip install --user autopep8

There is a newer version of the yapf package available.

[run] python3 -m pip install --user --upgrade yapf

Options

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report! These files are created and usually also deleted by flymake, a mode that comes with Emacs. I do not know why they stay around for you, sounds like a bug in flymake to me. You can report the bug there with `M-x report-emacs-bug`. As an intermediate fix, you can also just switch to flycheck (install that package first, of course):

```Lisp
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))
```

**Comment by yitang** [comment]
thank you very much for quick response and the workaround!
