### ISSUE TITLE
Remove importmagic

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#1230]
importmagic creates a lot of problems because it tries to import all modules. Many modules do not know how to deal with this, and either emit spurious output, cause CPU hogging or even crash Python altogether.

As sad as it is, since importmagic adds some nice features, in the current state of affairs it's not a good solution. At the bare minimum, the suggestion for installation should be removed. Probably all code related to importmagic can be removed as well.

**Comment by ChillarAnand** [comment]
I agree importmagic creates a lot of problems. Importing all modules and CPU hogging should go away with new version of importmagic. 

Can we have importmagic disabled by default and let users enable it if required?

**Comment by jorgenschaefer** [comment]
Tricky. Removing the recommendation to install it would probably solve most things already. We can use it if it's installed. But I don't like semi-dead code.

**Comment by gopar** [comment]
I'm in favor of removing `importmagic` completely. 

If it's decided to remove it. I can submit a PR.

@rgemulla @galaunay thoughts?

**Comment by galaunay** [comment]
Personally, I find the feature really useful but had to deactivate it because of high CPU usage.
I vote for removing it as well.
If a new version of importmagic fix the current issues, we can still retrieve the code from the repo...

**Comment by ChillarAnand** [comment]
Instead of removing importmagic completely, can we remove it from installation instructions for now? 

If it is having problems with the next version of importmagic as well, then we can remove it completely?

**Comment by jorgenschaefer** [comment]
> Instead of removing importmagic completely, can we remove it from installation instructions for now?

> If it is having problems with the next version of importmagic as well, then we can remove it completely?

What does the next version of imagemagic change that might fix the issues we have seen?

(We can easily revert a commit later when things get fixed)

**Comment by ChillarAnand** [comment]
Sure. It has module/project wise caching enabled. It should reduce CPU usage. Spurious output is still there.

**Comment by jorgenschaefer** [comment]
Actively importing random modules is my main issue with importmagic.

**Comment by ChillarAnand** [comment]
Hmm.. I guess it is better to remove importmagic then.

**Comment by galaunay** [comment]
Associated PR: #1242

**Comment by ycz0926** [comment]
is there any package that can replace the importmagic?

**Comment by ChillarAnand** [comment]
@ycz0926 Please checkout https://github.com/anachronic/importmagic.el, a stand alone package which supports importmagic.

**Comment by ycz0926** [comment]
@ChillarAnand ok,3ku

**Comment by ChillarAnand** [comment]
@ycz0926 It is very unlikely that elpy will support importmagic in near future and there are no other options. Can you open a feature request in importmagic.el repo?

**Comment by ycz0926** [comment]
@ChillarAnand ok,i will

**Comment by kootenpv** [comment]
Where is the continuation of this going? I understand the decision, but I'm looking for a new solution :)

**Comment by galaunay** [comment]
I tried [importmagic.el](https://github.com/anachronic/importmagic.el) recently.
It works well, but importmagic still consume a non-negligible amount of memory...

@emanuele open an [issue](https://github.com/alecthomas/importmagic/issues/47) to get some help from importmagic, but they didn't answered yet.

**Comment by kootenpv** [comment]
@galaunay my bad, I thought it would also fix the sorting of the imports, but I think it doesn't do that.

**Comment by galaunay** [comment]
Importmagic does that, but also try to add missing imports.

To only sort imports, the [isort](https://pypi.python.org/pypi/isort) seems to work quite well.

This is something that can be added to elpy without too much trouble.

**Comment by ameliesc** [comment]
> Importmagic does that, but also try to add missing imports.
> 
> To only sort imports, the [isort](https://pypi.python.org/pypi/isort) seems to work quite well.
> 
> This is something that can be added to elpy without too much trouble.

I am wondering whether there is any plan of including isort? Unfortunately the exisiting python-isort.el package doesn't work with elpy.
