### ISSUE TITLE
LD_LIBRARY_PATH no match

### ISSUE THREAD

**Issue by MrWanter** [jorgenschaefer/elpy#1237]
Hi! I got a problem that with getenv command for LD_LIBRARY_PATH, prompts no match, I tried the method in #411, but still not work.

**Comment by MrWanter** [comment]
I manually set the path in init file:
```
(setenv "LD_LIBRARY_PATH"
  (concat
   "/home/cc/Downloads/fast-rcnn/OpenCV/opencv/release/lib" ";"
   "/home/cc/Downloads/software/envs/py2/lib" ";"
   "/usr/local/cuda-7.5/lib64" ";"
   (getenv "LD_LIBRARY_PATH")
  )
)

(setenv "PYTHONPATH"
(concat 
"/home/cc/Downloads/caffe/python" ";"
"/home/cc/Downloads/fast-rcnn/caffe-fast-rcnn/python" ";")
)
```
and it works, but problem is, how to set elpy to automatically load those PATH from somewhere, like shell?

**Comment by galaunay** [comment]
I think that python shells inherit environment from Emacs, which inherits environment from the shell.
So if Emacs is run from bash (most probable case), adding:
```bash
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/cc/Downloads/fast-rcnn/OpenCV/opencv/release/lib:/home/cc/Downloads/software/envs/py2/lib:/usr/local/cuda-7.5/lib64"
export PYTHONPATH="$PYTHONPATH:/home/cc/Downloads/caffe/python:/home/cc/Downloads/fast-rcnn/caffe-fast-rcnn/python"
```
to your '.bashrc' (then restarting Emacs) should be enough.

If you want to pollute your bash environment, you can specify environment variables to be loaded in python shell by customizing `python-shell-process-environment`.

Hope it helps.

**Comment by galaunay** [comment]
@MrWanter  Did this solve your issue ?

**Comment by MrWanter** [comment]
yes, I set the path in init file like this:

**Comment by galaunay** [comment]
Ok, Can we close this issue then ?

**Comment by galaunay** [comment]
Please reopen if you need any additional information.
