### ISSUE TITLE
Run python script with elpy

### ISSUE THREAD

**Issue by MrWanter** [jorgenschaefer/elpy#1238]
The problem is simply, I got a` *.py` file, with `C-c C-c`, I cannot run it, prompts 
```
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
Removed if __name__ == '__main__' construct, use a prefix argument to evaluate
```
and the buffer for python intepreter gives:
```
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> >>> >>> >>> >>> >>> 
```
I can execute the script with `execfile(*.py)`, but why C`-c C-c` does not work? And I have viewed the elpy documentation, seems there is not much about write and run code on remote host/server, can someone suggest some reference? Thanks very much!

**Comment by galaunay** [comment]
Could you attach the not working script, so I can try on my side ?

Maybe useful information:
As said in the messages, if your code is in a `__name__ == '__main__'` construct:
```Python
if __name__ == '__main__':
    print('Hello World')
```
you will need to use a prefix argument (*i.e.* `C-u C-c C-c`) to run it.

**Comment by MrWanter** [comment]
Thank you, C-u C-c C-c works! I just searched the document of elpy, got this:
```
The functions for sending the entire buffer have special support for avoiding accidental code execution, e.g.:

C-c C-y r (elpy-shell-send-region-or-buffer)
Send the the active region (if any) or the entire buffer (otherwise) to the Python shell and keep point position.

When sending the whole buffer, this command will also escape any uses of the if __name__ == '__main__' idiom, to prevent accidental execution of a script. If you want this to be evaluated, pass a prefix argument with C-u.

Also bound to C-c C-c.
```
but I'm not much clear about the `avoiding accidental code execution`, is there some example about this or references? Also, it seems that passing arguments to the execution of a script is not easy, could you please suggest some methods to do this?

**Comment by galaunay** [comment]
Sometimes you want to evaluate the code inside `__name__ == '__main__'` (when calling the file as a script), and sometimes you don't (when you just want to import the functions/classes present in this file).
Elpy allows to do both: `C-c C-c` to evaluate the buffer but not the code inside `__name__ == '__main__'`, and  `C-u C-c C-c` to evaluate everything.

As far as I known, Elpy does not provide a way of passing arguments to python scripts.
But you can take a look at `compile` and `run-python` functions.

For example, the following snippet based on `run-python` should do what you want:
```Lisp
(defun elpy-shell-send-file-with-args (args)
  "Send current buffer to python shell with ARGS.

kill the python shell if already running."
  (interactive "sArguments: ")
  (let* ((bufname (format "*%s*" (python-shell-get-process-name nil)))
         (proc (get-buffer-process bufname)))
    (when proc
        (delete-process proc)))
  (run-python (format "%s -i %s %s"
                      (python-shell-calculate-command)
                      (buffer-name)
                      args)
              nil t))
```

**Comment by jorgenschaefer** [comment]
If the behavior seems weird, remember: Elpy does not run Python scripts, it evaluates the contents of the buffer in a Python shell. There is no such a thing as "arguments" in such a scenario.

**Comment by MrWanter** [comment]
Thank you, so is there downside for working on some larger project on elpy compare to directly working on shell?

**Comment by MrWanter** [comment]
prompts `python-shell-calculate-command` definition void

**Comment by MrWanter** [comment]
@jorgenschaefer What do you suggest for passing argument for a script, since it is very often for runnning python scripts.

**Comment by jorgenschaefer** [comment]
I would suggest making scripts only very thin wrappers around modules. Write unit tests for the modules. That's a much better test experience than running some script.

If you have to write and execute scripts, use `M-x compile` as galaunay suggested above.

**Comment by MrWanter** [comment]
I have tried writing wrapper for the job, solve my current problem, may think about better choice. And another thing I'm really curious about, but may have not enough knowledge and experience is to work with a remote server/host on elpy/emacs, you know, for some larger projects, is there some advice or hint or references, thanks:)

**Comment by jorgenschaefer** [comment]
Depends on what you mean with  "work with a remote server/host".

Run program remotely, debug locally? Tricky. No idea. Use a remote editor if you must.
Run editor locally, edit remotely? Don't. Edit and test locally, deploy remotely. If you must, use sshfs.

**Comment by MrWanter** [comment]
Yeah, Edit and test locally, deploy remotely, I'll try sshfs, many thanks:)

**Comment by jorgenschaefer** [comment]
I can recommend tools like ansible and/or docker for deployments. Ideally, make your CI server create and test a container and deploy that.

**Comment by MrWanter** [comment]
Thank you for pointing the way, I'll learn and have try:)

**Comment by gopar** [comment]
Closing since solved
