### ISSUE TITLE
Project root change when open file in different directory

### ISSUE THREAD

**Issue by MrWanter** [jorgenschaefer/elpy#1240]
It seems that `M-x elpy-set-project-root` gives different path when open files in different directory, e.g. open file in `~/Downloads/fast-rcnn/`, gives `~/Downloads/fast-rcnn/`, open file in `~/Downloads/fast-rcnn/tools/`, gives ` ~/Downloads/fast-rcnn/tools/`, I thought the project root should be fixed for specific project.

**Comment by jorgenschaefer** [comment]
Emacs does not have a concept of "a project". There is no way for Elpy to know that you intend those two buffers to be part of the same project. Elpy tries to guess the project root based on some markers (e.g. a `.git` directory). If they are missing, Elpy assumes the project root is the current directory of the opened file.

Does this answer your question? :-)

**Comment by MrWanter** [comment]
seems elpy is so  smart, but the command `elpy-set-project-root`, what is it used for?

**Comment by jorgenschaefer** [comment]
If Elpy is not smart enough, you can override its decision for the current buffer with it :-D
