### ISSUE TITLE
Navigation: Definition not found

### ISSUE THREAD

**Issue by MrWanter** [jorgenschaefer/elpy#1241]
My question may be naive, when using `M-.` , I got Navigation: `No definition found`, but I don't know to cop with this, I have build `TAGS` with `ctags -R .` in the project root directory`~/Downloads/fast-rcnn`, and I have set TAGS path in .emacs as:
```
(setq tags-table-list
           '("~/Downloads/fast-rcnn"))
```
And I previously used seperate IDEs like `Spyder`, seems they can very fluently jump to the definition without much configuration, just properly install the IDE, then go-definition just works very well, even if there is multiple same named items, it can find the right one(unlike vim, which may prompts for selection), can `elpy/emacs` also works well like that?

**Comment by jorgenschaefer** [comment]
Elpy does not use tags. What's the output of `M-x elpy-config`?

**Comment by MrWanter** [comment]
run `M-x elpy-config` the output is:
```
Elpy Configuration

Virtualenv........: py2 (/home/cc/Downloads/software/envs/py2)
RPC Python........: 2.7.13 (/home/cc/Downloads/software/envs/py2/bin/python)
Interactive Python: python (/home/cc/Downloads/software/envs/py2/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.17.0
Jedi..............: 0.10.2 (0.11.0 available)
Rope..............: 0.9.4 (0.10.7 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.3.3 available)
Yapf..............: Not found (0.20.0 available)
Syntax checker....: flake8 (/home/cc/Downloads/software/envs/py2/bin/flake8)

There is a newer version of Rope available.

[run] python -m pip install --upgrade rope

There is a newer version of Jedi available.

[run] python -m pip install --upgrade jedi

The importmagic package is not available. Commands using this will not
work.

[run] python -m pip install importmagic

The autopep8 package is not available. Commands using this will not
work.

[run] python -m pip install autopep8

The yapf package is not available. Commands using this will not work.

[run] python -m pip install yapf
```

**Comment by jorgenschaefer** [comment]
In your case, Elpy will use the `rope` library to find definitions. As Python is a rather dynamic language, it's not always easy to find a definition, especially when this involves modules written in C (scipy/numpy are notoriously hard, for example). Rope (and Jedi) try their best, but sometimes, they fail.

You can try `M-: (setq elpy-rpc-backend "jedi")` and `M-x elpy-rpc-restart` and see if that makes things work better. If it does, uninstall Rope.

**Comment by MrWanter** [comment]
Thank you, I have just changed it to jedi, better than rope, but still a lot of items cannot be finded in definition, I tried same scripts on Spyder, seems it can find all definitions, so I'm confused since spyder(other seperate IDE) can achieve that, why elpy/emacs/vim does not adopt same methods for definition navigation?

**Comment by jorgenschaefer** [comment]
Probably due to a variety of reasons, most of which will boil down to a simple one: Lack of developer time for writing and maintaining the required code. (You are welcome to help improving Jedi! :smile: )

**Comment by MrWanter** [comment]
:smile: :smile: :smile:
