### ISSUE TITLE
elpy-config different when running from gui or terminal

### ISSUE THREAD

**Issue by sacool** [jorgenschaefer/elpy#1247]
Hello,

I seem to have elpy nicely set up and configured when running emacs from my terminal on my mac, but not so when I run emacs from the GUI. Here are the two, from my terminal, and from my gui, respectively:

```
Elpy Configuration                                                              
                                                                                
Virtualenv........: None                                                        
RPC Python........: 3.6.1 (/Users/lucasgoldstone/miniconda2/envs/python3/bin/py\
thon)                                                                           
Interactive Python: python (/Users/lucasgoldstone/miniconda2/envs/python3/bin/p\
ython)                                                                          
Emacs.............: 25.3.1                                                      
Elpy..............: 1.17.0                                                      
Jedi..............: 0.11.0 (0.11.1 available)                                   
Rope..............: 0.9.4-1                                                     
Autopep8..........: 1.3.3                                                       
Yapf..............: 0.20.0                                                      
Syntax checker....: flake8 (/Users/lucasgoldstone/.local/bin/flake8)   
```
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.17.0
Jedi..............: 0.11.1
Rope..............: 0.10.7
Autopep8..........: 1.3.3
Yapf..............: Not found (0.20.0 available)
Syntax checker....: Not found (flake8)
```

Why would these be different, and how can I make the gui config match the terminal config (which is the way that I want it)? Thanks in advance for your help, and for elpy, it's pretty fantastic!! 

EDIT: I'm able to manually set elpy-rpc-python-command to the python at the path I want it, and make sure everything else is identical, but I'm still really curious why the gui elpy-config would be different from the terminal elpy-config...

EDIT 2: I figured out that this is because the emacs shell was not the same as my terminal shell... Installing the package [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) fixed the issue for me. Feel free to close this issue!

**Comment by jorgenschaefer** [comment]
I was about to suggest `exec-path-from-shell`… sadly, it's not too easy to configure global environments on mac, so that's probably the best option. Glad it works now, please do not hesitate to open a new issue if you have further problems! :-)
