### ISSUE TITLE
Cannot open elpy-config over proxy

### ISSUE THREAD

**Issue by ufnalbartosz** [jorgenschaefer/elpy#1250]
I wonder if this is a real issue or just me having troubles using company proxy. What I know is `M-x elpy-config` hangs emacs.

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report! Elpy tries to access pypi to get version information for some packages. Can the rest of Emacs access the web (e.g. `M-x package-list-packages`) via the proxy? Make sure the `http_proxy` and `https_proxy` environment variables are set inside Emacs.

**Comment by ufnalbartosz** [comment]
Well I've set `http_proxy` variable in my shell as well  in emacs with `url-proxy-services`. I am able to install package via `package-list-packages` but when I try `M-x elpy-config` Emacs still freezes. How can I see what's happening underneath when Emacs execute this command?

**Comment by jorgenschaefer** [comment]
Does `M-: (getenv "http_proxy")` return the correct value? Does `M-: (getenv "https_proxy")` do? If not, could you try `M-: (setenv "http_proxy" "...the proxy...")` and `M-: (setenv "https_proxy" "... the proxy ...")` and try again? (I'm not sure if that will work, I remember xmlrpclib being a bit strange about proxies.)

**Comment by ufnalbartosz** [comment]
Yes, in my case variables in Emacs are set properly (`M-: (getenv "http_proxy")` returns correct proxy address). Any other ideas? :)

**Comment by jorgenschaefer** [comment]
Elpy executes the code in the variable `C-h v elpy-config--get-config` in a Python shell to get the relevant values. Apparently, the default xmlrpclib implementation does not adhere to proxy settings. :-(

**Comment by galaunay** [comment]
xmlrpclib has been replaced with urllib2 as of 4ac45cbb26907c017207a3244db8f9e73d9010a1.
Please re-open if this issue is still relevant.
