### ISSUE TITLE
pyvenv-activate fails silently

### ISSUE THREAD

**Issue by chaturv3di** [jorgenschaefer/elpy#1252]
Hi,

I'm using Elpy with Emacs on MacOS High Sierra. I have a few conda virtual environments I can activate fine via commandline or via the corresponding choice of kernel in my Jupyter notebook. However, even though activating virtual environment in Emacs with `pyvenv-activate` appears to succeed, I cannot load the relevant Python packages. At the same time `elpy-config` suggests that the environment was activated properly. For example,

```
Elpy Configuration

Virtualenv........: tensorflow (/anaconda/envs/tensorflow)
RPC Python........: 3.5.2 (//anaconda/bin/python)
Interactive Python: //anaconda/bin/python (//anaconda/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.17.0
Jedi..............: 0.11.0 (0.11.1 available)
Rope..............: 0.9.4-1
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.3.3 available)
Yapf..............: Not found (0.20.0 available)
Syntax checker....: Not found (flake8)
                    ˆˆˆˆˆˆˆˆˆ
```
I am also surprised that `flake8` cannot be found. I installed both `jedi` and `flake8` using `conda install`.

Is there any further information which I can provide on this issue? 

Thanks in advance.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the record! What exactly do you mean with "fails"? Which environment did you activate, which Python interpreter did you expect to be used, and what exactly did you do to not have that interpreter be used?

Pure guesswork from the output above:
Did you try to activate the `/anaconda/envs/tensorflow` environment?
Is there a `/anaconda/envs/tensorflow/bin` directory?
Is there a `/anaconda/envs/tensorflow/bin/python` executable?
Is there a `/anaconda/envs/tensorflow/bin/flake8` executable?
What's your elpy configuration?

**Comment by chaturv3di** [comment]
Hi,

Thanks for a response. I do `M-x pyvenv-activate RET //anaconda/envs/tensorflow RET` to activate the environment. This virtual environment has the package `tensorflow` which I can otherwise load, e.g. when I `source activate tensorflow` and start Python interpreter in my shell. But I can't load this package when I start the interpreter in emacs using `M-x run-python`.

Regarding `/anaconda/envs/tensorflow/bin`:

- Directory exists
- `./python` is executable
- `./flake8` is executable

And:
```
Elpy Configuration

Virtualenv........: tensorflow (/anaconda/envs/tensorflow)
RPC Python........: 3.5.2 (//anaconda/bin/python)
Interactive Python: //anaconda/bin/python (//anaconda/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.17.0
Jedi..............: 0.11.0 (0.11.1 available)
Rope..............: 0.9.4-1
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.3.3 available)
Yapf..............: Not found (0.20.0 available)
Syntax checker....: flake8 (/anaconda/envs/tensorflow/bin/flake8)
```

**Comment by jorgenschaefer** [comment]
Apparently, it found `flake8` now, so that is working. You will have to restart the Python interpreter by killing the subprocess and then doing `M-x run-python` again after activating the virtualenv. Can you import `tensorflow` then?

**Comment by chaturv3di** [comment]
I quit Emacs and did everything over again. No luck.

**Comment by jorgenschaefer** [comment]
Hm. I just noticed that it uses `//anaconda/bin/python` as your interactive Python interpreter. What's the value of `python-shell-interpreter`?

**Comment by chaturv3di** [comment]
Yes, I have explicitly set that in my `init.el`. I just defaulted everything to Anaconda's Python.

```
(setq elpy-rpc-python-command "//anaconda/bin/python")
(setq python-shell-interpreter "//anaconda/bin/python")
```

So, evaluating the said variable:
```
(print python-shell-interpreter)

"//anaconda/bin/python"
```

Should I have something else here?

**Comment by jorgenschaefer** [comment]
> Should I have something else here?

Well, if you set it to an absolute path, Elpy will use that and not whatever it might find in your virtualenv.

**Comment by chaturv3di** [comment]
> Well, if you set it to an absolute path, Elpy will use that and not whatever it might find in your virtualenv.

Yes, this just struck me as I posted my response. So, I should change `python-shell-interpreter` to `python`. What about `elpy-rpc-python-command`? I guess that should be the absolute path in order to fire up Anaconda Python and not `/usr/bin/python`. Is that right?

**Comment by jorgenschaefer** [comment]
I do not know anything about anaconda, and I do not know what the semantics of `/usr/bin/python` is. Usually, you want both variables to just be `"python"` so the python interpreter in your current virtualenv is used.

**Comment by chaturv3di** [comment]
Thank you very much for your patience. Yes, just setting both variables to `python` solves everything.

**Comment by jorgenschaefer** [comment]
Glad it works now! That's the default, incidentally, so no need to configure anything if that works for you. :-)

I'll close this issue. Please do not hesitate to open a new one if you have further problems!
