### ISSUE TITLE
elpy-config failure with latest version

### ISSUE THREAD

**Issue by spluque** [jorgenschaefer/elpy#1254]
I just upgraded to the latest elpy from melpa (20171220.504), and now elpy-config is failing with message:

elpy-config: Symbol’s value as variable is void: rope-pypi-package

The only elpy variable I have in my init file is elpy-rpc-backend set to "jedi".  Any tips on troubleshooting this?

**Comment by jorgenschaefer** [comment]
That's a strange error. That variable is bound via `let*` and then immediately used, and not elsewhere at all. Can you try uninstalling and reinstalling the Elpy package? Maybe there is some outdated byte compiled package somewhere.

**Comment by spluque** [comment]
I just removed Elpy, and reinstalled, but am still getting this error.  Grepping my entire ~/.emacs.d the only match for 'rope-pypi' is in elpy.el, so I'm at a loss.  I didn't try removing/reinstalling all of Elpy's dependencies, but given the grep result I'm not sure that will help.

**Comment by spluque** [comment]
OK, I tried to narrow this down a bit more by starting emacs with:

`emacs -q -l init.el`

where init.el has:

```elisp
(package-initialize)
(elpy-enable)
```

and then `M-x toggle-debug-on-error RET elpy-config`, which got me this trace:

```elisp
Debugger entered--Lisp error: (void-variable rope-pypi-package)
  elpy-config--insert-configuration-problems(#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("emacs_version" "25.2.2" "python_rpc" "python" "python_rpc_executable" "/usr/bin/python" "python_interactive" "python" "python_interactive_executable" "/usr/bin/python" "virtual_env" nil "virtual_env_short" nil "autopep8_latest" nil "python_version" "2.7.14" "jedi_latest" nil "elpy_version" "1.17.0" "yapf_latest" "0.20.0" "autopep8_version" "1.3.3" "rope_latest" "0.10.7" "rope_version" "0.10.5" "yapf_version" "0.19.0" "jedi_version" "0.11.1" ...)))
  elpy-config()
  funcall-interactively(elpy-config)
  call-interactively(elpy-config record nil)
  command-execute(elpy-config record)
  execute-extended-command(nil "elpy-config" nil)
  funcall-interactively(execute-extended-command nil "elpy-config" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by jorgenschaefer** [comment]
I do not understand how that can happen at all. Could you try explicitly recompiling elpy.el, as in `M-x byte-recompile-file`, and restart Emacs again?

**Comment by spluque** [comment]
Forcing recompilation with `M-x byte-recompile-file elpy.el` I got the following warnings:

```elisp
elpy.el:172:2:Warning: make-obsolete-variable called with 2 arguments, but
    requires 3-4
elpy.el:788:1:Warning: Unused lexical variable ‘rope-pypi-package’

In elpy-config--insert-configuration-problems:
elpy.el:886:31:Warning: reference to free variable ‘rope-pypi-package’

In elpy-goto-location:
elpy.el:1592:16:Warning: ‘find-tag-marker-ring’ is an obsolete variable (as of
    25.1); use ‘xref-push-marker-stack’ or ‘xref-pop-marker-stack’ instead.

In elpy-nav-expand-to-indentation:
elpy.el:1746:12:Warning: ‘mark-whole-buffer’ is for interactive use only.
elpy.el:2127:2:Warning: make-obsolete called with 2 arguments, but requires 3
elpy.el:2128:2:Warning: make-obsolete called with 2 arguments, but requires 3

In elpy-module-company:
elpy.el:3308:33:Warning: assignment to free variable
    ‘company-dabbrev-code-everywhere’

In elpy-module-flymake:
elpy.el:3652:30:Warning: ‘flymake-warning-re’ is an obsolete variable (as of
    24.4); use ‘flymake-warning-predicate’ instead.
elpy.el:3803:5:Warning: reference to free variable ‘python-python-command’
elpy.el:3872:17:Warning: reference to free variable ‘highlight-indent-active’

In end of data:
elpy.el:3914:1:Warning: the following functions are not known to be defined:
    projectile-project-root, python-send-buffer, highlight-indentation
```

and then restarting didn't change anything, unfortunately.  I'm using Emacs 25.2.2 on Debian sid.

**Comment by jorgenschaefer** [comment]
Fascinating, there is a parenthesis error in that file no one noticed so far, apparently. Nice catch. Sorry for being so slow to notice it. Should be fixed in the next MELPA build.
