### ISSUE TITLE
Tool that collect nested structure of functions in a python script/prj

### ISSUE THREAD

**Issue by MrWanter** [jorgenschaefer/elpy#1260]
Hi! @jorgenschaefer, I'm wondering if there is some kind of tool in elpy that can generate the information of nested function structures in a complex/long python script or even a large python project, so we can have more structural understanding of a script or prj, e.g., we can create such kind of nested info architecture like trees, then we can make some note of each functions, I think this would be more efficient to understand/write a code base.

**Comment by jorgenschaefer** [comment]
Hello! Does `C-c C-o` do something like what you want to see? Alternatively, does `M-x speedbar`?

**Comment by MrWanter** [comment]
but `C-c C-o` only lists all functions defined, but seems no nested structures shown, actually what I want is generate a tree structured things, so that we can do some short notes there for each functions

**Comment by jorgenschaefer** [comment]
I'm afraid I do not understand what you're looking for, then. And it's highly unlikely that Elpy has such a feature. :-(

**Comment by MrWanter** [comment]
Thanks for your attention, I mean something like this:
```
                       func_main() [notes here]
                         /              \
func_child1_level1 [notes here]      func_child2_level2 [notes here]
                      /                                          /                            \
func_child1_level2 [notes here]    func_child2_l2 [notes]    func_child3_l2 [notes]
```
an for each script/prj, for each func_main, we can generate a tree like this, I dont know if I'm clear?

**Comment by jorgenschaefer** [comment]
Interesting. I think you mean a "call tree"? One you can annotate, that is. Elpy does not have such a feature, but there are various tools for Python to generate call trees (aka call graphs). Try to google for those terms. :-)

**Comment by MrWanter** [comment]
Thanks for pointing the way:)
