### ISSUE TITLE
elpy-goto-definition does not work anymore

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#1266]
Hi there, I'm not sure what is going on. I'm running the latest version of elpy and I do not see an EPC process anymore? 

company-jedi is still working (I get completions) but I constantly get `elpy-goto-definition: No definition found`

**Comment by jorgenschaefer** [comment]
Elpy is not using EPC (that's what `emacs-jedi` uses). Elpy is also different from `company-jedi`. Be careful with installing multiple packages that all do the same thing, they can easily confuse each other.

What's the output of `M-x elpy-config`?

**Comment by kootenpv** [comment]
It was the weirdest situation of having installed a custom IPython or something. Unrelated to elpy. Thanks for your concern!
