### ISSUE TITLE
Contacting host: elpa.gnu.org:80 hanged during installation

### ISSUE THREAD

**Issue by YichaoCaiDBS** [jorgenschaefer/elpy#1270]
Hi folks,

I have tried to install elpy in emacs (24.5.1) on my server which is running Ubuntu 16.04.

When I run M-x package-refresh-contents, emacs successfully connected to stable.melpa.org:443. 
After that, it was hanged on `Contacting host: elpa.gnu.org:80`. I am pretty sure that I am not behind proxy. Tried several times and it hanged every time.

Then I tried to ping this host and this is what I got:
```
me@server:~$ ping elpa.gnu.org:80
ping: unknown host elpa.gnu.org:80
```

However, pinging other websites is normal. I also tried to access this (elpa.gnu.org:80) on my local computer and it is accessible.

Does anyone get a hint of what is going on? Thank you so much!

Best regards,
Yichao

**Comment by jorgenschaefer** [comment]
Ping does not know ports. Try `ping elpa.gnu.org`?

**Comment by YichaoCaiDBS** [comment]
Hi @jorgenschaefer ,

Pinging `elpa.gnu.org` actually gives me replies. However, It still hangs. I've ask this in gnu help group ([here is the link](https://groups.google.com/forum/#!topic/gnu.emacs.help/_Hwo6UX6yHM)).

After two day's hanging,  I came back to the emacs session (still hanging) and restart the whole emacs `C-x C-c`. This time, I am able to install elpy.

After successful installation, I am curious about what would happen this time when I run `M-x package-refresh-content` again. And emacs did get hanged this time. Same message 
> Contacting host: elpa.gnu.org:80

It seems that the message would still be shown in the minibuffer after it did connect to the gnu host and refresh package contents. This make emacs looks like it's still connecting to the host. Executing other commands seems normal and no error.  

I am not sure whether other users have experienced this before, but right now it seems okay for now.

Thank you so much for your help!

I would like to close this post for now and will consider reopen this if there are further issues.
