### ISSUE TITLE
Key bindings undefined

### ISSUE THREAD

**Issue by sickerin** [jorgenschaefer/elpy#1271]
Hello,

I'm trying to directly run snippets of codes as described here ->

https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-shell-send-statement

I have followed all the instructions up to that point.
Another source I used is: https://realpython.com/blog/python/emacs-the-best-python-editor/#ipythonjupyter-integration

I get the following error:
C-c C-y is undefined

I have attached my .emacs file.
[emacsconfigfile.zip](https://github.com/jorgenschaefer/elpy/files/1647392/emacsconfigfile.zip)

I'm not sure if this is related to the issue, but I also use emacs for OCaml for a
different class, I'm not sure if it's because I have two settings combined into one .emacs file.

Thanks
(I'm new to emacs)

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report. This has been added very recently to Elpy and is not in the latest released version. You can either upgrade to the unstable version (directly from github or by using MELPA Unstable), or wait for the next release. Does this help? :-)

**Comment by sickerin** [comment]
Hello,

Thank you very much.
Could you tell me how I could do that? (how should I edit my .emacs file?)
I tried a few changes to the emacs file to use the unstable version, but they didn't work.
It'll be nice if you could provide a snip of code that does the job.

Thanks

**Comment by jorgenschaefer** [comment]
```
(add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
```
After that, `M-x package-list-packages` should list a version of Elpy that looks like a date (201801XX.YYY). That's the latest unstable version. Be aware though that unstable means just that – stuff might break. Please report bugs if they do :-D

**Comment by sickerin** [comment]
Hello, Perfect, it works. Thanks so much. Awesome stuff you've got here.

**Comment by jorgenschaefer** [comment]
Glad it works now :-) I'll close this issue, but please be sure to open a new one if you have further problems!
