### ISSUE TITLE
Error message  "Wrong number of arguments: (1 . &rest), 0" when sending buffer to shell using elpy-company-backend

### ISSUE THREAD

**Issue by bhrgunatha** [jorgenschaefer/elpy#1273]
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-05
elpy-20180119.54 installed from melpa 
I installed all the python packages with pip as per the documentation.

My elpy configuration is very basic:

```
(elpy-enable)
(add-hook #'elpy-mode-hook
          (lambda ()
            (elpy-company-backend)
            (define-key python-mode-map (kbd "C-j") #'newline-and-indent)
            (define-key python-mode-map (kbd "RET") #'newline-and-indent)
            (setq-default indent-tabs-mode nil
                          tab-width        4
                          py-indent-offset 4)))

```

However this causes an error when I try to send a buffer to the shell.

1) Create a file basic.py  
2) Enter print([1, 2]) 
3) Save buffer.
4) C-c C-c   (emacs reports it's bound to elpy-shell-send-region-or-buffer) 

Results in an error displayed in the mini-buffer : Wrong number of arguments: (1 . &rest), 0

This happens whether a shell already running or not.
In the *Messages* buffer I see:

```
Can’t guess python-indent-offset, using defaults: 4
File mode specification error: (wrong-number-of-arguments (1 . &rest) 0)
When done with a buffer, type C-x #
Sent: print([1, 2, 3])...
Shell native completion is enabled.
Can’t guess python-indent-offset, using defaults: 4
Wrong number of arguments: (1 . &rest), 0

``` 

If I comment out the  `(elpy-company-backend)` it works as expected and indeed the buffer contents are sent to the shell and executed.  

**EDIT:** To clarify I _am_ using the melpa version of elpy (elpy-20180119.54), but I _also_ get the same behaviour when I use the melpa-stable version (elpy-1.17.0)

**Comment by jorgenschaefer** [comment]
Thanks for the report! Could you hit `M-x toggle-debug-on-error`, reproduce this, and post the resulting backtrace?

**Comment by bhrgunatha** [comment]
Thanks, absolutely - [see gist with backtrace](https://gist.github.com/bhrgunatha/0ee03ee9d63769f0fb1d5007dabdc476) 

I forgot to mention but if I select a region (even the whole buffer) the error does not appear, just when I try to send the whole buffer.

If you need anything else just ask.

**Comment by jorgenschaefer** [comment]
`elpy-company-backend` requires an argument. I just noticed it in your config. I don't think it makes sense to call there, what do you expect that to do?

**Comment by bhrgunatha** [comment]
I wanted to ensure elpy used company for completion - the elpy menu show M-TAB bound to that function. My OS uses M-TAB so I can't use that and I _thought_  it turned on company support in elpy.  
Now I notice `elpy-company-backend` is automatically added `company-backends` and so I think I've wasted your time and I'm really sorry about that :( 
I'll try to re-bind it to C-TAB instead to invoke it manually.

**Comment by jorgenschaefer** [comment]
No worries. Company should trigger automatically after a short delay, so you usually don't need to trigger it manually  – but when you do, you need that command, indeed. I'll close this issue, but please do not hesitate to create a new one if you have further issues!
