### ISSUE TITLE
Use the RPC interpreter to run syntax checks

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#1275]
See #1162 – we install yapf etc. for the RPC interpreter, not the shell interpreter.

**Comment by galaunay** [comment]
I don't get the issue.
Yapf is called by `elpy-rpc`, so should use `elpy-rpc-python-command`,
and installation is coherent, as it also uses `elpy-rpc-python-command`.
Am I missing something ?

**Comment by jorgenschaefer** [comment]
`elpy-format-code` looks for the `yapf` executable, not the `yapf` module, for example. For syntax checks, we call `flake8` as a command, not the module. Etc. But we check the presence as modules. It's pretty inconsistent, and that is pretty confusing. Especially when you have a python interpreter set, but not the PATH for the installed scripts.

**Comment by galaunay** [comment]
Got it.
Thanks

**Comment by galaunay** [comment]
Was fixed by #1281.
I am closing this.
