### ISSUE TITLE
ipython for elpy on a virtualenv basis?

### ISSUE THREAD

**Issue by canicola** [jorgenschaefer/elpy#1278]
I came across the following issue. I played around with ipython and wanted to use it for a project. That's why I've installed it in a virtualenv only. In my init.el I've added

`(elpy-use-ipython)`

However, I got a command not found error when starting emacs. I guess this is because I haven't installed ipython on a global level. Is it possible to use ipython on a environment basis?

I came across this [issue](https://github.com/jorgenschaefer/elpy/issues/895), however I'm running linux debian 9.3 so that I guess that doesnt apply to me.

**Comment by jorgenschaefer** [comment]
Elpy removed the ipython config function because Emacs now supports ipython much better directly, and ipython is having more and more issues itself that are hard to work around. See http://elpy.readthedocs.io/en/latest/ide.html#interactive-python for a current ipython setup. Does this help?

**Comment by canicola** [comment]
thanks for the quick response. I guess my question would then be if it is possible to specify the interpreter on a virtual environment basis. But since this is not longer coupled to elpy as mentioned this looks like the wrong place to ask this question. I will try a stackexchange site. Thx, it does help

**Comment by der-Daniel** [comment]
@canicola  Have you solved this problem, yet?

**Comment by canicola** [comment]
@der-Daniel I did play around and found a workaround. However, for simplicity I now just fixed the interpreter across virtualenv. 

They workaround was to add to your venv/bin/activate a variable for within your virtualenv, like 
`export INTERPRETER=your_choice`

then as pointed out in the [link](http://elpy.readthedocs.io/en/latest/ide.html#interactive-python) above you can set the python shell interpreter to the `INTERPRETER` variable. This can be done via getenv in elisp. At least at the point in time when I was trying it, it worked. It is not a nice solution but a workaround.
