### ISSUE TITLE
elpy-shell-kill is not defined

### ISSUE THREAD

**Issue by marty0801** [jorgenschaefer/elpy#1280]
This function is not available for some reason. Here is my elpy-config. 

```
Virtualenv........:  (/home/marty/proj/geo3/)
RPC Python........: 3.5.2 (/home/marty/proj/geo3/bin/python3)
Interactive Python: ipython (/home/marty/proj/geo3/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: 0.11.1
Rope..............: 0.10.7
Importmagic.......: 0.1.7
Autopep8..........: 1.3.4
Yapf..............: 0.20.1
Syntax checker....: pyflakes (/home/marty/proj/geo3/bin/pyflakes)
 
```
Is the problem that my elpy version is obsolete? I attempted `M-x package-refresh-contents`, but I'm not sure whether it's working. The message  "Contacting Host: stable.melpa.org" is displayed indefinitely.

**Comment by galaunay** [comment]
`elpy-shell-kill` has been introduced with version 1.14, 
so you should indeed update to the last elpy version.

Your Emacs seems to not be able to connect to melpa.
I am afraid this is a problem linked to your network or Emacs configuration.
Do you have any additional information on what happen (maybe from the message buffer) ?

`package-refresh-contents` only refreshes the list of available packages, if you want to actually update a package, you can use `package-list-package` then interactively update all your packages (with 'U', then 'x').
If you want to update elpy only, `package-reinstall` should do the trick.

**Comment by marty0801** [comment]
Thank you. When executing `M-x package-refresh-contents`, the message buffer displays
```
Importing package-keyring.gpg...done
Contacting host: jorgenschaefer.github.io:80
Contacting host: marmalade-repo.org:80
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.
```
I suppose I should take it up with Emacs?

**Comment by marty0801** [comment]
Fixed this by re-installing emacs24 and elpy..
