### ISSUE TITLE
Error msg on installation

### ISSUE THREAD

**Issue by raynalm** [jorgenschaefer/elpy#1285]
Hello, 
I just installed elpy by following the steps given in readme.
I came upon an error in the *Compilation* log after launching 'package-install' 'elpy' command in emacs.
The error was 
elpy-shell.el:977:1:Error: Symbol's function definition is void: string-remove-suffix

I joined the full log since there were many warnings.
My config : Ubuntu 16.04, GNU emacs 24.5.1, python 3.6.1, anaconda 4.4.0, pip 9.0.1, with jedi, flake8, autopep8 and yapf installed just before.

I'm quite new with emacs, and thus I have no idea about the consequences of it ; i just know that an error is generally quite a bad sign ....
Thanks for the help !

[log_compil_err.txt](https://github.com/jorgenschaefer/elpy/files/1695647/log_compil_err.txt)

**Comment by galaunay** [comment]
Hi, 
Thanks for the report.
It could indeed make elpy kind of buggy.

I was able to reproduce it with a clean emacs, we missed a dependency.
I will make a patch to fix this.

Until then, you should be able to make it work by doing `M-:` then typing `(require 'subr-x)` before installing elpy.
