### ISSUE TITLE
Elpy is slow for some reason

### ISSUE THREAD

**Issue by HuStmpHrrr** [jorgenschaefer/elpy#1287]
For some reason, I found emacs becomes extremely unresponsive once the code size exceeds 200 lines in one of my computers(while the other one is fine). Specifically when I move point using arrow keys, it might take a few second for emacs to respond. However, coding normally seems good. I am reporting to here, because things become responsive again, once I turn off elpy-mode by `M-x elpy-mode`.

Following is my python related configuration, which is shared among computers(I can guarantee I use the same configuration as they are managed by git):

```
(use-package elpy
  :ensure t
  :config
  (elpy-enable)
  (setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt"))

(use-package flycheck
  :config
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

(use-package py-autopep8
  :ensure t
  :config
  (add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save))

(use-package python-environment
  :ensure t)

(use-package pyvenv
  :ensure t)
```

Also, all my packages are up to date as of this issue posted. I don't really know what can possibly be the reason for one machine being slow. Do you have any ways to somehow profile elpy to understand what is running slow?

In terms of the environment, both of my computers runs Ubuntu 16.04, and use emacs 25.3.

**Comment by galaunay** [comment]
Thanks for the report.

I generally use `elp` to see what is slowing down elpy.
You can start monitoring the whole elpy package with `(elp-instrument-package "elpy-")`, do your time-consuming operations, and get a report with `(elp-results)`.

You can also use the standard profiler, but it will show everything, not only elpy related functions: start it with `profiler-start`, do your thing, and get a report with `profiler-report`.

ps: try to avoid interactive functions reading inputs, the time you spend typing the input will be counted as time consumed by the function.

I am curious about what can slow down elpy at this excess, 
please let me know if you can find what happen.

**Comment by HuStmpHrrr** [comment]
thx. Following is the profiling result:

```
elpy-eldoc-documentation                          364         17.106411074  0.0469956348
elpy-rpc-get-calltip                              364         17.101866814  0.0469831505
elpy-rpc--buffer-contents                         364         16.838698388  0.0462601604
elpy-rpc--filter                                  4           4.791090864   1.197772716
elpy-rpc--handle-json                             364         4.7784753929  0.0131276796
elpy-promise-resolve                              364         4.7772022989  0.0131241821
elpy-rpc                                          364         0.26077085    0.0007164034
elpy-rpc--call                                    364         0.2597401709  0.0007135718
elpy-flymake-error-at-point                       364         0.0031556690  8.669...e-06
elpy-rpc--get-rpc-buffer                          364         0.0018704849  5.138...e-06
elpy-rpc--process-buffer-p                        364         0.0010190959  2.799...e-06
elpy-rpc--register-callback                       364         0.000441066   1.211...e-06
elpy-promise                                      364         0.0003958470  1.087...e-06
```

It seems `elpy-rpc--filter` is the one to be blamed.

**Comment by galaunay** [comment]
What did you exactly do during the profiling, Just moving around ?
Is 364 motions something that you could have done ?

Calls for `elpy-rpc--filter` are certainly long because they have to filter a large amount of outputs from `elpy-rpc-get-calltip` calls. 
So my first guess is `eldoc` asking for documentation way too often.

Does removing `elpy-module-eldoc` fix the issue ?

**Comment by HuStmpHrrr** [comment]
I turn on elp as you said, and the only thing i did was to press up and down arrow. the whole operation was done within a minute so i did not spend a whole day on pressing keys.

I will check with my other computer and see if the same number is generated. 

Also could you show me a concrete way of removing `elpy-module-eldoc`? I did `(defun elpy-module-eldoc (command &rest _args))` but there isn't obvious change.

**Comment by HuStmpHrrr** [comment]
from another computer:

```
elpy-rpc--filter                                  166         3.6090209490  0.0217410900
elpy-rpc--handle-json                             391         3.5883166349  0.0091772803
elpy-promise-resolve                              391         3.5865809879  0.0091728414
elpy-eldoc-documentation                          391         1.7888273670  0.0045750060
elpy-rpc-get-calltip                              391         1.7824656490  0.0045587356
elpy-rpc--buffer-contents                         391         1.6532241760  0.0042281948
elpy-rpc                                          391         0.1261987190  0.0003227588
elpy-rpc--call                                    391         0.1245319959  0.0003184961
elpy-flymake-error-at-point                       391         0.0046826449  1.197...e-05
elpy-rpc--get-rpc-buffer                          391         0.0026289250  6.723...e-06
elpy-rpc--process-buffer-p                        391         0.0017112569  4.376...e-06
elpy-rpc--register-callback                       391         0.0005912920  1.512...e-06
elpy-promise                                      391         0.000487475   1.246...e-06
```

There still are glitches, but it's much responsive. My other computer is indeed a better one, but both my computers are relatively recent and there shouldn't be 4x,5x difference in terms of CPU performance.

**Comment by galaunay** [comment]
> Also could you show me a concrete way of removing elpy-module-eldoc?

Just customize `elpy-modules`: `M-x customize-variable` then `elpy-modules`,
and untick `elpy-eldoc-module`.

You can also adjust the idle delay before which eldoc ask for documentation under point with:
```Elisp
(setq eldoc-idle-delay 1)  ;; in second
```
If it is actually set to zero, it can indeed be quite cpu consuming...

`elpy-rpc-get-calltip` takes around 0.001s in the computer I am using now computer (which is not recent in any way), so I will suggest a problem related to jedi...
I will search for a way to profile that, to make sure it is the case.

**Comment by HuStmpHrrr** [comment]
I use python 2.7.12 and jedi 0.10.2 on both machines. I also have rope, the slower one is 0.10.7, the other one is 0.10.5

I will check the other ones.

**Comment by HuStmpHrrr** [comment]
`(setq eldoc-idle-delay 1)` indeed works. it originally was `0` but I did not set it manually. i will keep it that way.

**Comment by galaunay** [comment]
It seems fixed.
I am closing this.
