### ISSUE TITLE
Get flake8 syntax-highlighting for python script not ending in '.py'

### ISSUE THREAD

**Issue by melton1968** [jorgenschaefer/elpy#1289]
I have some python scripts in a project that do not end in '.py'. I'd like to get the same flake8 syntax highlighting for issues as I do when editing python files that end in .py. All of the non-filename-conforming scripts are in a single directory.

When editing a .py file, my emacs mode line has: (Python || Elpy) [py36v1]
When editing a non-filename-conforming script: (Python ARev || Elpy) [py36v1]

Edit: Ok, the ARev is because one file is under revision control and one isn't.
Running C-h m shows that each buffer has exactly the same minor-modes enabled.

Is this something I can configure?

**Comment by galaunay** [comment]
So is this solved ?
If not, I am not sure to understand what the problem is.
I got flake8 to work perfectly on a script without a ".py" extension with elpy-mode activated.

**Comment by melton1968** [comment]
I can run flake8 successfully on any file by typing C-c C-v, but I don't get the warning / error highlighting in the buffer for a non-py file even though python-mode / elpy are activated for that buffer.

**Comment by galaunay** [comment]
Ok, found the problem.

flymake-mode checks which backend to use for the current file using the file extension.

To force flymake to use flake8 for scripts without an extension, you will have to customize `flymake-allowed-file-name-masks`.
Something like that I guess:
```Elisp
     (add-to-list 'flymake-allowed-file-name-masks
                  '("*\\'" elpy-flymake-python-init)))
```
But all files will then default to pyflake8...

This is not directly related to elpy, you should ask if there is a better way to do it directly to the flymake maintainer.  

Hope this helps.

**Comment by melton1968** [comment]
Perfect -- thanks. The files in question have patterned filenames, so I can use the regex to narrow it down to match the python files.
