### ISSUE TITLE
Unit test `elpy-config-should-show-flake8-pip-button-when-no-syntax-checker-available' is broken

### ISSUE THREAD

**Issue by Apteryks** [jorgenschaefer/elpy#1292]
python-check-command was apparently renamed to elpy-syntax-check-command and the proposed text to match has changed to use the --user option of pip. Patch incoming.

**Comment by galaunay** [comment]
The related PR has been treated, closing this...

**Comment by Apteryks** [comment]
Hello, was this really merged? I still have the same issue, and https://github.com/jorgenschaefer/elpy/blob/1.23.0/test/elpy-config-test.el suggests it wasn't.

**Comment by galaunay** [comment]
I guess I got confused somewhere...
Thanks for reminding me this issue.

#1450 should be merged soon and fix that.
