### ISSUE TITLE
elpy-shell-send-region-or-buffer cannot see different path

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jorgenschaefer/elpy#1296]
Suppose I have the following .py file:

`
from sys import path

path.append('../tools/')

import MyLib

`

then hitting C-c C-c will not be able to see `MyLib` and its inside functions.

**Comment by galaunay** [comment]
Hi, thanks for the report.

Elpy uses `(elpy-project-root)` to determine the path to the project root, and then starts all the shells in that particular directory.
So relative paths are based on the project directory, which can be different from your script directory.

This may explain your problem.

You can try deactivating this feature with:
```Elisp
(setq elpy-shell-use-project-root nil)
```

**Comment by DrWaleedAYousef** [comment]
Thanks so much.
