### ISSUE TITLE
Elpy doesn't recognize my module

### ISSUE THREAD

**Issue by almirnunes** [jorgenschaefer/elpy#1300]
Hello,

I am trying to use elpy for the first time.

The thing is that when I compile the code it shows me a message error like:
ImportError: No module named PlotSpit

This PlotSpit is a personal module. All the files are in the same folder. 
And the code works well when executing the python from cmd.exe.

I would like to know if I am doing something wrong. Or if I need an extra step to elpy reconize my files properly.

Thank you very much for considering this questions.

**Comment by gopar** [comment]
Hey,

What commands are you using to run the python programs?

**Comment by almirnunes** [comment]
I am using the C-p to open the python console and them C-c to send the code to the console.
It works in the first time. But if I try again even without changing the code it only shows "Sent:..." but nothing happens.
Then I have to use "kill-buffer" to kill the console and start over.

**Comment by almirnunes** [comment]
In Emacs:
I use C-c C-c  with the code buffer in focus.

In the cmd terminal:
I use python FILENAME.py.

**Comment by galaunay** [comment]
By default Elpy does not starts the shell in the current script folder, but
in the project folder (which is determined by the `elpy-project-root` function).
If your module folder is not the same than the folder identified by Elpy as the project folder, this could explain your problem.

Could you check the current folder of the python interpreter with:
```Python
import os
print(os.getcwd())
```

If the problem comes from here, you can deactivate elpy project root feature with:
```Elisp
(setq elpy-project-root nil)
```

**Comment by almirnunes** [comment]
Thanks!

That was exactly the problem. 

The only is that I tried to add (setq elpy-project-root nil) to the init.el file but elpy always set
back automatically the value to the .git folder.

So, what worked was deactivating the automatic setting of the root folder.

I don't if this is the best practice but now I am able to run the code again.

**Comment by galaunay** [comment]
Sorry, I meant:
```Elisp
(setq elpy-shell-use-project-root nil)
```

But it is apparently what you have done.

@gopar this feature (using the project root as default directory) has been confusing some people. I think we should whether deactivate it by default or add more information about this in the doc. What do you think about it ?

**Comment by jorgenschaefer** [comment]
Hm. This feature was added because the other behavior caused some confusion as well. I wonder whether there is some underlying assumption about the behavior somewhere we are missing.

**Comment by galaunay** [comment]
@jorgenschaefer 
I can understand that the current behavior confuses people because using `C-c C-c` in an elpy buffer (let's say `my-script.py`) and doing `python my-script.py` in a shell doesn't lead to the same effect.
But this is linked to the way I use elpy...

Why was the reason of the confusion for running the interpreter in the current folder ?

**Comment by jorgenschaefer** [comment]
If you have a foo/bar.py and foo/baz.py, baz.py could use `import foo.bar` and that would work if run e.g. using `python -m foo.baz` but not in `C-c C-c`.

I guess the confusion stems from using `C-c C-c` for "run this thing I'm editing", which it does not do. It sends the buffer to some REPL. It's close to "run this thing" most of the time, but depending on what "this thing" is, there are edge cases where it breaks one way or the other.

**Comment by galaunay** [comment]
> I guess the confusion stems from using C-c C-c for "run this thing I'm editing", which it does not do. It sends the buffer to some REPL. It's close to "run this thing" most of the time, but depending on what "this thing" is, there are edge cases where it breaks one way or the other.

I see your point here.
 
And the documentation is indeed coherent with that:
> Emacs can run a Python interpreter in a special buffer, making it much easier to
send code snippets over.

>    By default, Elpy tries to find the root directory of the current project
   (git, svn or hg repository, python package or projectile project) and
   starts the python interpreter here. This behaviour can be suppressed
   with the option ``elpy-shell-use-project-root``.

Nevermind then,
thanks for the clarification.
