### ISSUE TITLE
python shell does not start after upgrade to elpy 1.18.0

### ISSUE THREAD

**Issue by atmamta2** [jorgenschaefer/elpy#1303]
Hi,

I have just upgraded all packages that I could in anaconda3, elpy and related python packages, as well as all installed emacs lisp packages in a linux mint os environment. Since the upgrade, I cannot launch the python shell from emacs with C-c C-c. I get the following error:

elpy-shell-get-or-create-process: Wrong number of arguments: #[(dedicated cmd) "ÂÃ	!Ä#	" [cmd dedicated python-shell-make-comint python-shell-get-process-name t] 4 ("/home/attila/.emacs.d/elpa/python-20120402/python.elc" . 37528) (byte-code "ÁÂ!ÃÄÅ \"DÆÅ D" [current-prefix-arg y-or-n-p "Make dedicated process? " read-string "Run Python: " python-shell-parse-command nil] 4)], 3

Here is my elpy configuration:
*************************************************************
Virtualenv........: None
RPC Python........: 3.5.4 (/home/atmamta/usr/local/lib/anaconda3/bin/python)
Interactive Python: /home/atmamta/usr/local/lib/anaconda3/bin/python (/home/atmamta/usr/local/lib/anaconda3/bin/python)
Emacs.............: 25.3.2
Elpy..............: 1.18.0
Jedi..............: 0.11.1
Rope..............: 0.10.7
Autopep8..........: 1.3.4
Yapf..............: 0.20.2
Syntax checker....: flake8 (/home/atmamta/usr/local/lib/anaconda3/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH....
*************************************************************

Any ideas what might go wrong?

**Comment by galaunay** [comment]
If it is related to dedicated shells, it may be an obsolete byte-compiled file.
You can try reinstalling Elpy, it may be enough to fix this.

If not, could you post the whole backtrace from `toggle-debug-on-error` inside code tag (`) ?

**Comment by atmamta2** [comment]
yes, that worked. Thanks. 
In more detail: i deleted all the emacs lisp files from .emacs.d/elpy/ directory, then reinstalled all needed emacs packages.

**Comment by galaunay** [comment]
Good, 
thanks for the feedback !
