### ISSUE TITLE
elpy [go-to-definition]  not working on [pipenv] virtual environment

### ISSUE THREAD

**Issue by ssisksl77** [jorgenschaefer/elpy#1304]
I've set virtual environment by using [pipenv]

code compete with emacs is find.
but [go-to-definition] (M-.) is not working.

I've tried to solve it by myself. but I have been stuck in hours.

the interesting thing is if I install all dependencies and use [elpy] without the virtual environment, It works fine.

please. help me out of this error.

================================================
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

module 'jedi' has no attribute 'NotFoundError'

Configuration

Virtualenv........: nomadgram-ezELJ-p3 (/Users/tom/.virtualenvs/nomadgram-ezELJ-p3)
RPC Python........: 3.6.0 (/Users/tom/.virtualenvs/nomadgram-ezELJ-p3/bin/python)
Interactive Python: python (/Users/tom/.virtualenvs/nomadgram-ezELJ-p3/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.8.0
Jedi..............: 0.11.1
Rope..............: 0.10.7
Importmagic.......: 0.1.7
Syntax checker....: flake8 (/Users/tom/.virtualenvs/nomadgram-ezELJ-p3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/tom/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 82, in rpc_get_definition
    re_raise=jedi.NotFoundError)
AttributeError: module 'jedi' has no attribute 'NotFoundError'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tom/.emacs.d/elpa/elpy-1.8.0/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/tom/.emacs.d/elpa/elpy-1.8.0/elpy/server.py", line 121, in rpc_get_definition
    get_source(source), offset)
  File "/Users/tom/.emacs.d/elpa/elpy-1.8.0/elpy/server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "/Users/tom/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 83, in rpc_get_definition
    except jedi.NotFoundError:
AttributeError: module 'jedi' has no attribute 'NotFoundError'
```

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report!

> `Elpy..............: 1.8.0`

This is a pretty old version of Elpy, could you try to upgrade?

**Comment by ssisksl77** [comment]
OH GOD... It works!!!
I appreciate your advice!
Thank you!! Now, I can enjoy programming with elpy.

**Comment by jorgenschaefer** [comment]
Glad it works :-) Do not hesitate to open a new issue if you have further problems, and enjoy Elpy!
