### ISSUE TITLE
15 failing tests in what will be the official Debian package

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1308]
Hi Jorgen,

Thank you for elpy!  A number of my colleagues are excited about its official inclusion into the Debian (and Ubuntu via Debian) archive.  As part of its packaging I've been working on making the self-tests succeed using Debian's build environment and policy.  eg: using only Debian-packaged dependencies (no network access, and no pip); using virtualenv seems to be against policy, because the autotests must be against the package as-installed, using only system libraries; finally, we cannot use Cask.

This said, I've successfully configured my package such that 329/344 tests pass using Debian's ert-testing framwork (dh_elpa_test)!  At the moment I've disabled the following failing tests, because 329/344 is better than no testing at all (a build fails if any test fails).

Ran 344 tests, 329 results as expected, 15 unexpected (2018-03-03 08:25:59+0000)

15 unexpected results:
   FAILED  elpy-config--insert-configuration-problems-should-not-fail
   FAILED  elpy-config-should-not-fail
   FAILED  elpy-config-should-not-fail-without-virtualenv
   FAILED  elpy-config-should-show-flake8-pip-button-when-no-syntax-checker-available
   FAILED  elpy-insert--pip-button-value-create-should-do-user-install
   FAILED  elpy-rpc-integration
   FAILED  elpy-shell-kill-all-should-kill-all-shells
   FAILED  elpy-shell-send-current-statement-should-send-current-statement-only
   FAILED  elpy-shell-send-region-or-buffer-should-notify-of-removing-main
   FAILED  elpy-xref--apropos-should-give-an-xref-buffer
   FAILED  elpy-xref--definitions-should-return-definitions
   FAILED  elpy-xref--get-completion-table-should-return-completion-table
   FAILED  elpy-xref--references-test
   FAILED  elpy-yapf-fix-code-in-region-should-retain-line-and-column
   FAILED  elpy-yapf-fix-code-should-retain-line-and-column

If you have the time, and if these tests are important enough to be worth your time, then would you please consider helping to make them work?  Some, like `elpy-config-should-not-fail-without-virtualenv` and `elpy-config-should-show-flake8-pip-button-when-no-syntax-checker-available` can just be disabled, for the purposes of Debian, but I'm concerned about many of the others. 

Why help?  You'll get dashboads for continuous integration and reproducible build testing for all supported architectures, on Debian unstable (as close to latest upstream versions as possible for all packages) and Debian stable (tests that the latest release of elpy works on LTS Debian releases).  Here is an example for `irony-mode`

https://ci.debian.net/packages/i/irony-mode/
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/irony-mode.html

And our git repository is here (p.s. moving from alioth to salsa will take a few minutes): https://salsa.debian.org/emacsen-team/elpy.git

I'll send the full build log and backtraces (or only the backtraces, if you prefer) when I hear back from you.

Sincerely,
Nicholas

**Comment by jorgenschaefer** [comment]
Hello, and thanks for your message. I'm quite happy with trying to improve the build process so that it works with Debian, as long as that does not require extensive contortions to cater for Debian peculiarities. So, difficult to say if we can work on this without the errors :-)

> Why help?

I don't need dashboards, continuous integration and whatnot from Debian, we already have those. :-)

But I'm a former Debian developer, I'm happy to help if I can just because Debian is awesome.

**Comment by sten0** [comment]
P.S. I see that some of these test failures are already known, eg: #1212 #1274 #1292.  Some of the virtualenv-workaround (python3 vs python2 interpreter) issues should be solved if everything goes according to plan and buster (Debian 10, probably 2019 to 2020 release) transitions to python3-by-default.  Of course, I'd be happy to workaround this in the packaging in the meantime and will probably also end up joining the debian-python team to contribute to the py3 transition effort.

**Comment by jorgenschaefer** [comment]
> Did you know Anacat (Antoine) when you were a DD?

I don't think so. It's been some 15 years I think :-D

> Out of curiousity does it test against old versions? 

Yes, we have [a rather extensive build matrix](https://github.com/jorgenschaefer/elpy/blob/master/.travis.yml).

As for the tests, `M-x elpy-config` offers to use `easy_config` or `pip` to install packages. It won't install them, but it tells the user that there might be newer versions available. If possible, could you install the `python3-pip` package and see how many errors are fixed by that?

Also please install `python-jedi` and `python-yapf`. 

>     Test elpy-shell-kill-all-should-kill-all-shells condition:
>         (void-function loop)

This should be fixed in master.

>     (void-function elpy-shell-send-current-statement)

Bug, fixed in 9eea31a

>     (void-variable ert-runner-output-buffer)

Bug, not sure why that has not failed so far.

There are a few more errors I do not understand, but maybe some of them are fixed by the changes above.

**Comment by sten0** [comment]
Hi Jorgen,

On 9 March 2018 at 04:20, Jorgen Schäfer <notifications@github.com> wrote:

> Out of curiousity does it test against old versions?
>
> Yes, we have a rather extensive build matrix
> <https://github.com/jorgenschaefer/elpy/blob/master/.travis.yml>.
>
Wow :-)  There have been discussions on debian-devel about supporting
devops-style packages with complex dependencies, without resorting to
upstream vendor-defined dependencies.  Maybe travis could be part of a
solution?

> As for the tests, M-x elpy-config offers to use easy_config or pip to
> install packages. It won't install them, but it tells the user that there
> might be newer versions available. If possible, could you install the
> python3-pip package and see how many errors are fixed by that?
>
> Also please install python-jedi and python-yapf.
>
There was no change with python3-pip; however, because you mentioned trying
the python2 variants of jedi and yapf I tried this in d/control:

+             , python-autopep8 <!nocheck>
+             , python-jedi <!nocheck>
+             , yapf <!nocheck>
+             , python-pip <!nocheck>
+             , python-flake8 <!nocheck>

Now only
6 unexpected results:
  FAILED
 elpy-config-should-show-flake8-pip-button-when-no-syntax-checker-available
  FAILED  elpy-rpc-integration
  FAILED  elpy-shell-kill-all-should-kill-all-shells
    * I haven't searched for and cherry picked the patch in master yet
  FAILED
 elpy-shell-send-current-statement-should-navigate-to-next-statement
  FAILED
 elpy-shell-send-current-statement-should-send-current-statement-only
    * I'll cherry pick 9eea31a
  FAILED  elpy-shell-send-region-or-buffer-should-notify-of-removing-main

So after removing the above list from the original list of 15 the following
fail on Debian unstable when python2 isn't installed:
    FAILED elpy-config--insert-configuration-problems-should-not-fail
    FAILED elpy-config-should-not-fail
    FAILED elpy-config-should-not-fail-without-virtualenv
    FAILED elpy-insert--pip-button-value-create-should-do-user-install
    FAILED elpy-xref--apropos-should-give-an-xref-buffer
    FAILED elpy-xref--definitions-should-return-definitions
    FAILED elpy-xref--get-completion-table-should-return-completion-table
    FAILED elpy-xref--references-test
    FAILED elpy-yapf-fix-code-in-region-should-retain-line-and-column
    FAILED elpy-yapf-fix-code-should-retain-line-and-column

I'll import the patches you suggested to my python3-only packaging branch
and let you know how it goes.

Thank you!
Nicholas

**Comment by sten0** [comment]
And here is a build log for master@commit:gc95890b with both py2 and
py3 depends installed.

**Comment by jorgenschaefer** [comment]
Hm. Where's "here"? I don't see the build log?

**Comment by sten0** [comment]
Oh my, it seems github's email reply function blocks attachments :-/  Sorry, I didn't know that.  Build log attached
[elpy_1.18.0-1-38-gc95890b-1_amd64.build.gz](https://github.com/jorgenschaefer/elpy/files/1820909/elpy_1.18.0-1-38-gc95890b-1_amd64.build.gz)

**Comment by jorgenschaefer** [comment]
Thanks!

- In `test/elpy-config-test.el`, replace `"python -m pip install flake8"` with `"python -m pip install.*flake8" and let me know if this works – we can include this in Elpy if so
- There's still an error about `ert-runner-output-buffer` which I don't understand. I think this variable was removed recently? (Why is our CI green?)
- The remaining errors should be fixed by 2f4388

**Comment by sten0** [comment]
You're welcome :-)

Using a hungry glob for string-match in test/elpy-config-test.el worked (I filed a pull request in case that's faster/easier for you).

The error about `ert-runner-output-buffer` might be because I'm not using ert-runner to run the tests.  I was unable to get any tests to pass while using it, so decided to experiment building without it, and that experiment proved to be more successful than not.

Mysteriously I'm still getting these errors:
2 unexpected results:
   FAILED  elpy-rpc-integration
   FAILED  elpy-shell-send-region-or-buffer-should-notify-of-removing-main

[elpy_1.1-764-gf418f8e-1_amd64.build.gz](https://github.com/jorgenschaefer/elpy/files/1831081/elpy_1.1-764-gf418f8e-1_amd64.build.gz)

No idea why git describe didn't start counting from 1.18.0 this time, but I am in fact building f418f8e8a0bdc4f407add883a4961da950617690

**Comment by jorgenschaefer** [comment]
```
Test elpy-rpc-integration condition:
    (process-sentinel "exited abnormally with code 1")
```

I'm afraid I have no idea why that would happen :-(

**Comment by jorgenschaefer** [comment]
And the other test is indeed because you're not using ert-runner.

**Comment by sten0** [comment]
#1318 wasn't merged for 1.19.0 but is needed to fix `FAILED elpy-insert--pip-button-value-create-should-do-user-install`

>> Test elpy-rpc-integration condition:
>>    (process-sentinel "exited abnormally with code 1")
>
> I'm afraid I have no idea why that would happen :-(

I wonder if it might be a UTF-8 handling bug somewhere in dh-elpa, or maybe in libdpkg-perl?

```
elpy/tests/test_server.py
335:            f.write(u"möp".encode("utf-8"))
339:        self.assertEqual(source, u"möp")

test/elpy-rpc-test.el
28:    (should (equal (elpy-rpc "echo" '(23 "möp"))
29:                   '(23 "möp")))))
```

I'm out of time for today, but do you think s/möp/mop/ would be enough to test this hypothesis?

>  And the other test is indeed because you're not using ert-runner.
Ok, I think I'll continue to disable `elpy-rpc-integration` for now, because trying to get ert-runner to work with dh-elpa was a fruitless and demotivating experience...too many hours of free time were lost for zero progress.

Thank you once more for all the help, I really appreciate it!

**Comment by sten0** [comment]
There, I was finally able to isolate the immediate cause of `elpy-rpc-test` failure.  A brief summary of the steps I took to debug this can be found at https://gist.github.com/sten0/178ee6ec9506c8a2206cc62edc802a7d.  I wonder if this could be a dh-elpa or pbuilder but, and wonder if it can be worked around by globally setting UTF-8 encoding somewhere like ert-helper.el.  Please let me know and I'll get to work preparing a patch.  Oh, it doesn't fail using dpkg-buildpackage on normal Debian systems, or in autopkgtest lxc, which is why I wonder if it's something pbuilder specific.

**Comment by jorgenschaefer** [comment]
Does adding `;;; -*- coding: utf-8 -*-` to the relevant file fix the issue?

**Comment by sten0** [comment]
> Does adding ;;; -*- coding: utf-8 -*- to the relevant file fix the issue?

Yes, I believe adding that to the relevant elpy-rpc-test-related files allowed `elpy-rpc-test` (as does the sledgehammer `export LC_ALL = C.UTF-8` in debian/rules) to pass.  For elpy-1.19.0 `elpy-shell-kill-all-should-kill-all-shells` passes in pbuilder/cowbuilder, but I'm still new enough to lisp that I haven't been able to isolate what conditions are causing it to fail in LXC containers (either LXC autopkgtest or docker).  Still using emacs-25.2.2.  The short form of the failure from running the tests interactively showed.
```emacs-lisp
F elpy-shell-kill-all-should-kill-all-shells
    (error "`let' bindings can have only one value-form" add-hook 'elpy-mode-hook
           #'(lambda nil
               (elpy-shell-toggle-dedicated-shell 1)))
```

I'm reading a couple of books on lisp in the hopes of being able to make more meaningful contributions, but for now the best I can do is attach a script with the command dh-elpa uses to execute the tests, and the full backtrace.  I hope it will be more useful than the truncated batch-mode one  :-)
[dh-elpa-ert-test-command.sh.gz](https://github.com/jorgenschaefer/elpy/files/1922085/dh-elpa-ert-test-command.sh.gz)
[elpy-shell-kill-all-should-kill-all-shells.bt.gz](https://github.com/jorgenschaefer/elpy/files/1922086/elpy-shell-kill-all-should-kill-all-shells.bt.gz)

**Comment by jorgenschaefer** [comment]
There was some seriously silly code in Elpy there … could you try with that commit?

Also added the coding comment.

**Comment by jorgenschaefer** [comment]
@galaunay Could you look at 48076693 and the failing tests in https://travis-ci.org/jorgenschaefer/elpy/jobs/369042581 ? I think the `add-hook` lines were added for the changes in the dedicated shell behavior, I am unsure what the correct behavior of these tests should be right now. Thank you :-)

**Comment by galaunay** [comment]
The hook was indeed quite risky.
I made a PR (#1352) to fix that.

**Comment by sten0** [comment]
Dear @jorgenschaefer and @galaunay,

Thank you very much for all of your help resolving this issue, I couldn't have done it alone  :-D  Elpy is now in Debian.
https://packages.debian.org/sid/elpa-elpy
https://tracker.debian.org/pkg/elpy

I'll file a PR momentarily to add installation instructions for Debian (and derivatives) systems.  At a later date I hope to take a stab at making `elpy-shell-send-region-or-buffer-should-notify-of-removing-main` run without ert-runner, but I think it's appropriate to close this issue now.

Sincerely,
Nicholas
