### ISSUE TITLE
Any way to toggle on/off flymake in elpy?

### ISSUE THREAD

**Issue by xiaohanyu** [jorgenschaefer/elpy#131]
I've glanced the source code but found no user option to disable flymake. 

I think this option is useful in cases where users want to try other syntax checkers, such as https://github.com/flycheck/flycheck. 

Thanks.

**Comment by DonBeo** [comment]
Where is the file `elpy-default-minor-modes`?  I think this should be included in the wiki

**Comment by jorgenschaefer** [comment]
It's called `elpy-modules` these days.
