### ISSUE TITLE
Request for defined alias or function renaming

### ISSUE THREAD

**Issue by saltycraig** [jorgenschaefer/elpy#1311]
When using a package like 'which-key', and/or without the menu entries visible, discovery of elpy's virtual environment commands is difficult unless you read the manual carefully. This is because unlike most (all other?) commands are prefixed with the 'elpy-' string. I would like to recommend that the pyvenv functions called by elpy be aliased at the very least to be more discoverable, e.g.:

```lisp
(defalias 'elpy-venv-workon 'pyvenv-workon)
(defalias 'elpy-venv-activate 'pyvenv-activate)
(defalias 'elpy-venv-deactivate 'pyvenv-deactivate)
```

This is what I do in my person init.el, and I think it could be benefical to be a default for most users.

**Comment by jorgenschaefer** [comment]
Hm. Thank you for the suggestion. This is a tricky one, really – there are plenty of commands with e.g. a `python-` prefix that make sense in Elpy. Do you want to prefix all of them with `elpy-`? Wile I understand where you are coming from, I don't think this is a good solution, and more of a problem with `which-key` than Elpy.
