### ISSUE TITLE
merge yasnippets upstream?

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1313]
Sean Whitton, [one of the] primary author[s] of Debian's dh-elpa asked me why elpy installs its snippets to its libdir, and when I looked into why this might be I found that it might be because [official yasnippets collection](https://github.com/AndreaCrotti/yasnippet-snippets) already has a python-mode and installing to the canonical system snippets location would clobber these files.  I asked on #elpy if elpy's snippets would be useful without elpy and the answer was "yes".  Sorry I can't remember who replied to this question, and I lost my irc screen session when I carelessly rebooted.  Has anyone thought about unbundling the snippets, given that they would be useful independent of elpy?  @AndreaCrotti what do you think about this hypothetical merge?

**Comment by gopar** [comment]
The snippets can certainly work without elpy, and I think they would a good addition to yasnippets. Although, I believe there some conflicting snippets that do the same (Can't remember if this is still the case or which snippets are the ones I'm thinking about), then those will need to be sorted out, along with moving the functions from `.yas-setup.el` as well.

**Comment by sten0** [comment]
When I took a look about a week ago, IIRC there was about 35% overlap (conflicts, by file name) but then each project complements the other's python-mode by about 33% (by number of snippets).  I don't believe I'm familiar enough with the expectations of each python-mode's users' expectations to be able to do a make both happy, but I'm willing to give it a try at the risk of future allegations of sloppy and ignorant work...  Oh, but the 22nd is the soonest I'll be able to dedicate any time to do this.

**Comment by galaunay** [comment]
I think that unifying the python snippet lists is a very good idea as well.
I don't see any points in keeping two parallel lists.

I'll be happy to help if it's become necessary.

**Comment by sten0** [comment]
I found a bit of unexpected time today so I forked yasnippet-snippets, broke elpy/snippets out into its own branch (with pruned rewritten history) and pushed here: https://github.com/sten0/yasnippet-snippets

@galaunay and @gopar : this is my first time doing this, so any hints, advice, or guidelines would be very much appreciated :-)

**Comment by AndreaCrotti** [comment]
Hi @sten0 
the maintainer of yasnippet-snippets here, if you'd like to open a PR I'm happy to give it a look, generally I'm perfectly happy in merging the snippets.

**Comment by galaunay** [comment]
Just before you put too much effort in it, I think we will need approval from Jorgen.

@jorgenschaefer Do you see any problem in merging elpy snippets in yasnippet-snippets and rely on it to provide snippets in Elpy ?

**Comment by jorgenschaefer** [comment]
I'm all for merging stuff and having less code in Elpy! :-D We can easily depend on that package, too, if it's not included in yasnippets already.

**Comment by sten0** [comment]
Sweet! :-)  The package to depend on is https://melpa.org/#/yasnippet-snippets

Unfortunately yasnippet-snippets is currently only available in melpa unstable.  I've opened an issue on the yasnippet-snippets side here: https://github.com/AndreaCrotti/yasnippet-snippets/issues/257

**Comment by jorgenschaefer** [comment]
Hm yes. Depending on a package in MELPA Unstable only would be annoying. I'm ok-ish with just recommending it to be installed manually instead of a hard dependency, but really, they should start tagging …

**Comment by sten0** [comment]
> Hm yes. Depending on a package in MELPA Unstable only would be annoying. I'm ok-ish with just recommending it to be installed manually instead of a hard dependency, but really, they should start tagging …

At least on Debian (and derivatives) I can make yasnippet-snippets a hard dependency ;-)  On the topic of versioning, I just noticed that yasnippet-snippets has a funny inconsistency.  MELPA (unstable) version is [20180307.518](https://melpa.org/#/yasnippet-snippets), but the new autoload snippets pkg-el version is [1.0.3](https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/yasnippet-snippets.el).

One thing at a time though.  I've just submitted a pull request for -snippets that prefers elpy's python-mode snippets for any conflicts and wait for feedback.

**Comment by sten0** [comment]
Reminder to myself, or for someone to prod me to do the work if I take to long: https://github.com/AndreaCrotti/yasnippet-snippets/pull/259/commits/494cefb4cb367ce93e244368c9193c234626a89e

Easy to fix on the elpy side ;-)

**Comment by AndreaCrotti** [comment]
Sp @sten0 I finally pushed a tag this morning to yasnippet-snippets, and if I understood correctly that's all I needed to do (1.0).

And it looks like it worked :)
https://stable.melpa.org/#/yasnippet-snippets
I thought it was harder than this!

Anyway feel free to use that also, I will now update melpa stable frequently.

**Comment by AndreaCrotti** [comment]
We are on 0.2 already because I realised that the version declared in the metadata was 1.0.3 as @sten0 mentioned, so I fixed that as well now

**Comment by jorgenschaefer** [comment]
@AndreaCrotti Thank you so much for your work! :-) And releasing often is great :-D

**Comment by sten0** [comment]
On Thu, Apr 19, 2018 at 09:47:50AM +0000, Andrea Crotti wrote:
>    We are on 0.2 already because I realised that the version declared in the
>    metadata was 1.0.3 as [1]@sten0 mentioned, so I fixed that as well now

@AndreaCrotti Thank you, much appreciated :-)

**Comment by sten0** [comment]
Update: waiting for yasnippet-snippets to merge my PR.

**Comment by sten0** [comment]
Update: had to do a v2 merge and some minor fixups and rebasing.  The new PR is here: https://github.com/AndreaCrotti/yasnippet-snippets/pull/278

Thanks to @galaunay for catching a couple of issues I missed do to lack of experience.

I'll get to work on the Elpy side soon, and expect that to to go much faster! :-D

@jorgenschaefer, with one exception.  What is your opinion on preconfiguring yasnippets-snippets' `python-mode` and Elpy to use PEP 394-compliant `python-interpreter` on Debian (and derivative) systems?  It's more consistent with the "prefer system packages ethos, and make things work out-of-the-box with them" ethos of the project, but it shifts the burden of configuration onto users (of Debian-provided Elpy) who use Python 2 virtualenvs...it seems to me that these users are more likely to read the README.Debian, and beginner Python 3 Ubuntu users are the least likely.  Apologies if you've already answered this question, I wasn't able to find it using a query of (elpy AND ("python 3" OR "python3")).

I'm unclear how this will interact with the following scenario:

1. A Debian||derivative user installs a future release of Elpy from MELPA that depends on yasnippet-snippets (>= some_version).
2. yasnippets-snippets/some_version is fulfilled by the system package, and the system package sets `python-interpreter` to use /usr/bin/python3
3. The MELPA-installed Elpy does not set `python-interpreter` and I think `elpy-rpc-python-command`, and `python-command` will default to $PATH/python, where $PATH might be $venv/bin/python.
4. Consequently, yasnippets-snippets will Python 3, but Elpy uses `python-command` and `elpy-rpc-python-command`.

Does Elpy detect when it's running in a venv and could it it set `python-interpreter` before reloading yasnippet-snippets?  In the months that have passed I've forgotten if `python-command` and `elpy-rpc-python-command` are buffer local or not, and I've only ever used system-provided python3 so just set them globally in my Emacs config.

Cheers,
Nicholas

**Comment by jorgenschaefer** [comment]
Hm. Whether Elpy talks to Python 2 or Python 3 depends mainly on the virtualenv, so the reloading should be done in a `pyvenv-post-activate-hooks` function I guess?

**Comment by azzamsa** [comment]
@galaunay any update on this?

**Comment by sten0** [comment]
@azzamsa AFAIK @AndreaCrotti is merging them bit by bit: https://github.com/AndreaCrotti/yasnippet-snippets/pull/278#issuecomment-460002112

**Comment by azzamsa** [comment]
@sten0 oh great, thank you for info.

**Comment by sten0** [comment]
This issue can finally be closed!  Thanks to @JulienPalard for the last big push which is sincerely appreciated.

https://github.com/AndreaCrotti/yasnippet-snippets/commit/9f67370d9dbff73b0a4bf7c859455659b193f991
