### ISSUE TITLE
Update Twine in requirements?

### ISSUE THREAD

**Issue by brainwane** [jorgenschaefer/elpy#1319]
Hi! Thanks for using [Twine](https://pypi.org/project/twine/)!

I noticed that your `requirements-dev.txt` requirements specify an old version of Twine. I just released [version 1.11.0](https://pypi.org/project/twine/1.11.0/) and would appreciate knowing if you have any trouble upgrading, so we can fix our bugs. Thanks and best wishes.

**Comment by jorgenschaefer** [comment]
This is what I would call awesome service, thank you for letting us know! Upgraded this and a few other dependencies :-)
