### ISSUE TITLE
What is the right way to disable redline highlighting of codes?

### ISSUE THREAD

**Issue by potholiday** [jorgenschaefer/elpy#1323]
I am getting redline like [these in my code ](https://cloud.githubusercontent.com/assets/1993919/3674313/818d3ee0-1275-11e4-8bf0-86fb07fb6fa2.png).  What is the right way to disable this from the start up itself?

**Comment by galaunay** [comment]
This is flymake telling you that something may be wrong about your code.
In your example, it may be packages that are imported but not used.

You can disable flymake by customizing `elpy-modules`:
do `M-x customize-variable` then choose `elpy-modules` and untick `Highlight syntax errors (Flymake)`.
