### ISSUE TITLE
jupyter console not starting properly

### ISSUE THREAD

**Issue by PeterChristoph** [jorgenschaefer/elpy#1324]
From time to time, jupyter console does not start properly. Normally it starts with 4 input prompts as the following:
Jupyter console 5.2.0

Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
In [2]: 
In [3]: 
In [4]: 

but sometimes it starts with only one input prompt and is not responding at all. When I invoke M-x shell from emacs and open a jupyter console, it works properly. 

My elpy-config:
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.3 (/home/.../anaconda3/bin/python)
Interactive Python: jupyter (/home/...anaconda3/bin/jupyter)
Emacs.............: 24.5.1
Elpy..............: 1.18.0
Jedi..............: 0.10.2
Rope..............: 0.10.5
Autopep8..........: 1.3.3
Yapf..............: Not found
Syntax checker....: flake8 (/home/.../anaconda3/bin/flake8)

**Comment by galaunay** [comment]
Are you using the [recommended configuration](https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup) for jupyter ?
```Elisp
   (setq python-shell-interpreter "jupyter"
         python-shell-interpreter-args "console --simple-prompt")
```

If so, do you have any more information that can help us understand what happen ?
Like a relevant message in your `*Messages*` buffer, or a backtrace from interrupting an hanging jupyter console ?

**Comment by PeterChristoph** [comment]
Dear Jorgen, 
sorry for responding late. 
Yes, I am using the recommended configuration and also tried (setenv "JUPYTER_CONSOLE_TEST" "1").
I hope my Messages and Backtrace will help.

*Messages* 
Making python-shell-interpreter local to *Python* while let-bound!
Making python-shell-interpreter-args local to *Python* while let-bound!
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
Quit

*Backtrace*
Debugger entered--entering a function:
* run-python("/home/.../anaconda3/bin/jupyter console --simple-prompt" nil t)
  #<subr call-interactively>(run-python record nil)
  apply(#<subr call-interactively> run-python (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> run-python record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (run-python record nil))
  call-interactively(run-python record nil)
  command-execute(run-python record)
  execute-extended-command(nil "run-python")
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> execute-extended-command (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> execute-extended-command nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by galaunay** [comment]
I can't see anything wrong from your Messages and Backtrace.

But I ran into a similar problem when using Jupyter console with a virtual environment.
I think it is due to python mode failing to detect the prompt correctly.
Have you a `*Warnings*` buffer with something like that in it:
```
Warning (python): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with ‘keyboard-quit’ and then try fixing the
interactive flag for your interpreter by adjusting the
‘python-shell-interpreter-interactive-arg’ or add regexps
matching shell prompts in the directory-local friendly vars:
  + ‘python-shell-prompt-regexp’
  + ‘python-shell-prompt-block-regexp’
  + ‘python-shell-prompt-output-regexp’
Or alternatively in:
  + ‘python-shell-prompt-input-regexps’
  + ‘python-shell-prompt-output-regexps’
```

**Comment by PeterChristoph** [comment]
No, I dont have a *Warnings*-Buffer. But what seems to work is to elpy-shell-kill and reinvoke run-python. That is fine to me. I can write a small lisp-function to work around my problems :-)

**Comment by galaunay** [comment]
I'm sorry you have to fall back to a workaround to make this work :).

Python-mode support for jupyter console is not perfect atm, let's hope a future release will fix this.
