### ISSUE TITLE
elpy-shell-send-statement-and-step send to python shell buffer with specific name

### ISSUE THREAD

**Issue by Xparx** [jorgenschaefer/elpy#1325]
I'm running a python inferior mode with buffer name specific to a specific task. 

However running C-ret will open the default *Python* inferior process shell buffer.

Is there a way to associate all commands from a script/python code buffer to forward to a specific python shell buffer?

**Comment by galaunay** [comment]
There is.

Here is the relevant [doc](https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-shell-set-local-shell).

Basically, you can use `M-x elpy-shell-set-local-shell` then enter the shell name (let's say "my-shell-name").

Elpy will then send everything to the python shell named `Python[my-shell-name]`.
This variable is buffer-local, so it will only affect the current buffer.

Hope it helps.

**Comment by Xparx** [comment]
Thanks for the quick reply.
It's close to what I want but it seems to do some thing unexpected.
I have a python shell buffer named `*Python:test-session*` if I run `M-x elpy-shell-set-local-shell RET *Python:test-session*` which as you note will result in me connecting to a shell named *Python[*Python:test-session*]*. The thing is that I get *Python:test-session* from an org-mode src block with :session test-session. 
Not sure what path to go as both paths adds to the shell name outside what I expect.

Is there a way to make elpy shell buffer naming more precise?

**Comment by galaunay** [comment]
Under the hood, Elpy uses `python-shell-buffer-name` to change the shell buffer name, but add the `Python[...]` part.

So in your case, you should get what you want by setting directly `python-shell-buffer-name`, like so:
```Elisp
(defun python-shell-change-shell-name (name)
  (interactive)
  (setq-local python-shell-buffer-name name))
```

You can then use:
```Elisp
(python-shell-change-shell-name "Python:test-session")
```
from your python buffer.

**Comment by Xparx** [comment]
That did the trick! Thank you. `elpy` is really a great project.
