### ISSUE TITLE
elpy can not detect modules

### ISSUE THREAD

**Issue by LuhengStat** [jorgenschaefer/elpy#1326]
I am using elpy and python3, when I use it in emacs and use
import requests
it said that "ModuleNotFoundError: No module named 'requests'"

However, the command can run in python3 in the terminal, 
could you tell what is going on? Below is my elpy setup

(elpy-enable)
;; For elpy
(setq elpy-rpc-python-command "python3")
;; For interactive shell
(setq python-shell-interpreter "python3")

(add-hook 'python-mode-hook #'elpy-mode)
(with-eval-after-load 'elpy
  (remove-hook 'elpy-modules 'elpy-module-flymake)
  ;;(add-hook 'elpy-mode-hook 'flycheck-mode)
  (add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save))

(setq elpy-rpc-backend "jedi")  
(setenv "IPY_TEST_SIMPLE_PROMPT" "1")
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i")

(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))

**Comment by galaunay** [comment]
Could you paste the result from `(elpy-config)` ?

**Comment by LuhengStat** [comment]
I reinstalled everything and the probelm solved. However, I still do not know why this happen. Thanks.

**Comment by galaunay** [comment]
May be linked to the fact that "~/local/.bin" is not in your path... or not.
Anyway, glad that it's fixed now.
