### ISSUE TITLE
elpy-config says I'm using the python from virtualenv but it is not.

### ISSUE THREAD

**Issue by AkashGanesan** [jorgenschaefer/elpy#1333]
# Summary

When I use pyvenv-activate, it activates the environment but it doesn't use the virtualenv's python even though elpy-config says so.  Also, I don't have exec-shell-from-path 

When I try the following after activating the environment, 
````
import sys
print sys.executable
````
It prints the global path instead of the one in the ENV.
# My configuration
## OS
Ubuntu 17.04

## Result of `(elpy-config)`
Virtualenv........: ENV (/home/akash/learn/504/final_project/EECS_504_Project/keras_Realtime_Multi-Person_Pose_Estimation/ENV)
RPC Python........: 3.6.3 (/home/akash/learn/504/final_project/EECS_504_Project/keras_Realtime_Multi-Person_Pose_Estimation/ENV/bin/python)
Interactive Python: jupyter (/home/akash/learn/504/final_project/EECS_504_Project/keras_Realtime_Multi-Person_Pose_Estimation/ENV/bin/jupyter)
Emacs.............: 25.2.2
Elpy..............: 1.19.0
Jedi..............: 0.11.1
Rope..............: Not found (0.10.7 available)
Autopep8..........: 1.3.5
Yapf..............: 0.21.0
Syntax checker....: flake8 (/home/akash/learn/504/final_project/EECS_504_Project/keras_Realtime_Multi-Person_Pose_Estimation/ENV/bin/flake8)

## Elpy configuration in my init.el
```
(elpy-enable)
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt")
;; To prevent exec-from-shell :: https://github.com/jorgenschaefer/elpy/issues/1001
(setq shell-file-name "/bin/bash")
```

**Comment by galaunay** [comment]
Thanks for reporting this.

I was not able to reproduce your issue.
Have you restarted the python shell after changing the environment ?
with `elpy-shell-kill-shell` and `elpy-shell-switch-to-shell` for example ?

**Comment by AkashGanesan** [comment]
Hi @galaunay :  I figured out why this went wrong.  In the virtualenv, jupyter was not installed.  When I installed this, it works.  However, without juypter, I get the above when I do elpy-config though.  Maybe elpy can tell when there's no virtualenv based jupyter.

**Comment by galaunay** [comment]
Thank you for the feedback.

Elpy is supposed to fall back to the system installation if jupyter is not installed in the virtualenv:
```
Virtualenv........: dummy (/home/glaunay/.virtualenvs/dummy)
RPC Python........: 3.6.4 (/home/glaunay/.virtualenvs/dummy/bin/python3)
Interactive Python: jupyter (/usr/bin/jupyter)
```

But apparently, uninstalling jupyter from pip does not remove the jupyter binaries...
This could explain why Elpy got confused.

**Comment by galaunay** [comment]
It might be a good idea indeed.

There is no particular reason to fall back to binaries outside the virtualenv, It just take the first interpreter it can find in the PATH.

I'll think about a way of implementing this, thank you for the suggestion.
