### ISSUE TITLE
Elpy not using python from "pyvenv-activated" Anaconda environment

### ISSUE THREAD

**Issue by janejkanske** [jorgenschaefer/elpy#1336]
# Summary
Activating a virtual environment with pyvenv-activate works fine, as the virtualenv row below changes to show the `(c:/Users/janejkanske/Anaconda3/envs/env1)` environment. However, Elpy does not use python from that environment. It instead defaults to use python from the environment named first in PATH, namely `(c:/Users/janejkanske/Anaconda3/envs/env2/python.exe)` in the env2 environment. Changing the order in which the evns is named in the PATH does the trick (that is, name env1 before env2) but that shouldn't be necessary, should it? How do i get elpy to use python from the "pyvenv-activated" environment? I've tried the solutions listed in https://github.com/jorgenschaefer/elpy/issues/1001, and other conda-elpy related issues.

# My configuration
I run windows 10, Emacs 25.2.1 and Python 3.5.5.

Here is my default elpy-config (without any pyvenv-activate usage):
`Virtualenv........:  None`
`RPC Python........: 3.5.5 (c:/Users/janejkanske/Anaconda3/envs/env2/python.exe)`
`Interactive Python: python (c:/Users/janejkanske/Anaconda3/envs/env2/python.exe)`
`Emacs.............: 25.2.1`
`Elpy..............: 1.15.1`
`Jedi..............: Not found (0.11.1 available)`
`Rope..............: Not found (0.10.7 available)`
`Importmagic.......: Not found (0.1.7 available)`
`Autopep8..........: Not found (1.3.5 available)`
`Yapf..............: Not found (0.21.0 available)`
`Syntax checker....: Not found (flake8)`

# My init.el

`(setenv "WORKON_HOME" "C:\\Users\\janejkanske\\Anaconda3\\envs")`
`(setq elpy-rpc-python-command "python")`

**Comment by jorgenschaefer** [comment]
> Changing the order in which the evns is named in the PATH does the trick (that is, name env1 before env2) but that shouldn't be necessary, should it?

That's what "activating a virtualenv" does, really – it puts the bin directory of the virtualenv in front of `PATH`. I think the problem here is that either anaconda or Windows use non-standard virtualenv layouts, i.e. putting `python.exe` in the virtualenv directory instead of `bin/` in there.
