### ISSUE TITLE
 jupyter fails

### ISSUE THREAD

**Issue by LuhengStat** [jorgenschaefer/elpy#1338]
# jupyter can not work
when I use
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt")
the jupyer do not work and some warnings sais:

Warning (python): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with ‘keyboard-quit’ and then try fixing the
interactive flag for your interpreter by adjusting the
‘python-shell-interpreter-interactive-arg’ or add regexps
matching shell prompts in the directory-local friendly vars:
  + ‘python-shell-prompt-regexp’
  + ‘python-shell-prompt-block-regexp’
  + ‘python-shell-prompt-output-regexp’
Or alternatively in:
  + ‘python-shell-prompt-input-regexps’
  + ‘python-shell-prompt-output-regexps’

# Steps to reproduce

# My configuration
## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.4 (/anaconda3/bin/python)
Interactive Python: jupyter (/anaconda3/bin/jupyter)
Emacs.............: 25.3.1
Elpy..............: 1.19.0
Jedi..............: 0.11.1
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.21.0
Syntax checker....: Not found (flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH -- and then do
`elpy-rpc-restart'.

The configured syntax checker could not be found. Elpy uses this
program to provide syntax checks of your programs, so you might want
to install one. Elpy by default uses flake8.

[run] python -m pip install --user flake8

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button
to invoke its action.  Invoke [+] to expand a group, and [-] to
collapse an expanded group.  Invoke the [Group], [Face], and [Option]
buttons below to edit that item in another window.

```

## Elpy configuration in my init.el
```

(package-initialize)
(elpy-enable)
(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))

(add-hook 'inferior-python-mode-hook 'visual-line-mode)
(define-key elpy-mode-map (kbd "C-x C-n") 'elpy-shell-send-group-and-step)

(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt")

```

**Comment by galaunay** [comment]
Python.el cannot (at the moment) detects jupyter console prompt. 
So the warnings you get is kind of expected.

However, this should not prevent the interpreter to work.
You should be able to remove the warnings and fix this by adding the following to your `init.el`:
```Elisp
(setq python-shell-prompt-detect-failure-warning nil)
```

**Comment by LuhengStat** [comment]
Thanks. However, the waring still exist with 

Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native-enable’ was t and "jupyter" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 


and my configure is : 

(package-initialize)
(elpy-enable)
(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))

(add-hook 'inferior-python-mode-hook 'visual-line-mode)
(define-key elpy-mode-map (kbd "C-x C-n") 'elpy-shell-send-group-and-step)

(setq python-shell-prompt-detect-failure-warning nil)
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt")

**Comment by LuhengStat** [comment]
I searched the issues before and find I must add 
(setq python-shell-completion-native-enable nil)
to disable these. Now my final settings is( just for refer):



(package-initialize)
(elpy-enable)
(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))

(add-hook 'inferior-python-mode-hook 'visual-line-mode)
(define-key elpy-mode-map (kbd "C-x C-n") 'elpy-shell-send-group-and-step)

(setq python-shell-prompt-detect-failure-warning nil)
(setq python-shell-completion-native-enable nil)
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt")

**Comment by galaunay** [comment]
Thanks for the feedback,
I will add a note on this on the documentation.
