### ISSUE TITLE
How to gracefully interrupt or exit a running python code?

### ISSUE THREAD

**Issue by potholiday** [jorgenschaefer/elpy#1339]
Sometimes in the middle of running python code we need to hard exit the running code. For example take this looping of python.

````
for i in range(100000):
      print i
````

I can hard exit this loop by `Signals>Kill` the problem with this method is it kills the python process completely and again I have to restart the python process. In some IDE's we can interrupt a running  code without killing the process itself. How can I do this with elpy?

**Comment by potholiday** [comment]
Nevermind, Initially my `Signals>Break` didnt work. Now it seems to working

**Comment by bdixon95** [comment]
Wait I am having this problem now. How do I send a Signals>Break?

**Comment by potholiday** [comment]
@bdixon95 I am using Emacs gui and we have to select the shell first and then from the toolbar select Signals>Break

**Comment by galaunay** [comment]
If you want to bind a key to do that from the python script, you can use a function like this:
```Elisp
(defun elpy-shell-interrupt ()
  "Interrupt the process associated to the current python script."
  (interactive)
  (elpy-shell-switch-to-shell)
  (interrupt-process)
  (elpy-shell-switch-to-buffer))
```
