### ISSUE TITLE
keep cursor in code buffer

### ISSUE THREAD

**Issue by mankoff** [jorgenschaefer/elpy#134]
`C-c C-c` executes code buffer but moves cursor to IPython buffer. Is there a way to keep the cursor in the code buffer?

**Comment by dwla** [comment]
I'm a beginner of Emacs and I try my best to describe the issue. I use elpy-20220322.41 and the same problem mentioned above occurs. C-c C-c or C-RET executes the code successfully but the cursor will jump to the *Python* buffer. I wonder which function need to modified to keep the cursor in the code buffer when execute the code.

I try to fix the problem as previous comment states, but I cannot find the elpy-shell-send-region-or-buffer function in file espy-shell.el.
