### ISSUE TITLE
Suggestions: key blinding for "return" in inferior python

### ISSUE THREAD

**Issue by LuhengStat** [jorgenschaefer/elpy#1348]
In iniferior python, the "return" key runs all the code under its below, I think it 
is not natural and in most situations the codes below can not run. A natural 
way may be just go to the end of the buffer? 

(defun mydef-RET ()
  "define RET behavior in python"
  (interactive)
  (setq current-line (what-line))
  (end-of-buffer)
  (if (string=  current-line (what-line))
      (comint-send-input)))

(define-key inferior-python-mode-map (kbd "RET") 'mydef-RET)

**Comment by LuhengStat** [comment]
`
(defun MyDef-RET ()
  "define RET behavior in python"
  (interactive)
  (setq current-line (what-line))
  (end-of-buffer)
  (if (string=  current-line (what-line))
      (comint-send-input)))
(define-key inferior-python-mode-map (kbd "RET") 'MyDef-RET)`

**Comment by jorgenschaefer** [comment]
The current behavior is the standard behavior in all Emacs shells. I guess what is "natural" is quite subjective. Your code has nothing to do with Elpy, though – you could try and talk to the Emacs maintainers about it?

**Comment by LuhengStat** [comment]
OK, thanks.
