### ISSUE TITLE
no completion on dot

### ISSUE THREAD

**Issue by CyBu** [jorgenschaefer/elpy#1354]
# Summary

Elpy does not start-up on my emacs
I was expecting that the elpy package would provide auto-completion 
while I am writing code in python. However, while it suggests some recently 
used items (statement), it fails to show anything on a dot. 

# Steps to reproduce
--> Auto-complete statement works<br />
```
import numpy as np
data1 = [1,2,3]
data2 = [3,4,5]

print(data1)   # autocompletes with data1 or data2 choice
```
<br />
--> But, auto-complete "on dot" does not work<br />

```
import numpy as np
data1 = [1,2,3]
data2 = [3,4,5]

np.       # does not autocomplete with suggestions

```
<br />

# My configuration
## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/usr/local/bin/python3)
Interactive Python: /usr/local/bin/python3 (/usr/local/bin/python3)
Emacs.............: 25.3.1
Elpy..............: 1.19.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.21.0
Syntax checker....: Not found (flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH -- and then do
`elpy-rpc-restart'.

The configured syntax checker could not be found. Elpy uses this
program to provide syntax checks of your programs, so you might want
to install one. Elpy by default uses flake8.

[run] /usr/local/bin/python3 -m pip install --user flake8
```
 Note:<br />
 - I could not find the flake8 package for emacs, but it is installed 
 on my python  (pip install flake8)<br />
- It should not be necessary to have a Virtualenv set-up?  Ot if it is, how do I do that?<br />

## Elpy configuration in my init.el
```
;; https://realpython.com/emacs-the-best-python-editor/
;; 

;; init.el --- Emacs configuration

;; INSTALL PACKAGES
;; --------------------------------------

(require 'package)

(add-to-list 'package-archives
       '("melpa" . "http://melpa.org/packages/") t)

;;type y/n instead of yes/no
(defalias 'yes-or-no-p 'y-or-n-p)

(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))

(defvar myPackages
  '(better-defaults
    material-theme))

(mapc #'(lambda (package)
    (unless (package-installed-p package)
      (package-install package)))
      myPackages)


;; BASIC CUSTOMIZATION
;; --------------------------------------
(setq inhibit-startup-message t) ;; hide the startup message
(load-theme 'material t) ;; load material theme
(global-linum-mode t) ;; enable line numbers globally

(defun python-shell-completion-native-try ()
  "Return non-nil if can trigger native completion."
  (with-eval-after-load 'python
    '(let ((python-shell-completion-native-enable t)
           (python-shell-completion-native-output-timeout
            python-shell-completion-native-try-output-timeout))
       (python-shell-completion-native-get-completions
        (get-buffer-process (current-buffer))
        nil "_"))))

;; PYTHON 3
;;---------------------------------------
;; which python:  python3
(setq python-shell-interpreter "/usr/local/bin/python3")
(setq python-shell-completion-native-enable nil)
(setq elpy-rpc-python-command "/usr/local/bin/python3")

(defvar myPackages
  '(better-defaults
    elpy
    jedi
    flycheck
    material-theme
    py-autopep8))

(package-initialize)
(elpy-enable)

;;---------------------------------------


(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (elpy material-theme better-defaults))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

```

**Comment by galaunay** [comment]
## Notes on elpy-config

>  could not find the flake8 package for emacs, but it is installed
on my python (pip install flake8)

flake8 is just a python package, so you did as expected.
`elpy-config` should see and use it now.
If it is not, make sure the flake8 binaries are on your PATH.

> It should not be necessary to have a Virtualenv set-up? Ot if it is, how do I do that?

It is not mandatory to use a virtualenv.
It is useful if you want to use different package versions for different projects.
Here is the documentation of [virtualenv](https://virtualenv.pypa.io/en/stable/) and [pyvenv](https://github.com/jorgenschaefer/pyvenv) if you want to know more about this.

## Completion on dot

Regarding your issue, Elpy implements it's own wrapper around jedi, so you don't need to have the `jedi` emacs package installed.
You can try unsinstalling the `jedi` emacs package, with `M-x package-delete RET jedi`.

If it's still not working, could you try `M-x elpy-company-backend` with the cursor after the dot, and post what happen ?

note: Getting the completion choices can take some time, what happen if you wait a few seconds after typing the dot ?

**Comment by CyBu** [comment]
Thank you for your answers and clarifications. 

- removed the jedi packages (core and 2018....), but it showed no changes. 
- when i do M-TAB and move the cursor, i see a message: "cannot complete at point". If I don't move the cursor it just hangs there.
- when I do ``` M-x elpy-company-backend``` with the cursor after the ```np.``` nothing happens until i move the cursor, then it shows: "cannot complete at point". If I don't move the cursor it just hangs there.
In the message buffer i see: 
```
No completion found
user-error: Cannot complete at point
```
- however, if i do ``` M-x elpy-company-backend``` on an empty line, then I see drop down menu pop-up with a few choices.  Not sure if that helps you.

- regarding the PATH, I understand from the message:
```The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH -- and then do
`elpy-rpc-restart'.
```
that i should do: 
```export PATH=$PATH:$HOME/.local/bin/``` but when i do so and echo $PATH then I have a message saying that this is not a directory, and indeed the directory stops at 
$HOME/.local/ in my drive (i.e. there is no /bin). should I create it?

**Comment by CyBu** [comment]
my current PATH is: 
```
echo $PATH
/bin:/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:
```

**Comment by CyBu** [comment]
solved:  
All what was needed is to create a venv, replicate my python3 and modules in it and finally have emacs load that venv.

**Comment by galaunay** [comment]
Thanks for the feedback.
Happy that you found a solution.

Your are not the only one to have issues with Elpy completion when not using a virtual env.
(see #1356).
I'll try to investigate this.
