### ISSUE TITLE
[Question] Clear Python Shell Buffer

### ISSUE THREAD

**Issue by azzamsa** [jorgenschaefer/elpy#1355]
I saw another issue https://github.com/jorgenschaefer/elpy/issues/1204.

But, Is there any default keybinding or something like M-x clear-elpy-shell-buffer ?

I don't find such feature in the [docs](http://elpy.readthedocs.io/en/latest/ide.html#the-shell-buffer). Or am I miss something ?

Thanks for this great package. :)

**Comment by azzamsa** [comment]
@galaunay. Thanks a lot. Work like a charm. :)

Thanks.

**Comment by potholiday** [comment]
@galaunay  I also looking for a bash like `clear` function to clear my python shell. I added this to my init.el file 
```
(defun elpy-shell-clear-shell ()
  "Clear the current shell buffer."
  (interactive)
  (with-current-buffer (process-buffer (elpy-shell-get-or-create-process))
    (comint-clear-buffer)))
```
When I tried `M-x elpy-shell-clear-shell` it gives this error `symbol's function definition is void: comint-clear-buffer`. What do I do now?

**Comment by azzamsa** [comment]
@potholiday it works for me. Sounds like you invoke it when no python prompt exists. I got the same error last week when I tried to invoke non-existent prompt

**Comment by potholiday** [comment]
@azzamsa Can you plz tell me the steps you took to get it to work. Mine still not working?

**Comment by azzamsa** [comment]
Sure. [this is](https://github.com/azzamsa/emacs.d/blob/cdb634e0ae104665b11fbec6a3f8337a1439ff3d/modules/aza-python.el#L16) my elpy config.

**Comment by potholiday** [comment]
Mine `init.el` 

```
;;Elpy
(package-initialize)
(elpy-enable)

(defun elpy-shell-clear-shell ()
  "Clear the current shell buffer."
  (interactive)
  (with-current-buffer (process-buffer (elpy-shell-get-or-create-process))
    (comint-clear-buffer)))

```
Cant seems to find what I am doing wrong here

**Comment by galaunay** [comment]
if `comint-clear-buffer` is not defined, you can try this:
```Elisp
;;Elpy
(package-initialize)
(elpy-enable)
(require 'comint)

(defun elpy-shell-clear-shell ()
  "Clear the current shell buffer."
  (interactive)
  (with-current-buffer (process-buffer (elpy-shell-get-or-create-process))
    (comint-clear-buffer)))

```

**Comment by potholiday** [comment]
Still not working. In order to avoid any confusion (if any) I am looking for a clear function like this https://upload.wikimedia.org/wikipedia/commons/0/0f/Clear-gnulinux.gif . For emacs insted of `clear` in shell `M-x elpy-shell-clear-shell`

**Comment by azzamsa** [comment]
Ehsell already had `clear` [support](https://github.com/emacs-mirror/emacs/blob/973d10a34b23f2ce5acc00a90ec9767e6237fefa/lisp/eshell/esh-mode.el#L881). 

I think binding `elpy-shell-clear-shell` to key is faster than typing 'clear'.

**Comment by galaunay** [comment]
We are on the same page about the clear function.

I don't know when `comint-clear-buffer` has been implemented, could you give us some information about your Emacs  version ?

You can also try the following function, that does not rely on `comint-clear-buffer`:
```Elisp
(defun elpy-shell-clear-shell ()
  "Clear the current shell buffer."
  (interactive)
  (with-current-buffer (process-buffer (elpy-shell-get-or-create-process))
    (let ((comint-buffer-maximum-size 0))
      (comint-truncate-buffer))))
```

**Comment by potholiday** [comment]
@galaunay  Thank you that worked. My version is `Emacs 24.5.1`

**Comment by azzamsa** [comment]
Apart from `elpy-shell-clear-shell`. You can clear inferior-python buffer using `comint-clear-buffer` which bound to `C-c M-o`.
