### ISSUE TITLE
ELPY: autocompletion does not work for all python modules

### ISSUE THREAD

**Issue by CyBu** [jorgenschaefer/elpy#1356]
# Summary
I could get Elpy to do some of the autocompletion, but it does not work for all module. 
# Steps to reproduce
For example, using python3, 
```numpy.``` triggers the autocompletion, but
```pandas.``` does not trigger autocompletion
My guess is that numpy came standard with python3 (at least for me) but pandas is an installed module (with pip in a terminal console). The corollary is that emacs does not seem to use the same PATH as if I was using python in a terminal. 
Now the question is:  how do I remedy this?
# My configuration
## OS
OSX 10.13.4 (highsierra)
Emacs: Version 25.3 (9.0)
## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.5.2 (/usr/local/bin/python3)
Interactive Python: /usr/local/bin/python3 (/usr/local/bin/python3)
Emacs.............: 25.3.1
Elpy..............: 1.19.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.21.0
Syntax checker....: Not found (flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

**The directory ~/.local/bin/ is not in your PATH.** 
**OK, now how do I put it in my PATH ?**
As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH -- and then do
`elpy-rpc-restart'.

The configured syntax checker could not be found. Elpy uses this
program to provide syntax checks of your programs, so you might want
to install one. Elpy by default uses flake8.

[run] /usr/local/bin/python3 -m pip install --user flake8  
#( it is installed, but emacs doesn't see it!)
```

## Elpy configuration in my init.el
```
;; https://realpython.com/emacs-the-best-python-editor/
;; 

;; init.el --- Emacs configuration

;; INSTALL PACKAGES
;; --------------------------------------

(require 'package)

(add-to-list 'package-archives
       '("melpa" . "http://melpa.org/packages/") t)

;;type y/n instead of yes/no
(defalias 'yes-or-no-p 'y-or-n-p)

(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))

(defvar myPackages
  '(better-defaults
    material-theme))

(mapc #'(lambda (package)
    (unless (package-installed-p package)
      (package-install package)))
      myPackages)

;; BASIC CUSTOMIZATION
;; --------------------------------------
(setq inhibit-startup-message t) ;; hide the startup message
(load-theme 'material t) ;; load material theme
(global-linum-mode t) ;; enable line numbers globally

(defun python-shell-completion-native-try ()
  "Return non-nil if can trigger native completion."
  (with-eval-after-load 'python
    '(let ((python-shell-completion-native-enable t)
           (python-shell-completion-native-output-timeout
            python-shell-completion-native-try-output-timeout))
       (python-shell-completion-native-get-completions
        (get-buffer-process (current-buffer))
        nil "_"))))

;; which python:  python3
(setq python-shell-interpreter "/usr/local/bin/python3")
(setq python-shell-completion-native-enable nil)
(setq elpy-rpc-python-command "/usr/local/bin/python3")

;; elpy
(package-initialize)
(elpy-enable)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (elpy material-theme better-defaults))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Questions:**  
- How do I add The directory ~/.local/bin/ to my PATH, given that export PATH="/.local/bin:$PATH" did not work?
- How can I make that pandas, flake8 and all the other installed modules are seen by emacs and Elpy for autocompletion?

<img width="294" alt="numpy" src="https://user-images.githubusercontent.com/25697995/39204528-02ad8fbe-47c6-11e8-9710-1c08b112608c.png">
<img width="319" alt="pandas" src="https://user-images.githubusercontent.com/25697995/39204533-07513fde-47c6-11e8-90fa-be91277cd51f.png">

**Comment by galaunay** [comment]
## PATH modification

I use this in my `init.el`:
```Elisp
(setenv "PATH" (concat (expand-file-name "~/.local/bin:") (getenv "PATH")))
```
However, doing : 
```Bash
export PATH="$PATH:/home/USERNAME/.local/bin" 
emacs
```
in a terminal should work as well.

## Flake8

If modifying the PATH does not make flake8 to be detected, could you post your PATH, PYTHONPATH and the localisation of flake8 binaries (with `locate flake8` or something) ?
So we can check where the issue come from.

## Pandas completion

Same as flake8, what is the installation path of pandas and numpy ?

**Comment by CyBu** [comment]
Thanks for your response.  
In fact what happened is that my emacs config was not loading the python3 i thought it was. 
Instead it was loading the python2.7. 
So I created a new venv replicating my python3 set-up and the modules I needed. Then to assure that emacs picks it up. 

```
Elpy Configuration

Virtualenv........: emacs_python3 (/Users/cybu/emacs_python3)
RPC Python........: 3.5.2 (/Users/cybu/emacs_python3/bin/python3)
Interactive Python: /Users/cybu/emacs_python3/bin/python3 (/Users/cybu/emacs_python3/bin/python3)
Emacs.............: 25.3.1
Elpy..............: 1.19.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.21.0
Syntax checker....: flake8 (/Library/Frameworks/Python.framework/Versions/3.5/bin/flake8)

```

**Comment by galaunay** [comment]
This is weird.
`elpy-config` mentioned `python3`, so jedi should be using that...

**Comment by CyBu** [comment]
Hi, 

I think this is due to Mac that comes standard with python2.7 and numpy but no pip, no pandas, etc.
So it seems that Elpy pointed to a different python than python3 and that s the reason it did not get
the auto completion for pandas etc. Just ofrcing to the venv did the trick.

If it helps, I got this from: 
https://stackoverflow.com/questions/50007537/emacs-python-elpy-auto-complete-not-working-for-all?noredirect=1#comment87034409_50007537

Next is to have auto complete and correct indentation on org-mode!
Which I am still wrestling with… suggestions welcome :)

Thanks
Cy

**Comment by galaunay** [comment]
Thanks for the feedback.
There is certainly a way of making elpy smarter about that.

This is pretty confusing that elpy uses python2 for completion and python3 else.

**Comment by CyBu** [comment]
I agree, and it took me a while to understand what the problem was. 
Also, I am thinking that maybe a way to overcome this would be 
to force the creation of an virtual environment and have elpy point to it
automatically.  At least for Macs and probably also linux as they come 
standard with python 2.7.
Maybe not super elegant, but it will work out of the box

Of note also, I had started using aquamacs. But the folder for the 
for the init.el and packages is called "Aquamacs Emacs”, yes with a space!
So as a result no pip work.  

Lastly, if you could direct me to a way to have elpy auto-completion 
for org-mode, I would greatly appreciate it. 

Thanks for the good works!

**Comment by CyBu** [comment]
Maybe strongly recommend the virtual environment then :)

For pip:
Apple comes standard with python2.7 installed with a limited number of packages. 
pip is not one of them, I suppose this is to avoid that users install packages on the top of python2.7
as I believe apple is using python in quite a few of its apps. I seem to remember that python2.7 does not come with pip anyways. 

Thanks for the C-c’, it work fine with elpy. 
Great job for elpy thanks!

Have  great week end
Cy

**Comment by galaunay** [comment]
Thanks, for the feedback.

I will try to replicate this issue on linux to find a fix, or at least warn users when this happen. 

Have a nice week-end too.

**Comment by acmcclung** [comment]
I am having a very similar issue to this one, even working within a virtual environment: completion works for standard library modules (`json`, `math`, etc.) but not for `numpy`.

# Steps to reproduce
Activate my `py36` virtual environment using `M-x pyvenv-activate`, import `json` and `numpy`, observe completion after typing `json.` but not after `numpy.`.

# My configuration
## OS
macOS High Sierra
Emacs 26.1

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: py36 (/anaconda/envs/py36)
RPC Python........: 3.6.5 (/anaconda/envs/py36/bin/python)
Interactive Python: python (/anaconda/envs/py36/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.23.0
Jedi..............: 0.12.1
Rope..............: 0.10.7
Autopep8..........: 1.3.4 (1.3.5 available)
Yapf..............: 0.22.0
Black.............: 18.6b4
Syntax checker....: flake8 (/anaconda/envs/py36/bin/flake8)

There is a newer version of the autopep8 package available.

[run] python -m pip install --upgrade autopep8
```

## Elpy configuration in my init.el
```
(elpy-enable)
```

**Comment by galaunay** [comment]
Numpy can take some time to be analysed by jedi.
Is it still not working after several tries at the same position ?

Else, is numpy installed in your virtualenv, or just on your system ?

**Comment by acmcclung** [comment]
Thanks for replying. numpy is installed in several virtual environments, in the anaconda base and in system python (probably shouldn't have done this last bit, but oh well). Playing around with it a little further I am able to get completion in some virtual environments but not all, suggesting the problem has something to do with the particulars of my virtual environment, not elpy.

Do you know of some reason why jedi would hang in one virtualenv and not another? It takes about two seconds for one environment and hangs for >1 min in my `py36` environment. `json` is equally quick to load in both.

**Comment by galaunay** [comment]
Sorry, no idea.

It may help to benchmark directly jedi (to make sure the problem comes from there) with something like this:
```Python
import jedi

text = """import json
json."""
script = jedi.Script(source=text, line=2, column=5)
compl = [compl.name for compl in script.completions()]
print(compl)

text = """import numpy as np
np."""
script = jedi.Script(source=text, line=2, column=3)
compl = [compl.name for compl in script.completions()]
print(compl)i

print("System env: {}".format(list(jedi.find_system_environments())))
print("Default env: {}".format(jedi.get_default_environment()))
```
The last two lines should print the system env and your current virtualenv
(Just to check everything is in order...)
