### ISSUE TITLE
flymake configuration error popup

### ISSUE THREAD

**Issue by jeffpollock9** [jorgenschaefer/elpy#1361]
# Summary

I get the following popup whenever I open a .py file:

![screenshot from 2018-04-29 16-01-18](https://user-images.githubusercontent.com/5081168/39407978-f9a20d28-4bc6-11e8-8676-9a9dcab90ad4.png)

# Steps to reproduce

open any python file

# My configuration
## OS

ubuntu 18.04

## Result of `(elpy-config)`

```
Virtualenv........: None
RPC Python........: 3.6.5 (/usr/bin/python3)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 25.2.2
Elpy..............: 1.20.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.21.0
Syntax checker....: flake8 (/usr/local/bin/flake8)
```

## Elpy configuration in my init.el

my whole config is [here](https://github.com/jeffpollock9/.emacs.d/blob/master/init.el) but the important parts (I think) are:

```
(use-package elpy
  :ensure t
  :init
  (setq python-shell-interpreter "python3")
  (setq elpy-rpc-python-command "python3")
  (elpy-enable)
  :bind
  ("C-b" . elpy-autopep8-fix-code))
```

many thanks for elpy and for any time you can spare on this issue!

**Comment by galaunay** [comment]
I would say that the issue come from the flymake configuration file (`/home/jeff/workspace/misc/misc/python/adjoint_flymake.py`).
Could you post its content here ?

**Comment by jeffpollock9** [comment]
@galaunay thanks for the reply. I am probably being a bit dumb but I can't see how to post the content of that file, either it gets created and deleted too fast or it doesn't get created at all.

**Comment by galaunay** [comment]
Ok, my bad, it appears that `*_flymake.py` are temporary files created by flymake.

Could it be a permission problem ? With flymake unable to create this temporary file ?

Flymake log could give us additional information on what happen.
Could you activate it (with `(setq flymake-log-level 3)`), then open a python buffer and post the log messages that should appear in your `*Messages*` buffer ?

**Comment by jeffpollock9** [comment]
cool - I think that gives some useful information - the file is quite big so I have uploaded it [here](https://github.com/jorgenschaefer/elpy/files/1972462/log.txt).

Looks like there are a few errors, for example:

```
parsed ‘flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.’, no line-err-info
```

Can't really look into it right now but will do soon - cheers!

**Comment by galaunay** [comment]
Apparently this is due to an incompatibility between pycodestyle and flake8 (see [here](https://github.com/PyCQA/pycodestyle/issues/741)).

A PR has been merged in flake8 two weeks ago to address this issue.
This should disappear with the next flake8 release.

**Comment by jeffpollock9** [comment]
Yes it appears so - quite sure this is nothing to do with elpy.

Many thanks for your help, @galaunay
