### ISSUE TITLE
Autocomplete does not work on function inputs

### ISSUE THREAD

**Issue by NahsiN** [jorgenschaefer/elpy#1366]
# Summary
Consider the following code
```python
def foo(text):
    a = 'Hello world'
    a.spl
    text.spl

def main():
    foo('Hello World')
```
Autocomplete works on `a.spl` suggesting split and splitlines but not on `text.spl`. Realizing this might be a Jedi issue, I installed Atom along with the [autocomplete-python](https://atom.io/packages/autocomplete-python) package which also uses Jedi in the background. And in Atom, the autocomplete candidates are bang on which leads me to believe that the underlying issue is perhaps not with Jedi?

# Steps to reproduce
In your Emacs editor, type the above code snippet and examine the completion candidates for `text.spl`

# My configuration
## OS
Ubuntu 17.10
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.3 (/usr/bin/python3)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 25.2.2
Elpy..............: 1.17.0
Jedi..............: 0.11.1 (0.12.0 available)
Rope..............: 0.10.5
Importmagic.......: 0.1.7
Autopep8..........: Not found (1.3.5 available)
Yapf..............: 0.15.1 (0.21.0 available)
Syntax checker....: flake8 (/usr/bin/flake8)
```

## Elpy configuration in my init.el
```
(custom-set-variables
 '(elpy-rpc-backend nil)
 '(elpy-rpc-python-command "python3")
)
(package-initialize)
(elpy-enable)
(elpy-use-ipython)
```

**Comment by NahsiN** [comment]
That's good to know. I just updated my Jedi to 0.12.0 which did not resolve the issue.
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.3 (/usr/bin/python3)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 25.2.2
Elpy..............: 1.17.0
Jedi..............: 0.12.0
Rope..............: 0.10.5
Importmagic.......: 0.1.7
Autopep8..........: Not found (1.3.5 available)
Yapf..............: 0.15.1 (0.21.0 available)
Syntax checker....: flake8 (/usr/bin/flake8)
```

**Comment by NahsiN** [comment]
I just updated my elpy version to 1.20.0 and completion for both `a.sp` and `text.sp`. Issue resolved.

**Comment by NahsiN** [comment]
Btw, I did ask the Jedi community https://github.com/davidhalter/jedi/issues/1120 Seems to be a known issue with pandas.

**Comment by galaunay** [comment]
Thanks for the feedback.

If it is a pandas/jedi issue, I am afraid there is not a lot we can do from elpy...
We will have to wait for the next jedi version.
