### ISSUE TITLE
[Question] elpy find-files requires ivy

### ISSUE THREAD

**Issue by azzamsa** [jorgenschaefer/elpy#1368]
I am surprised that I have ivy installed in my system. I don't need ivy at all. I use other package with similar functionality.

Tracking the roots. It was installed as dependency of `[find-file-in-project](https://github.com/technomancy/find-file-in-project) that required by Elpy.

Why does Elpy has large scope that nothing to do with python development ?
I think managing files can be handled by user not by Elpy.

It's sad for non ivy user to have it installed just to use Elpy. Never use it but installed. It's better to let user decide things like this. 

Thanks lot for Elpy.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! I do not understand the question. Did Elpy configure anything that affects your workflow outside of Python development? Or are you worried about disk space?

**Comment by azzamsa** [comment]
Hi Schäfer. 

I mean. for managing/finding files in project. why you don't leave it to users ?

e.g using projectile, find-file-in-projects, helm-find-files.

So elpy doesn't need to manage this. I mean it's better for elpy to focus only with develompent e.g linting, formatting, code checking, virtualenv. not project files management. 

Putting this misc functionality within elpy lead elpy to depends to many other packages that has low correlation with python development , e.g ivy, find-files.

**Comment by jorgenschaefer** [comment]
Elpy provides a convenient way of opening files in your current project, which is helpful for Python development. If you like the `C-c C-f` shortcut, you can change how Elpy handles finding files using `(define-key elpy-mode-map (kbd "C-c C-f") <your file finding function>)`. I still do not understand the problem?

**Comment by azzamsa** [comment]
> I still do not understand the problem?

Sorry I think I can't describe the problem clearly. English is not my primary language. I have to choose the correct word to keep talking politely and doesn't hurt anyone feeling.

I will try to describe it again.

I heard Unix philosophy. "Do One Thing and Do It Well". I am surprised that Elpy depend on ivy to preserve user convenience for finding files withing project. In my humble opinion. I think it's better for Elpy not to have this functionality. Since emacs user already have their own way to manage/find files.

So Elpy codebase become cleaner and more modular. because user can choose/use their own way to manage/find files.

However. Maybe I am wrong.

**Comment by jorgenschaefer** [comment]
> I heard Unix philosophy. "Do One Thing and Do It Well".

I don't think Emacs follows this "unix philosophy" at all. Elpy certainly does not.

I think this is just a case of mis-matched expectations. Elpy does not try to be minimal. The purpose of Elpy is that you can easily install a fully-featured Python development environment. This includes many  other packages from Emacs. Elpy tries to make it possible for you to trim it down if it includes things you don't like, but the primary goal is to reduce the things the user has to do to get a useful environment.

**Comment by azzamsa** [comment]
> I think this is just a case of mis-matched expectations. Elpy does not try to be minimal. 

Nah. I got that key. "Elpy does not try to be minimal". It's true for " mis-matched expectations". Because I don't know Elpy philosophy yet.

Then it's like connecting emacs to ERC. we have foo for huge functionality, baz for minimalist approach and bar for something in between. Elpy is like foo in ERC packages.

Thank you for complete explanation.

---

I want to thank you. I use Eply most of the time. It's my only tool for doing python development. Never use anything else for now. I read lot of your article concerning Emacs and community.

Thank you so much for your contribution to community. I hope I can donate to my frequently used packages when I get a job.

Once again thank you for your time for Elpy and other packages.

**Comment by jorgenschaefer** [comment]
Thank you for the very kind words, and I hope you will continue to enjoy Elpy :-)
