### ISSUE TITLE
Wrong type argument: listp, elpy-company-backend

### ISSUE THREAD

**Issue by LuhengStat** [jorgenschaefer/elpy#1371]
# Summary
I am trying to add yasnippet support for elpy-mode-hook, however, 
there has an error with 

Wrong type argument: listp, elpy-company-backend

I am using the code below to set these, and anther two other mode works. 
So I guess maybe its the problem of elpy-company-backend.

```
;; add yasnippet support
(add-hook 'ess-mode-hook
	  (lambda ()
	    (set (make-local-variable 'company-backends)
		 (list
		  (cons 'company-yasnippet
			(car company-backends))))))

(add-hook 'elpy-mode-hook
	  (lambda ()
	    (set (make-local-variable 'company-backends)
		 (list
		  (cons 'company-yasnippet
			(car company-backends))))))

(add-hook 'LaTeX-mode-hook
	  (lambda ()
	    (set (make-local-variable 'company-backends)
		 (list
		  (cons 'company-yasnippet
			(car company-backends))))))
```

**Comment by galaunay** [comment]
I think `company-backends` should be a list, and with `(list (cons ...))` you are creating a cons cell within a list. So `company-backends` ends up being something like that:
```Elisp
((company-yasnippet . company-reftex-citations))
```

When elpy tries to add its backend, `company-backends` become:
```Elisp
(elpy-company-backend (company-yasnippet . company-reftex-citations))
```
Which is not a proper list.

The following hook should work, though:
```Elisp
(add-hook 'elpy-mode-hook
	  (lambda ()
	    (set (make-local-variable 'company-backends)
		  (list 'company-yasnippet
			(car company-backends)))))
```

Note: `(car company-backends)` returns only the first backend, so you lose all the others, is this what you want ?

**Comment by LuhengStat** [comment]
No, I just want to add the company-yasnippet keywords to the original backends. How to set these? Thanks.

**Comment by galaunay** [comment]
Try with this:
```Elisp
(add-hook 'elpy-mode-hook
	  (lambda ()
	    (set (make-local-variable 'company-backends)
		  (cons 'company-yasnippet
			company-backends))))

```

**Comment by LuhengStat** [comment]
sorry, it does not work. Maybe there has something thing wrong with my settings.

**Comment by galaunay** [comment]
What do you mean exactly,
it does not add the backend to the list (what is the value of `company-backends` then ?) or the completion does not happen as you expect ?

**Comment by LuhengStat** [comment]
The code does not work as I expect, The yasnippet backends shows, but others are not. the 
company-backends is (company-yasnippet elpy-company-backend company-bbdb company-nxml company-css company-eclim company-clang company-xcode company-cmake company-files (company-dabbrev-code company-gtags company-etags company-keywords) company-oddmuse ...)

**Comment by galaunay** [comment]
My bad, I pasted the wrong code.
This one will put yasnippet backend at the end of the current backends:
```Elisp
(add-hook 'elpy-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends)
                 (append company-backends '(company-yasnippet)))))

```

So yasnippet will only be called if all the other backends return nothing.

**Comment by LuhengStat** [comment]
Great, it works. Thanks.
