### ISSUE TITLE
No Autocomplete Suggestions With Input Parameter

### ISSUE THREAD

**Issue by kevinjfoley** [jorgenschaefer/elpy#1373]
# Summary

I don't get any suggestions when typing inside of the parameter list of a function which is a parameter of the current function.  Please see example below as I'm sure I'm wording this very poorly.

# Steps to reproduce
Using the following code:
```python
class my_class:
    a = 1
    b = 'b'

def my_function(input_param):
    'Truncates input_text to 5 characters'

    my_class.
    fake_function(my_class.)
    input_param(my_class.)
    input_param.input_param_method(my_class.)
``` 

Calling for autocompletions after `my_class.` works when it's by itself or in the parameter list of a function which isn't an input parameter to `my_function`.  However, I don't get any suggestions when typing in the parameter list of `input_param` which is meant to be a function passed to the function `my_function`.  It also doesn't work when treating `input_param` as a class and calling one of it's methods.

# My configuration
## OS
Mac OS

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.6.5 (/anaconda2/envs/data-modules/bin/python)
Interactive Python: python (/anaconda2/envs/data-modules/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.20.0
Jedi..............: 0.12.0
Rope..............: Not found (0.10.7 available)
Autopep8..........: 1.3.5
Yapf..............: 0.21.0 (0.22.0 available)
Syntax checker....: flake8 (/anaconda2/envs/data-modules/bin/flake8)
```

## Elpy configuration in my init.el
```
(use-package elpy
  :defer t
  :init
  (add-hook 'python-mode-hook #'elpy-mode)
  (setq elpy-rpc-backend "jedi")
  (setq elpy-dedicated-shells nil))
```
(I'm pretty sure setting the backend and dedicated shells are no longer needed/used)

**Comment by kevinjfoley** [comment]
It returns what I would expect for the first two,
```
(((name . "a") (suffix . "a") (annotation . "statement") (meta . "a = 1")) ((name . "b") (suffix . "b") (annotation . "statement") (meta . "b = 'b'")) ((name . "mro") (suffix . "mro") (annotation . "function") (meta . "def mro")) ((name . "__abstractmethods__") (suffix . "__abstractmethods__") (annotation . "instance") (meta . "instance __abstractmethods__")) ((name . "__base__") (suffix . "__base__") (annotation . "class") (meta . "class __base__")) ((name . "__bases__") (suffix . "__bases__") (annotation . "instance") (meta . "instance __bases__")) ((name . "__basicsize__") (suffix . "__basicsize__") (annotation . "instance") (meta . "instance __basicsize__")) ((name . "__call__") (suffix . "__call__") (annotation . "function") (meta . "def __call__")) ((name . "__class__") (suffix . "__class__") (annotation . "class") (meta . "class __class__")) ((name . "__delattr__") (suffix . "__delattr__") (annotation . "function") (meta . "def __delattr__")) ((name . "__dict__") (suffix . "__dict__") (annotation . "instance") (meta . "instance __dict__")) ((name . "__dictoffset__") (suffix . "__dictoffset__") (annotation . "instance") (meta . "instance __dictoffset__")) ...)
```

For the last two, oddly it started working when I placed the cursor after the dot in the third example and `(elpy-rpc-get-completions)` returned what was expected.  However it then didn't work in the fourth example and no longer works on the third example.  Both now return `nil`

**Comment by galaunay** [comment]
This is indeed quite weird.

It is quite complicated to debug elpy rpc without being able to reproduce the issue.


Could you try putting this [script](https://gist.github.com/galaunay/7c4b4b2a33362a30a240e4794ea0b400) alongside the problematic file, and run it ?
it mimics elpy mechanism for getting completion, so it should help us understand what's happening.

You obviously will have to put the right values for `line`, `column` and `filename`.

**Comment by kevinjfoley** [comment]
Tested it with latest Jedi on Github and things seem to work fine.  After installing individual commits it seems this one solves the issue - https://github.com/davidhalter/jedi/commit/fc14aad8f29cbcf61ca33a4eafd032339adec481 

Looking at the diff I'm not really sure how it solves the problem, might be an odd issue on my machine with a file not being found.  Either way looks like the problem wasn't with `elpy`.  Thanks for you help!

**Comment by kevinjfoley** [comment]
> That's very brave of you :).

I was pretty curious what was causing the issue and couldn't figure it out from the commit messages/diffs so I figured testing each commit would work.  I just got lucky it was the first commit after the 0.12.0 release =)
