### ISSUE TITLE
Is `black` autoformatter included?

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#1377]

**Comment by galaunay** [comment]
At the moment, only `yapf` and `autopep8` are supported,
but it should no be too complicated to support black as well.
What do you think black will do better than yapf ?

note: there is this package also [blacken](https://github.com/proofit404/blacken).

**Comment by jorgenschaefer** [comment]
If someone wants to work on adding support for that, works for me, but I don't see it as a particularly high priority. (Always remember, too, that code we add to the repository also needs to be supported in the future=

**Comment by gopar** [comment]
Black is now included
