### ISSUE TITLE
'error in process filter: Overlapping strings detected' error thrown when typing strings

### ISSUE THREAD

**Issue by lgp171188** [jorgenschaefer/elpy#1381]
# Summary
`error in process filter: Overlapping strings detected` error thrown when typing strings on typing either of the quote characters.

The following is the error in the `Messages` buffer
```
error in process filter: elpy-rpc--default-error-callback: Overlapping strings detected
error in process filter: Overlapping strings detected

```
# Steps to reproduce
Type a string by typing either the double quotes or the single quotes character. Emacs freezes and throws the error in the minibuffer repeatedly, thereby making it impossible to type further.

# My configuration
## OS
macOS High Sierra 10.13.4
GNU Emacs 26.1 (Emacs For Mac OS X installed using homebrew)

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........:  (/Users/gnarayan/d/python/mailadm/venv/)
RPC Python........: 3.6.5 (/Users/gnarayan/d/python/mailadm/venv/bin/python)
Interactive Python: python (/Users/gnarayan/d/python/mailadm/venv/bin/python)
Emacs.............: 26.1
Elpy..............: 1.17.0
Jedi..............: 0.12.0
Rope..............: Not found (0.10.7 available)
Autopep8..........: Not found (1.3.5 available)
Yapf..............: Not found (0.22.0 available)
Syntax checker....: flake8 (/Users/gnarayan/d/python/mailadm/venv/bin/flake8)
```

## Elpy configuration in my init.el
```
(use-package elpy
  :pin melpa-stable
  :init
  (elpy-enable)
  :config
  (delete 'elpy-module-highlight-indentation elpy-modules))

```

**Comment by galaunay** [comment]
Thanks for the report.

Could you update to the latest elpy version (1.21.0, even in melpa-stable) and check if it is still happening ?

**Comment by lgp171188** [comment]
@galaunay, I updated to the latest stable elpy version 1.21.0 and no longer see this at this moment. Will reopen this issue if I encounter it again.

**Comment by genovese** [comment]
I continue to see this problem even in 1.24.0. Every time I start a quote (single or triple), there is a tangible hang-time and this error is produced. It is a non-trivial hang time that varies in length but is always a distraction. It is reduced, though still present, if I try to type all the quotes quickly.

My elpy config is below. All the subpackages have been updated quite recently.  

Thanks!

## Elpy Configuration

    Virtualenv........: None
    RPC Python........: 3.7.0 (/usr/local/bin/python3)
    Interactive Python: python3 (/usr/local/bin/python3)
    Emacs.............: 26.1
    Elpy..............: 1.24.0
    Jedi..............: 0.12.1 (0.13.1 available)
    Rope..............: 0.11.0
    Autopep8..........: 1.4
    Yapf..............: 0.23.0 (0.24.0 available)
    Black.............: 18.6b4 (18.9b0 available)
    Syntax checker....: flake8 (/usr/local/bin/flake8)

## Emacs Config

    (use-package elpy
       :config (elpy-enable))

    (with-eval-after-load 'elpy
       (remove-hook 'elpy-modules 'elpy-module-flymake)
       (add-hook 'elpy-mode-hook 'flycheck-mode))

## SystemInfo

Mac OS X 10.12.6
Emacs 26.1

**Comment by dionisos2** [comment]
(same problem with the version 1.25.0)

**Comment by dionisos2** [comment]
Thank for your help @galaunay (and sorry for the late answer)

Your example triggered the error ("Overlapping strings detected"), so I set elpy-eldoc-show-current-function to nil.
(I think it fixed the problem)

**Comment by galaunay** [comment]
Great, 

I think this is the good workaround to use, until the python.el issue is fixed. 

Please re-open if the problem re-appears with the fix.

**Comment by Cerebus** [comment]
Happening again.  Workaround above works.
```
Emacs.............: 26.3
Elpy..............: 1.33.0
Virtualenv........: <elided>
Interactive Python: python 3.7.6 
RPC virtualenv....: rpc-venv 
 Python...........: python3 3.7.6 
 Jedi.............: 0.16.0
 Rope.............: 0.16.0
 Autopep8.........: 1.5
 Yapf.............: 0.29.0
 Black............: 19.10b0
Syntax checker....: flake8 (/usr/local/bin/flake8)
```

**Comment by wenijinew** [comment]
My error message in *Messages* is:
`Error during redisplay: (jit-lock-function 2201) signaled (error "Overlapping strings detected (start=2629, last-end=2631)") [2 times]`
The workaround doesn't work. It seems related with polymode/poly-lock.el
`(jit-lock-register #'font-lock-fontify-region)`
