### ISSUE TITLE
Install package: elpy [No Match]

### ISSUE THREAD

**Issue by chaturv3di** [jorgenschaefer/elpy#1382]
# Summary
Hi,

I've been using elpy regularly on my Ubuntu and Mac laptops. But recently I'm facing this issue when I try to install elpy in a new virtual environment. 

# Steps to reproduce
On my shell:

```shell
$ conda activate <virtualenv>
$ conda install -c conda-forge jedi
$ conda install -c anaconda flake8
$ conda install -c conda-forge autopep8
$ conda install -c conda-forge yapf
```
Then  in Emacs, I execute the following: 
```shell
M-x pyvenv-activate <virtualenv>
M-x package-refresh-contents
```
The first time I did this, I got a warning that the public key has changed. Since this, I get the following warning every time.
![screen shot 2018-05-31 at 11 09 12 am](https://user-images.githubusercontent.com/22843902/40763965-9c44a21e-64c4-11e8-997c-f973e4643fa9.png)
I select `A` for `Always` it the prompt says that package have been refreshed. However, in my `.emacs.d/elpa/` folder, I only see `elpy-1.17.0` even though the most recent one is `1.21.0`. 

Anyway, trying to install `elpy` after all of this gives me the `No match` error.

# My configuration
## OS
macOS High Sierra v10.13.4
conda 4.4.7
Python 3.6.5 | Anaconda, Inc.

## Result of `(elpy-config)`
Not available.

## Elpy configuration in my init.el
```lisp
;; Set correct Python
(setq elpy-rpc-python-command "python")
(setq python-shell-interpreter "python")

;; Correct indentation
(setq-default indent-tabs-mode nil)

(add-hook 'python-mode-hook
	  (lambda ()
	    (setq indent-tabs-mode nil)
	    (setq tab-width 4)
	    (setq python-indent 4)))

(with-eval-after-load 'python
  (defun python-shell-completion-native-try ()
    "Return non-nil if can trigger native completion."
    (let ((python-shell-completion-native-enable t)
          (python-shell-completion-native-output-timeout
           python-shell-completion-native-try-output-timeout))
      (python-shell-completion-native-get-completions
       (get-buffer-process (current-buffer))
       nil "_"))))


;; Obtain Elpy
(require 'package)
(add-to-list 'package-archives
	     '("melpa-stable" . "https://stable.melpa.org/packages/"))

;; For Elpy
(package-initialize)
(elpy-enable)
;;(sentenv "WORKON_HOME" "//anaconda/envs/")
(setq elpy-rpc-backend "jedi")
;;(elpy-clean-modeline)
```

**Comment by chaturv3di** [comment]
I'm sorry! Can I(someone) please delete this issue?

It seems that the problem hiding there in my `init.el` file. All I had to do was to uncomment and set the following env variable

```lisp
(setenv "WORKON_HOME" "//anaconda3/envs/")
```
Everything now works.

**Comment by galaunay** [comment]
Thanks for the corrective :)
don't worry, I will just close this issue.
