### ISSUE TITLE
Emacs prints the entire code after running Python with C-c C-c

### ISSUE THREAD

**Issue by cuspime** [jorgenschaefer/elpy#1390]
Hi,

After resolving so many difficulties in trying to install Python to run with emacs on Windows 10, everytthing is working nicely. However, what is really annoying is that I see the whole Python code printed in the buffer where I'm suppose to see (or where I would like to see) only the output after compiling with C-c C-c. I thought that this would be an easy fix but I haven't found anything about this. Maybe there is a "silent" mode?

My M-x elpy-config reads

Virtualenv........: None
RPC Python........: 3.6.4 (C:/ProgramData/Anaconda3/python.exe)
Interactive Python: C:/ProgramData/Anaconda3/pythonw.exe (C:/ProgramData/Anaconda3/pythonw.exe)
Emacs.............: 25.3.1
Elpy..............: 1.21.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.22.0
Black.............: Not found (18.6b1 available)
Syntax checker....: Not found (flake8)

I'd be grateful to have any help in this matter

<img width="461" alt="untitled" src="https://user-images.githubusercontent.com/20184125/41116417-22c25418-6a82-11e8-9c51-92c3c7b03d25.png">

Thank you for reporting to Elpy !

Here is a template to help you do it so your issue can be fixed as
soon as possible. Please replace this paragraph with a summary of
your issue and fill the next sections.

# Steps to reproduce

# My configuration
## Result of `(elpy-config)`
```
# Paste it here
```

## Elpy configuration in my init.el
```
# Paste it here
```

**Comment by galaunay** [comment]
I think you are looking for the `elpy-shell-echo-*` customisation variables.
There is some information in the [docs](https://elpy.readthedocs.io/en/latest/ide.html#shell-feedback) as well.

I hope it helps.

**Comment by cuspime** [comment]
Hi galunay,
I actually don't have the elpy-shell-echo-* option when I do M-x. 
Is there another way to change this?

**Comment by galaunay** [comment]
`M-x` only shows you available commands (i.e. functions).
`elpy-shell-echo-*` are customizable variables, that you can set in different ways:
- Via elpy configuration panel with`M-x elpy-config`(group `Elpy`, option `elpy-shell-echo-input`)
- Directly by customizing the variable with `M-x customize-variable RET elpy-shell-echo-input`.
- By directly setting the variable when emacs starts, by adding `(setq elpy-shell-echo-input nil)` to your configuration file.

Hope it helps.

**Comment by cuspime** [comment]
That worked like a charm. Thank you so very much!!

**Comment by galaunay** [comment]
You are welcome, 
Enjoy Elpy.

I guess it is safe to close this then.
