### ISSUE TITLE
matplotlib plot not appearing with elpy 1.21.0

### ISSUE THREAD

**Issue by markseeto** [jorgenschaefer/elpy#1394]
# Summary

After upgrading elpy from version 1.17.0 to 1.21.0, matplotlib plots are not appearing. I did not have this problem with elpy 1.17.0. I did not upgrade or install any other packages. 

# Steps to reproduce
I start Python with `M-x run-python`.

```
In [1]: import matplotlib.pyplot as plt

In [2]: plt.plot([1,2,3,4])
Out[2]: [<matplotlib.lines.Line2D at 0xe718ec17b8>]
<Figure size 432x288 with 1 Axes>

In [3]: plt.show()
```
and no plot appears. If I remember correctly, in elpy 1.17.0 the plot appeared without needing to call `plt.show()` (I'm new to elpy and Python so I don't know if this was the expected behaviour).

# My configuration
## OS
GNU Emacs 25.2 on Windows 8.1.

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.6.3 (c:/Windows/py.exe)
Interactive Python: jupyter (c:/Program Files/Python36/Scripts/jupyter.exe)
Emacs.............: 25.2.1
Elpy..............: 1.21.0
Jedi..............: 0.12.0
Rope..............: 0.10.7
Autopep8..........: Not found (1.3.5 available)
Yapf..............: Not found (0.22.0 available)
Syntax checker....: Not found (flake8)

You have not activated a virtual env. While Elpy supports this, it is often a
good idea to work inside a virtual env. You can use M-x pyvenv-activate or M-x
pyvenv-workon to activate a virtual env.

The autopep8 package is not available. Commands using this will not work.

[run] c:/Windows/py.exe -m pip install --user autopep8

The yapf package is not available. Commands using this will not work.

[run] c:/Windows/py.exe -m pip install --user yapf

The configured syntax checker could not be found. Elpy uses this program to
provide syntax checks of your programs, so you might want to install one. Elpy
by default uses flake8.

[run] c:/Windows/py.exe -m pip install --user flake8
```

## Elpy configuration in my init.el
```
(elpy-enable)

(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")

;; Avoid changing M-a and M-e in python mode
(define-key python-mode-map [remap backward-sentence] nil)
(define-key python-mode-map [remap forward-sentence] nil)

```
Thank you.

**Comment by markseeto** [comment]
I found the solution. I needed to run `% matplotlib` first. I don't understand why plots appear without calling `plt.show()`, but it doesn't appear to be a problem.

**Comment by galaunay** [comment]
I think `%matplotlib` activates (among other things) matplotlib interactive mode (that you can also activate with `matplotlib.pyplot.ion()`.
In this mode, matplotlib will show figure as soon as they are created, without the need of using `plt.show()`.

If you don't want plot to appear without calling `plt.show()` you can deactivate matplotlib intearactive mode with `matplotlib.pyplot.ioff()`.

**Comment by markseeto** [comment]
Thank you for your comments galaunay. After `import matplotlib.pyplot as plt`, I tried `plt.ion()` and it didn't have the same effect as `% matplotlib`. That is, if I run `plt.ion()` but not `% matplotlib`, then plots do not appear at all, even after `plt.show()`. But after running `% matplotlib`, you were right that `plt.ioff()` prevents plots from appearing until `plt.show()` is called. And if I run `% matplotlib` then `plt.ioff()` then `plt.ion()`, it goes back to displaying plots without calling `plt.show()`. This is useful to know. Thanks.

**Comment by galaunay** [comment]
You are welcome.

I think `%matplotlib` activates the interactive mode, but also configures properly matplotlib for ipython.
That would explain why `plt.ion()` is not enough for you to get your plots.

**Comment by mahyaret** [comment]
You can also use different back-end:
```
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt 
```
