### ISSUE TITLE
finding wrong python binary with conda

### ISSUE THREAD

**Issue by parsifal9** [jorgenschaefer/elpy#1401]
Hi elpy users, 
# Summary
I am having trouble getting elpy to work with conda.
Python modules that I have installed in the conda virutal env are not found. I think the problem is that the wrong python binary is being picked up.

"M-x elpy-config" shows 
Virtualenv........: None
RPC Python........: 3.6.4 (path/anaconda3/bin/python)
Interactive Python: jupyter (path/anaconda3/bin/jupyter)

which is as expected. "path/anaconda3/bin/" is in my path and contains python 3.6.4

I then start the virtual environment using  "M-x pyvevn-activate" and select the environment "path/anaconda3/envs/placer-env"

"M-! echo $PATH"  indicates that "path/anaconda3/envs/placer-env/bin" is now the first item in my path and "M-x elpy-config" shows I am now finding the python 3.6.5 in the virtual environment placer-env
(output shown below). So all looks as though it is working.

However when I open  a file python and use "C-c C-c" to submit some python code, a *Python* buffer is opened with a message

Jupyter console 5.2.0
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

i.e it is finding the anaconda3/bin/python and not the anaconda3/envs/placer-env/bin/python

This happens whether I 
1) start the conda env and then start emacs -- or start emacs outside the cond env
2) follow the advice of
https://emacs.stackexchange.com/questions/20092/using-conda-environments-in-emacs
and add a path to the .emacs file

The threads 
https://github.com/jorgenschaefer/elpy/issues/1001
https://github.com/jorgenschaefer/elpy/issues/1370
discuss similar issues -- not not quite the same

Bye
R

# My configuration
## OS
Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-06-05

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: placer-env (/home/dun280/local/anaconda3/envs/placer-env)
RPC Python........: 3.6.5 (/home/dun280/local/anaconda3/envs/placer-env/bin/python)
Interactive Python: jupyter (/home/dun280/local/anaconda3/envs/placer-env/bin/jupyter)
Emacs.............: 27.0.50
Elpy..............: 1.21.0
Jedi..............: 0.12.0
Rope..............: Not found (0.10.7 available)
Autopep8..........: Not found (1.3.5 available)
Yapf..............: Not found (0.22.0 available)
Syntax checker....: Not found (flake8)
```

## Elpy configuration in my init.el
```
No init.el file. This is from .emacs 

; set up elpy
(elpy-enable)

(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

(defvar myPackages
  '(better-defaults
    elpy
    flycheck
    material-theme
    py-autopep8)) ;; add the autopep8 package

(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")


(setenv "WORKON_HOME" "/home/dun280/local/anaconda3/envs")
(pyvenv-mode 1)
;; recomended by https://emacs.stackexchange.com/questions/20092/using-conda-environments-in-emacs
```

**Comment by galaunay** [comment]
Thanks for the detailed report.

Could you try using the lower level `(elpy-shell-get-or-create-process)` to create a python shell buffer, and see if the good binaries are used.

If not, could you try the even lower level `(run-python (python-shell-parse-command) nil t)` and see if the problem is still here.

If nothing works, could you post the result printed by this function,  to try to narrow down where the issue is occuring.
```Elisp
(defun elpy-debug ()
  (interactive)
  (message "PATH: %s" (getenv "PATH"))
  (message "python-shell-parse-command: %s" (python-shell-parse-command)))
```

If it shows your PATH and python command are ok, I think this will have to be reported to python.el.

**Comment by parsifal9** [comment]
Hi  galaunay,

Thanks for helping me with this problem.

I tried adding both 
(elpy-shell-get-or-create-process)
and
(run-python (python-shell-parse-command) nil t)
to .emacs and re-started emacs. They both created a *Python* buffer with

```
Jupyter console 5.2.0
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: 
```
and the elpy-debug command returned

```
PATH: /home/dun280/local/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
python-shell-parse-command: jupyter console --simple-prompt
```
so it is finding the 3.6.4 python binary in  ~/local/anaconda3/bin/
But this is expected as I have haven't started the virtual environment.
If I remove the 
(run-python (python-shell-parse-command) nil t)
command from .emacs, restart emacs then  I find

```
M-x elpy-debug
PATH: /home/dun280/local/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
python-shell-parse-command: jupyter console --simple-prompt

M-x pyvend-active
M-x elpy-debug
PATH: /home/dun280/local/anaconda3/envs/placer-env//bin:/home/dun280/local/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
python-shell-parse-command: jupyter console --simple-prompt
```
So "/home/dun280/local/anaconda3/envs/placer-env//bin" is first in the path and 
/home/dun280/local/anaconda3/envs/placer-env//bin/python -V
Python 3.6.5

I then use "C-c C-c" from a ,py file to start the interpreter and this is what appears
```
Jupyter console 5.2.0
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import pandas as pd
In [3]: import fiona, fiona.crs
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c04c0287504e> in <module>()
----> 1 import fiona, fiona.crs
ModuleNotFoundError: No module named 'fiona'
```
By the way, just in case I am misleading you. It is the ModuleNotFoundError that is holding me up.
I am just assuming that if the right binary was found then the installed modules would be found as well.

Bye

**Comment by parsifal9** [comment]
Hi galaunay,

I have been playing around (changing stuff randomly to see what happens)
If I remove
```
 (setq python-shell-interpreter "jupyter"
       python-shell-interpreter-args "console --simple-prompt"
       python-shell-prompt-detect-failure-warning nil)
 (add-to-list 'python-shell-completion-native-disabled-interpreters
              "jupyter")
```
from my .emacs file then restart emacs, "M-x pyvene-activate" and "C-c C-c" from a python file,
I get a message in the Warnings buffer
``` 
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native-enable’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 
```
but I get the right python version and it finds the installed modules
```
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>  >>> <_ast.Expr object at 0x7f58db41c978>
python.el: native completion setup loaded
>>> import pandas as pd
>>> import fiona, fiona.crs
```
Bye

**Comment by galaunay** [comment]
I think you are right, your module is not found because the used python binaries are  the wrong ones.
The warning about readline is not a big issue.

Apparently it is something to do with jupyter.
Are the jupyter binaries installed in your virtualenv ?

Which python version do you get if you call `jupyter console` from the command line with the virtualenv activated ?

**Comment by parsifal9** [comment]
Hi galaunay,

I think the short answer is "the wrong one".
1) yes, the jupyter binaries are installed in the virtualenv
```
tamar: ~/local/anaconda3/envs/placer-env/bin/jupyter --version
4.4.0
```
2) Inside the virtual environment, the right juypter and python are on the path but
"jupyter console" finds the wrong python binary
```
tamar: echo $PATH
/home/dun280/local/anaconda3/bin:/home/dun280/local/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

tamar: source activate placer-env

(placer-env) tamar:  echo $PATH
/home/dun280/local/anaconda3/envs/placer-env/bin:/home/dun280/local/anaconda3/bin:/home/dun280/local/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

(placer-env) tamar: which jupyter
/home/dun280/local/anaconda3/envs/placer-env/bin/jupyter
(placer-env) tamar: jupyter --version
4.4.0

(placer-env) tamar: which python
/home/dun280/local/anaconda3/envs/placer-env/bin/python
(placer-env) tamar: python --version
Python 3.6.5

(placer-env) tamar: jupyter console
Jupyter console 5.2.0
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by galaunay** [comment]
Hi, 

I am afraid this has something to do with Jupyter (or jupyter configuration ?).
I guess you will have to report there.

You should be able to see the path used by jupyter with `jupyter kernelspec list` (from inside your virtualenv).

**Comment by parsifal9** [comment]
Hi galaunay,
I was thinking the same thing, that this is not an elpy or even an emacs problem. However, I now have a much better idea where the problem lies . Thanks for your help.
Bye
