### ISSUE TITLE
backed unexpected error encountered

### ISSUE THREAD

**Issue by zhangda82** [jorgenschaefer/elpy#1409]
# Summary

Thank you for reporting to Elpy !

Here is a template to help you do it so your issue can be fixed as
soon as possible. Please replace this paragraph with a summary of
your issue and fill the next sections.

# Steps to reproduce

# My configuration
## Result of `(elpy-config)`
```
# Paste it here
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.1 (c:/Anaconda3/pythonw.exe)
Interactive Python: ipython (c:/Anaconda3/Scripts/ipython.exe)
Emacs.............: 26.1
Elpy..............: 1.22.0
Jedi..............: 0.12.0 (0.12.1 available)
Rope..............: 0.9.4-1
Autopep8..........: 1.3.5
Yapf..............: 0.20.0 (0.22.0 available)
Black.............: Not found (18.6b4 available)
Syntax checker....: flake8.exe (c:/Anaconda3/Scripts/flake8.exe)

You have not activated a virtual env. While Elpy supports this, it is often a good idea to work inside a virtual
env. You can use M-x pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

There is a newer version of Jedi available.

[run] c:/Anaconda3/pythonw.exe -m pip install --user --upgrade jedi

There is a newer version of the yapf package available.

[run] c:/Anaconda3/pythonw.exe -m pip install --user --upgrade yapf

The black package is not available. Commands using this will not work.

[run] c:/Anaconda3/pythonw.exe -m pip install --user black

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button to invoke its action. Invoke [+] to expand a
group, and [-] to collapse an expanded group. Invoke the [Group], [Face], and [Option] buttons below to edit that
item in another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[+]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[+]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
[+]-- Group Django extension
[+]-- Group Autodoc extension

## Elpy configuration in my init.el
```
# Paste it here
```
(setq elpy-rpc-error-timeout 600000000)
(setq elpy-rpc-timeout 5)
(setq elpy-disable-backend-error-display t)

(defun my-elpy-mode-hook ()
  (highlight-indentation-mode -1)
  (indent-guide-mode 1)
  (auto-complete-mode -1)
  (define-key elpy-mode-map "\C-m" 'newline-and-indent)
  (define-key elpy-mode-map "\C-j" 'electric-indent-just-newline)
  ;; I don't like elpy-nav-backward-indent and elpy-nav-foreward-indent taking my windmove key bindings
  (define-key elpy-mode-map (kbd "<C-left>") 'windmove-left)
  (define-key elpy-mode-map (kbd "<C-right>") 'windmove-right)
  (define-key elpy-mode-map (kbd "<C-up>") 'windmove-up)
  (define-key elpy-mode-map (kbd "<C-down>") 'windmove-down)
  (define-key elpy-mode-map (kbd "<C-.n>") 'elpy-goto-definition-other-window)
  )
(add-hook 'elpy-mode-hook 'my-elpy-mode-hook)
(when (require 'elpy nil t)
  (progn
    (elpy-enable)
))
Elpy Error

The backend encountered an unexpected error. This indicates a bug in Elpy. Please open a bug report with the data
below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

There's an issue (16 != 15) with the diff parser. Please report:
--- 
+++ 
@@ -12,5 +12,4 @@
 import nltk
 
 
-
-+def

Configuration

Virtualenv........: None
RPC Python........: 3.6.1 (c:/Anaconda3/pythonw.exe)
Interactive Python: ipython (c:/Anaconda3/Scripts/ipython.exe)
Emacs.............: 26.1
Elpy..............: 1.22.0
Jedi..............: 0.12.0 (0.12.1 available)
Rope..............: 0.9.4-1
Autopep8..........: 1.3.5
Yapf..............: 0.20.0 (0.22.0 available)
Black.............: Not found (18.6b4 available)
Syntax checker....: flake8.exe (c:/Anaconda3/Scripts/flake8.exe)

Traceback

Traceback (most recent call last):
  File "c:\home\zhangda\.emacs.d\elpa\elpy-20180629.513\elpy\jedibackend.py", line 246, in run_with_debug
    script = jedi.Script(*args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\api\__init__.py", line 119, in __init__
    cache_path=settings.cache_directory
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 383, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "c:\Anaconda3\lib\site-packages\parso\grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "c:\Anaconda3\lib\site-packages\parso\grammar.py", line 126, in _parse
    new_lines=lines
  File "c:\Anaconda3\lib\site-packages\parso\python\diff.py", line 163, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (16 != 15) with the diff parser. Please report:
--- 
+++ 
@@ -12,5 +12,4 @@
 import nltk
 
 
-
-+def

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\home\zhangda\.emacs.d\elpa\elpy-20180629.513\elpy\jedibackend.py", line 279, in run_with_debug
    script = jedi.Script(*args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\api\__init__.py", line 119, in __init__
    cache_path=settings.cache_directory
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 383, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "c:\Anaconda3\lib\site-packages\parso\grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "c:\Anaconda3\lib\site-packages\parso\grammar.py", line 126, in _parse
    new_lines=lines
  File "c:\Anaconda3\lib\site-packages\parso\python\diff.py", line 163, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (16 != 15) with the diff parser. Please report:
--- 
+++ 
@@ -12,5 +12,4 @@
 import nltk
 
 
-
-+def

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
# Filename: tokenize_exam_names.py
"""Summary: tokenize the exam names listed in the input csv file


"""
# Author: Da Zhang, PhD, DABR
# Created: Fri Jul  6 10:57:20 2018
# Last-Updated: Fri Jul  6 11:01:19 2018 (-14400 Eastern Daylight Time)
#      Update #: 1

import csv
import nltk


def'''

script = jedi.Script(source=source, line=15, column=3, path='c:/research/CT_dose_RADSR_mining/dev_proj/CCC_ACR_DIR_mapping/scripts/tokenize_exam_names.py', encoding='utf-8')
script.completions()
```

**Comment by galaunay** [comment]
Similar issue has been reported previously [here](https://github.com/jorgenschaefer/elpy/issues/1405).

It is not a bug in elpy but something wrong happening in jedi.
You should be able to fix this by reinstalling the `parso` library (maybe `jedi` as well) with pip.

**Comment by galaunay** [comment]
@zhangda82 Did a re-installation fixed it ?

**Comment by zhangda82** [comment]
So far I did not see the same error after re-installation. Thanks.
