### ISSUE TITLE
FutureWarning from pycodestyle.py in python 3.7.0 leads to elpy rpc process error

### ISSUE THREAD

**Issue by rpdeo** [jorgenschaefer/elpy#1410]
# Summary

FutureWarning from pycodestyle.py in python 3.7.0 prevents parsing of elpy rpc
process as the warning text from the elpy-rpc-python-command subprocess is
inserted before the JSON leading to an unhandled error condition.

# Steps to reproduce

* create a new virtualenv (I am using virtualenvwrapper)

* open a python source file within emacs (while elpy is configured and
  pyvenv-workon has been set to new virtualenv)

* elpy company completion should be missing due to rpc process not starting.

# My configuration

Python: 3.7.0
Emacs: 26.1
Elpy: 1.22.0

elpy emacs package is from MELPA specifically elpy-20180629.513

## OS

macOS

## Result of `(elpy-config)`

```
Virtualenv........: foo (/Users/user/.virtualenvs/foo)
RPC Python........: /Users/user/.virtualenvs/foo/bin/python
Interactive Python: ipython (/Users/user/.virtualenvs/foo/bin/ipython)
Emacs.............: 26.1
Elpy..............: Not found (Python), 1.22.0 (Emacs Lisp)
Jedi..............: Not found
Rope..............: Not found
Autopep8..........: Not found
Yapf..............: Not found
Black.............: Not found
Syntax checker....: flake8 (/Users/user/.virtualenvs/foo/bin/flake8)

```

After the fix given below, all modules are detected

```
Virtualenv........: foo (/Users/user/.virtualenvs/foo)
RPC Python........: 3.7.0 (/Users/user/.virtualenvs/foo/bin/python)
Interactive Python: ipython (/Users/user/.virtualenvs/foo/bin/ipython)
Emacs.............: 26.1
Elpy..............: 1.22.0
Jedi..............: 0.12.1
Rope..............: 0.10.7
Autopep8..........: 1.3.5
Yapf..............: 0.22.0
Black.............: 18.6b4
Syntax checker....: flake8 (/Users/user/.virtualenvs/foo/bin/flake8)
```

## Elpy configuration in my init.el
```
(require 'elpy)
(elpy-enable)
```

# Possible Fix

In `elpy.el`, line 1030...

```
(call-process elpy-rpc-python-command
              nil
              (current-buffer)
              nil
              "-c"
              elpy-config--get-config)
```

could be changed to,

```
(call-process elpy-rpc-python-command
              nil
              ((current-buffer) nil)
              nil
              "-c"
              elpy-config--get-config)
```

This ignores the STDERR from `elpy-rpc-python-command` allowing detection of
installed modules.

**Comment by galaunay** [comment]
Thanks for the detailed report, really helpful.

I made PR #1411 to fix this.
Instead of discarding all warnings and errors, It will just silence `futurewarnings`, in case other relevant warnings/errors may be raised.

Should be merged in the hour (just the time for the tests to run).

**Comment by rpdeo** [comment]
Thanks for the PR and quick response! 

I was thinking there should be a better way to fix this than throwing away errors and warnings from child processes, but wasn't sure how.
