### ISSUE TITLE
Possible issue in virtualenv handling with Jedi

### ISSUE THREAD

**Issue by rpdeo** [jorgenschaefer/elpy#1413]
# Summary

Hello,

My code completion was not working for packages installed in virtualenv, and I tracked it down to the Jedi sub-process starting a python process that was out of the virtualenv (i.e. using system python2.7 instead of python3.7). You can see the description on Jedi's issue tracker [here](https://github.com/davidhalter/jedi/issues/1177). It may be partly related also to how Elpy passes `VIRTUAL_ENV` environment variable to Jedi. Please have a look at the issue description and advise if this warrants any changes within Elpy also.

# Steps to reproduce

1. Setup a virtualenv with python3.7, install an additional package not in system python e.g. flask
2. Configure Emacs to use latest Elpy from MELPA, my config is given below.
3. Activate virtualenv with `M-x pyvenv-activate / workon`
4. Try to complete 'from flask. ... ', `*Messages*` buffer should have 'user-error: Could not complete.' I think this comes from Company.
5. `M-x list-processes` shows Elpy RPC buffer using `python3` from virtualenv from step 1
6. Execute `ps aux | grep Jedi` in terminal, to see Jedi having launched system python `python2.7` on the virtualenv path `.../site-package/jedi/evaluate/...` sub-process. (I have both python2.7 and 3.7 on the system, virtualenv is python3.7)

Expected result: Jedi should have also launched using virtualenv python3.7.

I added '3.7' to _SUPPORTED_PYTHONS in `jedi/jedi/environment.py` and after that it works as expected. It seems `jedi.Script()` accepts an `environment` keyword which is not being passed in `elpy/jedibackend.py` in Elpy. (But, may be there is some other mechanism at work from your side.)

# My configuration
## OS
macOS

## Result of `(elpy-config)`
```
Virtualenv........: foo (/Users/user/.virtualenvs/foo)
RPC Python........: 3.7.0 (/Users/user/.virtualenvs/foo/bin/python)
Interactive Python: ipython (/Users/user/.virtualenvs/foo/bin/ipython)
Emacs.............: 26.1
Elpy..............: 1.22.0
Jedi..............: 0.12.1
Rope..............: Not found (0.10.7 available)
Autopep8..........: 1.3.5
Yapf..............: 0.22.0
Black.............: 18.6b4
Syntax checker....: flake8 (/Users/user/.virtualenvs/foo/bin/flake8)
```

## Elpy configuration in my init.el
```
(require 'elpy)
(elpy-enable)
```

**Comment by rpdeo** [comment]
I would suggest not making any changes to Elpy immediately. I think Jedi team is working on testing python 3.7 support. Please see [this](https://github.com/davidhalter/jedi/pull/1161) thread.

I noted this issue here to suggest there is a possible stop-gap solution that does not lead to a crippled setup. 

Let me trace this more and report here, if it would be possible to avoid editing the Jedi source file and still make it work with a few configuration changes.

**Comment by galaunay** [comment]
Ok, 
thank you for bringing the information here.
I am staying tuned.
