### ISSUE TITLE
Don't suppress flymake modeline (or make it configurable)

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1422]
Just what the subject states, the flymake modeline in >= 26 is quite pretty and informative, I think it's a mistake to hide it in order to get a lighter modeline. Currently the option is of the all-or-nothing type. One alternative is to always keep flymake, another is to add a new customization option or, simpler, a new state to the current toggle, say:

* nil = not-lighter
* 'medium = activate flymake (and whatever else)
* anything else (including t) = lighter

I don't think anyone in his/her right mind is currently using 'medium instead of t, so this should be backwards compatible.

That said, here is an advice to selectively activate flymake in case somebody is interested in getting this working now:

```elisp
(advice-add 'elpy-modules-remove-modeline-lighter
            :around (lambda (fun &rest args)
                      (unless (eq (car args) 'flymake-mode)
                        (apply fun args))))
```

**Comment by jorgenschaefer** [comment]
I'm fine with just not suppressing the flymake modeline if it's useful.

**Comment by memeplex** [comment]
I've added a customization tip to the wiki https://github.com/jorgenschaefer/elpy/wiki/Customizations#enable-emacs-26-flymake-indicators-in-an-otherwise-light-modeline

**Comment by jorgenschaefer** [comment]
Thank you! I think with support for the new Flymake, making the useful modeline available is a good idea for Elpy, so I'll leave the issue open in case someone wants to adjust Elpy accordingly.

**Comment by galaunay** [comment]
So we just need not to hide flymake for emacs > 26.1 ?
(see associate PR #1438).

**Comment by memeplex** [comment]
One alternative is to keep only the [n m] part of the legend since it's a
lightweight modeline and the colors are distinctive enough. I'm not sure
how difficult that is though.

**Comment by galaunay** [comment]
You are right, 
I am closing this.
