### ISSUE TITLE
In python shell company menu is not shown for one letter identifiers

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1425]
# Summary

Try for example:

```
import tempfile
t = tempfile.TemporaryFile()
t.   # error: nothing happens
t.<tab> # ok: completion-at-point is triggered
tt = t
tt.   # ok: company menu is triggered
```

The same sequence when written in an elpy buffer works fine (although in that case completions are coming from jedi).

**Comment by memeplex** [comment]
Just in case, I tried setting capf as the only company backend but to no avail.

**Comment by memeplex** [comment]
Mmmh, I think it might be because of:

>    A character that is part of a valid candidate never triggers auto-completion.

in `company-auto-complete-chars`, since the candidates returned by python.el include a dot and the minimum prefix is set to 3. One fix for this could be to use the mixed backend (https://github.com/jorgenschaefer/elpy/pull/1403) in both elpy and python shell modes.

**Comment by memeplex** [comment]
For now I fixed this using

```
(add-hook 'inferior-python-mode-hook
          (lambda ()
            (setq-local company-minimum-prefix-length 2)))
```

Maybe you may want to add that to elpy instead of using the new combined backend.

**Comment by galaunay** [comment]
I got auto completion for `t.` with `company-minimum-prefix-length` still being 3.

Is it possible that this issue was already fixed ?
What emacs version are you using ?

**Comment by memeplex** [comment]
Emacs 26. You say you get autocompletion for python **shell**? Because the
problem is only with inferior mode autocompletion, in my case the ones
generated by ipython, which are of the form `t.xxx` so `t.` is considered
part of the prefix and the `.` doesn't get its special meaning as
punctuation AFAICS, so as `len('t.') < 3` autocompletion is not triggered
by company.

**Comment by galaunay** [comment]
I missed the shell thing...
I see what you mean now.

I don't think using the mixed backend in the python shell is a very good idea, as it can offer misleading completions (for variables existing only in the script).

But I guess it would make sense to make your solution part of the company module.
As completion in the shell is quite fast, It seems to be a good default behaviour.

**Comment by galaunay** [comment]
I made a PR for this (#1467).
Should be merged soon.
