### ISSUE TITLE
Full inferior mode input font locking

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1428]
I know this is a comint issue and I've already reported at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32344 (please see details there).

But maybe you're interested in adding this workaround to elpy (perhaps optionally depending on a customization option) in order to get full input font locking, it looks really nice!

```elisp
(advice-add 'comint-send-input
            :around (lambda (f &rest args)
                      (when (eq major-mode 'inferior-python-mode)
                        (cl-letf (((symbol-function 'g)
                                   (symbol-function 'add-text-properties))
                                  ((symbol-function 'add-text-properties)
                                   (lambda (start end properties &optional object)
                                     (unless (eq (nth 3 properties) 'comint-highlight-input)
                                       (g start end properties object)))))
                          (apply f args)))))
```

**Comment by memeplex** [comment]
Here is an improvement on the above code:
1. Uses a safer let binding for g (still safer if you use lexical binding).
2. Also colorizes the input send by elpy from another buffer.

```elisp
(defun elpy-shell--insert-and-font-lock (string face &optional no-font-lock)
  (let ((from-point (point)))
    (insert string)
    (python-shell-font-lock-post-command-hook)))

(advice-add 'comint-send-input
            :around (lambda (f &rest args)
                      (when (eq major-mode 'inferior-python-mode)
                        (cl-letf ((g (symbol-function 'add-text-properties))
                                  ((symbol-function 'add-text-properties)
                                   (lambda (start end properties &optional object)
                                     (unless (eq (nth 3 properties) 'comint-highlight-input)
                                       (funcall g start end properties object)))))
                          (apply f args)))))
```

Notice I had to redefine `elpy-shell--insert-and-font-lock` in order to avoid the standard comint input face and also to call the python font locking hook.

I understand all this is a workaround but the results look really nice! I suggest elpy to implement the above but in a more cleanly fashion:

1. The comint-send-input advice could be kept until the comint maintainers decide to add an option to avoid forced colorization of inputs (or forever if they decide not to do so).

2. Everything should depend on a new customization toggle `elpy-shell-input-font-lock' or whatever. When this toggle is enabled the advice is installed and elpy-shell--insert-and-font-lock calls python-shell-font-lock-post-command-hook, otherwise behavior is as usual.

What do you think?

(And please, give it a try, I believe once you saw the colors in your comint buffer you would want to add this!)

**Comment by memeplex** [comment]
The above was intended to suggest how this could be added as part of elpy. If anyone is wanting to hack his/her config right now, I would recommend to advice elpy-shell--insert-and-font-lock instead of overwriting it:

```elisp
(advice-add 'elpy-shell--insert-and-font-lock
            :around (lambda (f string face &optional no-font-lock)
                      (if (not (eq face 'comint-highlight-input))
                          (funcall f string face no-font-lock)
                        (funcall f string face t)
                        (python-shell-font-lock-post-command-hook))))
```

**Comment by jorgenschaefer** [comment]
Thank you for the suggestion! I like the idea, but I would prefer not having to maintain this code in the future. Having it in comint would be great, in the meantime, having it in the wiki is a good workaround. Thanks again! :-)

**Comment by memeplex** [comment]
@galaunay I'm trying to push the required changes into comint so as we can have full font locking in inferior shell, maybe you could express your interest in that feature in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32344. Thanks, Carlos.

**Comment by galaunay** [comment]
I would ne very pleased for this to be merged as well.
I'll send a message (if it can by of any help).
