### ISSUE TITLE
xref-find-definitions with prefix arguments is too slow

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1436]
# Summary

Sometimes it's useful to go to the definition of an identifier that's not in the current buffer, or at least not below the point, that's what `C-u M-.` is for. But it takes too long for elpy (or python.el, not sure) to build the completion-at-point table for the buffer. I think not providing completions would be ok since dabbrev-expand might be sufficient for completing stuff already in the buffer.

# Steps to reproduce

Open a reasonably complex python file. Press C-u M-.

**Comment by memeplex** [comment]
Indeed.

Btw, another improvement could be to allow for M-. in inferior mode, do you think that's possible within reason?

**Comment by galaunay** [comment]
It is unfortunately difficult.
The reason being it is hard to know for sure what a variable in the shell refers to (in the associated script).

For this minimal script for example:
```Python
a = 34
a = 23
```
It is difficult in the shell to know what was the last evaluated statement, and consequently, to what `a` actually refers to.

I guess something like that may work in most of the cases, but it is far from being bullet-proof.
```Elisp
(defun xref-goto-definition-from-shell ()
  "Goto to the definition at point from the shell."
  (interactive)
  (let ((symbol (symbol-at-point))
        (pos nil)
        (buff nil))
    (save-window-excursion
      (elpy-shell-switch-to-buffer)
      (goto-char (point-max))
      (when (search-backward-regexp (format "\\<%s\\>" symbol) nil t)
        (xref-find-definitions (elpy-xref--identifier-at-point))
        (setq pos (point))
        (setq buff (buffer-name))))
    (if (not (and pos buff))
        (message "No definition found")
      (pop-to-buffer buff)
      (goto-char pos))))
```
