### ISSUE TITLE
test failures: Wrong number of arguments: (2 . 2), 1

### ISSUE THREAD

**Issue by Apteryks** [jorgenschaefer/elpy#1440]
# Summary
The test `elpy-black-fix-code-in-region-should-retain-line-and-column` is failing reproducibly for Elpy 1.23.0, tested with Emacs 26.1.

````
maxim@apteryx /tmp/guix-build-emacs-elpy-1.23.0.drv-0/source [env]$ ert-runner -p  elpy-black-fix-code-in-region-should-retain-line-and-column
Warning: Lisp directory '/tmp/guix-build-ert-runner-0.7.0.drv-0/ert-runner.el-0.7.0': No such file or directory
test/test-helper.el: Pattern t is deprecated.  Use `_' instead
Test elpy-black-fix-code-in-region-should-retain-line-and-column backtrace:



Aborted: Ran 1 test in 0.871 seconds
1 unexpected results:
   FAILED  elpy-black-fix-code-in-region-should-retain-line-and-column
Wrong number of arguments: (2 . 2), 1
maxim@apteryx /tmp/guix-build-emacs-elpy-1.23.0.drv-0/source [env]$ echo $?
255
````

# My configuration
GNU Guix 0.15.0.760-e3fc9
(Emacs 26.1)

**Comment by Apteryks** [comment]
It seems that I get this error (Wrong number of arguments: (2 . 2), 1) for multiple (all?) tests. Maybe something is broken in my environment (looking at ert-runner).

**Comment by Apteryks** [comment]
I've tested a couple versions back to 1.18.0, but couldn't find one without the error. I think I've tested other packages using ert-runner with Emacs 26.1 and it works OK, so it seems there is something broken here.

**Comment by galaunay** [comment]
Travis tests with Emacs 26.1 are passing without issues for Elpy master branch.
I checked on my installation (emacs26.1 and elpy master branch) to be sure, and the tests are passing fine as well.

Did you run the test from a virtualenv initialized with `/script/setup` as recommended in the [doc](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) ?

**Comment by Apteryks** [comment]
I just tried, but it doesn't fix the errors. I'll investigate further and reopen if there is really a problem on Elpy's side! Thank you for the quick reply :)

**Comment by Apteryks** [comment]
For the record, the problem was a missing dependency (python-black) in the Guix emacs-elpy package that I was developing. I was thrown off by the unhelpful error reported by ert-runner ;)

It is now complete and I just pushed into GNU Guix proper, for anyone interested :)

**Comment by jorgenschaefer** [comment]
Thank you for your work! :-)
