### ISSUE TITLE
auto completion does not work for all modules under arch linux if installed with pacman

### ISSUE THREAD

**Issue by akimVattenbonde** [jorgenschaefer/elpy#1447]
# Summary

jedi auto completion not working for all modules

# Steps to reproduce

in elpy, functions from os, sys or shutil are autocompleted, functions from numpy, matplotlib or pandas are not.

# My configuration
## OS
Arch Linux
I installed site packages via pacman, not pip (this is apparently recommended by arch). I think that this is the problem? 
site packages are installed to /usr/lib/python 3.7.0/site-packages
python can be found at /usr/bin/python

everything works fine in terminal. If I get what I read so far, I would need to change my PATH to include the site packages? How can I achieve this?

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.7.0 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 26.1
Elpy..............: 1.19.0
Jedi..............: 0.12.1
Rope..............: Not found (0.11.0 available)
Autopep8..........: 1.3.5
Yapf..............: Not found (0.22.0 available)
Syntax checker....: flake8 (/usr/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables
in that directory, so Emacs won't find them. If you are missing some
commands, do add this directory to your PATH -- and then do
`elpy-rpc-restart'.

The yapf package is not available. Commands using this will not work.

[run] easy_install --user yapf

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button
to invoke its action.  Invoke [+] to expand a group, and [-] to
collapse an expanded group.  Invoke the [Group], [Face], and [Option]
buttons below to edit that item in another window.

```

## Elpy configuration in my init.el
```
(elpy-enable)
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")

;; use flycheck not flymake with elpy
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

;; force jedi
(setq elpy-rpc-backend "jedi")

;; enable autopep8 formatting on save
(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

;; auto-parenthesis
(setq elpy-parentheses-after-callables t)

```

**Comment by galaunay** [comment]
I am using arch as well, I don't think installing packages from pacman is a problem.
But I got the same issue as you do.

This is mainly because jedi does not support python3.7 yet and can't find packages installed in python3.7. It should be supported soon (see discussion [here](https://github.com/davidhalter/jedi/pull/1161#issuecomment-403791593)).

As a temporary workaround, you can install the packages you want completion for in python2.7 (`sudo pip2 install pandas matplotlib numpy`). Jedi should detect them and provide you completion.

(You can also update elpy, the last release is 1.23).

Hope it helps.

**Comment by akimVattenbonde** [comment]
jedi has been updaten to support python 3.7
autocompletion works now!

**Comment by galaunay** [comment]
Finally !
Thanks for the feedback.
