### ISSUE TITLE
flake8 wrapper script is used, rather than python -m flake8

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1452]
# Summary

flake8 wrapper script is used, rather than python -m flake8.  If this is purposeful, then please declare a dependency on the wrapper script somewhere in Elpy's documentation.

# Steps to reproduce

1. Install the the correct flake8 variant for the Python interpreter being used
1. Do not install the package that provides the $PATH/flake8 wrapper script
1. (elpy-enable)
1. (elpy-config)
1. Syntax checker....: Not found

# My configuration
## OS

Debian 9 (stable) and Debian 10 (testing and unstable).  I maintain the Debian package and am manually adding a dependency on the flake8 wrapper script at this time  :-)  Oh, and in the spirit of full reproducibility, I'm QAing the yet-unreleased 1.24.0-1 package available here: https://salsa.debian.org/emacsen-team/elpy

## Result of `(elpy-config)` on Debian 9 (with several packages cherry-picked from Debian 10)
```
Virtualenv........: None
RPC Python........: 3.5.3 (/usr/bin/python3)
Interactive Python: /usr/bin/python3 (/usr/bin/python3)
Emacs.............: 25.1.1
Elpy..............: 1.24.0
Jedi..............: 0.10.0 (0.12.1 available)
Rope..............: Not found (0.11.0 available)
Autopep8..........: 1.3.5 (1.4 available)
Yapf..............: 0.15.1 (0.23.0 available)
Black.............: Not found (18.6b4 available)
Syntax checker....: flake8 (/usr/bin/flake8)
```

## Elpy configuration in my init.el
NA, configured system-wide via the new debian-autoloads.el method with the following content
```
;;;###autoload
(setq elpy-rpc-pythonpath nil
      python-shell-interpreter "/usr/bin/python3"
      python-shell-interpreter-args "-i"
      elpy-rpc-python-command "/usr/bin/python3")
```

Whew, that seems like an overkill report for such a little bug ;-p

Cheers,
Nicholas

**Comment by jorgenschaefer** [comment]
> If this is purposeful, then please declare a dependency on the wrapper script somewhere in Elpy's documentation
I'm confused. Elpy declares a dependency on the pip installation of flake8, which includes the wrapper script. Why would you need a separate dependency declaration?

**Comment by sten0** [comment]
> > If this is purposeful, then please declare a dependency on the wrapper script somewhere in Elpy's documentation
> 
> I'm confused. Elpy declares a dependency on the pip installation of flake8, which includes the wrapper script. Why would you need a separate dependency declaration?

I'm sorry, my fault -- I didn't know that the wrapper script was part of a standard pip installation of flake8.  Closing this issue now!
