### ISSUE TITLE
Feature request: Make key prefix of `elpy-shell-*` commands customizable

### ISSUE THREAD

**Issue by Yevgnen** [jorgenschaefer/elpy#1454]
# Summary

Thank you for reporting to Elpy !

Here is a template to help you do it so your issue can be fixed as
soon as possible. Please replace this paragraph with a summary of
your issue and fill the next sections.

# Steps to reproduce
No

# My configuration
## OS
No

## Result of `(elpy-config)`
No

## Elpy configuration in my init.el
No

Hi, I really like the `elpy-shell-*` command group which has a default prefix <kbd>C-c</kbd> <kbd>C-y</kbd>. Although one can rebind all these commands manually, it would be nice to have this prefix customizable.

Thanks!

**Comment by galaunay** [comment]
Hi, 

Could be a good idea.
Having to rebind every commands can be indeed cumbersome.

I made a PR (#1457) to address that.

**Comment by Yevgnen** [comment]
Thanks for the work!
