### ISSUE TITLE
Easily to get stuck while writing

### ISSUE THREAD

**Issue by LuhengStat** [jorgenschaefer/elpy#1455]
# Summary

I use the elpy package to write python, while I found that 
it is easily to get stuck when I writing some code. For example. 

import numpy as np
import pandas as pd
a = np.array([1, 2, 3])

when I try to write a.max(), it is very easy to get stuck when I type "a.m"
for a long time.

# Steps to reproduce

# My configuration
## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.5 (c:/Users/Anaconda3/pythonw.exe)
Interactive Python: python (c:/Users/Anaconda3/python.exe)
Emacs.............: 26.1
Elpy..............: 1.24.0
Jedi..............: 0.12.1
Rope..............: 0.10.7
Autopep8..........: 1.4
Yapf..............: 0.23.0
Black.............: 18.6b4
Syntax checker....: Not found (flake8)


```

## Elpy configuration in my init.el
```
# Paste it here
```

**Comment by galaunay** [comment]
Is it hanging in the same way if you have an associated python shell running or not ?

What happen if you hit `C-g` when Emacs hangs ? Is Emacs sending any meaningful message ?

**Comment by LuhengStat** [comment]
If I hit C-g, the emacs will get well and the python script can be written in a normal way.

**Comment by galaunay** [comment]
It can be due to PR #1403...
Do you know if it is hanging in the same way if you have an associated python shell running or not ?

**Comment by LuhengStat** [comment]
Yes, I think it is probability due to the company mode or auto complete scheme.  I don't think the python shell is still running since the whole Emacs is get stuck.

**Comment by galaunay** [comment]
Could you activate the debug mode `M-x toggle-debug-on-quit`, hit `C-g` when Emacs is hanging and post the backtrace ?

**Comment by LuhengStat** [comment]
Sorry to reply late. The bug info is below:

```
Debugger entered--returning value: "Back to top level"
  normal-top-level()
```
By the way, I am using windows 7, and I found that this 
problem do not exist in a windows 10 os.

**Comment by galaunay** [comment]
I have no idea what is happening...

If it is windows-related it will be even more complicated to debug.
Have you tried with the latest elpy version ? a feature related to completion have been recently modified.

**Comment by LuhengStat** [comment]
In the new version, the problem has been solved. Thanks.
