### ISSUE TITLE
Character encoding error on non ascii chars, when using black

### ISSUE THREAD

**Issue by TheoAndersen** [jorgenschaefer/elpy#1463]
If i use non-us characters (as the danish æ, ø and å) in a file. Then ```elpy-black-fix-code``` will turn it into another strange char, and continue to expand with strange chars.

Its not an error in black since, it works from the command-line, and another emacs package ```blacken``` can utilize black without this.

**Comment by jorgenschaefer** [comment]
Sounds like an encoding problem? What's the value of `default-process-coding-system` for you?

**Comment by TheoAndersen** [comment]
Its ```(utf-8-dos . utf-8-unix)```

**Comment by jorgenschaefer** [comment]
That does not seem correct to me, really. You are encoding files with CR LF to a process, but decode only LF on receipt? What encoding do you use for your files?

**Comment by galaunay** [comment]
Hopefully fixed. Please re-open if not.
