### ISSUE TITLE
transition to 5 column index and drop support for sphinx < 1.4 ?

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1470]
I'm starting to get tired of ignoring the many lines of `WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', 'elpy-config (command)', 'command-elpy-config', '')]` in Debian's CI output.
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/elpy.html

On 14 Jun 2016 tk0miya wrote "Since Sphinx-1.4, the structure of index has changed to 5 columns based.  This warning means any extensions you use don't support new structure."
sphinx-doc/sphinx/issues/2673

If nobody else wants to read the 5 column spec and make what are probably very easy changes then ping me sometime later.  I've recently been strapped for time, could look into this later...if no one else wants to ;-)  Sphinx-1.4 was released in the spring of 2016 so I don't imagine there will be objections, but if there are, please feel free to object!

**Comment by galaunay** [comment]
PR #1471 should remove your unwanted warnings (without dropping sphinx < 1.4).
It will not take advantage of any new feature though, if you still want to have a look one day :).

**Comment by sten0** [comment]
https://github.com/jorgenschaefer/elpy/pull/1471/commits/397cf3472f6987d2101edbfa1b299ae82f3f854c#diff-913cb8c6318831c66c08cb86941afe88R36

Ah! It makes sense to handle this with a conditional, good call.  Thank you @galaunay :-)
