### ISSUE TITLE
Code completion not working for installed packages

### ISSUE THREAD

**Issue by sawan** [jorgenschaefer/elpy#1474]
# Emacs26, Code completion via (`elpy-company-backend`) is not working.

# Steps to reproduce

1. Create a fresh virtual environment and install _elpy_ + some other packages using ```pip```.
```
pip freeze 

Django==2.1.1
elpy==1.24.0
flake8==3.5.0
jedi==0.12.1
mccabe==0.6.1
parso==0.3.1
pycodestyle==2.3.1
pyflakes==1.6.0
pytz==2018.5
```
2. Activate the virtual env.
3. Create a simple Python code file: ~/test.py
4. Try code completion using a Python system package:
``` from os.path import join```
Completion works.

Output from ```M-x company-diag```:

```
Emacs 26.1 (x86_64-apple-darwin15.6.0) of 2018-06-23 on elcapitan.internal.macports.net
Company 0.9.6

company-backends: (elpy-company-backend company-bbdb company-eclim company-clang company-xcode company-cmake company-files
		      (company-dabbrev-code company-gtags company-etags company-keywords)
		      company-oddmuse company-dabbrev)

Used backend: elpy-company-backend
Major mode: python-mode
Prefix: #("join" 0 4
  (fontified t))

Completions:
  "join" "function"
```

5. Try code completion using an installed package:
``` from django.db import Mo ```
**Completion not working** at the ```.``` after ```django``` or even after the ```import```.

6. Try completion using ```elpy-company-backend```; still does not work.
Output from ```M-x company-diag```:

```
Emacs 26.1 (x86_64-apple-darwin15.6.0) of 2018-06-23 on elcapitan.internal.macports.net
Company 0.9.6

company-backends: (elpy-company-backend company-bbdb company-eclim company-clang company-xcode company-cmake company-files
		      (company-dabbrev-code company-gtags company-etags company-keywords)
		      company-oddmuse company-dabbrev)

Used backend: elpy-company-backend
Major mode: python-mode
Prefix: ("" . t)

Completions: none
```

# My configuration
## Result of `(elpy-config)`
```
Virtualenv........:  (/Users/sawanvithlani/src/virtual-envs/fresh-env/)
RPC Python........: 3.7.0 (/Users/sawanvithlani/src/virtual-envs/fresh-env/bin/python)
Interactive Python: python (/Users/sawanvithlani/src/virtual-envs/fresh-env/bin/python)
Emacs.............: 26.1
Elpy..............: 1.24.0
Jedi..............: 0.12.1
Rope..............: Not found (0.11.0 available)
Autopep8..........: Not found (1.4 available)
Yapf..............: Not found (0.24.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/Users/sawanvithlani/src/virtual-envs/fresh-env/bin/flake8)
```

```company-mode``` is enabled globally.
```elpy-rpc-backend``` is ```"jedi"```.

**Comment by galaunay** [comment]
Thanks for the detailed report, really helps.

I followed your steps, but wasn't able to reproduce your issue, I got completion for django.db.

Could you try to run the following python script (to run from within your virtualenv, preferably directly from a terminal):
```Python
import jedi

# Working
source = "from os.path import j"
script = jedi.Script(source=source, line=1, column=21)
candidates = script.completions()
print([cand.name for cand in candidates])


# Non-working ?
source = "from django.db import mo"
script = jedi.Script(source=source, line=1, column=24)
candidates = script.completions()
print([cand.name for cand in candidates])
```
It will help determine if the problem comes from Elpy or Jedi: 
If it does not prints completion candidates for django, you will have to report directly upstream to jedi.
Else, we can investigate further what Elpy does wrong.

ps: `elpy-rpc-backend` option has been removed, as rope is not supported anymore for static code analysis.

**Comment by sawan** [comment]
Hi,

Output is below:

```
(fresh-env)  [Mon Oct 01 15:45:49]  [sawanvithlani@Sawan-Vithlanis-MacBook] in: [ ~/.emacs.d ] 
 $ python
Python 3.7.0 (default, Jun 28 2018, 06:01:52) 
[Clang 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jedi
>>> 
>>> # Working
... source = "from os.path import j"
>>> script = jedi.Script(source=source, line=1, column=21)
>>> candidates = script.completions()
>>> print([cand.name for cand in candidates])
['join']
>>> 
>>> 
>>> # Non-working ?
... source = "from django.db import mo"
>>> script = jedi.Script(source=source, line=1, column=24)
>>> candidates = script.completions()
>>> print([cand.name for cand in candidates])
[]
```

**Comment by galaunay** [comment]
As I was afraid, it seems to be a problem with Jedi not finding the packages installed in your virtualenv.

I suggest to report this issue to [jedi](https://github.com/davidhalter/jedi/issues) directly.
If you give them your virtualenv setup and the result from the above script, they should be able to help.

**Comment by sawan** [comment]
> As I was afraid, it seems to be a problem with Jedi not finding the packages installed in your virtualenv.
> 
> I suggest to report this issue to [jedi](https://github.com/davidhalter/jedi/issues) directly.
> If you give them your virtualenv setup and the result from the above script, they should be able to help.

@galaunay So, I have reported the issue upstream and got the following reply:

https://github.com/davidhalter/jedi/pull/1161#issuecomment-426851302

I will be upgrading to ```jedi 0.13``` and checking again.

**Comment by galaunay** [comment]
If it does not work, I can check for an eventual problem of Environment (as pointed out by David Hatler).

**Comment by sawan** [comment]
@galaunay 
Upgrading to ```jedi 0.13``` seems to have fixed the problem!

**Comment by galaunay** [comment]
Great !
Thanks for the feedback.
