### ISSUE TITLE
Xref backend fails when called without line number in identifier string

### ISSUE THREAD

**Issue by duncanfrost** [jorgenschaefer/elpy#1483]
# Summary
Apologies in advance if this is the fault of other libraries. I'm an evil-user and use `evil-goto-definition` when finding symbol definitions in my projects. This tries a number of methods but eventually runs `xref-find-definitions` which uses the elpy backend when in python mode. From what I can tell calling `xref-find-definitions` interactively results in an identifier argument that includes a line number and a symbol. When called non-interactively as is the case with evil, only the symbol of interest is used as an argument. This results in `elpy-xref--identifier-line` failing.

I use xref with other languages (mainly c++ with lsp-mode) and `xref-find-definitions` works without the line number in its argument. 

# Steps to reproduce
Call `(xref-find-definitions identifier)` with an identifier string that **isn't** of the form "line number: symbol" but only "symbol" while in python-mode,

Alternatively, install evil mode and use "gd" to attempt to call `evil-goto-definition` over a symbol in python mode.

# My configuration
## OS
Antergos/Ubuntu

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.7.0 (/usr/sbin/python3)
Interactive Python: ipython (/usr/sbin/ipython)
Emacs.............: 26.0.50
Elpy..............: 1.25.0
Jedi..............: 0.12.1 (0.13.1 available)
Rope..............: Not found (0.11.0 available)
Autopep8..........: Not found (1.4 available)
Yapf..............: Not found (0.24.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/usr/sbin/flake8)
```

## Elpy configuration in my init.el
```
(setq elpy-modules (delete 'elpy-module-highlight-indentation elpy-modules))
(setq elpy-rpc-python-command "python3")
(setq python-shell-interpreter "ipython")
(setq elpy-rpc-backend "jedi")
```

**Comment by galaunay** [comment]
Thanks for the report, 

In my understanding of xref, `xref-find-definitions` should take an identifier as argument.
This identifier has to be a string, but can be different than the symbol at point.
The way to get an identifier is through the function `xref-backend-identifier-at-point`.

The good way to call `xref-find-definitions` would then be the following:
```Elisp
(xref-find-definitions (xref-backend-identifier-at-point (xref-find-backend)))
```
instead of:
```Elisp
(xref-find-definitions (symbol-at-point))
```

Here the relevant part of the xref doc:
```
;; This file provides a somewhat generic infrastructure for cross
;; referencing commands, in particular "find-definition".
;;
;; Some part of the functionality must be implemented in a language
;; dependent way and that's done by defining an xref backend.
;;
;; That consists of a constructor function, which should return a
;; backend value, and a set of implementations for the generic
;; functions:
;;
;; `xref-backend-identifier-at-point',
;; `xref-backend-identifier-completion-table',
;; `xref-backend-definitions', `xref-backend-references',
;; `xref-backend-apropos', which see.
[...]
;; Each identifier must be represented as a string.  Implementers can
;; use string properties to store additional information about the
;; identifier, but they should keep in mind that values returned from
;; `xref-backend-identifier-completion-table' should still be
;; distinct, because the user can't see the properties when making the
;; choice.
```

So either I misunderstood the xref operation, or the implementation of `evil-goto-definition` is a bit dodgy. I'll make a PR at evil with the correction, if I am wrong, they will let me know.

**Comment by duncanfrost** [comment]
Thanks @galaunay, those changes certainly have fixed things so I can only assume evil is at fault. Closing.
