### ISSUE TITLE
Elpy turns on a Virtual Env menu for all types of files

### ISSUE THREAD

**Issue by smaret** [jorgenschaefer/elpy#1484]
# Summary

Activating Elpy my `.emacs` file turns on a Virtual Env menu, regardless of the type of file I'm editing. This menu make sense only for Python files, so it should be turned off when other types of files are edited.

# Steps to reproduce

`M-x elpy-mode`

![capture d ecran 2018-10-18 a 14 58 28](https://user-images.githubusercontent.com/95471/47155994-609ccd00-d2e6-11e8-9301-4fae7b94fc91.png)

# My configuration

## OS

macos 10.14

## Result of `(elpy-config)`

```
Virtualenv........: None
RPC Python........: 3.6.6 (/Users/smaret/.nix-profile/bin/python3)
Interactive Python: python3 (/Users/smaret/.nix-profile/bin/python3)
Emacs.............: 26.1
Elpy..............: 1.25.0
Jedi..............: 0.12.1
Rope..............: 0.11.0
Autopep8..........: 1.3.5
Yapf..............: 0.24.0
Black.............: 18.9b0
Syntax checker....: flake8 (/Users/smaret/.nix-profile/bin/flake8)
```

## Elpy configuration in my init.el
```elisp
(use-package elpy
  :ensure t
  :config
  (elpy-enable)
  (when (require 'flycheck nil t) ; use flycheck
    (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
    (add-hook 'elpy-mode-hook 'flycheck-mode))
  (setq elpy-rpc-python-command "python3"))
```

**Comment by jorgenschaefer** [comment]
This is intentional, as this menu makes sense for all files – activating a virtualenv is a global setting affecting `exec-path` everywhere. That's just how virtualenvs work.
