### ISSUE TITLE
Feature request: working with super class methods

### ISSUE THREAD

**Issue by Yevgnen** [jorgenschaefer/elpy#1486]
# Summary

Thank you for reporting to Elpy !

Here is a template to help you do it so your issue can be fixed as
soon as possible. Please replace this paragraph with a summary of
your issue and fill the next sections.

# Steps to reproduce
No

# My configuration
## OS
No

## Result of `(elpy-config)`
No

## Elpy configuration in my init.el
No

It's quite often that I want to implement some (abstract) method of parent class in Python. Mainly two scenarios:

1. Implementing all abstract methods/classmethod/etc. marked by `abc.abstractmethod/...`of parent class.
2. Implementing method of parent class that's not marked by `abc.abstractmethod/...`

For 1 I wonder if it is possible for `elpy` to insert all there methods with empty body (like `pass`) into a Python.

For 2 I'd like to have a completion list for choosing parent methods and insert the function signature with empty body, since copying or typing the signature of parent method is quite tedious...

There may be more scenarios when working with parent class methods. Discussions are welcome.

Thanks!

**Comment by galaunay** [comment]
Elpy does not provide those functionalities at the moment.

Jedi can be used to retrieve the list of methods defined in the parent abstract class.
But to my knowledge, Jedi does allow to separate classical methods and abstract ones.

What could be done relatively easily is a function that will ask for one of the parent abstract class method with completion and insert it with an empty body.
It will cover your point 2, and still speed up inserting the abstract classes.
