### ISSUE TITLE
full function signature for auto-complete suggestions

### ISSUE THREAD

**Issue by mdk2029** [jorgenschaefer/elpy#1489]
# Summary

completion information displays only function names but not complete signature
Is it expected to be able to see more information about the function other than just the name?

# Steps to reproduce

Please see attached screenshot.  autocomplete shows appropriate functions correctly. But the mini-buffer has no additional information. From what I see when googling etc, other people seem to have information in the mini-buffer that shows the full signature of the candidate function from the auto-complete list

![screenshot_20181031_103506](https://user-images.githubusercontent.com/9317893/47761150-ac923d80-dcfa-11e8-9471-f6bce880743d.png)
# My configuration
## OS
ubuntu 17.10
emacs 25.2.2

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.3 (/usr/bin/python3)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 25.2.2
Elpy..............: 1.25.0
Jedi..............: 0.13.1
Rope..............: Not found (0.11.0 available)
Autopep8..........: 1.4.2
Yapf..............: 0.24.0
Black.............: 18.9b0
Syntax checker....: flake8 (/home/mk/.local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

```

## Elpy configuration in my init.el
```
(use-package elpy
  :ensure t
  )
(when (require 'elpy nil t)
  (elpy-enable))

;; same behavior if I remove the following three lines
(defun my/python-mode-hook ()
  (set (make-local-variable 'company-backends) '(company-jedi)))    
(add-hook 'python-mode-hook 'my/python-mode-hook)


```

**Comment by galaunay** [comment]
At the moment, Elpy provides:
- The full function signature in the minibuffer when the cursor is in the function arguments: 
``` Python
a.append(  # <- cursor here)
- Function documentation when hitting `C-d` during completion (like in your example).

So no full additional information in the minibuffer is expected during completion.
It is doable, I just wonder if it will be too slow to be useful...

**Comment by mdk2029** [comment]
Thanks for your reply!

Yes, both the things you mention - they work for me. Was just wondering if I am getting the full expected functionality or not. 

I have read through the elpy.readthedocs.io and have a few general questions to better understand what is happening, not sure where to ask since this is not really an issue, but anyways:

-  The documentation says that elpy uses `jedi` (the python module) for the IDE like features. It also says that it uses company mode for the completion features. Just wondering what, if any, role does  `company-jedi.el` have? If I do not have `company-jedi` as one of the `company-backends`, elpy still seems to work correctly. So do I need `company-jedi` or does elpy have its own built-in company backend? 

-  When I look at `python-check-command` var, it says `pyflakes`. Is elpy using pyflakes or flake8 (my understanding is that flake8 is pyflakes + pep8) for syntax checking?

Thank you.

**Comment by gopar** [comment]
@mdk2029 
Hey!

You can achieve something similar with [company-quickhelp](https://github.com/expez/company-quickhelp)

This is what I have in my config:
```
(require 'company-quickhelp)
(company-quickhelp-mode 1)
```

<img width="656" alt="screen shot 2018-10-31 at 4 35 31 pm" src="https://user-images.githubusercontent.com/1545083/47824644-0dd20500-dd2b-11e8-893e-a4b8f4e45be5.png">

**Comment by mdk2029** [comment]
Cool, thanks!

**Comment by galaunay** [comment]
Asking question here is perfectly fine, no problem.
We also have an IRC channel on freenode.
I try to be connected as much as possible, but there is no certitude you will get an answer there :).

Regarding your first point: Elpy and `company-jedi.el` provide the same functionality, which is offering jedi completion candidates through company.
So basically if you have both Elpy and `company-jedi.el` enabled, you may be doing the work twice.

Regarding your second point, Elpy overrides `python-check-command` locally for python buffers (you can check the value of `python-check-command` from within a python buffer).
And you are right, flake8 is indeed pyflake + pep8 styling.
