### ISSUE TITLE
How to configure the formatter used on 'C-c C-r f'?

### ISSUE THREAD

**Issue by SergiyKolesnikov** [jorgenschaefer/elpy#1490]
I have two code formatters installed: autopep8 and yapf. When I press 'C-c C-r f' (format code) yapf is used. Is there a way to configure elpy to use autopep8 on 'C-c C-r f' (without removing yapf)?

**Comment by gopar** [comment]
You can achieve what you want by doing the following:

```
(define-key elpy-refactor-map (kbd "f") 'elpy-autopep8-fix-code)
```

The default of what is happening is that when you call `C-c C-r f`, elpy has a switch statement which checks which checker is available. Whatever checker elpy finds first, is the one it ends up using that.
From the looks of it, `yapf` is the first checker that is checked.

**Comment by azzamsa** [comment]
@gopar any equvalent code for yapf, To ensure that Elpy use yapf ?

**Comment by azzamsa** [comment]
Found it, sorry I think something wrong with my company-mode. I have to look it manually

``` elisp
(:map elpy-refactor-map
               ("f" . elpy-yapf-fix-code)))
```
