### ISSUE TITLE
elpy-check function does not respect arguments to flake8 I have set

### ISSUE THREAD

**Issue by saltycraig** [jorgenschaefer/elpy#1493]
# Summary
Might be related to #1215 

elpy-check function seems to ignore the extra arguments I have set on the python-check-command variable, and instead just runs plain "flake8 {file}". Running python-check without elpy-mode on works
as I desire, reading my arguments to python-check-command.

# Steps to reproduce
With elpy off and flymake off, I have python-check-command set to:

(From *scratch* buffer)
```
python-check-command
"c:/Users/cmaceachern/Envs/git-bash-pyqt/Scripts/flake8.exe --config=c:/Users/cmaceachern/.config/flake8 "
```

In the flake8 config file, I have ignore E501 (line over 79 characters). If I open a python buffer without elpy-mode or flymake-mode on, and manually run M-x python-check I get:

```
c:/Users/cmaceachern/Envs/git-bash-pyqt/Scripts/flake8.exe --config=c:/Users/cmaceachern/.config/flake8  "main.py"
main.py:2:1: F401 'os' imported but unused
main.py:7:1: F401 'PyQt5.QtCore' imported but unused
main.py:8:1: F401 'PyQt5.QtCore.QUrl' imported but unused
main.py:9:1: F401 'PyQt5.QtWidgets.QApplication' imported but unused
```

Which is what I expected. Now I turn of Flymake using M-x flymake-mode and browse around the buffer a bit and insert a couple newlines to trigger flymake check, same results as running python-check, so all good so far everything working as intended.

Now turn on elpy-mode with M-x elpy-mode.

Immediately, I see that Flymake is visually noting (using '!!' in gutter) lines over 79 chars. I try
running M-x python-check again, works as intended, giving same results:

```
c:/Users/cmaceachern/Envs/git-bash-pyqt/Scripts/flake8.exe --config=c:/Users/cmaceachern/.config/flake8  "main.py"
main.py:2:1: F401 'os' imported but unused
main.py:7:1: F401 'PyQt5.QtCore' imported but unused
main.py:8:1: F401 'PyQt5.QtCore.QUrl' imported but unused
main.py:9:1: F401 'PyQt5.QtWidgets.QApplication' imported but unused
```

For some reason though, the flymake integration is no longer honoring my flake8 config now (with elpy-mode on). 

Now I run M-x elpy-check and get the following results:

```
flake8 "c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py"
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:2:1: F401 'os' imported but unused
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:7:1: F401 'PyQt5.QtCore' imported but unused
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:8:1: F401 'PyQt5.QtCore.QUrl' imported but unused
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:9:1: F401 'PyQt5.QtWidgets.QApplication' imported but unused
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:24:80: E501 line too long (88 > 79 characters)
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:25:80: E501 line too long (88 > 79 characters)
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:31:80: E501 line too long (82 > 79 characters)
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:36:80: E501 line too long (85 > 79 characters)
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:42:80: E501 line too long (82 > 79 characters)
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:45:80: E501 line too long (80 > 79 characters)
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:101:80: E501 line too long (85 > 79 characters)
c:/Users/cmaceachern/projects/openroll-qt/src/main/python/openroll/main.py:103:80: E501 line too long (96 > 79 characters)
...(snipped for length)...
```

Investigating, I look up elpy-check function docs, which says that it runs 'python-check-command' on current buffer, so I check 'python-check-command' value but clicking on it in the help window:

```
python-check-command is a variable defined in ‘python.el’.
Its value is
"c:/Users/cmaceachern/Envs/git-bash-pyqt/Scripts/flake8.exe --config=c:/Users/cmaceachern/.config/flake8 "
Original value was 
"c:/Users/cmaceachern/Envs/git-bash-pyqt/Scripts/pyflakes.exe"
```

It seems to me at this point that 'elpy-check' is not honouring 'python-check-command' value when you call 'elpy-check', and simply calling 'flake8 {buffername}' instead, as evidenced above. I'm not sure how to fix that, my elisp is not that good yet, so I'll leave it up to someone else to help me, please!

# My configuration
## OS
Windows 7 64-bit

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: git-bash-pyqt (c:/Users/cmaceachern/Envs/git-bash-pyqt)
RPC Python........: 3.5.4 (c:/Windows/py.exe)
Interactive Python: python (c:/Users/cmaceachern/Envs/git-bash-pyqt/Scripts/python.exe)
Emacs.............: 26.1
Elpy..............: 1.26.0
Jedi..............: 0.13.1
Rope..............: Not found (0.11.0 available)
Autopep8..........: 1.4.2
Yapf..............: Not found (0.24.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8.exe (c:/Users/cmaceachern/Envs/git-bash-pyqt/Scripts/flake8.exe)
```

## Elpy configuration in my init.el
```
None, manually toggling elpy-mode
```

**Comment by saltycraig** [comment]
For now I believe I've fixed it by setting 'elpy-syntax-check-command' variable to value of 'python-syntax-command':

``` elisp
(setq elpy-syntax-check-command python-check-command)
```

Either put that in your init or evaluate it and restart elpy-mode and you will now get a flake8 command via 'elpy-check' function that respects your arguments and config file. It does seem to break Flymake, as it now can't find a proper backend. More digging required, will post updates if I find them.

**Comment by saltycraig** [comment]
Fix for flymake integration:

```elisp
(setq python-flymake-command '("c:/path/to/your/flake8" "--config=/path/to/your/.config/flake8" "-"))
```

My fixes, all together:

```
(setq python-flymake-command '("/path/to/desired/binary/of/flake8" "--config=/path/to/.config/flake8" "-"))
(setq python-check-command "/path/to/desired/binary/flake8 --config=/path/to/.config/flake8 ")
(setq elpy-syntax-check-command python-check-command)
```

Working for me on Windows 7 Emacs 26.1 with Python 3.5.4 and Elpy 1.26.

**Comment by galaunay** [comment]
Thanks for the investigation and the feedback !

Elpy overwrites `python-check-command` with the content of `elpy-syntax-check-command` locally on each python buffers. Which explain your first issue I think.

So instead of:
```Elisp
(setq python-check-command "/path/to/desired/binary/flake8 --config=/path/to/.config/flake8 ")
(setq elpy-syntax-check-command python-check-command)
```
it should be enough to use:
```Elisp
(setq elpy-syntax-check-command "/path/to/desired/binary/flake8 --config=/path/to/.config/flake8")
```

Regarding the fact that it breaks flymake, this is a proper bug. But I know where it comes from and I should be able to fix it in the following days.

**Comment by galaunay** [comment]
I (Finally) made a PR to fix this.

As soon as it is merged, It should be safe to replace  those lines:
```Elisp
(setq python-flymake-command '("/path/to/desired/binary/of/flake8" "--config=/path/to/.config/flake8" "-"))
(setq python-check-command "/path/to/desired/binary/flake8 --config=/path/to/.config/flake8 ")
(setq elpy-syntax-check-command python-check-command)
```
By a simple:
```Elisp
(setq elpy-syntax-check-command "/path/to/desired/binary/flake8 --config=/path/to/.config/flake8")
```

Please tell me if it is not the case.

**Comment by JulienPalard** [comment]
Looks like I have your patch in my elpy.el, still I can't passe parameters via `elpy-syntax-check-command`, what's I tried:
```
(custom-set-variables
 '(elpy-syntax-check-command "pycheckers -c flake8,mypy"))
```

I straced emacs and spotted that pycheckers is started with no parameters:
```
2322  execve("/home/mdk/.venvs/pycheckers/bin/pycheckers", ["/home/mdk/.venvs/pycheckers/bin/pycheckers"], 0x7ffe98b6c4f0 /* 60 vars */ <unfinished ...>
```

**Comment by galaunay** [comment]
Is `python-flymake-command` properly defined in your python buffer (it is buffer-local) ?
It should look like something like that:
``` elisp
("pycheckers" "-c" "flake8,mypy")
```

**Comment by JulienPalard** [comment]
OK so today it works and I can't tell what changed:

Using `strace -s 999 -f -o emacs.strace emacs foo.py`, `M-x describe-variable python-flymake-command` gives:
```
python-flymake-command is a variable defined in ‘python.el’.
Its value is ("pycheckers" "-c" "flake8,mypy")
Original value was ("pyflakes")
Local in buffer __init__.py; global value is ("pyflakes")
```
gives:
```
10323 execve("/home/mdk/.venvs/flask/bin/pycheckers", ["/home/mdk/.venvs/flask/bin/pycheckers", "-c", "flake8,mypy"], 0x7fffaaf08460 /* 60 vars */ <unfinished ...>
```

It also means that this issue can probably be closed, as it looks to work :)

Thanks @galaunay!

**Comment by galaunay** [comment]
I do love issues that solves themselves :).

I close this for now, please re-open if the issue come back.
