### ISSUE TITLE
Installed python modules are not found

### ISSUE THREAD

**Issue by nitroschock** [jorgenschaefer/elpy#1497]
Hi Jorgen,

Elpy does not detect most of the python modules it is supposed to support. Among these modules
are jedi, rope, autopep8, yapf and black. Though, I installed all these modules via pip in a virtual environment, the Elpy-Config buffer says "Not found" for all of them. Only flake8 is found.
The exec-path variable is correct, hence it contains the path to the bin folder of my virtual environment.
What could gone possibly wrong?

# Steps to reproduce

# My configuration
Ubuntu 16.04
Emacs 26.1

## Result of `(elpy-config)
Elpy Configuration

Virtualenv........:  (/media/zufall/inter/Python/Python-Spielplatz/env/)
RPC Python........: 3.5.2 (/media/zufall/inter/Python/Python-Spielplatz/env/bin/python)
Interactive Python: ipython (/media/zufall/inter/Python/Python-Spielplatz/env/bin/ipython)
Emacs.............: 26.1
Elpy..............: 1.26.0
Jedi..............: Not found (0.13.1 available)
Rope..............: Not found (0.11.0 available)
Autopep8..........: Not found (1.4.3 available)
Yapf..............: Not found (0.24.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/media/zufall/inter/Python/Python-Spielplatz/env/bin/flake8)

....

## Elpy configuration in my init.el

.....

(defvar pyPackages
  '(elpy
    flycheck
    ein
    pylint
    py-autopep8))

(mapc #'(lambda (package)
    (unless (package-installed-p package)
      (package-install package)))
      pyPackages)

(elpy-enable)

(with-eval-after-load 'elpy (remove-hook 'elpy-modules 'elpy-module-flymake)
		      (add-hook 'elpy-mode-hook 'flycheck-mode))

(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")

....

**Comment by gopar** [comment]
Where does `pip` point to? If you used `pip install xxx` then they must of been installed somewhere. Perhaps `pip` was pointing to another environment?

**Comment by nitroschock** [comment]
Hi gopar,

I solved the problem. It seems the reason was that the modules I have installed were of a different python version than pip. pip has been 3.5 and the modules were 3.6. I'm still confused though, because I don't know why different python versions have been mixed up. Anyway, I set up a new virtual environment and now it works.
