### ISSUE TITLE
Documentation of elpy-use-ipython, elpy-use-cpython out of date

### ISSUE THREAD

**Issue by rpgoldman** [jorgenschaefer/elpy#1498]
# Summary

The elpy documentation in https://github.com/jorgenschaefer/elpy/blob/master/docs/ide.rst still mentions `elpy-use-ipython` and `elpy-use-cpython`.  But these commands are both deprecated in the source code.

I think those two paragraphs should just be deleted.

**Comment by jorgenschaefer** [comment]
Sounds about right.

**Comment by rpgoldman** [comment]
OK, see #1501 -- I hope that helps.
