### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by zhangda82** [jorgenschaefer/elpy#1499]
# Summary

Thank you for reporting to Elpy !

Here is a template to help you do it so your issue can be fixed as
soon as possible. Please replace this paragraph with a summary of
your issue and fill the next sections.

# Steps to reproduce

# My configuration
## Result of `(elpy-config)`
```
# Paste it here
```

## Elpy configuration in my init.el
```
# Paste it here
```

**Comment by jorgenschaefer** [comment]
I think this was an error? Please feel free to report a new issue with actual content if there's anything :-)
