### ISSUE TITLE
A simple question: How to disable (elpy-nav-backward-indent)

### ISSUE THREAD

**Issue by alucardkoten** [jorgenschaefer/elpy#1510]
I want to keep C-left and C-right as "moving backward and forward a word." So can I change the key bindings or disable it?

**Comment by galaunay** [comment]
```Elisp
(define-key elpy-mode-map (kbd "<C-left>") nil)
(define-key elpy-mode-map (kbd "<C-right>") nil)
```
should do.

It removes Elpy's keybinding for these key combinations.

**Comment by galaunay** [comment]
I will assume that this can be closed.
Please re-open if you have any other question on the subject.
