### ISSUE TITLE
Show PEP8 errors in fringe

### ISSUE THREAD

**Issue by azzamsa** [jorgenschaefer/elpy#1512]
# Summary

Elpy shows PEP8 errors in Emacs fringe 3 months ago. But I don't know what happened. Now I can't get those PEP8 warning in my fringe. I have reverted my elpy configuration. But nothing works.

NOTE : I disabled Flymake and use flycheck instead. But even I restored everything to default. I can't get what I want.

```
  (when (require 'flycheck nil t)
    (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
    (add-hook 'elpy-mode-hook 'flycheck-mode))

```

I tried using hardcode "(setq python-check-command "flake8")", nothing works.
But using `C-c C-v` I can get the result what I want.

```
main_controller.py:4:1: F401 'pathlib' imported but unused
main_controller.py:9:1: F401 'neo' imported but unused
main_controller.py:10:1: F401 'foo' imported but unused
main_controller.py:13:1: F401 'PyQt5.QtWidgets.QMainWindow' imported but unused
main_controller.py:13:1: F401 'PyQt5.QtWidgets.QFileDialog' imported but unused
main_controller.py:16:12: F821 undefined name 'pyqtSignal'
main_controller.py:18:1: E302 expected 2 blank lines, found 1
main_controller.py:27:10: E225 missing whitespace around operator
main_controller.py:28:9: F841 local variable 'a' is assigned to but never used
main_controller.py:28:10: E225 missing whitespace around operator
main_controller.py:29:5: E301 expected 1 blank line, found 0
main_controller.py:30:80: E501 line too long (85 > 79 characters)
main_controller.py:35:80: E501 line too long (80 > 79 characters)
main_controller.py:41:5: E303 too many blank lines (2)
main_controller.py:49:13: F841 local variable 'e' is assigned to but never used
main_controller.py:55:5: E303 too many blank lines (2)
main_controller.py:64:5: E303 too many blank lines (2)
main_controller.py:80:5: E303 too many blank lines (2)
```

I want to show them in my fringe.

# My configuration

## OS
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-05-29
OS: Debian GNU/Linux 9.6 (stretch) x86_64

## Result of `(elpy-config)`

```
Elpy Configuration

Virtualenv........: global_py3 (/home/azzamsya/.virtualenvs/global_py3)
RPC Python........: 3.5.3 (/home/azzamsya/.virtualenvs/global_py3/bin/python)
Interactive Python: python (/home/azzamsya/.virtualenvs/global_py3/bin/python)
Emacs.............: 26.1
Elpy..............: 1.27.0
Jedi..............: 0.13.2
Rope..............: Not found (0.11.0 available)
Autopep8..........: 1.4.3
Yapf..............: 0.25.0
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/home/azzamsya/.virtualenvs/global_py3/bin/flake8)

The black package is not available. Commands using this will not work.
```

## Elpy configuration in my init.el

https://github.com/azzamsa/emacs.d/blob/master/modules/aza-python.el

Thank you for Elpy :)

**Comment by azzamsa** [comment]
Solved.

It turns out that I have to kill the reopen the buffer. 

My previous step was:
1) pyvenv-workon
2) pyvenv-restart-python

Now I have to kill and reopen the buffer for the third step.

Would you like to do this automatically (without kill-and-reopen) after doing python-restart ?

Thank you.

**Comment by azzamsa** [comment]
> Maybe re-enabling flycheck/flymake would suffice?

re-enabling them don't work. still need to kill then reopen. 
Maybe we can add [auto-virtualenv](https://github.com/marcwebbie/auto-virtualenv) hooked when elpy start. But for now I will use the traditional one :)

**Comment by jorgenschaefer** [comment]
It's weird that the buffer needs to be re-opened. I do not know why. You can do so on the `pvenv-post-activate-hooks`, but it shouldn't be necessary …

**Comment by azzamsa** [comment]
> It's weird that the buffer needs to be re-opened. I do not know why. 

Do you encounter the same issue in your machine ?

**Comment by jorgenschaefer** [comment]
I have a global installation of flake8, so I can't reproduce this, no.

**Comment by azzamsa** [comment]
Thanks :)

Maybe I will stick with venv, I am really worried of python dependency hell.

Thanks for Elpy. :)

**Comment by azzamsa** [comment]
Anyone who didn't have flake8 and other lib globally. You can use pyvenv hooks to make change applied immediately to current opened buffer.

```elisp
(use-package pyvenv
  :config
  (add-hook 'pyvenv-post-activate-hooks
            (lambda () (revert-buffer t t))))
```
