### ISSUE TITLE
MELPA url incorrect in docs?

### ISSUE THREAD

**Issue by ATL-Flaneur** [jorgenschaefer/elpy#1513]
# Summary

Thank you for reporting to Elpy !

Here is a template to help you do it so your issue can be fixed as
soon as possible. Please replace this paragraph with a summary of
your issue and fill the next sections.

# Steps to reproduce

Following directions, evaluate in `*scratch*`

```
(require 'package)
`(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/"))
```

Then run `M-x package-refresh-contents` to load the contents of the new repository, 

# My configuration
## OS

MacOS 10.14.2 with Emacs 26.1

## Result of `(elpy-config)`

Doesn't get this far. Get the following in `*Messages*`:

```
Contacting host: stable.melpa.org:443
Contacting host: elpa.gnu.org:443
Failed to download ‘gnu’ archive.

```

## Elpy configuration in my init.el
```
N/A
```

Looks like the URL has changed?

**Comment by jorgenschaefer** [comment]
Nope, both URLs are correct. The offial GNU one just has some issues from time to time. (Note the error you see says "gnu", not "melpa".)

**Comment by ATL-Flaneur** [comment]
Thanks for the quick reply. Any mirrors that I could use, or just wait for the server issue to resolve?

It is interesting that going to `https://stable.melpa.org/packages/` gives:

```
Package Listing

Please see the main page for a full package listing. You will be redirected automatically.
```

**Comment by jorgenschaefer** [comment]
Yes, it's the URL for the package.el tool, not for web browsers. :-)

**Comment by jorgenschaefer** [comment]
And no, there are no mirrors of those archives. I'm afraid you'll have to wait until it's fixed (it works for me right now, maybe try again?)

**Comment by ATL-Flaneur** [comment]
Tried again—same error of `Failed to download ‘gnu’ archive.` 😕

**Comment by jorgenschaefer** [comment]
`package-initialize` is done automatically by Emacs. I'm afraid Elpy requires Emacs to work, and can not include the entirety of Emacs' documentation.

Glad it works now for you, and enjoy Elpy :-)
