### ISSUE TITLE
The documentation about getting completion from shell is not up-to-date

### ISSUE THREAD

**Issue by abangfarhan** [jorgenschaefer/elpy#1515]
I notice that in the [documentation](https://elpy.readthedocs.io/en/latest/ide.html) and also at the [documentation's source](https://github.com/jorgenschaefer/elpy/blob/master/docs/ide.rst) it was mentioned that to get completion from shell we need to set the variable `elpy-company-add-completion-from-shell` to `t`. However, what needed to be changed is the `elpy-get-info-from-shell`. Is there a reason why the documentation is not up-to-date?

**Comment by jorgenschaefer** [comment]
I suspect the reason is that whover did the change to the code forgot to update the documentation, and no one else did so far :-) If you would like to fix it, a PR would be most welcome!

**Comment by galaunay** [comment]
Someone may be me...
Thanks for fixing this :)
I guess we can close this issue now.
