### ISSUE TITLE
ipython inferior shell completions not working

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1517]
Just for letting you know of https://github.com/ipython/ipython/issues/11541 which affects users of ipython.

Is not elpy's neither python.el's fault but maybe you're or will be getting reports so...

The linked issue contains a diagnosis of the problem and a suggested fix. You might want to check if the fix is right for emacs, since the failing method `all_completions` is in ipython just for the sake of emacs.

**Comment by Xparx** [comment]
I'm so relieved it's not only me... I have wrestled with this issue all day (and unknowingly for a couple of weeks(?)). 
Screaming internally for hours. 

Thanks for figuring it out (I hope).
This effects jupyter-console as well I assume?

I'm using a setup with with elpy and ob-ipython and I thought I hit the file size limit of completion before x-mas and have proceeded to cut my file up in to smaller files. Unsurprisingly with no effect.

Today I started to try to use regular python through both orgmode and (run-python) and company-mode works.

**Comment by Xparx** [comment]
I think I know what you mean.
I'm running python 3.6.7  with IPython 7.2.0 inside jupyter-console it looks like or however it is setup.
Not sure exactly how it works.

When starting the jupyter-console with default arguments this is the header of the terminal

    Jupyter console 6.0.0

    Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
    Type 'copyright', 'credits' or 'license' for more information
    IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

But as with (run-python) I also tried it with `X-u M-x run-python RET ipython --simple-prompt` with the same result.  So I have to assume it stems from the same issue.

**Comment by Xparx** [comment]
Btw, do you know in what version of ipython this got introduced? If I knew I could install an older version.

**Comment by Xparx** [comment]
I installed the previous version ipython 7.1.1 and the issue is not there. i.e. I got back autocompletion in my shell back.
(Thanks for posting this and pointing me in the right direction.)

**Comment by memeplex** [comment]
`all_completions` is calling `complete` which has been deprecated, so I assume the problem must have been introduced recently, probably in a refactoring that introduced `completions` as the new interface but forgot to redirect `all_completions` there.

**Comment by gtakacs** [comment]
Changing the behavior of get_ipython().complete() is super annoying. It broke completion in my ipython.el based Emacs environment, therefore I downgraded to IPython 7.1.

**Comment by memeplex** [comment]
@gtakacs you don't neee to do that. See https://github.com/ipython/ipython/issues/11541 for a workaround you can just add to your ipython config file.

**Comment by Xparx** [comment]
I Just tried the solution but I still can't get completion working for ipython=7.2.0.

i put the following code in `~/.ipython/profile_default/ipython_config.py`
```
# Configuration file for ipython.
import warnings

warnings.filterwarnings('ignore')

c = get_config()  # noqa

c.TerminalIPythonApp.extensions = [
    'autoreload'
]
c.TerminalIPythonApp.exec_lines = [
    '%autoreload 2',
    # https://github.com/ipython/ipython/issues/11541
    'get_ipython().Completer.all_completions = '
        'lambda t: map(lambda c: t[:t.rfind(".") + 1] + c.text, '
                      'get_ipython().Completer.completions(t, len(t)))'  # noqa

]
# c.InteractiveShell.colors = 'nocolor'
# c.InteractiveShellApp.matplotlib = 'tk'
```

**Comment by Xparx** [comment]
Hmm. I'm not sure my config is loading correctly. The autoload desn't seem to be loaded either. Ill give this an extra look when I have time.

**Comment by memeplex** [comment]
This was already fixed in milestone 7.3. I think we can close it. It stays as reference nevertheless.

**Comment by azzamsa** [comment]
@memeplex today I try to use Ipython because company some time din't work in inferior shell, but with the same code it works in buffer.

Is there a way for us (elpy) to make company work reliably in inferior shell ? if this the case maybe should I open new issue ?

**Comment by memeplex** [comment]
It should work with the next release of ipython, meanwhile use the workaround I proposed in https://github.com/ipython/ipython/issues/11541 (or clone ipython master and install with `pip install --user -e .`.

**Comment by azzamsa** [comment]
Great, for now I will see what we can do to improve company situation https://github.com/jorgenschaefer/elpy/issues/1545
