### ISSUE TITLE
some common backend which will utilize and choose between jedi/rope

### ISSUE THREAD

**Issue by sergeyglazyrindev-samsung** [jorgenschaefer/elpy#1518]
Hello. I'd like to use rope as backend for elpy. You support now jedi only. That's ok. That's your personal project and you may make any decisions as you are owner but I'd like to create a common python backend which will utilize rope/jedi specific stuff, so it may become appropriate for usage in elpy.
What do you think ?
Would you consider to change jedi to python-elpy-backend which would be a python package which will make a decision and chooses between jedi/rope/etc
It won't be hard. But I think it would be good to get rid of specific jedi usage in elpy. Then we can solve issue with not supported rope, etc. Now rope supports python 3 features without rope_py3k package.

**Comment by sergeyglazyrindev-samsung** [comment]
Omg :) Language server protocol sounds amazing but not sure if it would be easy to use it in elpy...
About my idea: that's a point: I'd love to own a package which encloses whole logic related to jedi stuff. And we will remove everything related to jedi from elpy and you'll use only this package. All logic related to the specific jedi usage will be encapsulated in the new python package. I think it would be great improvement for elpy. And that will give me a room to add back rope. Rope isn't dead. But I don't want to convince you as we had tough discussion before. That's why I'd like to use elpy with rope but I don't want to create an extra problems for you.

**Comment by jorgenschaefer** [comment]
I understand. I do not think a new project with a single maintainer would be a good dependency for Elpy I'm afraid. Thank you for your offer in any case :-)

**Comment by sergeyglazyrindev-samsung** [comment]
What could you recommend me to use to support rope for elpy ? auto-complete, etc ? I don't want to clone elpy and customize it.... cause I'll lose compatibility with your upstream

**Comment by jorgenschaefer** [comment]
I can not in good conscience recommend to use rope at all.

If you must, you could write a Python module with the same interface as the jedi module but using rope behind the scenes, make it importable as `jedi`, and install that in the virtualenv instead of the "real" jedi. You can't use jedi then, but you'd be using Rope that way. It would be some effort, though, as you have to mimic Jedi's interface.

**Comment by sergeyglazyrindev-samsung** [comment]
Thank you
