### ISSUE TITLE
How can I pass an argument to black?

### ISSUE THREAD

**Issue by mrbig033** [jorgenschaefer/elpy#1522]
# Summary

# Steps to reproduce

Run `elpy-black-fix-code` on code with more than 80 characters line length. It will format the code following its default of 90 characters per line. I wish to change this option. The command line option on [Black's documentation](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length) is clear, but I don't know where to put it on Elpy.

# My configuration

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
of 2018-11-28
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- elpy-20181204.148
- Python 3.7.2
- black, version 18.9b0

## Result of `(elpy-config)`

```
Virtual........: None
RPC Python........: 3.7.2 (/usr/local/bin/python3.7)
Interactive Python: python3.7 (/usr/local/bin/python3.7)
Emacs.............: 27.0.50
Elpy..............: 1.27.0
Jedi..............: 0.13.2
Rope..............: Not found (0.11.0 available)
Autopep8..........: 1.4.3
Yapf..............: 0.25.0
Black.............: 18.9b0
Syntax checker....: flake8 (/usr/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.
```

## Elpy configuration in my init.el

# Paste it here

``` emacs-lisp
(use-package elpy
  :defer t
  :ensure t
  :init
  (setq elpy-autodoc-delay 0.3)
  (add-hook 'elpy-mode-hook (lambda () (elpy-shell-toggle-dedicated-shell 1)))
  (add-hook 'python-mode-hook 'elpy-mode)
  :config
  (general-unbind 'elpy-mode-map
    :with 'ignore
    [remap elpy-shell-send-statement-and-step])
  (setq python-shell-completion-native-enable t)
  (setq elpy-rpc-python-command "python3.7")
  (setq python-shell-interpreter "python3.7") (elpy-enable))
```

**Comment by gopar** [comment]
Currently, there is no way to pass arguments to black :(

**Comment by mrbig033** [comment]
That's a shame! Thanks anyway.

**Comment by galaunay** [comment]
If you need to specify arguments project-wise, you may be interest in using a `pyproject.toml` file (see black documentation [here](https://github.com/ambv/black#pyprojecttoml)).

**Comment by mrbig033** [comment]
@galaunay thank you very much for your answer, but I opted to use [blacken](https://github.com/proofit404/blacken) in addition to Elpy instead.

**Comment by juergenhoetzel** [comment]
> If you need to specify arguments project-wise, you may be interest in using a `pyproject.toml` file (see black documentation [here](https://github.com/ambv/black#pyprojecttoml)).

Sadly ` pyproject.toml` is only loaded  if `black`  is run as CLI-Tool: Seems like the config file loading has also be done in elpy `blackutil.py`

**Comment by galaunay** [comment]
oh yes... you are right.

I made PR (#1565) to allow to customise the maximal number of characters per line (as it seems to be a very common parameter to change).

Tests are not passing properly yet,but we can continue the discussion there.

**Comment by juergenhoetzel** [comment]
> I made PR (#1565) to allow to customise the maximal number of characters per line (as it seems to be a very common parameter to change).
> 
> Tests are not passing properly yet,but we can continue the discussion there.

Thanks for your PR!  But it would be nice if elpy could configure the maximum line length itself. To quote elpy goals 

> It combines and configures a number of other packages

the `custom` option and the `.flake8` option can even be in conflict with each other.

I came up with this *hacky* code: 

```python
    try:
        import os
        from flake8.api import legacy as flake8
        cwd = os.getcwd()
        os.chdir(directory)
        line_length = flake8.get_style_guide().options.max_line_length
        os.chdir(cwd)
    except ImportError:
        line_length = black.DEFAULT_LINE_LENGTH
```

**Comment by juergenhoetzel** [comment]
> > I made PR (#1565) to allow to customise the maximal number of characters per line (as it seems to be a very common parameter to change).
> > Tests are not passing properly yet,but we can continue the discussion there.
> 
> Thanks for your PR! But it would be nice if elpy could configure the maximum line length itself. To quote elpy goals
> 
> >

Based on your branch I used the following code in the RPC-Server to figure out the `maximum_line_length`:

```python
import os
import configparser


def get_max_line_length(root):
    pyproject_path = os.path.join(root, "pyproject.toml")
    flake8_path = os.path.join(root, ".flake8")
    parser = configparser.SafeConfigParser()
    if parser.read(pyproject_path) and parser.has_option("tool.black", "line-length"):
        return parser.getint("tool.black", "line-length")
    if parser.read(flake8_path) and parser.has_option("flake8", "max-line-length"):
        return parser.getint("flake8", "max-line-length")
```

If you merge #1560 and there is interest in this code I would create a PR

**Comment by galaunay** [comment]
@juergenhoetzel Sorry I didn't saw your proposal for a PR.
I went forward and added the feature.

The code is heavily inspired from yours. 
If you want the authorship for this, please tell me, I will revert my commit and merge yours.

I guess this issue can be closed anyway.
