### ISSUE TITLE
Change of maintainership

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#1523]
Hello @galaunay!
As you have noticed, I have been less and less active the last months. I simply do not have the time to work on Elpy anymore. As you have been doing a great job and your decisions and changes have been pretty much spot on – thank you again so much for all your great work! – would you like to take over maintainership officially?

I will stop responding to issues here unless I'm mentioned explicitly.

**Comment by memeplex** [comment]
I wouldn't mind helping with minor fixes/features.

**Comment by galaunay** [comment]
Hi @jorgenschaefer,

I would be happy to take over.
I will try my best to take good care of Elpy, as you did those 6 past years.
Thanks for your trust on that matter.

However, I guess it will take a bit of time from both our sides to switch (you will have to brief me on the release process at least ?), and it is kind of a bad time for me (as you can see for my late reply...).
Would you consider doing that in a few weeks, when I would be able to take the time to do it properly ?

**Comment by jorgenschaefer** [comment]
I'm definitely not gone and you can @mention me any time. I just noticed I can't keep up and I feel worse and worse for it.

The release process is nowadays basically './script/release`

This still includes the elpy PyPI package, but that package is basically useless and should not be used anymore, and shouldn't have been used anymore for many years. That step can be removed.

Thank you so much for your work!

**Comment by galaunay** [comment]
Hi @jorgenschaefer,

I made a release yesterday and somebody complained about the Pypi package to be obsolete on IRC.
I told him to use Melpa as recommended by the doc, but could we delete Elpy from Pypi to be sure nobody is using it anymore ?

**Comment by jorgenschaefer** [comment]
I deleted the project on PyPI. Thank you for all your work! :-)

**Comment by rakanalh** [comment]
> I deleted the project on PyPI. Thank you for all your work! :-)

I think removing the package was a bit of a hasty decision. For people not using the latest version, elpy python package cannot be installed and elpy won't work.

**Comment by galaunay** [comment]
> For people not using the latest version, elpy python package cannot be installed and elpy won't work.

Elpy's python files come with Elpy since version 1.4 (mai 2014).
Are you using an older version than that ?

**Comment by rakanalh** [comment]
I actually have 1.29.1 installed. I still get warnings about non-matching elpy version installed. I should probably delete the py package installed using pip.

**Comment by rakanalh** [comment]
> Elpy's python files come with Elpy since version 1.4 (mai 2014).
> Are you using an older version than that ?

How is this supposed to work with venvs though?

**Comment by galaunay** [comment]
@jorgenschaefer I just realized that the [documentation](https://elpy.readthedocs.io/en/latest/index.html) at readthedoc was not updated by the latest release (still mentioning Elpy 1.27). Is it not supposed to be triggered automatically from github ?
