### ISSUE TITLE
How does elpy choose auto-formatting library?

### ISSUE THREAD

**Issue by dankessler** [jorgenschaefer/elpy#1525]
This is likely a matter for the documentation, but when getting started with elpy, I was curious how elpy would choose between `yapf`, `autopep8`, and `black` (assuming all were installed) when I called `elpy-format-code`. 

The [documentation](https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-format-code) is not crystal clear on package priority, but from reading the [source of `elpy.el`, L2167](https://github.com/jorgenschaefer/elpy/blob/b4803b554d78941e871cd976ff7828294e85c991/elpy.el#L2167), it seems to me that it will use, in the order listed below, the first package it determines to be "available" (using `elpy-config--package-available-p`)
1. `yapf`
2. `autopep8`
3. `black`

I notice this is the order in which the packages are listed in the [documentation](https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-format-code), but I thought it could be made a bit clearer. For example, if someone has a tricked out `autopep8` style file, they may be confused why it's not doing anything if `yapf` is also available.

I'd be happy to do this as a small PR, but wanted to check with an issue to see if this would be the right way to contribute.

The only place where the ordering seems different that I've seen is in the buffer displayed by `elpy-config`, which for me displays the (formatting) packages in the order
1. `autopep8`
2. `yapf`
3. `black`

**Comment by gopar** [comment]
Hey! Thanks for taking the time to point this out.

True, doesn't seem like elpy explicitly mentions the order of formatters :/ 

A PR will be happily appreciated :)

**Comment by galaunay** [comment]
It is in the doc now, I am closing this.
