### ISSUE TITLE
xref-find-definitions with prefix arg still not working in big files

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1529]
# Summary

A similar problem was reported before (https://github.com/jorgenschaefer/elpy/issues/1426) and apparently fixed by the merged PR (https://github.com/jorgenschaefer/elpy/pull/1429).

But now I'm getting a "Timeout during RPC call get_names from backend" after about a second of waiting.

I think the right behavior would be to show a prompt with no autocompletions if generating the list is too expensive.

# Steps to reproduce

Open a python file with many identifiers (for example [completer.py](https://raw.githubusercontent.com/ipython/ipython/75dc1c0bab811325814dad862b9dde1aec79aff8/IPython/core/completer.py)) , type `C-u M-.`.

# My configuration

## OS

```
~:: uname -a
Linux archlinux 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
```
## Result of `(elpy-config)`

```

Virtualenv........: None
RPC Python........: 3.7.2 (/usr/bin/python)
Interactive Python: ipython (/home/carlos/.local/bin/ipython)
Emacs.............: 26.1.90
Elpy..............: 1.28.0
Jedi..............: 0.13.2
Rope..............: Not found (0.11.0 available)
Autopep8..........: Not found (1.4.3 available)
Yapf..............: Not found (0.25.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/home/carlos/.local/bin/flake8)
```

## Elpy configuration in my init.el

```
 '(elpy-get-info-from-shell t)
 '(elpy-remove-modeline-lighter t)
 '(elpy-shell-echo-input-lines-head 3)
 '(elpy-shell-echo-input-lines-tail 3)

(defun my-elpy-mode-hook ()
  (setq fill-column 79
        ;; https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32120
        tab-width 4))
(add-hook 'elpy-mode-hook #'my-elpy-mode-hook)

;; https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32344
;; https://github.com/jorgenschaefer/elpy/issues/1428
(defun my-elpy-highlight-input-advice
    (f string face &optional no-font-lock)
  (if (not (eq face 'comint-highlight-input))
      (funcall f string face no-font-lock)
    (funcall f string face t)
    (python-shell-font-lock-post-command-hook)))
(advice-add #'elpy-shell--insert-and-font-lock
            :around #'my-elpy-highlight-input-advice)

(defun my-comint-highlight-input-advice (f &rest args)
  (if (eq major-mode 'inferior-python-mode)
      (cl-letf* ((g (symbol-function 'add-text-properties))
                 ((symbol-function 'add-text-properties)
                  (lambda (start end properties &optional object)
                    (unless (eq (nth 3 properties) 'comint-highlight-input)
                     (funcall g start end properties object)))))
        (apply f args))
    (apply f args)))
(advice-add #'comint-send-input :around #'my-comint-highlight-input-advice)

(elpy-enable)

;; https://github.com/jorgenschaefer/elpy/issues/1399
(define-key elpy-mode-map (kbd "M-<tab>") #'company-capf)

```

**Comment by galaunay** [comment]
It would be relatively simple to do.

However, because Elpy identifies objects using the line number and the object name (for example "234: foo"), you would need to input both of them in the prompt (which implies knowing the object line number...).
Would this feature be useful in that case ?

**Comment by memeplex** [comment]
No, I don't think it could be useful that way but just confusing. I see the underlying problem, though.

**Comment by memeplex** [comment]
@galaunay shouldn't this old issue https://github.com/jorgenschaefer/elpy/issues/544 be closed? Is there anything missing?

**Comment by gopar** [comment]
Closed it. @memeplex thanks for noticing it
