### ISSUE TITLE
Symbol's function definition is void: elpy-enable

### ISSUE THREAD

**Issue by raullaasner** [jorgenschaefer/elpy#1532]
# Summary

When opening Emacs, I get the error message
```
Symbol's function definition is void: elpy-enable
```
Everything was working fine until now and I haven't made any changes recently. I have installed elpy from melpa and I can see that all the files are located in `~/.emacs.d/elpa/elpy-20190130.2109/`. That includes `elpy.el` which defines `elpy-enable`. I also tried adding
```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/elpy-20190130.2109/")
```
to the configuration file in case that directory was not searched in but it made no difference. Any ideas how to debug this?

# Steps to reproduce

My Emacs configuration file contains
```elisp
(package-initialize)
(elpy-enable)
```
If I use this instead,
```elisp
(use-package elpy
  :config
  (elpy-enable))
```
the error message becomes
```
Error (use-package): Cannot load elpy
```

# My configuration

Emacs: 26.1
OS: Arch Linux

## Result of `(elpy-config)`

Since elpy is not properly loaded, this command cannot be run.

**Comment by raullaasner** [comment]
The only thing that seems to work for me is to include the following in the configuration file:
```elisp
(load-file "~/find-file-in-project.el")
(require 'find-file-in-project)
(load-file "~/.emacs.d/elpa/elpy-20190130.2109/elpy-autoloads.el")
(elpy-enable)
```
I had to first download `find-file-in-project.el` and put it somewhere. Very strange.

**Comment by galaunay** [comment]
`find-file-in-project` is an Elpy dependency,
it should be installed automatically when installing elpy from Melpa.

What happen if you try reinstalling elpy ?

**Comment by raullaasner** [comment]
Thanks. I uninstalled both elpy and `find-file-in-project` and then reinstalled elpy and now it works. Previously, I had only uninstalled and reinstalled elpy, which still led to the error.
