### ISSUE TITLE
`elpy-format-code` removes ALL blank lines on windows when region is selected.

### ISSUE THREAD

**Issue by AdamCottrill** [jorgenschaefer/elpy#1533]
# Summary

`elpy-format-code` removes ALL blank lines on windows when region
is selected but works as expected on the whole buffer.

# Steps to reproduce

To illustrate the issue, here are some simple functions taken from the python documentation.  The whole buffer was originally formatted with `elpy-black-fix-code`.  Everything looks as it should:

 ```python
def all(iterable):
     """
     a simple example function
     """

     for element in iterable:
         if not element:
             return False
     return True


def any(iterable):
     """
     a simple function
     """

     for element in iterable:
         if element:
             return True
     return False


def enumerate(sequence, start=0):
     """
     a simple example function
     """
 
     n = start
     for elem in sequence:
         yield n, elem
         n += 1
```

If we select the region from line 1 to the return value of the second function (any()) and run `elpy-format-code`, ALL of the blank lines are removed, included those that should be kept. In this example, there should be two spaces above the definitions of any() and enumerate(), and the single blank lines should also remain inside the function blocks of all() and any():

```python
def all(iterable):
    """
    a simple example function
    """
    for element in iterable:
        if not element:
            return False
    return True
def any(iterable):
    """
    a simple example function
     """
    for element in iterable:
        if element:
            return True
    return False

def enumerate(sequence, start=0):
    """
    a simple example function
    """

    n = start
    for elem in sequence:
        yield n, elem
        n += 1
```
   
If we modify `elpy--fix-code-with-formatter` by changing this line:

```lisp
    (replace-regexp-in-string "\n$" "" new-block))
```
to this:

```lisp
    (replace-regexp-in-string "\r\n$" "" new-block))
```

Then evaluating the whole elpy.el buffer and re-running `elpy-format-code` on the
same region as above yields:

```python
def all(iterable):
    """
    a simple example function
    """

    for element in iterable:
        if not element:
            return False
    return True


def any(iterable):
    """
    a simple example function
    """

    for element in iterable:
        if element:
            return True
    return False


def enumerate(sequence, start=0):
    """
    a simple example function
    """

    n = start
    for elem in sequence:
        yield n, elem
        n += 1
```

Which I believe is exactly what it should be.  I'm not sure how this suggestion will effect the function on unix systems. Worst case scenario might be to add an if statement to use '\r\n$' on windows and '\n$' on unix systems, but regrettably, this is far beyond my lisp skill set.

# My configuration
## OS

Windows 7

## Result of `(elpy-config)`

Elpy Configuration

Virtualenv........: test_elpy (C:/1work/.virtualenv/test_elpy)
RPC Python........: 3.7.0 (c:/windows/py.exe)
Interactive Python: C:/python37/python.exe (C:/python37/python.exe)
Emacs.............: 26.1
Elpy..............: 1.28.0
Jedi..............: 0.13.2
Rope..............: 0.12.0
Autopep8..........: 1.4.3
Yapf..............: 0.26.0
Black.............: 18.9b0
Syntax checker....: flake8.exe (c:/Python37/Scripts/flake8.exe)

## Elpy configuration in my init.el
```lisp
(elpy-enable)
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
   (add-hook 'elpy-mode-hook 'flycheck-mode))
```

**Comment by AdamCottrill** [comment]
I was able to recreate the issue on a second computer running Linux Mint.  The suggested fix above fixes the issue on this computer too.

Results of elpy-config:

Virtualenv........: test_elpy (/home/adam/.virtualenvs/test_elpy)
RPC Python........: 3.6.8 (/home/adam/.virtualenvs/test_elpy/bin/python)
Interactive Python: python (/home/adam/.virtualenvs/test_elpy/bin/python)
Emacs.............: 25.3.2
Elpy..............: 1.28.0
Jedi..............: 0.13.2
Rope..............: 0.12.0
Autopep8..........: 1.4.3
Yapf..............: 0.26.0
Black.............: 18.9b0
Syntax checker....: flake8 (/home/adam/.virtualenvs/test_elpy/bin/flake8)

**Comment by galaunay** [comment]
Thanks for reporting.

In fact, I don't understand what `(replace-regexp-in-string "\n$" "" new-block)` is supposed to do.
It is basically removing every empty lines (which gives what you observe).

It is coming from a commit from two years ago (132a202f9a6e62742f81d73e56eec6842672391e).
I don't know how it has remained unnoticed for so long.
I made #1536 to address this.

**Comment by galaunay** [comment]
#1536 is merged now.
I close this issue that is (hopefully) fixed.

Please re-open if it is not the case.

**Comment by azzamsa** [comment]
I was using this feature once, since it's broken, I thought it comes from my config. Turn out this comes from Elpy :)

Previously:

![anim-ta](https://user-images.githubusercontent.com/17734314/52946460-a3f76d00-33a6-11e9-91a2-7074c028c710.gif)

After Upgrade to https://github.com/jorgenschaefer/elpy/pull/1536:

![anim-tb](https://user-images.githubusercontent.com/17734314/52946528-ce492a80-33a6-11e9-986e-eca2a5348bfa.gif)

Thanks for the fix.
