### ISSUE TITLE
Downgrade flymake errors (question)

### ISSUE THREAD

**Issue by bindernet** [jorgenschaefer/elpy#1540]
# Summary
I see issues like W293 'blank line contains whitespace' as an error. I know I can disable using a flake8 config. However I would like to change it to a warning. Any ideas?
Thanks. 

# Steps to reproduce

# My configuration
## OS
arch linux

## Result of `(elpy-config)`
Elpy Configuration

Elpy Configuration

Virtualenv........: env (/home/xxxx/automl/run2/env)
RPC Python........: 3.7.2 (/home/xxxx/automl/run2/env/bin/python)
Interactive Python: python (/home/xxxx/automl/run2/env/bin/python)
Emacs.............: 26.1
Elpy..............: 1.28.0
Jedi..............: 0.13.2
Rope..............: Not found (0.12.0 available)
Autopep8..........: Not found (1.4.3 available)
Yapf..............: Not found (0.26.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/home/xxxx/.local/bin/flake8)

## Elpy configuration in my init.el
(elpy-enable)
--- From .emacs

**Comment by galaunay** [comment]
You can use `python-flymake-msg-alist` to choose which message you want to assign to notes, warnings and errors. Something like that for example: 
``` Elisp
(setq python-flymake-msg-alist
  '(("\\(^redefinition\\|.*unused.*\\|used$\\)" . :warning)
   ("^E999" . :error)
   ("^[EW][0-9]+" . :note)))
```

That is a good point though, I think I am gonna try to set this to a decent value for python.

**Comment by galaunay** [comment]
#1541 should label every error with a code beginning by "W" as warnings.
This should address your problem as well.

**Comment by bindernet** [comment]
Great. Thanks.
