### ISSUE TITLE
uninformative error message if _python-shell-interpreter_ cannot be found

### ISSUE THREAD

**Issue by otoomet** [jorgenschaefer/elpy#1549]
# Summary

If elpy cannot find _python-shell-interpreter_, it reports "_wrong-type-argument arrayp nil_".  This error message is rather unhelpful.

I expect something along the lines:

_python shell interpreter [name] cannot be found.  Check your 'python-shell-interpreter' variable setting_

# Steps to reproduce

1. set the variable _python-shell-interpreter_ to a non-existing executable (like _xyz_) in .emacs (or uninstall your interpreter).
2. restart emacs
3. open a python file
4. go to an executable statement in the python file (e.g. `print("hello")`)
4. type C-c C-y s  
  i.e. execute statement of code
5. you get the error _shell-quote-argument: Wrong type argument: arrayp, nil_

# My configuration
## OS
Ubuntu 16.04

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.5.2 (/usr/bin/python3)
Interactive Python: xyz (not found)
Emacs.............: 24.5.1
Elpy..............: 1.28.0
Jedi..............: 0.11.1 (0.13.3 available)
Rope..............: 0.12.0
Autopep8..........: 1.4.3
Yapf..............: 0.26.0
Black.............: Not found (18.9b0 available)
Syntax checker....: Not found (flake8)
```

## Elpy configuration in my init.el
(no init.el, related code from .emacs)
```
      ;(setq python-shell-interpreter "ipython3")
      (setq python-shell-interpreter "xyz")
      (setq elpy-rpc-python-command "python3")
      (setq python-shell-interpreter-args "--simple-prompt -i")
```

**Comment by galaunay** [comment]
Thanks for the feedback.

Emacs 26.1 does a slightly better job and report `apply: Searching for program: No such file or directory, xyz`.

I still added a warning in Elpy. 
It should be implemented in the next version.

**Comment by galaunay** [comment]
That is merged, 
I am closing this.
