### ISSUE TITLE
how to interactively activate project local `venv/`

### ISSUE THREAD

**Issue by avocadoras** [jorgenschaefer/elpy#1558]
# Summary
I'm really trying to do something simple but cannot find the functionality in the elpy documentation. I would like for `workon` to read local `venv/` directories. I can get this to work with my Emacs tool bar by pressing `Activate` and then choosing my project's `venv/` directory. How can I activate my local project's `venv` interactively?

# My configuration
## OS

Macos Mojave

## Elpy configuration in my init.el
```
(use-package elpy
  :after python
  :ensure t
  :config
  (elpy-enable)
  (defalias 'workon 'pyvenv-workon)
  ;; (setq elpy-rpc-backend "jedi")
  ;; use flycheck instead of flymake
  (when (load "flycheck" t t)
    (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
    (add-hook 'elpy-mode-hook 'flycheck-mode)))
```

**Comment by azzamsa** [comment]
If you mean 'interactively' as invoking them from minibuffer, you can use `M-x pyvenv-workon`. But if you mean 'automatically' you can use something like [auto-virtualenv](https://github.com/marcwebbie/auto-virtualenv) or [pyenv-mode-auto](https://github.com/ssbb/pyenv-mode-auto)

I never use both package. I just invoke pyvenv-workon before starting to work on project.

**Comment by avocadoras** [comment]
@azzamsa I meant interactively as in calling the function with `M-x`. Ok, so I have `(defalias 'workon 'pyvenv-workon)`, but when I `M-x workon` I get a message that `$WORKON_HOME` is not set. When I use `M-x pyvenv-activate` I can activate my local `venv/` directory. Another thing, how can set the modeline to show currently active virtual environment?

**Comment by azzamsa** [comment]
I tried some venv package in emacs, but in the end I decide to stick with [pyvenv](https://github.com/jorgenschaefer/pyvenv).

Try the following steps:

1. remove all your config that manages venv
2. install pyvenv
3. use `pyvenv-workon`
4. select the venv

![workon](https://user-images.githubusercontent.com/17734314/55269138-d740ec00-52c2-11e9-9cfe-855ef22f8b3c.png)

my config just as simple as this:

```
(use-package pyvenv
:after elpy)
```

I've my venv name in my modeline without additional config, I belive pyvenv handle this out of the box.
 
PS: I am using [virtualenvwrapper ](https://virtualenvwrapper.readthedocs.io/en/latest/), so all my venv are in one place ~/.virtualenvs

**Comment by avocadoras** [comment]
@azzamsa I was using `virtualenvwrapper.el` and  I liked it cause I did not have to set up the global variables for `$WORKON_HOME` of `$PROJECT_HOME` as well as sourcing the file on login. I also liked that it showed you in the modeline currently active environments. Honestly, I just wanted something that would allow me to activate virtual environments in emacs and that would show me which one is active in the modeline. I'll stick to `pyenv` and `elpy.el` + `pyvenv.el`
