### ISSUE TITLE
Correct format to change key bindings

### ISSUE THREAD

**Issue by pauljohn32** [jorgenschaefer/elpy#1559]
# Create a full working key remapping stanza

I find several posts about key binding changes, but no full working example. I'm very close to victory here.  Can we put together all of the pieces?  

After a lot of fiddling around and copying mistakes out of posts on Stackoverflow, I believe I do have a working example that successfully changes C-return to S-return and M-TAB to s-TAB.  I arrived at this through a byzantine sequence of mistakes.

```
(eval-after-load "elpy"
 '(progn
    (define-key elpy-mode-map [(control return)] nil)
    (define-key elpy-mode-map [(shift return)] 'elpy-shell-send-statement-and-step)
    (define-key elpy-mode-map (kbd "?\M-\t") nil)
    (define-key elpy-mode-map (kbd "s-<tab>") 'elpy-company-backend)
    )
)
```

I was getting errors when I tried to specify kbd "M-TAB" in the third element,  Emacs warning said use "?\M-\t") to refer to M-TAB.  However, the 4th line only works with `<tab>`, so I'm confused/doubtful whether third define-key statement has any effect (window manager controls it anyway). I learned how to do the C-return mapping from the ESS help list. Their instructions had "[(control return)]" rather than (kbd ...).  

I'm unsure the define-key syntax. This post https://emacs.stackexchange.com/a/46254/14005 seems to assert it is more correct to write:

```
 (define-key elpy-mode-map [(shift return)]  # 'elpy-shell-send-statement-and-step)
```

or

```
 (define-key elpy-mode-map [(shift return)]  (function elpy-shell-send-statement-and-step))
```

I'm happy to do this the way you say is best, but I'm tired of guessing what's right in StackOverflow.

# My configuration
## Ubuntu Linux 18.10 
Elpy elpy-20190130.2109   

## Result of `(elpy-config)`
```
# Elpy Configuration

Virtualenv........: None
RPC Python........: 3.7.3 (/home/pauljohn/LinuxDownloads/anaconda3/bin/python)
Interactive Python: jupyter (/home/pauljohn/LinuxDownloads/anaconda3/bin/jupyter)
Emacs.............: 25.2.2
Elpy..............: 1.28.0
Jedi..............: 0.13.3
Rope..............: 0.12.0
Autopep8..........: 1.4.3
Yapf..............: 0.26.0
Black.............: 19.3b0
Syntax checker....: flake8 (/home/pauljohn/LinuxDownloads/anaconda3/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

Options

```

## Elpy configuration in my init.el

```
(elpy-enable)
;; recommended in elpy docs
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")
; https://stackoverflow.com/questions/25154809/how-can-i-stop-elpy-from-overriding-some-of-my-keybindings/25159354
; https://emacs.stackexchange.com/questions/46247/cannot-bind-m-s-left
(eval-after-load "elpy"
 '(progn
    (define-key elpy-mode-map [(control return)] nil)
    (define-key elpy-mode-map [(shift return)] 'elpy-shell-send-statement-and-step)
    (define-key elpy-mode-map (kbd "?\M-\t") nil)
    (define-key elpy-mode-map (kbd "s-<tab>") 'elpy-company-backend)
    )
)
```

**Comment by galaunay** [comment]
Following what is written in Elpy's code, I would use something like that:
```Elisp
(define-key elpy-mode-map (kbd "<C-return>") nil)
(define-key elpy-mode-map (kbd "<S-return>") 'elpy-shell-send-statement-and-step)
(define-key elpy-mode-map (kbd "M-TAB") nil)
(define-key elpy-mode-map (kbd "<backtab>") 'elpy-company-backend)
```

Internally, Elpy uses the `'function-name` syntax and not the `#'function-name` one.
To my understanding, it does not really change anything at this level, unless you are really worried about performance.

**Comment by pauljohn32** [comment]
Why do you prefer 

    (kbd "<C-return>")

to

    [(control return)]

Little differences like that concern me.

**Comment by galaunay** [comment]
`kbd` is supposed to be more simple to use, as said in the [doc](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-Rebinding.html#Init-Rebinding):
> There are several ways to write a key binding using Lisp. The simplest is to use the kbd function, which converts a textual representation of a key sequence—similar to how we have written key sequences in this manual—into a form that can be passed as an argument to global-set-key. 

The other options (strings and vector) are a little bit more tricky when the keys you want to bind are not ASCII characters.

I also like `kbd` because you can use `C-h k` (`describe-key`) to find out the representation of any keys by just pressing them.
