### ISSUE TITLE
setting python-check-command in dir-locals.el

### ISSUE THREAD

**Issue by little-dude** [jorgenschaefer/elpy#1564]
Hi,

First thanks for this package. I'm getting started with emacs and elpy so I apologize if this question is a bit dumb.

I work on different projects that use different linters (or linter options), so I'd like to set `python-check-command` to different values for some projects.

Here is what I have in my `init.el`:

```elisp
;; whitelist allowed values for python-check-command
(setq safe-local-variable-values
      (append '((python-check-command . "pylint")) safe-local-variable-values))

(use-package elpy
  ;; Only call `elpy-enable` when needed.
  ;; See: https://emacs.stackexchange.com/q/10065/22105
  :init (with-eval-after-load 'python (elpy-enable))
  :config
  ;; by default, elpy uses flymake. This forces it to use flycheck instead
  ;; See:
  ;;     - https://github.com/jorgenschaefer/elpy/wiki/Customizations#use-flycheck-instead-of-flymake
  ;;     - https://github.com/jorgenschaefer/elpy/issues/137
  (when (require 'flycheck nil t)
    (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
    (add-hook 'elpy-mode-hook 'flycheck-mode)))
```

In my project directory I have the following `.dir-locals.el`:

```elisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((python-mode
  (python-check-command . "pylint")))
```

An important precision I think: I don't have the linters globally installed somewhere, so they become available only after I run `pyvenv-activate`. I bet there's a way to automate that, but that's the next step.

Output of `elpy-config`, **after entering the virtualenv with `pyvenv-activate`**:

```
Elpy Configuration

Virtualenv........:  (/home/little-dude/python/docker-py/env/)
RPC Python........: 3.7.3 (/home/little-dude/python/docker-py/env/bin/python)
Interactive Python: python (/home/little-dude/python/docker-py/env/bin/python)
Emacs.............: 26.1
Elpy..............: 1.28.0
Jedi..............: 0.13.3
Rope..............: 0.14.0
Autopep8..........: 1.4.3
Yapf..............: 0.26.0
Black.............: 19.3b0
Syntax checker....: flake8 (/home/little-dude/python/docker-py/env/bin/flake8)
```

This looks good but `python-check-command` is still set to an invalid value, instead of `pylint`:

```
python-check-command is a variable defined in ‘python.el’.
Its value is "install pyflakes, pylint or something else"
Original value was 
"/home/little-dude/python/docker-py/env/bin/pyflakes"

  This variable may be risky if used as a file-local variable.
  However, you have added it to ‘safe-local-variable-values’.

Documentation:
Command used to check a Python file.

You can customize this variable.

[back]
``` 

Do you know why this `python-check-command` does not get set correctly in this case? This seems related to https://github.com/jorgenschaefer/elpy/issues/789, but I don't want to set this variable globally.

**Comment by little-dude** [comment]
I just realized that my `.dir-locals.el` is wrong...
It should be:

```elisp
((python-mode . ((python-check-command . "pylint"))))
```

Very sorry for the noise.

**Comment by galaunay** [comment]
If helpful: you can use something like this:
``` elisp
((python-mode
  (eval pyvenv-activate "/path/to/my/virtualenv")))
```
to automatically activate virtualenvs depending on the directory your are in.

**Comment by little-dude** [comment]
Thanks @galaunay !

Since I want to learn elisp a little I've tried to make a slightly more sophisticated version of this, where I don't have to hardcode the path. It works but I don't really like my code. It's a bit off-topic here, but do you mind telling me if that's good, style-wise?

```elisp
((python-mode . ((python-check-command . "pylint")
		 (eval . (pyvenv-activate (concat (let ((d (dir-locals-find-file ".")))
						    (if (stringp d) d (car d))) "env"))
		       ))))
```

I also have this slightly different version (I don't like the imbricated `let` but I prefer the fact that the `(pyenv-activate (concat root-dir "env"))` is clearer:

```elisp
((python-mode . ((python-check-command . "pylint")
		 (eval . (let ((root-dir (let ((d (dir-locals-find-file ".")))
					   (if (stringp d) d (car d)))))
			   (pyvenv-activate (concat root-dir "env")))
		       ))))
```

**Comment by galaunay** [comment]
I do find the last one more readable.
If you want to avoid imbricated `let`, you can use `let*` instead:
```Elisp
((python-mode . ((python-check-command . "pylint")
                 (eval . (let* ((dir (dir-locals-find-file "."))
                                (root-dir (if (stringp dir) dir (car dir))))
                           (pyvenv-activate (concat root-dir "env")))))))
```
it makes the symbol `dir` available during the evaluation of the `root-dir` form.

It is also considered good practice to use ` (concat (file-name-as-directory root-dir) "env")` to join path. Just in case `root-dir` doesn't end with a backslash.

Apart from that, I would not have done better.
Enjoy your Lisp adventure !

**Comment by little-dude** [comment]
Thanks for the tips, and for the encouragements @galaunay !

**Comment by rileyrg** [comment]
expand-file-name is the best way to expand a directory I think but otherwise thanks very much.
