### ISSUE TITLE
use-package configuration and autoloads [feature request]

### ISSUE THREAD

**Issue by Ergus** [jorgenschaefer/elpy#1566]
Hi:
I am trying to configure elpy to be autoloaded with use-package, but there is not a good method to defer it with the provided functions. 

The expected configuration should be something like:
```
(use-package elpy
  :hook (python-mode . elpy-enable))
```
But the problem is that the elpy-enable function sets many hooks inside, so the elpy-mode is not enabled with this method, because the hook is set after the mode is actually loaded. And loading elpy is slow due to tramp connections, virtualenvs and so on.

Loading elpy-enable in the init section works (as expected), but it makes emacs startup VERY slow even when not using python so it is not the right to do right now.

I made a workaround this, but this is not a proper solution because it does not have the tests you do in the function, does not use the functionalities you provide, and also it does not assert the right operation's order (specially elpy-modules-global-init before elpy-mode). 

```
(use-package elpy
  :hook ((python-mode . elpy-mode)
	   (pyvenv-post-activate-hooks . elpy-rpc--disconnect)
	   (inferior-python-mode-hook . elpy-shell--enable-output-filter))
  :config
  (elpy-modules-global-init)
  (define-key inferior-python-mode-map (kbd "C-c C-z") 'elpy-shell-switch-to-buffer)
  )
```
So please, could you provide any of the options bellow? 
1) some functions to autoload the elpy (lazily)
2) Or fix `elpy-enable` in order to make it autoloadable instead if loading everything in the call?
3) Or a documentation for the steps to follow to autoload it?  (Or an oficial example using use-package with bind, defer or equivaents)

Very thanks for the package ans sorry for bothering with this.
Ergus

**Comment by galaunay** [comment]
Hi, 

> I am trying to configure elpy to be autoloaded with use-package

You are right, it is quite difficult to do with the code as it is now.

One solution would be to advise python-mode for its first call:
``` Elisp
(defun enable-elpy-once ()
  (elpy-enable)
  (advice-remove 'python-mode 'enable-elpy-once))
(advice-add 'python-mode :before 'enable-elpy-once)
```
Would it work for you ?

**Comment by Ergus** [comment]
Hi @galaunay :

Yes your solution works for me. Maybe it is not a bad idea to consider it as a "more permanent" solution to recommend in the wiki page/ manual, and provide/recommend such a configuration (or the equivalent one with use-package) in the wikipage in order to not affect the global emacs startup time for other modes.

My actual working config is:
```
(use-package elpy
  :defer
  :init
  (defun enable-elpy-once ()
    (elpy-enable)
    (advice-remove 'python-mode 'enable-elpy-once))
  (advice-add 'python-mode :before 'enable-elpy-once)
  :config
  (setq python-shell-interpreter "jupyter"
	python-shell-interpreter-args "console --simple-prompt"
	python-shell-prompt-detect-failure-warning nil
	elpy-rpc-python-command "python3"
	python-check-command "pyflakes"
	flycheck-python-flake8-executable "flake8")
  (add-to-list 'python-shell-completion-native-disabled-interpreters "jupyter"))
```
So new users could find it in the wiki and will not try the first one I did, because it the "use-package" way.

**Comment by galaunay** [comment]
I like having Elpy loading at startup, so it does not slow anything down when I open my first python buffer.
So I am a bit reluctant to defer Elpy loading by default.

It is difficult (with my knowledge of `use-package`) to make Elpy respect the `:defer` statement.
But I updated the doc to indicate how to do it.

By the way, I made a small modification to ensure Elpy cannot be enabled twice.
This make deferring Elpy easier and the following line should be enough:
```Elisp
(advice-add 'python-mode :before 'elpy-enable)
```

**Comment by Ergus** [comment]
Hi:
  You could also remove the advice from within the function, so it won't be needed to do the hook call everytime. But that's a minor issue. With the new changes use-packages lines can be simplified this way:

```
(use-package elpy :ensure t
  :defer t
  :init
  (advice-add 'python-mode :before ''elpy-enable))
```

I think it is very important to provide a use-package ready to use configuration in the documentations, because it is the easiest way for new users to get a ready setup.

So if you could add a section with this config in the Readme and the documentation.

**Comment by galaunay** [comment]
Thanks for the highlighting this.
 I updated the instruction on both the readme and the documentation.

**Comment by aspiers** [comment]
Oh, just found it in https://github.com/jorgenschaefer/elpy/wiki/Configuration thanks to [this Stack Exchange answer](https://emacs.stackexchange.com/a/50757/2018).  It was not obvious to me that I should look there; IMHO this really belongs in the installation instructions.

**Comment by galaunay** [comment]
@aspiers The doc are up to date in the [sources](https://github.com/jorgenschaefer/elpy/blob/master/docs/introduction.rst), properly mentionning `use-package` as they should.

The problem is Elpy's readthedocs page is no automatically updated and only Jorgen can do it manually.
I tried to contact him a few month ago regarding that, without success.
I'll try again and fix that as soon as possible.

**Comment by aspiers** [comment]
Fantastic, thanks so much @galaunay!
