### ISSUE TITLE
how to pip install new packages in current project 

### ISSUE THREAD

**Issue by avocadoras** [jorgenschaefer/elpy#1568]
It's not clear to me from the documentation which is the usual workflow to install create new projects and install packages via `pip` into them. Once I run `python -m venv venv` in my directory, I can activate my project with `M-x pyvenv-activate`. However, how do I install packages in my current virtual environment? 

I have tried:

1. `M-x pyvenv-activate`
2. `M-x shell`
3. `pip install requests`

which this happens
`Error: bash: /path/to/my/venv//bin/pip: /path/to/my/venv/bin/python: bad interpreter: No such file or directory`

Which leaves me with the other option of opening up the terminal and activating my virtual environment and installing all of my  new packages with the terminal. 

So then, is Elpy use case mostly to activate a current project but the setup and install of packages should be done seperately in a terminal???

# My configuration
```elisp
(use-package python
    :mode ("\\.py\\'" . python-mode)
    :interpreter ("python" . python-mode)
    :config
    (progn (setq python-shell-interpreter "python")
	   (setq python-indent-offset 4)
	   (setq python-shell-completion-native-disabled-interpreters '("python")))

    ;; When using Emacs 24.1 on Mac OS X compiled via homebrew. The python-shell always used US-ASCII as encoding
    ;; To fix this
    (when (memq window-system '(mac ns x))
      (setenv "LC_CTYPE" "UTF-8")
      (setenv "LC_ALL" "en_US.UTF-8")
      (setenv "LANG" "en_US.UTF-8")))

  (use-package elpy
    :after python
    :ensure t
    :config
    (elpy-enable)
    (defalias 'workon 'pyvenv-workon)
    ;; (setq elpy-rpc-backend "jedi")
    ;; use flycheck instead of flymake
    (when (load "flycheck" t t)
      (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
      (add-hook 'elpy-mode-hook 'flycheck-mode)))

  (use-package pyvenv
    :after elpy)
```
## OS
macOS mojave

**Comment by galaunay** [comment]
> Once I run python -m venv venv

You can also create virtualenv using `M-x pyvenv-create`.

> which this happens
Error: bash: /path/to/my/venv//bin/pip: /path/to/my/venv/bin/python: bad interpreter: No such file or directory

It should work, is `/path/to/my/venv/bin/python` existing and a proper python shell ?

**Comment by avocadoras** [comment]
> You can also create virtualenvs using M-x pyvenv-create.

This is good to know.

 > Is /path/to/my/venv/bin/python existing and a proper python shell ?
1. `/path/to/my/venv/bin/python` yes, it exists. 
2.  Yes, it works now... not sure what happened before, I double checked by activating the environment and then `which python`, and I can see it pointing to `/path/to/my/venv/bin/python`.

My bad.
