### ISSUE TITLE
getting "Symbol's function definition is void: elpy-enable" with last dev version

### ISSUE THREAD

**Issue by pbgc** [jorgenschaefer/elpy#1572]
With last dev version in melpa ... I get "Symbol's function definition is void: elpy-enable"

I saw in this commit: https://github.com/jorgenschaefer/elpy/commit/d5e01fa484573a0b455998ed11cb7e199f78300c

the advice to use:

`(advice-add 'python-mode :before 'elpy-enable)`

but it not works for me. The way I got it working ... while getting faster emacs startup is:

`(advice-add 'python-mode :after 'elpy-mode)`

**Comment by galaunay** [comment]
> With last dev version in melpa ... I get "Symbol's function definition is void: elpy-enable"

Thank for reporting that, it was just a typo. It should be fixed by now.

> `(advice-add 'python-mode :after 'elpy-mode)`

This will not fully load Elpy, and you may end up having only partial support for virtualenvs, output echoing and company.
I strongly recommend `elpy-enable` instead of `elpy-mode`.

**Comment by pbgc** [comment]
Thanks! I'm currently afk but will try again asap.


I changed to elpy-mode because elpy-enable was giving error, but if it's fixed I will go back.

**Comment by Cerebus** [comment]
How long for this fix to propagate?

**Comment by Cerebus** [comment]
OK, weirdness--
(elpy-enable) --> void function
But, if I first run (elpy-config):
(elpy-enable) --> t

**Comment by Cerebus** [comment]
Functioning workaround:
Run (elpy-version) before (elpy-config)

**Comment by pooyataher** [comment]
Thank you, @Cerebus.  The following in my init file worked for now:
```
(elpy-version)
(elpy-enable)
```
But with (elpy-enable) alone in my init file, I still get the following error at emacs startup:
`Symbol's function definition is void: elpy-enable`

**Comment by Cerebus** [comment]
flake8 seems to not be working, but I was also shifting some configs from termux to crouton, so it's possible I broke something myself.

**Comment by galaunay** [comment]
@Cerebus, @pooyataher 
This is due to the `elpy-enable` autoload statement that disappeared at some point.
It should be fixed for elpy v20190414.2123.

**Comment by pbgc** [comment]
@galaunay I confirm that it's fixed.

**Comment by galaunay** [comment]
Thanks for the feedback.
I close this then.
