### ISSUE TITLE
error when byte compiling elpy-shell

### ISSUE THREAD

**Issue by hmelman** [jorgenschaefer/elpy#1576]
# Summary

I get this error when installing elpy from melpa:
elpy-shell.el:1205:34:Error: `add-to-list' can't use lexical var `bp-lines';
    use `push' or `cl-pushnew'

# My configuration

"GNU Emacs 26.2 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.6)
 of 2019-04-14"

**Comment by galaunay** [comment]
Thanks for that.
It escaped my attention.

It will be fixed by PR #1577.
