### ISSUE TITLE
elpy-config still tests for, and counsels to, install elpy with pip

### ISSUE THREAD

**Issue by ViktorHaag** [jorgenschaefer/elpy#1579]
# Summary

M-x elpy-config still detects for, and counsels to, install python elpy module; however, the module is no longer available on PyPi and was deleted as no longer needed (see issue referred to below).

# Steps to reproduce
- update elpy via package to ensure it's up to date (test with elpy elisp 1.29.1)
- M-x elpy config

# My configuration
## OS

MacOS 10.14.4

## Emacs version

GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.2.0, Carbon Version 158 AppKit 1671.2)
 of 2019-04-14

- installed via homebrew cask with the emacs-mac cask
```
emacs-mac: emacs-26.2-z-mac-7.6
https://bitbucket.org/mituharu/emacs-mac.git
/usr/local/Caskroom/emacs-mac/emacs-26.2-z-mac-7.6 (64B)
From: https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Casks/emacs-mac.rb
==> Name
Emacs-mac
==> Artifacts
Emacs.app (App)
/Applications/Emacs.app/Contents/MacOS/Emacs -> emacs (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/ebrowse (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/emacsclient (Binary)
/Applications/Emacs.app/Contents/MacOS/bin/etags (Binary)
```

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.7.3 (/usr/local/bin/python3)
Interactive Python: python3 (/usr/local/bin/python3)
Emacs.............: 26.2
Elpy..............: Not found (Python), 1.29.1 (Emacs Lisp)
Jedi..............: 0.13.3
Rope..............: Not found (0.14.0 available)
Autopep8..........: 1.4.4
Yapf..............: 0.27.0
Black.............: 19.3b0
Syntax checker....: flake8 (/usr/local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is often a
good idea to work inside a virtual env. You can use M-x pyvenv-activate or M-x
pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables in that
directory, so Emacs won't find them. If you are missing some commands, do add
this directory to your PATH -- and then do `elpy-rpc-restart'.

The Python interpreter could not find the elpy module. Make sure the module is
installed.

[run] python3 -m pip install --user elpy

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button to
invoke its action.  Invoke [+] to expand a group, and [-] to collapse an
expanded group.  Invoke the [Group], [Face], and [Option] buttons below to edit
that item in another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[+]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[+]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
[+]-- Group Django extension
[+]-- Group Autodoc extension

```

## Elpy configuration in my init.el
```
(starter-kit-install-if-needed 'elpy 'flycheck 'py-autopep8 'py-yapf)
(elpy-enable)
(setq elpy-rpc-python-command "python3")
(setq elpy-modules '(elpy-module-company
                     elpy-module-eldoc
                     elpy-module-pyvenv
                     elpy-module-yasnippet
                     elpy-module-sane-defaults))
(require 'py-yapf)
(setq elpy-rpc-timeout 10)
```

# See also
Change of maintainership issue that mentions python elpy module no longer needed and [decision taken to delete it from PyPi](https://github.com/jorgenschaefer/elpy/issues/1523)

**Comment by rakanalh** [comment]
I haven't been following updates on the project recently... but is elpy completely elisp now?

**Comment by galaunay** [comment]
@rakanalh 
Elpy still have a big chunk of python.
 But the the Elpy Emacs package now comes with a copy of the Elpy python module (you can find it in `~/.emacs/elpa/elpyVERSION/elpy` or similar).

What Elpy does is adding the Elpy python package location to PYTHONPATH before launching the RPC.
It is simpler from the user point of view (when it works...) and avoid version mismatch between lisp and python code.

@ViktorHaag
 I will fix the message display.
However, Elpy doesn't seem to be able to find the Elpy python module in your case.
I would suggest a full re-installation of Elpy from melpa (as a first try).
If it is not enough, what is the value of `PYTHONPATH` return by `(elpy-rpc--environment)` ?

**Comment by ViktorHaag** [comment]
@galaunay Thanks; it appears that after removing the Python module and re-installing the elpy package in Emacs, `emacs-confg` now reports like this, so I assume things are OK:
```
...
Elpy..............: 1.29.1
...
```

**Comment by galaunay** [comment]
Good, I assume I can close this then.
A collateral dommage of removing Elpy from Pypi I am afraid, sorry about the trouble.
