### ISSUE TITLE
Emacs 2.61, getting a big block of code every time I run C-c C-c

### ISSUE THREAD

**Issue by lumogas** [jorgenschaefer/elpy#1582]
# Summary
I've updated to emacs 2.61 on Windows 7. I was running into the "no readline module" problem, detailed here:
https://github.com/jorgenschaefer/elpy/issues/887
I solved it by installing pyreadline 2.1:
https://pypi.org/project/pyreadline/
But now I get a big chunk of text every time I rund C-c C-c:

![python_problem_demo](https://user-images.githubusercontent.com/19858683/56378855-4764d280-61dc-11e9-886d-be5be3adfcfb.jpg)

What can I do to make that disappear? I didn't have that issue with the earlier version of emacs. My python shell is set to Python 2.7

# My configuration
## OS
Windows 7 32 bit

## Result of `(elpy-config)`
```
Neither easy_install nor pip found
```

## Elpy configuration in my init.el
```
(add-to-list 'package-archives
             '("elpy" . "http://jorgenschaefer.github.io/packages/"))
```

**Comment by galaunay** [comment]
I think it is reminiscent of a bad commit I merged two weeks ago.
It has been reverted so you should be alright by updating Elpy to 1.29.1.

In the case it is due to something else, a temporary workaround would be to set `elpy-shell-echo-output` to `nil`.

**Comment by lumogas** [comment]
Yup, thanks! That fixed it.
