### ISSUE TITLE
Elpy package got deleted from pypi.org?

### ISSUE THREAD

**Issue by xelibrion** [jorgenschaefer/elpy#1583]
Pypi.org returns 404 when requesting https://pypi.org/project/elpy/ as I type, I am also unable to install `elpy` package via `pip`.

Would you happen to know what is happening @jorgenschaefer?

**Comment by galaunay** [comment]
The elpy python package is not needed anymore.
It is now shipped with Elpy, so you don't need to install it explicitly.

**Comment by jboning** [comment]
I just encountered an issue where `elpy` had leaked into a project's `requirements.txt`, and its absence from pypi caused a build issue. I'm surely not alone. I've fixed my own dependency, but would you consider restoring the old packages onto pypi for the sake of unbreaking other projects?

**Comment by gopar** [comment]
@jboning Hey, kinda odd that elpy ended up in a projects `requirements.txt` (since it's only for emacs). Packages that are specific to a persons workflow shouldn't be in there :)

Any who, I don't think elpy will end up again in pypi since it's really outdated. If enough people become verbal about it then it might be good to put it back. @galaunay thoughts?

**Comment by tacaswell** [comment]
Putting up a tombstone project that installs but does nothing in probably a good idea, if for no other reason than to make sure someone does not put a malicious package up in it's place.

**Comment by jboning** [comment]
I went ahead and posted an empty package at https://pypi.org/project/elpy/ so no one else can, though it probably still breaks dependencies for requirements.txt files created with `pip freeze`.

**Comment by galaunay** [comment]
@jboning thanks for that.

The Pypi package has been useless for quite some time now, we had no idea it would create so much troubles to remove it.

**Comment by tacaswell** [comment]
https://xkcd.com/1172/  :angel:

**Comment by costrouc** [comment]
Why was this package dropped? This was fixed with this PR https://github.com/NixOS/nixpkgs/pull/67518

**Comment by doolio** [comment]
If `elpy` is no longer (really) available on PYPI is there any need for the `setup.py` and `setup.cfg` files in this repository?
