### ISSUE TITLE
elpy-config is extremely slow

### ISSUE THREAD

**Issue by mbtuckersimm** [jorgenschaefer/elpy#1584]
# Summary

`elpy-config` is extremely slow, to the point where I've given up. I've done some investigation (detailed below) and it seems that the issue is in contacting the pypi server, despite the fact that I have a quite fast internet connection.

Even though the underlying problem is likely not with `elpy`, I'm stuck as to how to fix it, so I'm filing this issue and hoping for some help.

# Steps to reproduce

1. Load a file in a python project.
2. Activate virtualenv with `M-x pyvenv-activate`.
3. `M-x elpy-config`
4. Wait... 

# My configuration

OS: Ubuntu 16.04
Emacs: 26.1
elpy: 20190416.1701 (melpa)

# Result of `(elpy-config)`
Unavailable since `elpy-config` never completes (well, I run out of patience).

## Elpy configuration in my init.el
```
(use-package elpy
  :config
  (elpy-enable)
  (setenv "WORKON_HOME" "~/.pyenv/versions/")
  ;; disable flymake since we use flycheck instead
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  :ensure t)
```

# What I've tried so far

I was playing around in an ipython shell (within the relevant virtual environment) with the python code that's called during `elpy-config`:
1. Import `json`, `sys`, and `warnings`.
2. `import xmlrpc.client as xmlrpclib`
3. Define the function `latest`:
```
def latest(package, version=None):
    try:
        with xmlrpclib.ServerProxy('https://pypi.python.org/pypi') as pypi:
            latest = pypi.package_releases(package)[0]
        if version is None or LooseVersion(version) < LooseVersion(latest):
            return latest
        else:
            return None
    except:
        return None
```
4. `import timeit`
5. `timeit.timeit("latest('jedi')", setup='from __main__ import latest', number=1)`
6. Result is `524.0016240759978`.

So it takes almost 9 minutes to do this operation for just a single package! (The `latest` function does come up with the correct latest version of jedi, 0.13.3 at the time of filing this issue, FWIW.)

**Comment by mbtuckersimm** [comment]
I should mention that this is on a desktop computer, so it's not easy to try this with a different internet connection :(

**Comment by gopar** [comment]
Yups, I see the same results. Might be better to switch to the new json api that pypi provides. Now that warehouse(New version of pypi) is live

Note to self: 
Warehouse docs: https://warehouse.pypa.io/api-reference/json/

**Comment by gopar** [comment]
@mbtuckersimm PR peding. See #1585

**Comment by mbtuckersimm** [comment]
@gopar Thanks for your work on this, much appreciated!

**Comment by yangdaweihit** [comment]
I also come to this problem and my config is as such:
```
Emacs.............: 26.1
Elpy..............: 1.32.0
Virtualenv........: myenv (/home/wall-e/.virtualenv/myenv)
Interactive Python: jupyter 4.6.2 (/home/wall-e/.virtualenv/myenv/bin/jupyter)
RPC virtualenv....: rpc-venv (/home/wall-e/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.7.6 (/home/wall-e/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: 0.16.0
 Rope.............: 0.16.0
 Autopep8.........: 1.5
 Yapf.............: 0.29.0
 Black............: 19.10b0
Syntax checker....: flake8 (/home/wall-e/.virtualenv/myenv/bin/flake8)

```

When I load `elpy-config`, it takes long logne time. Please give me a detailed guide to resolve tis problem.
