### ISSUE TITLE
auto completion gets wrong type

### ISSUE THREAD

**Issue by kong13661** [jorgenschaefer/elpy#1587]
Auto completion gets wrong type. For example, I import `numpy` module, and I type `np.`. The first candidate is abs, and it should be a function, but elpy considers it's a module. It seems because `abs` has been imported in `__init__.py` file, and elpy won't track the definition. I also use `company-quickhelp `package, and because of this problem, it won't show me doc since module has no document. 
I don't know if it is a feature, because it seems efficient when first comlpetion. But I notice jedi has cache. Is there any way to solve it?

**Comment by gopar** [comment]
This is a Jedi issue. Elpy only provides out of the box configuration. Jedi provides the auto completion candidates
