### ISSUE TITLE
Running different bins of python

### ISSUE THREAD

**Issue by JurijsNazarovs** [jorgenschaefer/elpy#1590]
Hello,

I am trying to make following work, but not sure how. I have a personal computer, where python3 is located in /usr/bin/python3 . Then i put  in my .emacs file following lines:

```
(setq elpy-rpc-python-command " /usr/bin/python3")
(setq python-shell-interpreter " /usr/bin/python3")
````

and everything works fine on my pc if I do C-c, C-c.

However, I have to work on some python files in remote server, so I have to open file in emacs using C-x, C-f, /ssh:.... . The problem is that python3 on the remote server is not in  /usr/bin/python3. Thus, C-c, C-c doesn't to work.

I tried to add the following lines:
```
(setq elpy-rpc-python-command " python3")
(setq python-shell-interpreter " python3")
````
and make an alias for python3 command in the server in .bash_profile, but emacs still not picking it up.

So, could you recommend the way I deal with this situation that no matter where I press C-c, C-c and run a right version of python3.

**Comment by galaunay** [comment]
Hi, 

With the following configuration:
```Python
(setq elpy-rpc-python-command "python3")
(setq python-shell-interpreter "python3")
```
Elpy will use the first executable named `python3` that it will found in your PATH.

So to get what you want, I would add the folder where your python3 binaries is to the PATH.
Something like this in your `.bash_profile` should do:
``` bash
PATH=/path/to/python/binaries:$PATH
```

(on your personal computer it shouldn't be needed, as `/usr/bin` should already be in your PATH.)

**Comment by JurijsNazarovs** [comment]
Hello, thanks for your reply. However, I have added the path to the binary in .bash_profile, or .profile, or .bash_rc and none of that helped. Namely, if i ssh using terminal, then python3 does what it needs to do. But it seems like emacs does not read any of these files when I connect to server using C-x,C-f and ssh.

**Comment by gopar** [comment]
Hey, 

Elpy doesn't work with remote files :(

See #276

**Comment by galaunay** [comment]
@gopar I just tries and it works (at least for me :) ). I think the main problem was dealing with jedi and rope because the rpc is run locally.

@JurijsNazarovs Strange, tramp should read your .profile on connection...
The tramp [doc](https://github.com/jorgenschaefer/elpy/issues/1590) mention something that you could use:

> Tramp starts a remote process when a command is executed in a remote file or directory buffer. As of now, these packages have been integrated to work with Tramp: compile.el (commands like compile and grep) and gud.el (gdb or perldb).
> 
> For Tramp to find the command on the remote, it must be accessible through the default search path as setup by Tramp upon first connection. Alternatively, use an absolute path or extend tramp-remote-path (see Remote programs):
>
>     (add-to-list 'tramp-remote-path "~/bin")
>     (add-to-list 'tramp-remote-path "/appli/pub/bin")

Is it better with `(add-to-list 'tramp-remote-path "/path/to/python/binaries")`?

ps: As @gopar said, Elpy's completion and documentation may not work properly on a remote server

**Comment by JurijsNazarovs** [comment]
@galaunay 

Thanks, but it did not help.

**Comment by galaunay** [comment]
I am afraid it is more related to Tramp than Elpy, I am running out of ideas.

You could still specify the python interpreter per file, using 
```Elisp
# -*- python-shell-interpreter: /path/to/python3; elpy-rpc-python-command: /path/to/python3; -*-
``` 
at the beginning of you scripts on your remote machine, or
```Elisp
# Local Variables:
# python-shell-interpreter: /path/to/python3
# elpy-rpc-python-command: /path/to/python3
# End:
```
at the end.

**Comment by galaunay** [comment]
Please re-open if we can do more about this.
