### ISSUE TITLE
elpy-nav-move-line-up/down binds to ESC up/down

### ISSUE THREAD

**Issue by kirk86** [jorgenschaefer/elpy#1597]
# Summary
`M-up/down` doesn't work on OSX seems to be binding to `ESC up/down`

# My configuration
## Result of `(elpy-config)`
```
Virtualenv........: None                                                                                                                                       
RPC Python........: 3.7.3 (/home/user/miniconda3/bin/python3)                                                                                                   
Interactive Python: python (/home/user/miniconda3/bin/python)                                                                                                       
Emacs.............: 26.2                                                                                                                                           
Elpy..............: 1.29.1                                                                                                                       
Jedi..............: 0.13.3                                                                                                                                  
Rope..............: 0.14.0                                                                                                                                       
Autopep8..........: 1.4.4                                                                                                                                          
Yapf..............: Not found (0.27.0 available)                                                                                                                   
Syntax checker....: flake8 (/home/user/miniconda3/bin/flake8)
```

## Elpy configuration in my init.el
```
default/ no changes
```

**Comment by galaunay** [comment]
I think ESC maps to Meta by default on MacOS.

Would [this page](https://www.emacswiki.org/emacs/MetaKeyProblems#toc17) of the doc helps ?

**Comment by kirk86** [comment]
@galaunay thanks fort the reply. 
I think it doesn't it's not that because `M-x` works perfectly fine.

**Comment by galaunay** [comment]
So if I understand correctly it is only for Elpy and only for `M-up` and `M-down`.

Could you check what is bound to `M-up` ?
(with `C-h k M-up` or similar).

**Comment by kirk86** [comment]
> So if I understand correctly it is only for Elpy and only for `M-up` and `M-down`

Exactly.

Upon key description I keep getting:
```
ESC <up> (translated from ESC M-[ A) is undefined
```

**Comment by galaunay** [comment]
Are you using Emacs from a terminal ?

I found a [post](https://stackoverflow.com/questions/4548106/screen-somehow-unmaps-my-arrow-keys-in-emacs-after-a-z) that may be related to your problem if it is the case.

**Comment by kirk86** [comment]
@galaunay thanks a lot, yeah that's true I'm using emacs on a terminal.
Funny thing is that I just checked on my linux box and everything works fine, it might have to do sth similar to the post you linked to, with either the OSX in this instance or the terminal or both. I'll further investigate and report back any findings.

**Comment by galaunay** [comment]
I am cleaning issues. Please re-open if there is still something wrong.
