### ISSUE TITLE
Cannot install elpy

### ISSUE THREAD

**Issue by triplrrr** [jorgenschaefer/elpy#1601]
I have been unable to install elpy to my emacs installation. I tried to install it and I got the following result. 
```
Contacting host: melpa.org:80
package-install-from-archive: http://melpa.org/packages/yasnippet-20190423.206.el: Not found
```

I have not tried to reproduce on other machines, but I have been so far unable to install on my machine regardless of a restart of emacs, refreshing my package list, or a restart of my machine. 

My config is [here](https://pastebin.com/TKYLLMYu). I am running Kubuntu 18.10 with KDE. My Emacs version is Emacs 25.2.2. 

`(elpy-config)` gave the following result
```
eval: Symbol’s function definition is void: elpy-config
```
There is no config for elpy in my `~/.emacs` file.

**Comment by gopar** [comment]
Looks like one of the dependencies for elpy is missing from the melpa repository.
`yasnippet-x.y.el: Not Found`

Note to self: Looks like we might have to bump the yasnippet version? verified that it's not on the melpa repo anymore. 🤔

**Comment by sten0** [comment]
@gopar this sounds like a transient MELPA bug.  eg, the following links appear to be valid:
  https://melpa.org/packages/yasnippet-20190502.2214.el
  https://stable.melpa.org/packages/yasnippet-0.13.0.el
@triplrrr, you don't need to use yasnippet from MELPA, because cosmic has 0.13.0.  `sudo apt install elpa-yasnippet`

**Comment by triplrrr** [comment]
@sten0 thanks, but now I get a different error message
```
package-install-from-archive: https://melpa.org/packages/ivy-20190516.1513.tar: Not found
```

**Comment by galaunay** [comment]
Elpy doesn't require `ivy`, so it shouldn't prevent elpy to work.

However you do seem to have a problem with package management.
Would running this help ?
```Elisp
(package-initialize)
(package-refresh-contents)
(package-install 'ivy)
```

**Comment by azzamsa** [comment]
@triplrrr is this problem persists ?

**Comment by olishmollie** [comment]
I encountered this issue also. Solved it with "M-x package-install RET elpy RET". So for me, I only got the ya-snippet error through use-package's :ensure directive. Maybe the bug lies there?

**Comment by nackjicholson** [comment]
@azzamsa Yes this problem still persists. I get the same thing using `M-x package-install RET elpy RET` as well.

```
package-install-from-archive: http://melpa.org/packages/yasnippet-20190630.1720.el: Not found
```

**Comment by nackjicholson** [comment]
@galaunay Help! I noticed you were able to merge #1613 to fix a similar problem. Could you do that again to use the current version of yasnippet on melpa?

**Comment by galaunay** [comment]
I updated Yasnippet version during the same commit, so it should be alright.

Your Emacs is trying to download a version of yasnippet (`20190630.1720`) that is not on Melpa's server anymore (the current version is `20190724.1204`).

Emacs should automatically refresh the package list before installing any package.
For you, it is apparently not happening...
You can force Emacs to do it with `M-x package-refresh-contents`.
Is it running properly (without errors in `*Messages*`) ?

**Comment by galaunay** [comment]
I hope this is fixed now, please re-open if not.
