### ISSUE TITLE
Problems using Jupyter

### ISSUE THREAD

**Issue by arnyeinstein** [jorgenschaefer/elpy#1604]
# Summary

When I use Jupyter from my winPython installation (after removing Anaconda) in elpy, I run into following problem:

[ZMQTerminalIPythonApp] ERROR | Failed to run command:
['C:\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\renge\\AppData\\Roaming\\jupyter\\runtime\\kernel-13892.json']

I checked if there was still a "rest" of Anaconda anywhere (registry, search for string "anaconda" in files), but couldn't find any. If I use the python console, everything is fine.
I can run Jupyter from a dos window.

Cheers
Renger

# Steps to reproduce
Installed Anacode 3.7, worked with Jupyter in elpy, installed wxPython, removed anaconda, problem appeared in elpy

# My configuration
## Result of `(elpy-config)`
Virtualenv........: None
RPC Python........: 3.6.8 (c:/WPy36/python-3.6.8.amd64/pythonw.exe)
Interactive Python: jupyter (c:/WPy36/python-3.6.8.amd64/Scripts/jupyter.exe)
Emacs.............: 26.1
Elpy..............: 1.30.0
Jedi..............: 0.13.3
Rope..............: 0.12.0
Autopep8..........: 1.4.4
Yapf..............: 0.27.0
Black.............: 19.3b0
Syntax checker....: flake8.exe (c:/WPy36/python-3.6.8.amd64/Scripts/flake8.exe)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

## Elpy configuration in my init.el
(elpy-enable)

(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))

(add-hook 'inferior-python-mode-hook 'visual-line-mode)
(define-key elpy-mode-map (kbd "C-x C-n") 'elpy-shell-send-group-and-step)

 (setq python-shell-interpreter "jupyter"
 python-shell-interpreter-args "console --simple-prompt"
python-shell-prompt-detect-failure-warning nil)
 (add-to-list 'python-shell-completion-native-disabled-interpreters
 "jupyter")

```

**Comment by galaunay** [comment]
I think you are right and the path to the old anaconda binaries is still remaining in some config files.
Have you check the Jupyter configuration files in `%PROGRAMDATA%\jupyter\` ?

You can also list the (potential) other jupyter config directories with `jupyter --paths`. 
It may give you some indication about where to look for.

If it happens only in Emacs, it may be due to some environment variables being set improperly.
You can check Emacs environment variables with `M-x describe-variable RET process-environment`.

Hope it helps.

**Comment by arnyeinstein** [comment]
Thanks. I finally found the culprit: There were some old folders "/jupyter/kernels/python3" left on my computer. So nothing to do with elpy. I don't know if somebody can delete this thread as?
Cheers
Renger
