### ISSUE TITLE
That's split screen trick is  exactly what I'm looking to do. Can you run it by me a little slower? Or write the instructions in the comments?

### ISSUE THREAD

**Issue by davidjayjackson** [jorgenschaefer/elpy#1607]
# Summary

Thank you for reporting to Elpy !

Here is a template to help you do it so your issue can be fixed as
soon as possible. Please replace this paragraph with a summary of
your issue and fill the next sections.

# Steps to reproduce

# My configuration
## Result of `(elpy-config)`
```
# Paste it here
```

## Elpy configuration in my init.el
```
# Paste it here
```

**Comment by galaunay** [comment]
bit of context ?

**Comment by davidjayjackson** [comment]
Here you go:
https://youtu.be/D20CgRjDuX4

**Comment by galaunay** [comment]
From a python buffer with Elpy enabled, the command you are looking for is `elpy-shell-switch-to-shell`, which is bound to `C-c C-z` by default.

If you want to know a bit more about what you can do in Elpy with python shells, I recommend [this section](https://elpy.readthedocs.io/en/latest/ide.html#the-shell-buffer) of the documentation.
Elpy's [quickstart](https://github.com/jorgenschaefer/elpy/blob/master/docs/quickstart.rst) may be useful for you as well.

**Comment by davidjayjackson** [comment]
Jorgen,
Thanks for the commands, and the link to the manual.

David
