### ISSUE TITLE
Cannot install from melpa

### ISSUE THREAD

**Issue by abeluck** [jorgenschaefer/elpy#1612]
# Summary

elpy is not installable due to a missing package on melpa.

Looks like it was updated to a new version:

https://melpa.org/#/find-file-in-project

20190602.1042

# My configuration
## OS

Debian, emacs 25

## init.el
```
(use-package elpy
  :ensure t
  :defer t
  :init
  (advice-add 'python-mode :before 'elpy-enable))
```

## Error on startup
```
Error (use-package): Failed to install elpy: https://melpa.org/packages/find-file-in-project-20190408.325.el: Not found
```

**Comment by galaunay** [comment]
Thanks for reporting this.

I updated Elpy dependencies in #1613.
Hopefully it should be fixed by now.

**Comment by abeluck** [comment]
It is working for me now, thanks.

**Comment by NoahDragon** [comment]
Got the same issue today, but worked this afternoon.

**Comment by galaunay** [comment]
I am closing this then, 
feel free to re-open if the issue comes up again.

**Comment by dadudeme** [comment]
I believe this has happened again:
`Error (use-package): Failed to install elpy: https://melpa.org/packages/yasnippet-20250112.1504.tar: Not found`

with use-package instructions:
'     (use-package elpy
       :ensure t
       :init
       (elpy-enable))'
