### ISSUE TITLE
Completion and code navigation stopped working on last melpa dev release

### ISSUE THREAD

**Issue by pbgc** [jorgenschaefer/elpy#1614]
Hi,

After installing last dev release on melpa Completion and code navigation stopped working.

I see on the configure option that it's said:

Jedi..............: Not found (0.14.0 available)

The jedi package is not available. Completion and code navigation will
not work.

[run] ~/Development/emacs_vv3/bin/python3 -m pip install jedi

I already have jedi installed (already was and everything working great)! And even if I choose [run] I'm told that!

thanks!

Pedro Costa

![Captura de ecrã 2019-06-26, às 11 06 48](https://user-images.githubusercontent.com/180825/60171471-96456e80-9802-11e9-8eca-7ea9cf6af78f.png)
![Captura de ecrã 2019-06-26, às 11 06 56](https://user-images.githubusercontent.com/180825/60171483-99405f00-9802-11e9-8bd0-342e27a8fed4.png)

**Comment by pbgc** [comment]
I uninstalled Jedi and parso and installed again and now it works

Jedi just needs parso >=0.3.0 and I had 0.3.1 ....  but it seems that now elpy only works with jedi if parso is 0.5.0 ..

It seems like a bug to me ... but I will close the issue.

**Comment by galaunay** [comment]
Hi, 
thanks for reporting.

I couldn't make jedi 0.14 work at all with parso <0.5.
It has been reported to jedi already, see this [issue](https://github.com/davidhalter/jedi/issues/1348).
