### ISSUE TITLE
elpy spawns a lot of of jedi processes?

### ISSUE THREAD

**Issue by avkoval** [jorgenschaefer/elpy#1619]
# Summary

I've found that on this workplace I have a lot of processes spawned by elpy, and the number grows over time. Here is image (it can't fit the screen):

![](http://scr.ua2web.com/avk/ss_20190714182205_0ULZdq4DEAJVyU4tUyUj.png)

Process count: 391 (this is since morning, I've worked several hours today)

# Steps to reproduce

I am just working with some python files as usually and see that this happens.

# My configuration
## OS

Linux 5.1.15-arch1-1-ARCH #1

## Result of `(elpy-config)`
```
Virtualenv........:  (/home/k/yp/default/env/)
RPC Python........: 2.7.16 (/home/k/yp/default/env/bin/python)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 27.0.50
Elpy..............: 1.30.0
Jedi..............: 0.13.2 (0.14.1 available)
Rope..............: 0.11.0 (0.14.0 available)
Autopep8..........: 1.4.3 (1.4.4 available)
Yapf..............: 0.26.0 (0.28.0 available)
Black.............: Not found (19.3b0 available)
Syntax checker....: pylint (/home/k/yp/default/env/bin/pylint)
```

## Elpy configuration in my init.el
```
 from .emacs:
 '(elpy-eldoc-show-current-function nil)
 '(elpy-modules
   '(elpy-module-company elpy-module-eldoc elpy-module-pyvenv elpy-module-yasnippet elpy-module-sane-defaults))
 '(elpy-project-root-finder-functions
   '(elpy-project-find-projectile-root elpy-project-find-git-root elpy-project-find-hg-root))
 '(elpy-rpc-backend "jedi" t)
 '(elpy-rpc-python-command "python")
 '(elpy-syntax-check-command "pylint")

 from config.el:

   (use-package elpy
    :commands elpy-enable
    :init (run-with-idle-timer 10 nil #'elpy-enable)
    :config
    (progn
      (setq elpy-rpc-backend "jedi"
            elpy-rpc-project-specific 't)
      (when (fboundp 'flycheck-mode)
        (setq elpy-modules (delete 'elpy-module-flymake elpy-modules)))))


```

**Comment by avkoval** [comment]
Any hints? How can I help debugging it?

**Comment by galaunay** [comment]
It has been reported in #1481 and it seems to be linked to jedi and virtualenv.
The reason for this has not been found so far.

You can try updating jedi to the last version (0.14.1).
You can also try making a fresh venv.
If nothing works, you may found some useful information to help debug this in #1481.

I am closing this, but we can continue in #1481.
