### ISSUE TITLE
Emacs 26 warnings and a failing/flaky tests

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1620]
Hi @galaunay,

When I built/packaged e61540b today against 26.1 I noticed numerous `Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)`, plus flaky/failing `elpy-pdb-debug-buffer-should-enter-pdb` and `elpy-pdb-debug-last-exception-should-ignore-breakpoints`.  should-enter-pdb failed on the first build, should-ignore-breakpoints failed on the second, and neither failed on the third build.  If I had to guess I'd guess that it's timing-sensitive flakiness.

P.S. I'm investigating the possibility of enabling a Emacs 26.1 CI via a Debian 10 builder that is compatible with a travis-ci.com subscription.  'just need to confirm if it's appropriate for upstream projects :-)

Cheers,
Nicholas

**Comment by galaunay** [comment]
Hi @sten0,

For `elpy-pdb-debug-*` tests, there is indeed a hard-coded maximum waiting time [here](https://github.com/jorgenschaefer/elpy/blob/master/test/test-helper.el#L132)  (of 10s).
As it is a 'maximum' waiting time, it can be increased if necessary.

For Flymake errors, I get those as well. Apparently just flymake telling us that it will only use the `python-mode` flymake backend, and not the legacy flymake backend. Flymake still works perfectly.
It is more related to flymake and python-mode, as It also happens without Elpy activated.

> P.S. I'm investigating the possibility of enabling a Emacs 26.1 CI via a Debian 10 builder that is compatible with a travis-ci.com subscription. 'just need to confirm if it's appropriate for upstream projects :-)

Would this mean a CI for Elpy on debian ?

Gaby.

**Comment by sten0** [comment]
Hi @galaunay,

Thanks for the tip about the `elpy-pdb-debug-*` tests.  I'll experiment with larger values to see if that does the trick.

Weird, I'm surprised upstream Emacs didn't modify python-mode to use the new flymake...  'hopefully a fix will appear in a future 26.x release! :-)

> > P.S. I'm investigating the possibility of enabling a Emacs 26.1 CI via a Debian 10 builder that is compatible with a travis-ci.com subscription. 'just need to confirm if it's appropriate for upstream projects :-)
> 
> Would this mean a CI for Elpy on debian ?

As a side-effect, yes, but my primary motivation is just to be able to CI against something that newer than three years old.  From what I can tell, this would require adding a solution based on the following method https://docs.travis-ci.com/user/docker.  Sound interesting?  If I were to work on it I'd probably follow the following doc, minus the logic to push to DockerHub, because's that's not necessary for Elpy AFAICT: https://giorgos.sealabs.net/build-and-test-against-docker-images-in-travis.html

**Comment by sten0** [comment]
I'm about to give patching the `elpy-pdb-debug-*` hardcoded timeout a try.  For the record, here is the backtrace:
```elisp
Shell native completion is enabled.
   passed  199/387  elpy-pdb-debug-buffer-should-stop-at-the-first-breakpoint
Can’t guess python-indent-offset, using defaults: 4
Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Can’t guess python-indent-offset, using defaults: 4
Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Sent: def foo(a):...
Shell native completion is enabled.
Can’t guess python-indent-offset, using defaults: 4
Sent: def foo(a):...
   passed  200/387  elpy-pdb-debug-last-exception-should-debug-last-exception
Can’t guess python-indent-offset, using defaults: 4
Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Can’t guess python-indent-offset, using defaults: 4
Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Warning [flymake test.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Sent: def foo(a):...
Test elpy-pdb-debug-last-exception-should-ignore-breakpoints backtrace:
  #f(compiled-function (proc event) #<bytecode 0x1330c29>)(#<process p
  accept-process-output(#<process Python> 1.0)
  python-shell-accept-process-output(#<process Python> 1.0)
  python-shell-completion-native-setup()
  python-shell-completion-native-turn-on-maybe(t)
  python-shell-completion-native-turn-on-maybe-with-msg()
  run-hooks(python-shell-first-prompt-hook)
  python-shell-comint-watch-for-first-prompt-output-filter("Python 3.7
  run-hook-with-args(python-shell-comint-watch-for-first-prompt-output
  comint-output-filter(#<process Python> "Python 3.7.4 (default, Jul 1
  sleep-for(0.1)
  (while (and (if (boundp 'python-shell--first-prompt-received) (progn
  (let ((cumtime 0)) (while (and (if (boundp 'python-shell--first-prom
  (save-current-buffer (set-buffer (process-buffer (elpy-shell-get-or-
  elpy-shell--ensure-shell-running()
  (let* ((process (elpy-shell--ensure-shell-running)) (process-buf (pr
  (progn (fset 'python-shell-send-file vnew) (let* ((process (elpy-she
  (unwind-protect (progn (fset 'python-shell-send-file vnew) (let* ((p
  (let* ((vnew (if elpy-shell-echo-output (symbol-function 'elpy-shell
  elpy-shell-send-region-or-buffer-and-step(nil)
  (save-excursion (deactivate-mark) (elpy-shell-send-region-or-buffer-
  (unwind-protect (save-excursion (deactivate-mark) (elpy-shell-send-r
  (let ((saved-marker (save-mark-and-excursion--save))) (unwind-protec
  (let ((p)) (let ((saved-marker (save-mark-and-excursion--save))) (un
  elpy-shell-send-buffer-and-step(nil)
  funcall-interactively(elpy-shell-send-buffer-and-step nil)
  call-interactively(elpy-shell-send-buffer-and-step)
  (let ((orig (point))) (setq current-prefix-arg my-prefix-arg) (call-
  elpy-shell--send-with-step-go(elpy-shell-send-buffer-and-step nil ni
  elpy-shell-send-buffer()
  (progn (find-file (f-join project-root "test.py")) (python-mode) (el
  (progn (elpy-testcase-create-files project-root '("test.py")) (progn
  (unwind-protect (progn (elpy-testcase-create-files project-root '("t
  (let ((project-root (make-temp-file "elpy-test-" t))) (unwind-protec
  (progn (setq elpy-rpc-timeout 100) (let ((project-root (make-temp-fi
  (unwind-protect (progn (setq elpy-rpc-timeout 100) (let ((project-ro
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-b
  (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-cu
  (unwind-protect (progn (let ((temp-buffer (generate-new-buffer " *te
  (let ((old-process-list (process-list)) (old-buffer-list (buffer-lis
  (lambda nil (let ((old-process-list (process-list)) (old-buffer-list
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name elpy-pdb-debug-last-exception-should-
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test 
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  eval((ert-run-tests-batch-and-exit))
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
  command-line()
  normal-top-level()
Test elpy-pdb-debug-last-exception-should-ignore-breakpoints condition:
    (error "Selecting deleted buffer")
   FAILED  201/387  elpy-pdb-debug-last-exception-should-ignore-breakpoints
```

**Comment by galaunay** [comment]
I ran into similar errors when working on #1548.
Very annoying and difficult to trace, as it seems to happen in a sentinel of a filter.
I will post something here if I can find a proper explanation for this.
Please tell me if changing the timeout helps.

**Comment by sten0** [comment]
Hi @galaunay!

Yes, changing the timeout appears to help.  Of course we won't know for sure until 50 to 100 iterations have passed.  In the past, the average rate of failure over 100 tests is 3% (When I see a failure I run the tests on my local CI testbed in a loop of 100 builds).

https://ci.debian.net/packages/e/elpy/unstable/amd64/

As for a way to debug this further: maybe the tests can be run with `benchmark.el` (built-in)?  I haven't investigate the where and how of this, but this seems to be the most obvious way to identify where the stalls are occurring.

Cheers!
Nicholas

**Comment by sten0** [comment]
Ok, we have 100 CI runs in Debian now.  96 for b929013, and 4 for 8adc427.  (Cask and travis are not used in these tests)  All have passed!  I've also confirmed the simple cases of running tests in a loop on a real system, in a chroot, and in an LXC--all of these were experiencing sporadic failures previously.

Given that setting max-wait to 20 in test-helper.el and setting elpy-rpc-timeout to 20 globally (overridden to 100 in some places by test-helper.el IIRC), I think the next step to modify every test so it runs with `benchmark-run` or `benchmark-run-compiled`; that will "Return a list of the total elapsed time for execution, the number of garbage collections that ran, and the time taken by garbage collection."  To be fair, it's possible an upstream garbage collection bug is causing the stall ;-)

I'm not sure what the cut point out to be, but it seems like anything that causes a 10 second stall in batch mode needs work, and anything above 7 might be suspect.

@galaunay, did you want to take a stab at hunting down where the stalls are occurring or should I add it to my TODO?

**Comment by galaunay** [comment]
>  All have passed!
Happy to hear it !

`elpy/wait-for-output` is mainly used to wait for the python interpreter to be started properly.
It is quite fast on a personal computer (I was able to drop `max-wait` to `0.1`), but seems to be longer on Travis, hence the value of `10` I put there.

I made a script (`elpy/script/test-benchmark`) to benchmark tests as you mentioned 
It prints the test names followed by the result of `benchmark-run` (elapsed time, gc calls and gc calls time).

Would you have a chance of running it on Debian ?

**Comment by sten0** [comment]
> elpy/wait-for-output is mainly used to wait for the python interpreter to
be started properly.
> It is quite fast on a personal computer (I was able to drop max-wait to
0.1), but seems to be longer on Travis, hence the value of 10 I put there.
>

Is there anything in common between `elpy/wait-for-output` and
`elpy-shell-should-echo-outputs`?  I noticed a new failure on armhf (I'm
guessing a slow and/or overloaded system) on the buildd network (real
hardware vs virtualised CI).  It wasn't able to get it to fail on amd64,
which is why I hope this might be a useful data point...native shell
completion has been disabling itself forever (ages ago Jorgen told me it's
an upstream bug in python-mode), so I'm guessing those lines are a red
herring; although later native completion appears to succeed, which is
strange.  It's with 8adc427 and Emacs 26.1 btw.

```elisp
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support
readline, yet ‘python-shell-completion-native-enable’ was t and "python3"
is not part of the ‘python-shell-completion-native-disabled-interpreters’
list.  Native completions have been disabled locally.
Shell native completion is disabled, using fallback
Sent: 4+3
Can’t guess python-indent-offset, using defaults: 4
python.el: native completion setup loaded
7
>>> OK
Test elpy-shell-should-echo-outputs backtrace:
  signal(ert-test-failed (((should (string-match "^7" (with-current-bu
  ert-fail(((should (string-match "^7" (with-current-buffer "*Python*"
  (if (unwind-protect (setq value-1439 (apply fn-1437 args-1438)) (set
  (let (form-description-1441) (if (unwind-protect (setq value-1439 (a
  (let ((value-1439 'ert-form-evaluation-aborted-1440)) (let (form-des
  (let* ((fn-1437 (function string-match)) (args-1438 (condition-case
  (progn (python-mode) (elpy-mode) (setq elpy-shell-echo-input nil) (s
  (progn (setq elpy-rpc-timeout 100) (progn (python-mode) (elpy-mode)
  (unwind-protect (progn (setq elpy-rpc-timeout 100) (progn (python-mo
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-b
  (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-cu
  (unwind-protect (progn (let ((temp-buffer (generate-new-buffer " *te
  (let ((old-process-list (process-list)) (old-buffer-list (buffer-lis
  (progn (let ((old-process-list (process-list)) (old-buffer-list (buf
  (if (<= 25 emacs-major-version) (progn (let ((old-process-list (proc
  (lambda nil (if (<= 25 emacs-major-version) (progn (let ((old-proces
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name elpy-shell-should-echo-outputs :docum
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  eval((ert-run-tests-batch-and-exit))
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
  command-line()
  normal-top-level()
Test elpy-shell-should-echo-outputs condition:
    (ert-test-failed
     ((should
       (string-match "^7"
    (with-current-buffer "*Python*" ... ...)))
      :form
      (string-match "^7"
   #("Python 3.7.4+ (default, Sep  4 2019, 08:03:05)
[GCC 9.2.1 20190827] on linux
Type \"help\", \"copyright\", \"credits\" or \"license\" for more
information.
>>>
python.el: native completion setup loaded
>>> 7
>>> OK
>>> " 148 149
(read-only fence)
149 153
(read-only t front-sticky ... rear-nonsticky t font-lock-face ...)
153 154
(front-sticky t font-lock-face comint-highlight-input)
154 195
(front-sticky ... rear-nonsticky t field output
inhibit-line-move-field-capture t)
195 196
(front-sticky ... rear-nonsticky t field output
inhibit-line-move-field-capture t read-only fence)
196 200
(front-sticky ... rear-nonsticky t field output
inhibit-line-move-field-capture t read-only t)
200 208
(front-sticky ... rear-nonsticky t field output
inhibit-line-move-field-capture t)
208 209
(front-sticky ... rear-nonsticky t field output
inhibit-line-move-field-capture t read-only fence)
209 213
(front-sticky ... rear-nonsticky t field output
inhibit-line-move-field-capture t read-only t ...)))
      :value nil))
   FAILED  331/392  elpy-shell-should-echo-outputs
```
https://tests.reproducible-builds.org/debian/rb-pkg/bullseye/armhf/elpy.html

> I made a script (elpy/script/test-benchmark) to benchmark tests as you
mentioned
> It prints the test names followed by the result of benchmark-run (elapsed
time, gc calls and gc calls time).
>
> Would you have a chance of running it on Debian ?
>

Thank you for working on this!  Yes, I'll cherry pick it onto 1.31.0 (which
I also need to import) as soon as I have a decent chunk of free time :-)

**Comment by sten0** [comment]
Here are the benchmark results on a reasonably fast system:
[elpy_1.31.0-1_amd64-2019-09-14T23:35:50Z.build.zip](https://github.com/jorgenschaefer/elpy/files/3613258/elpy_1.31.0-1_amd64-2019-09-14T23.35.50Z.build.zip)

Results from running the new benchmarks on a virtualised system will appear at the following URL sometime between a few minutes from now and a day from now (look for version 1.31.0-1 at the top):
https://ci.debian.net/packages/e/elpy/unstable/amd64/

**Comment by sten0** [comment]
Oh, and results for builds on real machines on different architectures are available via the sidebar here:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/elpy.html

**Comment by sten0** [comment]
@galaunay  Oh, and to collate our CI data with yours you can use this  `https://ci.debian.net/data/packages/unstable/amd64/e/elpy/latest-autopkgtest/log.gz`.  I just realised the stats are all nicely prefixed with `(elpy-`, with no false matches (unless a self-test were to fail). 
 That CI runs once a day at what appears to be a random time, so please take care to check for duplicates.

**Comment by galaunay** [comment]
Nice, thanks.

I have made a few adjustments to reduce the time spent on some tests.
Apparently what is causing most of the slow tests is `(elpy-config)`, which can indeed be a bit slow to query to pypi API.
Nothing abnormally weird until now :).

**Comment by sten0** [comment]
> Nice, thanks.
> 

You're welcome :-)

> I have made a few adjustments to reduce the time spent on some tests.
> Apparently what is causing most of the slow tests is `(elpy-config)`, which can indeed be a bit slow to query to pypi API.
> Nothing abnormally weird until now :).

That makes sense.  I wonder how those elpy-config-related tests are running on Debian infrastructure, where the network is blocked? (eg: waiting to time out, or giving up early).

Also, I have some bad news.  I found a bug (either an undocumented requirement, or a bug in the code...undetermined at this point in time) in `dh-elpa-test`, our test runner (somewhat equivalent to Cask), which was causing a SUCCESS exit code, even when tests were clearly failing.  This invalidates PASS||FAIL status since Sept 14, but the benchmark data is probably good...

Unless Emacs optimises code on-the-fly.  This is hypothetical, but it occurred to me that while it wastes resources in case of ERT failure, running the benchmarks before tests might be necessary to defend against on-the-fly optimisation.  eg: that benchmarks run faster than tests when tests have already run within the same Emacs instance.

**Comment by sten0** [comment]
Unfortunately, running the benchmark script before running self-tests, in the same Emacs instance breaks the following tests:
```
4 unexpected results:
   FAILED  elpy--sort-and-strip-duplicates-should-sort-and-strip-duplicates
   FAILED  elpy-doc-should-be-updated-automatically
   FAILED  elpy-doc-should-find-documentation-from-inside-arguments
   FAILED  elpy-module-django-get-test-runner-cache-size-limit
```
[elpy_1.31.0-2_amd64-2019-09-28T21:54:42Z.build.zip](https://github.com/jorgenschaefer/elpy/files/3666060/elpy_1.31.0-2_amd64-2019-09-28T21.54.42Z.build.zip)

I'm guessing that the benchmark script needs to clean up after itself with a few `makunbound`.

**Comment by galaunay** [comment]
Oh yes, it definitely does.
I updated the script to make it a bit cleaner in 90d7a5a.

**Comment by sten0** [comment]
Thank you @galaunay :-)

**Comment by galaunay** [comment]
I am closing this at the moment (because there is way too many issues open :/),
please reopen if necessary.
