### ISSUE TITLE
Elpy Installation -non venv

### ISSUE THREAD

**Issue by aviikc** [jorgenschaefer/elpy#1621]
# Summary
I havn't tried elpy on a virtual env. I wish to run elpy without virtual env is there a way i can.  Is there a step by step guide to this. I'm new to emacs, i dont know if i'm asking the right questions. Should i add ipython. 

# Steps to reproduce
I'm using emacs 26.2 

# My configuration
## OS
Debian 10.0

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.7.3 (/usr/bin/python3)
Interactive Python: python (/usr/bin/python)
Emacs.............: 26.1
Elpy..............: Not found (Python), 1.30.0 (Emacs Lisp)
Jedi..............: 0.14.1
Rope..............: 0.14.0
Autopep8..........: 1.4.4
Yapf..............: 0.28.0
Black.............: 19.3b0
Syntax checker....: flake8 (/usr/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is often a
good idea to work inside a virtual env. You can use M-x pyvenv-activate or M-x
pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables in that
directory, so Emacs won't find them. If you are missing some commands, do add
this directory to your PATH -- and then do `elpy-rpc-restart'.

The Python interpreter could not find the elpy module. Please report to:
https://github.com/jorgenschaefer/elpy/issues/new.

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button to invoke
its action. Invoke [+] to expand a group, and [-] to collapse an expanded group.
Invoke the [Group], [Face], and [Option] buttons below to edit that item in
another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[+]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[+]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
[+]-- Group Django extension
[+]-- Group Autodoc extension
```

## Elpy configuration in my init.el

```
    (use-package elpy
        :straight (elpy :type git :host github :repo "jorgenschaefer/elpy")
;        :defer t
;        :commands (elpy-enable)
        :after python
        :init
          (advice-add 'python-mode :before 'elpy-enable)
        :config
        (setq elpy-rpc-python-command "/usr/bin/python3"
;;              elpy-rpc-pythonpath  "/home/aviik/.local/lib/python3.7"
        )
     )
```

**Comment by gopar** [comment]
Hey, i'm not sure I understand the question. Elpy is capable of running without a virtual env if everything is set up. (`elpy-config` is showing that you have everything setup correctly such as jedi, rope, etc so it should be ready to go)

Is there something that isn't working (auto completion, refactoring, using wrong python version, etc)?

I also noticed that elpy isn't showing up as installed, but it is since you were able to do `M-x elpy-config`, not sure if this is because you are using `use-package` to install packages.

But please let us know what the main issue is that you are facing :)

**Comment by aviikc** [comment]
This is what I end up with in elpy outputs, 

*elpy outputs*
There was some unexpected output from the Elpy backend. This is usually not a
problem and should usually not be reported as a bug with Elpy. You can safely
hide this buffer and ignore it. You can also see the output below in case there
is an actual problem.
```
Output
/usr/bin/python3: No module named elpy.__main__
```

elpy is in 
/usr/lib/python3/dist-packages/

I tend to use ``` use-package ``` along with ```straight``` as i work at a college and and my system and os keeps on changing.  These packages help me sync my other packages with their github repos. 
My echo $PYTHONPATH results in a blank line.
Should I ``` (setenv "PYTHONPATH" "/usr/lib/python3/dist-packages/")```

**Comment by aviikc** [comment]
One more thing I thought I could add :
```
>>> elpy.__path__
['/home/aviik/.local/lib/python3.7/site-packages/elpy']
```

**Comment by galaunay** [comment]
You don't need to install the `elpy` python package from pip anymore (it is shipped with the emacs package now).So you can uninstall it with:
```bash
pip uninstall elpy
```

Also, it is generally not useful to set ` elpy-rpc-pythonpath` manually (and the value you set in your config was not what Elpy was expected). Could you make sure `elpy-rpc-pythonpath` is not set and try restarting emacs ?

If it is still showing `elpy outputs`, could you post the result of `M-: (print elpy-rpc-pythonpath)` and `M-: (elpy-rpc--environment)` ?
(press the `meta key`, then `:`, then type the command, then press `return`).
This will help us understand what happened.

**Comment by galaunay** [comment]
> M-: (print elpy-rpc-pythonpath) results in
"/home/aviik/.emacs.d/straight/build/elpy/"

This is fine. 

> M-: (elpy-rpc--environment) Results in:
> ```
> ("TERM=dumb" "SESSION_MANAGER=local/debian:@/tmp/.ICE-unix/1024,unix/debian:/tmp/.ICE-unix/1024" "XDG_CONFIG_DIRS=/etc/xdg" "XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share" "PWD=/home/aviik" "XDG_VTNR=7" "QT_ACCESSIBILITY=1" "GDMSESSION=lightdm-xsession" "SHELL=/bin/bash" "GLADE_CATALOG_PATH=:" "SSH_AUTH_SOCK=/tmp/ssh-MsCy16ixgJ1D/agent.983" "XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/aviik" ...)
>```

The display is truncated, could you instead post the result of:
```elisp
(let (python_env)
  (dolist (envvar (elpy-rpc--environment) python_env)
    (when (string-match "PYTHONPATH" envvar)
      (setq python_env envvar)
      (message envvar))))
```

> Output from Backend
> ```
> There was some unexpected output from the Elpy backend. This is usually not a
> problem and should usually not be reported as a bug with Elpy. You can safely
> hide this buffer and ignore it. You can also see the output below in case there
> is an actual problem.
> 
> Output
> /usr/bin/python3: Error while finding module specification for 'elpy.__main__' (ModuleNotFoundError: No module named 'elpy')
> ```

Elpy is complaining because it is not finding Elpy's `__main__.py`.
This file should be in `/home/aviik/.emacs.d/straight/build/elpy/elpy` on your system, is it there ?

You should also have the following files in the same folder:
``` bash
auto_pep8.py
blackutil.py
compat.py
__init__.py
jedibackend.py
__main__.py
pydocutils.py
refactor.py
rpc.py
server.py
tests
yapfutil.py
```

**Comment by aviikc** [comment]
This is what I have in   /home/aviik/.emacs.d/straight/build/elpy/
```
elpy-autoloads.el
elpy-django.el
elpy-django.elc
elpy.el
elpy.elc
elpy-pkg.el
elpy-pkg.elc
elpy-profile.el
elpy-profile.elc
elpy-refactor.el
elpy-refactor.elc
elpy-shell.el
elpy-shell.elc
```

**Comment by galaunay** [comment]
Would it work if you add `(setq elpy-rpc-pythonpath "/home/aviik/.emacs.d/straight/repos/elpy")` to you configuration ?

**Comment by aviikc** [comment]
It works.......It actually works. Thanks!
Very Grateful

**Comment by galaunay** [comment]
Happy to help.

Apparently straight is not installing the python sources in the expected directory.
I will have a look to it, but in the meantime, the workaround should work.
