### ISSUE TITLE
retrigger elpy mode

### ISSUE THREAD

**Issue by CDitzel** [jorgenschaefer/elpy#1622]
# Summary

When switching python buffers, often times I have to retrigger elpy, i.e. put elpy-mode twice to re-enable it for the current buffer to get the red-underlined hints. Why is that and how to avoid it?

# Steps to reproduce
Close Emacs and reopen it. switch buffer to open previous python file

# My configuration
## Result of `(elpy-config)`
```
Virtualenv........: pytorch (/home/ditzel/.virtualenvs/pytorch)
RPC Python........: 3.6.7 (/home/ditzel/.virtualenvs/pytorch/bin/python)
Interactive Python: python (/home/ditzel/.virtualenvs/pytorch/bin/python)
Emacs.............: 25.3.2
Elpy..............: 1.30.0
Jedi..............: 0.14.1
Rope..............: 0.14.0
Autopep8..........: 1.4.4
Yapf..............: 0.28.0
Black.............: 19.3b0
Syntax checker....: flake8 (/home/ditzel/.virtualenvs/pytorch/bin/flake8)
```

## Elpy configuration in my init.el
```
(setq python-indent-guess-indent-offset-verbose nil
      python-shell-interpreter "python")
(setq-default python-indent 4)
(setq-default python-indent-offset 4)
(add-hook 'python-mode-hook
          (lambda ()
            (setq tab-width 4)))




(use-package yapfify
  :init
  (add-hook 'python-mode-hook 'yapf-mode))

(use-package python
  :mode ("\\.py\\'" . python-mode)
  :interpreter ("python" . python-mode)
  :config
  (progn (setq python-shell-interpreter "python")
     (setq python-indent-offset 4)
     (setq python-shell-completion-native-disabled-interpreters '("python"))))

(use-package elpy
  :defer 1
  :after python
  :config
  (elpy-enable)
  (defalias 'workon 'pyvenv-workon))
```

**Comment by galaunay** [comment]
It is a bit complicated to make Elpy 'deferable', so your issue may come from there.

would it work with this:
```Elisp
(use-package elpy
  :defer t
  :init
  (advice-add 'python-mode :before 'elpy-enable))
  :config
  (elpy-enable)
  (defalias 'workon 'pyvenv-workon))
```

**Comment by CDitzel** [comment]
Thanks. I will try. in the meantime I found that this affects apparently only the syntax checking, e.g. too long lines and the underlining of such issues. So its more likely that this is flake8 related maybe?

Also I was wondering, how is Black used in elpy and for what purposes?

**Comment by galaunay** [comment]
> Thanks. I will try. in the meantime I found that this affects apparently only the syntax checking, e.g. too long lines and the underlining of such issues. So its more likely that this is flake8 related maybe?

It may also be Elpy's flymake module that is not initialised properly.
Is `flymake-mode` enabled when you open a new python buffer ?

> Also I was wondering, how is Black used in elpy and for what purposes?

You can use `M-x elpy-black-fix-code` to use black to format the code of the current buffer.

**Comment by CDitzel** [comment]
thanks, how can I make this the default? and how does this interplay with flymake?

**Comment by galaunay** [comment]
> thanks, how can I make this the default?

What do you want to make as default exactly ?

> and how does this interplay with flymake?

Flymake integrates linters (like flake8) in Emacs, that warns you about style/syntax errors.
Black is not a linter but an automatic code formater,  that modify your code to ensure it follows a set of styling guidelines.

So they don't really interplay, and using one or the other depends on your workflow. Flymake offers more flexibility regarding coding style and warn you about syntax error (black will just give up if there is any syntax error). On the other hand, black format everything for you, saving you the burden of fixing coding style issues by hand.

**Comment by CDitzel** [comment]
thanks, but I mean e.g. if I do M-x elpy-black-fix-code, the code gets formatted in a certain way but only if I do C-x C-s for the next time. Then the formatting is again changed according to some other layout. Why is that and what determines the default layout that is used upon saving?

**Comment by galaunay** [comment]
Elpy doesn't reformat the code upon saving.
I think it is due to the `yapfify` package you use.

If you remove those lines from your config:
```Elisp
(use-package yapfify
  :init
  (add-hook 'python-mode-hook 'yapf-mode))
```
It should address your issue.

**Comment by galaunay** [comment]
I hope this is fixed now, please re-open if not.
