### ISSUE TITLE
module not found error when running script with elpy

### ISSUE THREAD

**Issue by CDitzel** [jorgenschaefer/elpy#1627]
# Summary

I am running python 3.6 in virtualenv and in the script I import a custom module (python file that is located within the same directory) with 

> import models

and everything works from the shell. But when I enter the same virtual environment from within Emacs via pyenv-workon and press C-c C-c in the file I get

> ModuleNotFoundError: No module named 'models'

why is that? It seems that elpy cant find this module for some reason. Using pdb does work as well. so it must be elpy-related. Am I missing something here?

# My configuration
ubuntu 18.04 Emacs 26. with python 3.6 in virtualenv

## Result of `(elpy-config)`
```
Virtualenv........: pytorch (/home/ditzel/.virtualenvs/pytorch)
RPC Python........: 3.6.7 (/home/ditzel/.virtualenvs/pytorch/bin/python)
Interactive Python: python (/home/ditzel/.virtualenvs/pytorch/bin/python)
Emacs.............: 25.3.2
Elpy..............: 1.30.0
Jedi..............: 0.14.1
Rope..............: 0.14.0
Autopep8..........: 1.4.4
Yapf..............: 0.28.0
Black.............: 19.3b0
Syntax checker....: flake8 (/home/ditzel/.virtualenvs/pytorch/bin/flake8)
```

## Elpy configuration in my init.el
```

(use-package yapfify
  :init
  (add-hook 'python-mode-hook 'yapf-mode))

(use-package python
  :mode ("\\.py\\'" . python-mode)
  :interpreter ("python" . python-mode)
  :config
  (progn (setq python-shell-interpreter "python")
     (setq python-indent-offset 4)
     (setq python-shell-completion-native-disabled-interpreters '("python"))))

(use-package elpy
  :defer t
  :init
  (advice-add 'python-mode :before 'elpy-enable)
  :config
  (elpy-enable)
  (defalias 'workon 'pyvenv-workon))

```

**Comment by galaunay** [comment]
Elpy tries to start the shell in the "project" folder (which is determined for every script by the command `elpy-project-root`). If you module is not in this folder, python will not be able to find it.
You can check in which folder you are by typing `import os; print(os.getcwd())` in the python shell.

This behavior is  convenient in some configurations but can be confusing (I agree).
If you don't like it, you can change the [`elpy-shell-use-project-root`](https://elpy.readthedocs.io/en/latest/ide.html?highlight=%22elpy-shell-use-project-root%22#command-elpy-shell-switch-to-shell) option:
```elisp
(setq elpy-shell-use-project-root nil)
```

I hope it was your issue.

**Comment by CDitzel** [comment]
that was helpful. Thank you for your information =)
