### ISSUE TITLE
elpy-test won't invoke manage.py on specific tests

### ISSUE THREAD

**Issue by phamhm** [jorgenschaefer/elpy#1629]
# Summary
When the pointer is outside of any test classes or functions, elpy-test will run django test with "manage.py" and the tests run fine. When the pointer is inside a class or test method, elpy-test would prompt for setting env variable DJANGO_SETTINGS_MODULE. 

Thank you for reporting to Elpy !

# Steps to reproduce
1. setting elpy-test-runner to django. 
2. run elpy-test (or C-x C-t) with pointer outside of class. Test will run. 
3. Move pointer to inside a class, django test won't run.

**Comment by galaunay** [comment]
When the pointer is inside a test class, Elpy tries to run only the test at point.

This implies a specific syntax (like `./manage.py test myapplication.tests.first_test`), that depends on the runner you are using (the default runner uses `.` as separators while nose uses `:`).
So Elpy needs to know which runner you want to use.

This is supposed to be set in your setting file and Elpy uses the environment variable `DJANGO_SETTINGS_MODULE` to know where this file is.

I understand it can be cumbersome to set this environment variable every time, so
I made a PR (#1630) that make Elpy use a default path when `DJANGO_SETTINGS_MODULE` is not specified.
This will fix your issue.

**Comment by galaunay** [comment]
The PR will be merged soon, please re-open this issue if it is not fixing your problem.
