### ISSUE TITLE
Change `C-c C-g` key binding

### ISSUE THREAD

**Issue by patxoca** [jorgenschaefer/elpy#1635]
`elpy-pdb-map` is currently bound to `C-c C-g`, which is an unfortunate choice, because C-g is the standard Emacs binding for `(keyboard-quit)`. I don't have a good alternative, maybe `C-c M-g`.

https://github.com/jorgenschaefer/elpy/blob/7acdd14eaec4b123ae1c16ead59c91adcf7f9775/elpy.el#L510

**Comment by galaunay** [comment]
Legitimate, thanks.
I changed it to `C-c C-u`.
