### ISSUE TITLE
test-helper.el fails on a python3-only system

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1636]
Hi!

The Debian Python Team is now aggressively removing Python 2 support from leaf packages (Elpy is one of these), and making sure that they will still function correctly when py2 is removed in [four months](https://pythonclock.org) (pythonclock.org) so I had to take another stab at identifying the state of Elpy.  As far as I can tell, the only remaining issue is an implicit hard dependency on process calls to $PATH/python.

As ever, the details of how I'm preconfiguring Python-3-by-default can be found here: https://salsa.debian.org/emacsen-team/elpy/blob/master/debian/debian-autoloads.el

It's not obvious to me why `test-helper.el` implicitly depends on $PATH/python, so I've attached two build logs that differ thus:

[elpy_1.29.1+40.gb929013-2_amd64-2019-08-22T22:07:15Z.build.txt](https://github.com/jorgenschaefer/elpy/files/3532159/elpy_1.29.1%2B40.gb929013-2_amd64-2019-08-22T22.07.15Z.build.txt)
 * Installs python2.7

[elpy_1.29.1+40.gb929013-2_amd64-2019-08-22T22:09:46Z.build.txt](https://github.com/jorgenschaefer/elpy/files/3532160/elpy_1.29.1%2B40.gb929013-2_amd64-2019-08-22T22.09.46Z.build.txt)
 * Does not install python2.7
 * L1413-L1414:
```
Loading /<<PKGBUILDDIR>>/test/test-helper.el (source)...
Searching for program: No such file or directory, python
```
I spent as much free time as I had this afternoon trying to trace this, and got as far as `progn: Searching for program: No such file or directory, python`, so I'm guessing there's a py2 assumption in a macro somewhere, and that this is triggered by one of the `(progn ,@body)` forms in test-helper.el.  I hope it's not a hard problem to solve, and wish I could contribute a fix rather than a best-attempt at debugging (I haven't yet learned how to debug macros, and struggle with what seems to be indirection of some kind).

I'm not sure what Ubuntu's timeline for removal is, but I believe this will begin to cause problems for users after either the Ubuntu release in October 2019 or April 2020 (py2 pip will also disappear at that time and users will need to switch to pip3).

On the upside, AFAICT this might be last remaining Python2-to-Python3 issue! :-)

'hope this bug report is useful!
Nicholas

**Comment by sten0** [comment]
Ah, I think this is how one what one would probably need to do to debug this further [Instrumenting-Macro-Calls](https://www.gnu.org/software/emacs/manual/html_node/elisp/Instrumenting-Macro-Calls.html)

**Comment by galaunay** [comment]
Hi, 

I found some hard-written references to `"python"` that may be the problem here.
I will get back at you asap with a potential fix.

**Comment by sten0** [comment]
Thanks @galaunay, much appreciated!

**Comment by sten0** [comment]
Success: https://ci.debian.net/data/autopkgtest/unstable/amd64/e/elpy/2896376/log.gz

I did enough local tests that I'm confident it's fixed.

Closing this issue now!

**Comment by galaunay** [comment]
Good news, one more step towards perfection :)
