### ISSUE TITLE
ipython wrong line numer

### ISSUE THREAD

**Issue by bingtangben** [jorgenschaefer/elpy#1637]
I use elpy with ipython, but in ipython shell line number is not correct. It's confusing that ipython seems omit many ouput lines.

**Comment by galaunay** [comment]
Elpy is regularly sending code to the interpreter (notably to get information on what is loaded there) so this could mess with the line numbers.

However, I didn't manage to reproduce this issue.
Could you post your Elpy configuration as well as a non-working example ?

**Comment by bingtangben** [comment]
Thanks for your explaination. The line number problem seems hard to fix.

Sometimes I type small codes directly in IPython shell buffer and it could mess the line numbers. I find Elpy is sending some codes (not just codes I'm typing) to IPython and this will be much slow.
