### ISSUE TITLE
Change pdb yasnippet expansion to: __import__("pdb").set_trace()

### ISSUE THREAD

**Issue by hmelman** [jorgenschaefer/elpy#1643]
I started using black as a formatter and while I otherwise like it, I found it expanded the breakpoint statements I use with elpy's `pdb` yasnippet into three lines which then got annoying to delete (compared to one line). black [issue 790](https://github.com/psf/black/issues/790) describes exactly this situation. While they aren't supporting an inline comment to disable reformatting, they suggest an equivalent breakpoint statement that doesn't have this problem.

I've setup a personal snippet for this which works, but I suggest changing elpy's yasnippet expansion of `pdb` to: `__import__("pdb").set_trace()`

**Comment by galaunay** [comment]
Done, thanks for the suggestion !
