### ISSUE TITLE
Issue management

### ISSUE THREAD

**Issue by azzamsa** [jorgenschaefer/elpy#1645]
Hi

I think we should use more label for the issues. There are some of non-elpy issue and "support" issue. Magit use `support` label for [questions](https://github.com/magit/magit/issues?q=label%3Asupport+is%3Aclosed), and move other [non magit issue](https://github.com/magit/non-magit-issues/issues). Applying this will make elpy issue tracker cleaner and lower the burden of developers, plus easy to search for old issue.

**Comment by galaunay** [comment]
Hi

I agree.
I will try to start using labels again on my side.

**Comment by azzamsa** [comment]
I will close this since it's no finish line for this.
