### ISSUE TITLE
elpy cashing variables?

### ISSUE THREAD

**Issue by CDitzel** [jorgenschaefer/elpy#1656]
I noticed that sometimes elpy cashes entities and variables so that e.g. after commenting out sections of code, C-c C-c still results in a running app where as the very same code compiled in the shell throws an error which was to be expected. 

I dont like this behavior as it suggests wrong facts and implies incorrect scopes. How do I disable this?

**Comment by galaunay** [comment]
I am not sure to understand the behaviour you described.
Could you give an example ?

**EDIT:**
If you have the following code:
```python
a = 2
try:
  print(a)
except:
  print("'a' is not defined")
```
and hit `C-c C-c`, I will get:
```python
2
```
If you modify the code to:
```python
# a = 2
try:
  print(a)
except:
  print("'a' is not defined")
```
and hit `C-c C-c` again, you will still get:
```python
2
```
because the interpreter was not restarted between the two `C-c C-c`.
Is it the behaviour you dislike ?

**Comment by CDitzel** [comment]
Yes exactly this, how can I circumvent this?

**Comment by sten0** [comment]
> By construction, `C-c C-c` is not "executing the current buffer" but "sending the current buffer code to the python interpreter". So it does not restart the interpreter.
> 

/\ does existing documentation explain it this clearly? /\

> In order to do what you want, you could use `elpy-shell-kill-shell` (bound to `C-c C-k`) between each `C-c C-c`.
> You could also ask Elpy to do it automatically with something like this:
> 
> ```emacs-lisp
> (advice-add 'elpy-shell--send-region-or-buffer-internal
>             :before
>             (lambda (&rest _rest)
>               (let ((shell-buffer (python-shell-get-buffer)))
>                 (when shell-buffer
>                   (delete-process shell-buffer)
>                   (kill-buffer shell-buffer))))
>             '((name . "kill shell before sending buffer.")))
> ```

/\ imho this would also be useful in a FAQ/Hints/Tips and Tricks section /\  I'd also add a short note about its downsides, so it will be obvious why it's not the default behaviour.

**Comment by galaunay** [comment]
I will update the documentation to make this clearer and find a place for the snippet.
I am closing this in the meantime, please reopen if necessary.

**Comment by CDitzel** [comment]
thank you guys for your help
