### ISSUE TITLE
RPC virtualenv does not update when activating a new environment

### ISSUE THREAD

**Issue by mrclneumann** [jorgenschaefer/elpy#1663]
# Summary

When I understand correctly, all RPCs are started in a dedicated environment named `elpy-rpc-venv`. Activating an environment with a different python version than `elpy-rpc-venv` should thus trigger a re-creation of the obsolete `elpy-rpc-venv` in order to give correct results for code completion, documentation, etc. Is this the way this dedicated environment is meant to work? 

If yes, I have an issue that `elpy-rpc-venv` does not update once it has been created for the first time.

# Steps to reproduce
- Create and activate a virtual environment with python 2.7
- Call `elpy-config` -> elpy creates `elpy-rpc-venv`
- Deactivate the environment
- Create and activate a virtual environment with python 3.6

# My configuration
## OS
Ubuntu 18.04

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.31.0
Virtualenv........: newenv (/home/marcel/.virtualenvs/newenv)
Interactive Python: python 3.6.8 (/home/marcel/.virtualenvs/newenv/bin/python)
RPC virtualenv....: elpy-rpc-venv (/home/marcel/.virtualenvs/elpy-rpc-venv)
 Python...........: python 2.7.15 (/home/marcel/.virtualenvs/elpy-rpc-venv/bin/python)
 Jedi.............: 0.15.1
 Rope.............: 0.14.0
 Autopep8.........: 1.4.4
 Yapf.............: 0.28.0
 Black............: Not found (19.3b0 available)
Syntax checker....: flake8 (/home/marcel/.virtualenvs/newenv/bin/flake8)

The black package is not available. Commands using this will not work.

[Install black]

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button
to invoke its action.  Invoke [+] to expand a group, and [-] to
collapse an expanded group.  Invoke the [Group], [Face], and [Option]
buttons below to edit that item in another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[+]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[+]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
[+]-- Group Django extension
[+]-- Group Autodoc extension
```

## Elpy configuration in my init.el
```
(use-package elpy
  :ensure t
  :init
  (elpy-enable))
```

**Comment by galaunay** [comment]
The python version of `elpy-rpc-venv` and of the current virtualenv can be different without issues.
You should still have the documentation and completion related to the virtualenv you are using (if not, please raise an issue here).
That's why `elpy-rpc-venv` does not need to be updated when the current virtualenv changes.

The `elpy-rpc-venv` is however updated if you change the value of `elpy-rpc-python-command`, that dictates the version of python to use for the RPC.
