### ISSUE TITLE
Invalid function: elpy-insert--popup

### ISSUE THREAD

**Issue by puitgfr** [jorgenschaefer/elpy#1664]
# Summary

Hello,

When I visit a new python buffer, Elpy complains about an invalid function: `elpy-insert--popup`. Here is the whole error message:
```error in process filter: elpy-rpc--handle-unexpected-line: Invalid function: elpy-insert--popup
error in process filter: Invalid function: elpy-insert--popup
error in process sentinel: elpy-rpc--default-error-callback: peculiar error: "exited abnormally with code 1"
error in process sentinel: peculiar error: "exited abnormally with code 1"
```

# Steps to reproduce

- `C-x C-f new.py`
- press any key

# My configuration
## OS
Debian stable

## Result of `(elpy-config)`
```
Emacs.............: 26.1
Elpy..............: 1.31.0
Virtualenv........: None
Interactive Python: python3 3.7.3 (/usr/bin/python3)
RPC virtualenv....: elpy-rpc-venv (/home/fran/.virtualenvs/elpy-rpc-venv)
 Python...........: python3 3.7.3 (/home/fran/.virtualenvs/elpy-rpc-venv/bin/python3)
 Jedi.............: Not found (0.15.1 available)
 Rope.............: Not found (0.14.0 available)
 Autopep8.........: Not found (1.4.4 available)
 Yapf.............: Not found (0.28.0 available)
 Black............: Not found (19.3b0 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The jedi package is not available. Completion and code navigation will
not work.
[Install jedi]

The autopep8 package is not available. Commands using this will not
work.
[Install autopep8]

The yapf package is not available. Commands using this will not work.
[Install yapf]

The black package is not available. Commands using this will not work.
[Install black]
```

## Elpy configuration in my init.el
```elisp
(setq python-shell-interpreter "python3")

(use-package elpy
  :init
  (add-hook 'flycheck-mode-hook #'flycheck-pycheckers-setup)
  (advice-add 'python-mode :before 'elpy-enable)
  :config
  (setq
   elpy-modules '(elpy-module-company
                  elpy-module-eldoc
                  elpy-module-pyvenv
                  elpy-module-highlight-indentation
                  elpy-module-yasnippet
                  elpy-module-django
                  elpy-module-autodoc
                  elpy-module-sane-defaults)
   elpy-rpc-python-command python-shell-interpreter
   elpy-shell-echo-input nil
   ))
```

**Comment by puitgfr** [comment]
I've found a workaround : setting `include-system-site-packages` to true in `~/.virtualenvs/elpy-rpc-venv/pyenv.cfg` does the trick.
I guess it has something to do with the fact that all my pip packages are installed system-wide (in `/usr/local/lib/python3.7/dist-packages`).

By the way, it solves as well the `autopep8`, `rope` and `yapf` « not available » status printed by `elpy-config`. Indeed, these packages are present in `/usr/local/lib/python3.7/dist-packages`.

**Comment by galaunay** [comment]
It looks like Elpy is trying to inform you of something that went wrong but that a macro necessary to do so (`elpy-insert--popup`) is not loaded properly.

Would it help to add `(require 'elpy)` in `elpy-rpc.el` help ?

**Comment by puitgfr** [comment]
I'm not sure to understand. ``elpy-rpc`` is required in ``elpy.el``. We'd get a recursive load error, wouldn't we ? You suggest the other way around ?

**Comment by galaunay** [comment]
Ah yes, you are right.

I have no clue...
Maybe try the simpler `(elpy-enable)` instead of `(advice-add 'python-mode :before 'elpy-enable)` ?

**Comment by yorodm** [comment]
Any luck on this? I'm having the same problem in Windows

**Comment by galaunay** [comment]
I think I found the problem.
It should be fixed, could you update to the latest version of Elpy (from git or melpa) and tell me if it is still happening?

**Comment by galaunay** [comment]
I am closing this, please re-open if the issue still exist.

**Comment by yorodm** [comment]
It's fixed, thanks so much.

**Comment by puitgfr** [comment]
Thanks for the fix, it works.
