### ISSUE TITLE
Elpy giving error: Wrong type argument: number-or-marker-p

### ISSUE THREAD

**Issue by mikesdnielsen** [jorgenschaefer/elpy#1666]
# Summary

Completion is no longer working in Elpy and it  gives off an error `widget-apply: Wrong type argument: number-or-marker-p, "Abort trap: 6"`when trying to run `elpy-config`

I've tried with both the stable and most recent version from MELPA. 

# Steps to reproduce
- Open a python file
- Activate your virtualenv (`pyvenv-workon`)
- Run `elpy-config` 

# My configuration
## OS
MacOS Mojave 10.14.6

## Result of `(elpy-config)`
N/A - can't run `elpy-config` 

## Elpy configuration in my init.el
```
(elpy-enable)
(pyvenv-mode)

;; elpy customization
(defun elpy-goto-definition-or-rgrep ()
  "Go to the definition of the symbol at point, if found. Otherwise, run `elpy-rgrep-symbol'."
    (interactive)
    (ring-insert find-tag-marker-ring (point-marker))
    (condition-case nil (elpy-goto-definition)
        (error (elpy-rgrep-symbol
                   (concat "\\(def\\|class\\)\s" (thing-at-point 'symbol) "(")))))

(define-key elpy-mode-map (kbd "M-.") 'elpy-goto-definition-or-rgrep)

;; use flycheck not flymake with elpy
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

(setq elpy-rpc-backend "jedi")
(setq elpy-rpc-timeout nil)

;; enable autopep8 formatting on save
(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

;; enable isort formatting on save
(require 'py-isort)
(add-hook 'before-save-hook 'py-isort-before-save)
```

**Comment by galaunay** [comment]
Thanks for the detailed report.

Could you run `(elpy-config)` after activating debug-on-error (`M-x toggle-debug-on-error`) and post the result ?

**Comment by mikesdnielsen** [comment]
Thanks for getting back. I tried to uninstall the elpy package and remove all configuration. I then re-added it all (identical) and it now seems to work just fine again. 

It was weird, as the above issue had been appearing for about 2 days with little I could do about it. 

I'll close my issue for now - thanks for a great package. :-)

**Comment by mikesdnielsen** [comment]
Hmm, the error is back again now. It might be project specific. I use a `.dir-locals.el` to activate `pyvenv-workon`. Here is a dump from the debug: 

```
  elpy-insert--pip-button-value-create((elpy-insert--pip-button :package "black"))
  widget-apply((elpy-insert--pip-button :package "black") :value-create)
  widget-default-create((elpy-insert--pip-button :package "black"))
  widget-apply((elpy-insert--pip-button :package "black") :create)
  widget-create(elpy-insert--pip-button :package "black")
  elpy-config--insert-configuration-problems(#<hash-table equal 22/65 0x502ce911>)
  elpy-config()
  funcall-interactively(elpy-config)
  call-interactively(elpy-config record nil)
  command-execute(elpy-config record)
  execute-extended-command(nil "elpy-config" "elpy-config")
  funcall-interactively(execute-extended-command nil "elpy-config" "elpy-config")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by galaunay** [comment]
It looks like `(elpy-config--get-config)` is returning something unexpected.

Could you try running 
```elisp
(maphash (lambda (key value) (message "%s: %s" key value))
           (elpy-config--get-config))
```
and post what will appear in the `*Messages*` buffer ?

**Comment by mikesdnielsen** [comment]
Could it be related to an error in the virtualenv for the specific project I'm working on? The error is very strange as it seems to only be present sometimes. Yesterday, I noticed that an brew update had "destroyed" a virtualenv which I then recreated.

**Comment by galaunay** [comment]
Yes, it could be.
Elpy is basically sending a bit of code to python to get information about package versions.
It is apparently returning something unexpected, so it could definitely be a damaged virtualenv.

Running the `maphash` call (from my last post) may give us a better idea on what's happening.

**Comment by mikesdnielsen** [comment]
I'll see if I can break my virtualenv again and see if this can provoke the error as it is now "gone" again.

**Comment by galaunay** [comment]
Ok, I will mark this as closed for now.
Please let me know itf it ends up re-appearing again.

**Comment by snlawrence** [comment]
Hey, @galaunay I'm having the same issue, no code completion and `M-x elpy-config` failing with the same error. 

> Could you try running
>
> (maphash (lambda (key value) (message "%s: %s" key value))
           (elpy-config--get-config))
```
emacs_version: 26.1
python_rpc: python
python_rpc_executable: /home/slawrence/anaconda3/bin/python
python_interactive: ipython
python_interactive_executable: /home/slawrence/anaconda3/bin/ipython
virtual_env: /home/slawrence/anaconda3/envs/main
virtual_env_short: main
error_output:
```
The debugger output on running `elpy-config`:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p "Bus error")
  elpy-insert--pip-button-value-create((elpy-insert--pip-button :package "elpy" :button-overlay #<overlay from 628 to 633 in *Elpy Config*>))
  widget-apply((elpy-insert--pip-button :package "elpy" :button-overlay #<overlay from 628 to 633 in *Elpy Config*>) :value-create)
  widget-default-create((elpy-insert--pip-button :package "elpy" :button-overlay #<overlay from 628 to 633 in *Elpy Config*>))
  widget-apply((elpy-insert--pip-button :package "elpy" :button-overlay #<overlay from 628 to 633 in *Elpy Config*>) :create)
  widget-create(elpy-insert--pip-button :package "elpy")
  elpy-config--insert-configuration-problems(#<hash-table equal 8/65 0x127c2c1>)
  elpy-config()
  funcall-interactively(elpy-config)
  call-interactively(elpy-config record nil)
  command-execute(elpy-config record)
  execute-extended-command(nil "elpy-config" "elpy-config")
  funcall-interactively(execute-extended-command nil "elpy-config" "elpy-config")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

My conda virtual environment appears to be broken, for example:

```bash
$ conda install numpy
Collecting package metadata (current_repodata.json): - Bus error (core dumped)
```
Not sure how I broke the virtual environment, but let me know if I can provide any more information.
