### ISSUE TITLE
Get user consent before pip installing packages

### ISSUE THREAD

**Issue by yurkobb** [jorgenschaefer/elpy#1667]
# Summary

After a recent upgrade I have noticed that elpy pip-installed stuff like yapf into a virtualenv without my consent. I would prefer to install these packages manually from system repositories instead of pypi, but for that I need to be given choice. Installing extra packages like these should be opt-in.

My assumption is that if I install something from melpa, the package should not be _automatically_ installing anything from other sources beyond those enabled in my `package-archives`, just like if I install something via apt, those packages should only depend on packages in my sources.list and not be auto-installing pip/npm/gem packages.

# Steps to reproduce
1. <s>Install or</s> upgrade elpy. EDIT: just tested with a separate clean user account: installing elpy doesn't create the rpc virtualenv automatically; this must have been an upgrade glitch?
2. Run `elpy-config`
3. Note the message in the minibuffer: `Elpy is creating the RPC virtualenv... (This may take a while, but should only happen once in a while)`

Additionally, I have tried `rm -fR ~/.virtualenvs/` and running `elpy-config` again. Elpy recreates the virtualenv.

# My configuration
## OS
Fedora 30

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 26.2
Elpy..............: 1.31.0
Virtualenv........: None
Interactive Python: python3 3.7.4 (/usr/bin/python3)
RPC virtualenv....: elpy-rpc-venv (/home/yurb/.virtualenvs/elpy-rpc-venv)
 Python...........: python3 3.7.4 (/home/yurb/.virtualenvs/elpy-rpc-venv/bin/python3)
 Jedi.............: 0.15.1
 Rope.............: 0.14.0
 Autopep8.........: 1.4.4
 Yapf.............: 0.28.0
 Black............: 19.3b0
Syntax checker....: flake8 (/usr/bin/flake8)
```

## Elpy configuration in my init.el
```
(elpy-enable)
(setq elpy-rpc-python-command "python3")
(setq python-shell-interpreter "python3")

(add-hook 'elpy-mode-hook (lambda ()
                            (highlight-indentation-mode -1)))

(setq python-fill-docstring-style 'pep-257-nn)
```

**Comment by galaunay** [comment]
Thanks for reporting this,
I understand your concern about installing packages from PyPI automatically.
I just made a PR (#1670) to fix this, it should be merged in a few hours.

Elpy will now ask before installing anything from PyPI.

**Comment by galaunay** [comment]
Should be fixed now, please re-open if not.

**Comment by yurkobb** [comment]
Thanks a lot for the quick change!

I have a followup question. If I don't let elpy install the dependencies, how can I make it use system-wide installed ones?

For instance, I have black installed system-wide:
```bash
$ python3 -c "import black" && echo "all fine"
all fine
```

...and `elpy-rpc-python-command` is set to `python3`.

Yet `elpy-config` reports black as not installed. I presume this is because it expects black to be installed within its virtualenv (reported by `elpy-config` as `~/.emacs.d/elpy/rpc-venv`) instead of system-wide.

**Comment by galaunay** [comment]
I merged another PR yesterday that allows to customise which environment to use for the RPC.

`(setq elpy-rpc-virtualenv-path 'global)` should do the trick for you 
(you can also check `elpy-rpc-virtualenv-path` documentation to check what are the others options).

**Comment by yurkobb** [comment]
> (setq elpy-rpc-virtualenv-path 'global) should do the trick for you
It does indeed! Thank a lot!
