### ISSUE TITLE
format code error under windows with Chinese words

### ISSUE THREAD

**Issue by kevindragon** [jorgenschaefer/elpy#1678]
# Summary

`测试` will be replaced by `娴嬭瘯`

# Steps to reproduce

`M-x` -> `elpy-format-code`

# My configuration
## OS

Windows 7 (China)

# Reason

The os default encoding is GBK, when start the python process from emacs, the python process encoding is set to GBK. But the encoding of python file and buffer is utf-8.

**Comment by galaunay** [comment]
Should be fixed by #1679.
