### ISSUE TITLE
elpy sorts import after saving the file

### ISSUE THREAD

**Issue by JurijsNazarovs** [jorgenschaefer/elpy#1680]
# Summary

If I have sys.path.append() statement in the python code, and if this statement is not the last one, then once I save code, the whole import section is reordered, so that sys.path.append() becomes the last one. Every time the order is different.

# Steps to reproduce
```
import sys
import torch.optim as optim
from TCN.char_cnn.utils import *
import argparse
from TCN.char_cnn.model import TCN
import torch.nn as nn
import math
import time
sys.path.append("../../")
import warnings
```

After saving file result are following:

```
import warnings
import sys
import torch.optim as optim
from TCN.char_cnn.utils import *
import argparse
from TCN.char_cnn.model import TCN
import torch.nn as nn
import math
import time
sys.path.append("../../")
```

# My configuration
## OS
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04

## Result of `(elpy-config)`
```
Emacs.............: 26.3
Elpy..............: 1.31.0
Virtualenv........: None
Interactive Python: /home/nazarovs/software/anaconda3/envs/pytorch/bin/python3 3.7.3 (/home/nazarovs/software/anaconda3/envs/pytorch/bin/python3)
RPC virtualenv....: rpc-venv (/home/nazarovs/.emacs.d/elpy/rpc-venv)
 Python...........: /home/nazarovs/software/anaconda3/envs/pytorch/bin/python 3.7.3 (/home/nazarovs/software/anaconda3/envs/pytorch/bin/python)
 Jedi.............: 0.15.1
 Rope.............: 0.14.0
 Autopep8.........: 1.4.4
 Yapf.............: 0.28.0
 Black............: 19.3b0
Syntax checker....: flake8 (/home/nazarovs/software/anaconda3/envs/pytorch/bin/flake8)
```

## Elpy configuration in my init.el
```

```

**Comment by JurijsNazarovs** [comment]
Seems like this is the problem with autopep8. Turning it off issue disappears.

**Comment by galaunay** [comment]
Elpy is not supposed to run autopep8 on save.
`py-autopep8.el` does that I believe, do you have it installed ?

**Comment by JurijsNazarovs** [comment]
@galaunay you are rights, seems like i have separately installed py-autopep8.el and I have following command in my .emacs file: 

```
(require 'py-autopep8)                                                                                                                                                                                  
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)
```
Then does elpy has an abilitiy to make code looks pretty by itself or this is just with autopep8 function? Is there is a way to turn off sorting feature in autopep8 in emacs?

**Comment by galaunay** [comment]
> Then does elpy has an abilitiy to make code looks pretty by itself or this is just with autopep8 function?

Elpy also provides auto-formatting using `yapf` and `black` (you can try `elpy-yapf-fix-code` and `elpy-black-fix-code`).

You can make auto-formatting on save using the following snippet: 
``` elisp
(add-hook 'elpy-mode-hook
          (lambda ()
            (add-hook 'before-save-hook 'elpy-autopep8-fix-code nil t)))
```

> Is there is a way to turn off sorting feature in autopep8 in emacs?

You can specify some pep8 rules to be ignored with a customization file (see [here](https://github.com/hhatto/autopep8#configuration)).
Basicaly, I think you can ignore import re-ordering with a `~/.config/pycodestyle` containing the following inside:
```
[pycodestyle]
max_line_length = 120
ignore = E401,E402
```

**Comment by JurijsNazarovs** [comment]
I see, thank you. I will close the issue then.
