### ISSUE TITLE
Failed test: elpy-rpc-get-virtualenv-path-should-return-current-venv-path

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1695]
I've forked the project and followed the instructions in `CONTRIBUTING.md`. I just want to let you know that one unit test is not passing in my environment:

```
Ran 414 tests in 99.380 seconds
1 unexpected results:
   FAILED  elpy-rpc-get-virtualenv-path-should-return-current-venv-path
```

**Comment by galaunay** [comment]
The new branch tests seem to pass.
Please re-open if it still relevant;
