### ISSUE TITLE
elpy doesn't recognize custom compiled python

### ISSUE THREAD

**Issue by dackon** [jorgenschaefer/elpy#1722]
# Summary
I compiled python-3.8.0 myself, because I don't want to use root privilege to install official python. Although I added the python to $PATH in emacs, and in emacs eshell, the command 'which python' successfully pointed to my compiled python, the elpy cannot recognize it. 

# My configuration
## OS
macOS 10.15.1

## Result of `(elpy-config)`
```
Emacs.............: 26.3
Elpy..............: 1.32.0
Virtualenv........: None
Interactive Python: python 3.8.0 (/Users/foo/Workspace/tools/python/bin/python)
RPC virtualenv....: rpc-venv (/Users/foo/.emacs.d/elpy/rpc-venv)
 Python...........: python 2.7.16 (/Users/foo/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.15.1
 Rope.............: 0.14.0
 Autopep8.........: 1.4.4
 Yapf.............: 0.28.0
 Black............: Not found (19.10b0 available)
Syntax checker....: Not found (flake8)
```

Currently, I use module 'venv' to create the rpc-venv myself, created the .Python soft link and copied the file 'elpy-rpc-python-path-command' and it worked:

```
Emacs.............: 26.3
Elpy..............: 1.32.0
Virtualenv........: rpc-venv (/Users/foo/.emacs.d/elpy/rpc-venv)
Interactive Python: python 3.8.0 (/Users/foo/.emacs.d/elpy/rpc-venv/bin/python)
RPC virtualenv....: rpc-venv (/Users/foo/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.8.0 (/Users/foo/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.15.1
 Rope.............: 0.14.0
 Autopep8.........: 1.4.4
 Yapf.............: 0.28.0
 Black............: 19.10b0
Syntax checker....: flake8 (/Users/foo/.emacs.d/elpy/rpc-venv/bin/flake8)
```

Can you fix this bug? Thanks.

**Comment by galaunay** [comment]
Hi, 

Except if you want to use black, using python2 or python3 for the RPC will not really change anything (only the module versions matter).
That's why Elpy tries to use the system python for the RPC.

If you still want to use python3.8 for the RPC, you can set `elpy-rpc-python-command` to the full path `/Users/foo/Workspace/tools/python/bin/python`.
The RPC should reinstall itself automatically (if not, use `elpy-rpc-reinstall`).

**Comment by dackon** [comment]
It works. Thank you.

**Comment by dackon** [comment]
@galaunay If I set the variable, deleted the rpc-venv and did the elpy-config again, elpy cannot jump to definitions in the packages installed in the virtual env.

```lisp
(setq elpy-rpc-python-command "/Users/foo/Workspace/tools/python/bin/python")
```

**Comment by galaunay** [comment]
en on a symbol you want to What gives `(elpy-rpc-get-definition)` with the cursor on a symbol with a definition ?

**Comment by dackon** [comment]
Thanks for replay. It's not necessary for elpy to use python 3. It worked fine with python2. Close.
