### ISSUE TITLE
formatting with send-defun-to-shell 

### ISSUE THREAD

**Issue by tensorfoo** [jorgenschaefer/elpy#1725]
Sending a function to the shell works but I was wondering if I could get it to stop showing the 
`...:` lines, and just show the function as it appears in the editor? 

edit. i found the string `"...:'` in `elpy-shell.el` and changed it to the empty string, which fixed that issue but unfortunately it's still showing a large empty space before each line in my function. If I could tell elpy to stop reformatting my code and just show as is, that would be amazing.

edit. ok solved that too by changing the line :
`(prompt (concat (make-string (max 0 (- column 7)) ? ) "...: ")) `
to:
`(prompt "")`
in `elpy-shell--append-to-shell-output` of `elpy-shell.el`.  That was driving me insane!

**Comment by galaunay** [comment]
Sorry I couldn't react faster and help you on this.

The idea was for the code to be aligned with the first line (which is preceded by `>>>`).
If you don't like it, you can set `elpy-shell-echo-input-cont-prompt` to `nil`.

Please re-open if necessary.
