### ISSUE TITLE
Elpy doesn't recognize packages installed with `pip` under `pyenv global`

### ISSUE THREAD

**Issue by mrbig033** [jorgenschaefer/elpy#1736]
# Steps to reproduce

- InstallPyenv with the [pyenv-installer](https://github.com/pyenv/pyenv-installer)
- Add the relevant lines on `.bashrc`:

``` shell
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"
```
- `$ pyenv install 3.8.0 && pyenv global 3.8.0` 
- `$ pip install jedi rope autopep8 yapf black` 
- Verify if executable packages are available in path:

``` shell
$ black 
No Path provided. Nothing to do 😴
$ autopep8 --version
autopep8 1.4.4 (pycodestyle: 2.5.0)
$ yapf --version
yapf 0.29.0
```
- NOTE: this same configuration was working fine on MX Linux 18 with Emacs 27.

# My configuration

- **OS**: MX Linux 19
- **$ uname -r**: 4.19.0-6-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- **i3wm** version 4.16.1 
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- **GNU Emacs** GNU Emacs 26.1 
- [~/.emacs.d](https://github.com/mrbig033/emacs02)
- **pyenv** 1.2.15
- **Elpy** 1.32.0

### Issue

Elpy does not find packages installed using `pip` under `pyenv global`. 

## Result of `(elpy-config)`

```
Elpy Configuration

Emacs.............: 26.1
Elpy..............: Not found (Python), 1.32.0 (Emacs Lisp)
Virtualenv........: None
Interactive Python: python 3.8.0 (/home/jerry/.pyenv/shims/python)
RPC virtualenv....: rpc-venv (/home/jerry/.emacs.d/elpy/rpc-venv)
 Python...........: python nil (/home/jerry/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: Not found
 Rope.............: Not found
 Autopep8.........: Not found
 Yapf.............: Not found
 Black............: Not found
Syntax checker....: Not found (flake8)

Warnings

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The Python interpreter could not find the elpy module. Please report
to: https://github.com/jorgenschaefer/elpy/issues/new.

There was an unexpected problem starting the RPC process. Please check
the following output to see if this makes sense to you. To me, it
doesn't.

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f6ea8ca46c0 (most recent call first):


The jedi package is not available. Completion and code navigation will
not work.

[Install jedi]

The autopep8 package is not available. Commands using this will not
work.

[Install autopep8]

The yapf package is not available. Commands using this will not work.

[Install yapf]

The black package is not available. Commands using this will not work.

[Install black]

The configured syntax checker could not be found. Elpy uses this
program to provide syntax checks of your programs, so you might want
to install one. Elpy by default uses flake8.

[Install flake8]

Options

Square brackets indicate buttons; type RET or click mouse-1 on a
button to invoke its action. Invoke [+] to expand a group, and [-] to
collapse an expanded group. Invoke the [Group], [Face], and [Option]
buttons below to edit that item in another window.

[+]-- [Group] Elpy
[+]-- [Group] Python
[+]-- [Group] Virtual Environments (Pyvenv)
[+]-- [Group] Completion (Company)
[+]-- [Group] Call Signatures (ElDoc)
[+]-- [Group] Inline Errors (Flymake)
[+]-- [Group] Code folding (hideshow)
[+]-- [Group] Snippets (YASnippet)
[+]-- [Group] Directory Grep (rgrep)
[+]-- [Group] Search as You Type (ido)
[+]-- [Group] Django extension
[+]-- [Group] Autodoc extension
```
## Elpy configuration in my init.el

```
(use-package elpy
  :defer t
  :init
  (advice-add 'python-mode :before 'elpy-enable)
  :config

  (defun elpy-goto-definition ()
    (interactive)
    (elpy-rpc-warn-if-jedi-not-available)
    (let ((location (elpy-rpc-get-definition)))
      (if location
          (elpy-goto-location (car location) (cadr location))
        (error "No definition found")))
    (save-excursion
      (evil-scroll-line-to-center 1)))

  (setq elpy-autodoc-delay 3))
```

**Comment by galaunay** [comment]
Elpy now uses a dedicated virtualenv for its python dependencies (black, jedi, yapf, ...).
In your case, this virtualenv is in `/home/jerry/.emacs.d/elpy/rpc-venv`, but the dependencies have not been installed in it.

You can try reinstalling the virtualenv with `M-x elpy-rpc-reinstall-virtualenv`, elpy should ask you at some point if you want to install the dependencies as well.
You can check if everything went fine with `elpy-config`.

If you prefer to go back to the old behaviour (without a dedicated virtualenv for the RPC), you can customize the `elpy-rpc-virtualenv-path` variable:
```elisp
(customize-set-variable 'elpy-rpc-virtualenv-path 'current)
```
Elpy will use jedi, yapf and black from the pyenv environment.

**Comment by mrbig033** [comment]
I see. Now, for some reason, after running `M-x elpy-rpc-reinstall-virtualenv` and before setting `(setq 'elpy-rpc-virtualenv-path 'current)`, `elpy-config` correctly identified all the packages, with the exception of `black`. 

After setting `(setq 'elpy-rpc-virtualenv-path 'current)`, `elpy-config` recognized all packages without exception. 

May I suggest you add a message about this possible setting in the event of similar failures?

Anyway, that is resolved and I'm closing the issue. Thank you very much and keep up the awesome work!
