### ISSUE TITLE
xref buffer not using compilation-line-number face

### ISSUE THREAD

**Issue by hmelman** [jorgenschaefer/elpy#1738]
I noticed in `*xref*` buffers generated by using `M-?` in elpy python buffers, that the line number was in a different color than in `*grep*` buffers.  Tracking it down I think there is a bug in  `elpy-xref--format-references`. It is directly using `font-lock-comment-face` for this.  Instead, `xref` itself uses `'compilation-line-number` face. I think for consistency elpy should do the same, or make it an elpy face that is configurable.

**Comment by galaunay** [comment]
Done (in c7c252dcc73bf817c3b67349720f8e1b29be1277), thanks for noticing.
Please re-open if something wrong.
