### ISSUE TITLE
Multi-step editing operations disrupted by elpy after-change function

### ISSUE THREAD

**Issue by kenmanheimer** [jorgenschaefer/elpy#1742]
# Summary

Multi-step editing operations like query-replace are disrupted by an elpy after-change function, `elpy-folding--mark-foldable-lines`, because it does a search without saving match data.

I've submitted pull request #1741 with a patch that solves the problem.

# Steps to reproduce

In a python-mode buffer with elpy and the `elpy-module-folding` module enabled, do a query replace with multiple matches. After the first replacement I get an error and this message in the mode line:

    replace-match-maybe-edit: Match data clobbered by buffer modification hooks

A stack trace resulting from enabling debug-on-error doesn't reveal which change function is at fault. By wrapping the change functions in `save-match-data` I was able to identify `elpy-module-folding` as the problem. #1741 incorporates the fix.

# My configuration
## OS
Ubuntu 18.04

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.32.0
Virtualenv........: None
Interactive Python: python3 3.6.9 (/usr/bin/python3)
RPC virtualenv....: rpc-venv (/home/klm/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.6.9 (/home/klm/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: 0.15.1 (0.15.2 available)
 Rope.............: 0.14.0
 Autopep8.........: 1.4.4
 Yapf.............: 0.29.0
 Black............: 19.10b0
Syntax checker....: flake8 (/usr/bin/flake8)
```

## Elpy configuration in my init.el
```
 '(elpy-eldoc-show-current-function t)
 '(elpy-modules
   (quote
    (elpy-module-company elpy-module-eldoc elpy-module-folding elpy-module-pyvenv elpy-module-highlight-indentation elpy-module-yasnippet elpy-module-django elpy-module-autodoc elpy-module-sane-defaults)))
 '(elpy-rpc-python-command "python3")
 '(elpy-test-discover-runner-command (quote ("python" "-m" "unittest" "spherical")))
 '(elpy-test-nose-runner-command (quote ("/usr/local/bin/nosetests")))
 '(elpy-test-runner (quote elpy-test-discover-runner))
```

**Comment by galaunay** [comment]
Thanks for getting to the bottom of this.
The PR is merged so I guess it is safe to close this.
Please re-open if not.
