### ISSUE TITLE
Make elpy-shell-send-region-or-buffer switch to *Python* buffer

### ISSUE THREAD

**Issue by notuntoward** [jorgenschaefer/elpy#1743]
After I run `elpy-shell-send-region-or-buffer` (and related functions like `elpy-shell-send-region-or-buffer-and-step`), my next step is almost always to switch to the *Python* buffer.  

If` elpy-shell-display-buffer-after-send`is true, the the *Python* buffer is started and displayed very conveniently.

The only thing missing is that the mouse cursor isn't switched to it.  Is it possible to do do this switch  automatically, after the send?

**Comment by galaunay** [comment]
I think you are looking for `elpy-shell-send-region-or-buffer-and-go`, which is bound to `C-c C-y R` by default.

**Comment by notuntoward** [comment]
Yes, I see that I am.  Thanks!
