### ISSUE TITLE
Way to not bind C-<up> and C-<down>

### ISSUE THREAD

**Issue by Holt59** [jorgenschaefer/elpy#1750]
Is there a way to bind `C-<up>` and `C-<down>` to their original `forward-paragraph` and `backward-paragraph` while using the `use-package` set-up? I tried using `bind:` but it does not work:

```
(use-package elpy
    :defer t
    :bind
    (("M-/" . elpy-company-backend)
     ("C-<up>" . backward-paragraph)
     ("C-<down>" . forward-paragraph)
     ("C-<prior>" . elpy-nav-forward-block)
     ("C-<prev>" . elpy-nav-backward-block))
     ...
)
```

The `C-<prior>` and `C-<prev>` binds work as expected, but the `C-<up>` and `C-<down>` do not override elpy ones.

**Comment by galaunay** [comment]
`:bind` adds the keybinding to the global keymap.
But what you want is to modify Elpy's keymap.
Something like this should do the trick:
``` elisp
(use-package elpy
    :defer t
    :bind
    (("M-/" . elpy-company-backend)
     ("C-<prior>" . elpy-nav-forward-block)
     ("C-<prev>" . elpy-nav-backward-block)
     :map elpy-mode-map
     ("C-<up>" . nil)
     ("C-<down>" . nil)))
```
This will remove the `C-<up>` and `C-<down>` keybindings from Elpy keymap.

**Comment by Holt59** [comment]
Thanks, work perfectly!
