### ISSUE TITLE
Python interpreter could not find the elpy module

### ISSUE THREAD

**Issue by ppublicgit** [jorgenschaefer/elpy#1757]
I am trying to setup emacs with elpy for python development. I have browsed and attempted to copy solutions to some similar problems but have been unable to fix the issue of python not finding the elpy module. I have created a virtual environment for python with elpy installed (I can find it in my .virtualenvs/main/lib/python3.8/site-packages directory) but elpy-config shows that elpy is not found. I have tried several fixes but none have worked. I came across the post https://github.com/jorgenschaefer/elpy/issues/1588 and tried using the solution of changing the elpy.el file by changing the elpy-config--get-config function to use requests instead of urllib but to no avail.

# My configuration
## Result of `(elpy-config)`
```
Emacs.............: 26.3
Elpy..............: Not found (Python), 1.32.0 (Emacs Lisp)
Virtualenv........:  (/home/p/.virtualenvs/main/)
Interactive Python: jupyter . (/home/p/.virtualenvs/main/bin/jupyter)
RPC virtualenv....: main (/home/p/.virtualenvs/main)
 Python...........: python 3.8.1 (/home/p/.virtualenvs/main/bin/python)
 Jedi.............: 0.16.0
 Rope.............: 0.16.0
 Autopep8.........: 1.5
 Yapf.............: 0.29.0
 Black............: 19.10b0
Syntax checker....: flake8 (/home/p/.virtualenvs/main/bin/flake8)
```

## Elpy configuration in my init.el
```
;; Enable elpy
(pyvenv-activate "~/.virtualenvs/main/")
;;(setq elpy-rpc-python-command "python")
(setq elpy-rpc-virtualenv-path 'current)
(elpy-enable)


;; Use IPython for REPL
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")



;; Enable Flycheck
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))
```

**Comment by galaunay** [comment]
If ulrlib2 is the problem (as for #1588), you can try adding this (sorry it is a bit long) to your init.el (after `elpy-enable`):
```elisp
(setq elpy-config--get-config "import json
import sys
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)

from distutils.version import LooseVersion


def latest(package, version=None):
    return None


config = {}
config['rpc_python_version'] = ('{major}.{minor}.{micro}'
                            .format(major=sys.version_info[0],
                                    minor=sys.version_info[1],
                                    micro=sys.version_info[2]))

try:
    import elpy
    config['elpy_version'] = elpy.__version__
except:
    config['elpy_version'] = None

try:
    import jedi
    if isinstance(jedi.__version__, tuple):
        config['jedi_version'] = '.'.join(str(x) for x in jedi.__version__)
    else:
        config['jedi_version'] = jedi.__version__
    config['jedi_latest'] = latest('jedi', config['jedi_version'])
except:
    config['jedi_version'] = None
    config['jedi_latest'] = latest('jedi')

try:
    import rope
    config['rope_version'] = rope.VERSION
    if sys.version_info[0] <= 2:
        config['rope_latest'] = latest('rope', config['rope_version'])
    else:
        config['rope_latest'] = latest('rope_py3k', config['rope_version'])
except:
    config['rope_version'] = None
    config['rope_latest'] = latest('rope')

try:
    import autopep8
    config['autopep8_version'] = autopep8.__version__
    config['autopep8_latest'] = latest('autopep8', config['autopep8_version'])
except:
    config['autopep8_version'] = None
    config['autopep8_latest'] = latest('autopep8')

try:
    import yapf
    config['yapf_version'] = yapf.__version__
    config['yapf_latest'] = latest('yapf', config['yapf_version'])
except:
    config['yapf_version'] = None
    config['yapf_latest'] = latest('yapf')

try:
    import black
    config['black_version'] = black.__version__
    config['black_latest'] = latest('black', config['black_version'])
except:
    config['black_version'] = None
    config['black_latest'] = latest('black')

json.dump(config, sys.stdout)
")
``` 

If it fixes your problem, we can have a go at changing from urllib2 to request.

**Comment by ppublicgit** [comment]
I added the code you have posted but still the elpy-config says elpy not found for python. I opened a python shell in the virtual environment being used and tried to import elpy. This worked, but elpy.__version__ return an error saying "AttributeError: module 'elpy' has no attribute '__version__'". I tried importing jedi and calling .__version__ on that add it properly returned the version of jedi. Is there somewhere else I should be installing elpy from other than pip install? Calling dir(elpy) reveals that elpy only has the following methods:
__builtins__, __cached__, __doc__, __file__, __loader__, __name__, __package__, __path__, __spec__. 
The __init__.py file is empty as well. It appears from issue #1583 that the pypi package is meant to be empty, so maybe this is as expected. How is the elpy package supposed to be installed then? From issue #1583 it seems that it should be installed automatically by elpy, however when I remove elpy from my main virtualenv and delete and reinstall the elpy package in emacs, elpy is not installed automatically. When I try and write python code I constantly get an error message from elpy output saying "/home/p/.virtualenvs/main/bin/python: Error while finding module specification for 'elpy.__main__' (ModuleNotFoundError: No module named 'elpy')/home/p/.virtualenvs/main/bin/python: Error while finding module specification for 'elpy.__main__' (ModuleNotFoundError: No module named 'elpy')".

**Comment by ppublicgit** [comment]
I did not realize that surrounding a word with double underscore bolds the word, all bolded words are really double underscored before and after.

**Comment by galaunay** [comment]
The elpy python package is now shipped with elpy when you install it from melpa. You should be able to find it in `~/.emacs.d/elpa/elpy/elpy` (or similar).
The package on pypi is indeed empty and is just here to prevent breaking user's configurations (you should uninstall it).

To be sure python is able to find the elpy python package, elpy adds its path to PYTHONPATH before starting the RPC process. Apparently, there is something going wrong for you at this stage.
Could you post the result of `M-: (elpy-rpc--environment)` ?

ps: on github you can surround your code with backticks (`) to prevent special characters (such as __) to be interpreted.

**Comment by ppublicgit** [comment]
I removed the pip package for elpy and checked the location you mentioned and there is the elpy module in there.

The ouput of M-: (elpy-rpc--environment) : 

("VIRTUAL_ENV=/home/p/.virtualenvs/main/" "PATH=/home/p/.virtualenvs/main//bin:/home/p/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin" "PYTHONHOME" "_=/usr/bin/emacs" "KONSOLE_DBUS_WINDOW=/Windows/1" "OLDPWD=/home/p/.emacs.d/elpa/elpy-20200202.2031" "LC_NUMERIC=en_US.UTF-8" "MAIL=/var/spool/mail/p" "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus" "PATH=/home/p/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin" "KDE_FULL_SESSION=true" "XDG_DATA_DIRS=/home/p/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop" ...)

I checked my pythonpath in my virutalenv called main and it is empty. I also looked at the elpy-config -Group Elpy -Option Elpy RPC Pythonpath and it shows it as empty. I manually added the path to the elpy module in this easy configuration and it now seems to work (elpy-config shows Elpy...: 1.32.0 now instead of the Not Found python). So it appears that this path is never added. This fix works for now but any update to elpy will break it as the elpy-### will change. Not sure what  to do from here but at least it is up and running and seems to be working while I have played around a little with a few python scripts.


On a different note, now that it seems to work, I was hoping to have python code blackened on save and online it seems that elpy is supposed to auto enable this? However, my code is not blackened on save, but using C-C C-R f does blacken the code fine. How do I enable this feature? I cannot seem to find it in the docs, or in the easy configuration or online.

Thank you for all the help.

**Comment by galaunay** [comment]
> I also looked at the elpy-config -Group Elpy -Option Elpy RPC Pythonpath and it shows it as empty.

So here is the problem.
This variable is supposed to be initialised to the elpy library path automatically.
It uses the following code:
``` elisp
(setq elpy-rpc-pythonpath (file-name-directory (locate-library "elpy")))
```
In your case, it appears to return `nil`...
What does `(locate-library "elpy")` returns for you ?

> I was hoping to have python code blackened on save and online it seems that elpy is supposed to auto enable this?

It was in the documentation at some point, but was apparently lost during cleanup.
I added it back, you can find the snippet you need [here](https://elpy.readthedocs.io/en/latest/customization_tips.html#auto-format-code-on-save).

**Comment by ppublicgit** [comment]
Sorry for the delayed response. The call to (locate-library "elpy") returns /home/p/.emacs.d/elpa/elpy-#####/elpy.elc

**Comment by galaunay** [comment]
Ok, so this does work.
You should have the Elpy's python files under `/home/p/.emacs.d/elpa/elpy-#####/elpy/`.

I wrote an instrumented version `elpy-rpc-environment` (which seems to be at the origin of the issue):
``` elisp
(defun elpy-rpc--environment ()
  "Return a `process-environment' for the RPC process.

This includes `elpy-rpc-pythonpath' in the PYTHONPATH, if set."
  (message "\n\n=== DEBUG 'elpy-rpc--environment ===\n")
  (message "elpy-rpc-pythonpath: %s" elpy-rpc-pythonpath)
  (message "__init__.py: %s" (expand-file-name "elpy/__init__.py"
                                                elpy-rpc-pythonpath))
  (message "__init__.py exists ?: %s" (file-exists-p (expand-file-name
                                                      "elpy/__init__.py"
                                                      elpy-rpc-pythonpath)))
  (if (or (not elpy-rpc-pythonpath)
          (not (file-exists-p (expand-file-name "elpy/__init__.py"
                                                elpy-rpc-pythonpath))))
      process-environment
    (let* ((old-pythonpath (getenv "PYTHONPATH"))
           (new-pythonpath (if old-pythonpath
                               (concat elpy-rpc-pythonpath
                                       path-separator
                                       old-pythonpath)
                             elpy-rpc-pythonpath)))
      (message "old-pythonpath: %s" old-pythonpath)
      (message "new-pythonpath: %s" new-pythonpath)
      (cons (concat "PYTHONPATH=" new-pythonpath)
            (append process-environment
                    (when (and (string-equal system-type "windows-nt")
                               (>= (string-match-p
                                    (regexp-quote "utf-8")
                                    (format "%s" buffer-file-coding-system))) 0)
                      (list
                       "PYTHONIOENCODING=utf-8"
                       "PYTHONLEGACYWINDOWSSTDIO=1")))))))
(message "%s" (elpy-rpc--environment))

```
If you run this snippet, it will display some messages in your `*messages*` buffer that should help us understand.

ps: If there is sensitive information in the environment variables, please remove them, only the `PYTHONPATH` variable matters here.

**Comment by ppublicgit** [comment]
There is no PYTHONPATH variable. I have PATH and PYTHONHOME but no PYTHONPATH.

PYTHONHOME only points to /usr.bin/emacs. 

If I do echo $PYTHONPATH in a bash terminal I get nothing. It seems I do not have a PYTHONPATH set.

**Comment by galaunay** [comment]
So the problem most probably comes from the function `elpy-rpc--environment`.
what is the output of the instrumented function I gave you earlier ?

**Comment by ppublicgit** [comment]
(PYTHONPATH=/home/p/.emacs.d/elpa/elpy-20200323.1647 TERM=dumb VIRTUAL_ENV=/home/p/.virtualenvs/main/ PATH=/home/p/.virtualenvs/main//bin:/home/p/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl PYTHONHOME LC_NUMERIC=en_US.UTF-8 PATH=/home/p/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl XDG_DATA_DIRS=/home/p/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share LC_TIME=en_US.UTF-8 ...)

**Comment by ppublicgit** [comment]
This is what it outputs as of now (note I have the rpc-pythonpath hard coded in the elpy-config).

**Comment by galaunay** [comment]
It should display a bunch of lines starting with `=== DEBUG 'elpy-rpc--environment ===` in your `*Messages*` buffer as well.

**Comment by ppublicgit** [comment]
I must have ran the snippet incorrectly. I reran it now and this was the output:

=== DEBUG ’elpy-rpc--environment ===

elpy-rpc-pythonpath: /home/p/.emacs.d/elpa/elpy-20200323.1647
__init__.py: /home/p/.emacs.d/elpa/elpy-20200323.1647/elpy/__init__.py
__init__.py exists ?: t
old-pythonpath: nil
new-pythonpath: /home/p/.emacs.d/elpa/elpy-20200323.1647
(PYTHONPATH=/home/p/.emacs.d/elpa/elpy-20200323.1647 TERM=dumb VIRTUAL_ENV=/home/p/.virtualenvs/main/ PATH=/home/p/.virtualenvs/main//bin

**Comment by galaunay** [comment]
I am a bit puzzled, because everything looks fine.

What happen if you run this ?
```elisp
(setq elpy-rpc-pythonpath (file-name-directory (locate-library "elpy")))
(message "elpy-rpc-pythonpath: %s" elpy-rpc-pythonpath)
(message "(elpy-rpc--environment: %s" (elpy-rpc--environment))
```

**Comment by ppublicgit** [comment]
I think it looks fine because I have hard coded in the the rpc-pythonpath in the elpy-config. I removed my hardcoded path, uninstalled the elpy package, reinstalled the elpy package and it was unable to find elpy python again. The elpy-rpc-environment function now returns:

=== DEBUG ’elpy-rpc--environment ===

elpy-rpc-pythonpath: 
__init__.py: /home/p/elpy/__init__.py
__init__.py exists ?: nil
(TERM=dumb VIRTUAL_ENV=/home/p/.virtualenvs/main/ PATH=/home/p/.virtualenvs/main//bin:/home/p/.local/bin...

If I go back to elpy-config and hardcode in the path to the new package (/home/p/.emacs.d/elpa/elpy#### then the function call for elpy-rpc-environment correctly finds the path again:

=== DEBUG ’elpy-rpc--environment ===

elpy-rpc-pythonpath: /home/p/.emacs.d/elpa/elpy-20200329.1830
__init__.py: /home/p/.emacs.d/elpa/elpy-20200329.1830/elpy/__init__.py
__init__.py exists ?: t
old-pythonpath: nil
new-pythonpath: /home/p/.emacs.d/elpa/elpy-20200329.1830
(PYTHONPATH=/home/p/.emacs.d/elpa/elpy-20200329.1830 TERM=dumb VIRTUAL_ENV=/home/p/.virtualenvs/main/ PATH=/home/p/.virtualenvs/main//bin:/home/p/.local/bin:

So elpy is unable to find the path to the elpy module and add itself to the pythonpath unless I manually enter the path into rpc-pythonpath environment variable in the elpy-config.

**Comment by galaunay** [comment]
Something is probably going wrong during elpy loading and `elpy-rpc-pythonpath` is not set properly.

As `(locate "elpy")` was working for you, it should be enough to just add :
``` elisp
(setq elpy-rpc-pythonpath (file-name-directory (locate-library "elpy")))
```
in your config after `(elpy-enable)`.

**Comment by ppublicgit** [comment]
If I run the snippet by pressing M-: and running the the call (setq elpy-rpc-pythonpath (file-name-directory (locate-library "elpy"))) then it properly sets the rpc-pythonpath. However, if I have it in my init file it does not actually run the function for some reason. I am not sure how to fix this (I have tried putting the call before and after elpy-enable, but to no avail). At this point, the fact that I can at least make elpy path work by manually running the function makes me content. I do not think it is necessary for you to continue troubleshooting my setup. Thanks for all the help.

**Comment by galaunay** [comment]
I am closing this issue then.

Please let me know if you finally find the reason why
