### ISSUE TITLE
tell me which formatter was used by elpy-format-code

### ISSUE THREAD

**Issue by anarcat** [jorgenschaefer/elpy#1762]
It would be great if elpy would tell me which formatter was picked when i run `elpy-format-code`.

Right now it *seems* to pick "black" here, but I actually have no idea.

could the fix be as simple as:

```diff
modified   elpy.el
@@ -2250,6 +2250,7 @@ root directory."
 
 (defun elpy--fix-code-with-formatter (method)
   "Common routine for formatting python code."
+  (message "fixing code with formatter %s" method)
   (let ((line (line-number-at-pos))
         (col (current-column))
         (directory (if (elpy-project-root)
```

thanks!

**Comment by galaunay** [comment]
Great idea, thanks.

Is has been added in 782e93d7d74bd9b6128a7191149291732df25dd4.
