### ISSUE TITLE
Cannot run `elpy-rpc-reinstall-virtualenv` succesfully

### ISSUE THREAD

**Issue by avocadoras** [jorgenschaefer/elpy#1766]
# Summary

I'm getting this warning message on Elpy 
```
Pip doesn't seem to be installed in the dedicated virtualenv created
by Elpy (/). This will prevent some features from working properly
(completion, documentation, reformatting, ...). You can try
reinstalling the virtualenv with `elpy-rpc-reinstall-virtualenv'. If
the problem persists, please report on Elpy's github page.
```

I tried running the command per usual `M-x elpy-rpc-reinstall-virtualenv`, but I got this error message
```
elpy-rpc-reinstall-virtualenv: Cannot reinstall the system environment, please reinstall the necessary packages manually
```

# Steps to reproduce
`M-x elpy-rpc-reinstall-virtualenv`

# My configuration
## OS
Ubuntu 19

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.32.0
Virtualenv........: None
Interactive Python: python3 3.7.5 (/usr/bin/python3)
RPC virtualenv....: system (/)
 Python...........: python3 3.7.5 (//bin/python3)
 Jedi.............: 0.16.0
 Rope.............: 0.14.0
 Autopep8.........: 1.5
 Yapf.............: 0.29.0
 Black............: 19.10b0
Syntax checker....: flake8 (/home/thecomputer/.local/bin/flake8)

Warnings

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

Pip doesn't seem to be installed in the dedicated virtualenv created
by Elpy (/). This will prevent some features from working properly
(completion, documentation, reformatting, ...). You can try
reinstalling the virtualenv with `elpy-rpc-reinstall-virtualenv'. If
the problem persists, please report on Elpy's github page.
```
## Elpy configuration in my init.el

```elisp
(elpy-enable)
(defalias 'workon 'pyvenv-workon)

(setq python-shell-interpreter "python3"
      elpy-rpc-python-command "python3"
      python-shell-interpreter-args "-i")

(defun elpy-django-command (cmd)
  "Prompt user for Django command. If called with `C-u',
    it will prompt for other flags/arguments to run."
  (interactive (list (completing-read "Command: " (elpy-django--get-commands) nil nil)))
  ;; Called with C-u, variable is set or is a cmd that requires an argument
  (when (or current-prefix-arg
            elpy-django-always-prompt
            (member cmd elpy-django-commands-with-req-arg))
    (setq cmd (concat cmd " " (read-shell-command (concat cmd ": ") "--noinput"))))
  (if (string= cmd "shell")
      (run-python (concat elpy-django-command " " cmd " -i python")
                  t t)
    (compile (concat elpy-django-command " " cmd))))
```

**Comment by galaunay** [comment]
You seem to have `elpy-rpc-virtualenv-path` set to `'system` (or `'global` maybe).
In that case, Elpy doesn't really need pip (it only needs it when you use the dedicated virtualenv).

I updated `elpy-config` so that it won't show the message anymore.

Is everything working as expected (completion, code execution, documentation, ...) ?

**Comment by avocadoras** [comment]
@galaunay yes, I just checked and it's set to `system`. How is this set? I remember I had to install Elpy on a different computer and the `.emacs.d/elpy` dir got created automatically, without needing to install the dev packages. I'm guessing that since I installed them on this computer with `--user` with `pip`, Elpy knows about them? 

Btw, I had not used Elpy for a while until now, I'm guessing now you can install the dev packages like `jedi` globally and activate a `virutalenv` and not need to reinstall the dev packages again??

**Comment by galaunay** [comment]
The variable `elpy-rpc-virtualenv-path` has to be set manually (with `customize-variable`).
It basically controls where Elpy looks for its python dependencies.

If it is set to `'system`, Elpy will try to find the python packages it needs in the system environment (so if you already have them installed globally, it will work right away).

If it is set to `'default`, Elpy will install all its dependencies in a dedicated virtualenv in `$HOME/.emacs/elpy/rpc-venv`. It is more convenient if you don't want to make modifications to your system.

> Btw, I had not used Elpy for a while until now. 'm guessing now you can install the dev packages like jedi globally and activate a virutalenv and not need to reinstall the dev packages again??

That was the point, yes, you don't need to install jedi and everything else in every virtualenv.

**Comment by avocadoras** [comment]
Very cool. Thanks!
