### ISSUE TITLE
[Feature Request] "elpy-mark-function-dwim" to mark Python function declaration

### ISSUE THREAD

**Issue by avocadoras** [jorgenschaefer/elpy#1772]
# Summary
I have tried to explore the available elpy functions with `C-h f` and I see no function to mark the current function. 

Emacs has a function that marks the whole function with `C-M-h` (`mark-defun`). It is very useful when trying to copy paste or eval the current region. 

I'd like to know if there could be something similar in Elpy; I'd like for Elpy to have a function that marks the entire function declaration of `def`. The reason is that I use `C-c C-y r` or `C-c C-y R` alot, but find myself having to highlight the function manually. I'd be a plus if, let's say, the point is somewhere inside the function declaration and you could call something like `elpy-mark-def-dwim` and highlight the entire function declaration on point.

I'm very bad at Elisp and cannot, unfortunately, implement this myself :/.

**Comment by galaunay** [comment]
`C-M-h` should work in python buffers as well.
By default, it calls `python-mark-defun`, which should do what you want.

You may also find useful `elpy-shell-send-defun` (bound to `C-c C-y f`) that directly send the current function to the python shell.

**Comment by avocadoras** [comment]
@galaunay thanks. They do what I need. I'll close this issue.
