### ISSUE TITLE
hiding docstrings

### ISSUE THREAD

**Issue by drdv** [jorgenschaefer/elpy#1774]
`elpy-info-docstring-p` doesn't handle functions whose signature is on several lines, e.g.,

```
def test(argument1,
         argument2):
    """Test function."""
```
The function `python-info-docstring-p` (in `python.el`) doesn't have this problem. Is there any reason not to use it directly?

**Comment by galaunay** [comment]
I guess there was one at some point.

But you are right that it works better with `python-info-docstring-p`.
I made a PR to make the switch.

**Comment by drdv** [comment]
Thanks. I am closing this one. I left a question at #1776
