### ISSUE TITLE
Dead link to external resource

### ISSUE THREAD

**Issue by panoptimum** [jorgenschaefer/elpy#1775]
# Summary

README.rst - External Resources
The link to the article "Emacs: The Best Python Editor? by Sean Wade" is dead.
That article was an unauthorized repost of https://realpython.com/emacs-the-best-python-editor/
Please link to the original article. 

# Steps to reproduce
For details see the comments section at https://irreal.org/blog/?p=8779

**Comment by galaunay** [comment]
Thanks for letting us know, I fixed this.
I'll have to be more careful in the future...
