### ISSUE TITLE
flake8 / flake8_nb with .ipyn notebooks

### ISSUE THREAD

**Issue by alpresci** [jorgenschaefer/elpy#1778]
# Summary

flake8 does not work properly with .pynb notebook files. 
I have also found that flake8_nb does work well with those notebooks.

# Steps to reproduce
Inside Emacs python-flake8 finds an error at the beginning of the file because of the ln[]: code and then stops there.

From a shell: flake8 notebookname.ipynb has the same problem
but
 flake8_nb notebookname.ipynb  - from the same shell - works properly

Is there a way to either use flake8_nb instead of flake8 when I work on jupyter notebook .ipynb files OR to make flake8 to work well with them?

thanks a lot for your help!

# My configuration
## MacOS Catalina 10.15.4
GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
 of 2019-09-02

## Result of `(elpy-config)`
```
# Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.33.0
Virtualenv........: None
Interactive Python: python 3.7.6 (/Users/prescimo/anaconda3/bin/python)
RPC virtualenv....: rpc-venv (/Users/prescimo/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.7.6 (/Users/prescimo/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.17.0
 Rope.............: 0.16.0
 Autopep8.........: 1.5.1
 Yapf.............: 0.29.0
 Black............: 19.10b0
Syntax checker....: flake8 (/Users/prescimo/anaconda3/bin/flake8)

Warnings
You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.
```

## Elpy configuration in my init.el
```
(use-package elpy
  :ensure t
  :init
  (elpy-enable)
  (setq elpy-rpc-backend "jedi"))

(when(require 'ein)
(setq ein:use-auto-complete-superpack t))
(add-hook 'ein:connect-mode-hook 'ein:jedi-setup)
(add-hook 'ein:connect-mode-hook 'ein:ac-setup)

(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))
```

**Comment by galaunay** [comment]
I had no idea Elpy could be used within EIN.

You can change the syntax checker elpy uses by customising the variable `elpy-syntax-check-command` (something like `(setq elpy-syntax-check-command "flake8_nb")` should do).

**Comment by alpresci** [comment]
thanks!

**Comment by galaunay** [comment]
You are welcome.

I am closing this, please re-open if needed !
