### ISSUE TITLE
Cannot enter elpy-config

### ISSUE THREAD

**Issue by Evangeline-T** [jorgenschaefer/elpy#1780]
# Summary
I tried to setup elpy(1.33.0) in emacs(26.3)  following https://east.fm/posts/configuring-gnu-emacs-with-elpy-on-macos/index.html.

Here is some background information.
**Python version:**  I installed installed python 2.7 under system folder (\User\bin\python) and python 3.7 under /opt/anaconda3/bin/python3. 
- Emacs's python-mode chooses python 2.7 as default.
- I build my_venv using python3 -m venv /project/my_venv in terminal. This should make the python version under this virtual environment be 3.7. 

After I activated my_venv by: M-x pyvenv-activate RET ~/project/my_venv, I got an error message when I tried to enter elpy-config by M-x elpy-config. It says:
```
"Elpy needs the ’virtualenv’ or ’venv’ python packages to create its virtualenv. 
Please install one of them or disable the dedicated virtualenv with ‘(setq elpy-rpc-virtualenv-path ’current)‘"
```

However, 
- I can run code in Emacs's python-mode. 
- And M-: pyvenv-virtual-env-name RET gives me "my_venv".

I am confused about the error message.

# Steps to reproduce
Install python2.7 in global system and python 3.7 in /opt/anaconda3/bin/
Use python3 -m venv /project/my_venv to build a virtual environment

Install Emacs 26.3, install elpy (1.33.0)
Copy my elpy-config to emacs's init.el file

Restart Emacs
M-x pyvenv-activate RET /project/my_venv RET
M-x elpy-config.

# My configuration
## OS
macOS High Sierra Version 10.13.6

## Result of `(elpy-config)`
```
Cannot enter elpy-config
```

## Elpy configuration in my init.el
```
(use-package elpy
  :ensure t
  :defer t
  :init
  (advice-add 'python-mode :before 'elpy-enable))
```

**Comment by Evangeline-T** [comment]
I find solution in [ documentation of Elpy 1.33.0](https://elpy.readthedocs.io/en/latest/concepts.html)

In explanation of elpy-rpc-python-command (Customize Option). It says: 
> The Python interpreter Elpy should use to run the RPC process. This defaults to "python", which should be correct for most cases.
> Please` do note that this is not an interactive interpreter, so do not set this to "ipython", "jupyter" or similar.
> As the RPC should be independent of any virtual environment, Elpy will try to use the system interpreter if it exists. If you wish to use a specific python interpreter (from a virtual environment for example), set this to the full interpreter path.

So, if I want elpy use specific python interpreter I should set this to the full interpreter path.

Then I changed my elpy-config in init.el into:
```
(use-package` elpy
  :ensure t
  :defer t
  :init
  (advice-add 'python-mode :before 'elpy-enable)
  :config
  (setq elpy-shell-echo-output nil)   ;; This solve strange '^G's in Ipython output.
  (setq elpy-rpc-python-command "/your/path/to/python"
	python-shell-interpreter "/your/path/to/ipython"
	python-shell-interpreter-args "-i --simple-prompt"))
```

Voilà! It works nice for now.

**Comment by galaunay** [comment]
Glad you found a solution, and thanks for the feedback !
