### ISSUE TITLE
No Completion Until I run elpy-company-backend

### ISSUE THREAD

**Issue by hnisonoff** [jorgenschaefer/elpy#1781]
# Summary
I currently do not get any completion. After I run elpy-company-backend, however, I get completion all the time. My understanding was that this command gives you completion at point but for me it appears to globally turn automatic completion on. How do I have this on by default so that I do not have to run the command when I open a new file?
open python file (no completion)
run `M-x elpy-company-backend`
Now I have completion all the time

# My configuration
## OS
macOS Catalina

## Result of `(elpy-config)`
```
Emacs.............: 26.3
Elpy..............: 1.33.0
Virtualenv........: openmm (/Users/hunternisonoff/anaconda3/envs/openmm)
Interactive Python: ipython 7.13.0 (/Users/hunternisonoff/anaconda3/envs/openmm/bin/ipython)
RPC virtualenv....: rpc-venv (/Users/hunternisonoff/.emacs.d/elpy/rpc-venv)
 Python...........: python 2.7.16 (/Users/hunternisonoff/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.17.0
 Rope.............: Not found (0.16.0 available)
 Autopep8.........: Not found (1.5.2 available)
 Yapf.............: Not found (0.29.0 available)
 Black............: Not found (19.10b0 available)
Syntax checker....: flake8 (/Users/hunternisonoff/anaconda3/envs/openmm/bin/flake8)
```

## Elpy configuration in my init.el
```
    (use-package elpy
      :ensure t
      :init
      (elpy-enable))

    (use-package company
    :ensure t
    :config
    (setq company-idle-delay 0)
    (add-hook 'after-init-hook 'global-company-mode)
    ;;(setq company-minimum-prefix-length 3)
    )

```

**Comment by galaunay** [comment]
Sometimes (depending on the buffer your are in), it takes some times for Elpy to initialize and get the completion candidates.
During this time, you will not have any completion while typing.

Could it be just that for you ? or is the completion really doesn't work even after typing a while ?

**Comment by Cerebus** [comment]
Having a similar problem on emacs-27.1-rc1.  I get no completion popup, ever; I have to run eply-company-backend explicitly.  Completion suggestions are always correct for the context, they just don't appear automatically.

**Comment by galaunay** [comment]
That is probably a problem with company then. Here are few things you could check:
- Is the company module activated (it should appear in the `elpy-modules` list).
- Is `company-idle-delay` set to a value (typically 0.1 or 0.5 )
- Is company activated in your python buffers (`M-x company-mode` will tell)

If everything is fine, do you have company working in other modes ?

**Comment by Cerebus** [comment]
This turned out to be a Doom problem.  Fix was:
```emacs-lisp
(after! elpy
  (set-company-backend! 'elpy-mode
    '(elpy-company-backend :with company-files company-yasnippet)))
```

**Comment by galaunay** [comment]
Good to known, thanks for the feedback.
