### ISSUE TITLE
Switching between python interpreters

### ISSUE THREAD

**Issue by Nathan-Furnal** [jorgenschaefer/elpy#1783]
This is not a bug,

I was wondering if there were an easy way to switch interpreters for the following logic : 

During data analysis, one might want to play around with a jupyter notebook and plot the data, reshape it, etc while once it's done ; create a python file which is the modeling or the data pipeline proper.

My elisp is terrible but basically it would be an interactive function which would allow different sessions for different files if that make sense something like ``M-x elpy-switch-interpreter``

Thanks for the very good package !

**Comment by galaunay** [comment]
[`elpy-shell-toggle-dedicated-shell`](https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-shell-toggle-dedicated-shell) and [`elpy-shell-set-local-shell`](https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-shell-set-local-shell) may be what you are looking for.

`M-x elpy-shell-toggle-dedicated-shell` will tell the current buffer to use a dedicate shell.
`M-x elpy-shell-set-local-shell` will ask for a shell name and tell the current buffer to use it. This way you can still have multiple python buffer using the same shell.

Hope it helps.

**Comment by Nathan-Furnal** [comment]
Thanks, that makes sense!
