### ISSUE TITLE
RPC error when opening the first Python file

### ISSUE THREAD

**Issue by liZe** [jorgenschaefer/elpy#1793]
# Summary

Each time I open emacs, elpy doesn’t work when I open my first Python file. Flake is not automatically launched and autodoc fails each time the autodoc delay is reached.

I get this error each time autodoc is launched:
```
error in process filter: elpy-rpc--default-error-callback: Wrong number of arguments: (0 . 0), 2
error in process filter: Wrong number of arguments: (0 . 0), 2
```

Restarting RPC doesn’t fix the problem.

This bug only happens with the first Python file I open. If I close this buffer and reopen the file, or if I open other files, elpy works. 

# Steps to reproduce

- Open emacs
- Open a Python file

# My configuration
## OS
Linux (Gentoo)

## Result of `(elpy-config)`
```
Emacs.............: 26.3
Elpy..............: 1.33.0
Virtualenv........: None
Interactive Python: python 3.7.7 (/usr/bin/python)
RPC virtualenv....: rpc-venv (/home/lize/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.7.7 (/home/lize/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.17.0
 Rope.............: 0.17.0
 Autopep8.........: 1.5.2
 Yapf.............: 0.30.0
 Black............: 19.10b0
Syntax checker....: flake8 (/usr/bin/flake8)
```

## Elpy configuration in my init.el
```
(add-hook 'python-mode-hook 'elpy-mode)
```

**Comment by galaunay** [comment]
Elpy needs to be enabled with `(elpy-enable)` to work properly (see [the doc](https://elpy.readthedocs.io/en/latest/introduction.html#installation)).
This will automatically add the necessary function to `'python-mode-hook` as well.

It may not be the cause of your issue, but it is a good first thing to try.

**Comment by liZe** [comment]
> Elpy needs to be enabled with `(elpy-enable)` to work properly (see [the doc](https://elpy.readthedocs.io/en/latest/introduction.html#installation)).

It works. Thanks a lot, I should have read the documentation more carefully. :pray:

**Comment by galaunay** [comment]
You are welcome. 
I added a warning to ensure this will not happen for somebody else.
