### ISSUE TITLE
Invalid function error when calling elpy-format-code

### ISSUE THREAD

**Issue by tbetcke** [jorgenschaefer/elpy#1798]
# Summary
When running elpy-format-code I obtain the error message
Invalid function: (when (interactive-p) message "Autoformatting code with black.")

elpy-config:

Emacs.............: 26.3
Elpy..............: 1.33.0
Virtualenv........: None
Interactive Python: python 3.8.2 (/usr/bin/python)
RPC virtualenv....: rpc-venv (/home/betcke/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.8.2 (/home/betcke/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.17.0
 Rope.............: 0.17.0
 Autopep8.........: Not found (1.5.2 available)
 Yapf.............: Not found (0.30.0 available)
 Black............: 19.10b0
Syntax checker....: Not found (flake8)

**Comment by galaunay** [comment]
It is fixed in the last version (1.34.0, just released today).
Please update and re-open if the issue still exists.
