### ISSUE TITLE
Disable electric-indent-mode during mouse-yank-primary?

### ISSUE THREAD

**Issue by JulienPalard** [jorgenschaefer/elpy#1799]
# Summary

When I paste Python code to an elpy-enabled buffer, indentation get messed up, due to electric-indent-mode.

Currently when I paste I either suspend emacs, use `cat >> the_file.py`, or use `M-x e-i-m` to disable `electric-indent-mode`, then paste, then `M-x e-i-m` again to re-enable it, both ways are non-optional.

If elpy could replace `mouse-yank-primary` to a function that temporarily disable `electric-indent-mode`, I think it would fix the issue.

# Steps to reproduce

1. emacs /tmp/foo.py
2. copy the following code and paste it to your emacs using middle-click

```
def foo():
    ...
def bar():
    ...
def baz():
    ...
```

It gives:

```
def foo():
        ...
        def bar():
                ...
                def baz():
                        ...
```

# My configuration
## OS

Debian bullseye

## Result of `(elpy-config)`
```
Emacs.............: 26.1
Elpy..............: 1.33.0
Virtualenv........: .venv (/home/mdk/clones/Org/.venv)
Interactive Python: python 3.8.3 (/home/mdk/clones/Org/.venv/bin/python)
RPC virtualenv....: rpc-venv (/home/mdk/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.8.3 (/home/mdk/clones/Org/.venv/bin/python)
 Jedi.............: 0.16.0 (0.17.0 available)
 Rope.............: Not found (0.17.0 available)
 Autopep8.........: Not found (1.5.2 available)
 Yapf.............: Not found (0.30.0 available)
 Black............: 19.3b0 (19.10b0 available)
Syntax checker....: Not found (flake8)
```

## Elpy configuration in my init.el
```
'(elpy-modules
   (quote
    (elpy-module-company elpy-module-eldoc elpy-module-flymake elpy-module-pyvenv elpy-module-yasnippet elpy-module-django elp\
y-module-sane-defaults)))

```

**Comment by galaunay** [comment]
I could not reproduce this behavior.
For me, middle-click pastes your example snippet properly even with `electric-indent-mode` enabled.

Could you try with a clean Emacs:
``` bash
emacs -Q -l start-clean-elpy.el
```
(after getting `start-clean-elpy.el` from the Elpy repo [here](https://github.com/jorgenschaefer/elpy/blob/master/scripts/start-clean-elpy.el))

**Comment by JulienPalard** [comment]
`start-clean-elpy.el` is a nice idea!

Tried `emacs -Q -l start-clean-elpy.el`, followed by `C-x-C-f /tmp/test.py`, followed by a middle-click-paste of my snippet and got:

![elpy](https://user-images.githubusercontent.com/239510/83069058-9335ac80-a069-11ea-81a0-73c188f93f24.png)

(oh yes, my test.py already contained something... haha)

**Comment by galaunay** [comment]
I managed to reproduce it. Apparently, it only happens when starting emacs in the terminal.

I am afraid it is not really related to Elpy. But maybe advising `mouse-yank-primary` would work. Something like that (untested):
``` elisp
(advice-add 'mouse-yank-primary
            :around
            (lambda (oldfun &rest r)
              (if (and (derived-mode-p 'python-mode)
                       eletric-indent-mode)
                  (progn
                    (electric-indent-mode -1)
                    (apply #'funcall oldfun r)
                    (electric-indent-mode 1))
                (apply #'funcall oldfun r)))
            '((name . "Disable electric indent for python")))

```

**Comment by JulienPalard** [comment]
> Apparently, it only happens when starting emacs in the terminal.

Is there another way to start emacs? or are you speaking of 

> I am afraid it is not really related to Elpy. But maybe advising `mouse-yank-primary` would work.

At first glance I agree with you: it's not related to elpy. It's even a feature: when pasting C code (and many other languages) it gets re-indented while pasting, it's probably an appreciated feature.

So it's Python related, not `mouse-yank-primary` nor `electric-indent-mode` related, so I think it's the role of elpy (or emac's `python.el`?) to correct this, am I right?

**Comment by galaunay** [comment]
I agree this could belong in Elpy's `sane-default` module.
Is the snippet above fixing the problem ?

**Comment by JulienPalard** [comment]
Hum no. I'm no elisp programmer so I can't really tell why.

I see the `:around advice: Disable electric indent for python` hint in `describe-function mouse-yank-primary` so the snippet applied properly, but did not fix the issue.

Maybe `mouse-yank-primary` is not called at all? When I try `C-h k ` (`describe-key`) followed by a middle click I'm getting the doc of what's pasted in my buffer, (If I copy a m letter, I'm getting the help for the key m). Also, adding a `(message "test")` to the body of your replacement function gives nothing, again like `mouse-yank-primary` is never called.

**Comment by JulienPalard** [comment]
Hint from `man urxvt`: 
> Pasting:
>    Pressing and releasing the Middle mouse button in an urxvt window causes the
>    value of the PRIMARY selection (or CLIPBOARD with the Meta modifier) to be
>    inserted as if it had been typed on the keyboard.

Looks like a dead end.

**Comment by JulienPalard** [comment]
I'm trying to enable bracketed paste. It fixes the terminal emacs issue without any emacs configuration, I'll see what it breaks.

If someone land on this issue for the same reason, bracketed paste can be enabled using:

    printf $'\e[?2004h'

(and disabled by changing the `h` to an `l` (high to low), or toggeled using a `t`)

Thanks @galaunay for the help, really appreciate!
