### ISSUE TITLE
Attempting to format code (with black) fails with an 'Invalid function' error

### ISSUE THREAD

**Issue by hnarayanan** [jorgenschaefer/elpy#1802]
# Summary

When I attempt to format Python source files with `M-x elpy-format-code`, it consistently fails and shows me the following error message.

```
Invalid function: (when (interactive-p) message "Autoformatting code with black.")
```

This has worked before for me, and only started failing in recent versions of elpy. I peeked into the elpy source code and things got extra confusing to me, because if I call the explicit concrete function `M-x elpy-black-fix-code`, it works and my source file is formatted.

 If someone can help me debug what is wrong with my setup, I would appreciated.

# Steps to reproduce

Open a Python file, attempt to format it with `M-x elpy-format-code`.

# My configuration

- python 3.8x
- recent elpy from Melpa
- emacs from Macports
- packages in a virtualenv

## OS

macOS Catalina 10.15.5
## Result of `(elpy-config)`
```
Emacs.............: 27.0.91
Elpy..............: 1.33.0
Virtualenv........: venv (/Users/me/Sites/edgefolio/source/api/venv)
Interactive Python: python 3.8.3 (/Users/me/Sites/edgefolio/source/api/venv/bin/python)
RPC virtualenv....: venv (/Users/me/Sites/edgefolio/source/api/venv)
 Python...........: python 3.8.3 (/Users/me/Sites/edgefolio/source/api/venv/bin/python)
 Jedi.............: 0.16.0 (0.17.0 available)
 Rope.............: Not found (0.17.0 available)
 Autopep8.........: Not found (1.5.2 available)
 Yapf.............: Not found (0.30.0 available)
 Black............: 19.10b0
Syntax checker....: flake8 (/opt/local/bin/flake8)
```

## Elpy configuration in my init.el
```
(elpy-enable)
(setq elpy-rpc-timeout 5)
(setq elpy-rpc-virtualenv-path 'current)
```

**Comment by galaunay** [comment]
It has been fixed in the latest release (1.34.0).
It should be gone if you update.

**Comment by galaunay** [comment]
(Please re-open if not)

**Comment by hnarayanan** [comment]
It did fix it, thank you!
