### ISSUE TITLE
Replacing flymake with flycheck breaks syntax checking command

### ISSUE THREAD

**Issue by falloutphil** [jorgenschaefer/elpy#1804]
If I take the advice from docs to replace flymake with flycheck:
https://elpy.readthedocs.io/en/latest/customization_tips.html?highlight=flymake#use-flycheck-instead-of-flymake

This seems to prevent python-check-command being set from elpy-syntax-check-command because it happens inside a flymake procedure:
https://github.com/jorgenschaefer/elpy/blob/master/elpy.el#L3607

Workaround is to set it manually in custom.  Without this `C-c C-v` fails checking syntax of python file.

Suggestion is to move this setting out of flymake specific procedure.

The error is similar to this issue for reference:
https://github.com/jorgenschaefer/elpy/issues/1002

Thanks!

**Comment by vytas7** [comment]
Thanks for the clarification, affecting me as well. I tossed in a workaround similar to https://github.com/jorgenschaefer/elpy/issues/1002#issuecomment-301255217

**Comment by galaunay** [comment]
It should do it (commit 467d8b3c0a2e04d7d0f721d43a8d5881b31d922c).
Please re-open if I misunderstood.

**Comment by vytas7** [comment]
@galaunay Confirmed fixed in `elpy 20200805.1736` from MELPA, thanks!
