### ISSUE TITLE
elpy-shell-cell-boundary-regexp not working

### ISSUE THREAD

**Issue by neopku** [jorgenschaefer/elpy#1822]
## OS
Windows 7 Emacs 26.3

I was trying to add "#%%" as one of the cell boundary and have the config in my init file:

(setq elpy-shell-cell-boundary-regexp
      "^\\(?:##.*\\|#%%.*\\|#\\s-*<.+>\\|#\\s-*\\(?:In\\|Out\\)\\[.*\\]:\\)\\s-*$")
But after typing C-c C-y w, emacs told me "Not in a codecell".

**Comment by neopku** [comment]
Adding the beginning of boundary worked.
(setq elpy-shell-codecell-beginning-regexp
   "^\\(?:##.*\\|#%%.*\\|#\\s-*<codecell>\\|#\\s-*In\\[.*\\]:\\)\\s-*$")

**Comment by galaunay** [comment]
Thanks for the feedback.

Indeed those two need to be modified together.
I updated the docstring of `elpy-shell-codecell-boundary-regexp` to reflect that.
