### ISSUE TITLE
elpy-pdb-debug-buffer throws ModuleNotFoundError with local module

### ISSUE THREAD

**Issue by lljr** [jorgenschaefer/elpy#1830]
# Summary

Consider a directory structure like this
```
- testtest/
-- test_this_error/
--- __init__.py
-- test.py
```

in `test.py` write
```python
import test_this_error

print("hello")
```

When you set the breakpoint and launch the debugger it will not recognize `test_this_error` module.
This also happens when working inside a virtual environment.

# Steps to reproduce
1. create a directory structure like in the description
2. set a breakpoint with `C-c C-u b` after `import test_this_error` statement
3. launch the debugger with `C-c C-u d`

# My configuration
## OS
Ubuntu 20

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.34.0
Virtualenv........: None
Interactive Python: ipython 7.15.0 (/home/wario/.local/bin/ipython)
RPC virtualenv....: system (/)
 Python...........: python3 3.8.2 (//bin/python3)
 Jedi.............: 0.17.0 (0.17.2 available)
 Rope.............: 0.16.0
 Autopep8.........: 1.5.2 (1.5.4 available)
 Yapf.............: 0.30.0
 Black............: 19.10b0
Syntax checker....: flake8 (/home/wario/.local/bin/flake8)

Warnings

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

There is a newer version of Jedi available.

[Update jedi]

There is a newer version of the autopep8 package available.

[Update autopep8]

```

## Elpy configuration in my init.el
```
(elpy-enable)
(defalias 'workon 'pyvenv-workon)

(setq elpy-rpc-python-command "python3"
      ;; Interpreter to be used
      python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")

;; (add-hook 'elpy-mode-hook (lambda () (elpy-shell-toggle-dedicated-shell 1)))

```

**Comment by galaunay** [comment]
Thanks for the detailed infos.

It could be that the script is started in the wrong directory.
If it is the case, using `(setq elpy-shell-starting-directory 'current-directory)` may help.

Elpy tries to be smart and starts scripts in their project root (returned by `(elpy-project-root)`). If this directory is not your `testtest` directory, python cannot find the `test_this_error` module.

**Comment by lljr** [comment]
@galaunay What do you mean? that `testtest` should be the value for `elpy-project-root`? Right now I'm testing with a project that has a .git defined in the root dir. Calling `(elpy-project-root)` gives me the value I expect (the root dir). Yet, I have the same error...

**Comment by galaunay** [comment]
What I was trying to say is that the python interpreter may be starting in a different directory then the one you expect (`testtest/`) if `elpy-shell-starting-directory` is set to `'project-directory`.
You can easily test this by adding `import os; print(os.getcwd())` (or similar) at the start of the `test.py` file.

I reproduced your directory structure, and it works for me, both in the debugger and in a virtualenv.
Regarding `elpy-shell-starting-directory`, you need to restart the python interpreter (with `C-c C-k`  and `C-c C-z`) after modifying it (it does not change the directory of already started python interpreter).

**Comment by lljr** [comment]
@galaunay hmmm it's working for me now... Maybe it's that I'm using an older version than the one in the main branch. All my packages are managed through Guix. Not all packages are kept up-to-date.
