### ISSUE TITLE
high-lighting codecell boudary

### ISSUE THREAD

**Issue by neopku** [jorgenschaefer/elpy#1833]
High-lighting codecell boundary would help me a lot.

**Comment by galaunay** [comment]
`hightlight.el` could do that for you:
``` elisp
(highlight-lines-matching-regexp 'elpy-shell-cell-boundary-regexp)
```
It would highlight all the codecell though, not only the one you are in.

Is it the kind of behaviour you were looking for ?

**Comment by neopku** [comment]
Yes. I am using highlight. But this font style is mixed with comment style. I am looking for the font-lock solution.

**Comment by neopku** [comment]
This is my temporary solution:
`(defface my-codecell-boundary
  '((t :background "white smoke"
       :foreground "navy"
       :overline "dark red"
       :slant normal
       :weight bold
       :height 1.1
       ))
  "Face for elpy codecell boundary."
  :group 'elpy-mode)

(add-hook 'elpy-mode-hook
	  (lambda ()
	    (highlight-lines-matching-regexp elpy-shell-cell-boundary-regexp 'my-codecell-boundary)))
`

**Comment by neopku** [comment]
This is my temporary solution:
``` elisp
(defface my-codecell-boundary
  '((t :background "white smoke"
       :foreground "navy"
       :overline "dark red"
       :slant normal
       :weight bold
       :height 1.1
       ))
  "Face for elpy codecell boundary."
  :group 'elpy-mode)

(add-hook 'elpy-mode-hook
	  (lambda ()
	    (highlight-lines-matching-regexp elpy-shell-cell-boundary-regexp 'my-codecell-boundary)))
```

**Comment by galaunay** [comment]
This works for me:
``` elisp
(font-lock-add-keywords
 'python-mode
 `((,(replace-regexp-in-string "\\\\" "\\\\"
                               elpy-shell-cell-boundary-regexp)
    0 'my-codecell-boundary prepend)))
```

**Comment by neopku** [comment]
This is great, thanks.

> This works for me:
> 
> ```emacs-lisp
> (font-lock-add-keywords
>  'python-mode
>  `((,(replace-regexp-in-string "\\\\" "\\\\"
>                                elpy-shell-cell-boundary-regexp)
>     0 'my-codecell-boundary prepend)))
> ```
