### ISSUE TITLE
no module named `numpy`

### ISSUE THREAD

**Issue by yangdaweihit** [jorgenschaefer/elpy#1834]
I send a statement `import numpy as np` and got python shell complained information:

```
ModuleNotFoundError: No module named 'numpy.matlib'; 'numpy' is not a package
```

The below is configuration list:

```
Elpy Configuration

Virtualenv........: emacs (/home/wall-e/.virtualenv/emacs)
RPC Python........: 3.8.5 (/usr/bin/python3)
Interactive Python: python3 (/home/wall-e/.virtualenv/emacs/bin/python3)
Emacs.............: 26.3
Elpy..............: 1.25.0
Jedi..............: 0.17.2
Rope..............: 0.17.0
Autopep8..........: 1.5.4
Yapf..............: 0.30.0
Black.............: 20.8b1
Syntax checker....: flake8 (/home/wall-e/.local/bin/flake8)

```
I checked the installed package in virtualenv `emacs`:

```
(emacs) ➜  emacs pwd
/home/wall-e/.virtualenv/emacs
(emacs) ➜  emacs pip3 list | grep numpy
numpy              1.19.0
```
I know it might be the most probable that I set wrong variables but I don't know where is the problem. Please help me find out the way.

**Comment by galaunay** [comment]
Does it raise the same error when you run your statement in a console (with the `/home/wall-e/.virtualenv/emacs` virtualenv activated) ?

Also, you have an old version of Elpy. It may already be useful to update to 1.34.
