### ISSUE TITLE
Include list of dependencies in instructions to install from source

### ISSUE THREAD

**Issue by miguelmorin** [jorgenschaefer/elpy#1836]
# Summary

I am unable to install Elpy following [the instructions](https://elpy.readthedocs.io/en/latest/introduction.html) from source because of package dependencies.

I cloned the repo to `~/code/elpy` and added these to the Emacs initialization file:

    (add-to-list 'load-path "~/code/elpy")
    (load "elpy")
    (load "elpy-rpc")
    (load "elpy-shell")
    (load "elpy-profile")
    (load "elpy-refactor")
    (load "elpy-django")

And I get this error in `*Messages*`:

<pre>
Loading ~/code/elpy/elpy.el (source)...
eval-buffer: Cannot open load file: No such file or directory, s
</pre>

with no more details.

[StackExchange](https://emacs.stackexchange.com/questions/60614/unable-to-install-elpy-eval-buffer-cannot-open-load-file-no-such-file-or-dir) suggested it was the `s` package, which I installed. I now get

<pre>
Loading /Users/mmorin/code/elpy/elpy.el (source)...
eval-buffer: Cannot open load file: No such file or directory, pyvenv
</pre>

Can you list in the instructions all the packages required to install Elpy from source?

# Steps to reproduce

On a clean Emacs installation, clone the repo to `~/code/elpy` and evaluate these lines:

    (add-to-list 'load-path "~/code/elpy")
    (load "elpy")

# My configuration
## OS

macOS 10.14.6

Emacs 27.1 (9.0)

## Result of `(elpy-config)`
```
Debugger entered--Lisp error: (void-function elpy-config)
```

## Elpy configuration in my init.el
```
(add-to-list 'load-path "~/code/elpy")
(load "elpy")
```

**Comment by galaunay** [comment]
You also need to install some dependencies (I agree it should be mentioned).
I updated the doc. Thanks for the feedback.

Please re-open if it is still nor working.

**Comment by miguelmorin** [comment]
Thanks! It's clearer now. This time I tried to install it via Melpa with 

```
(package-install 'use-package)
(require 'use-package)

(use-package elpy
  :ensure t
  :init
  (elpy-enable))
```

On a Python buffer, I get:

```
Running 'virtualenv -p python /Users/mmorin/.emacs.d/elpy/rpc-venv':

/Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_14: /usr/local/bin/virtualenv: No such file or directory


Elpy failed to install its dedicated virtualenv due to the above
error. If the error details does not help you fixing it, You can
report this problem on Elpy repository on github.
In the meantime, setting the `elpy-rpc-virtualenv-path' option to
either `global' or `current' should temporarily fix the issue.
```

I checked `virtualenv` and [this page](https://virtualenv.pypa.io/en/stable/installation.html) urges caution. How do you suggest installing the required `virtualenv` or `pyvenv`?

**Comment by galaunay** [comment]
If you don't want to install `virtualenv`, Elpy can also use [`venv`](https://docs.python.org/3/library/venv.html). Elpy will detect if it is available and use it instead of `virtualenv`.

You can also choose not to use virtualenv at all, by setting  `(setq elpy-rpc-virtualenv-path 'current)`.
The drawback is that you will have to install some additional python packages for Elpy to work properly, namely:
- jedi
- black
- autopep8
- yapf
- rope

**Comment by miguelmorin** [comment]
Yes, I confirm that ElPy now works with those packages. I only see these error messages at the beginning and not after:

```
error in process sentinel: flymake-error: [Flymake] Unexpected report from disabled backend python-flymake
error in process sentinel: [Flymake] Unexpected report from disabled backend python-flymake
```

Also, I don't see an indication for variables used before assignment: does that check come from the virtual environment?

**Comment by galaunay** [comment]
This is an error raised by flymake. It is telling you that one of the backends providing linting (here `python-flymake`) have been disabled.

you will have to install the "flake8" python package as well to get linting working in Elpy.
(you can also use other linting packages, like pyflakes, pep8 or mypy as well by customizing `elpy-syntax-check-command`).
