### ISSUE TITLE
Elpy doesn't switch environments

### ISSUE THREAD

**Issue by Nathan-Furnal** [jorgenschaefer/elpy#1837]
Hi,

I'm using elpy and facing an annoying issue, when I switch virtual environments with `M-x pyvenv-workon`, elpy doesn't follow and keeps the environment dating when the `*Python*` buffer was created, active. 

So I need to actively kill the current shell and restart the rpc to have the environments actually activated with elpy.

My config is : 

```emacs-lisp
(use-package elpy
  :ensure t
  :defer t
  :init
  ;; Setting work on to easily switch between environments
  (setenv "WORKON_HOME" (expand-file-name "~/miniconda3/envs/"))
  (advice-add 'python-mode :before 'elpy-enable)
  :config
  (setq elpy-rpc-virtualenv-path 'current)
  
  (remove-hook 'elpy-modules 'elpy-module-pyvenv)
  (remove-hook 'elpy-modules 'elpy-module-django)

  ;; Kill the process when switching environments

  (add-hook 'pyvenv-post-activate-hooks (lambda ()
					  (elpy-shell-kill)
					  (elpy-rpc-restart)))

  ;; Use flycheck instead of flymake
 (when (load "flycheck" t t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

  ;; Remove the guessing Python indent message
  (setq python-indent-guess-indent-offset-verbose nil)
  
  (defun my/elpy-use-jupyter ()
    "Use Jupyter & IPython instead of the regular REPL"
  (interactive)
  (setq python-shell-interpreter "ipython"
	python-shell-interpreter-args "-i --simple-prompt"))

  ;; Format code with YAPF on save

  (add-hook 'elpy-mode-hook (lambda ()
                            (add-hook 'before-save-hook
                                      'elpy-yapf-fix-code nil t)))
  :bind (:map elpy-mode-map
	      ("C-c a" . elpy-shell-send-statement)
	      ("C-c q" . elpy-shell-send-region-or-buffer)
	      ("<C-tab>" . elpy-company-backend)))
```

Is there a way to fix this behavior ? 

Thanks a lot

**Comment by galaunay** [comment]
Hi, 

> So I need to actively kill the current shell and restart the rpc to have the environments actually activated with elpy.
Elpy starts a new RPC when detecting a new virtualenv, so it should not be needed to use `elpy-rpc-restart`.

A python interpreter is bound to the virtualenv that was active when it was started. I am not sure it would be an easy task to adapt an interpreter to a new virtualenv. So IMHO, restarting the interpreter is the good solution.

Another solution would be to keep several interpreters open. Elpy can handle multiple interpreters in different ways (one per project, one per file, ...). If you are interested, [here](https://elpy.readthedocs.io/en/latest/ide.html#the-shell-buffer) is the relevant part of the documentation.

**Comment by Nathan-Furnal** [comment]
Thanks! it seems that I indeed do not need to restart the RPC and the hook is doing its job fine.
Thanks for the answer, I'll read more of the docs
