### ISSUE TITLE
Jupyter console displays "^G^G^G..." when sending buffer to shell

### ISSUE THREAD

**Issue by avigan** [jorgenschaefer/elpy#1838]
# Summary

I have been encountering multiple issues with elpy, ipython and plotting with matplotlib for a while now, and following the documentation I have tried to switch to Jupyter console. However, when I use Jupyter console and send a region or buffer to the console it displays multiple `^G^G^G...` characters and the code is not executed. The fix for in IPython, which is to add `-c exec('__import__(\\'readline\\')')` to `python-shell-interpeter-args`, does not seem to work for Jupyter console. I get the following error:
```
[ZMQTerminalIPythonApp] CRITICAL | Unrecognized flag: '-c'
```
I guess there is maybe another way to pass the readline import? I have tried to type directly `exec('__import__(\'readline\')')` as the first command in the shell, but the problem remains the same. 

Any help would be much appreciated.

# My configuration
## OS
```
Mac OS X 10.14.6
```
## Result of `(elpy-config)`
```
Emacs.............: 28.0.50
Elpy..............: 1.34.0
Virtualenv........: None
Interactive Python: jupyter 4.6.3 (/Users/avigan/anaconda3/envs/default/bin/jupyter)
RPC virtualenv....: default (/Users/avigan/anaconda3/envs/default)
 Python...........: python 3.8.5 (/Users/avigan/anaconda3/envs/default/bin/python)
 Jedi.............: 0.17.1 (0.17.2 available)
 Rope.............: 0.17.0
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: Not found (20.8b1 available)
Syntax checker....: flake8 (/Users/avigan/anaconda3/envs/default/bin/flake8)
```
## Elpy configuration in my init.el
```
(elpy-enable)

(setq elpy-shell-send-region-or-buffer 0)
(setq elpy-shell-switch-to-shell 0)
(setq elpy-rpc-virtualenv-path 'current)

(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt --no-confirm-exit"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")
```

**Comment by avigan** [comment]
My bad, the workaround proposed in https://github.com/jorgenschaefer/elpy/issues/1550#issuecomment-574512892 actually works for me: `(setq elpy-shell-echo-output nil)`

**Comment by jdtsmith** [comment]
BTW, `^G` is terminal-speak for "ring the bell", so this is literally iPython _ringing the bell_ when it is fed >1024 characters on a line.  It's because simple-prompt uses the terminal to gather input, and MacOS has a 1024 character limit.  Linux is usually 4096, so you don't notice it.  The "best" solution is to compile some helper functions up front via a temp file, and use those to dramatically shorten the code lines sent.  The current use of a pipe in MacOS is a bandaid that prevents C-D from functioning correctly.
