### ISSUE TITLE
Disable auto-complete popup/toolkit and eldocs echo area updates by default

### ISSUE THREAD

**Issue by gar1t** [jorgenschaefer/elpy#1839]
When writing code, I prefer to focus on my writing of the code and not to see things popup and change my field of view. This is distracting to me and unhelpful.

Having the option to explicitly show these visualizations is of course quite helpful!

I'd like to configure elpy to show/do literally nothing when I type, including popups/tooltips and docs in the echo area. Then use a key binding to activate these helpers when needed.

I'm having a hard time sorting through the configuration that I'd need to use to accomplish this. I've tried settings that I think should work (e.g. setting 'Company Idle Delay' and 'Company Tooltip Idle Delay' to values like 999) but the tooltips keep showing up after I type three characters. I'm guessing there's an interaction with some other configuration.

Short of disabling eldocs, I haven't been able to disable the automatic use of the echo area to show docs as the cursor position changes. I wouldn't mind this but it then disables, seemingly, my ability to see flymake messages.

I apologize for using GitHub issues to ask this question. I'm not sure if there's a better way to get help.

**Comment by galaunay** [comment]
> I'm having a hard time sorting through the configuration that I'd need to use to accomplish this. I've tried settings that I think should work (e.g. setting 'Company Idle Delay' and 'Company Tooltip Idle Delay' to values like 999) but the tooltips keep showing up after I type three characters. I'm guessing there's an interaction with some other configuration.

Elpy set `company-idle-delay` to 0.1 for every python buffer you open. If you do not want idle completion, you can use something like this
``` elisp
  (add-hook 'elpy-mode-hook (lambda () (setq company-idle-delay nil)))
```
To ensure idle completion stays deactivated.

> Short of disabling eldocs, I haven't been able to disable the automatic use of the echo area to show docs as the cursor position changes. I wouldn't mind this but it then disables, seemingly, my ability to see flymake messages.

You can disable Elpy's eldoc module by customising `elpy-modules`. If you still want to use eldoc (for flymake and others), you will have to activate eldoc by yourself (as Elpy will not do it for you anymore). This should do:
```elisp
    (add-hook 'python-mode-hook 'eldoc-mode)
```
