### ISSUE TITLE
Unclear message: "Jedi.............: Not found (0.17.2 available)"

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [jorgenschaefer/elpy#1844]
Elpy 1.34.0
Emacs 26.1
Debian GNU/Linux 10 (current last stable)

`elpy-config` tells me

` Jedi.............: Not found (0.17.2 available)`

What does "available" mean here? From where? How?

btw: "jedi" is installed via `pip` and `pip3` on my current Debian and can imported without any problems in a Python2 and Pyhton3 prompt.

**Comment by galaunay** [comment]
You should have a "warning" section underneath giving more explanation on that.
We can continue this discussion on your other issue #1843, as it is probably the same issue.
