### ISSUE TITLE
elpy-config: "[Install]" not working on Debian 10

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [jorgenschaefer/elpy#1845]
Elpy 1.3.40
Emacs 26.1
Debian GNU/Linux 10 (stable)

As the docs mentions for Debian 10
https://elpy.readthedocs.io/en/latest/introduction.html#from-apt-debian-10-an-ubuntu-18-10
I tried to use the Install-Buttons in `elpy-config`

But e.g. for "Jedi" it do not work because of user permission problems.

```

Collecting jedi
  Using cached https://files.pythonhosted.org/packages/c3/d4/36136b18daae06ad798966735f6c3fb96869c1be9f8245d2a8f556e40c36/jedi-0.17.2-py2.py3-none-any.whl
Collecting parso<0.8.0,>=0.7.0 (from jedi)
  Using cached https://files.pythonhosted.org/packages/93/d1/e635bdde32890db5aeb2ffbde17e74f68986305a4466b0aa373b861e3f00/parso-0.7.1-py2.py3-none-any.whl
Installing collected packages: parso, jedi
Could not install packages due to an EnvironmentError: [Errno 13] Keine Berechtigung: '/usr/local/lib/python2.7/dist-packages/parso-0.7.1.dist-info'
Consider using the `--user` option or check the permissions
```

Of course, the emacs runs as a user process. `pip` is not allowed (by default) to install something as a user.

But do not try to use `--user` by default as a solution!
Some users do not like to install python packages as users they install them globaly (via `sudo pip` or `sudo pip3`).

I do not know a Debian-related solution here. Some more investigation is needed.

**Comment by galaunay** [comment]
`Consider using the '--user' option or check the permissions` is printed by pip itself, not Elpy.

The documentation have been updated to give more adequate recommendation to Debian users (which is install the needed package from the Debian repos).

**Comment by sten0** [comment]
@Codeberg-AsGithubAlternative-buhtz, /usr/share/doc/foo/README.Debian is where these sort of things are usually documented.  Did you read /usr/share/doc/elpa-elpy/README.Debian?  If so, was this README, and do you have any suggestions for improving it?  P.S. for the record, Debian users are supposed to follow https://www.debian.org/Bugs/Reporting and not bother upstream maintainers with what may be bugs that exist only in the Debian package ;-)

@galaunay, thank you for the extra Debian user support.  P.P.S. I really hope you have time to take a look at https://github.com/jorgenschaefer/elpy/issues/1856#issuecomment-755267105 before the end of the month.
