### ISSUE TITLE
About the elpy-get-info-from-shell option.

### ISSUE THREAD

**Issue by hongyi-zhao** [jorgenschaefer/elpy#1847]
Hi,

I noticed the interesting option of elpy [here](https://elpy.readthedocs.io/en/latest/ide.html#option-elpy-get-info-from-shell). I want to know whether this feature is corresponding to the dynamic/runtime auto-completion for type/variable/function names, just as the behavior represented by ipython/jupyter?

Any hints will be highly appreciated.

Regards,
HY

**Comment by galaunay** [comment]
Hi, 

Yes, it is supposed to offer the same functionality as the dynamic completion in ipython/jupyter.
I replied in more details in your other issue #1846, we can continue this discussion there.
