### ISSUE TITLE
What does `Symbol’s value as variable is void: <!DOCTYPE` mean? in this context?

### ISSUE THREAD

**Issue by touxstone** [jorgenschaefer/elpy#1854]
# Summary

Hi, please help with this issue I have just installed this package but following the recommendations posted [here](https://0e39bf7b.blog/posts/configure-emacs-for-python-development/) regarding disabling signature checking temporarily first since following regular instructions I used to get into installation issues related to signature verification. Now after installing and restart, it seems correctly, I got the warning shown below:
(Thanks!!)

```el
    Error (use-package): elpy/:init: Symbol’s value as variable is void: <!DOCTYPE
    Error (use-package): elpy/:catch: Symbol’s value as variable is void: <!DOCTYPE
```
# Steps to reproduce
Just every time I restart EMACS

# My configuration
Operating System: Fedora 31 (Thirty One)
       CPE OS Name: cpe:/o:fedoraproject:fedora:31
            Kernel: Linux 5.8.18-100.fc31.x86_64
      Architecture: x86-64

## Result of `(elpy-config)`
```el
    Debugger entered--Lisp error: (void-variable <!DOCTYPE)
  byte-code("\010\210\011\210\n\210\013\210\f\210\015\210\016\006\210\016\007\210\016\010\207" [<!DOCTYPE html PUBLIC ><html><head><meta http-equiv= content= /><script type= >url=] 1)
  require(pyvenv)
  eval-buffer(#<buffer  *load*-570077> nil "/home/txarly/.emacs.d/elpa/elpy-20201115.1811/elpy-rpc.el" nil t)  ; Reading at buffer position 1318
  load-with-code-conversion("/home/txarly/.emacs.d/elpa/elpy-20201115.1811/elpy-rpc.el" "/home/txarly/.emacs.d/elpa/elpy-20201115.1811/elpy-rpc.el" nil t)
  require(elpy-rpc)
  eval-buffer(#<buffer  *load*> nil "/home/txarly/.emacs.d/elpa/elpy-20201115.1811/elpy.el" nil t)  ; Reading at buffer position 1812
  load-with-code-conversion("/home/txarly/.emacs.d/elpa/elpy-20201115.1811/elpy.el" "/home/txarly/.emacs.d/elpa/elpy-20201115.1811/elpy.el" nil t)
  (elpy-config)
  eval((elpy-config) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  #<subr call-interactively>(eval-last-sexp nil nil)
  apply(#<subr call-interactively> eval-last-sexp (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> eval-last-sexp nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (eval-last-sexp nil nil))
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
    
```

## Elpy configuration in my init.el
```el
    (use-package elpy
    :ensure t
    :init
    (elpy-enable))
```

**Comment by gopar** [comment]
This is pretty interesting. An error is being raised when trying to load `pyvenv` 

Can you post any other configurations related to python? Do you have `pyvenv` installed?

**Comment by touxstone** [comment]
Yes I do but I go on fedora so what I've got installed is `python3-virtualenv` and `python3-virtualenvwrapper` no other config related with python on emacs otherwise those built-in functionalities based on `python.el` (as long as I got knowledge).

**Comment by gopar** [comment]
Ah sorry, I wasn't clear. I meant if you had [pyvenv](https://github.com/jorgenschaefer/pyvenv/) installed in emacs.

**Comment by touxstone** [comment]
No, I do not have `pyenv` on emacs (though by reading the `elpy.el` script that should not be a problem, should it?. Anyway, I am new at using (python) `virtualenv` and `virtualenvwrapper` and so far, quite specifically to learn using `Nikola` (that static site and blog generator written in Python). I was just trying to gain literacy in python and missed some functionalities I got with emacs-paredit when at e.g. closing parentheses`()`, `[]`, `{}`, `" "`

**Comment by gopar** [comment]
Wait you don't have it installed? That shouldn't be possible? Elpy uses `pyvenv` as a dep, and using `use-package` it should of already installed it. Hmm can you double check by doing `M-x list-packages` and see if `pyvenv` is installed? And whether if it's installed or not, can you (re)install it? (If you already have it installed, uninstall it and install it again).

The error that you talked about is a weird one, b/c when trying to load `pyvenv`, it looks like it's trying to load html code as lisp code. Not sure why that can happen besides a random error when installing the package

**Comment by touxstone** [comment]
I couldn't get it installed using `use-package` I used to get a signature verification error. As referenced at starting posting this issue, I only could manage to install it by `Mx package-list-packages` after disabling `signature-verification` temporally as explained [here](https://0e39bf7b.blog/posts/configure-emacs-for-python-development/). But (wait) after re-checking I found out I actually got `pyvenv-20191202.1039` placed in my elpa dir and the content of the `pyenv.el` is html code rather than `emacs-lisp`.

**Comment by touxstone** [comment]
Okay, thank you for the clues. 
I just removed files (`elpy` and the faulty `pyvenv` I had (I already had installed all the other dependencies)) and tried again (as from the previous try I could manage to update the GPG keys used by Emacs package manager by installing `gnu-elpa-keyring-update`) this time installation (though including some compilation warnings) worked. It's nice at first sight.
PS. Yet, I still miss the closing `()`, `[]`, `{}`, `" "` functionality /..\

**Comment by gopar** [comment]
When inputing a '(' you don't automatically get a closing paren? Is that what you mean?
You probably might not have `electric-pair-mode` mode actividated (should be built in).

Closing this issue as the main problem is addressed
