### ISSUE TITLE
40% rate of a failed self-test with Elpy 1.35 + Emacs 27.1 + Python 3.9, over 10 runs

### ISSUE THREAD

**Issue by sten0** [jorgenschaefer/elpy#1856]
# Summary

elpy-pdb-debug-last-exception-should-ignore-breakpoints sometimes fails (1/4 builds so far).

# Steps to reproduce
See attached logs.  Now with backtraces truncated to 500 columns instead of the super narrow default.  Searching for "elpy-pdb-debug-last-exception-should-ignore-breakpoints" will provide the backtrace at the first hit.
Fail: [elpy_1.35.0-1_amd64-2020-11-18T22:15:26Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5563277/elpy_1.35.0-1_amd64-2020-11-18T22.15.26Z.build.txt)
Pass: [elpy_1.35.0-1_amd64-2020-11-18T22:31:43Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5563278/elpy_1.35.0-1_amd64-2020-11-18T22.31.43Z.build.txt)
Pass: [elpy_1.35.0-1_amd64-2020-11-18T22:18:54Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5563279/elpy_1.35.0-1_amd64-2020-11-18T22.18.54Z.build.txt)
Pass: [elpy_1.35.0-1_amd64-2020-11-18T22:13:54Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5563280/elpy_1.35.0-1_amd64-2020-11-18T22.13.54Z.build.txt)

# My configuration
## OS
Debian unstable, Emacs 27.1, on Python 3.8.6 for now, but moving to 3.9.0 by default soon.  Full list available here:
[elpy_1.35.0-1_amd64.buildinfo.txt](https://github.com/jorgenschaefer/elpy/files/5563271/elpy_1.35.0-1_amd64.buildinfo.txt)

**Comment by sten0** [comment]
Now with Python 3.9, I'm seeing a 40% failure rate (over 10 runs), with failures affecting four self-tests.

Debian-specific customisations are to default to system Python:
```elisp
(setq elpy-rpc-pythonpath nil
      python-shell-interpreter "/usr/bin/python3"
      python-shell-interpreter-args "-i -E"
      elpy-rpc-python-command "/usr/bin/python3"
      elpy-rpc-virtualenv-path 'system)
```

`ELPY_TEST_DONT_USE_VIRTUALENV` is set.

plus a patch that doubles the timeouts in `test-helper.el` (significantly reduces incidence of failed tests on our CI infrastructure!)

[elpy_1.35.0-1_amd64-2020-11-22T04:50:55Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578970/elpy_1.35.0-1_amd64-2020-11-22T04.50.55Z.build.txt) FAILED: elpy-profile-buffer-or-region-test-fail, elpy-profile-buffer-or-region-test-indir-failed
[elpy_1.35.0-1_amd64-2020-11-22T04:59:31Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578967/elpy_1.35.0-1_amd64-2020-11-22T04.59.31Z.build.txt) FAILED: elpy-pdb-debug-last-exception-should-debug-last-exception
[elpy_1.35.0-1_amd64-2020-11-22T04:59:36Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578966/elpy_1.35.0-1_amd64-2020-11-22T04.59.36Z.build.txt) FAILED: elpy-pdb-debug-buffer-should-enter-pdb
[elpy_1.35.0-1_amd64-2020-11-22T05:02:16Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578965/elpy_1.35.0-1_amd64-2020-11-22T05.02.16Z.build.txt) FAILED: elpy-pdb-debug-last-exception-should-ignore-breakpoints

And logs for the successful runs:
[elpy_1.35.0-1_amd64-2020-11-22T04:53:09Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578968/elpy_1.35.0-1_amd64-2020-11-22T04.53.09Z.build.txt)
[elpy_1.35.0-1_amd64-2020-11-22T04:51:03Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578969/elpy_1.35.0-1_amd64-2020-11-22T04.51.03Z.build.txt)
[elpy_1.35.0-1_amd64-2020-11-22T04:47:47Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578971/elpy_1.35.0-1_amd64-2020-11-22T04.47.47Z.build.txt)
[elpy_1.35.0-1_amd64-2020-11-22T04:45:18Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578972/elpy_1.35.0-1_amd64-2020-11-22T04.45.18Z.build.txt)
[elpy_1.35.0-1_amd64-2020-11-21T21:42:08Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578973/elpy_1.35.0-1_amd64-2020-11-21T21.42.08Z.build.txt)
[elpy_1.35.0-1_amd64-2020-11-21T21:39:39Z.build.txt](https://github.com/jorgenschaefer/elpy/files/5578974/elpy_1.35.0-1_amd64-2020-11-21T21.39.39Z.build.txt)

**Comment by sten0** [comment]
And here's a more recent [elpy_1.35.0-1_amd64.buildinfo.txt](https://github.com/jorgenschaefer/elpy/files/5613286/elpy_1.35.0-1_amd64.buildinfo.txt)

**Comment by sten0** [comment]
I rebased the packaged onto 4032c72, disabled all the Jedi-related tests and pytests, and am still seeing errors in the following:
```
   FAILED  elpy-multiedit-python-symbol-at-point-should-save-some-buffers
   FAILED  elpy-xref--apropos-should-give-an-xref-buffer
   FAILED  elpy-xref--definitions-should-return-definitions
   FAILED  elpy-xref--get-completion-table-should-return-completion-table
   FAILED  elpy-xref--references-test
```
I'm struggling to identify the causes of recent test failures that appear to be related to the Python 3.9.1 migration (p.s. oh my goodness, so much work elsewhere on the Python team because of this!)  In four days Elpy will be dropped from Debian 11 (bullseye, the next release), and about four weeks from now until the door closes on being able to get it back in.  A hint would be truly appreciated :-)

Disabling these tests for a month or two is an option, and thankfully we're beginning the soft-freeze at the beginning of February, so there won't be any more large disruptions.  I'm looking forward to hopefully having more free time by then!

**Comment by Apteryks** [comment]
With the current master branch (commit 8d0de310d41ebf06b22321a8534546447456870c), I get only these failures:

```
.............................................................................................................................................................................................Test elpy-multiedit-python-symbol-at-point-should-save-some-buffers backtrace:


Test elpy-multiedit-python-symbol-at-point-should-save-some-buffers condition:

    (error "Selecting deleted buffer")

F..................................................................................................Test elpy-refactor-rpc-rename-should-rename-in-multiple-files backtrace:


Test elpy-refactor-rpc-rename-should-rename-in-multiple-files condition:

    (ert-test-failed
     ((should
       (string= diff
                (concat "--- Classes.py
" "+++ Classes.py
" "@@ -1,4 +1,4 @@
" "-class Foo(object):
" "+class new_foo(object):
" "    def __init__(self, a, b):
" "       self.res = a + b
" "--- test.py
" "+++ test.py
" ...)))
      :form
      (string= nil "--- Classes.py
+++ Classes.py
@@ -1,4 +1,4 @@
-class Foo(object):
+class new_foo(object):
    def __init__(self, a, b):
       self.res = a + b
--- test.py
+++ test.py
@@ -1,4 +1,4 @@
-from Classes import Foo
-foo = Foo(1, 2)
+from Classes import new_foo
+foo = new_foo(1, 2)
 print(foo.res)
")
      :value nil))

F.............................................................................................................................................................................

Ran 462 tests in 88.569 seconds
2 unexpected results:
   FAILED  elpy-multiedit-python-symbol-at-point-should-save-some-buffers
   FAILED  elpy-refactor-rpc-rename-should-rename-in-multiple-files
```

With the direct inputs (GNU Guix):

```
dependencies: emacs-company@0.9.13 emacs-ert-runner@0.8.0 emacs-f@0.20.0 emacs-find-file-in-project@6.1.2 emacs-highlight-indentation@0.7.0-1.d03803f emacs-pyvenv@1.21 emacs-s@1.12.0 emacs-yasnippet@0.14.0
+ python-autopep8@1.5.3 python-black@20.8b1 python-flake8@3.9.1 python-jedi@0.18.0-1.1d94494 python-rope@0.19.0 python-sphinx@4.2.0 python-wrapper@3.9.6 python-yapf@0.29.0 texinfo@6.7
```

**Comment by Apteryks** [comment]
Hmm, nevermind, I just got these extras:
```
4 unexpected results:
   FAILED  elpy-pdb-debug-buffer-should-ignore-breakpoints
   FAILED  elpy-promise-wait-should-return-after-timeout
   FAILED  elpy-refactor-extract-variable-should-extract-variable
   FAILED  elpy-refactor-extract-variable-should-extract-variable-from-region
```

**Comment by sten0** [comment]
I've decided to close this issue since we're down to what appears to be one or two failing tests, and it's not nice to see this issue title.  Thank you everyone who worked on these many issues!
