### ISSUE TITLE
Empty and incessant "Output from the virtualenvwrapper hook post_deactivate" pop-up buffers

### ISSUE THREAD

**Issue by posita** [jorgenschaefer/elpy#1864]
After upgrading my Emacs packages recently, I get these popping up incessantly, sometime every time I do `C-n` to move to a next line in a Python source file. I can't think of anything else that's changed in my setup.

<img width="764" alt="Screen Shot 2020-12-13 at 09 04 11" src="https://user-images.githubusercontent.com/222581/102018491-605fb700-3d22-11eb-8a79-560c88394ae7.png">

I am using [`virtualenvwrapper`](https://bitbucket.org/virtualenvwrapper/virtualenvwrapper/src/master/) to manage my virtual environments, but I haven't overridden anything in any of my `postdeactivate` scripts.

Apologies if this project is not the source of these annoyances.

**Comment by gaetano-guerriero** [comment]
It is related to this: https://github.com/jorgenschaefer/pyvenv/issues/102

**Comment by posita** [comment]
Thanks for the pointer! Closing this as a duplicate of jorgenschaefer/pyvenv#102.
