### ISSUE TITLE
elpy-goto-definition and virtualenv

### ISSUE THREAD

**Issue by ppgaluzio** [jorgenschaefer/elpy#1881]
# Summary

I am having some strange problem regarding `elpy-goto-definition` (and some other features) and the use of virtualenvs.

Basically I have two different virtualenvs, in one of them `elpy-goto-definition` works as expected. If I change to the other environment using `pyvenv-workon` **without leaving the buffer**, then I got "No definition found". The problem is, both virtual envs seem to have all the required packages correctly installed.

Here is the elpy-config of the working environment:

```
Emacs.............: 26.1
Elpy..............: 1.34.0
Virtualenv........: AVF-ENV (/home/paulo/environments/AVF-ENV)
Interactive Python: ipython3 7.14.0 (/home/paulo/environments/AVF-ENV/bin/ipython3)
RPC virtualenv....: AVF-ENV (/home/paulo/environments/AVF-ENV)
 Python...........: python3 3.7.3 (/home/paulo/environments/AVF-ENV/bin/python3)
 Jedi.............: 0.18.0
 Rope.............: 0.17.0
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: 20.8b1
Syntax checker....: flake8 (/home/paulo/environments/AVF-ENV/bin/flake8)
```

And here is the config of the environment that is not working:

```
Emacs.............: 26.1
Elpy..............: 1.34.0
Virtualenv........: O2Sat (/home/paulo/environments/O2Sat)
Interactive Python: ipython3 7.19.0 (/home/paulo/environments/O2Sat/bin/ipython3)
RPC virtualenv....: O2Sat (/home/paulo/environments/O2Sat)
 Python...........: python3 3.7.3 (/home/paulo/environments/O2Sat/bin/python3)
 Jedi.............: 0.18.0
 Rope.............: 0.18.0
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: 20.8b1
Syntax checker....: flake8 (/home/paulo/environments/O2Sat/bin/flake8)
````

The only relevant difference I can see is the different version for Rope, which I fixed without any improvement.

`elpy-doc` is also not working in one of the envs, but is on the other.

I would appreciate any suggestion of what may be causing this behavior.
Thank you,

# My configuration
## OS

Linux paulo-pc 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)
 of 2019-09-23, modified by Debian

## Elpy configuration in my init.el
```elisp
(elpy-autodoc-delay 1.0)
(elpy-eldoc-show-current-function nil)
(elpy-modules
   (quote
    (elpy-module-company elpy-module-eldoc elpy-module-flymake elpy-module-pyvenv elpy-module-highlight-indentation elpy-module-yasnippet elpy-module-sane-defaults)))
(elpy-shell-add-to-shell-history t)
(elpy-shell-starting-directory (quote current-directory))
(elpy-shell-use-project-root nil)

(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))
(setq elpy-rpc-virtualenv-path 'current)
(setq elpy-rpc-python-command "python3")
(add-hook 'after-init-hook 'global-company-mode)

(setq elpy-rpc-timeout 10)
(setq company-idle-delay 1.0)

(define-key elpy-mode-map (kbd "M-.") 'elpy-goto-definition-or-rgrep)
(require 'boolcase-mode)
(add-hook 'python-mode-hook 'boolcase-mode)

(add-hook 'inferior-python-mode-hook
          (lambda () (add-hook
                      'comint-output-filter-functions
                      #'comint-truncate-buffer)))
(setq comint-buffer-maximum-size 1024)

(setq
 python-shell-interpreter "ipython3"     ;ipython3 ?
 python-shell-interpreter-args "--simple-prompt --pprint"
 python-shell-prompt-regexp "In \\[[0-9]+\\]: "
 python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: " )
```

**Comment by aiguofer** [comment]
I'm running into issues with `elpy-goto-definition` as well... I'm not sure if it's related.

I've had a set up that has worked for a long time, and allowed me to navigate code and get code completion using https://github.com/aiguofer/pyenv.el to switch environments [see this article for details](https://medium.com/analytics-vidhya/managing-a-python-development-environment-in-emacs-43897fd48c6a)

Some changes recently had broken my setup, but i could still get stuff working using `pyvenv-workon` in conjunction with `pyenv.el`. Now after the last time I updated, it doesn't seem to work at all. When I do `M-x elpy-goto-definition` it doesn't even seem to be bound to `M-.`, and when I hit enter nothing happens (no message, no warning, no nothing).

Here's my current `elpy-config` (the thing about `jupyter-console` is because I have it installed through `pipx`):

```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.35.0
Virtualenv........: fulcrum-contentful (/home/aiguofer/.pyenv/versions/fulcrum-contentful/)
Interactive Python: jupyter-console 6.2.0 (/home/aiguofer/.local/bin/jupyter-console)
RPC virtualenv....: rpc-venv (/home/aiguofer/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.8.5 (/home/aiguofer/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: 0.18.0
 Rope.............: 0.18.0
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: 20.8b1
Syntax checker....: flake8 (/home/aiguofer/.local/bin/flake8)

Warnings

The python interactive interpreter (jupyter-console) is not installed
on the current virtualenv
(/home/aiguofer/.pyenv/versions/fulcrum-contentful/). The system
binary (/home/aiguofer/.local/bin/jupyter-console) will be used
instead.

[Install jupyter-console]
```

**Comment by jotsif** [comment]
The upgrade to 0.18 broke this for me so I had to downgrade to Jedi 0.17.2 to get this working.

**Comment by vkurup** [comment]
Thanks @jotsif, that fixed it for me as well. I noticed this issue comment related to jedi 0.18: https://github.com/jorgenschaefer/elpy/issues/1868#issuecomment-767324717 I haven't yet tried that fork

**Comment by ppgaluzio** [comment]
That solved the problem for me! Thank you @jotsif.
