### ISSUE TITLE
`xref` unsuccessful in python buffers: "no definition found"

### ISSUE THREAD

**Issue by asberk** [jorgenschaefer/elpy#1885]
# Summary

The command `xref-find-definitions` is no longer working for me (nor its companions such as `xref-find-references`). Now, when I hit `M-.` I get `No definition found` in the minibuffer. IIRC, `xref` was working correctly prior to my having updated packages & installed `ggtags` (to work with `cc-mode` only, **not** to integrate with `elpy`). So, in particular, I cannot imagine how GNU Global could be mucking with `xref`, but it is a possibility. 

How can I return functionality to `M-.` once more? 

# Steps to reproduce

In `my_file.py` write:
```python
def func():
    print("hi")

func()
```
Move point to the second occurrence of `func` and hit `M-.` to receive `No definition found` message. 

# My configuration
## MacOS Catalina (10.15.7)

In python buffers, I have:

`xref-backend-functions` set to (buffer local) `(elpy--xref-backend t)`. When I try to run, in turn, `elpy--xref-backend`, I learn that this function takes no arguments. When I run it with no arguments, I get `(elpy--xref-backend)` returning `elpy`.

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.35.0
Virtualenv........: python38 (/usr/local/Caskroom/miniconda/base/envs/python38)
Interactive Python: python 3.8.5 (/usr/local/Caskroom/miniconda/base/envs/python38/bin/python)
RPC virtualenv....: python38 (/usr/local/Caskroom/miniconda/base/envs/python38)
 Python...........: python 3.8.5 (/usr/local/Caskroom/miniconda/base/envs/python38/bin/python)
 Jedi.............: 0.18.0
 Rope.............: Not found (0.18.0 available)
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: 20.8b1
Syntax checker....: flake8 (/usr/local/Caskroom/miniconda/base/envs/python38/bin/flake8)
```

## Elpy configuration in my init.el
```
(use-package elpy
  ;;:diminish elpy-mode
  :ensure t
  :defer t
  :init
  (pyvenv-activate "/usr/local/Caskroom/miniconda/base/envs/python38")
  (advice-add 'python-mode :before 'elpy-enable)
  :config
  (remove-hook 'elpy-modules 'elpy-module-flymake)
  (define-key elpy-mode-map (kbd "C-c C-n") 'flycheck-next-error)
  (define-key elpy-mode-map (kbd "C-c C-p") 'flycheck-previous-error)
  (define-key elpy-mode-map (kbd "s-<down>") 'elpy-nav-forward-block)
  (define-key elpy-mode-map (kbd "s-<up>") 'elpy-nav-backward-block)
  (define-key elpy-mode-map (kbd "s-<right>") 'elpy-nav-forward-indent)
  (define-key elpy-mode-map (kbd "s-<left>") 'elpy-nav-backward-indent)
  )
```

And in the `custom-set-variables` call I have

```
 '(elpy-rpc-timeout 2)
 '(elpy-rpc-virtualenv-path "/usr/local/Caskroom/miniconda/base/envs/python38")
```

**Comment by asberk** [comment]
Note that `xref` is working perfectly in buffers running `emacs-lisp-mode`, and this leads me to suspect it must be something related to its configuration with `elpy`.

**Comment by thormick** [comment]
I'm getting the same issue. I also see that if instead of using `M-.` I run [`elpy-goto-definition`](https://github.com/jorgenschaefer/elpy/blob/4032c7251eb2d74ec8a301a3988b62b7a0f00932/elpy.el#L1744) on the use of a function I also get `No definition found`. And I see that documentation lookup works; if I change the example to:
```python
def func():
    """Func doing func-y stuff"""
    print("hi")

func()
```
Then I can move the cursor to the use of `func()`, hit `C-c C-d`, and the documentation string displays just fine. So it doesn't seem to be an issue with either `xref` or Jedi.

**Comment by thormick** [comment]
Oops, nevermind, what I'm running into is #1868, and see that the fix there (don't forget the `import`) fixes my issue (though there's still an annoying prompt for a TAGS file, but only the first time I do `M-.` in an emacs session).

**Comment by asberk** [comment]
I can confirm that `elpy-doc` still works for me, and that `elpy-goto-definition` does not work (giving "No definition found"). 

I have never needed to supply/generate a TAGS file before for `xref` with `elpy`. I would like to avoid having to do that if possible.  

I tried the fix suggested in #1868 and now `elpy-goto-definition` works, but `xref-find-definitions` still does not. I was under the assumption that under the hood, the latter calls the former. I would appreciate any insight on being able to sort this out.

**Comment by excalamus** [comment]
For whatever reason, I was able to get the goto and find functions working again by rolling back to jedi 0.17.2 (0.17.1 also worked for me).

**Comment by galaunay** [comment]
I think this may be the same issue as #1795.

**Comment by SergiyKolesnikov** [comment]
Downgrading jedi to <0.18.0 worked for me:
```
cd ~/.emacs.d/elpy/rpc-venv
source bin/activate
pip install 'jedi<0.18.0'
```
Both `xref-find-definitions` and `xref-find-references` work. Although, I get the TAGS prompt on their first invocation.

**Comment by SergiyKolesnikov** [comment]
@galaunay I have just upgraded to elpy 1.35.0 (20210630.2317) and issue seems to be resolved in this version. `xref-find-definitions` and `xref-find-references` work as expected with jedi 0.18.0. No annoying TAGS prompt either.

**Comment by asberk** [comment]
Ditto @SergiyKolesnikov
