### ISSUE TITLE
Elpy not working with Jedi 0.18.0

### ISSUE THREAD

**Issue by georgek** [jorgenschaefer/elpy#1903]
# Summary

This was reported in #1890 but that issue was closed without being resolved.

# Steps to reproduce

0. `(setq elpy-rpc-virtualenv-path 'default)`
1. Install a fresh rpv-venv using `elpy-rpc-reinstall-virtualenv`.
2. Try to use Jedi for autocompletion, xref etc.

# Workaround 

Install Jedi 0.17 into the rpc-venv:
```
source ~/.emacs.d/elpy/rpc-venv/bin/activate
pip install jedi~=0.17.0
```

# My configuration
## OS
Ubuntu

## Elpy configuration in my init.el
```
(use-package elpy
  :after python
  :init
  (elpy-enable)
  :config
  (setq python-shell-interpreter "ipython"
        python-shell-interpreter-args "-i --simple-prompt")
  (setq elpy-rpc-python-command "python3.8")
  (setq elpy-rpc-virtualenv-path 'default)
  (setq elpy-rpc-backend "jedi")
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (setq-default elpy-django-test-runner-args
                '("test" "--noinput" "--keepdb" "--parallel" "--failfast"))
  (unbind-key "C-c C-n" elpy-mode-map)
  (unbind-key "C-c C-p" elpy-mode-map)
  :bind (:map elpy-mode-map
         ("C->" . #'elpy-nav-indent-shift-right)
         ("C-<" . #'elpy-nav-indent-shift-left)))
```

**Comment by smohaorg** [comment]
I had the same issue and after updating to the latest version using master branche, the bug has been fixed.

**Comment by gopar** [comment]
Is this still happening?
@georgek

**Comment by georgek** [comment]
After updating I've been able to upgrade to Jedi 0.18.0 with no problems. Thanks all!
