### ISSUE TITLE
Gauging Interest in Breakpoint/Debug overhaul

### ISSUE THREAD

**Issue by jdtsmith** [jorgenschaefer/elpy#1905]
I've been considering making some major improvements to elpy's debugging and breakpoint handling.  I'm the maintainer of the now fairly quiet [`IDLWAVE`](https://github.com/jdtsmith/idlwave) mode, and am transitioning from IDL to Python (as many in my field have done).  One of my favorite IDLWAVE features we developed was "electric debug mode".  It functioned much like `edebug` does for elisp: when enabled, you can use single key commands to step into or over statements, move up and down the call stack, set/remove breakpoints, print variable and statement values, etc.  It also had some other very nice features, many of which are challenging to use easily with `pdb` by itself:

- Commands to set/alter conditional breakpoints, and  "after" n breakpoints (aka `ignore` in pdb parlance)
- custom marginal glyphs to show the breakpoint "flavor" (several fringe bitmaps may be ok)
- mouse-based interaction with break point lines to enable/disable, remove, change conditions, repeat count, etc.
- commands to quickly move between breakpoint lines
- "here" command: continue execution up to the current line (one of my favorites!)

You can see the full list of commands IDLWAVE's electric debug mode supports [here](https://www.gnu.org/software/emacs/manual/html_mono/idlwave.html#Electric-Debug-Mode). 

It would be fairly straightforward to port much of this functionality to elpy.  I've started to sketch this out, and have realized that, while a separate package could be used to implement much of this, it would be easier to accomplish _within_ elpy itself (rather than advising a number of Elpy functions and the brittleness that entails).  Before going too far down this road, I wanted to ask the maintainers: how open would you be to this type of contribution?  

Despite some similarities, IDL and Python/PDB debugging have some real differences (e.g. PDB sessions have to be reset between each call of the code, wiping everything out!).  And I am by no means a PDB expert.  If there are others who'd like to contribute ideas, I'd be quite glad to discuss.  Thanks for considering.

**Comment by gopar** [comment]
Hey @jdtsmith ! Thanks for wanting to improve elpy :)

Currently there is a bit of a slowdown in the maintainership of elpy and it doesn't look like it'll pick up soon from any of the maintainers(The main maintainer is also out for a while). I've been slowly looking over at PR's but as I've been out of touch with lisp, its a rather slow process. 

A PR for improving elpy debugging would be greatly welcomed! But as I've mention it might be a while to get it merged in, but since you clearly have the ability the PR reviews would less strenuous. I don't want to tell you "Yes, do it!" and then never having the opportunity to get it merged in :(

I think we should let the other maintainers chime in as well.

**Comment by jdtsmith** [comment]
OK great.  Happy to hear other perspectives.  

In the meantime I've been digging a bit deeper, and found that the `__pdbi._runscript()` method that `elpy` uses to enable the debugger with a script has some serious [issues](https://github.com/gotcha/ipdb/issues/225) in `iPython`.  After a `pdb` debug session ends, the REPL is rendered unusable (it clobbers locals!).  I've found that `%run -d` is a great substitute, but obviously only for `iPython` users.  It would perhaps be wise to have a customize var that lets the user setup `elpy` for `iPython` and utilize this instead.  It also means all BP info has to be communicated after the debugger is entered (it stops on line 1 by default).  

I also have thought up a system to use `elpy-project-root` and find all buffer-visited `elpy-mode` files, and set their breakpoints in the `pdb` session too (or potentially _all_ `elpy` buffers with BPs, e.g. if your are debugging external libs at the same time).  Coming from another language, it seems very strange and backwards to me that you can't setup breakpoints _before_ debugging commences, and you have to keep setting them over and over!  `Elpy` will make that _much_ simpler.

**Comment by pweibert** [comment]
@jdtsmith I stumbled over the impossibility to set breakpoints in multiple files. In my opinion it is quite a frequent use case to set breakpoints in multiple files that will be called from a main file. So I opened a pull request #2007 which enables this functionality. You only need to replace the elpy-shell.el file in case you want to try it.

**Comment by jdtsmith** [comment]
Thanks.  I'm actually implementing a new standalone separate mode that is tied deeply into iPython.  One of the planned capabilities is a special `%debug` magic that allows passing in all the files/breakpoints/BP conditions up front.  That way you can set them in Emacs as needed (even with no shell running), and then on running a command or script file in iPython with debugging, they'll all be transferred "just in time".  If you are interested in helping/testing let me know.

**Comment by jdtsmith** [comment]
And I'll close this given that my efforts have shifted elsewhere, but happy to discuss if others want to carry it forward.
