### ISSUE TITLE
[Interpreter Setup] add-to-list or with-eval-after-load?

### ISSUE THREAD

**Issue by ThomasBucaioni** [jorgenschaefer/elpy#1908]
Following the [documentation](https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup), I've set the interpreter to `jupyter` with:
```
(start-process-shell-command "myprocessvirtualenv" "mybuffervirtualenv" "virtualenv ~/code/jupyterenvironment")
(start-process-shell-command "myprocesssource" "mybuffersource" "source ~/code/jupyterenvironment/bin/activate")
(setq python-shell-interpreter "~/code/jupyterenvironment/bin/jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters "jupyter")
;; (with-eval-after-load 'python-shell-completion-native-disabled-interpreters "jupyter")
```
But it happens that the list doesn't contain the interpreter, only _"pypy"_ and _"ipython"_ as in `python.el`. Also, I tried `with-eval-after-load` instead of `add-to-list`, but the list still doesn't show _"jupyter"_. Did I miss something?

**Comment by galaunay** [comment]
the `add-to-list` solution works for me.
Are those lines in your `init.el` ?
Doesit work if you ran it manually (with `M-: (add-to-list 'python-shell-completion-native-disabled-interpreters "jupyter")` for example) ?

**Comment by ThomasBucaioni** [comment]
It works now, thank you for your time

**Comment by hongyi-zhao** [comment]
I use the same configuration, but Emacs is always stuck there forever when I hit `C-c C-c`.
