### ISSUE TITLE
Elpy completely broken on Emacs 27 (MacOS 11.2.3)

### ISSUE THREAD

**Issue by sawan** [jorgenschaefer/elpy#1910]
# Summary

Elpy is completely not working on Emacs 27.

This is most likely something to do with the RPC facility.

# Steps to reproduce

1. Remove every thing from and including 

> ~/.emacs.d/elpy

2. Fire up Emacs
3. `M-x elpy-reinstall-virtualenv`
4. Verify environment is working by navigating to 

> ~/.emacs.d/elpy/rpc-env

, manually sourcing, importing packages such as `jedi`, etc.
5. Open up a file, test.py
6. `M-x elpy-enable` + `M-x elpy-rpc-restart`
7. import os, `M-x elpy-goto-definition`
8. Message says that package `jedi` needs to be installed to make this work. As seen below, all required packages are installed.

No Elpy functionality works in the file, 

e.g. `M-x elpy-black-fix-code `gives me: 

`Timeout during RPC call fix_code_with_black from backend `

A great, great pity -- at his point I would pay money to get this suff to work. I love Elpy and it has been solid for last 2-3 years; this issue is seriously hampering my work.

# My configuration
## OS
MacOS 11.2.3

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 27.1
Elpy..............: 1.35.0
Virtualenv........: None
Interactive Python: python 2.7.16 (/usr/bin/python)
RPC virtualenv....: rpc-venv (/Users/sawanvithlani/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.8.6 (/Users/sawanvithlani/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.18.0
 Rope.............: 0.18.0
 Autopep8.........: 1.5.6
 Yapf.............: 0.31.0
 Black............: 20.8b1
Syntax checker....: Not found (flake8)

```

## Elpy configuration in my init.el
```
None
```

**Comment by sawan** [comment]
I switched back to Emacs 26 and still no luck.

Most likely this is a MacOS 11 issue.

**Comment by caioboffo** [comment]
Having the same issue with emacs27 and ubuntu20

**Comment by caioboffo** [comment]
> I switched back to Emacs 26 and still no luck.
> 
> Most likely this is a MacOS 11 issue.

Have a look at this #1903 and #1890

**Comment by sawan** [comment]
#1890 Suggested downgrade of Jedi seems to have solved this.

Many thanks @caioboffo for triaging.
