### ISSUE TITLE
Unable to create rpc-venv on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by eanopolsky** [jorgenschaefer/elpy#1937]
# Summary

I'm receiving an error when elpy attempts to create its rpc-venv on Ubuntu 20.04.2

# Steps to reproduce

- Installed Ubuntu Server 20.04.2 in a virtual machine (ubuntu-20.04.2-live-server-amd64.iso) using all default options.
- Logged in using the user account created during installation and ran:

```
sudo apt-get update
sudo apt-get install emacs-nox
```

- Created a ~/.emacs file with the following content:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```

- Installed use-package version 20210207.1926 from melpa.
- Added the following to .emacs:

```
(use-package elpy
  :ensure t
  :init
  (elpy-enable))
```

- Closed emacs, reopened emacs, and ran `M-x elpy-config RET`. Received response `Cannot find executable 'python', please set 'elpy-rpc-python-command' to an existing executable.` in the minibuffer.
- Exited emacs and ran `sudo apt-get install python-is-python3`.
- Started emacs, and ran `M-x elpy-config RET`. Received response `Elpy needs the 'virtualenv' or 'venv' python packages to create its virtualenv. Please install one of them or disable the dedicated virtualenv with '(setq elpy-rpc-virtualenv-path 'current)'`.
- Exited emacs and ran `sudo apt-get install python3-venv`.
- Started emacs and ran `M-x elpy-config RET`. Received the response `Elpy failed to create its dedicated virtualenv. Please check the '*elpy-virtualenv*' buffer.`
- Checked the indicated buffer. It had the following content:

```
Running 'python -m venv /home/anopolsky/.emacs.d/elpy/rpc-venv':

Error: Command '['/home/anopolsky/.emacs.d/elpy/rpc-venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

Elpy failed to install its dedicated virtualenv due to the above
error. If the error details does not help you fixing it, You can
report this problem on Elpy repository on github.
In the meantime, setting the `elpy-rpc-virtualenv-path' option to
ensure `system' or `current' should temporarily fix the issue.
```

- Exited emacs and ran `strace -v -f -s 100 -o ~/emacs.strace emacs`
  - Typed `M-x elpy-config RET` and received the same errors as before.
  - Exited emacs.
- Ran `grep execve emacs.strace`. The interesting line starts with the following text:

`3149 execve("//bin/python", ["//bin/python", "-m", "venv", "/home/anopolsky/.emacs.d/elpy/rpc-venv"]` ...

Note the **double** slash before bin.

- Ran:

```
anopolsky@elpy-debug-temp:~$ which python
/usr/bin/python
anopolsky@elpy-debug-temp:~$ file $(which python)
/usr/bin/python: symbolic link to python3
anopolsky@elpy-debug-temp:~$ file $(which python3)
/usr/bin/python3: symbolic link to python3.8
anopolsky@elpy-debug-temp:~$ file $(which python3.8)
/usr/bin/python3.8: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9c096cdc8214a805dca8d174fe072684b0f21645, for GNU/Linux 3.2.0, stripped
anopolsky@elpy-debug-temp:~$ python -m venv normal_python_test
anopolsky@elpy-debug-temp:~$ normal_python_test/bin/python -Im ensurepip --upgrade --default-pip
Looking in links: /tmp/tmpnhnpar0x
Requirement already up-to-date: setuptools in ./normal_python_test/lib/python3.8/site-packages (44.0.0)
Requirement already up-to-date: pip in ./normal_python_test/lib/python3.8/site-packages (20.0.2)
Requirement already up-to-date: pkg_resources in ./normal_python_test/lib/python3.8/site-packages (0.0.0)
anopolsky@elpy-debug-temp:~$ /bin/python
python            python3           python3.8         python3.8-config  python3-config    
anopolsky@elpy-debug-temp:~$ file /bin/python
/bin/python: symbolic link to python3
anopolsky@elpy-debug-temp:~$ file /bin/python3
/bin/python3: symbolic link to python3.8
anopolsky@elpy-debug-temp:~$ file /bin/python3.8
/bin/python3.8: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9c096cdc8214a805dca8d174fe072684b0f21645, for GNU/Linux 3.2.0, stripped
anopolsky@elpy-debug-temp:~$ /bin/python -m venv single_slash_test
anopolsky@elpy-debug-temp:~$ single_slash_test/bin/python -Im ensurepip --upgrade --default-pip
Looking in links: /tmp/tmpueajqz0i
Requirement already up-to-date: setuptools in ./single_slash_test/lib/python3.8/site-packages (44.0.0)
Requirement already up-to-date: pip in ./single_slash_test/lib/python3.8/site-packages (20.0.2)
Requirement already up-to-date: pkg_resources in ./single_slash_test/lib/python3.8/site-packages (0.0.0)
anopolsky@elpy-debug-temp:~$ //bin/python -m venv double_slash_test
Error: Command '['/home/anopolsky/double_slash_test/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
anopolsky@elpy-debug-temp:~$ 
```

It appears that python is able to create a virtual environment without issues when it's run as /bin/python or /usr/bin/python, but //bin/python causes the error. I don't know why emacs is running //bin/python.

This may or may not be related to https://github.com/jorgenschaefer/elpy/issues/1756.

# My configuration
## OS

Ubuntu 20.04.2 installed in a VM from the official ISO using default install settings. My copy of ubuntu-20.04.2-live-server-amd64.iso has sha256sum d1f2bf834bbe9bb43faf16f9be992a6f3935e65be0edece1dee2aa6eb1767423, which I believe is correct.

## Result of `(elpy-config)`
```
Debugger entered--Lisp error: (error "Elpy failed to create its dedicated virtualenv. Please check the ‘*elpy-virtualenv*’ buffer.")
  signal(error ("Elpy failed to create its dedicated virtualenv. Please check the ‘*elpy-virtualenv*’ buffer."))
  error("Elpy failed to create its dedicated virtualenv. Please check the `*elpy-virtualenv*' buffer.")
  elpy-rpc--create-virtualenv("/home/anopolsky/.emacs.d/elpy/rpc-venv")
  elpy-rpc-get-or-create-virtualenv()
  elpy-config--get-config()
  elpy-config()
  eval((elpy-config) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

## Elpy configuration in my init.el
```
(use-package elpy
  :ensure t
  :init
  (elpy-enable))
```

**Comment by erpo41** [comment]
Workaround:
- Run `sudo apt-get install python3-pip`.
- Add `(setq elpy-rpc-python-command "/usr/bin/python3")` to .emacs.
- Start emacs and run `M-x elpy-config RET`.
