### ISSUE TITLE
With Python 3.10, distutils is deprecated, warning error breaks elpy-config

### ISSUE THREAD

**Issue by ViktorHaag** [jorgenschaefer/elpy#1938]
As of Python 3.10, attempting to import LooseVersion from distutils.version causes Python to emit a DeprecationWarning; this causes elpy-config to not work properly when using Python 3.10 as the underlying interpreter (see [line 634 in elpy.el](https://github.com/jorgenschaefer/elpy/blob/4248dccef31e260813d93cafd083bfcd71efc92a/elpy.el#L634)):

```
In [1]: from distutils.version import LooseVersion
<ipython-input-1-76de18461efc>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
```

Switching to using Version from the packaging module seems to work instead; changing that import in elpy.el to this, seems to avoid the warning emitted and get elpy-config working again:
```
from packaging.version import Version as LooseVersion
```
(importing Version this way attempts to avoid other code changes in elpy.el, and seems to work just fine as all we seem to do is instantiate two Versions with version strings and use a `<` compare operation on the two objects)

I can try to follow up with a PR, but I'm not familiar with the build/test environment needed for this project so I'll have to see if I can get something set up to do that.

As far as I can tell, this error might only be cosmetic -- that is, it causes elpy-config not to work, or report the state of the underlying system properly, but elpy seems able to still locate all the things it needs to function just the same.

**Comment by ViktorHaag** [comment]
Here's a report of my elpy-config once making the change to use packaging instead of distutils in elpy.el above to get it working:
```
Elpy Configuration

Emacs.............: 27.2
Elpy..............: 1.35.0
Virtualenv........: None
Interactive Python: /Users/vhaag/.pyenv/shims/python3 3.10.0 (/Users/vhaag/.pyenv/shims/python3)
RPC virtualenv....: .pyenv (/Users/vhaag/.pyenv)
 Python...........: /Users/vhaag/.pyenv/shims/python3 3.10.0 (/Users/vhaag/.pyenv/shims/python3)
 Jedi.............: 0.18.0
 Autopep8.........: Not found (1.5.7 available)
 Yapf.............: Not found (0.31.0 available)
 Black............: 21.9b0
Syntax checker....: flake8 (/usr/local/bin/flake8)

Warnings

You have not activated a virtual env. It is not mandatory but often a good idea
to work inside a virtual env. You can use `M-x pyvenv-activate` or `M-x
pyvenv-workon` to activate one.

The directory ~/.local/bin/ is not in your PATH. As there is no active
virtualenv, installing Python packages locally will place executables in that
directory, so Emacs won't find them. If you are missing some commands, do add
this directory to your PATH -- and then do `elpy-rpc-restart'.
```

**Comment by gopar** [comment]
Fixed now:
https://github.com/jorgenschaefer/elpy/issues/1939
