### ISSUE TITLE
It seems impossible to prevent automatic completion after a dot, regardless of company settings

### ISSUE THREAD

**Issue by prosoitos** [jorgenschaefer/elpy#1958]
# Summary

I don't like company and eldoc popups to be triggered automatically. I much prefer triggering them manually with a kbd when I need them. This is how I have configured company and it works perfectly everywhere... except for elpy which seems to override my company settings.

My my config, I have:

```el
(setq company-idle-delay nil)
(setq company-minimum-prefix-length 10)
```
The first one should be sufficient to stop company from auto-completing without being manually triggered (and it works well elsewhere). The 2nd one is thus not useful, but I am adding it here to show that elpy does not follow these settings.

Whenever I use a dot in a python-mode buffer, the company auto-completion popup pops up automatically, even if there is only one character (e.g. `t.`) and even if it shouldn't popup in the first place.

So my questions are:

- Why isn't elpy respecting my company settings?
- What could I do to have company behave in my python buffers the way it does everywhere else?

Of course, I could disable company in python-mode and that would solve those annoying popups when I don't want them. But then, of course, I wouldn't be able to trigger them with a kbd when I do want them.

Thanks!!!!

# My configuration
## OS

Arch Linux (5.15.13-arch1-1)

## Result of `(elpy-config)`

```
Emacs.............: 27.2
Elpy..............: 1.35.0
Virtualenv........: None
Interactive Python: python 3.10.1 (/usr/bin/python)
RPC virtualenv....: rpc-venv (/home/marie/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.10.1 (/usr/bin/python)
 Jedi.............: 0.18.1
 Autopep8.........: Not found (1.6.0 available)
 Yapf.............: Not found (0.32.0 available)
 Black............: Not found (21.12b0 available)
Syntax checker....: flake8 (/usr/bin/flake8)
```

## Elpy configuration in my init.el

```el
(elpy-enable)

(setq elpy-modules
   '(elpy-module-company elpy-module-eldoc elpy-module-pyvenv elpy-module-highlight-indentation
     elpy-module-yasnippet elpy-module-django elpy-module-sane-defaults))
```

**Comment by prosoitos** [comment]
Note: I suspect that the problem has to do with the dot.

company-jedi has a variable about auto-completion after dot. Maybe a similar variable could be added into elpy???

Thanks!!!

**Comment by gopar** [comment]
Does running the company settings in `elpy-mode-hook` help with this?

```
(add-hook 'elpy-mode-hook '(lambda () (setq company-idle-delay nil) (setq company-minimum-prefix-length 10))
```

**Comment by smithzvk** [comment]
Yep, that hook seems to work to restore the original values for me.

**Comment by gopar** [comment]
Closing this as resolved, since settings can be put in `elpy-mode-hook`
