### ISSUE TITLE
Marmalade still on 1.2.1 (broken)

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#196]
Marmalade is broken and does not accept new packages. I am afraid I have no idea how long this will last.

In the meantime, you can download http://jorgenschaefer.github.io/packages/elpy-1.3.0.tar and use `M-x package-install-file`.

This is a suboptimal situation, but nothing I can currently fix. :-(

**Comment by offby1** [comment]
[This](https://github.com/jorgenschaefer/elpy/blob/master/NEWS.rst#new-in-elpy-1180) says 

> Elpy is now using MELPA Stable as the official distribution point. Please remove jorgenschaefer.github.io from your sources list if you still use it. It will not receive further updates after 1.18.
