### ISSUE TITLE
Emacs RPC communication on windows freezes Emacs

### ISSUE THREAD

**Issue by adamc55** [jorgenschaefer/elpy#199]
I'm having Emacs freeze totally periodically after adding elpy -- I'm using the package elpy-20140213.1028 (version 1.3.0, according to elpy.el).

It happens when I'm just typing -- looks like autocomplete gets triggered, but then there is a total freeze, so I can't tell you what _elpy-rpc_ says.

**Comment by MehrdadAG** [comment]
Hi. I am facing the same problem with emacs 25.1 and jedi 0.10.0 
Emacs halts and i have to close the terminal and reopen the file again. It happens i think when jedi tries to provide autocomplete for the code

**Comment by aagaard** [comment]
I face the same issue. My configuration:

OS: Windows 10
RPC Python........: 3.6.1 (c:/Users/me/.envs/yiu/pythonw.exe)
Emacs.............: 25.1.1
Elpy..............: 1.15.1
Jedi..............: 0.10.3

Pythonw uses 100% CPU and emacs hangs. It cannot be "unlooped" with C-g, so it is something between the OS and emacs that does not response. If I kill the pythonw.exe process, the emacs comes back and modify the buffer.
