### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by lvh** [jorgenschaefer/elpy#21]
There's a very noticeable (order of magnitude a second, I'd guess) delay when typing.

I've tried the following things:
- disabling python-check.sh
- disabling flymake entirely
- removing (elpy-use-ipython)
- increasing ac delays (`(setq ac-auto-show-menu 1.0) (setq ac-quick-help-delay 1.2)` and also the same thing with 2.0 and 2.2 as delays)
- moving the ropeproject to be inside my package instead of the repository toplevel directory (just in case it was accidentally trying to index the whole virtualenv)

... but so far nothing helps :(

Here's a video showing the issue writing a simple example class (a WTForms validator); my keyboard typing on the audio track so you can see the sync issue:

https://dl.dropbox.com/u/38476311/elpyperformanceissue.mov

(It's AAC/H.264; please let me know if you have issues viewing it and I'll convert it to something else.)

I'm running a fully updated current-generation Macbook Air with OS X 10.8 and Emacs for OS X. Any help is very appreciated :)

**Comment by Gnouc** [comment]
@jorgenschaefer I faced the same problem with the stable version. Here is my config:
```
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("melpa-stable" . "http://melpa.milkbox.net/packages/")
                         ("elpy" . "https://jorgenschaefer.github.io/packages/")))

....

;; elpy
(use-package elpy
  :ensure t
  :init
  (setq elpy-rpc-backend "jedi")
  (with-eval-after-load 'python (elpy-enable))
  :bind ("M-," . pop-tag-mark)
  :config
  (elpy-use-ipython)
  (setq elpy-rpc-backend "jedi")
  ;; fill column indicator
  (use-package fill-column-indicator
    :ensure t
    :config
    (add-hook 'after-change-major-mode-hook 'fci-mode)
    (setq fci-rule-color "LightSlateBlue")
    (setq-default fci-rule-column 79)
    (setq fci-handle-truncate-lines t))
  (add-hook 'elpy-mode-hook
            (lambda ()
              (local-set-key (kbd "C-c M-c") 'elpy-shell-switch-to-shell)
              (setq python-indent-offset 4))))
```

Set `elpy-rpc-backend` to `jedi` with no luck, typing text is extremely slow.

**Comment by jorgenschaefer** [comment]
@Gnouc, thanks for the report! What's the size of the Python buffer you are editing? Also, what file system is that on (local or network)?

**Comment by Gnouc** [comment]
@jorgenschaefer It's a standalone script, 32KB in size. I did all the work in local file system, an `ext4` partition on `Debian Jessie 8.2`

**Comment by jorgenschaefer** [comment]
32KB is pretty large – Emacs has to write out the file on every change to get completions etc. If you set `elpy-rpc-ignored-buffer-size` to a lower value, say, 10000 maybe, does that speed up editing? It will disable "good" completions, though.

**Comment by Gnouc** [comment]
@jorgenschaefer Yes, setting `elpy-rpc-ignored-buffer-size` to `10000` speed up typing much. But I can not do completion anymore with error `elpy-company-backend async timeout with args`.

But you can see my above config was set elpy backend two times. if I removed the second one:
```
;; elpy
(use-package elpy
  :ensure t
  :init
  (setq elpy-rpc-backend "jedi")
  (with-eval-after-load 'python (elpy-enable))
  :bind ("M-," . pop-tag-mark)
  :config
  (elpy-use-ipython)
  ;; fill column indicator
  (use-package fill-column-indicator
    :ensure t
    :config
    (add-hook 'after-change-major-mode-hook 'fci-mode)
    (setq fci-rule-color "LightSlateBlue")
    (setq-default fci-rule-column 79)
    (setq fci-handle-truncate-lines t))
  (add-hook 'elpy-mode-hook
            (lambda ()
              (local-set-key (kbd "C-c M-c") 'elpy-shell-switch-to-shell)
              (setq python-indent-offset 4))))
```

Then the typing is not slow as `rope` backend, but is not as fast as setting ignore buffer. But it's acceptable. I have no ideal why setting backend two times causing this issue.

**Comment by jorgenschaefer** [comment]
That is strange indeed – I am afraid I do not know `use-package`, so I have no idea what it does there.

**Comment by ChillarAnand** [comment]
@jorgenschaefer  `use-package` just ensures that the package is installed. Code under `:init` will be evaluated immediately where as code under `:config` will be evaluated lazily and bind just binds keys to corresponding mode map.

**Comment by jorgenschaefer** [comment]
@ChillarAnand, I figured that is the intention, but why would that affect the behavior in this case? Does "lazily" do something that might not be obvious on the first glimpse? I do not know.
