### ISSUE TITLE
 Emacs RPC communication on windows freezes Emacs

### ISSUE THREAD

**Issue by adamc55** [jorgenschaefer/elpy#212]
I can't re-open issue #199, but alas, the problem has re-appeared. It seems that switching to pythonw helps, but it is not a complete fix. (Or, possibly, there are multiple causes.)

Still, if it stays down to once a day or so, simply killing the python process is an acceptable work-around.

**Comment by ujj-w-a-l** [comment]
Mine got solved by installing rpcbind package from the package manager.
