### ISSUE TITLE
Re-evaluate Rope and Jedi

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#229]
Elpy uses Rope as the default backend. This was based on early impressions of completion coverage. But Jedi is actively maintained and has grown a lot since then, while Rope is more or less stale and is accumulating cruft. Maybe it's time to switch the default, if not outright discontinuing support for multiple backends and simply using Jedi as the default.

**Comment by gopar** [comment]
Can be closed since we use jedi only now as the backend
