### ISSUE TITLE
auto-complete vs. company

### ISSUE THREAD

**Issue by piotrklibert** [jorgenschaefer/elpy#268]
Hi,

I've been using elpy for the last year or so without updating it (or maybe I updated it once - the version I had until yesterday was ~1.2) and without any major issues. elpy is a great and I'm really grateful @jorgenschaefer for building it! With this out of a way, let's get to the point.

I upgraded yesterday to git master branch (manually, I don't trust package.el enough to let it manage elpy and a few other essential plugins), it took some work as usual (upgrading python dependencies by hand) but it was not a big deal. But, after restarting Emacs, I got an error saying that there is no "company" module, and that apparently elpy was trying to load it.

In effect I was forced to ditch auto-complete.el (which I quite liked and customized quite a bit during the last year) and to switch to company. I'm not mad or anything, I wanted to try company anyway, but I'd like to ask: why the switch?

I read the NEWS file, but there was nothing about the switch there, I googled a bit, but without any luck, and so I came here to ask. Was auto-complete->company meant to fix some bugs? Does company mode have better API? Additionally, do you have any advice for using them both in one Emacs session? The nimrod-mode I use depends on auto-complete, but from what I see enabling both company-mode and auto-complete causes (both of them) to stop working.

Once again, thanks for outstanding elpy mode, I realize that packaging and dependency tracking in Elisp is still not a solved problem, I'm just asking this (mostly) out of curiosity.

**Comment by DungxNguyen** [comment]
Hi. Are you working on this feature yet? 

I'm trying to order the candidates by meta, i.e I want the params to be displayed at the top of the list. 
However, when I tried to write a new function to order the candidates, it keep saying the candidates variable is void. I tried to print it out (print candidates) inside elpy-command-backend but it also says candidates variable is void.

Do you have any suggestion on this?
>  4) Completions in correct order
> 
> Not sure what you mean there. By default, company does an alphabetical sort, though backends can override the sort order. I'm thinking of doing the latter for Elpy eventually, depending on what the backends can do.
>
