### ISSUE TITLE
Unable to install elpy

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#273]
I am having a hard time installing 

I have the following in my `.emacs` file:

```
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                 ("marmalade" . "http://marmalade-repo.org/packages/")))
; Auto-complete:
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
; Org mode
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("elpy" . "http://jorgenschaefer.github.io/packages/") t)
```

I did `M-x describe-variable RET package-archives RET` to confirm that `package-archives` have the correct values:

```
package-archives is a variable defined in `package.el'.
Its value is (("gnu" . "http://elpa.gnu.org/packages/")
 ("marmalade" . "http://marmalade-repo.org/packages/")
 ("melpa" . "http://melpa.milkbox.net/packages/")
 ("org" . "http://orgmode.org/elpa/")
 ("elpy" . "http://jorgenschaefer.github.io/packages/"))
```

I then do `M-x refresh-package-contents`, but when I then try: `M-x install-package RET elpy RET` I get no matches.

This is all with a nightly build of Emacs from ~two weeks ago.

**Comment by hasmisahar** [comment]
Hi, I cant find elpy on package list what should i do?

**Comment by mhauskn** [comment]
I encountered this problem when using Emacs 25 on Windows. The problem is that this version of emacs on windows doesn't support TLS and can't communicate with the https site.  One solution was changing the address from "https://stable.melpa.org/packages/" to "http://stable.melpa.org/packages/".

**Comment by austinjp** [comment]
For those arriving here experiencing issues with TLS/https on Linux/Ubuntu, try adding the following at the top of your `.emacs` *before* `(package-initialize)`:

```lisp
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.2")
```

See <https://emacs.stackexchange.com/a/51772> for background info.

You may need to do `sudo apt install gnutls-bin libgnutls28-dev` beforehand.

Note the TLS version specified is 1.2, I found that 1.3 was not supported. You can check what's supported on various sites, e.g. here:

<https://www.ssllabs.com/ssltest/analyze.html?d=elpa.gnu.org&hideResults=on>
