### ISSUE TITLE
Use Rope *and* Jedi when the other lacks a feature

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#329]
Both Rope and Jedi offer features the other lacks. It would be interesting to use one or the other when the primary one lacks a feature, and use the backend selection only for when both support a feature.

E.g. Rope supports retrieving a docstring, but does not support finding symbol occurrences, while Jedi does not know how to retrieve a docstring, but can easily find symbol occurrences.

**Comment by offby1** [comment]
:+1:

**Comment by gopar** [comment]
Closing, elpy only suse jedi now
