### ISSUE TITLE
Relaxing highlighting of warnings/errors (excluding codes)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#346]
Hi,

I have been using Elpy for some time now, and I love it. I hope to be able to contribute to the repository at some in the near future. In the mean time, thanks again for this great package. 

One problem I am having is the warning/error highlighting on my files seem a bit too strict (I get lots of errors for `E111 indentation is not a multiple of four`, `E501 line too long` etc.). I guess my coding style isn't good (good to know though!), but almost every line in my file has an exclamation point and is underlined in red. 

Is there any way to relax the rules for underlines/exclamation points? Perhaps there is a way of letting the user provide a list of codes to exclude from the warnings? In my case for example, excluding `E111`  would probably be enough.

On this note, is there any way within Elpy to automatically fix the indentation of a file to make it compliant with `E111`?

**Comment by zeeshansayyed** [comment]
Thanks a lot for this discussion. It helped me. I eventually found this - http://flake8.readthedocs.org/en/latest/config.html
It's better to create user-level settings if you want it to be for all projects.

**Comment by aarohijohal** [comment]
> Thanks a lot for this discussion. It helped me. I eventually found this - http://flake8.readthedocs.org/en/latest/config.html
> It's better to create user-level settings if you want it to be for all projects.

@zeeshansayyed That's a very useful point!
Here's an updated URL to what you linked: http://flake8.pycqa.org/en/latest/user/configuration.html
