### ISSUE TITLE
Completion on self-written modules

### ISSUE THREAD

**Issue by profhase** [jorgenschaefer/elpy#350]
I got a module installed with

    python setup.py develop

From here jedi only completes the import statement. There is no completion menu for classes/functions defined in this module, nor there is a help on function signatures or a possibility to `go to definition`. Is it a bug or is jedi missing such features?

**Comment by jorgenschaefer** [comment]
I'll close this issue for the time being. Please do not hesitate to re-open it if you find further information, and I hope you enjoy Elpy even with this problem!
