### ISSUE TITLE
Timeout during RPC call get_definition from backend 

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#362]
I have a function defined in a file, and later in that file I am using that function. When I do `M-.` (i.e. `elpy-`goto-definition`) I get the following error in the minibuffer`Timeout during RPC call get_definition from backend`. I have tried increasing the timeout to up to 5 seconds without luck.

I am using the latest elpy from `elpa`. What could be wrong?

Here is the output of `elpy-config`:

```
Elpy Configuration

Virtualenv........:  (/Users/josh/anaconda/envs/py3k/)
RPC Python........: 3.3.5 (/Users/josh/anaconda/envs/py3k/bin/python)
Interactive Python: python (/Users/josh/anaconda/envs/py3k/bin/python)
Emacs.............: 24.3.93.1
Elpy..............: 1.5.1
Jedi..............: 0.8.1-final0
Rope..............: 0.9.4-1
Syntax checker....: pyflakes (/Users/josh/anaconda/envs/py3k/bin/pyflakes)
```

**Comment by chenxianneng** [comment]
thanks very much I have the same problem and I have solute it on the same way too
