### ISSUE TITLE
Elpy Eror (example of many). Python 3 with conda virtualenv

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#363]
I just run into the following error (this is an example of many other errors that I run into frequently). Below is the output. I apologize I didn't include the source code in Python for reproduction. A large part of the code is proprietary source code. One thing I can say is that the code in the file is not a script or module that one could import. It is rather a collection of Python snippets that I execute in IPython. Each block is functional, but running the code sequentially may not work. 

```
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new
```
* [Error message](https://gist.github.com/ribonoous/dd4e6443b3f3ee3612f6)

**Comment by jorgenschaefer** [comment]
Any updates on this? I'm sadly at a loss of ideas on what to do. Would be great if it would just fix itself! :-D

**Comment by davidhalter** [comment]
The cache sits in `~/Library/Caches/Jedi` on OS X.

**Comment by jorgenschaefer** [comment]
Lacking any further updates, I will close this issue. Please do not hesitate to re-open it or file a new one if the problem persists and/or you have further information.

And thanks to David for the help, too!
