### ISSUE TITLE
Move indentation block

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#367]
Indentation block detection for moving them around needs to be reworked.

- Lines starting with `else:`, `elsif:`, `except:` and `finally:` belong to the preceding block
- Empty lines belong to the block _preceding_ them
- Comments directly in front or after a block belong to that block (they can join blocks, too)
- Comments surrounded by whitespace are blocks of their own

This includes #279 and #310

**Comment by jorgenschaefer** [comment]
Don't forget to include decorators with the same iblock (see #443).

**Comment by offby1** [comment]
Just curious: why is it important to note that `Empty lines belong to the block preceding them`?

**Comment by jorgenschaefer** [comment]
Hm. I actually think that's wrong.

I'm totally not sure about empty line handling anymore. Probably empty lines should be separators, not part of blocks.

**Comment by whirm** [comment]
What about using whatever PEP8 says for each case (classes, functions, etc.)
https://www.python.org/dev/peps/pep-0008/#id15

**Comment by jorgenschaefer** [comment]
@whirm, as far as I can see, PEP8 says blank lines are separators, no?

**Comment by whirm** [comment]
Sorry, wrong link I meant to paste this one: https://www.python.org/dev/peps/pep-0008/#blank-lines

I was thinking about using them as separators as you said, and once you move a block, you "fix" the amount of empty lines you will be "dragging" with it (1 line between in-class function definitions, 2 lines between top level class and function definitions, an so on)

**Comment by jorgenschaefer** [comment]
Hm. Nice idea.

(Eek! More work! BAD IDEA! :-D)

**Comment by jorgenschaefer** [comment]
- Lines starting with `else:`, `elsif:`, `except:` and `finally:`, as well as closing parentheses (`)]}`) belong to the preceding block
- Lines starting with @ symbols (decorators) belong to the block following block
- Comments directly in front or after a block belong to that block (they can join blocks, too)
- Comments surrounded by whitespace are blocks of their own
- Empty lines _separate_ blocks

**Comment by jorgenschaefer** [comment]
Atom does move the current line or the current selection _line-wise_ only (with C-up/down). That might actually be perfectly sufficient and less DWIMmy.
