### ISSUE TITLE
Prompt for session name

### ISSUE THREAD

**Issue by mankoff** [jorgenschaefer/elpy#383]
I recall elpy used to ask me for a session name. This was mentioned in #85, but no specific resolution was there. Now the python shell is always in the *Python* buffer. Is it possible to set a variable so that elpy asks what buffer name I want? It would be useful to have different Python processes in each Emacs frame.

**Comment by jorgenschaefer** [comment]
I suspect this is solved :-) Thanks for the code, I hope it will be useful for others!

**Comment by mankoff** [comment]
Yes solved. Sorry for leaving open. Thanks for cleaning up.
