### ISSUE TITLE
object instance autocompletion

### ISSUE THREAD

**Issue by statmobile** [jorgenschaefer/elpy#391]
I was wondering if I could get some help with autocompletion.  I'm using rope as the backend, and as a side not I don't see the M-x elpy-rpc-backend to change to jedi to see if that would be any better.  I can get completion on basic object such as lists, i.e.:
```python
a = [66, 33, 22]
a.[tab] 
```
works, but if I load up a pandas object
```python
import pandas as pd
sales = pd.read_csv("http://pbpython.com/extras/sample-sales.csv")
sales.[tab]
```
does not work.  Any help would be greatly appreciated.

**Comment by jorgenschaefer** [comment]
I assume this question was answered, so I will close this issue. Please do not hesitate to open a new issue if you encounter any further problems.
