### ISSUE TITLE
The sane defaults turn truncate long lines to off by accident

### ISSUE THREAD

**Issue by shackra** [jorgenschaefer/elpy#395]
I have set truncate long likes to `t` by default on my Emacs, but when elpy-mode is started, it disables the minor mode, I think, by accident. This don't happen anymore if I turn off Elpy's sane defaults.

**EDIT:** interesting though, there is no reference to `toggle-truncate-lines` or to `truncate-lines` variable on the entire project.

**Comment by jorgenschaefer** [comment]
Any updates on this?

**Comment by jorgenschaefer** [comment]
Oops, did not mean to close this quite yet.

**Comment by shackra** [comment]
I dont have this issue anymore!

**Comment by jorgenschaefer** [comment]
Great! Please do not hesitate to open a new issue of you have further problems!, and enjoy elpy!  :-)

**Comment by shackra** [comment]
Thanks!
