### ISSUE TITLE
TAB inserts TAB, not spaces

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#410]
I have the following Python setup on my `.emacs` file:

```
(package-initialize)
(elpy-enable)
(setq elpy-rpc-backend "jedi")

; See https://github.com/jorgenschaefer/elpy/issues/341
(add-hook 'pyvenv-post-activate-hooks 'elpy-rpc-restart)

; Overriding elpy keyboard 
(load "python")
(define-key python-mode-map [remap backward-sentence] nil)
(define-key python-mode-map [remap forward-sentence] nil)
; (add-hook 'pyvenv-post-activate-hooks 'elpy-rpc-restart)

(add-hook 'python-mode-hook
      (lambda ()
        (setq indent-tabs-mode t)
        (setq tab-width 2)
                (setq python-shift-right 2)
                (setq python-shift-left 2)
        (setq python-indent 2)))

(pyvenv-activate "/Users/avazquez/anaconda3/envs/py34/")
```

I am working on a Python file that uses **four spaces** as indentation (which I can see, by using `whitespace-mode`). The file was written by someone else. Strangely, when I try to add and indent code (e.g. a single line) on the file using `TAB RET`, I see that the character `TAB` (not two spaces) is inserted. 

How can I change this to auto-detect the indentation schema used in the file, and if no clear one is used (yet), use two spaces? Is this something that Elpy can help with?

**Comment by mijail73** [comment]
thank you
