### ISSUE TITLE
How to set Interactive Python as /usr/bin/python3

### ISSUE THREAD

**Issue by xuehao** [jorgenschaefer/elpy#418]
Here is my elpy config:
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.4.0 (/usr/bin/python3)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.6.0
Jedi..............: 0.8.1-final0
Rope..............: 0.9.4-1 (0.10.2 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

**Comment by jorgenschaefer** [comment]
Any updates on this? Did this solve your problem?

**Comment by xuehao** [comment]
Yes, of course. Sorry to reply too late. Please close this issue. Thanks.

**Comment by jorgenschaefer** [comment]
Great to hear! Please do not hesitate to open a new issue if there are any further problems :-)
