### ISSUE TITLE
How To Make Better Use Of ELPY

### ISSUE THREAD

**Issue by xuehao** [jorgenschaefer/elpy#421]
Dear Jorgen,
I have used ELPY for a long time. But only use code snippet(yasnippet) and autocomplete(company) to edit Python code, and use flake8 to check syntax.
I can workon venv in Emacs, but I don't know how to test code within venv. Then, I just use C-c C-c or eshell to test code. 
I think I didn't make the best use of ELPY. But I don't know how better it can be. 
Can give a workflow or a usage manual for better Python development using ELPY?

Best Regards,
Mike

**Comment by jorgenschaefer** [comment]
I assume this question was answered. Please do not hesitate to open a new issue if you have any further questions or problems!

**Comment by ChillarAnand** [comment]
Hi @xuehao ,

i started writing some tips & it became too long, so i made it a blog post. 
check out if you are interested http://www.avilpage.com/2015/03/how-to-make-better-use-of-any-emacs.html

thanks for asking :)

**Comment by jorgenschaefer** [comment]
Nice blog post! Thank you for that.

**Comment by xuehao** [comment]
@ChillarAnand Glad to get your help. Thank you very much.
