### ISSUE TITLE
No syntax information from backend

### ISSUE THREAD

**Issue by sebhofer** [jorgenschaefer/elpy#423]
Hi!

I think elpy is great... if only it would work properly for me :-< Unfortunately I don't get any syntax information in the completion pop-up. This might be either due to misconfiguration of emacs or my python setup. How do I debug this?

TIA
Sebastian

**Comment by jorgenschaefer** [comment]
Sorry for the long delay in the response (especially after getting thanked for the initial fast response!), I was on vacation over the holidays and new year's.

When Elpy can get completions from a backend, it will add information such as "module", "function", "class" etc. to the completion popup. If those are missing, then Elpy did not get any completion information from the backend, and fell back to dabbrev as the source of completions – basically, symbols in other Python buffers with the same name.

A common problem for Elpy not getting correct completions from the backend is that the relevant module is not found in the Python path. To verify if the basic functionality works, try a buffer like this:

```Python
import json

json.
```

`M-TAB` at the end of `json.` should create a popup beginning with `decoder   module` and `dump   function`. If it does not, please post the configuration information from `M-x elpy-config`.

**Comment by sebhofer** [comment]
Hi! Now I'm sorry for the long wait. I got distracted from trying to fix my emacs python environment. Today I tried to work out if or what's going wrong but I'm still not sure if everything works as expected  So the status is the following: I type something like

    a = [1, 2, 3]

    a.

and hit `M-TAB`. This does result in a list of functions ("append",...), but I never get any additional explanation about what the function does. Is that supposed to be happening? Is there an unambiguous way to test if I get the correct information from jedi/rope?

My elpy-config looks good:

    Elpy Configuration

     Virtualenv........: canopy (/home/sebhofer/canopy) 
     RPC Python........: 2.7.6 (/home/sebhofer/canopy/bin/python)
     Interactive Python: ipython (/home/sebhofer/canopy/bin/ipython)
     Emacs.............: 25.0.50.2
     Elpy..............: 1.6.0
     Jedi..............: 0.8.1-final0
     Rope..............: 0.10.2
     Syntax checker....: flake8 (/home/sebhofer/canopy/bin/flake8)

Maybe I'm just expecting too much and everything is working correctly anyway. If this is the case, I'm very sorry for the noise!

**Comment by jorgenschaefer** [comment]
Elpy should display something like `function` next to the method name (if it does not, there's some problem with the backend). It does not create a separate popup with the docstring by default, if that is what you mean. You can display the docstring using `C-c C-d` or you can use [a separate module](https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-can-i-get-documentation-as-pop-ups-next-to-the-completion-pop-up) for this.

**Comment by birkenfeld** [comment]
Pressing `C-h` while the completion list is displayed should show the help in a different window.

**Comment by sebhofer** [comment]
Jorgen, yes I was expecting that. Thanks you cleared that up (and sorry I didn't look at the FAQ before)!

Also, thanks to Georg for the useful hint!

**Comment by jorgenschaefer** [comment]
You're not the first user to ask for such a popup, hence why I added it to the FAQ (more so I can point to it than for others to find it on their own, really) – I created #483 as a suggestion to enable that module by default.

I assume this problem is solved. Please do not hesitate to open a new issue if you have any more problems, and enjoy Elpy! :-)
