### ISSUE TITLE
rpc process not starting

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#429]
I have successfully installed elpy and this is my config

Elpy Configuration

Virtualenv........: pearl (/home/k3/.virtualenvs/pearl)
RPC Python........: 2.7.6 (/home/k3/.virtualenvs/pearl/bin/python)
Interactive Python: ipython (/home/k3/.virtualenvs/pearl/bin/ipython)
Emacs.............: 24.3.1
Elpy..............: 1.6.0
Jedi..............: 0.8.1-final0
Rope..............: 0.9.3 (0.10.2 available)
Syntax checker....: pyflakes (/home/k3/.virtualenvs/pearl/bin/pyflakes)

Features like `elpy-doc` are working fine. 

However `elpy-goto-definition` is not working. When i checked for rpc process, no rpc process is intialized. 

M-x elpy-rpc-restart is doing nothing when invoked. 

It is not throwing any errors when elpy is enabled.

**Comment by jorgenschaefer** [comment]
Thank you for the report, and sorry for not responding earlier, I was on vacation.

Did you solve this problem?
