### ISSUE TITLE
elpy-shell-send-region-or-buffer opens Python shell in current window when using python-mode.el

### ISSUE THREAD

**Issue by marwy** [jorgenschaefer/elpy#430]
I'm using [python-mode.el](https://launchpad.net/python-mode) and when I do C-c C-c on a Python buffer, elpy opens Python shell in current window, instead of using other window or creating a new one if there's only one. 

This behavior does not exist when using default Python mode, so I'm not sure who's at fault here: python-mode.el, elpy, maybe I misconfigured something?

**Comment by jorgenschaefer** [comment]
Thank you for the report, and sorry for the long delay in responding. I was on vacation.

Elpy does not support `python-mode.el`, I'm afraid. There are just too many differences with the default `python.el`. I also have no idea what `python-mode.el` does, really, to cause this.

**Comment by marwy** [comment]
Are there any plans for adding support for python-mode.el? I haven't yet really made up my mind about which mode should I use, but it'd be nice to know that I can switch them easily if I want to. I'm guessing I'm not the only one ;-).

**Comment by jorgenschaefer** [comment]
The differences between python.el and python-mode.el are quite substantial, and I have not found any reason to use python-mode.el these days (the new python.el shipped with Emacs 24 is much improved over the old one), so no, no such plans exist right now, I'm afraid. :-)

**Comment by jorgenschaefer** [comment]
I assume this issue is solved. Please do not hesitate to re-open this issue or file a new one if you have further problems, and enjoy Elpy!
