### ISSUE TITLE
Python3 Virtual Environment Support

### ISSUE THREAD

**Issue by arocks** [jorgenschaefer/elpy#431]
Hi, I use Arch Linux which has standardized on Python 3. Since python 3 has a different virtual environment system [pyvenv](https://docs.python.org/3.4/using/scripts.html#scripts-pyvenv) built-in; can you suggest how we can point elpy to use this environment?

Thanks!

**Comment by ChillarAnand** [comment]
elpy uses [pvenv.el](https://github.com/jorgenschaefer/pyvenv) to manage venvs. It has `pyvenv-activate` function to activate venv.

So, You can do 

    M-x pyvenv-activate RET /path/to/your/venv/ RET

to activate required env.

If you are using projectile, You can use [projectile-switch-project-hook](https://github.com/bbatsov/projectile/blob/d7d9dcd059c685a0691bf92b118891c7bd9c1dbd/projectile.el#L2213) to auto activate venv on switching project.

**Comment by arocks** [comment]
Yes, I did try `pyvenv-activate` and it returned a post activation error. It seems like mkvirtualenv wrapper is assumed to be installed.

For the record I solved the problem by doing a system wide install. But I would like to know if there is support for pyvenv.

**Comment by jorgenschaefer** [comment]
Thank you for the report and sorry for not responding earlier, I was on vacation.

This is indeed a bug – pyvenv should not fail if virtualenvwrapper is not installed.

**Comment by jorgenschaefer** [comment]
Closing this issue as it is a problem in pyvenv. See jorgenschaefer/pyvenv#24 for an issue to track this bug.
