### ISSUE TITLE
error installing from elpy package repository

### ISSUE THREAD

**Issue by nhoffman** [jorgenschaefer/elpy#438]
I'm experiencing errors trying to install elpy from the elpy package
archive hosted on github. The first time I try to install, the package
installation process terminates with this message:

```
Contacting host: jorgenschaefer.github.io:80
epg-start-verify: Writing to process: Bad file descriptor, epg
```

And then subsequent attempts result in this message:

```
Contacting host: jorgenschaefer.github.io:80
epg-start-verify: process epg no longer connected to pipe; closed it
```

I see similar errors using emacs 24.4.1 on both OS X and ubuntu 12.04.

Here's my package initialization code:

```
(when (>= emacs-major-version 24)
  (require 'package)
  (setq package-archives
        '(("ELPA" . "http://tromey.com/elpa/")
          ("gnu" . "http://elpa.gnu.org/packages/")
          ("melpa" . "http://melpa.org/packages/")
          ("melpa-stable" . "http://stable.melpa.org/packages/")
          ("marmalade" . "http://marmalade-repo.org/packages/")
          ("org" . "http://orgmode.org/elpa/")
          ("elpy" . "http://jorgenschaefer.github.io/packages/")
          ))

  ;; Check if we're on Emacs 24.4 or newer, if so, use the pinned package feature
  ;; note that elpy installation fails when pinned to elpy package
  (when (boundp 'package-pinned-packages)
    (setq package-pinned-packages
          '((elpy . "elpy")
            (org . "org")
            (magit . "melpa-stable")
            )))

  (package-initialize))
```

There is no error if I pin elpy to melpa-stable instead. Is there any
additional information that would be useful?

Thanks!
Noah

**Comment by jorgenschaefer** [comment]
Thank you for the report.

`epg` is Emacs' GnuPG interface. This error looks like there is a problem verifying the signature of the packages. I _suspect_ that there is a problem in epg unrelated to Elpy here. Could you try `M-x toggle-debug-on-error` and do this again? It should produce a backtrace showing more directly where the error happens.

To fix this, you should be able to set `package-check-signature` to `nil`.

**Comment by nhoffman** [comment]
Well, now I can't reproduce the error on either OS X or linux. Very strange - happened over and over yesterday (and, I should note, I got the same error trying to install highlight-indentation from the elpy package repository). Unless others chime in, I suspect that this should be closed. Thanks for the response (and for elpy)!

**Comment by jorgenschaefer** [comment]
Strange – maybe a temporary problem with gpg-agent or some gnome keyring? Glad it works now, though.

In any case, please do not hesitate to re-open this issue or open a new one if there are any further problems!
