### ISSUE TITLE
auto imports using rope?

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#440]
elpy has almost everything an IDE needs with the exception of auto import. 

While writing code, if cursor is at any package, there should be an option to import it automatically.

Also after writing the code, when factoring is done `C-c C-r`, it should import any missed imports.

**Comment by whirm** [comment]
There's an auto import branch already that uses importmagic, but it hasn't been merged yet.

**Comment by jorgenschaefer** [comment]
Thank you for the suggestion!

Doing this correctly is pretty tricky. Rope's auto import did not work as I expected when I tried it, and caused more problems than it solved, hence why it's not supported at the moment. As @whirm says, there's a branch to use the `importmagic` branch which I think will solve most of your problems, but upstream has not made `importmagic` available from PyPI yet, so I hesitate to merge the branch. Which is kind of annoying, Elpy 1.7 is soon to be released and I would really like to include that feature.

**Comment by whirm** [comment]
@jorgenschaefer I know it wouldn't be pretty, but what about having it as an elpy submodule in the meanwhile?

**Comment by jorgenschaefer** [comment]
@whirm, possible, but I'm not sure it's _that_ important a feature. Especially as I'd have to track bugs etc. Even if it does not make it in, Elpy 1.8 is only three months down the road after all. :-)

**Comment by whirm** [comment]
nice! :)

**Comment by ChillarAnand** [comment]
just pinging @birkenfeld so that he updates `importmagic` on PyPi!

**Comment by ChillarAnand** [comment]
Thank You @birkenfeld. 

@jorgenschaefer since `importmagic` is available on PyPi, You can merge `importmagic` branch.

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by jorgenschaefer** [comment]
@ChillarAnand, does the new importmagic code fulfill this feature request for you?

**Comment by ChillarAnand** [comment]
Love it :smile:
