### ISSUE TITLE
Two `super` snippets

### ISSUE THREAD

**Issue by bersace** [jorgenschaefer/elpy#445]
Hi,

Elpy is great. I hit something weird. There is two snippets for `super` : the one you provide with elpy that supports well super inside classmethods. Yasnippet ships a buggy one which hardcode `self` Is there a way to have elpy override it ?

Or maybe contribute to yasnippet itself ?

Best regards,
Étienne

PS: i checked epy, and found elpy better. Nice job !

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the praise! I am glad you like Elpy.

What is the value of `yas-snippet-dirs`? The Elpy snippet directory should appear _before_ the yasnippet one.

**Comment by bersace** [comment]
Sorry for the lag !

```lisp
("~/.emacs.d/snippets" yas-installed-snippets-dir "/home/bersace/.emacs.d/elpa/elpy-20141031.945/snippets/")
```

**Comment by jorgenschaefer** [comment]
Oh, indeed, elpy actually appends the directory. I'm not sure if that's good or bad, come to think of it.

You can use `(setq yas-snippet-dirs '("~/.emacs.d/snippets" "/home/bersace/.emacs.d/elpa/elpy-20141031.945/snippets/" yas-installed-snippets-dir))` in your .emacs after `(elpy-enable)`

**Comment by bersace** [comment]
Still having two. I think it's because their name is `super` and `super()`, isn't it ?

**Comment by jorgenschaefer** [comment]
> Still having two. I think it's because their name is super and super(), isn't it ?

Possibly? I don't use the official yasnippet repository, so I only have one.

**Comment by bersace** [comment]
Oh, maybe i could just disable it :)

**Comment by bersace** [comment]
How do you disable official yasnippet repository ?

**Comment by bersace** [comment]
Ok, did it with:

```lisp
(setq yas-snippet-dirs
      '(list "~/.emacs.d/snippets"
	     (concat (file-name-directory (locate-library "elpy"))
		     "snippets/")))
```
