### ISSUE TITLE
Wrapping code in %cpaste and --

### ISSUE THREAD

**Issue by statmobile** [jorgenschaefer/elpy#446]
When I start a debugger using ipdb.set_trace() I want to highlight and send code to the iPython shell.  Right now I can do it using the isend minor mode, but I need to put a %cpaste at the beginning and -- at the end.  I feel like this would be a great feature in elpy, because I believe this is how some of the other IDEs handle debugging.

Any ideas on how I could write a function to do this, and if there's any desire to add it to elpy as a debugging feature?

**Comment by jorgenschaefer** [comment]
Thank you for the idea!

There is currently no special support in Elpy for ipython beyond setting it up. I did not know about ipdb, for example, nor about those special sequences.

Emacs' python.el does not usually send code directly to the subprocess, but instead writes it to a file and uses `exec` to execute the file. This is necessary because interactive Python treats empty lines as terminators, which would break on actual Python code (e.g. a class definition would end after every method, which is wrong).

So I am unsure as to how the ipdb interaction works there, really. 

If you look at `elpy-shell-send-region-or-buffer` (the default binding for `C-c C-c`), you can see how it extracts the current region and then uses `python-shell-send-string` to send the actual string. Copying the code and adding some code before and after should be quite straightforward.

Instead of `python-shell-send-string`, your code would use `comint-send-string` to sidestep the file execution trick by python.el.

Does this help?

**Comment by statmobile** [comment]
Thanks jorgen, before I look into it, let me ask you this.  Are you opposed to including another project in elpy?  Specifically, i-send minor mode, I believe the license is compatible, and we can reach out to the author and see if he approves.

https://github.com/ffevotte/isend-mode.el

The reason I ask, is because it looks like they've done all of the hard work.  It will wrap the code in the %cpaste and --, as well as remove indentation (except for the necessary Python indentation) when sending code to the iPython shell.  I just figured out how to set it up, you just have to fire up the i-send minor mode associate it with the iPython shell, and highlight the code and a Ctrl-Return sends it all prepared.  

What do you think?

**Comment by jorgenschaefer** [comment]
Elpy could easily depend on isend-mode and enable it in all elpy buffers, that's not a problem. But I am not convinced the mode adds anything to Elpy. From the package description:

> isend-mode is an Emacs extension allowing interaction with code interpreters in ansi-term or term buffers.

I do not know how many people use `ansi-term` or `term` to run interactive interpreters. That strikes me as odd.

> Some language-specific modes (e.g. python.el) already provide similar features; isend-mode does the same in a language-agnostic way.

So they say python.el does similar things already.

From what I understand, python.el already can send code to both Python and IPython interactive processes. I understood from your report that you have issues sending code to ipdb specifically, and not ipython in general?

What, exactly, is your use case for isend-mode?

**Comment by statmobile** [comment]
I'm still trying to tweak my workflow to reflect how I used to use the Wingware IDE to debug my projects.  I just got it up and running (somewhat), and I'll put it together in a blog post and screen session if you're interested I can post it on here.

Maybe you won't like it, but most people are inserting ipdb.set_trace() in their code to debug, what I am doing is running the code in cpython, and embedding an ipython session with Ipython.embed() (note you can only do this in cpython not ipython) in my file in order to debug.  Sometimes I can just use elpy to send my code to the Python buffer using C-c C-c, but I often start getting IndentationError issues.  In order to work around this, I isend-mode has a ipython feature that will let me associate it with the Python buffer running ipython, and will wrap %cpaste and -- around it and remove indentation so that ipython can interpret the code by just highlighting it and using C-Return.

I feel like elpy lacks a little in interacting with an active Python session for debugging, but I may be missing something.

**Comment by jorgenschaefer** [comment]
> Sometimes I can just use elpy to send my code to the Python buffer using C-c C-c, but I often start getting IndentationError issues. 

Could you give an example of when this breaks? As I mentioned, python.el uses `exec` to execute regions sent to the inferior Python process, and Elpy already does remove indentation of sent code fragments, so this should not happen. This might be a bug in python.el or Elpy.

**Comment by statmobile** [comment]
Yeah, that's what's driving me crazy is that it's not consistent, I'll try to compose a file where I can reproduce it 100% of the time.

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by statmobile** [comment]
I think I may have finally nailed it down:

```python
from __future__ import print_function

# I'm using Python 3.4.2
# IPython 2.3.1

# If I run C-c C-c for the whole file these loops work fine
# If I highlight the whole loop and C-c C-c I get:
# TabError: inconsistent use of tabs and spaces in indentation
# This occurs for both cpython and ipython
for i in range(5):
    for j in range(5):
        def f():
            print('Produce Elpy TabError')
        f()
```

**Comment by statmobile** [comment]
Let me know if that has trouble for you as well, in the mean time I'll keep an eye open for if/when I get an IndentationErrror.  It usually shows up in the heat of a coding session, so I'll need to try to make it reproducible.

**Comment by jorgenschaefer** [comment]
Hm. I can highlight either for loop (i.e. even the indented one), hit `C-c C-c`, and get the correct output in the `*Python*` buffer. Using either CPython 3.4.0 or 2.7.3, and Elpy devel (which shouldn't change this from 1.6.0).

What version of Elpy are you using?

**Comment by statmobile** [comment]
I'm using 1.6.0 and I can still reproduce the bug.  Sorry, I thought I was helping enhance the project with features, but maybe I'm just finding a bug.  Here's a screencast of what happens for me:

http://showterm.io/50d37b652c034e4f30348

**Comment by jorgenschaefer** [comment]
Very strange. I just installed ipython locally and still can not reproduce this – it "just works" here. Any I don't think the development version of Elpy changed anything there.

Could you evaluate the following piece of code, reproduce the error, and paste the output from the `*Messages*` buffer here?

```Lisp
(defun elpy-shell-send-region-or-buffer (&optional arg)
  (interactive "P")
  ;; Ensure process exists                                                      
  (elpy-shell-get-or-create-process)
  (let ((if-main-regex "^if +__name__ +== +[\"']__main__[\"'] *:")
        (has-if-main nil))
    (if (use-region-p)
        (let ((region (elpy-shell--region-without-indentation
                       (region-beginning) (region-end))))
          (setq has-if-main (string-match if-main-regex region))
          (set-text-properties 0 (length region) nil region)
          (message "Region:\n```\n%S\n```" region)
          (python-shell-send-string region))
      (save-excursion
        (goto-char (point-min))
        (setq has-if-main (re-search-forward if-main-regex nil t)))
      (python-shell-send-buffer arg))
    (display-buffer (process-buffer (elpy-shell-get-or-create-process))
                    nil
                    'visible)
    (when has-if-main
      (message (concat "Removed if __main__ == '__main__' construct, "
                       "use a prefix argument to evaluate.")))))
```

**Comment by statmobile** [comment]
Okay, I opened emacs on my problem code, then opened your function into elpy-test.el and M-x eval-buffer on your code

;; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.

    Loading /opt/local/share/emacs/site-lisp/subdirs.el (source)...done
    Error: (void-function defstruct)
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/
    [yas] Discovered there was already *scratch* in fundamental-mode
    [yas] Discovered there was already  *code-conversion-work* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 0* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 1* in fundamental-mode
    [yas] Discovered there was already  *load* in fundamental-mode
    [yas] Discovered there was already *ESS* in fundamental-mode
    [yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode) (quote fundamental-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode/.yas-setup...done
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets
    [yas] Check your `yas-snippet-dirs': ~/.emacs.d/snippets is not a directory
    [yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
    For information about GNU Emacs and the GNU system, type C-h C-a.
    highlight-indentation with indent-width 4
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode/.yas-setup...done
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode/.yas-setup...done
    [yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode) (quote prog-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode/.yas-setup...done
    <<< Type SPC or RET to bury the buffer list >>>
    Mark set
    Making python-shell-interpreter local to *Python* while let-bound!
    Making python-shell-interpreter-args local to *Python* while let-bound!
    Sent python-shell-completion-setup-code
    Sent python-ffap-setup-code
    Sent python-eldoc-setup-code
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    You can run the command `elpy-shell-send-region-or-buffer' with C-c C-c
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    Mark set
    Sent python-shell-completion-setup-code
    Sent python-ffap-setup-code
    Sent python-eldoc-setup-code
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    You can run the command `elpy-shell-send-region-or-buffer' with C-c C-c
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    <<< Type SPC or RET to bury the buffer list >>>
    Loading /opt/local/share/emacs/site-lisp/subdirs.el (source)...done
    Error: (void-function defstruct)
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/
    [yas] Discovered there was already *scratch* in fundamental-mode
    [yas] Discovered there was already  *code-conversion-work* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 0* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 1* in fundamental-mode
    [yas] Discovered there was already  *load* in fundamental-mode
    [yas] Discovered there was already *ESS* in fundamental-mode
    [yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode) (quote fundamental-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode/.yas-setup...done
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets
    [yas] Check your `yas-snippet-dirs': ~/.emacs.d/snippets is not a directory
    [yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
    For information about GNU Emacs and the GNU system, type C-h C-a.
    highlight-indentation with indent-width 4
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode/.yas-setup...done
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode/.yas-setup...done
    [yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode) (quote prog-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode/.yas-setup...done
    <<< Type SPC or RET to bury the buffer list >>>
    Mark set
    Making python-shell-interpreter local to *Python* while let-bound!
    Making python-shell-interpreter-args local to *Python* while let-bound!
    Sent python-shell-completion-setup-code
    Sent python-ffap-setup-code
    Sent python-eldoc-setup-code
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    You can run the command `elpy-shell-send-region-or-buffer' with C-c C-c
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    Mark set
    Sent python-shell-completion-setup-code
    Sent python-ffap-setup-code
    Sent python-eldoc-setup-code
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    You can run the command `elpy-shell-send-region-or-buffer' with C-c C-c
    Region:
    ```
    "for i in range(5):
        for j in range(5):
    	def f():
    	    print('Produce Elpy TabError')
    	f()
    
    "
    ```
    <<< Type SPC or RET to bury the buffer list >>>

**Comment by statmobile** [comment]
I thought I'd show the results of sending the whole file as well:

    Loading /opt/local/share/emacs/site-lisp/subdirs.el (source)...done
    Error: (void-function defstruct)
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/
    [yas] Discovered there was already *scratch* in fundamental-mode
    [yas] Discovered there was already  *code-conversion-work* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 0* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 1* in fundamental-mode
    [yas] Discovered there was already  *load* in fundamental-mode
    [yas] Discovered there was already *ESS* in fundamental-mode
    [yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode) (quote fundamental-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode/.yas-setup...done
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets
    [yas] Check your `yas-snippet-dirs': ~/.emacs.d/snippets is not a directory
    [yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
    For information about GNU Emacs and the GNU system, type C-h C-a.
    highlight-indentation with indent-width 4
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode/.yas-setup...done
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode/.yas-setup...done
    [yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode) (quote prog-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode/.yas-setup...done
    Making python-shell-interpreter local to *Python* while let-bound!
    Making python-shell-interpreter-args local to *Python* while let-bound!
    Sent python-shell-completion-setup-code
    Sent python-ffap-setup-code
    Sent python-eldoc-setup-code
    Can't guess python-indent-offset, using defaults: 4
    Flymake unable to run without a buffer file name
    highlight-indentation with indent-width 4
    Sent: from __future__ import print_function...
    <<< Type SPC or RET to bury the buffer list >>>

**Comment by statmobile** [comment]
This is when I send the whole buffer:

    Loading /opt/local/share/emacs/site-lisp/subdirs.el (source)...done
    Error: (void-function defstruct)
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/
    [yas] Discovered there was already *scratch* in fundamental-mode
    [yas] Discovered there was already  *code-conversion-work* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 0* in fundamental-mode
    [yas] Discovered there was already  *Echo Area 1* in fundamental-mode
    [yas] Discovered there was already  *load* in fundamental-mode
    [yas] Discovered there was already *ESS* in fundamental-mode
    [yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode) (quote fundamental-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/fundamental-mode/.yas-setup...done
    [yas] Prepared just-in-time loading for /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets
    [yas] Check your `yas-snippet-dirs': ~/.emacs.d/snippets is not a directory
    [yas] Reloaded everything (snippets will load just-in-time)... (some errors, check *Messages*).
    For information about GNU Emacs and the GNU system, type C-h C-a.
    highlight-indentation with indent-width 4
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/elpy-20141031.945/snippets/python-mode/.yas-setup...done
    [yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode) (quote python-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/python-mode/.yas-setup...done
    [yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode) (quote prog-mode)))!
    [yas] Loading compiled snippets from /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode
    Loading /Users/blopes/.emacs.d/elpa/yasnippet-20141223.303/snippets/prog-mode/.yas-setup...done
    <<< Type SPC or RET to bury the buffer list >>> [2 times]
    Making python-shell-interpreter local to *Python* while let-bound!
    Making python-shell-interpreter-args local to *Python* while let-bound!
    Sent python-shell-completion-setup-code
    Sent python-ffap-setup-code
    Sent python-eldoc-setup-code
    Can't guess python-indent-offset, using defaults: 4
    Flymake unable to run without a buffer file name
    highlight-indentation with indent-width 4
    Sent: from __future__ import print_function...
    <<< Type SPC or RET to bury the buffer list >>>

**Comment by statmobile** [comment]
That `(void-function defstruct)` has been annoying me, because I've been using the MacPorts version on OS X.  I just downloaded Emacs for Mac OS X, and set it up.  It looks like I'm still having the same problem.  Let me know if you want me to repeat the Messages on this version of Emacs.

**Comment by jorgenschaefer** [comment]
Nope, that's plenty enough. This is the problem:

```
Region:

"for i in range(5):
    for j in range(5):
    def f():
        print('Produce Elpy TabError')
    f()

"
```

Somehow, indentation gets lost there.

Are you mixing (literal) tabs and spaces there for indentation?

**Comment by statmobile** [comment]
I thought I was forcing space tabs with `(setq indent-tabs-mode nil)` in my .emacs file, but I guess not.  I added a python-mode hook:

```
(add-hook 'python-mode-hook
      (lambda ()
        (setq indent-tabs-mode t)
        (setq tab-width 4)
        (setq python-indent 4)))
```
Opened a new file, and wrote the same double loop, and it does highlight and run with C-c C-c.  Thanks Jorgen, you can close this "bug" as user error.  It can't be said enough how fast you are to respond while maintaining this project.

**Comment by jorgenschaefer** [comment]
Setting `indent-tabs-mode` to `nil` globally really should do the trick.

Elpy probably should warn the user if there are tabs in the region to be sent. I created #457 to track that feature request.

Thank you for the report and the suggestion, and also the kind words – please do not hesitate to report any issues you find!
