### ISSUE TITLE
importmagic tests fail in Python 3.x

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#449]
The Emacs Lisp tests of the importmagic feature fail with Python 3.x:

https://travis-ci.org/jorgenschaefer/elpy/builds/48023365

@birkenfeld, I haven't looked at this yet, is this an easy fix?

**Comment by birkenfeld** [comment]
I'll have a look.

**Comment by birkenfeld** [comment]
Pretty easy :)

**Comment by jorgenschaefer** [comment]
Fixed in 24e98b4
