### ISSUE TITLE
Unable to install the latest elpy

### ISSUE THREAD

**Issue by ribonoous** [jorgenschaefer/elpy#453]
I have the following in my Emacs init file:

```
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
		                 ("marmalade" . "http://marmalade-repo.org/packages/")))
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(add-to-list 'package-archives '("elpy" . "http://jorgenschaefer.github.io/packages/") t)
```
What's strange is that, when I do  `M-x package-refresh-contents` and then `M-x list-packages` I only see the following options:

![screen shot 2015-01-25 at 11 09 05 am](https://cloud.githubusercontent.com/assets/1993919/5892143/e5252a54-a482-11e4-85ae-a6ae9d004c70.png)

that is, none of them seem to come from `http://jorgenschaefer.github.io/packages/`, (and I presume that they are older versions) Those are the only three options that show up when I search for `elpy` in the list of packages returned by `M-x list-packages`.

How can I install elpy from `master`?

**Comment by jorgenschaefer** [comment]
The line that says "available  elpy" is from github.io.

I do not know what you mean with "install from master", exactly?

**Comment by ribonoous** [comment]
Thanks @jorgenschaefer That explains it :). I think I was confused because `mermelade` and `elpy` both have said version `1.6.0 ` for some time (so I thought it was a stable release), even though the GitHub repository keeps getting commits over time.

**Comment by jorgenschaefer** [comment]
Yes, 1.6.0 is the current stable release. You can not install the current development release of Elpy via `package-install`; you need to set up git, and if it breaks, you get to keep all the pieces. :-)

Elpy 1.7.0 is scheduled to be released beginning of February, though.

**Comment by ameliovr** [comment]
That's great. Thanks @jorgenschaefer  One quick question. Even **after** installing the version that says:

`elpy 1.6.0 available elpy`

I got asked to install:

`elpy 1.6.0 available 20141031.945`

from `melpa` which is presumably an older version. This happens anytime I do `M-x list-packages RET u` (that is, checking for automatic updates). Why is that?  Can I prioritize the `elpy` source over the `melpa` one, or perhaps remove the `melpa` version altogether?

**Comment by jorgenschaefer** [comment]
The MELPA version should be the same. You get this behavior because MELPA overrides version numbers with time stamps.

You can use `package-pinned-packages` (and in Emacs 25, `package-archive-priorities`) to change which archives various packages are installed from.

Please be aware that using MELPA means you get development versions of all the packages Elpy depends on, with the associated problems of larger number of bugs.

**Comment by ameliovr** [comment]
Very helpful. Thanks @jorgenschaefer!
