### ISSUE TITLE
autoimport - elpy backend is dying unexpectedly 

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#454]
I have been playing with autoimport & whenever 

1. there is a syntax error in any of *.py file it encounters, 
2. if i try to autoimport a function which is present in some other file in current directory, 

backend process is dying.

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

```
Error Message

'NoneType' object has no attribute 'startswith'

Configuration

Virtualenv........: elpy (/home/anand/.virtualenvs/elpy)
RPC Python........: 2.7.6 (/home/anand/.virtualenvs/elpy/bin/python)
Interactive Python: python (/home/anand/.virtualenvs/elpy/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.6.1
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Importmagic.......: 0.1.0 (0.1.1 available)
Syntax checker....: flake8 (/home/anand/.virtualenvs/elpy/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/anand/.emacs.d/personal/packages/elpy/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/anand/.emacs.d/personal/packages/elpy/elpy/server.py", line 219, in rpc_add_import
    return self.import_magic.add_import(source, statement)
  File "/home/anand/.emacs.d/personal/packages/elpy/elpy/impmagic.py", line 53, in add_import
    if statement.startswith('import '):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by birkenfeld** [comment]
How exactly are you invoking the importmagic functionality?

**Comment by ChillarAnand** [comment]
Using `C-c C-m` (`C-m` is binded to `RET`)

**Comment by birkenfeld** [comment]
OK, that should ask you for a symbol to import, then query for one of several possible import statements with that symbol. Do you get both queries?

**Comment by ChillarAnand** [comment]
It is asking for symbol at point to import, when i hit enter backend process is dying.

**Comment by ChillarAnand** [comment]
Sometimes when other *.py files has some lint errors, it is throwing errors like this

```
Failed to parse /home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/GoogleScraper/scraping.py: invalid syntax (scraping.py, line 80)
Failed to parse /home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/GoogleScraper/core.py: invalid syntax (core.py, line 122)
{"id": 26, "error": {"message": "symbol index is not yet ready", "code": 200}}
```

**Comment by jorgenschaefer** [comment]
Just to be sure, @birkenfeld, does this fix the spurious "Failed to parse" output, too?

**Comment by birkenfeld** [comment]
As far as I can see, that's "print" output generated by importmagic. I guess the backend is not supposed to write to stdout?

**Comment by jorgenschaefer** [comment]
Elpy uses stdin/stdout for the RPC protocol, so yes, the backend should not do that.

(In general, libraries should not just print to stdout, but use the `logging` library)

**Comment by birkenfeld** [comment]
> Elpy uses stdin/stdout for the RPC protocol, so yes, the backend should not do that.

Makes sense. I'll fix importmagic and release a 0.1.2 today.

> (In general, libraries should not just print to stdout, but use the logging library)

Of course. I guess that is just a leftover of the early state of development.

**Comment by jorgenschaefer** [comment]
Thank you, @birkenfeld ! I really appreciate all the work you put into this.

And @ChillarAnand, thank you as well for the report. With the new importmagic, both parts of your issue should be fixed – I hope you continue to enjoy Elpy :-)

**Comment by birkenfeld** [comment]
0.1.2 uploaded to PyPI.

**Comment by ChillarAnand** [comment]
@jorgenschaefer  @birkenfeld   Thank You. :cake:
