### ISSUE TITLE
autoimport - caching & ranking imports 

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#465]
Original report [importmagic/issues/12](https://github.com/alecthomas/importmagic/issues/12)

Django & lot of 3rd packages for django models, views e.t.c with same names & most of the times django imports will be imported when compared to others.

Can we cache the imported imports & update their ranks on a per project basis?

**Comment by jorgenschaefer** [comment]
Thank you for the report!

Might be time to add some general caching for Elpy, so importmagic can also cache its database.

@birkenfeld, can importmagic easily provide an efficient "update the data" function? Something that would annotate parsed information with source files and their ctimes/mtimes, and update the info if files changed/were removed/added?

**Comment by birkenfeld** [comment]
Currently no, but I'm planning to add caching and easy update.

**Comment by jorgenschaefer** [comment]
Very nice!

**Comment by gopar** [comment]
Closing since related to importmagic and that is no longer in elpy
