### ISSUE TITLE
from PySide.QtGui import used; unable to detect undefined names

### ISSUE THREAD

**Issue by zarzen** [jorgenschaefer/elpy#466]
`'from PySide.QtCore import *' used; unable to detect undefined names`
I got this error when I open a python file, which I wrote some pyside code in.

Is that means pyflakes don't know where is pyside packages?

**Comment by jorgenschaefer** [comment]
This means that your code checking tool (most likely flake8) can not tell you whether identifiers in the current file are undefined or not, because you imported "from library import *", so there could be all sorts of identifiers in the current file.

If you do not want to see this error, add the following to your `setup.cfg` or to `~/.config/flake8`:

```
[flake8]
ignore = F403
```

See https://github.com/jorgenschaefer/elpy/wiki/Configuration#configuring-the-syntax-checker-flake8 for more information.

**Comment by zarzen** [comment]
hm, I create `~/.config/flake8` and add these code 
```
[flake8]
ignore = F403
```
and when I reopen the file, it doesn't work.
then I add `max-line-length = 99` as test command, it also can not work right.

**Comment by jorgenschaefer** [comment]
Sorry, I think I am not following correctly, and might be guessing a bit too much as to what you are seeing or requiring. Where are you seeing the error? Could you please provide full details for the problem description:

- What _exactly_ did you do?
- What _exactly_ did happen?
- What _exactly_ did you expect to happen?

Thank you!

**Comment by zarzen** [comment]
Oh.
First, I want to use `emacs + elpy` write pyside program. 
So I have to use modules from PySide package, such like PySide.QtCore and PySide.QtGui.

Then I got come error message like this:
![screen shot 2015-01-30 at 23 50 15](https://cloud.githubusercontent.com/assets/1150493/5978446/cf9265e2-a8da-11e4-9937-8ae1509994ee.png)

[Goal]
1. I want to eliminate such error message
2. I hope elpy can do auto complete with PySide package. (maybe I have to open another issue)

About second goal:
I hope when I write a class inherit QDialog, elpy can figure out all methods QDialog has.

**Comment by jorgenschaefer** [comment]
Thank you. Let's focus on the 1st goal – I think #459 should cover the 2nd goal.

What is the value of `python-check-command` for you?

Does `C-c C-v` show this error as well?

**Comment by zarzen** [comment]
yeah.
this is `C-c C-v` shows:
```
-*- mode: compilation; default-directory: "~/Dev/Python/firstQt/" -*-
Compilation started at Sat Jan 31 00:09:17

/usr/local/bin/pyflakes /Users/zarzen/Dev/Python/firstQt/tutorial.py
/Users/zarzen/Dev/Python/firstQt/tutorial.py:4: 'from PySide.QtCore import *' used; unable to detect undefined names
/Users/zarzen/Dev/Python/firstQt/tutorial.py:5: 'from PySide.QtGui import *' used; unable to detect undefined names
/Users/zarzen/Dev/Python/firstQt/tutorial.py:6: 'time' imported but unused

Compilation exited abnormally with code 1 at Sat Jan 31 00:09:17
```

And I don't know how can I know the value of `python-check-command`? 
I am just using `C-h v` to search that value.
Is this right?:
```
python-check-command is a variable defined in `python.el'.
Its value is "/usr/local/bin/pyflakes"
Original value was "pyflakes"

  This variable may be risky if used as a file-local variable.

Documentation:
Command used to check a Python file.

You can customize this variable.
```

**Comment by jorgenschaefer** [comment]
Ok, you indeed use pyflakes – sorry about that.

I do not know pyflakes. Elpy recommends flake8 for error checks. Is there a particular reason you are using pyflakes instead of flake8?

**Comment by zarzen** [comment]
No, actually I don't know both of them.
I use `/usr/local/bin/pyflakes` is due to that `python-check-command` value is `pyflakes` at first time.
But at that time, I got an error that "file not exists", then I change that value to `/usr/local/bin/pyflakes` in order to help emacs find that `bin`.

So I should change to flake8?

**Comment by jorgenschaefer** [comment]
Yes. If you follow the instructions in `M-x elpy-config`, elpy will ask you to install flake8 if it can't find it. Elpy should also set that variable automatically to flake8 if it can find it. If it isn't, set it to flake8 yourself.

**Comment by zarzen** [comment]
Thanks!
errors disappeared !
