### ISSUE TITLE
elpy-importmagic-fixup should ask the user for the right choice when there's more than one option for an import.

### ISSUE THREAD

**Issue by whirm** [jorgenschaefer/elpy#469]
For instance: if I'm using get() from ```requests``` and call ```elpy-importmagick-fixup``` the import line added will be: ```from args import get``` instead of ```from requests import get```

**Comment by birkenfeld** [comment]
Agreed.

**Comment by whirm** [comment]
that was quick! :D

**Comment by birkenfeld** [comment]
We aim to please ;)

**Comment by jorgenschaefer** [comment]
@birkenfeld is doing all the work, I'm just here taking credit and stuff.
