### ISSUE TITLE
a chat room for elpy users?

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#470]
can we have start irc channel #elpy or start a chat room at [gitter](https://gitter.im/) for general discussion about elpy?

**Comment by jorgenschaefer** [comment]
Good idea, thank you. I am not sure how much traffic there will be, but I asked the freenode staff to register the channel `#elpy` on irc.freenode.net.

You can also ask on the main `#emacs` channel – I am not always around, but others there might be able to help with some problems, too.

**Comment by ChillarAnand** [comment]
Could you register at [botobot](https://botbot.me/request/) also?

`NEWS.rst` is [not fetched by melpa] (https://github.com/milkypostman/melpa/blob/f907b8aa1088621c9458df25bfe20169b00be5d5/recipes/elpy), so `elpy-news` is not working?

**Comment by jorgenschaefer** [comment]
I have not heard back from freenode about the channel, so won't do much there yet.

Also, ah, yeah, MELPA … could you create a separate issue for that? (MELPA is not the official distribution channel, but it's used often enough that it's worth supporting it.)

**Comment by ChillarAnand** [comment]
looks like channel is created & few people are hanging around?

**Comment by jorgenschaefer** [comment]
Yes, but it's registered to some Polish election campaign from 2004, so we have no control whatsoever over the channel. :-)

**Comment by ChillarAnand** [comment]
if possible, please add  `esay-fix` tags for new issues from here on. if some newbies want to contribute here, they  can take a bite :)

**Comment by jorgenschaefer** [comment]
I like that idea in principle, but I'm not sure if I can in any sensible way decide if something is an "easy fix" … Usually, by the time I know something is an easy fix I have already fixed it.

**Comment by ChillarAnand** [comment]
thank you :)
