### ISSUE TITLE
not auto-complete when import xxx or from xxx 

### ISSUE THREAD

**Issue by chenxs110** [jorgenschaefer/elpy#475]
when i  tap import key word and then tap what module i want to import,but no company menu popup

**Comment by chenxs110** [comment]
note  i  pip install django, python org module can auto-complete but django module not auto-complete ,whether change backend can fix it ?

**Comment by jorgenschaefer** [comment]
I am sorry, I am not sure I understood that problem description.

Are you saying that "import django" does not provide completion, but for example "import json" does? If I understood this wrong, could you please rephrase? What exactly are you entering, what exactly are you seeing, and what exactly did you expect to see?

If I got it right:
- Does it work after `M-x elpy-rpc-restart`?
- Does it work if you set the `DJANGO_SETTINGS_MODULE` environment variable and then do `M-x elpy-rpc-restart`?

**Comment by chenxs110** [comment]
thank you, when i execute elpy-rpc-restart,import auto complete success

**Comment by jorgenschaefer** [comment]
Glad this was fixed, I'll close this issue now. Please do not hesitate to file a new issue if you have any further problems, and enjoy Elpy. :-)
