### ISSUE TITLE
Not compatible with yasnippet 0.9

### ISSUE THREAD

**Issue by spacecowboy** [jorgenschaefer/elpy#477]
Running git clone of yasnippet due to running into issue #79. 

Yasnippet version:
```
git describe --tags
0.9.0-beta-21-g197ef7f
```

I am unable to activate elpy due to:
```
Warning (emacs): Unable to activate package `elpy'.
Required package `yasnippet-0.8.0' is unavailable
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report.

The error you describe sounds like you are installing yasnippet without `package.el`, but then try to use `package.el` to install Elpy – the latter will fail, as `package.el` is not aware of yasnippet.

You can use the official Elpy repository, which comes with a compatible version of yasnippet, or you can install both yasnippet and elpy from git, but I am afraid you can not (easily) mix that.

It might be an idea for `package.el` to support local overrides like this, but for that you'd have to file a feature request against Emacs core.

Does this help?

**Comment by spacecowboy** [comment]
Thanks. Cloning elpy directly solved the problem. Still, original problem is that it won't work with yasnippet installed from *melpa*. Here's the log just a reference.

With Yasnippet `20141223.303` (from melpa):

```
Debugger entered--Lisp error: (wrong-type-argument consp nil)
  elpy-modules-remove-modeline-lighter(yas-minor-mode)
  elpy-module-yasnippet(global-init)
  apply(elpy-module-yasnippet global-init nil)
  elpy-modules-run(global-init)
  elpy-modules-global-init()
  elpy-enable()
  (progn (elpy-enable))
```

**Comment by jorgenschaefer** [comment]
I did not know about that "original problem", the issue you linked to is about a different problem. Thanks for reporting this. I am using yasnippet 0.9.0.1 from MELPA Stable and things work there. I am afraid that MELPA deliberately prefers unstable code to stay most recent, hence why Elpy does not support MELPA – if you use it, you're on your own. You can use either Elpy's own repository, or at least MELPA stable.

**Comment by jorgenschaefer** [comment]
The current master branch should fix that problem, by the way. Again, thank you for the report!
