### ISSUE TITLE
Failing test: elpy-flymake--standard-value-should-get-standard-value in Emacs 25

### ISSUE THREAD

**Issue by birkenfeld** [jorgenschaefer/elpy#486]
Since Emacs revision bd7a1e156, `python.el` uses `(executable-find "pyflakes")` for determining `python-check-command`, so that the default value now includes the full path to pyflakes (for me it happens to be in `~/.local/bin`).

`(should (equal (elpy-flymake--standard-value 'python-check-command) "pyflakes"))` now fails.

**Comment by jorgenschaefer** [comment]
Fixed in 24f3d5b
