### ISSUE TITLE
update melpa fetcher for elpy

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#487]
`elpy-news` is not working as `NEWS.rst` is [not fetched by melpa](https://github.com/milkypostman/melpa/blob/f907b8aa1088621c9458df25bfe20169b00be5d5/recipes/elpy)

**Comment by jorgenschaefer** [comment]
Thank you!

MELPA is not the official distribution channel, so this is not strictly speaking a bug, but it is used by enough people to make it worthwhile to support, so I'll update the recipe at some point if no one gets there before me :-)

**Comment by ChillarAnand** [comment]
submitted PR milkypostman/melpa/pull/2490

**Comment by jorgenschaefer** [comment]
Thank you very much!
