### ISSUE TITLE
Error on trying to get documentation for completions

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/elpy#490]
Pressing Ctrl+D twice when completions are showing returns the following message:

```
Company: Back-end elpy-company-backend error "Wrong type argument: char-or-string-p, 1423627497.5392025" with args (doc-buffer capitalize)
```

Here's the backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p 1423627396.9222503)
  company-doc-buffer(1423627396.9222503)
  elpy-company-backend(doc-buffer "decode")
  apply(elpy-company-backend (doc-buffer "decode"))
  #[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(doc-buffer "decode") company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"]()
  funcall(#[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(doc-buffer "decode") company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"])
  company-call-backend-raw(doc-buffer "decode")
  apply(company-call-backend-raw (doc-buffer "decode"))
  company--force-sync(company-call-backend-raw (doc-buffer "decode") elpy-company-backend)
  company-call-backend(doc-buffer "decode")
  company-show-doc-buffer()
  call-interactively(company-show-doc-buffer nil nil)
  command-execute(company-show-doc-buffer)
```

Am I doing anything wrong? Documentation lookup using C-c C-d works, but documentation does not appear next to completions when typing a function (should it?)

**Comment by jorgenschaefer** [comment]
Thank you for the report!
You are not doing anything wrong there, apparently there's a bug in the backend which returns a floating point number instead of a string as a docstring (?).

Can you post the output of `M-x elpy-config`?

What backend are you using? Also, what function/method does this happen on?

> documentation does not appear next to completions when typing a function (should it?)

Not by default. [There's a package](https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-can-i-get-documentation-as-pop-ups-next-to-the-completion-pop-up) that does that which might be included in Elpy in the future, though.

**Comment by cpitclaudel** [comment]
Upgrading to rope 0.10.2 following your suggestion in the other thread seems to have fixed it! Here's my config for reference though:

Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 24.4.1
Elpy..............: 1.7.0
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Importmagic.......: 0.1.2
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

That's strange. I'll close this and reopen it if I manage to reproduce it on the new rope!

Side note: it would be nice to have a command to know which backend is currently in use. If I set rope as my preferred backend, then uninstall rope, elpy doesn't seem to complain (or did I miss something?)

**Comment by jorgenschaefer** [comment]
Elpy keeps an RPC server running in the background. If you uninstall rope, that is still running with rope loaded. You can force a restart of all RPC servers using `M-x elpy-rpc-restart`. Elpy won't complain, though, but fall back to Jedi automatically. :-)

**Comment by cpitclaudel** [comment]
That's what I meant; if I uninstall and restart, it falls back (which is neat), but a small message letting me know so would be nice :)

**Comment by jorgenschaefer** [comment]
That's tricky – a user who installs jedi but not rope would want to use jedi without any kind of message. If you set `elpy-rpc-backend` to `"rope"`, you will get a message about falling back to Jedi, though!

**Comment by cpitclaudel** [comment]
Ah, I just missed that message. Thanks!
