### ISSUE TITLE
pip3 install flake8

### ISSUE THREAD

**Issue by bendyarm** [jorgenschaefer/elpy#494]
Hi,
I am a new elpy user, trying to use it with python3.  I'm using OSX 10.9.5 and Emacs 24.3.1.
In the elpy-config buffer, I was able to change both the interactive and rpc python to python3.
I was also able to get jedi and importmagic , although the [run] button did the wrong thing.
(The [run] button ran pip install to my python 2.7.)  I used pip3 in a separate shell and then elpy-config saw them.
When I did the same thing for flake8,  it seemed to install fine:
```
pip3 install --user flake8
...
... pyflakes>=0.8.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from flake8)
...
... Successfully installed flake8
```
But then the \*Elpy Config\* buffer shows:
```
Syntax checker....: Not found (pyflakes)
```
Any ideas for what to look for, for why elpy can't find pyflakes?

**Comment by xuehao** [comment]
@bendyarm Add following config in your ·.emacs· or ·init.el· file
·(setq elpy-rpc-python-command "python3")·
·(elpy-use-cpython "/usr/bin/python3")·

**Comment by bendyarm** [comment]
@xuehao Thanks for trying to help but I already used m-x elpy-config
to set up both rpc python and interactive python to use python3.
The result was that it already added this to my .emacs file:
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(elpy-interactive-python-command "python3")
 '(elpy-rpc-python-command "python3"))
```
And m-x elpy-config can find both instances of python3 
in /usr/local/bin/python3, that much is clear.

The weird thing is that elpy-config has no problem
finding jedi but it can't find flake8, even though
both are in ~/Library/Python/3.4/lib/python/site-packages

I tried putting this in my .emacs file:
`(setq python-check-command "flake8")`
because the value was "pyflakes" previously.
Still didn't work.  I also turned off virtual environments
from the elpy-config setting.  Still didn't work.

I see that elpy.el calls `(executable-find "flake8")` .
I don't seem to have an executable flake8.
Maybe I had the venv set up wrong when I first
did pip3 install flake8?  Anyway, pip uninstalling 
and reinstalling does not seem to create an executable
flake8, so I don't know how that gets installed.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

When installing Python packages like `flake8` with `pip install --user`, their executables are added to the directory `~/.local/bin/`. You can either `(setq python-check-command (expand-file-name "~/.local/bin/flake8"))` or add `~/.local/bin/` to your `PATH`.

Let me know if this solves your problem, and enjoy Elpy!

**Comment by bendyarm** [comment]
After creating a python3 virtual environment using the `pyvenv` program,
and using the `[run]` buttons to install jedi, importmagic, and flake8
directly into the venv, elpy-config seems to be happy.  
Maybe this is the typical use case for python3?

Also, it looks like it is **not** a good idea to do
`(elpy-use-cpython "/usr/local/bin/python3")`
because that will override the python in the venv.
Is that a correct conclusion?

**Comment by jorgenschaefer** [comment]
> Maybe this is the typical use case for python3?

Not just for python3 – using virtualenvs for development is best practice for Python in general :-)

> Is that a correct conclusion?

Yes. Virtualenvs give you an encapsulated environment with a separate Python instance and added libraries, and `python` should point to the right one in each of them. You can use `M-x pyvenv-activate` to switch virtualenvs, or `M-x pyvenv-workon` if you use `virtualenvwrapper`.

**Comment by bendyarm** [comment]
@jorgenschaefer Thanks for the reply!  I just saw it now.  That makes sense.
I did not have a `~/.local/` directory so so the install silently failed to create
an executable, most likely.  (The reason I suspect that is that at the time 
I did a 'find' for the executable flake8 in the likely
directories and didn't find it; and if there was a warning at pip install time
it was not very obvious.)

**Comment by jorgenschaefer** [comment]
As far as I know, pip should create the directory – it's some sort of standard used by more and more software as of late.

I believe your problem is solved, so I will close this issue. Please do not hesitate to open further issues if you have any more problems, and enjoy Elpy!

**Comment by tfabbri** [comment]
I attach this [link](http://stackoverflow.com/questions/7143077/how-can-i-install-packages-in-my-home-folder-with-pip) from a stackoverflow discussion explaining where `~/.local/` is located for the  MacOS system when installing using `--user` option.
