### ISSUE TITLE
Powerline prompt with (elpy-use-ipython)

### ISSUE THREAD

**Issue by aiguofer** [jorgenschaefer/elpy#495]
I like using the powerline prompt for IPython, so I set up my IPython config with:
```
c.InteractiveShellApp.extensions = [
    'powerline.bindings.ipython.post_0_11'
]
```
However, this causes elpy to freeze my emacs whenever I load a Python file for the first time.

If I first load up elpy and then add the above config, I can start the ipython shell just fine (although the powerline prompt doesn't look as expected).

Is there a way to get the powerline prompt for IPython inside of emacs?

**Comment by jorgenschaefer** [comment]
I am afraid I do not know what powerline for ipython is (I do not use ipython myself), but if it does something fancy with the terminal, it is likely you can't use it in Emacs – the `M-x run-python` shell Emacs provides is a "dumb terminal" and can only read linewise output from the subprocess, so anything more advanced will fail. I'm not sure why it is freezing, I don't think it should.

Sadly, this is nothing Elpy controls. The `M-x run-python` interface is completely provided by Emacs' built-in `python-mode`. If you feel this should be supported in some form, maybe try using `M-x report-emacs-bug`?

**Comment by aiguofer** [comment]
Ahhh thanks.

Yeah, the powerline prompt uses some special characters (from patched fonts) to create a neat looking prompt, which can also show you additional info (like which dir you're in, etc).

Here's an example of what it looks like https://eightnoteight.wordpress.com/2014/10/22/finally-using-powerline-in-ipython-in-its-full-power/.

I'll try filing this against Emacs instead!

**Comment by jorgenschaefer** [comment]
Emacs' `inferior-python-mode` (which is what runs in `M-x run-python` buffers) uses regular expressions to detect a prompt. It might be that setting something useful for the prompt pattern would already work – you can look at the source code of `elpy-use-ipython` (the Emacs 24.3 check) to see an example for setting up the various variables.
