### ISSUE TITLE
possible bug or at least suggestion on tabs

### ISSUE THREAD

**Issue by bendyarm** [jorgenschaefer/elpy#499]
Hi, I think I ran into a bug with the standard configuration.
When I did c-c c-c on a region containing a def
in a python mode buffer, I got this:
```
>>> __pyfile = open('''/var/folders/22/t51qsvrj6pz5c0kyztgbkxb40000gn/T/py13528n5S
...
TabError: inconsistent use of tabs and spaces in indentation
```
even though there were no tabs in my source buffer
and `indent-tabs-mode` was nil.
And, I had nothing concerning tab-related settings
in my `.emacs` file.

When I opened that temp file in a buffer, it had tabs,
replacing places where my source code had 8 spaces.
I was able to work around the problem by putting
```
(setq-default indent-tabs-mode nil)
```
in my `.emacs` file, but it seems like a bug to me
that the tabs would be introduced.  Maybe the
code that sends the text to a temp file can be
more explicit about turning off replacement of spaces by tabs?
Or, maybe something could be added to the setup
instructions about turning off `indent-tabs-mode `
globally.
Thanks!

**Comment by jorgenschaefer** [comment]
Interesting find, thank you for the report!
Emacs' `python-mode` does the handling of the temp file, I can imagine it forgetting to copy that setting to the temp buffer. A quick glance at `python-shell--save-temp-file` seems to confirm that, but I have not fully investigated. I'll play around with this and probably apply a bugfix upstream.

**Comment by jorgenschaefer** [comment]
Hm. I can not actually reproduce this.

Which version of Emacs is this?
Can you provide a step-by-step guide on how to get this behavior in an `emacs -Q`?

**Comment by Lompik** [comment]
I remark the same issue. The issue arises in the `elpy-shell--region-without-indentation` function when it calls `indent-rigidly`. It replaces the 8 spaces indent by tabs in the following case :

Here's a minimal example 
Input files `test.py` :

	f = open('./tmp.csv', 'rt')
	try:
		reader = csv.reader(f)
		head = reader.__next__()
		for row in reader:
			table.append(row)
	finally:
		f.close()


and for `tmp.csv` (irrelevant):

    f1,f2,f3
    g1,g2,g3

To reproduce: select the whole test.py region and call `C-c C-c`. Python 3 will throw the error: 

	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/tmp/test.py", line 6
		table.append(row)
						^
	TabError: inconsistent use of tabs and spaces in indentation

Indeed the line 6 starts with a tab.

**Comment by jorgenschaefer** [comment]
Very nice bug hunting there, thank you! What's the value of `indent-tabs-mode` for you?

**Comment by Lompik** [comment]
`nil` as it fixes the issue :)

    indent-tabs-mode is a variable defined in `C source code'.
    Its value is nil
    Original value was t

It's actually buffer local. Maybe that's a lead for a fix ?

**Comment by jorgenschaefer** [comment]
Yeah, Elpy should set this to nil locally to avoid this. Thanks again!

**Comment by cnsgsz** [comment]
I seem to run into a similar issue even I have the above fix.

with test1.py as:
```
def test1():
    print("a")
```
highlighting the two lines and c-c c-c works.

but with test2.py as:
```
def test2():
    if True:
        print("a")
```

I got error similar to those in this thread:
> Python 3.3.5 |Anaconda 2.3.0 (64-bit)| (default, Jun  4 2015, 15:22:11) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/.../test2.py", line 3
>     print("a")
>              ^
> TabError: inconsistent use of tabs and spaces in indentation

indent-tab-mode is nil in test2.py buffer, but t in the \*Python\* buffer.

> test2.py buffer:
> indent-tabs-mode is a variable defined in `C source code'.
> Its value is nil
> Original value was t
> Local in buffer test.py; global value is t
> 
> *Python* buffer:
> indent-tabs-mode is a variable defined in `C source code'.
> Its value is t


`(setq-default indent-tabs-mode nil)`
fixed the problem just as suggested earlier in this thread. 

I checked the elpy code under emacs.d and it has the above commit that closed this issue.

should the \*Python\* buffer also have indent-tabs-mode as nil?
