### ISSUE TITLE
invalid token in docstring.

### ISSUE THREAD

**Issue by bersace** [jorgenschaefer/elpy#501]
Hi,

I'm hitting some bug that's looks relative to docstring. eply-rpc backend fails to starts with :

```
rror initializing Elpy

There was an error when trying to start the backend. Elpy can not work until
this problem is solved. The following lines were received from Python, and
might help identifying the problem.

('invalid token', 'ERRORTOKEN', u"'\n")
('invalid token', 'ERRORTOKEN', u'\'\'\'\n        sel\n        pass\n\n    def lol(self):\n        var = """notrst"""\n        var\n\n')
{"result": [], "id": 6}
('invalid token', 'ERRORTOKEN', u"'\n")
('invalid token', 'ERRORTOKEN', u'\'\'\'\n        self\n        pass\n\n    def lol(self):\n        var = """notrst"""\n        var\n\n')
{"result": [], "id": 7}
{"result": null, "id": 8}
('invalid token', 'ERRORTOKEN', u"'\n")
('invalid token', 'ERRORTOKEN', u'\'\'\'\n        self.\n        pass\n\n    def lol(self):\n        var = """notrst"""\n        var\n\n')
{"result": [], "id": 9}
{"result": null, "id": 10}
{"result": null, "id": 11}

```

Here is the python file :

```python
# -*- coding: utf-8 -*-

u'''
docstring
'''


def method():
    u"""
    Dôcstring
    """

    import ipdb; ipdb.set_trace()  # noqa
    pass


class Toto(object):
    """
    DocString

    :returns: toto
    """

    def toto(self):
        '''loilolil'''
        pass

    def lol(self):
        var = """notrst"""
        var
```

Note : i'm using mmm :x

```lisp
(require 'python)
(require 'mmm-mode)

(defun rst-python-statement-is-docstring (begin)
  "Return true if beginning of statiment is :begin"
  (save-excursion
    (save-match-data
      (python-nav-beginning-of-statement)
      (looking-at-p begin))))

(defun rst-python-front-verify ()
  (rst-python-statement-is-docstring (match-string 0)))

(add-to-list 'mmm-save-local-variables 'adaptive-fill-regexp)
(add-to-list 'mmm-save-local-variables 'fill-paragraph-function)

(mmm-add-classes
 '((rst-python-docstrings
    :submode rst-mode
    :face mmm-comment-submode-face
    :front "u?\\(\"\"\"\\|\'\'\'\\)"
    :front-verify rst-python-front-verify
    :back "~1"
    :end-not-begin t
    :save-matches 1
    :insert ((?d embdocstring nil @ "u\"\"\"" @ _ @ "\"\"\"" @))
    :delimiter-mode nil)))

;;;(assq-delete-all 'rst-python-docstrings mmm-classes-alist)

(mmm-add-mode-ext-class 'python-mode nil 'rst-python-docstrings)
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! What do I have to do to reproduce the bug? (I'm not seeing you mention an actual bug, so I guess I'm missing something obvious?)

**Comment by bersace** [comment]
Sorry !! I update the ticket :/

**Comment by jorgenschaefer** [comment]
Thanks. That looks bad.

@birkenfeld, does this "ERRORTOKEN" thing look like something importmagic would emit?

**Comment by birkenfeld** [comment]
I checked; it shouldn't emit messages to stdout/err anymore.

**Comment by jorgenschaefer** [comment]
@birkenfeld, thanks – but the type of message looks like importmagic? Maybe an old version.

@bersace, could you post the header from `M-x elpy-config`, in particular the importmagic version?

**Comment by bersace** [comment]
Yep, i have installed importmagic recently.

```
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.8 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.7.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/usr/local/bin/flake8)
```

**Comment by jorgenschaefer** [comment]
That should be the most recent version – I'm confused as to what is emitting `('invalid token', 'ERRORTOKEN', u"'\n")` … :-(

Do you have any particular unusual packages installed that might cause this?

**Comment by bersace** [comment]
The situation is a bit complicated. The project is in venv in a docker container (wheezy). I run emacs outside in the host. The code is mounted in the container. I install jedi and elpy deps as --user or system. Depending.

How can i trace the code that produce the invalid token ?

**Comment by jorgenschaefer** [comment]
I … actually have no idea. You can use `strace` on the RPC process and see what kind of messages are sent to cause the problem.

Try the new Elpy 1.7.1, which contains a workaround for this problem, and let me know if that helps?

**Comment by bersace** [comment]
It works !! :)

**Comment by jorgenschaefer** [comment]
Nice! Glad to hear that :-)

**Comment by bersace** [comment]
Can you upload elpy in melpa ?

**Comment by jorgenschaefer** [comment]
No, I can't.

MELPA pulls from the Elpy git repository. It does so at a random time outside of my control.

Use the Elpy ELPA. That's the officially supported way of installing Elpy.

**Comment by bersace** [comment]
I use it, but melpa is "higher" than elpy. 2015 > 1.7 :/

**Comment by jorgenschaefer** [comment]
Yes, MELPA overrides version numbers when it creates packages. This is a huge problem because now you have an Elpy package that is a higher version number than the official one, and you have no clue whatsoever what official version you have (`M-x elpy-version` will tell you). If I had not fought about it, you would also have an unstable version of Elpy that could randomly break because you are using MELPA (you are happy using unstable, randomly breaking versions of other packages I hope?).

That MELPA does not educate its users on all the drawbacks it poses is one of my biggest problems with the repository.

Do not use MELPA unless you have a very good reason to use it. Use the official Elpy repository, or MELPA Stable, which does not have the problems of the main MELPA repository.

**Comment by bersace** [comment]
Ok, i tested melpa stable, but where do yop find highlight-indentation 0.5 ?

**Comment by bersace** [comment]
Ok sorry, i needed to refresh package list :/

**Comment by jorgenschaefer** [comment]
I assume this problem is solved. Please do not hesitate to open a new issue if you have any further problems, and enjoy Elpy :-)
