### ISSUE TITLE
Request: Make highlight-indentation optional

### ISSUE THREAD

**Issue by spacecowboy** [jorgenschaefer/elpy#503]
Currently disabling it via a hook:

```elisp
(add-hook 'python-mode-hook (highlight-indentation-mode 0))
```

but why require it in the first place?

**Comment by jorgenschaefer** [comment]
Because I find it useful for Python code. :-)

You can disable it by customizing `elpy-modules` and removing `elpy-module-highlight-indentation`.

**Comment by spacecowboy** [comment]
Oh. Feel free to merge all my issues into "Insert disclaimer for noobs"...

**Comment by jorgenschaefer** [comment]
Where would you have found such a disclaimer? (A "if you dislike defaults look here for ways to customize it" one, that is :-))

**Comment by spacecowboy** [comment]
http://elpy.readthedocs.org/en/latest/concepts.html#modules

Ironically, I did read that section but did not know that highlight-indentation (and other packages) was considered a "module". Hard wired into looking "dependency" or "package".

**Comment by birkenfeld** [comment]
Well, highlight-indentation is both a package and a module in elpy :)

**Comment by spacecowboy** [comment]
Well sure, but what constitutes a "module" is not really defined anywhere as far as I can see.

highlight-indentation is also out of date btw :)

**Comment by jorgenschaefer** [comment]
"Out of date" in what way?

**Comment by spacecowboy** [comment]
As in not the newest version. Noticed that the version at https://github.com/antonj/Highlight-Indentation-for-Emacs
allows one to define colors for the current line block and the rest, separately. Version in elpy has only one face option.

**Comment by spacecowboy** [comment]
Just realized this version might be a fork... My bad..

**Comment by jorgenschaefer** [comment]
The Elpy repo now has highlight-indentation 0.6 – thank you!

**Comment by spacecowboy** [comment]
:+1:

**Comment by sjatkins** [comment]
<peeve>IMHO tool making developers should be very careful to separate their personal preferences for things like this from what the tool does about such matters by default.  Whether I want this highlight on not is orthogonal to wanting elpy functionality.  There is no logical connection between the two. </peeve>

**Comment by jorgenschaefer** [comment]
> IMHO tool making developers should

That's great. I disagree. I hope you have a good time. :-)
