### ISSUE TITLE
Too many backends running in long emacs session

### ISSUE THREAD

**Issue by birkenfeld** [jorgenschaefer/elpy#505]
When I open modules from many projects in my session, elpy starts backend processes for each, but they are never cleaned up.

Just now i had 4G of memory tied up in about 25 elpy backend processes :)

I would propose killing all but the last 5 or so RPC processes when creating a new one. They're usually cheap to restart when needed.

**Comment by jorgenschaefer** [comment]
Good idea, actually. Thanks!
