### ISSUE TITLE
elpy-test will try to run an inner method as a test if the point is in it.

### ISSUE THREAD

**Issue by whirm** [jorgenschaefer/elpy#510]
Let's say I have this code:

```python
def test_foo():
    def do_bar():
        pass
    check_stuff(do_bar)
```

If the point is in ```do_bar()```, ```elpy-test``` will try to run that as the test instead of ```test_foo()```.

Maybe elpy could try to go up until it finds a method that starts with test_?

**Comment by jorgenschaefer** [comment]
Good idea.

I think there's never a reason to pass the inner method to a test runner …
