### ISSUE TITLE
Error using Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [jorgenschaefer/elpy#511]
hi
your package can't be install using only Melpa stable : 

```bash
Dependency elpy failed to install: Package `highlight-indentation-0.5.0' is unavailable
```

I creates an issue [1] for the *highlight-indentation* package.

[1] : https://github.com/antonj/Highlight-Indentation-for-Emacs/issues/26

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. The officially supported way of installing Elpy is by using the Elpy ELPA:

```Lisp
(require 'package)
(add-to-list 'package-archives
             '("elpy" . "http://jorgenschaefer.github.io/packages/"))
```

Let me know if this solves your problem!

**Comment by jorgenschaefer** [comment]
I assume this problem is solved. Please do not hesitate to open a new issue if you have any further problems, and enjoy Elpy :-)
