### ISSUE TITLE
importmagic mangles imports

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#512]
Just saw this, not sure how to reproduce:

```
import cPickle as pickle

[...]

sys.getsizeof(o, 0)
```

`C-c C-m`
Object to import: `sys.getsizeof` 
New import statement: `import sys`

```
import cPickleas pickle
import sys
```

```
Importmagic.......: 0.1.3
```

**Comment by birkenfeld** [comment]
Interesting :(

**Comment by jorgenschaefer** [comment]
I suspect it's something rather simple, like forgetting a space in some string formatting code, but I'm at work and can't debug it any closer right now. Leaving it here as a note for later. :-)

**Comment by whirm** [comment]
The same just happened to me, I used importmagic and got the first ```import X as Z mangled``` to ```import timeas timemod```
the rest are just fine.

**Comment by alecthomas** [comment]
This has been [fixed](https://github.com/alecthomas/importmagic/pull/16) in importmagic thanks to @whirm.

**Comment by jorgenschaefer** [comment]
Excellent, thank you!
