### ISSUE TITLE
Warn in elpy-use-ipython if ipython is not installed

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#515]
i installed elpy on new machine & when i open any *.py file it & it couldn't open the file.

Message:

    Entering debugger...
    Error in post-command-hook (mode-local-post-major-mode-change): (wrong-type-argument arrayp nil)

Here is the full backtrace

    Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
      replace-regexp-in-string("[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
      shell-quote-argument(nil)
      python-shell-calculate-command()
      run-python-internal()
      python-shell-internal-get-or-create-process()
      python-shell-internal-send-string("import sys;print ('\\n'.join(sys.path))")
      semantic-python-get-system-include-path()
      (progn (semantic-python-get-system-include-path))
      (if (and (featurep (quote python)) (not noninteractive)) (progn (semantic-python-get-system-include-path)))
      (when (and (featurep (quote python)) (not noninteractive)) (semantic-python-get-system-include-path))
      eval((when (and (featurep (quote python)) (not noninteractive)) (semantic-python-get-system-include-path)))
      custom-initialize-reset(semantic-python-dependency-system-include-path (when (and (featurep (quote python)) (not noninteractive)) (semantic-python-get-system-include-path)))
      custom-declare-variable(semantic-python-dependency-system-include-path (when (and (featurep (quote python)) (not noninteractive)) (semantic-python-get-system-include-path)) "The system include path used by Python language." :group python :group semantic :type (repeat (directory :tag "Directory")) :set #[(sym val) "\303	\"\210	\304\305\nBC\306\307#\210\310\311\307\"\210)\312\313!\205 \310\313\307\"\207" [sym val tmp0 set-default mode-local-bind semantic-dependency-system-include-path (mode-variable-flag t) python-mode mode-local-map-mode-buffers #[nil "\302\301!\210\211\207" [tmp0 semantic-dependency-system-include-path make-local-variable] 2] fboundp semantic-decoration-unparsed-include-do-reset] 4])
      byte-code("\306\300\307\310\311\312\311\313\314\315\316\317&\210\320\321	BC\322\323#\210\324\325\323\"\210)\326\321\323\327!\330\n\204D\211\204D \205C\331
    \"\n\203n\f\204n\n\332N\203]\331
    \n\332N\"\211\204D\n\211\333N\206h\n\334N)\211\204H\f,\335\336#\210\326\321\323\300#\207" [semantic-python-dependency-system-include-path tmp0 mode symbol bind name custom-declare-variable (when (and (featurep (quote python)) (not noninteractive)) (semantic-python-get-system-include-path)) "The system include path used by Python language." :group python semantic :type (repeat (directory :tag "Directory")) :set #[(sym val) "\303	\"\210	\304\305\nBC\306\307#\210\310\311\307\"\210)\312\313!\205 \310\313\307\"\207" [sym val tmp0 set-default mode-local-bind semantic-dependency-system-include-path (mode-variable-flag t) python-mode mode-local-map-mode-buffers #[nil "\302\301!\210\211\207" [tmp0 semantic-dependency-system-include-path make-local-variable] 2] fboundp semantic-decoration-unparsed-include-do-reset] 4] mode-local-bind semantic-dependency-system-include-path (mode-variable-flag t) python-mode mode-local-map-mode-buffers #[nil "\302\301!\210\211\207" [tmp0 semantic-dependency-system-include-path make-local-variable] 2] put symbol-name nil intern-soft mode-local-symbol-table mode-local-parent derived-mode-parent variable-documentation "System path to search for include files." mode-local-active-mode major-mode] 12)
      wisent-python-default-setup()
      run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
      apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
      run-mode-hooks(python-mode-hook)
      python-mode()
      set-auto-mode-0(python-mode nil)
      set-auto-mode()
      normal-mode(t)
      after-find-file(nil t)
      find-file-noselect-1(#<buffer models.py> "~/projects/python/django/junction/junction/base/models.py" nil nil "~/projects/python/django/junction/junction/base/models.py" (17827588 2050))
      find-file-noselect("/home/anand/projects/python/django/junction/junction/base/models.py" nil nil nil)
      find-file("/home/anand/projects/python/django/junction/junction/base/models.py")
      find-file-at-point("/home/anand/projects/python/django/junction/junction/base/models.py")
      helm-find-file-or-marked("/home/anand/projects/python/django/junction/junction/base/models.py")
      apply(helm-find-file-or-marked "/home/anand/projects/python/django/junction/junction/base/models.py")
      helm-funcall-with-source(((name . "Projectile files") (init #[0 "\301\302\303\300!\203
    \300 \202\300\"\207" [#[nil "\3001\301 0\207\210\302\207" [(error) projectile-current-project-files nil] 1] helm-init-candidates-in-buffer global functionp] 4]) (candidates . helm-candidates-in-buffer) (keymap keymap (right . helm-next-source) (left . helm-previous-source) (127 . #[0 "\306\307\310\311\312\305!\313\"\314$\216\315\302!\210\316\304!\317\211\211\301=\203'\315\302!\210\320\202]\321\303\"\211\262\203:\315A!\210\320\202]\312!\262\322\300\"\262\323!\203S\315!\210\202\\\324\325\"\244\317\266\204\205e\202)\207" [(keymap (right . helm-execute-persistent-action) (left . helm-find-files-up-one-level) (127 . #3) (8 keymap (2 . helm-send-bug-report-from-helm)) (12 . helm-find-files-up-one-level) (67108910 . helm-find-files-up-one-level) (C-backspace . helm-ff-run-toggle-auto-update) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (3 keymap (64 . helm-ff-run-insert-org-link) (114 . helm-ff-run-find-file-as-root) (47 . helm-ff-run-find-sh-command) (112 . helm-ff-run-print-file) (1 . helm-ff-run-gnus-attach-files) (127 . helm-ff-run-toggle-auto-update) (63 . helm-ff-help) (104 . helm-ff-file-name-history) (61 . helm-ff-run-ediff-file) (88 . helm-ff-run-open-file-with-default-tool) (24 . helm-ff-run-open-file-externally) (15 . helm-ff-run-switch-other-frame) (111 . helm-ff-run-switch-other-window) (105 . helm-ff-run-complete-fn-at-point) (100 . helm-ff-persistent-delete)) (27 keymap (114 . helm-ff-rotate-right-persistent) (108 . helm-ff-rotate-left-persistent) (105 . helm-ff-properties-persistent) (112 . helm-ff-run-switch-to-history) (61 . helm-ff-run-ediff-merge-file) (37 . helm-ff-run-query-replace-on-marked) (33 . helm-ff-run-eshell-command-on-file) (101 . helm-ff-run-switch-to-eshell) (75 . helm-ff-run-kill-buffer-persistent) (68 . helm-ff-run-delete-file) (72 . helm-ff-run-hardlink-file) (83 . helm-ff-run-symlink-file) (76 . helm-ff-run-load-file) (66 . helm-ff-run-byte-compile-file) (67 . helm-ff-run-copy-file) (82 . helm-ff-run-rename-file) (46 . helm-ff-run-etags) (103 keymap ... ... ...)) (19 . helm-ff-run-grep) (24 keymap (4 . helm-ff-run-browse-project) (6 . helm-ff-run-locate)) (29 . helm-ff-run-toggle-basename) keymap (94 . helm-swoop-caret-match) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap ...)) (help keymap (109 . helm-help)) (67108927 keymap (109 . helm-help)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (4 . helm-debug-output)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (21 . helm-force-update) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (4 . helm-delete-current-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (23 . helm-yank-text-at-point) (24 keymap (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) ...) 127 helm-ff-delete-char-backward nil nil helm-ff-delete-char-backward--exit-fn make-byte-code 0 "\300\205\300 \207" vconcat vector [] 1 call-interactively read-key nil t assoc lookup-key commandp mapcar identity last-command-event unread-command-events] 7 nil nil]) (8 keymap (2 . helm-send-bug-report-from-helm)) (12 . helm-find-files-up-one-level) (67108910 . helm-find-files-up-one-level) (C-backspace . helm-ff-run-toggle-auto-update) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (3 keymap (97 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-dired-files-add-action] 2 nil nil]) (102 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-dired-files-new-action] 2 nil nil]) (64 . helm-ff-run-insert-org-link) (114 . helm-ff-run-find-file-as-root) (47 . helm-ff-run-find-sh-command) (112 . helm-ff-run-print-file) (1 . helm-ff-run-gnus-attach-files) (127 . helm-ff-run-toggle-auto-update) (63 . helm-ff-help) (104 . helm-ff-file-name-history) (61 . helm-ff-run-ediff-file) (88 . helm-ff-run-open-file-with-default-tool) (24 . helm-ff-run-open-file-externally) (15 . helm-ff-run-switch-other-frame) (111 . helm-ff-run-switch-other-window) (105 . helm-ff-run-complete-fn-at-point) (100 . helm-ff-persistent-delete)) (27 keymap (114 . helm-ff-rotate-right-persistent) (108 . helm-ff-rotate-left-persistent) (105 . helm-ff-properties-persistent) (112 . helm-ff-run-switch-to-history) (61 . helm-ff-run-ediff-merge-file) (37 . helm-ff-run-query-replace-on-marked) (33 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-find-files-eshell-command-on-file-action] 2 nil nil]) (101 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-switch-to-eshell] 2 nil nil]) (75 . helm-ff-run-kill-buffer-persistent) (68 . helm-ff-run-delete-file) (72 . helm-ff-run-hardlink-file) (83 . helm-ff-run-symlink-file) (76 . helm-ff-run-load-file) (66 . helm-ff-run-byte-compile-file) (67 . helm-ff-run-copy-file) (82 . helm-ff-run-rename-file) (46 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-ff-etags-select-action] 2 nil nil]) (103 keymap (122 . helm-ff-run-zgrep) (112 . helm-ff-run-pdfgrep) (115 . helm-ff-run-grep))) (19 . helm-ff-run-grep) (24 keymap (4 . helm-ff-run-browse-project) (6 . helm-ff-run-locate)) (29 . helm-ff-run-toggle-basename) keymap (94 . helm-swoop-caret-match) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (67108927 keymap (109 . helm-help)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (4 . helm-debug-output)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (21 . helm-force-update) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (4 . helm-delete-current-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (23 . helm-yank-text-at-point) (24 keymap (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) ...) (action ("Find File" . helm-find-file-or-marked) ("Find file in Dired" . helm-point-file-in-dired) ("View file" . view-file) ("Checksum File" . helm-ff-checksum) ("Query replace fnames on marked" . helm-ff-query-replace-on-marked) ("Query replace contents on marked" . helm-ff-query-replace) ("Query replace regexp contents on marked" . helm-ff-query-replace-regexp) ("Serial rename files" . helm-ff-serial-rename) ("Serial rename by symlinking files" . helm-ff-serial-rename-by-symlink) ("Serial rename by copying files" . helm-ff-serial-rename-by-copying) ("Open file with default tool" . helm-open-file-with-default-tool) ("Find file in hex dump" . hexl-find-file) ("Insert as org link `C-c @'" . helm-files-insert-as-org-link) ("Open file externally `C-c C-x, C-u to choose'" . helm-open-file-externally) ("Grep File(s) `C-s, C-u Recurse'" . helm-find-files-grep) ("Zgrep File(s) `M-g z, C-u Recurse'" . helm-ff-zgrep) ("Switch to Eshell `M-e'" . helm-projectile-switch-to-eshell) ("Etags `M-., C-u reload tag file'" . helm-projectile-ff-etags-select-action) ("Eshell command on file(s) `M-!, C-u take all marked as arguments.'" . helm-projectile-find-files-eshell-command-on-file-action) ("Find file as root `C-c r'" . helm-find-file-as-root) ("Ediff File `C-='" . helm-find-files-ediff-files) ("Ediff Merge File `C-c ='" . helm-find-files-ediff-merge-files) ("Delete File(s) `M-D'" . helm-delete-marked-files) ("Copy file(s) `M-C, C-u to follow'" . helm-find-files-copy) ("Rename file(s) `M-R, C-u to follow'" . helm-find-files-rename) ("Symlink files(s) `M-S, C-u to follow'" . helm-find-files-symlink) ("Relsymlink file(s) `C-u to follow'" . helm-find-files-relsymlink) ("Hardlink file(s) `M-H, C-u to follow'" . helm-find-files-hardlink) ("Find file other window `C-c o'" . find-file-other-window) ("Switch to history `M-p'" . helm-find-files-switch-to-hist) ("Find file other frame `C-c C-o'" . find-file-other-frame) ("Print File `C-c p, C-u to refresh'" . helm-ff-print) ("Locate `C-x C-f, C-u to specify locate db'" . helm-ff-locate) ("Create Dired buffer from files `C-c f'" . helm-projectile-dired-files-new-action) ("Add files to Dired buffer `C-c a'" . helm-projectile-dired-files-add-action)) (help-message . helm-ff-help-message) (filtered-candidate-transformer helm-fuzzy-matching-default-sort-fn helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (coerce . helm-projectile-coerce-file) (mode-line . "\\<helm-find-files-map>\\[helm-ff-help]:Help \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct") (header-line . "C-j: Find File (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--match-plugin helm-compile-source--persistent-help) (matchplugin) (data . #[nil "\3001\301 0\207\210\302\207" [(error) projectile-current-project-files nil] 1]) (get-line . buffer-substring-no-properties) (search helm-mp-exact-search helm-mp-3-search helm-candidates-in-buffer-search-from-start helm-fuzzy-search)) helm-find-file-or-marked "/home/anand/projects/python/django/junction/junction/base/models.py")
      helm-execute-selection-action-1()
      helm-execute-selection-action()
      helm-internal((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[junction] Find file: " nil nil "*helm projectile*" nil nil nil)
      apply(helm-internal ((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[junction] Find file: " nil nil "*helm projectile*" nil nil nil))
      helm((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[junction] Find file: " nil nil "*helm projectile*" nil nil nil)
      apply(helm ((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[junction] Find file: " nil nil "*helm projectile*" nil nil nil))
      helm(:sources (helm-source-projectile-dired-files-list helm-source-projectile-files-list) :buffer "*helm projectile*" :prompt "[junction] Find file: ")
      helm-projectile-find-file()
      projectile-switch-project-by-name("~/projects/python/django/junction/")
      (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))
      (lambda (project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project)))("~/projects/python/django/junction/")
      apply((lambda (project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))) "~/projects/python/django/junction/")
      helm-funcall-with-source(((name . "Projectile projects") (init #[0 "\301\302\303\300!\203
    \300 \202\300\"\207" [#[nil "\301 \203
    \302\303 !\304 B\207\207" [projectile-known-projects projectile-project-p abbreviate-file-name projectile-project-root projectile-relevant-known-projects] 2] helm-init-candidates-in-buffer global functionp] 4]) (candidates . helm-candidates-in-buffer) (keymap keymap (19 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-find-files-grep] 2 nil nil]) (27 keymap (68 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-remove-known-project] 2 nil nil]) (99 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-compile-project] 2 nil nil]) (101 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-switch-to-eshell] 2 nil nil]) (103 . #[nil "\300\301!\207" [helm-quit-and-execute-action helm-projectile-vc] 2 nil nil])) (4 . #[nil "\300\301!\207" [helm-quit-and-execute-action dired] 2 nil nil]) keymap (94 . helm-swoop-caret-match) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (67108927 keymap (109 . helm-help)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (4 . helm-debug-output)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (21 . helm-force-update) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (4 . helm-delete-current-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (23 . helm-yank-text-at-point) (24 keymap (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . helm-recenter-top-bottom-other-window) (15 . helm-next-source) (10 . helm-execute-persistent-action) (26 . helm-execute-persistent-action) (9 . helm-select-action) (13 . helm-maybe-exit-minibuffer) (left . helm-previous-source) (right . helm-next-source) (7 . helm-keyboard-quit) ...) (action ("Switch to project" lambda (project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))) ("Open Dired in project's directory `C-d'" . dired) ("Open project root in vc-dir or magit `M-g'" . helm-projectile-vc) ("Switch to Eshell `M-e'" . helm-projectile-switch-to-eshell) ("Grep in projects `C-s'.  With C-u, recurse" . helm-find-files-grep) ("Compile project `M-c'. With C-u, new compile command" . helm-projectile-compile-project) ("Remove project(s) `M-D'" . helm-projectile-remove-known-project)) (filtered-candidate-transformer helm-fuzzy-matching-default-sort-fn helm-fuzzy-highlight-matches) (volatile) (match identity) (fuzzy-match) (mode-line . "\\<helm-find-files-map>\\[helm-ff-help]:Help \\<helm-map>\\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct") (header-line . "C-j: Switch to project (keeping session)") (dont-plug helm-compile-source--candidates-in-buffer helm-compile-source--match-plugin helm-compile-source--persistent-help) (matchplugin) (data . #[nil "\301 \203
    \302\303 !\304 B\207\207" [projectile-known-projects projectile-project-p abbreviate-file-name projectile-project-root projectile-relevant-known-projects] 2]) (get-line . buffer-substring-no-properties) (search helm-mp-exact-search helm-mp-3-search helm-candidates-in-buffer-search-from-start helm-fuzzy-search)) (lambda (project) (let ((projectile-completion-system (quote helm))) (projectile-switch-project-by-name project))) "~/projects/python/django/junction/")
      helm-execute-selection-action-1()
      helm-execute-selection-action()
      helm-internal(helm-source-projectile-projects nil "[~] Switch to project: " nil nil "*helm projectile*" nil nil nil)
      apply(helm-internal (helm-source-projectile-projects nil "[~] Switch to project: " nil nil "*helm projectile*" nil nil nil))
      helm(helm-source-projectile-projects nil "[~] Switch to project: " nil nil "*helm projectile*" nil nil nil)
      apply(helm (helm-source-projectile-projects nil "[~] Switch to project: " nil nil "*helm projectile*" nil nil nil))
      helm(:sources helm-source-projectile-projects :buffer "*helm projectile*" :prompt "[~] Switch to project: ")
      helm-projectile-switch-project(nil)
      funcall-interactively(helm-projectile-switch-project nil)
      #<subr call-interactively>(helm-projectile-switch-project nil nil)
      ad-Advice-call-interactively(#<subr call-interactively> helm-projectile-switch-project nil nil)
      apply(ad-Advice-call-interactively #<subr call-interactively> (helm-projectile-switch-project nil nil))
      call-interactively(helm-projectile-switch-project nil nil)
      command-execute(helm-projectile-switch-project)

**Comment by jorgenschaefer** [comment]
The error is thrown by python.el's `python-shell-calculate-command` – what's the value of `python-shell-interpreter`, and does that exist in your `PATH`?

**Comment by ChillarAnand** [comment]
its values is `ipython`, i have not installed that & it was causing error. after installing everything is fine.

is it possible to show a warning message if user chooses to use `ipython (elpy-use-ipython)` & if it hasn't installed?

**Comment by jorgenschaefer** [comment]
Good idea.

Or, more generally, provide a better error message for the case of `python-shell-interpreter` not being found, regardless of its value!
