### ISSUE TITLE
elpy and cygwin

### ISSUE THREAD

**Issue by MichaelLiuzzi** [jorgenschaefer/elpy#518]
Hello Jorgen,

I use elpy on my OS X machine and it works flawlessly. However at work I use a windows machine and cygwin. I can't seem to get them to play nice together. 

Output
C:\Python34\python.exe: Error while finding spec for 'elpy.__main__' (<class 'I\
mportError'>: No module named 'elpy')^M

However when I run a python shell and append the directory to my sys.path and import elpy everything works fine. 

Not sure what's going on....?

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report.

What is the value of `elpy-rpc-pythonpath`?

**Comment by MichaelLiuzzi** [comment]
Thanks for the quick response!

 "/home/mliuzzi/.emacs.d/elpa/elpy-1.7.1/"

Though I also set it to the absolute path at another point: C:/cygwin64/home/mliuzzi/.emacs.d/elpa/elpy-1.7.1/

**Comment by jorgenschaefer** [comment]
Elpy adds this to `PYTHONPATH` – if you do that manually, add that path to `PYTHONPATH` and start `python.exe`, can you `import elpy`? (I am afraid I have not much clue about Windows and have no way to test this.)

**Comment by MichaelLiuzzi** [comment]
Yes. If I start a python shell and then append that path to sys.path I can import elpy without any problem. Similarly, if I set PYTHONPATH in Cygwin then I can import elpy.

**Comment by jorgenschaefer** [comment]
Huh. Elpy isn't doing much of anything but to run `python -m elpy.__main__` with `PYTHONPATH` set to that path. It's weird that it would get that error if that works outside of Emacs.

Any idea what might be causing this behavior in Windows?

**Comment by MichaelLiuzzi** [comment]
I have no clue haha. I'm as perplexed as you. My thinking was that there was some related problem triggering the error. But I don't know emacs lisp so I wouldn't even know where to begin.

**Comment by nandryshak** [comment]
@MichaelLiuzzi How are you using Emacs? Are you using it from Cygwin, or a Windows-native build?

**Comment by MichaelLiuzzi** [comment]
Cygwin. I saw your issue up above, @nandryshak . Is it still applicable if I'm using Cygwin 64?

**Comment by jorgenschaefer** [comment]
Half a year later, I'm afraid I'm still unsure what the problem might be. Lacking updates or ideas, I'll close this as unreproducible. Sorry. If you have further problems, please do not hesitate to file another report!
