### ISSUE TITLE
unnecessary flake8 warnings 

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#521]
Here is my elpy config

    Virtualenv........: py3 (/home/k3/.virtualenvs/py3)
    RPC Python........: 3.4.0 (/home/k3/.virtualenvs/py3/bin/python)
    Interactive Python: ipython (/home/k3/.virtualenvs/py3/bin/ipython)
    Emacs.............: 24.4.1
    Elpy..............: 1.7.1
    Jedi..............: 0.8.1-final0
    Rope..............: 0.9.4-1
    Importmagic.......: 0.1.3
    Syntax checker....: pyflakes (/home/k3/.virtualenvs/py3/bin/pyflakes)

When i open a file with this line

    from unittest.mock import Mock, MagicMock

flake8 throws warning message

    No name 'mock' in module 'unittest' [E0611]

But when i send that file to shell, it executes correctly. I am not sure if the error is due to elpy/flake8.

**Comment by jorgenschaefer** [comment]
Thanks for the report :-)

> `Syntax checker....: pyflakes (/home/k3/.virtualenvs/py3/bin/pyflakes)`

You're using pyflakes, not flake8! Not that it matters for this, though – this would be a bug in pyflakes/flake8. You can verify this by running pyflakes/flake8 manually on the respective source file. It should emit the warning.

In the meantime, you can configure flake8 at least (probably pyflakes, too) to ignore the error by adding `ignore = E611` to the `[flake8]` section of `setup.cfg` or `~/.config/flake8`.
