### ISSUE TITLE
elpy-rpc-python-command gets set wrong in Cygwin when using emacs-w32 (fix inside)

### ISSUE THREAD

**Issue by nandryshak** [jorgenschaefer/elpy#523]
`elpy-rpc-python-command` is defined like this:

    (defcustom elpy-rpc-python-command (if (eq window-system 'w32)
                                           "pythonw"
                                           "python")...)

However, using the `emacs-w32` package provided by Cygwin causes this variable
to get set incorrectly. The package uses the `w32` window system, but it's
still in Cygwin, so it doesn't use `pythonw`.

The variable should be defined like this:

    (defcustom elpy-rpc-python-command (if (string-equal system-type "windows-nt")
                                           "pythonw"
                                           "python")...)

**Comment by jorgenschaefer** [comment]
Nice one, thank you!
