### ISSUE TITLE
How to change elpy's RPC to Python 3 in Emacs Prelude

### ISSUE THREAD

**Issue by xuehao** [jorgenschaefer/elpy#524]
When I modify `prelude-python.el` like this:
```
(defun prelude-python-mode-defaults ()                                          
  "Defaults for Python programming."                                            
  (subword-mode +1)                                                             
  (elpy-mode) 
  (setq elpy-rpc-python-command "python3")                                                                   
...
) 
```
The `elpy-config` shows RPC is still Python 2. 

But when I move ` (setq elpy-rpc-python-command "python3") ` to `.emacs.d/personal/custom.el`, it works fine.

Why does it happen? How to fix it? I want to put Python's config into only one file.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report.
I have no idea about prelude, so I can't really help you with it (you might want to ask the prelude people if you need help with prelude), but as a first guess, you could put the `setq' statement at the top of the `prelude-python.el` file, as opposed to within the `defun`?

**Comment by ChillarAnand** [comment]
`python-mode-hook` activates, `prelude-python-mode` which calls the function `prelude-python-mode-defaults` function.

so your config should work whenever you open `*.py` file.

@xuehao  can you try this config

    (defun prelude-python-mode-defaults ()                                          
      "Defaults for Python programming."                                            
      (subword-mode +1)                                                             
      (require 'elpy)
      (elpy-enable)
      (setq elpy-rpc-python-command "python3")

**Comment by xuehao** [comment]
@ChillarAnand Yes, it can detect `Python 3` now. But something is wrong with `eldoc`.
So I modify this config as follows:
```
(require 'elpy)
(defun prelude-python-mode-defaults ()
    ...
    (elpy-mode)
    (setq elpy-rpc-python-command "python3") 
    ...
)
```
I don't know why, but it works fine. Thank you.

**Comment by jorgenschaefer** [comment]
Glad this was solved. Thanks to @ChillarAnand for the help!
