### ISSUE TITLE
Please help me decide which backend to use

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#525]
I started out using "rope", because ... I dunno, I think I saw somewhere that it was the default.  I had no idea how the backends differed, so I didn't care.  Recently, however, I've learned that "jedi" allows `elpy-multiedit-python-symbol-at-point` to work nicely, whereas rope doesn't, so I've switched.  I wish I had known earlier the pros and cons of the various backends.

**Comment by ChillarAnand** [comment]
check  out https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-should-i-use-rope-or-jedi

**Comment by jorgenschaefer** [comment]
Yes, this is a real issue of Elpy right now, but I have no good solution. #329 would be a possible solution, as would be a "drop Rope altogether" as a result of #229. Rope is mostly stagnant and the latest attempt to revive it did not survive, it seems. Jedi will release a major rework of the library soon, and I expect to use it as the default then.

Thanks @ChillarAnand for linking the FAQ entry! :-)

**Comment by offby1** [comment]
@jorgenschaefer works for me.  Or, as the kids say: :+1:

**Comment by mmclark** [comment]
FWIW, I found jedi does a better job with navigation (M-.) than rope.  With rope installed and imports such as:

```
from mypackage.mymodule import Foo
```

(where mypackage was in the root of my project directory) rope was unable to locate Foo, and jedi was.

**Comment by jorgenschaefer** [comment]
Uh, I guess this is fixed with the FAQ :-) Sorry for leaving it open for so long.
