### ISSUE TITLE
color is abnormal when open .py file

### ISSUE THREAD

**Issue by thisEric** [jorgenschaefer/elpy#527]
emacs version:24.4
elpy.el version:elpy-20150226.1148

The first time open a .py file, the color display is OK, but when open another .py file, the color is abnormal, most of the code become red color.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!
This might be flymake telling you that the file does not follow the coding conventions it is configured to check for. If you put point on a red line, does the echo area show something like "E302 expected …" or similar?

If you run `C-c C-v`, does that show a lot of errors?

**Comment by thisEric** [comment]
thanks jorgenschaefer, I am sorry I made mistakes about this issue. It's actually indicates the warnings in the code. One more question, why the first time I open the .py file, it doesn't detect the warnings? and after that, no matter what .py to open, it can detect warnings in the code.

**Comment by jorgenschaefer** [comment]
I am not sure why that would happen – syntax errors and style warnings should be marked when the file is opened, even on the first time. Are there any errors or warnings in the `*Messages*` buffer?

**Comment by thisEric** [comment]
No, there isn't any error message, just some warnings, if I fix the warnings, everything is OK.
Does it relate to something like python env settings? I just enabled with (elpy-enable), use default settings. Anyway, thanks for your reply, I close this issue.
