### ISSUE TITLE
elpy goto definition efficiently?

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#528]
if i do `M-.` on any definition it takes me to the location of the file like this 

![elpy1](https://cloud.githubusercontent.com/assets/4463796/6982761/9be434d4-da33-11e4-98b5-c455c9523c4d.png)
(notice that the `point` is in the bottom line of buffer.)

but usually we jump to definition to take a look at it. so we have press `C-l` twice to take it to the top of buffer. 

so it makes sense to have a direct jump like this

![elpy2](https://cloud.githubusercontent.com/assets/4463796/6982760/9be3ba22-da33-11e4-9eb1-491242c13302.png)

(notice that the `point` is in top line of buffer.)

**Comment by jorgenschaefer** [comment]
Thank you for this nice idea and code in #529!

I did not use the PR because `recenter` is a better choice than `recenter-top-bottom` there, but it's basically the same idea.

**Comment by ChillarAnand** [comment]
if i do `C-h f elpy-goto-definition` emacs opens a buffer like this 
![ee](https://cloud.githubusercontent.com/assets/4463796/7765983/155a4bae-0082-11e5-9238-ca5368feffcc.png)

if i click on elpy it will take me to a new buffer but the point will be in the bottom line. 
any idea how to make pointer appear in top?

**Comment by jorgenschaefer** [comment]
The function it uses is `help-button-action`, which will call a few other functions down. Somewhere around there.
