### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by jdmssmkr** [jorgenschaefer/elpy#53]
This is a small annoying problem which is driving me almost mad. I have asked for help on various IRC channels but nobody could help me.

Python indentation in Emacs 24, using elpy, fails on the second or third indent (and thanks to elpy I get a nice red error-message). I configure my environment as such: 

;;
(setq python-check-command "pep8")
(elpy-enable)

;;
(defun jdm-python-mode-hook ()
  (setq indent-tabs-mode nil)
  (setq python-indent 4)
  (setq tab-width 4))

;;
(add-hook 'python-mode-hook 'jdm-python-mode-hook)

;;
(provide 'jdm-python)

I have no idea why this shouldn't work. Somebody on IRC suggested that I asked this to you in case the elpy-package does something strange.

**Comment by sriaditya** [comment]
I stumbled on this closed issue on a google search. I wonder whether it would be appropriate to post my comments here.  Any way - it may help some one  - 
On my system auto indentation failed when using elpy on emacs24.3.1 on GNU Linux - Trisquel 7.0.  Without elpy active, the indentation worked well. 
The problem disappeared upon adding the line
`(electric-indent-mode +1)`
in my .emacs file.
