### ISSUE TITLE
How to hook into elpy-company-backend to activate company-yasnippet support?

### ISSUE THREAD

**Issue by halbtuerke** [jorgenschaefer/elpy#530]
I have the following elisp snippet to add `company-yasnippet` to every activated company backend:

```elisp
(defun company-mode/backend-with-yas (backend)
  (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
      backend
    (append (if (consp backend) backend (list backend))
            '(:with company-yasnippet))))
```

I tried using it with elpy's `elpy-company-backend` like so, but unfortunately it does not work:

```elisp
(add-hook 'python-mode-hook
          (lambda ()
            (add-to-list 'company-backends
            (company-mode/backend-with-yas 'elpy-company-backend))))
```

This resulted in the following value for `company-backends`:

```elisp
(elpy-company-backend
 (elpy-company-backend :with company-yasnippet)
 ...)
```

Just to test if it would work if I manually set the backend I tried via

```
M-x (setq company-backends (company-mode/backend-with-yas 'elpy-company-backend))
```

which resulted in the correct value.

```elisp
((elpy-company-backend :with company-yasnippet)
 ...)
```

Unfortunately I don't see any snippets in the completion list.

Any ideas how I could fix this?

Thanks in advance

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report.

For your first question, you probably should remove `elpy-module-company` from `elpy-modules` if you do the company integration yourself. That should result in the value you expect there.

As for the second question, I have no idea. The `:with` thing might have problems with asynchronous backends? You might have to ask the company author about this, I'm afraid.

**Comment by halbtuerke** [comment]
After removing the company module from the active modules and using my setup everything seems to work fine now. :+1: 

Thank you very much for pointing me in the right direction.

For anyone with a similar problem here is my current configuration snippet:

```elisp
(setq elpy-modules (delq 'elpy-module-company elpy-modules))
(elpy-enable)

(add-hook 'python-mode-hook
          (lambda ()
            ;; explicitly load company for the occasion when the deferred
            ;; loading with use-package hasn't kicked in yet
            (company-mode)
            (add-to-list 'company-backends
                         (company-mode/backend-with-yas 'elpy-company-backend))))
```

**Comment by jorgenschaefer** [comment]
Glad it works now, and enjoy Elpy :-)
