### ISSUE TITLE
Unable to use Elpy on Emacs 24.5.1

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#535]
I just upgraded to Emacs 24.5.1. Elpy didn't work right away, so I uninstalled it, closed Emacs, started Emacs and then installed it again (through `M-x list-packages` from the Elpy source, i.e. `1.7.1`), but still I am having no luck.

This is the error that I get when I try to run `(elpy-enable)` after starting Emacs and after  running `(package-initialize)`:

```
Debugger entered--Lisp error: (void-function cl-struct-define)
  cl-struct-define(yas--template "A template for a snippet." cl-structure-object nil nil ((cl-tag-slot) (key) (content) (name) (condition) (expand-env) (file) (keybinding) (uuid) (menu-binding-pair) (group) (perm-group) (table)) cl-struct-yas--template-tags cl-struct-yas--template t)
  byte-code("\300\301\302\303#\210\304\305\306\307\310\211\311\312\313\303&	\207" [function-put yas--make-template side-effect-free t cl-struct-define yas--template "A template for a snippet." cl-structure-object nil ((cl-tag-slot) (key) (content) (name) (condition) (expand-env) (file) (keybinding) (uuid) (menu-binding-pair) (group) (perm-group) (table)) cl-struct-yas--template-tags cl-struct-yas--template] 10)
  require(yasnippet)
  elpy-module-yasnippet(global-init)
  apply(elpy-module-yasnippet global-init nil)
  elpy-modules-run(global-init)
  elpy-modules-global-init()
  elpy-enable()
  eval((elpy-enable) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

That said, even though I run into the error above, I can still run `M-x elpy-config`, and this is what I get:

```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.4.3 (/Users/avazquez/anaconda3/bin/python)
Interactive Python: python (/Users/avazquez/anaconda3/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.7.1
Jedi..............: 0.8.1-final0
Rope..............: 0.9.4-1
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: flake8 (/Users/avazquez/anaconda3/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH, even though you do
not have an active virtualenv. Installing Python packages locally will
create executables in that directory, so Emacs won't find them. If you
are missing some commands, do add this directory to your PATH.

The importmagic package is not available. Commands using this will not
work.

[run] pip install --user importmagic

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button
to invoke its action.  Invoke [+] to expand a group, and [-] to
collapse an expanded group.  Invoke the [Group], [Face], and [Option]
buttons below to edit that item in another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[+]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[+]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
```

**Comment by jorgenschaefer** [comment]
> ```
> Debugger entered--Lisp error: (void-function cl-struct-define)
>   cl-struct-define(yas--template "A template for a snippet." cl-structure-object nil nil ((cl-tag-slot) (key) (content) (name) (condition) (expand-env) (file) (keybinding) (uuid) (menu-binding-pair) (group) (perm-group) (table)) cl-struct-yas--template-tags cl-struct-yas--template t)
>   byte-code("\300\301\302\303#\210\304\305\306\307\310\211\311\312\313\303& \207" [function-put yas--make-template side-effect-free t cl-struct-define yas--template "A template for a snippet." cl-structure-object nil ((cl-tag-slot) (key) (content) (name) (condition) (expand-env) (file) (keybinding) (uuid) (menu-binding-pair) (group) (perm-group) (table)) cl-struct-yas--template-tags cl-struct-yas--template] 10)
>   require(yasnippet)
>   elpy-module-yasnippet(global-init)
>   apply(elpy-module-yasnippet global-init nil)
>   elpy-modules-run(global-init)
>   elpy-modules-global-init()
>   elpy-enable()
> ```

Elpy is enabling yasnippet, which breaks. If I read this backtrace correctly, Yasnippet is using an older version of cl.el internally, which breaks because macros are expanded in compiled files. Try re-compiling yasnippet for 24.5? (You should be able to do something like `M-x byte-recompile-directory RET ~/.emacs.d/elpa/yasnippet-0.9.0.1/`)

**Comment by amelio-vazquez-reina** [comment]
Thank you @jorgenschaefer  That perfectly fixed the problem!
