### ISSUE TITLE
test_add_import is failing

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#541]
when i run tests using py.test,  this tests seems to fail. 

    def test_add_import(self):
        self.build_index()
        start, end, newblock = self.importmagic.add_import(
            TEST_SOURCE, 'from mymod import AnUncommonName')
        self.assertEqual(start, 2)
        self.assertEqual(end, 5)
        self.assertEqual(newblock.strip(),
                        'import logging\nimport time\n\nfrom mymod import AnUncommonName')
       E       AssertionError: 'import time\n\nimport logging\n\nfrom mymod import AnUncommonName' !=  'import logging\nimport time\n\nfrom mymod import AnUncommonName'

**Comment by jorgenschaefer** [comment]
Yep, see #479 – I'm waiting for a response of @birkenfeld about this.

It's weird that it works fine in Travis. If I change the lines to make it run locally, Travis fails.

**Comment by ChillarAnand** [comment]
thank you
