### ISSUE TITLE
Improved M-. / M-, functionality

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#544]
`M-.` should jump to the most likely definition of the current symbol, and put the old position into the global mark ring.

`C-u M-.` should list all possible definitions, assignments, and also _uses_ of the thing at point, with the respective line from their respective file, in an compilation-like buffer, with the user being able to just jump to any of them as needed.

This issue replaces:
#401 Command to list all usages of the symbol at point
#476 New `M-.`/`M-,` API in Emacs 25

**Comment by johnchanwork** [comment]
Nice feature. I've been waiting for this for awhile. And this is THE feature I missed switching from anaconda-mode.
