### ISSUE TITLE
update window point in inferior python process

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#547]
when i do `C-c C-c` on any buffer, the out put in inferior python process will be more than a page. if switch to that buffer and do `M-v` and comeback to `*.py` buffer, make some changes and run `C-c C-c` again, the python process buffer gets updated but the point will remain in the same position. but it has to be updated. 

i tried [the following](https://github.com/jorgenschaefer/elpy/commit/5e665e59e62f256db765fb16acffc2761e4683b8)  & its working when i execute it interactively but for `C-c C-c` its not working.

```
(set-window-point 
     (display-buffer (process-buffer (elpy-shell-get-or-create-process))
                                       nil
                                       'visible)
     (point-max))
```

i don't know what am i missing.

**Comment by jorgenschaefer** [comment]
Thanks for this report.
This is strange. If point in the *Python* buffer is at the end (i.e. after the prompt), it stays there and the window scrolls to keep the last line visible for me. So I can not reproduce the behavior you describe.

Can you reproduce this with `emacs -q` (i.e. without loading your config, and just elpy)?
Can you provide step-by-step reproduction instructions for me to follow? Including exact Emacs and Elpy versions?

**Comment by ChillarAnand** [comment]
i think i have not explained the issue clearly. 

case a: before executing `C-c C-c`,  point in the Python process buffer is at the end

before `C-c C-c`:
![1](https://cloud.githubusercontent.com/assets/4463796/7336842/1de41ace-ec2e-11e4-9704-2a584c87d7aa.png)


after  `C-c C-c`, 

![1](https://cloud.githubusercontent.com/assets/4463796/7336842/1de41ace-ec2e-11e4-9704-2a584c87d7aa.png)

python process buffer gets updated and point also moves according to the output. everything works fine.


case b: point is not at the end of prompt. 

before `C-c C-c`:
![2](https://cloud.githubusercontent.com/assets/4463796/7336843/1de55b5a-ec2e-11e4-82d3-0c11d12e9733.png)



after `C-c C-c`:
![4](https://cloud.githubusercontent.com/assets/4463796/7336841/1ddd8344-ec2e-11e4-9a18-6708115a2096.png)

point stays at the exact same position even python process buffer gets updated.

hope that makes sense

**Comment by jorgenschaefer** [comment]
Hm. Why do you want point to be moved then? You specifically moved it away from the end of the buffer – do you want `C-c C-c` to always move point to the end of the buffer, no matter where it is?

**Comment by ChillarAnand** [comment]
yes. it is better to move point to the end of the buffer, no matter where it is.

most of the times, the output in the python process buffer will be more than a few pages when an error occurs. so i will scroll back to see where error occured. since the file locations are *clickable* i will just click the link to jump to the location of error. fix the error & then run `C-c C-c`.

**Comment by jorgenschaefer** [comment]
I do not think that everyone would agree that this would be the expected behavior.

I would suggest for you to define your own function and simply use that:

```Lisp
(require 'elpy)
(define-key elpy-mode-map (kbd "C-c C-c") 'my/send-region-or-buffer)
(defun my/send-region-or-buffer (&optional arg)
  (interactive "P")
  (elpy-shell-send-region-or-buffer arg)
  (with-current-buffer (process-buffer (elpy-shell-get-or-create-process))
    (set-window-point (get-buffer-window (current-buffer))
                      (point-max))))
```

**Comment by ChillarAnand** [comment]
makes sense. thank you :+1:

**Comment by ketil-malde** [comment]
The suggested code works as long as the Python process buffer is already visible, but if not, it moves point to the end of the current buffer.  I'm no elisp expert, but inserting a

            (display-buffer-at-bottom (current-buffer) nil)

before the `set-window-point` opens a window to the buffer if it isn't there already.
