### ISSUE TITLE
seg fault when using importmagic

### ISSUE THREAD

**Issue by cnngimenez** [jorgenschaefer/elpy#551]
I think this should be an importmagic issue, but I don't know where is the problem. Like any seg-fault problem, this was difficult to find.

When I was using elpy, I found that the python code was crashing all the time, after a lot of debug I discarded the Elisp code and some python modules, also I found that it apears at random while debugging, so I realize a thread was running and crashing the python part of elpy. 

So, ImportMagic class crashes sending me a "segmentation fault" problem after the first entrance (the init JSON part like this: `{"id":1,"method":"init","params":[{"backend":"rope","project_root":"\/home\/myusername\/"}]}`) and some time latter, I think while build_index thread is working.

When I uninstall the importmagic package using pip, everything works fine (for now :smile:).

I use Fedora 21, elpy-rpc 1.8.0 (recently installed), I try on python 2.7.8 and 3.4.1, importmagic 0.1.3.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!
Could you provide the full error you were seeing, and also what you were doing when it happened?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I am closing this issue. Please do not hesitate to open a new issue if you encounter any more problems!
