### ISSUE TITLE
django-test-runner should somehow accept settings setup

### ISSUE THREAD

**Issue by qwiglydee** [jorgenschaefer/elpy#554]
It is common practice to have different django settings for production and developement.
The settings module should be configurable when invoking django test runner.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report.
The test runners do not prescribe any settings module, but simply use the current value of the `DJANGO_SETTINGS_MODULE` environment variable – you can change that to whichever settings module you like to use.

Does this answer your question?

**Comment by qwiglydee** [comment]
This variable should be set in environment where test runner starts. And the variable is project-dependant.
I see no way (or dont know how) to create project-local test runner.

Even if i created sh or py script like `runtests` to put in project dir - i cannnot figure out how to 'install' custom test runner to run the script.

**Comment by jorgenschaefer** [comment]
I usually use virtualenvwrapper's post-activate script to set project-specific environment variables.

And you can use `M-x elpy-set-project-variable` to set Emacs Lisp variables for a project. This uses Emacs' directory-local variables. :-)

**Comment by qwiglydee** [comment]
I have created following:
```
(defun elpy-test-runtests-runner (top file module test)
  (interactive (elpy-test-at-point))
  (if module
      (apply #'elpy-test-run
             top
             (append '("./runtests")
                     (list (if test
                               (format "%s.%s" module test)
                             module))))
    (apply #'elpy-test-run
           top
           '("./runtests"))))
(put 'elpy-test-runtests-runner 'elpy-test-runner-p t)
```
That works via M-x
But how to make it selectable for elpy-test-runner?

**Comment by jorgenschaefer** [comment]
A bit tricky with Emacs' customize interface, but you can just use `(setq elpy-test-runner 'elpy-test-runtests-runner)` – though in current versions of Elpy, you can just `(setq elpy-test-django-runner-command '("./runtests"))` and use the default django runner.

**Comment by drazenzen** [comment]
For custom django setup i just "override" (set shell args ;) for original elpy's django test runner.
```
(defun elpy-MY-PROJECT-django-runner (top file module test)
  (interactive (elpy-test-at-point))
  (if module
      (elpy-test-run top
                     "python" "devmanage.py" "test" "--noinput" ;; "--keepdb"
                     (if test
                         (format "%s.%s" module test)
                       module))
    (elpy-test-run top
                   "python" "devmanage.py" "test" "--noinput" ;; "--keepdb"
                   )))

(global-set-key (kbd "<f5>") 'elpy-MY-PROJECT-django-runner)
```
and than include custom `defun` in my project.

**Comment by jorgenschaefer** [comment]
I created #556 to track the addition of some section to the manual that explains a best practice approach for managing these things. Thanks for reporting this! :-)

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this is solved. Thanks for the report and ideas!
