### ISSUE TITLE
Switch back to python script buffer from python shell

### ISSUE THREAD

**Issue by lentils** [jorgenschaefer/elpy#555]
First off, thank you for Elpy! It's a great package and you should be proud of it. I especially appreciate how responsive you are to your users. 

One thing I've wanted is the ability to switch back to the python script buffer from the inferior python shell. If you can switch to the shell with "C-c C-z", it would be really nice to have that same functionality to easily switch back after playing in the REPL for a bit. Oftentimes I have multiple windows open, and it's distracting to have to navigate back by switching with `other-window`. 

A great model for this feature is ESS's `ess-switch-to-inferior-or-script-buffer` command. It's smart enough to know which buffer you switched to shell from and will always take you back to it.

Thanks again for all your hard work.

**Comment by jorgenschaefer** [comment]
That is an excellent idea, thank you!

**Comment by ChillarAnand** [comment]
hi @jorgenschaefer,  i am trying to [implement this](https://github.com/ChillarAnand/elpy/commit/59e03c557c280a604e7b1a14a9577fdc7b1accfb), but i can't figure out how to enable elpy in inferior python process buffer?

**Comment by jorgenschaefer** [comment]
I'm not sure if enabling Elpy in the inferior python process is the right thing to do – python and inferior-python are very different editing environments.

A very simply solution would be to just bind `C-c C-z` in `inferior-python-mode-map` to a command that jumps back to Elpy.

The more complex solution would be to write a `elpy-inferior-mode` and enable that in `inferior-python-mode-hook`. While this might be useful later for enabling various enhancements in the shell, for this feature alone, that's way too much work. So I'd go with just changing `inferior-python-mode-map`.
