### ISSUE TITLE
Issues getting Elpy to recognize a project.

### ISSUE THREAD

**Issue by drenze** [jorgenschaefer/elpy#557]
I strongly suspect that this issue is not a bug, but rather a user error, however I haven't been able to figure it out.

I'm in the process of converting over from using Eclipse to Emacs 24.3 and Elpy 1.7.50 for my Python development.  However, I'm running into a roadblock in getting Elpy to recognize my project.  Based on my understanding of the way elpy should work from the [documentation][1], if I set a project root folder, that folder should be included in the `sys.path` to search for modules.  This is not happening.

The [Elpy Documentation][1] doesn't seem to have any answers to my particular conundrum, nor can I find a basic tutorial that walks me through creating my first Elpy project to break it down and show me what I'm doing wrong.  When I contacted Jorgen via email, he suggested I post my question here.

In the shell, I first create the virtual environment `virtualenv` using `mkvirtualenv` from `virtualenvwrapper`.  Then I create the following folder/file structure within the virtualenv folder:

    virtualenv
    `-- my_project
        |-- src
        |   `-- my_project
        |       |-- __init__.py
        |       `-- foo.py
        `-- test

The contents of `foo.py` are:

    class foo(object):
        pass

    if __name__ == '__main__':
        pass

Next, I connect to an already-running instance of Emacs server using the Emacs client. Within Emacs, I enter: 

    M-x pyvenv-workon virtualenv

Emacs does show `[my_project]` in the mode line.  Next, I enter:

    M-x elpy-set-project-root ~/Projects/my_project/src

Then, I type `C-c C-f` to search the project for a file, and I get:

    C-c C-f is undefined

So, I type:

    M-x elpy-find-file

and I get:

    No project root found

If I create the file `test/test_foo.py` with the following code:

    from my_project import foo

    if __name__ == '__main__':
        pass

and then run it using `C-c C-c`, I get:

    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/doug/Projects/my_project/src/test/test_foo.py", line 1, in <module>
        from my_project import foo
    ImportError: No module named 'my_project'
    >>>

  [1]: http://elpy.readthedocs.org/en/latest/introduction.html

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> I strongly suspect that this issue is not a bug, but rather a user error, however I haven't been able to figure it out.

No worries, questions are fine here :-)

> I'm in the process of converting over from using Eclipse to Emacs 24.3 and Elpy 1.7.50 for my Python development.  However, I'm running into a roadblock in getting Elpy to recognize my project.  Based on my understanding of the way elpy should work from the [documentation][1], if I set a project root folder, that folder should be included in the `sys.path` to search for modules.  This is not happening.

This is a bit confusing thanks to the way Emacs works. For Emacs, a variable is either global or local to a buffer; there is nothing in between. As Elpy can not mandate a global project root, as you might want to edit multiple projects in different buffers, the project root is buffer-local. Which means that every buffer of a given project has its own project root.

> The [Elpy Documentation][1] doesn't seem to have any answers to my particular conundrum, nor can I find a basic tutorial that walks me through creating my first Elpy project to break it down and show me what I'm doing wrong.  When I contacted Jorgen via email, he suggested I post my question here.

Indeed, and this is a problem. #556 tracks the desire to create a best practice guide on how to develop using Elpy.

> In the shell, I first create the virtual environment `virtualenv` using `mkvirtualenv` from `virtualenvwrapper`.  Then I create the following folder/file structure within the virtualenv folder:

A quick note on best practice here: Usually, you do create a virtualenv folder in a different place to your project directory (which will likely be in a VCS). For example, you can have a virtualenv in `~/.virtualenvs/my_project/` and the project directory in `~/projects/my_project`.

> […]
>
> Then, I type `C-c C-f` to search the project for a file, and I get:
>
>    C-c C-f is undefined

Yep, Elpy is only active within Python files. You'll have to open a Python file to get its key bindings. Using its functions outside of Python files also will not work.

This is likely confusing when coming from Eclipse, where the whole editing environment has some sort of project-specific state. Keep in mind that Emacs does not have that. You either have a global state, or a buffer-local state, and Emacs is often used for many things at once, not "just" Python development, so you always have to get some sort of Python buffer before you can work correctly.

(This can be improved slightly with Projectile as a project package, which I am considering for Elpy, but it still won't work exactly like in other IDEs)

> If I create the file `test/test_foo.py` with the following code:
> […]
> and then run it using `C-c C-c`, I get:
> […]
>    ImportError: No module named 'my_project'

Elpy does not know that `test/` is a subdirectory of your project, nor that `../src/` is a library path to be added to your load path.

As you are using a slightly unconventional directory layout with a separate test and library directory (which is not wrong, just less common in Python), I would recommend that you use `add2virtualenv` on your `src` directory to make this path available in your virtualenv. After that, `C-c C-c` should work.

`C-c C-t` will work in test files, but it won't find your tests if you are in a Python file in your `src` directory.

Let me know if this works.

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this problem is solved. Thanks for the report, and do not hesitate to create new ones if you have further problems!

**Comment by mashu** [comment]
I have the same problem. I am using this structure 
`
project/
data  LICENSE  search  test
`
C-c C-t works just fine, but C-c C-c it can't find a module name search. This is because when I open search/MyClassFile.py it somehow tries to execute it from search/  although I started emacs in project/

I tried suggestion with add2virtualen but I dont have such bash command.
