### ISSUE TITLE
elpy not working with django mode

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#558]
i am trying [django-mode](http://melpa.org/#/django-mode). whenever i enable django mode, i am not able to enable elpy.  
when i am in *.py file, `elpy-mode` throws

    Elpy only works with `python-mode`

**Comment by jorgenschaefer** [comment]
Nice catch, thank you – Elpy should check if it's a derived mode of python-mode, not if it's python-mode directly.

**Comment by xamvolagis** [comment]
Hi, I am trying this with cython-mode, which is derived from python-mode, but I am getting the same error when editing a .py file, and getting 
File mode specification error: (error "Elpy only works with `python-mode'")
when trying with .pyx files.
