### ISSUE TITLE
Remove yasnippets totally

### ISSUE THREAD

**Issue by marcwebbie** [jorgenschaefer/elpy#560]
Any way to prevent elpy loading yasnippets? I have removed yasnippets module however once elpy loads, it loads all yasnippets anyway.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. Elpy should not do anything related to yasnippet if the symbol `elpy-module-yasnippet` is not in the `elpy-modules` variable. Did you remove the module from there?

**Comment by marcwebbie** [comment]
I've used this to delete yasnippet module:

```
(delete 'elpy-module-yasnippet elpy-modules)
```

**Comment by jorgenschaefer** [comment]
Does `C-h v elpy-modules` show `elpy-module-yasnippet` still? (`delete` is not guaranteed to remove the element from the list, see its docstring for details)

Also, are you running this code before `elpy-enable`?

**Comment by marcwebbie** [comment]
It was removed,

It was an order issue on my config. I was calling `(delete 'elpy-module-yasnippet elpy-modules)` after `elpy-enable` as you've mentioned

Thanks for the help. :)

**Comment by jorgenschaefer** [comment]
You're welcome, and glad it works now. Enjoy Elpy! :-)
