### ISSUE TITLE
'MergedNamesDict' object has no attribute 'get'

### ISSUE THREAD

**Issue by TuringMachinegun** [jorgenschaefer/elpy#563]
Not sure if helpful, I just encountered this bug message. I'm using Jedi as rpc. Actually I set it just today, and this is the first time I encounter this error.

Error Message

'MergedNamesDict' object has no attribute 'get'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.3.1
Elpy..............: 1.7.1
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: pyflakes (/usr/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/user/.emacs.d/elpa/elpy-20150226.1148/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/user/.emacs.d/elpa/elpy-20150226.1148/elpy/server.py", line 86, in rpc_get_calltip
    get_source(source), offset)
  File "/home/user/.emacs.d/elpa/elpy-20150226.1148/elpy/server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "/home/user/.emacs.d/elpa/elpy-20150226.1148/elpy/jedibackend.py", line 126, in rpc_get_calltip
    "index": call.index,
  File "/home/user/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 466, in get_subscope_by_name
    for s in self.py__mro__(self._evaluator):
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 429, in py__mro__
    for cls_new in mro_method(evaluator):
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 409, in py__mro__
    for cls in self.py__bases__(self._evaluator):
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 438, in py__bases__
    return list(chain.from_iterable(args.eval_args()))
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/param.py", line 151, in eval_args
    return [self._evaluator.eval_element(el) for stars, el in self._split()]
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/home/user/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "/home/user/.local/lib/python2.7/site-packages/jedi/parser/fast.py", line 78, in __getitem__
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
  File "/home/user/.local/lib/python2.7/site-packages/jedi/parser/fast.py", line 78, in <genexpr>
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
AttributeError: 'MergedNamesDict' object has no attribute 'get'

**Comment by jorgenschaefer** [comment]
Thank you for the report!

I assume you can't share the code that caused this error? It's a bug in Jedi, and I'd like to report it upstream with a reproduction case.

**Comment by TuringApproved** [comment]
Hi Jorgen,
thanks for the light-fast reply! (And a huge thanks for Elpy as well)

Well, I can't share the code itself. But I can refactor things around:

```python
import simpleNNlib  as snn
import numpy as np

class NeuralThingy():

    def __init__(self, x_params, y_params):

        self.x_params = x_params
        self.y_params = y_params

        max_linx = np.amax(self.x_params[:, :, 0] + self.x_params[:, :, 1])
        max_liny = np.amax(self.y_params[:, :, 0] + self.y_params[:, :, 1])
        self.h = np.amax((max_linx, max_liny))*2  # inhibitory constant

        self.x_nsymbols = x_params.shape[0]
        self.y_nsymbols = x_params.shape[1]
        self.nstates = self.x_nsymbols * self.y_nsymbols

        # construct input layer

        self.xinp_lr = snn.RampLayer(2, initial_values=[0.25, 0.5])
        self.yinp_lr = snn.RampLayer(2, initial_values=[0, 0.5])
```

The error happened when the point was "snn.RampLayer("<- here

as for the simpleNNlib, that is really nothing special so no problem sharing it:

```python

import numpy as np
from collections import defaultdict


class AbstractNNLayer(object):
    """
    The base class for all neuron layers. Each layer has to implement the possibility to
    add connections from other layers,
    to compute the input to each neuron by summing all contribution from it connections,
    and to compute the output given the input and some activation function.

    In particular, derived classes will override the activation funcion with their own.
    For example, a ramp layer will use a ramp activation function,
    a heaviside layer will use a heaviside function, etc...

    :param n_units: the number of units in the layer
    :param initial_values: a list of activation values with which the units will be 
	initialized
    """

    def __init__(self, n_units, initial_values=[]):
        self.n_units = n_units
        self.connections = []
        if not initial_values:
            self.activation = np.zeros(n_units)
        else:
            self.activation = np.array(initial_values)
            if self.activation.size != n_units:
                raise ValueError("initializing with wrong number of values.")
        self.transfer_function = None  # this is the abstract class, need to implement a specific one

    def _add_connection(self, from_layer, connection_matrix):
	"""
	Add a connection from from_layer to this layer, with weights as in connection_matrix.
	Return the connection matrix, so that it is possible to edit it subsequently.
	:warning: don't use this function directly, rely on Connection class to establish connections.
	"""
        conn_mat = np.array(connection_matrix)
        self.connections.append((from_layer, conn_mat))
        return conn_mat

    def sum_input(self):
	"""
	Computes the input contribution from connected layers.
	"""
        running_sum = np.zeros(self.n_units)
        if self.connections:
            for from_layer, connection_matrix in self.connections:
                if from_layer.activation.ndim == connection_matrix.ndim == 1:
                    running_sum += from_layer.activation * connection_matrix
                else:
                    running_sum += np.dot(from_layer.activation, connection_matrix)
        return running_sum

    def activate(self):
	"""
	Computes the units activation.
	"""
        self.activation = self.transfer_function(self.sum_input())

    def __getitem__(self, item):
        return LayerSlice(self, item)  # returns activation of item


class HeavisideLayer(AbstractNNLayer):
    """
    Class implementing a layer of neurons with Heaviside activation function.

    :param n_units: number of units in layer.
    :param centers: specifies :math:`c_i` for each unit :math:`i` , given the unit activation function :math:`H_i(x-c_i)` .
	Equivalent to adding a bias of :math:`-c_i` .
    :param inclusive: if :math:`H_i(-c_i)=1`, the :math:`i`-th item in the list is True, 
	otherwise it's False and :math:`H_i(-c_i)=0`.
    """

    def __init__(self, n_units, centers, inclusive=[]):
        AbstractNNLayer.__init__(self, n_units)
        self.centers = np.array(centers)
        self.inclusive = np.array(inclusive, dtype=bool) if inclusive else np.zeros(n_units, dtype=bool)
        if not self.centers.size == self.inclusive.size == self.n_units:
            raise ValueError("Array must be of the same size as layer.")
        self.exclusive = np.invert(self.inclusive)

    def activate(self):
	"""
	Computes the units activation
	"""
        inp_sum = self.sum_input()
        self.activation[self.inclusive] = (inp_sum[self.inclusive] >= self.centers[self.inclusive]).astype(int)
        self.activation[self.exclusive] = (inp_sum[self.exclusive] > self.centers[self.exclusive]).astype(int)
        return self.activation


class RampLayer(AbstractNNLayer):
    """
    Class implementing a layer of neurons with saturated linear activation function.

    :param n_units: number of units in layer.
    :param biases: a list specifying the bias for each neuron.
    :param initial_values: initial activation values
    """

    def __init__(self, n_units, biases=0, initial_values=[]):
        AbstractNNLayer.__init__(self, n_units, initial_values)
        self.biases = biases

    def activate(self):
        self.activation = np.clip(self.sum_input() + self.biases, 0, 1)
        return self.activation


class LayerSlice():
    """
    This class is used so that to access the activation for a given layer *nnlayer*,
    you can just use the notation *nnlayer[someslice]*, where *someslice* is the usual Python slice.
    """
    def __init__(self, layer, a_slice):
        self.layer = layer
        self.a_slice = a_slice

    def get_activation(self):
        return self.layer.activation[self.a_slice]

    activation = property(get_activation)


class Connection():
    """
    Class implementing a connection. Basically used to keep track of who is connected to who at this moment.
    Also, you can modify the connection by modifying conn_mat.

    :param from_layer: layer from which the connection is established.
    :param to_layer: layer to which the connection is established.
    :param connection_matrix: matrix specifying connections and weights.
    """
    # I don't remember why I wanted to keep track of all connections, I don't use this anywhere
    keep_track = defaultdict(list)

    def __init__(self, from_layer, to_layer, connection_matrix):
        self.sender = from_layer
        self.receiver = to_layer
        self.conn_mat = to_layer._add_connection(from_layer, connection_matrix)
        Connection.keep_track[to_layer].append(from_layer) 
```

**Comment by jorgenschaefer** [comment]
Thank you for the reproduction case. I'll report this upstream.
