### ISSUE TITLE
add elpy-indent-buffer?

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#565]
it will be useful when you have to edit files which are not properly indented or if you have any indentation errors.

**Comment by jorgenschaefer** [comment]
Hm. I am not sure what exactly you are suggesting this function would do.

It is not possible to automatically correct a badly-indented Python file, as indentation defines the block structure. E.g. it is impossible to programmatically decide what the correct indentation for the following code is:

```Python
x = 0
if True:
    x += 1
  x += 2
```

So, what exactly would that function do, or when would it be useful?

**Comment by ChillarAnand** [comment]
Python mode defines a variable `python-indent`. If python-indent is set to 4, and if we some functions like this

```
(defun elpy-indent-buffer ()
  "Indent current buffer."
  (interactive)
  (indent-region (point-min) (point-max)))

(defun elpy-indent-region-or-buffer ()
  "Indent a region if selected, otherwise the whole buffer."
  (interactive)
  (save-excursion
    (if (region-active-p)
        (progn
          (indent-region (region-beginning) (region-end))
          (message "Indented selected region."))
      (progn
        (elpy-indent-buffer)
        (message "Indented buffer.")))))
```

then the above code will be auto indented to
```
x = 0
if True:
    x += 1
    x += 2
```
Also if there is any mixed indentations(say 3 or 8 spaces) it will be auto adjusted.


But overall, it looks like it is a bad idea though.

**Comment by jorgenschaefer** [comment]
The problem is that there is no reason to assume that the code shouldn't be reindented to this instead:

```
x = 0
if True:
    x += 1
x += 2
```

I can see a use for a function that reindents *correctly* indented Python code to a different indent width. I'd really like e.g. [autopep8](https://pypi.python.org/pypi/autopep8) support in Elpy.

**Comment by ChillarAnand** [comment]
one last thing:

if i do `<M-down>` on this

    for i in range(10):
       |i = i + 1
        if i % 2  == 0:

it becomes 

    for i in range(10):
        if i % 2  == 0:
       |i = i + 1

instead of this 

    for i in range(10):
        if i % 2  == 0:
           |i = i + 1

is it a good idea to add context/indentation awareness to elpy?

and +1 for autopep8 support :smile:

**Comment by jorgenschaefer** [comment]
> is it a good idea to add context/indentation awareness to elpy?

Might be. But this has the same problem: It is not possible programmatically to decide what the right indentation is. Elpy actually tried to do that before, but it got it wrong so often I gave up on that … :-/

**Comment by ChillarAnand** [comment]
thank you!
