### ISSUE TITLE
Add support for autopep8

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#566]
As [mentioned here](https://github.com/jorgenschaefer/elpy/issues/565#issuecomment-103843256), it is a good idea to add autopep8 support for elpy.

**Comment by jorgenschaefer** [comment]
See also #231 – there are a few modules that provide an interface to modify the current file (the already supported importmagic is another one that does this), I think it would be a good idea to figure out an approach on how to support all of them with a common interface as opposed to building individual support for each of them.
