### ISSUE TITLE
Questions about elpy!

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#568]
1. `M-tab` is binded to elpy-backend. For non-mac users, meta is alt. Alt-tab is binded to app switcher by default. Can we change key binding for that?

2. `C-c C-c`  directly sends buffer to shell. If a script is reading arguments from command line, what is the best way to execute it in elpy?

3. Looks like melpa is not tracking master branch. 
I don't know right way to install dev version and sometimes i get this error.

```
Elpy Version Mismatch

You are not using the same version of Elpy in Emacs Lispcompared to
Python. This can cause random problems. Pleasedo make sure to use
compatible versions.

Elpy Emacs Lisp version: 1.8.0
Elpy Python version....: 1.7.1
``` 

 How to install development version locally? Can we add it readme or contributing file?

**Comment by jorgenschaefer** [comment]
> 1. `M-tab` is binded to elpy-backend. For non-mac users, meta is alt. Alt-tab is binded to app switcher by default. Can we change key binding for that?

Change? No. Add another binding? Maybe.

`M-TAB` is a default Emacs binding for `completion-at-point`. That's why Elpy binds that key at all.

As Elpy does completion automatically, that command is rarely needed, so I'm not sure if it is worth taking up a non-standard key binding for that. In the GUI version, you can likely use `C-M-i`, too. So there might already be an alternative.

It is not uncommon for window managers and other tools to "steal" bindings Emacs uses. You can either configure your user interface to free them (I have window switching on windows-tab, for example), or you can add that command to a different key.

> 2. `C-c C-c`  directly sends buffer to shell. If a script is reading arguments from command line, what is the best way to execute it in elpy?

`M-x compile` or `M-!` depending on which interface you like. I usually run Python scripts in a separate terminal or in `M-x shell`.

> 3. Looks like melpa is not tracking master branch.

Indeed, that is by design.

> How to install development version locally? Can we add it readme or contributing file?

```
rm -rf ~/.emacs.d/elpa/elpy*
mkdir ~/Projects
cd ~/Projects
git clone https://github.com/jorgenschaefer/elpy
```

Add the following to your `~/.emacs.d/init.el` or `~/.emacs`:

```Lisp
(add-to-list 'load-path "~/Projects/elpy")
(load "elpy" nil t)
(elpy-enable)
```

Obviously, use whatever directory you prefer instead of `~/Projects`.

To update, run `git pull --rebase`, `M-x load-library RET elpy RET` and `M-x elpy-rpc-reload`.

**Comment by ChillarAnand** [comment]
i was using (load-file "/path/to/elpy.el")
updated to this
> (load "elpy" nil t)

thank you :)

**Comment by ChillarAnand** [comment]
When i do `M-x elpy-config`, it is taking ~30 seconds to show the menu. Is it only for me or everybody else?

**Comment by jorgenschaefer** [comment]
That might be because Elpy does a check for package availability on pypi, which can take a while on a slow connection. I created #576 for a possible solution to this.

**Comment by ChillarAnand** [comment]
For above installation method to work fine, we have to manually install dependencies?

**Comment by jorgenschaefer** [comment]
Yes?

**Comment by ChillarAnand** [comment]
Ok. Thanks!

**Comment by ChillarAnand** [comment]
In my system, only `elpy.__main__` is using ~400MB of memory and I think its too much.

What is the average memory usage for elpy and how to minimize memory usage?

**Comment by ChillarAnand** [comment]
Some times  there are multiple  elpy process running, even  if  there is only one emacs instance running.

![ee](https://cloud.githubusercontent.com/assets/4463796/12136337/d57ea92c-b46c-11e5-9a60-fcda772a919c.png)

**Comment by jorgenschaefer** [comment]
> What is the average memory usage for elpy and how to minimize memory usage?

Elpy (and the backends it uses) do load the Python application being analyzed. So this depends entirely on what you are using it for. You want to check the `RSS` column in `top(1)`, though, as that's the only relevant memory usage metric.

> Some times there are multiple elpy process running, even if there is only one emacs instance running.

Elpy spawns a backend process per virtualenv and per project root it finds. You can use `M-x list-processes` to see a list of processes Emacs knows about.

Does this answer your questions? :-)

**Comment by ChillarAnand** [comment]
Yes. Thank you.

**Comment by ChillarAnand** [comment]
Does elpy supports plots? 

Running this code 

```py
print('foo')

import pylab
import matplotlib.pyplot as plt

data = [1, 2, 3, 4, 5]
plt.plot(data)
plt.show()
print('foo')
```

generates this

```py
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> foo
foo
>>> python.el: native completion setup loaded
>>> foo
foo
>>> 
```

**Comment by jorgenschaefer** [comment]
> Does elpy supports plots?

I don't understand that question. What does matplotlib use for `plt.show` when run in a standard Python shell?

**Comment by ChillarAnand** [comment]
Never mind. OP problem was solved https://github.com/jorgenschaefer/elpy/issues/909
