### ISSUE TITLE
Indentation for breaking lines disappears

### ISSUE THREAD

**Issue by dingxiong** [jorgenschaefer/elpy#572]
When breaking a long line to multiple lines, the indentation disappears compared with the native python mode.
For example, 
```
interpDifv = -dotproduct[minIndex+1] * newDifv[minIndex]
+ dotproduct[minIndex] * newDifv[minIndex+1]
```
should be better as
```
interpDifv = -dotproduct[minIndex+1] * newDifv[minIndex]
             + dotproduct[minIndex] * newDifv[minIndex+1]
```

**Comment by ChillarAnand** [comment]
hi  @dingxiong thanks for  the  report.  looks like  default python  mode(python.el)  doesn't  do auto indent  when  a long line is breaked into  multiple lines. 

elpy  doesn't  have  auto  indent features  right  now. also  [check this](https://github.com/jorgenschaefer/elpy/issues/565#issuecomment-103875439)

**Comment by jorgenschaefer** [comment]
Thank you for the report! Elpy uses the "native" Python mode that comes with Emacs and should not change anything with the indentation it does – the behavior you describe is what that mode does. Indeed, it is difficult for Emacs to know whether you want indentation there or not, without indentation, it's a valid Python program, too.

You can use parentheses to make it explicit what you want:

```Python
interpDifv = (-dotproduct[minIndex+1] * newDifv[minIndex]
              + dotproduct[minIndex] * newDifv[minIndex+1])
```

**Comment by dingxiong** [comment]
Thanks for the information. I did not notice that it is the feature of the python mode. 
Parentheses work for me ! Thanks again.

**Comment by jorgenschaefer** [comment]
Glad this works for you, and enjoy Elpy! :-)
