### ISSUE TITLE
error while grepping 

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#573]
i tried `C-c C-s cursor` and it exited abnormally.

![elpy222](https://cloud.githubusercontent.com/assets/4463796/7835733/ac2a23b4-0498-11e5-8efc-7f9bfa2e9634.jpg)

**Comment by jorgenschaefer** [comment]
Thanks for the report.

Are you using flycheck instead of flymake? Is `flycheck_views.py` a temporary file created by flycheck?

If so, `elpy-rgrep-symbol` should tell grep to ignore `flycheck_*` files. Or rather a possible flycheck module should add that to `grep-find-ignored-files`, I guess.

**Comment by ChillarAnand** [comment]
> Is flycheck_views.py a temporary file created by flycheck?

yes

**Comment by jorgenschaefer** [comment]
Ok, so you will have to customize `grep-find-ignored-files` for your use case until there's a flycheck module for Elpy :-)

**Comment by ChillarAnand** [comment]
got it. thank  you :+1:
