### ISSUE TITLE
Is it possible to use Elpy without Yasnippet?

### ISSUE THREAD

**Issue by daschwa** [jorgenschaefer/elpy#575]
I noticed that `elpy` is dependent on `yasnippet` in `elpy-pkg.el` and was wondering if there is a simple way to use `elpy` without it, thanks.

**Comment by jorgenschaefer** [comment]
Hello! You can customize `elpy-modules` and just remove `elpy-module-yasnippet`, Elpy will then not do any yasnippet initialization or customization.

Let me know if that solves your problem :-)

**Comment by daschwa** [comment]
Exactly what I was looking for, thanks!
