### ISSUE TITLE
Change face for warnings

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jorgenschaefer/elpy#581]
How can I change the face font of the warning signs displayed by the syntax and code checks?

![screen shot 2015-06-03 at 9 25 23 pm](https://cloud.githubusercontent.com/assets/1993919/7975019/46bf16fc-0a37-11e5-9ebf-e8f340630b0e.png)

They seem to be designed for a clear background color theme, but they are hard to read on a dark one. 

This is all on:
```
"GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.3.0, NS appkit-1347.57 Version 10.10.3 (Build 14D136))
 of 2015-06-03 on macbook-pro.my.company.net"
```

**Comment by jorgenschaefer** [comment]
Hello! Elpy uses flymake for these highlights, and the two faces are `flymake-errline` and `flymake-warnline`. Are those what you are looking for?

**Comment by amelio-vazquez-reina** [comment]
Thank you @jorgenschaefer Yes. That solved the problem.

**Comment by jorgenschaefer** [comment]
Glad to hear that! Please do not hesitate to open more issues if you encounter further problems, and enjoy Elpy :-)
