### ISSUE TITLE
ipython shell cannot have tab completion after run command `%reset`

### ISSUE THREAD

**Issue by shelper** [jorgenschaefer/elpy#584]
title pretty much explains everything.:)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report.

I am afraid the title does not explain much to me – I do not use ipython and have no idea what "after run command %reset" means, so you will have to be a bit more verbose with me.

What exactly are you doing, what exactly are you seeing, and what exactly did you expect to see?

**Comment by shelper** [comment]
sorry for being confusing, 
`%reset` is the the magic function in IPython, that "Resets the namespace by removing all names defined by the user, if called without arguments, or by removing some types of objects, such as everything currently in IPython’s In[] and Out[] containers (see the parameters for details)...."
so basically after you run 
`In [1]:%reset`
in the IPython based python shell buffer, the tab autocompletion won't work any more

but if you have IPython in the windows command line window， this `%reset` funtion wont disable the autocompletion.

I am not sure if this is a bug of your IPython based python shell buffer in your elpy, it is a minor issue.

**Comment by jorgenschaefer** [comment]
Ah! The python.el that comes with Emacs does send some initialization code, I guess IPython removes whatever that defines when you use `%reset`. 

Does it work again when you do `M-: (python-shell-send-setup-code)` after the `%reset`?

**Comment by shelper** [comment]
yes, it work again, thx

**Comment by jorgenschaefer** [comment]
Ah, good.

I'm not sure if Elpy can sensibly automate this, I'm afraid. :-/

**Comment by jorgenschaefer** [comment]
Having thought more about this, I don't think this is something Elpy can (or should) do. Please do report this upstream with `M-x report-emacs-bug`, as it's something best done by `python.el`. Sorry for letting this hang around for so long. Please do not hesitate to open a new issue if you have further problems!
