### ISSUE TITLE
Do not enable flymake if the check command is missing

### ISSUE THREAD

**Issue by hotpxl** [jorgenschaefer/elpy#586]
Hi. Currently if `pyflakes` or `jedi` is not installed and I open a file with `elpy` enabled, it will break and refuse to open the file. How can I change this behavior so that it fails silently, still enabling me to edit the file, but without autocompletion if `jedi` or `pyflakes` is not installed. I want to automate this and not having to manually enable or disable modes. I switch between `virtualenv`s a lot so I can't make sure that all of them have the dependencies.

Thanks.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!
Elpy should work (albeit in a limited way) even if neither pyflakes nor jedi are installed. What behavior exactly do you see when you say "it will break and refuse to open the file"?

**Comment by hotpxl** [comment]
Hi. When I open a Python file without `pyflakes` installed, in pops up a big warning like this. If I hit enter, it will redirect me to `*scratch*`.

![screen shot 2015-06-10 at 15 46 55](https://cloud.githubusercontent.com/assets/2174815/8077386/f617fe48-0f87-11e5-9274-5c98a4951e93.png)

**Comment by jorgenschaefer** [comment]
Ah yes, that is flymake. I guess Elpy should not enable flymake if the appropriate check command does not exist – good idea!

What error do you see about Jedi?

**Comment by hotpxl** [comment]
If I have `pyflake` installed but not `jedi`, it starts up just fine. It won't autocomplete of course. But the error is silent and everything is perfect.
