### ISSUE TITLE
elpy-nav-move-iblock-down can actually drag lines into oblivion :D

### ISSUE THREAD

**Issue by whirm** [jorgenschaefer/elpy#590]
You can move a line down past the end of the buffer and it will disappear :tada:

**Comment by jorgenschaefer** [comment]
Thanks for the report! Is this happening with the latest development version, or with the stable one?

I know I fixed an error like this, and I can't reproduce it with the latest development version. (Although there are plenty of bugs with the code movement commands still …)

**Comment by whirm** [comment]
I was in `bfd7c91819115429f88260438f92df7dc3b1bc26`, I upgraded to latest devel version and can't reproduce it anymore.

Before I could by doing something like:
visit ```/tmp/thing.py```

type ```RET```, ```print "hi"```, ```RET``` ```up```, ```M up```, ```M down```, ```M down```

Sorry for the noise!

**Comment by jorgenschaefer** [comment]
No worries, and thanks for checking again! :-)
