### ISSUE TITLE
elpy not working with cython mode

### ISSUE THREAD

**Issue by xamvolagis** [jorgenschaefer/elpy#591]
This is similar to issue [558](https://github.com/jorgenschaefer/elpy/issues/558)
Hi, I am elpy this with cython-mode, which is derived from python-mode, but I am getting the same error 
Elpy only works with `python-mode'
when editing a .py file, and getting 
File mode specification error: (error "Elpy only works with `python-mode'")
when trying with .pyx files.

**Comment by ChillarAnand** [comment]
@xamvolagis  hi, are you using master branch of elpy?

**Comment by xamvolagis** [comment]
Sorry, I had been using melpa as per the README, and that links to the release version. I installed it using el-get and manually choosing the master release, and now it works great, thanks a lot!

**Comment by ChillarAnand** [comment]
@xamvolagis no issues :smile:

**Comment by jorgenschaefer** [comment]
Thanks for responding here, and glad the issue got solved. :-)

**Comment by csheaff** [comment]
Hi Jorgen,

I'm currently using cython-mode with elpy as well and my syntax checker does not seem to be working properly. I can observe syntax errors of my .pyx file using C-c C-n, but they do not appear in my code. I'm using the latest version of elpy. Any thoughts?

Clay

**Comment by jorgenschaefer** [comment]
@csheaff I assume the .pyx files are using python-mode? Then, no idea – sounds like a bug in cython-mode and flymake maybe?
