### ISSUE TITLE
Which features and advantages would I lose if I remove elpy and simply use company-jedi?

### ISSUE THREAD

**Issue by shackra** [jorgenschaefer/elpy#592]
I was thinking on removing elpy and go more vanilla with my Emacs configuration for editing Python. Which features would I lose on doing this transition?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the issue. I'm afraid I do not know company-jedi, but you can find a list of Elpy features here: https://elpy.readthedocs.org/en/latest/ide.html

I would guess that everything except for completion would stop to work. (Also, completion using Rope, but I suspect that is not too relevant for you.) Elpy also comes with a number of other packages and configures them (yasnippet, flymake, etc.), and you can of course configure them by hand, too.

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this question is answered. Please do not hesitate to open a new issue if you have further problems!
