### ISSUE TITLE
elpy doesn't recognize neither jedi nor rope

### ISSUE THREAD

**Issue by jghasban** [jorgenschaefer/elpy#594]
Hello!!

I've followed your instructions for installing elpy, i've used pip to get jedi and rope_py3k (I'm using python3 interpreter)

but the following appears when i lunch M-x elpy-config:

Elpy Configuration

Virtualenv........: None
RPC Python........: 3.4.0 (/usr/bin/python3)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 24.3.1
Elpy..............: 1.8.0
Jedi..............: Not found (0.9.0 available)
Rope..............: Not found (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH, even though you do
not have an active virtualenv. Installing Python packages locally will
create executables in that directory, so Emacs won't find them. If you
are missing some commands, do add this directory to your PATH.

You requested Elpy to use the backend jedi, but the Python interpreter
could not load that module. Make sure the module is installed, or
change the value of `elpy-rpc-backend' below to one of the available
backends.

[run] pip install --user jedi

Please could you help me to properly configure jedi or rope?

Thank you.

**Comment by jghasban** [comment]
I also guess that the problem is where python3 lives ... isn't it?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

How did you install jedi and rope? Apparently, the Python interpreter `/usr/bin/python3` can not find them. Did you install them in a virtualenv, or maybe a different Python installation?

**Comment by jghasban** [comment]
Hello:

I have installed Jedi and rope_py3k using pip. As I'm using python3.4 interpreter for my projects I went to usr/local/lib/python3.4/dist.packages and i realize that pip didn't install the pakages there, so i switch to usr/local/lib/python2.7/dist.packages and i have found them there. Surprisingly pip sticks to python2.7 dist packages directory. Then I've tried the following: i run "sudo aptitude search jedy "(this was the was i've installed python3) and the following packages appeared:

python-jedi (for python2)
python3-jedi (for python3)

so i decide to install python3-jedi by doing "sudo aptitude install python3-jedi". When the installation ended up I return to my emacs and run M-x elpy-config and now jedi appears but the version is 0.7.0 and a warning of a new version (0.9.0) also appears. Until here i was pretty satisfied but when i test jedi by writing some python code in a buffer, an error message shwed up saying something about the encoding arg in jedi and that it seems to be an Elpy bug.
Then I kept searching for solutions and i've found an issue here that says that Elpy fails when using jedi 0.7.0 version. The thing that i couldn't do was installing the jedi 0.9.0 version ... Could you give me some guide lines in this matter?? Do you know what the problem could be?

Thank you for your time.

Regards,

Joseph

**Comment by jorgenschaefer** [comment]
It is quite possible that the `pip` program on your system belongs to the Python 2 interpreter. As you are using Python 3.4, you should have a pip program that comes with that Python interpreter. Is there a `pip3` or `pip3.4` program available?

**Comment by jghasban** [comment]
I'll chek it and I´ll write to you back

**Comment by jghasban** [comment]
Hello Jorge:

Well, I've installed pip3 which is python3-pip in aptitude packages. Then I've upgraded jedi to 0.9.0 and everything works just fine.

Thanks for your time. I'm happy now :)

Joseph

**Comment by jorgenschaefer** [comment]
Great to hear! Once you become more comfortable with everything, I can highly recommend using virtualenvs – they make all of this a lot easier, and Elpy has great support for them: http://docs.python-guide.org/en/latest/dev/virtualenvs/

I will close this issue now. Please do not hesitate to open a new issue if you have any further problems or questions, and enjoy Elpy! :-)
