### ISSUE TITLE
Unexpected output from backend - elpy-rpc ready (1.8.0)

### ISSUE THREAD

**Issue by ajsteven130** [jorgenschaefer/elpy#596]
Hello,

whenever elpy starts, I get an "Unexpected output from backend" window, with the following output:

```
Output from Backend

There was some unexpected output from the Elpy backend. This is
usually some module that does not use correct logging, but might
indicate a configuration problem.

Output
elpy-rpc ready (1.8.0)
```

Is there a way to simply ignore this "error"?

config is: elpy 1.8.0 using the jedi backend on Windows 7. Python install is the Anaconda distribution with Python 3.4

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

This is weird, that's the default greeting of the Elpy RPC server, it's most definitely not "unexpected"! :-D

What's the value of `default-process-coding-system` for you?

**Comment by ajsteven130** [comment]
Thanks for the quick response! I thought this output should be expected as well.

The value of `default-process-coding-system` is `(utf-8-unix . utf-8-unix)`

I do see the ^M line ending in the `Output From Backend` buffer - `elpy-rpc ready 51.8.0)^M`

**Comment by jorgenschaefer** [comment]
On Windows, process communication like the communication with the Elpy RPC process does use CR LF as a line terminator. Does it work if you set `default-process-coding-system` to `(utf-8-dos . utf-8-dos)`?

If so, did you change that variable in your configuration?

**Comment by ajsteven130** [comment]
Yes! That fixed it!

`default-process-coding-system` was set ito `(utf-8-unix . utf-8-unix)` in my init.el, but I have no idea why. Changing that fixed everything.

Thank you very much for your help, and sorry for making you debug a problem I created myself.

**Comment by jorgenschaefer** [comment]
No worries at all, and glad it works now! I will close this issue – please do not hesitate to open a new issue if you have any further problems or questions, and enjoy Elpy :-)
