### ISSUE TITLE
importmagic now has a few style config options

### ISSUE THREAD

**Issue by whirm** [jorgenschaefer/elpy#598]
Which can be set via `Imports.set_style(option1=value1,...optionN=valueN)`

Right now it's just `multiline` and `max_colums`.

I guess max_colums should be set to `fill-column`.

`multiline` defines if multiline imports should be using `backslash` or `parentheses` and it should be a
customizable option to be set to either value.

**Comment by jorgenschaefer** [comment]
Good idea!

`max_columns` should likely have a separate variable, too. I think `fill-column` is mainly useful for comments and strings, which is kind of different from code.

Also, nice work on importmagic!

**Comment by whirm** [comment]
I would love to have a config option that sets this and the python-fill-paren & co. column witdth.

**Comment by jorgenschaefer** [comment]
@whirm, good question! Looks like it's a full subset? Good to know :-D

**Comment by gopar** [comment]
importmagic is no longer supported
