### ISSUE TITLE
Why not move the dependencies  into elpy folder

### ISSUE THREAD

**Issue by xuehao** [jorgenschaefer/elpy#600]
Every python virtualenv need install elpy python dependencies, which is not convenient.

**Comment by jorgenschaefer** [comment]
Thank you for the idea! There's a suggestion for a similar goal in #516 that is not implemented yet.

In the meantime, you can install the dependencies in a separate virtualenv and add its `site-lisp` directory to `PYTHONPATH` or your virtualenv with virtualenvwrappers `add2virtualenv`. Does that help?

**Comment by whirm** [comment]
You can also use ```pip install --user importmagic foo bar ...```

**Comment by xuehao** [comment]
@whirm could tell how to do detailly? I try it but it still does't work

**Comment by whirm** [comment]
Just run ```pip install --user importmagic jedi rope``` on a terminal and the packages will be installed into  ```~/.local/lib/python2.7/site-packages``` out of any venv. And on the default PYTHONPATH.

**Comment by jorgenschaefer** [comment]
Recent virtualenv installations disable site packages, so that might not be in `sys.path` after all. You can run virtualenvwrapper's `toggleglobalsitepackages` to enable site packages in a virtualenv then, though.

**Comment by jorgenschaefer** [comment]
Not to self: `pip install jedi --target=.../somedir/` and adding `somedir` to `PYTHONPATH` should work.

**Comment by xuehao** [comment]
Great work. I just want this function. Thanks.
BTW, why not put this in the Wiki page?

**Comment by jorgenschaefer** [comment]
> BTW, why not put this in the Wiki page?

No reason not to!
