### ISSUE TITLE
searching for program : no such file or directory, c\:/python27/python.exe 

### ISSUE THREAD

**Issue by Thuruv** [jorgenschaefer/elpy#602]
The error caused not to run a program from the macs. I 've installed both python-mode and elpy. Its emacs24.5 windows.

see the path, Its malfunctioned. How to change the path. . Please help/

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question!

What exactly are you doing when you get this error?

**Comment by ruefo** [comment]
Got the same Error with same version of emacs and elpy 1.8.0 from melpa. Comes up e.g. when calling interactive python mode (C-c C-z); In this case "Searching for program: no such file or directory, c\:/Python34/Scripts/ipython.exe". I tried setting different python commands, but nothing worked. Seems as if the faulty escape char is inserted by the elpy config. Though, i could not find the point, where this is done.

**Comment by jorgenschaefer** [comment]
What's the output of `M-: (python-shell-parse-command)`?
Does `M-x run-python` work?

**Comment by ruefo** [comment]
1. "c\\:/Python34/Scripts/ipython.exe -i"
2. no.
Hmm.. seems as if Virtualenv is None. Could that be related?

**Comment by jorgenschaefer** [comment]
Ok. This might be due to `shell-quote-argument` breaking. `M-: (shell-quote-argument "C:/foo")` shows `"C\\:/foo"`, I take it?

This is a bug in `python.el` from Emacs core (and might be worth a bug report there, not sure if it's fixed in the development version).

In the meantime, you can evaluate the following which should hopefully fix the problem:

```Lisp
(defun python-shell-parse-command ()
  "Calculate the string used to execute the inferior Python process."
  (let ((exec-path (python-shell-calculate-exec-path)))
    (format "%s %s"
            (executable-find python-shell-interpreter)
            python-shell-interpreter-args)))
```

Does that solve the problem?

**Comment by ruefo** [comment]
Yeah. fixes te problem.

**Comment by jorgenschaefer** [comment]
Great to hear, and you are welcome :-)

@Thuruv, does this fix it for you, too?

**Comment by Thuruv** [comment]
Hie Jorgen,

Yup, the script you gave works. C-c C-c has done its job in running the
code.

Thanks you much. I don't know how to raise a bug. Can you do it. .? I'll
learn from It.
Thanks Again.

​
With All,
-Thilip V
CI Access Control Team

**Comment by jorgenschaefer** [comment]
Glad to hear this fixes your problem!

I'm afraid having no access to a Windows system, I can't actually test if this is fixed already, nor could I test if some change upstream would fix it, so I'll just leave it at this for now.

Please do not hesitate to open a new issue if you have further problems or questions, and enjoy Elpy :-)
