### ISSUE TITLE
auto format python code for pep8 upon saving 

### ISSUE THREAD

**Issue by shelper** [jorgenschaefer/elpy#605]
can you add this module to your elpy?
https://github.com/paetzke/py-yapf.el

enable the flymake in real time some times is annoying and slows down the editor. 
maybe run this yapf upon saving would be a better option for some users (like me :))

**Comment by jorgenschaefer** [comment]
Nice idea, thanks. Do you know `yapf` compares to [autopep8](https://pypi.python.org/pypi/autopep8/)?

**Comment by shelper** [comment]
i dont know much details, but according to http://eli.thegreenplace.net/2015/yapf-yet-another-python-formatter/
“”“
There are two big advantages for using YAPF for all your code:
It makes you think (and obsess) about formatting much less when writing / tweaking code. This saves time when coding.
It makes code from different developers consistent in a single project. This aids reading code, so IMHO it's the more important advantage.
”“”

**Comment by jorgenschaefer** [comment]
The question would be more about relative merits compared to autopep8, which seems to be doing much of the same thing, not for automatic code formatting itself :-) But ok, I'll take a look at some point. Thanks again!

**Comment by shelper** [comment]
does elpy provides options to autopep8 the code upon buffer-saving at this moment?
yapf and autpep8 may be similar to each other, it would be a timesaver for python coding if such an autoformat option in elpy can be enabled based on either yapf or autpep8.

**Comment by jorgenschaefer** [comment]
See #566 and #571 :-)

**Comment by ChillarAnand** [comment]
@jorgenschaefer  autopep8 vs yapf, a snippet from my [blog post](http://www.avilpage.com/2015/05/automatically-pep8-your-python-code.html)

![pep8](https://cloud.githubusercontent.com/assets/4463796/8482750/352a964e-2109-11e5-925d-c0007160696a.png)

**Comment by jorgenschaefer** [comment]
I don't know what you mean with "remove only lint errors [but] can't format code", autopep8 clearly formats code :-)

That autopep8 does not fix `more[3:  5]` looks like a missing feature – it seems not to fix E225 for some reason. And I haven't found a way to disable reformatting. So yeah, yapf seems to have a more comprehensive feature set.

Thanks for looking into this!

**Comment by ChillarAnand** [comment]
> I don't know what you mean with "remove only lint errors [but] can't format code"

original code
```
x = {  'a':37,'b':42,

'c':927}
```

autopep8
```
x = {'a': 37, 'b': 42,

     'c': 927}
```

yapf
```
x = {'a': 37, 'b': 42, 'c': 927}
```

**Comment by jorgenschaefer** [comment]
@ChillarAnand, yes, so both tools do format code?

**Comment by ChillarAnand** [comment]
@jorgenschaefer  yes :D

**Comment by jorgenschaefer** [comment]
Which would contradict the claim that _"they can't format code"_. That's all I said.

**Comment by ChillarAnand** [comment]
@jorgenschaefer Yeah, its my mistake. I meant to `beautify` not `format`. Just updated it. Thanks :)

**Comment by lins05** [comment]
I've implemented it in #705 .

**Comment by ChillarAnand** [comment]
Great. I guess we  can close this.

**Comment by jorgenschaefer** [comment]
Indeed! Thank you all :-)
