### ISSUE TITLE
Provide a variable describing path to elpy/snippets

### ISSUE THREAD

**Issue by eqyiel** [jorgenschaefer/elpy#607]
The snippets under `elpy/snippets` are great.

At the moment (if you use `package.el`) you need to add them using something like `(add-to-list 'yas-snippet-dirs "~/.emacs.d/site-lisp/elpa/elpy-1.8.1/snippets")`, manually incrementing the version when bumped.

It would be good to be able to do something like this instead: `(add-to-list 'yas-snippet-dirs 'elpy-installed-snippets-dir)`.

For instance, take a look at these lines from `yasnippet.el`:
```
(defvar yas-installed-snippets-dir nil)
(setq yas-installed-snippets-dir
      (when load-file-name
        (concat (file-name-directory load-file-name) "snippets")))
(defcustom yas-snippet-dirs (remove nil
                                    (list "~/.emacs.d/snippets"
                                          'yas-installed-snippets-dir))
```
`elpy` could do this too, and since `elpy` already requires `yasnippet`, the `add-to-list` could be called in `elpy-enable`!

**Comment by eqyiel** [comment]
My bad, this is already implemented by `elpy-enable`.

**Comment by jorgenschaefer** [comment]
Oh, a self-solving issue. Those are my favorite ones!

Thanks for reporting it anyhow, do not hesitate to open new issues if you have other ideas, and enjoy Elpy! :-)
