### ISSUE TITLE
Please disable flymake if the buffer isn't visiting a file.

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#608]
This is elpy version 1.8.1

I've noticed that when I do `magit-show-commit`, and one of the files in the commit is a python file, there are errors like `error in process sentinel: flymake-get-file-name-mode-and-masks: Invalid file-name`
What's happening, I guess, is: magit has created a python-mode buffer to hold the contents of the file, but that buffer isn't actually visiting a file.
And the buffer's name is e.g. `rackcontrol/load_whole_rack_config.py.~RA-110~3~`
Now that seems like a valid file name, but maybe flymake is (as often happens) misreporting the error: the _real_ error might be ENOENT, but it's confused, and is reporting that there's something wrong with the name (besides naming a file that doesn't exist).

**Comment by jorgenschaefer** [comment]
Thank you for the report!

I _guess_ flymake does not work for buffers without files, and should likely not enable in these at all. Needs some investigation.
