### ISSUE TITLE
Setting version of Python that runs in shell

### ISSUE THREAD

**Issue by danielhones** [jorgenschaefer/elpy#609]
First of all, I'd like to thank you for writing Elpy.  It's a great tool, everything works just right and it's configured almost perfectly right out of the box.  I love using it.

I have one question though, is it possible to set which version of Python runs in the shell that's initiated with `C-c C-z`?  Currently on my computer it's Python 3.4, but I'd like to make the default 2.7, or at least bind a 2.7 shell to a different key.  Is there any way to do this?

Thanks in advance for your time,
Daniel

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the kind words!

The shell run with `C-c C-z` is set with the option `python-shell-interpreter`, which defaults to `"python"`. I can highly recommend [using virtualenvs](http://docs.python-guide.org/en/latest/dev/virtualenvs/), though, which will ensure that `"python"` runs the right Python version for each of your projects.

Does this answer your question? :-)

**Comment by danielhones** [comment]
Yes it does!  Thanks very much.  I had been trying to use virtualenv, but then realized that elpy seems to want virtualenvwrapper so I switched to using that.  I found the relevant section in the documentation as well, don't know why I missed it before.  Thanks for answering, and I'll read the docs more closely next time.

**Comment by jorgenschaefer** [comment]
Elpy _should_ work without virtualenvwrapper (using `M-x pyvenv-activate` instead of `M-x pyvenv-workon`). If it doesn't, please do let me know!

Other than that, glad it works now. I'll close this issue. Please do not hesitate to open a new one if you have any further problems or questions, and enjoy Elpy! :-)
