### ISSUE TITLE
Bad backend

### ISSUE THREAD

**Issue by zrwang** [jorgenschaefer/elpy#612]
In my espy-config menu, I got something like this.

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.8.0 (Python), 1.8.1 (Emacs Lisp)
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/Users/zrwang/Library/Python/2.7/bin/flake8)

The Elpy backend is version 1.8.0 while the Emacs package is 1.8.1. This is
incompatible. Please upgrade the Python module.

Could you kindly tell me how to upgrade the Python module? Thanks!

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the question!

In theory, Elpy ships with its own copy of the Python module and adds that to the path, so this should not happen. Did you maybe install the Elpy module by hand? If so, try uninstalling it, that should fix the problem.

If not, in a Python shell, enter `import elpy` and `elpy.__file__` – what does it say where it was installed?

**Comment by zrwang** [comment]
Hi,
Thank you for your prompt reply.
I didn't manually install the elpy. And the location is as follows:

Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import elpy
>>> elpy.__file__
'/Library/Python/2.7/site-packages/elpy/__init__.pyc'

Thanks!

**Comment by jorgenschaefer** [comment]
Somehow, Elpy was installed as a package – where is that file from?

**Comment by zrwang** [comment]
I actually forgot about where and when I installed this package. So what should I do? Just remove the files under that directory?
Thanks!

**Comment by jorgenschaefer** [comment]
Removing `/Library/Python/2.7/site-packages/elpy*` should work, yes. Let me know if it does (or doesn't)! :-)

**Comment by zrwang** [comment]
Problem solved! Thank you very much! I am gonna close this issue. Thank you again!

**Comment by jorgenschaefer** [comment]
Glad it works, and enjoy Elpy! :-)
