### ISSUE TITLE
Trying to solve Flymake bug after making a file

### ISSUE THREAD

**Issue by dongz1007** [jorgenschaefer/elpy#620]
<h4>When I was trying to create a new py file "$ emacs filename.py", the following error appeared:</h4>

![screen shot 2015-07-29 at 2 49 55 pm](https://cloud.githubusercontent.com/assets/7764245/8967052/b925b5d8-3602-11e5-9065-a28bc5a6e458.png)

<h4>Then I tried to run "M-x elpy-config" to see details, I got this:</h4>
![screen shot 2015-07-29 at 3 00 57 pm](https://cloud.githubusercontent.com/assets/7764245/8967118/17af3066-3603-11e5-9b0b-f17dce1c41be.png)

<h4>Package installation:</h4>
I ran "sudo pip install --user jedi/rope/flake8" command in the command-line to get these packages installed. 

<h4>Problem:</h4>
I guess this sentence claimed my problem "Installing Python packages locally will
create executables in that directory, so Emacs won't find them". I read previous bugs, but I still have no clue how to fix it.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

`pip install --user` will install the package for the current user, so you do not need to use `sudo`. The scripts will then be in the directory `~/.local/bin`, which you have to add to your `PATH`. Your screenshots seem to be from a Mac, where adjusting `PATH` is notoriously annoying, so you can do that in your `.emacs` with `(add-to-list 'exec-path (expand-file-name "~/.local/bin"))`

You might need to restart Emacs afterwards, as Elpy won't configure `flake8` unless it can actually find it.

Let me know if this fixes the problem!

**Comment by dongz1007** [comment]
Hi Jorgen, Thank you for the quick response. 
<p>This code <code>(add-to-list 'exec-path (expand-file-name "~/.local/bin"))</code> really found those packages:</p>
![screen shot 2015-07-30 at 6 54 33 pm](https://cloud.githubusercontent.com/assets/7764245/8997181/7457fe58-36ec-11e5-9db9-3641193fa224.png)
<p>But when I was trying to create a new file <code>test.py</code> using <code>emacs test.py</code> again, Flymake threw another error this time:</p>
![screen shot 2015-07-30 at 6 57 08 pm](https://cloud.githubusercontent.com/assets/7764245/8997271/83e85718-36ed-11e5-91e9-5dd0cf797828.png)
<p>When I press <code>RET</code> could make the error message disappeared, but it was really annoying while I was editing the file.</p>
<h3>Solution:</h3>
<p>Therefore, I searched online and found <code>(setq flymake-gui-warnings-enabled nil)</code> this code to fix Flymake popup error problem. And now, I can use emacs with elpy as a normal person. </p>
<p>I am very appreciated for your help!</p>
Best,
Johnny

**Comment by jorgenschaefer** [comment]
Hello, and great that it works now!

This error means that flymake isn't working for you – does `~/.local/bin/flake8 test.py` throw any unusual errors for you?

**Comment by dongz1007** [comment]
<p>Hi Jorgen, thank you for the response.</p>
<p>After I put <code>(setq flymake-gui-warnings-enabled nil)</code>  into <code>.emacs</code> file, everything seemed to work perfectly. But how can I check additionally whether flymake work or not? Thank you very much!</p>
Best,
Johnny

**Comment by jorgenschaefer** [comment]
> But how can I check additionally whether flymake work or not?

If you type some line with bad indentation or similar, the buffer should have error highlights.

You can try and run `C-c C-v` and see if that works. If that manages to run `flake8` correctly, and does find errors, but the buffer does not show those errors inline, flymake is not working properly.

**Comment by dongz1007** [comment]
<p>It seemed that flymake was not working properly on the bad indentation. How should I fix this? </p>
![screen shot 2015-07-31 at 9 07 01 am](https://cloud.githubusercontent.com/assets/7764245/9007874/8f2c430c-3763-11e5-8edd-1e5679ae0b4d.png)

**Comment by dongz1007** [comment]
<p>Hi Jorgen, thanks for all these helps.</p>
<p>I solve all of these problems by installing <code>virtualenv</code>. </p>
![screen shot 2015-08-04 at 2 17 09 pm](https://cloud.githubusercontent.com/assets/7764245/9068782/89539522-3ab3-11e5-9850-03f0504223be.png)
<p>Now, elpy works perfectly for me. Thanks again!</p>

**Comment by jorgenschaefer** [comment]
Glad it works now, and enjoy Elpy! :-)

**Comment by dongz1007** [comment]
<p>Before I installed <code>virtualenv</code>, my macbook pro was crashed. I reinstalled the system all over again.</p>
<p>If anyone have the same problem in the future and if you are not familiar with mac system files, I recommend to install <code>virtualenv</code> directly, do not mess with your mac files.</p>
<p>Best Wishes,</p>
<p>Johnny</p>
