### ISSUE TITLE
elpy error

### ISSUE THREAD

**Issue by anle9371** [jorgenschaefer/elpy#621]
Error Message

'ListComprehension' object has no attribute 'parent'

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (c:/Python27/python.exe)
Interactive Python: python (c:/Python27/python.exe)
Emacs.............: 24.5.1
Elpy..............: 1.8.1
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: flake8.exe (c:/Python27/Scripts/flake8.exe)

**Comment by jorgenschaefer** [comment]
Thank you for the report! This looks a lot like #615 … Is this a recurring problem and keeps you from working with Elpy, or was this some odd one off problem?

**Comment by jorgenschaefer** [comment]
Lacking further updates, let's track this in #615 :-)

**Comment by anle9371** [comment]
Yes, please. Sorry for the overdue response, lots of random life stuff
happened.

Thanks,

Amy
