### ISSUE TITLE
elpy-test-at-point is too restrictive about test file names

### ISSUE THREAD

**Issue by IvanMalison** [jorgenschaefer/elpy#624]
This condition is used to determine whether elpy-test-at-point should return test information

``` elisp
(if (and file (string-match "/test[^/]*$" file))
```

Some python libraries do not use this naming convention for test files. Is this logic even all that necessary. It seems like it should be enough if the function in close proximity has a 'test' name.

If you think that keeping this is absolutely necessary I would at least recommend that it be moved into a function that is configurable by the user.

something like `elpy-test--is-test-file-function`

I can make this change if it sounds good to you.

**Comment by jorgenschaefer** [comment]
Thank you for the report! I thought about it for a bit and you are right, I can't think of a reason why `elpy-test-at-point` would care about the file name. Just checking the class name should be enough.
