### ISSUE TITLE
How to define custom prefix expansion?

### ISSUE THREAD

**Issue by xiaohan2012** [jorgenschaefer/elpy#630]
Hi,

Is there a way to define custom prefix expansion? Such as 

p + TAB --> print()
tr + TAB -> import pdb; pdb.set_trace()

It seems that there no such guide in the documentation? Am I search the wrong term?

**Comment by jorgenschaefer** [comment]
Hello! Elpy uses [YASnippet](https://github.com/capitaomorte/yasnippet) for snippet expansion, you can easily [define your own snippet](https://capitaomorte.github.io/yasnippet/snippet-development.html) for these sorts of things.

Incidentally, Elpy comes with a snippet called `pdb`, so `pdb + TAB` should already cover your second use case.

Does this answer your question? :-)

**Comment by xiaohan2012** [comment]
Wow, cool! Thanks
