### ISSUE TITLE
Elpy completion don't work with .so libs

### ISSUE THREAD

**Issue by sollidsnake** [jorgenschaefer/elpy#631]
Using company and the default elpy configuration won't provide completion for libraries like PyQt, that use .so files instead of .py. Using the jedi backend it works out-of-the-box. So, as a workaround, I need this in my python hook:
```
(remove-hook 'elpy-modules 'elpy-module-company)
(jedi:setup)
(jedi-mode 1)
(setq-local company-backends '(company-jedi))
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!
I think there's some confusion here. The `jedi:setup` and `jedi-mode` functions are from `emacs-jedi`, a different project than and unrelated to Elpy. You are using two IDE-like projects at the same time there.

You were likely confused by the naming confusion there. `jedi` is a Python library completely unrelated to Emacs. `emacs-jedi` is an Emacs extension that uses the Python library. Elpy is a different Emacs extension that also uses the _Python_ library. Elpy does not use `emacs-jedi`.

To use Jedi (the Python library) with Elpy, either install jedi and uninstall rope (using `pip`, not `M-x package-install`), or install both and change `elpy-rpc-backend` in Emacs to `"jedi"`.

Does this help?

**Comment by sollidsnake** [comment]
Sorry, I think I worded poorly my comment. I know about `jedi` library, I'm just letting you know that the default `elpy` configuration doesn't provide completion for packages like `PyQt`. I find this is important for the goal of `elpy`.

**Comment by jorgenschaefer** [comment]
Could you provide the output of `M-x elpy-config` when this is not working? Is `PyQt` available in the environment the Elpy RPC process is running in?

**Comment by sollidsnake** [comment]
Yes, PyQt is available in the elpy environment. `elpy` completes the package name, but the only option available is the `PyQt4.uic`, that is a pure python module of PyQt. The `.so` modules are the ones that aren't loaded.
![img6](https://cloud.githubusercontent.com/assets/1778350/9331829/f58002d2-4597-11e5-8a07-f09a8090660f.png)

here's the output of `elpy-config`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.4.3 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.8.1
Jedi..............: 0.9.0
Rope..............: 0.9.4-1
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH, even though you do
not have an active virtualenv. Installing Python packages locally will
create executables in that directory, so Emacs won't find them. If you
are missing some commands, do add this directory to your PATH.

The importmagic package is not available. Commands using this will not
work.
```

**Comment by jorgenschaefer** [comment]
Thank you! What's the value of `elpy-rpc-backend`?

**Comment by sollidsnake** [comment]
It's `nil`. Setting it to `"jedi"` didn't seem to change anything.

**Comment by jorgenschaefer** [comment]
Does `M-x elpy-rpc-restart` afterwards help to make sure that the RPC process uses the new setting?

**Comment by sollidsnake** [comment]
Yes, it does! The completion works after running `elpy-rpc-restart`

**Comment by jorgenschaefer** [comment]
I'm glad to hear it works now :-) The problem was that Elpy was using Rope (the default if both are available), and then the old backend was still running so it kept using Rope. It should keep working now if you either uninstall rope or set `elpy-rpc-backend` in your config file.

I assume this solves your problem?

**Comment by sollidsnake** [comment]
Yes, putting the following line in init.el and restarting emacs resolves this
```
(setq elpy-rpc-backend "jedi")
```
Thanks!
