### ISSUE TITLE
'Configuration error' popup from flymake when opening a python file

### ISSUE THREAD

**Issue by vjohansen** [jorgenschaefer/elpy#650]
Hi

I just installed elpy by following the instructions. Now each time I open a python file I get a popup from flymake.

       Configuration error has occurred while running (flake8 c:/Users/vagn/src/python/test_flymake.py)

"GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570"
Windows 7

I can run C-c C-v (elpy-check) successfully

    -*- mode: compilation; default-directory: "~/src/python/" -*-
    Compilation started at Sat Aug 29 08:30:04

    flake8 "c:/users/vagn/src/python/test.py"
    c:/users/vagn/src/python/test.py:3:1: E402 module level import not at top of file
    c:/users/vagn/src/python/test.py:3:1: F401 'sys' imported but unused
    c:/users/vagn/src/python/test.py:4:34: W292 no newline at end of file

    Compilation exited abnormally with code 1 at Sat Aug 29 08:30:05

I can see from flymake-post-syntax-check that the popup happens because flake8 has a non-zero exit value and no warnings and errors are found.

Here is the debug output from flymake

    Can't guess python-indent-offset, using defaults: 4
    file c:/users/vagn/src/python/test.py, init=elpy-flymake-python-init
    flymake is running: nil
    file c:/users/vagn/src/python/test.py, init=elpy-flymake-python-init [3 times]
    create-temp-inplace: file=c:/users/vagn/src/python/test.py temp=c:/Users/vagn/src/python/test_flymake.py
    saved buffer test.py in file c:/Users/vagn/src/python/test_flymake.py
    starting process on dir /
    started process 11208, command=(flake8 c:/Users/vagn/src/python/test_flymake.py), dir=c:/users/vagn/src/python/
    received 245 byte(s) of output from process 11208
    file c:/users/vagn/src/python/test.py, init=elpy-flymake-python-init
    parse line: file-idx=1 line-idx=2 file=c:/Users/vagn/src/python/test_flymake.py:3 line=1 text=E402 module level import not at top of file
    get-real-file-name: file-name=c:/Users/vagn/src/python/test_flymake.py:3 real-name=~/src/python/test_flymake.py:3
    parsed 'c:/Users/vagn/src/python/test_flymake.py:3:1: E402 module level import not at top of file', got line-err-info
    parse line: file-idx=1 line-idx=2 file=c:/Users/vagn/src/python/test_flymake.py:3 line=1 text=F401 'sys' imported but unused
    get-real-file-name: file-name=c:/Users/vagn/src/python/test_flymake.py:3 real-name=~/src/python/test_flymake.py:3
    parsed 'c:/Users/vagn/src/python/test_flymake.py:3:1: F401 'sys' imported but unused', got line-err-info
    parse line: file-idx=1 line-idx=2 file=c:/Users/vagn/src/python/test_flymake.py:4 line=34 text=W292 no newline at end of file
    get-real-file-name: file-name=c:/Users/vagn/src/python/test_flymake.py:4 real-name=~/src/python/test_flymake.py:4
    parsed 'c:/Users/vagn/src/python/test_flymake.py:4:34: W292 no newline at end of file', got line-err-info
    file c:/users/vagn/src/python/test.py, init=elpy-flymake-python-init
    process 11208 exited with code 1
    cleaning up using flymake-simple-cleanup
    deleted file c:/Users/vagn/src/python/test_flymake.py
    test.py: 0 error(s), 0 warning(s) in 0.79 second(s)
    switched OFF Flymake mode for buffer test.py due to fatal status CFGERR, warning Configuration error has occurred while running (flake8 c:/Users/vagn/src/python/test_flymake.py)

Config

     Elpy Configuration

    Virtualenv........: None
    RPC Python........: 3.4.3 (c:/tools/Anaconda3/python.exe)
    Interactive Python: ipython (c:/tools/Anaconda3/Scripts/ipython.exe)
    Emacs.............: 24.5.1
    Elpy..............: 1.8.1
    Jedi..............: 0.9.0
    Rope..............: 0.9.4-1
    Importmagic.......: 0.1.3
    Syntax checker....: flake8.exe (c:/tools/Anaconda3/Scripts/flake8.exe)

**Comment by jorgenschaefer** [comment]
Thanks for the report! This looks weird – the trace even includes the errors flymake found in the output.

My stab in the dark here would be that there's some line ending confusion maybe, considering this is Windows. What is the value of `default-process-coding-system`?

**Comment by vjohansen** [comment]
default-process-coding-system is a variable defined in `C source code'.
    Its value is (utf-8-dos . utf-8-unix)



The parser errors are not added to a list in flymake-parse-err-lines because the file names differ  according to flymake-same-files.

I added a message calls to flymake-same-files and flymake-fix-file-name


Note the :3



    started process 15948, command=(flake8 c:/Users/vagn/src/python/test_flymake.py), dir=c:/users/vagn/src/python/
    received 167 byte(s) of output from process 15948
    file c:/users/vagn/src/python/test.py, init=elpy-flymake-python-init
    parse line: file-idx=1 line-idx=2 file=c:/Users/vagn/src/python/test_flymake.py:3 line=1 text=E402 module level import not at top of file
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py"
    flymake-same-files "c:/Users/vagn/src/python/test_flymake.py:3" "c:/Users/vagn/src/python/test_flymake.py" nil
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    flymake-same-files "c:/Users/vagn/src/python/test_flymake.py:3" "c:/users/vagn/src/python/test.py" nil
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    get-real-file-name: file-name=c:/Users/vagn/src/python/test_flymake.py:3 real-name=~/src/python/test_flymake.py:3
    flymake-fix-file-name "~/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    flymake-same-files "~/src/python/test_flymake.py:3" "c:/users/vagn/src/python/test.py" nil
    flymake-fix-file-name "~/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    parsed 'c:/Users/vagn/src/python/test_flymake.py:3:1: E402 module level import not at top of file', got line-err-info
    parse line: file-idx=1 line-idx=2 file=c:/Users/vagn/src/python/test_flymake.py:3 line=1 text=F401 'sys' imported but unused
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py"
    flymake-same-files "c:/Users/vagn/src/python/test_flymake.py:3" "c:/Users/vagn/src/python/test_flymake.py" nil
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    flymake-same-files "c:/Users/vagn/src/python/test_flymake.py:3" "c:/users/vagn/src/python/test.py" nil
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    flymake-fix-file-name "c:/Users/vagn/src/python/test_flymake.py:3"
    get-real-file-name: file-name=c:/Users/vagn/src/python/test_flymake.py:3 real-name=~/src/python/test_flymake.py:3
    flymake-fix-file-name "~/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    flymake-same-files "~/src/python/test_flymake.py:3" "c:/users/vagn/src/python/test.py" nil
    flymake-fix-file-name "~/src/python/test_flymake.py:3"
    flymake-fix-file-name "c:/users/vagn/src/python/test.py"
    parsed 'c:/Users/vagn/src/python/test_flymake.py:3:1: F401 'sys' imported but unused', got line-err-info
    file c:/users/vagn/src/python/test.py, init=elpy-flymake-python-init
    process 15948 exited with code 1
    cleaning up using flymake-simple-cleanup
    deleted file c:/Users/vagn/src/python/test_flymake.py
    test.py: 0 error(s), 0 warning(s) in 0.70 second(s)
    switched OFF Flymake mode for buffer test.py due to fatal status CFGERR, warning Configuration error has occurred while running (flake8 c:/Users/vagn/src/python/test_flymake.py)

**Comment by vjohansen** [comment]
flymake works if I disable by own config. I will investigate further,

So just close this issue. sorry for the noise,

**Comment by vjohansen** [comment]
The problem happens when I eval the push calls for ruby

**Comment by vjohansen** [comment]
http://www.emacswiki.org/emacs/FlymakeRuby

**Comment by jorgenschaefer** [comment]
Heh. Glad this problem resolved itself, and impressive debugging there!

**Comment by xhw1** [comment]
@vjohansen Sorry to bother you again. I got the similar flymake debug output. How did you solve this?

**Comment by vjohansen** [comment]
I was using some other elisp code that interfered with flymake in a bad way.

From what I can see above: I removed the flymake for ruby code I had added. This fixe the issue.

I suggest you try to remove other flymake code than that for elpy/python to see if it will work.

Or even start with minimal .emacs that only use elpy and nothing else
