### ISSUE TITLE
What is wrong with my python shell? Double outputs, Weird Elements

### ISSUE THREAD

**Issue by dongz1007** [jorgenschaefer/elpy#656]
<p>I wrote two lines of code and tried to get an input from user.</p>
<code>num = raw_input("Enter a num? ")</code>
<code>print num</code>
<p>Then, I pressed <code>C-c C-c</code> to execute my code. The <code>import</code> part inside of the python shell shows every time after I press the command.  And the output prints twice every time. </p>
## Here is a screenshot: 
![screen shot 2015-09-02 at 12 20 00 am](https://cloud.githubusercontent.com/assets/7764245/9623117/78add5f8-510a-11e5-8098-22eaada24341.png)
<p>Thank you!</p>

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question … this is weird. The code you're seeing is what Emacs' `python.el` sends to the Python interpreter (to avoid problems with empty lines and such). Normally, this is hidden by the implementation. I do not know why you see it.

Do you have any local configuration related to python-mode, comint, or process coding systems?

**Comment by dongz1007** [comment]
<p>Hi Jorgen, Thank you for your quick response. After received the reply from you, I tried few things: </p>
<p>* I re-installed Emacs on Mac OSX, ran a test with Emacs without Elpy installed, then I found out there is nothing wrong with my Elpy setup. Without my old <code>.Emacs</code> configurations, the error is still there. Which means something wrong with my computer.</p>
<p>* And I did some research about python-mode, comint, and process coding systems in google, I cannot find any related local file to them. </p>
<p>* I also did research about this error online, but there is limited resources. </p>
<p>What should I do? </p>
<p>Thank you very much for your help. </p>

**Comment by jorgenschaefer** [comment]
I am afraid I do not use Mac OS X, so I have very little experience with the problems there. As this seems to be a problem with Emacs itself, you could try to report a bug with Emacs using `M-x report-emacs-bug`? I am sorry I can not be of more help here.

**Comment by dongz1007** [comment]
<p>Hi Jorgen, thank you for all your help anyways. I will try to report this error to emacs. </p>

**Comment by jorgenschaefer** [comment]
You are welcome, and good luck!

**Comment by tianlixu** [comment]
I"m seeing the same problem in my emacs 25.3.1 on my Macbook.
