### ISSUE TITLE
Disable highlight-indentation-mode

### ISSUE THREAD

**Issue by pmcao** [jorgenschaefer/elpy#66]
Hi there,

Is there any option to disable the highlight-indentation-mode? 

Thank you!

**Comment by jorgenschaefer** [comment]
Use `M-x customize-variable RET elpy-modules RET` and remove the checkbox from the "highlight indentation" line.

**Comment by vinimmelo** [comment]
Another solution is to add a hook that remove this minor mode (not the best solution, i know):
`(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))`

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Sorry for warm this up. 
`M-x highlight-indentation-mode` works for me.

But I do not know how to make this setup persistent with using `use-package`. Can you give me a hint here please. You also wrote to remove that mode from a variable. I don't know how to do this with lisp syntax.

This is my use-package for elpy.

```
(use-package elpy
  :hook
  (python-mode . hs-minor-mode)  ;; folding
  :init
  (elpy-enable)
  :config
  (setq elpy-rpc-virtualenv-path 'current    ;; deactivate virtuelenv
        eldoc-echo-area-use-multiline-p nil  ;; mini-buffer doc nur 1-zeilig
	flymake-no-changes-timeout 35        ;; on-the-fly syntax check not so fast
	;; "error in process filter" problem when writing doc-strings
	;; see for details: https://emacs.stackexchange.com/a/63852/12999
        elpy-eldoc-show-current-function nil
	)
)
```

**Comment by ShravanTata** [comment]
Add this line in your config after loading elpy

`(setq elpy-modules (delq 'elpy-module-highlight-indentation elpy-modules))`
