### ISSUE TITLE
Restart rpc after changing venv

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#663]
It is better if elpy can restart rpc automatically after changing a virtualenv.

**Comment by jorgenschaefer** [comment]
Actually, all that is needed for this is to set `elpy-rpc--buffer` to nil in all Elpy buffers. This will cause Elpy to look up a new or existing buffer for the current library root and full RPC Python path. The latter should make Elpy use the correct RPC process for the virtualenv automatically.

**Comment by ChillarAnand** [comment]
How does elpy knows that user has called `pyvenv-activate` function? 

I think you have mentioned somewhere not to use hooks/defadvice.

**Comment by jorgenschaefer** [comment]
You should be able to use `pyvenv-post-activate-hooks`.
