### ISSUE TITLE
Do you recommend to use Python2 for elpy?

### ISSUE THREAD

**Issue by elgoog** [jorgenschaefer/elpy#665]
This is a question about python version for elpy.
When I try to install rope in Python3, an error occurs.
Here is the error message.
"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-anr36vt8/rope"
Looks like rope doesn't support python3 and the project seems to be inactive.
It is written in https://github.com/python-rope/rope/issues/57
Should elpy is used with only python2 if we use all features?

**Comment by ChillarAnand** [comment]
Elpy should work fine with both versions.

Can you try installing rope in python3 using this?

     pip install rope_py3k

**Comment by elgoog** [comment]
Thank you for the way.
I could install it.
