### ISSUE TITLE
Rope's refactoring error should throw a normal error, not a backtrace

### ISSUE THREAD

**Issue by petrux** [jorgenschaefer/elpy#666]
I have something like:

    import theano
    import numpy
    
    def AE(object):
    
        def __init__(self, d, h, lr):
            """Create a new autoencoder
        """
        
            b = numpy.sqrt(6.0 / (1.0 * (d + h)))
            self.Win = theano.shared(
                name='Win',
                value=numpy.random.uniform(-b, b, (d, h))
                .astype(theano.config.floatX)
            )
    
Trying to rename `self.Win` I have the following error message:

```
Error Message

Rename refactoring should be performed on resolvable python identifiers.

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.6.0
Jedi..............: 0.7.0 (0.9.0 available)
Rope..............: 0.9.2 (0.10.2 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/petrux/.emacs.d/elpa/elpy-20141031.945/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/petrux/.emacs.d/elpa/elpy-20141031.945/elpy/server.py", line 180, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/petrux/.emacs.d/elpa/elpy-20141031.945/elpy/refactor.py", line 207, in get_changes
    return method(*args)
  File "/home/petrux/.emacs.d/elpa/elpy-20141031.945/elpy/refactor.py", line 246, in refactor_rename_at_point
    refactor = Rename(self.project, self.resource, offset)
  File "/usr/lib/python2.7/dist-packages/rope/refactor/rename.py", line 28, in __init__
    'Rename refactoring should be performed'
RefactoringError: Rename refactoring should be performed on resolvable python identifiers.
```

**Comment by jorgenschaefer** [comment]
Thank you for the report. I am afraid Rope simply can not do this (for whatever reason). You could try installing Rope 0.10.2 instead, but I don't think that'll fix the problem.

**Comment by jorgenschaefer** [comment]
Come to think of it, Elpy should not pop up the full backtrace, but simply throw a normal error. That won't make the refactoring work, but the error will be a bit less obnoxious.
