### ISSUE TITLE
Add verbose option to py.test

### ISSUE THREAD

**Issue by abdulhaq-e** [jorgenschaefer/elpy#670]
I would like to run py.test as `py.test -vv`. I figured where I should make the change but whatever I put I get "command not found"

`Elpy Config --> [Group] Elpy --> [Option] Elpy Test Pytest Runner Command`

Tried `py.test -vv`, `py.test "-vv"`, all fail. How should I set it?

**Comment by jorgenschaefer** [comment]
Hello! This variable is a list - you want it to have two values, not one (using the `INS` button), with the first being `py.test` and the second being `-vv`.

Alternatively, you can use `(setq elpy-test-pytest-runner-command '("py.test" "-vv"))` in your `init.el` :-)

Does this solve the problem for you?

**Comment by abdulhaq-e** [comment]
Hi

This works perfectly. Thanks a lot.
