### ISSUE TITLE
Add configuration options for autopep8

### ISSUE THREAD

**Issue by slancheblanche** [jorgenschaefer/elpy#671]
I like the concept of running autopep8 through elpy, but I would like to be able to use some of configuration options that are available when running autopep8 on the command line.

What I would like to do is:
* configure the maximum line length
* disable fixes for certain errors/warnings

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

Does the current autopep8 implementation not use the `~/.config/pep8` and `setup.cfg` files?

**Comment by jorgenschaefer** [comment]
This should be fixed in the current development version. Let us know if anything breaks still!
