### ISSUE TITLE
Required feature `pyvenv'

### ISSUE THREAD

**Issue by pGalu** [jorgenschaefer/elpy#674]
Perhaps this is simply my ignorance showing, but attempting to follow the installation instruction here and in the docs, I encounter the following error:

    Compiling file /home/piotr/.emacs.d/elpa/elpy-1.9.0/elpy.el at Sun Sep 27 15:46:51 2015
    elpy.el:47:1:Error: Required feature `pyvenv' was not provided

The same error is returned when I subsequently attempt to use any of the elpy commands, like elpy-config etc.

(Regarding the prerequisite Python modules, I've installed jedi, but not rope, since it doesn't support Python 3)

I couldn't find this particular problem addressed anywhere yet.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. I guess this got truncated when reporting?

If you are encountering the error "required feature `pyvenv' not found", you are missing the [pyvenv library](https://github.com/jorgenschaefer/pyvenv) - you are best off installing Elpy from a package archive, that will also install all the dependencies.

Does this help with your problem?

**Comment by pGalu** [comment]
Thank you, and sorry about the missing text at first.
Curiously, `pyvenv` (1.8) appeared as `installed` in `list-packages` the whole time.
Removing it first and then reinstalling elpy (from melpa-stable this time) seems to have done the trick, though.
Again, thank you for such quick help.

**Comment by jorgenschaefer** [comment]
That does indeed sound strange – possibly a broken installation or similar? In any case, glad it works now.

I'll close this issue. If you have any further problems, please do not hesitate to open a new one. And enjoy Elpy! :-)
