### ISSUE TITLE
lines with syntax errors not hilighted for python (but not *.py) files

### ISSUE THREAD

**Issue by zacchiro** [jorgenschaefer/elpy#679]
When editing Python executable scripts (e.g., files with shebang line `#!/usr/bin/python`) whose names do not match the *.py globs, syntax checking misbehaves.
In particular, while C-c C-v does work, but lines with errors are not highlighted in the editing buffer, so no visual clues are shown about where to fix errors. One can only jumps to them after C-c C-v using prev/next error navigation.
Other Elpy features work as usual though, and the modeline shows the same thing that is shown when editing *.py files, i.e., `(Python Server || Elpy)`

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

Try evaluating the following expression, replacing the `.py` with whatever ending you are using:

```Lisp
(add-to-list 'flymake-allowed-file-name-masks
             '("\\.py\\'" elpy-flymake-python-init))  
```

Does it work now?

Out of curiosity, what endings are you using other than `.py`?

**Comment by zacchiro** [comment]
> Out of curiosity, what endings are you using other than .py?

So, that's the point: no extension whatsoever. My question is how to have flymake work for files like the following one:

    $ /tmp  cat hello
    #!/usr/bin/python3
    
    print('Hello, world!')

when editing them all elpy functionalities seem to work fine, except flymake.
I've tried evaluating directly `(flpy-flymake-python-init)` after opening the above file, but it doesn't seem to work: flymake is still not activated.

**Comment by jorgenschaefer** [comment]
Hm. Looking over Flymake's source, it seems flymake is not meant to do this at all. Interesting. You could report this via `M-x report-emacs-bug` :-)

In the meantime, I guess you could try [flycheck](https://github.com/flycheck/flycheck) – I do not use it, but I'm told it's quite a good replacement for Flymake, and should be able to support this.

After installing the flycheck module, you can enable it using this:

```Lisp
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))
```

Let me know if this works for you!

(#137 is about adding Flycheck support to Elpy, incidentally)

**Comment by jorgenschaefer** [comment]
Did this fix the problem for you? :-)

**Comment by zacchiro** [comment]
On Fri, Oct 09, 2015 at 04:07:19AM -0700, Jorgen Schäfer wrote:
> Did this fix the problem for you? :-)

Well, no :-)  as this bug report is specifically about flymake, and
honestly I don't fancy moving to flycheck right now, and just for this.

I find a bit surprising that elpy couldn't just tell flymake "activate
yourself on this buffer as if it were named *.py, no matter what". But I
haven't checked the flymake API.

**Comment by jorgenschaefer** [comment]
Yes, I am surprised that I could not find such an API in flymake.

**Comment by jorgenschaefer** [comment]
As this is a problem with flymake, this is sadly not something I can fix, so I will close this issue.

Please do report this missing feature with `M-x report-emacs-bug`, though, so the flymake maintainers can address it.

I hope you can enjoy Elpy despite of this problem :-) Do not hesitate to open a new issue if you have any further problems!
