### ISSUE TITLE
Brew python site packages not being found.

### ISSUE THREAD

**Issue by gregnewman** [jorgenschaefer/elpy#687]
I'm using brew Python on El Capitan (clean install).
If I inspect elpy-config outside of a virtualenv most of the values are not found. (rope, jedi, pyflakes, etc.)
If I switch to my virtualenv (and install these packages inside my project's venv, they are obvioulsy found.
I'd rather not have to install these packages for every venv.  Shouldn't elpy be able to find my global site-packages?

I tried `(setenv "PYTHONPATH" "/usr/local/bin/python")` but that did not fix the issue.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! If you are using virtualenvwrapper, you can use the `toggleglobalsitepackages` command to enable global packages in your virtualenv. Does that solve the problem? :-)

Otherwise, you'd have to set `PYTHONPATH` to something like `/usr/local/lib/python2.7/site-packages/` as it has to contain the library path, not the binary.

**Comment by gregnewman** [comment]
Thanks @jorgenschaefer 
I'd rather not toggle global site packages if I don't have to.
I tried to set my `PYTHONPATH` to `/usr/local/lib/python2.7/site-packages/` and that doesn't fix it either.
`(setenv "PYTHONPATH" "/usr/local/lib/python2.7/site-packages/")`

I have `desktop-save-mode` on so it's a minor inconvenience when reopening emacs to clear pyflakes warnings for every python buffer.  Am I not setting `PYTHONPATH` properly for elpy?

**Comment by gregnewman** [comment]
I just went through `elpy-config` and allowed it to install, using easy-install, the packages.  Looks like they installed in `/Users/greg/Library/Python/2.7/` which I guess would solve the problem but I don't like that it assumes that's the python I'm using, since I'm using Brew python.

Now all conflicts are solved except for flake8 which the install said it's located in `/Users/greg/Library/Python/2.7/bin` but each time I reopen `elpy-config` it says it's not found.

**Comment by gregnewman** [comment]
@jorgenschaefer I've fixed my issues.  I added the following to my init and all is good now.

`(add-to-list 'exec-path "/usr/local/bin/")`

**Comment by jorgenschaefer** [comment]
Oh, so the problem was not that the correct Python was not finding the appropriate packages, but that Elpy used the incorrect Python? Sorry, I misunderstood that.

Glad it works now – please do not hesitate to open a new issue if you have any further problems :-)
