### ISSUE TITLE
EOF in multi-line statement when 

### ISSUE THREAD

**Issue by jackcviers** [jorgenschaefer/elpy#688]
```
Error Message

('EOF in multi-line statement', (58, 0))

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.4.1
Elpy..............: 1.9.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/jackcviers/.emacs.d/elpa/elpy-20150830.510/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/jackcviers/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 220, in rpc_add_import
    return self.import_magic.add_import(source, statement)
  File "/home/jackcviers/.emacs.d/elpa/elpy-20150830.510/elpy/impmagic.py", line 68, in add_import
    imports = importmagic.importer.Imports(self.symbol_index, source)
  File "/home/jackcviers/.local/lib/python2.7/site-packages/importmagic/importer.py", line 79, in __init__
    self._parse(source)
  File "/home/jackcviers/.local/lib/python2.7/site-packages/importmagic/importer.py", line 150, in _parse
    self._tokens = list(tokenize.generate_tokens(reader.readline))
  File "/usr/lib/python2.7/tokenize.py", line 363, in generate_tokens
    raise TokenError, ("EOF in multi-line statement", (lnum, 0))
TokenError: ('EOF in multi-line statement', (58, 0))
```
### Call

`elpy-importmagic-add-import` on `random.uniform` in
```python
yaw = grad2rad(float(random.uniform(15.19, 15.26))
```
and selecting `import random` in helm selection. Message line prints: ` Wrong type argument: listp, 1444598513.8947017`

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

This is a bug in importmagic – @birkenfeld, does this look familiar? Also, would you prefer reports in the importmagic repo? :-)

**Comment by jackcviers** [comment]
@jorgenschaefer no problem, and that bug reporting feature of elpy is fantastic, btw.

**Comment by jorgenschaefer** [comment]
Thank you! :-)

**Comment by jorgenschaefer** [comment]
Ok, minimal reproduction case:

```Python
import importmagic
index = importmagic.index.SymbolIndex()
index.build_index([])
importmagic.importer.Imports(index, "foo(")
```

I am unsure if this actually _is_ a bug in importmagic, or if Elpy is just using importmagic badly.

**Comment by birkenfeld** [comment]
Ok, so the basic gist is that with an incomplete source, importmagic doesn't parse the source? Not sure we can do much about it, I don't think importmagic should grow a source sanitizer.

Maybe jedi contains something like this, which we can use to preprocess?

**Comment by jorgenschaefer** [comment]
The problem as far as I am concerned is that Elpy shows a big error message when a user does something rather normal (invoke importmagic on a piece of malformatted code).

If this is the expected behavior from importmagic, the impmagic module in Elpy should catch this error and raise an appropriate xmlrpc Fault that only gets shown as an error to the user.

So, in this particular case, importmagic is behaving as expected? :-)

**Comment by birkenfeld** [comment]
> So, in this particular case, importmagic is behaving as expected? :-)

I would say yes. At least for the automatic fixups, we need to know all the used names in the module.
For just adding an import you could argue that the rest of the file doesn't matter.

But for now I think just adding a good error message is fine. Since you know jedi much better, maybe you have an opinion if we could use it to sanitize the input?

**Comment by jorgenschaefer** [comment]
> But for now I think just adding a good error message is fine. Since you know jedi much better, maybe you have an opinion if we could use it to sanitize the input?

Jedi has its own partial code parser, in the `jedi.parser` package. As far as I know, though, the output is not the same as the `ast` module, so using it might require a lot of effort.

**Comment by birkenfeld** [comment]
Actually, hold on. TokenError can only occur at EOF, which means that we can recover the whole source. And Imports does not parse, only tokenize.

So I'll fix this one in importmagic.

**Comment by birkenfeld** [comment]
And pushed. I'll open an elpy PR for the cases where a SyntaxError can still occur.

**Comment by jorgenschaefer** [comment]
You are awesome, thank you so much!

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume the issue was fixed. Thanks a lot for the report, and do not hesitate to open a new issue if you have any further problems, and enjoy Elpy!
