### ISSUE TITLE
highlight indentation is too slow on big files

### ISSUE THREAD

**Issue by bersace** [jorgenschaefer/elpy#689]
Hi,

Elpy handle nicely degraded mode on big file for RPC. But i still feel emacs to lag on big file when indentation highlight is on.

I use a workaround in my .emacs.d that disable _only_ indentation highlight and everythink get smoother. https://github.com/bersace/dotemacs/blob/master/site-lisp/my-elpy.el

Maybe there is a way to optimize this. Actually, indentation highlight is very helpful on python, so losing it is a sad :)

Regards

**Comment by jorgenschaefer** [comment]
I think it'd be a good idea if Elpy would automatically disable features that cause bad performance in large buffers, thank you for the idea!

Improving indentation highlight to be faster would be even nicer, of course …

**Comment by bersace** [comment]
Hi @jorgenschaefer I suggest to close this issue. It's looks outdated.

**Comment by jorgenschaefer** [comment]
Sounds good, thank you.
