### ISSUE TITLE
Elpy should support dedicated Python processes

### ISSUE THREAD

**Issue by xin-jin** [jorgenschaefer/elpy#690]
It seems to me that currently all python buffers share a single python interpreter shell. Is it possible to associate different buffers to separate shells? In ess-mode, one can choose which shell to use (either an existing one or create a new one). I think it is very useful feature.

Thanks!

**Comment by emacsway-qarea** [comment]
Have you tried rename current buffer before start new?

**Comment by xin-jin** [comment]
@emacsway-qarea I did try. But that dissociate that shell with any buffer. What I want is run several different shells for different buffers at the same time, so that I can run two programs without their results messed up together.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question. :-)

You can do this using `C-u M-x run-python` – it will ask you which command to run, and then whether to make a "dedicated process". The latter is what you are looking for.

Does that solve the problem?

**Comment by xin-jin** [comment]
@jorgenschaefer Thanks. Yes, I indeed can make a new dedicated process now. However, I find that the ``C-u C-u`` (send buffer to shell) behavior is then strange. It does send the buffer to the shell it associated with, but the "popped up" shell is the old one. 

That is, if I have buffer1 and buffer2, also shell1 and shell2, respectively. When I execute buffer2, the result is indeed printed on shell2, but shell1 rather than shell 2 pops up. Even when I manually split the frame to buffer2 and shell2, shell1 still pops up and messes up the frame:

![selection_002](https://cloud.githubusercontent.com/assets/6195346/10461860/467ebe34-7190-11e5-9b6d-33c4a3642736.png)

**Comment by jorgenschaefer** [comment]
Oh, interesting. The buffer pop-up code is from Elpy, the rest is from python.el, and Elpy does not know about dedicated processes. I guess Elpy should support them at least rudimentarily.

Thanks for the report!

**Comment by jonmoore** [comment]
I use the advice below for python-shell-get-process-name together with pyvenv-track-virtualenv so that I can have a mapping file->venv->process-name.  Based on limited tests this seems to work with elpy-shell-send-region-or-buffer, although it is obviously a bit fragile.
```elisp
(defun my-python-shell-get-process-name (orig-fun &rest args)
  "If `pyvenv-virtual-env-name' is set then return a buffer name
based on this and `python-shell-buffer-name', otherwise call
`python-shell-get-process-name'"
  (if pyvenv-virtual-env-name
      (format "%s[%s]" python-shell-buffer-name pyvenv-virtual-env-name)
    (apply orig-fun args)))
(advice-add 'python-shell-get-process-name :around #'my-python-shell-get-process-name)
```

**Comment by muahah** [comment]
I ran to the same problem before ended up here, I modified `elpy-shell-get-or-create-process` to support dedicated python shells :
```Lisp
(defun elpy-shell-get-or-create-process (&optional dedicated)
  "Get or create an inferior Python process for current buffer and return it."
  (let* ((bufname (format "*%s*" (python-shell-get-process-name nil)))
	 (dedbufname (format "*%s*" (python-shell-get-process-name t)))
         (proc (get-buffer-process bufname))
	 (dedproc (get-buffer-process dedbufname)))
    (if dedproc
	dedproc
      (if proc
	  proc
	(run-python (python-shell-parse-command) dedicated)
	(get-buffer-process bufname)))))
```
I find very useful to have dedicated python shells for every buffers, maybe elpy should have an option for that.

**Comment by jorgenschaefer** [comment]
That PR should have fixed this. If not, please reopen.
