### ISSUE TITLE
Elpy Backend Error

### ISSUE THREAD

**Issue by tim042849** [jorgenschaefer/elpy#694]
Elpy Error window opens with the following (truncated at 'source') after '#' line:
#############################################################
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

__init__() got an unexpected keyword argument 'encoding'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.7.0
Jedi..............: 0.7.0 (0.9.0 available)
Rope..............: Not found (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/tim/.emacs.d/elpa/elpy-1.7.0/elpy/jedibackend.py", line 299, in run_with_debug
    script = jedi.Script(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
#############################################################################
Following source = '''\ ## source code of the file
#############################################################################
Also, the minibuffer is full of data. Most if not all is reproduced from *Messages*
Above mention data follows lines of '#'
#############################################################################
 [help-window help-buffer help-setup help-window-point-marker help-window-select window-live-p window-buffer window-parameter quit-restore marker-buffer set-window-point nil selected-window t frame other window-frame selected-frame window-list no-mini 2 select-window help-window-display-message window "Type \"q\" to delete help window" "Type \"q\" to delete help frame" "Type \"q\" to restore previous buffer" "Type \\[delete-other-windows] to delete the help window" "Type \"q\" in help window to restore its previous buffer" "Type \"q\" in help window to delete it" "Type \"q\" in help window to restore previous buffer"] 4 2004444], 2
error in process filter: Wrong number of arguments: #[(help-window) "Å!

**Comment by tim042849** [comment]
OT here : The file which is being edited at the time of error messages is legacy code, but has been
tested with flake8 run from the command line so that no messages from flake8 are found. The only alteration of flake8 behavior has been to set
max-line-length = 100
in the config file.
I'm on a new ubuntu installation and suspect a missing component, but this is literally my first experience with elpy.

**Comment by jorgenschaefer** [comment]
Thank you for the report!

> `Jedi..............: 0.7.0 (0.9.0 available)`

Could you upgrade to 0.9.0 and see if that fixes the problem?

**Comment by tim042849** [comment]
I have upgraded to 0.9.0. Before, I could barely make a keystroke before errors began to be reported. After a bit of navigating, I see no problem. I hope to spend some time coding later today. I will report back after doing some work on this project. Thanks very much to Jorgen for the quick reply. :)

**Comment by jorgenschaefer** [comment]
Glad it works now! I will close this issue then, but please do not hesitate to open a new one if you have any further problems – and enjoy Elpy :-)

**Comment by tim042849** [comment]
* Jorgen Schäfer <notifications@github.com> [151018 07:42]:
> Glad it works now! I will close this issue then, but please do not hesitate to open a new one if you have any further problems – and enjoy Elpy :-)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgenschaefer/elpy/issues/694#issuecomment-149025086

  It occurs to me to write a cron job that updates pip packages daily.

  There's good info here :
  http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip

  Question :
    If jedi, flake8 or anything else associated with elpy is
    updated, do I need to restart emacs?

  Thanks for such timely responses!
-- 
Tim 
http://www.akwebsoft.com, http://www.tj49.com

**Comment by jorgenschaefer** [comment]
> If jedi, flake8 or anything else associated with elpy is updated, do I need to restart emacs?

flake8 is used as an external program that is run every time it is needed, so any changes should be picked up automatically. Jedi, importmagic and a few others are used in the long-running RPC process that Elpy maintains – you need to `M-x elpy-rpc-restart` to get that to pick up any changes in Python packages.

Restarting Emacs is only necessary (or rather, usually a good idea) when you upgrade the Elpy Emacs package. :-)

**Comment by tim042849** [comment]
Thank you Jorgen. I am good to go.
  Now, time watch your videos.

* Jorgen Schäfer <notifications@github.com> [151018 23:10]:
> > If jedi, flake8 or anything else associated with elpy is updated, do I need to restart emacs?
> 
> flake8 is used as an external program that is run every time it is needed, so any changes should be picked up automatically. Jedi, importmagic and a few others are used in the long-running RPC process that Elpy maintains – you need to `M-x elpy-rpc-restart` to get that to pick up any changes in Python packages.
> 
> Restarting Emacs is only necessary (or rather, usually a good idea) when you upgrade the Elpy Emacs package. :-)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgenschaefer/elpy/issues/694#issuecomment-149122659

-- 
Tim 
http://www.akwebsoft.com, http://www.tj49.com
