### ISSUE TITLE
Code Completion in Python Shell

### ISSUE THREAD

**Issue by gopar** [jorgenschaefer/elpy#697]
Not sure if this has already been asked but is there any way to get code completion within a python shell buffer? I'm using company-mode to _try_ to get completions but nothing works. For now I'm using the following snippet as a work around

``` lisp
(set (make-local-variable 'company-backends) '(company-dabbrev))
```

Works only for things already typed in buffer. Any info or related issues to get more info would be nice.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

Emacs' python.el already has some basic completion in the shell (namely, for already imported packages), which _should_ also be available to company when using the `company-capf` module. Have you tried that?

Other than that, Jedi has some support for completion in an interactive shell, but Elpy does not utilize that part of the Jedi API yet, I'm afraid.

**Comment by gopar** [comment]
@jorgenschaefer Sweet thanks! This works :smile:
