### ISSUE TITLE
pdb-many-windows

### ISSUE THREAD

**Issue by syamajala** [jorgenschaefer/elpy#708]
I'm not sure if this is the right place to ask, but I figured if anyone could do this it might be you.

What I would like is a many-windows mode like gdb-many-windows. Something that can list the stack frames and variables when using pdb would be very helpful.

**Comment by jorgenschaefer** [comment]
Hello! I am afraid I am not sure exactly what you are looking for – the request sounds very specific to debugging, so a feature of Emacs' gud / pdb mode? Or did you have something else in mind?

**Comment by syamajala** [comment]
Yes it was more of a request for an additional minor mode as I think that's how gdb-many-windows works. But it doesn't seem like it will be straight forward to add something like that for python without a better debugger.

**Comment by jorgenschaefer** [comment]
_In theory,_ GUD (the Emacs debugging interface) supports pdb … so _in theory,_ `M-x pdb` should be affected by `gdb-many-windows` … I do not use `M-x pdb` or GUD, though, so I do not know if it does or, if not, why it doesn't. Have you tried?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this question is resolved. Please do not hesitate to re-open this or open a new issue if you have further questions. Enjoy Elpy!
