### ISSUE TITLE
Flymake giving error with folder with Makefile

### ISSUE THREAD

**Issue by rhoit** [jorgenschaefer/elpy#71]
![Screenshot - 04292013 - 02:00:24 PM](https://f.cloud.github.com/assets/1684754/437543/b8a2b79e-b0a5-11e2-8d38-0cbd93b73de2.png)
## Error

When i run the any *.py file it gives me popup information.

```
  Flymake: Failed to launch syntax check process 'pyflakes' with args (/home/rho/testpy/main_flymake.py): Searching for program: no such file or directory, pyflakes. Flymake will be switch OFF
```
#### How do i disable **Flymake**?

Yes I have install pyflakes both in py2 and py3 using.

```
  $ pip2 install --user pyflakes # for py2.7
  $ pip install --user pyflakes # for py3.3
```

**Comment by zarzen** [comment]
I want to set full path to pyflackes. But I can't..
I follow the steps mentioned previously.
`M-x customize-variable RET python-check-command RET`
then click apply and save, emacs told me that `forward-sexp: Scan error: "Unbalanced parentheses"'
I was change the command directly. 
screen shot :
![screen shot 2015-01-29 at 12 56 58](https://cloud.githubusercontent.com/assets/1150493/5952649/56867ef6-a7b6-11e4-8971-ef8c67557bf4.png)

**Comment by jorgenschaefer** [comment]
I do not know what might be causing that error. Could you run `M-x toggle-debug-on-error` and hit "apply and save" again to see where the error happens? You can post the backtrace here.

Or rather, please do open a new issue for this, as it is unrelated to the issue you commented on. Thank you! :-)

**Comment by zarzen** [comment]
I am sorry I made that mistake.
I was editing .emacs file at the same time.  There was an unclosed parenthesis in my `.emacs` file.

**Comment by jorgenschaefer** [comment]
No worries. Glad it works now, and please do not hesitate to open a new issue if you have any further problems!

**Comment by stallman-cui** [comment]
thank to @jorgenschaefer:   commented on Apr 29, 2013
M-x customize-variable RET python-check-command RET and set it to the full path of pyflakes :-)
it works

**Comment by NickMitchell7** [comment]
One more thanks from me. Below is my actual path, in case it helps anyone:
1) M-x customize-variable RET
2) python-check-command RET
3) in the text box after 'Python Check Command:' ent the exact path with pyflakes itself included of course:   "/usr/local/bin/pylakes"
4) Click on "Apply and Save"
5) Open up a .py file and enjoy!

![bildschirmfoto 2015-09-23 um 17 03 37](https://cloud.githubusercontent.com/assets/12820901/10048845/15923ccc-6215-11e5-9073-4c10b8abfc70.png)
