### ISSUE TITLE
elpy-autopep8-fix-code error

### ISSUE THREAD

**Issue by edt-devel** [jorgenschaefer/elpy#720]
Wenn calling elpy-autopep8-fix-code I get the following message:

    Elpy Error

    The backend encountered an unexpected error. This indicates a bug in Elpy.
    Please open a bug report with the data below in the Elpy bug tracker:

    https://github.com/jorgenschaefer/elpy/issues/new

    ```
    Error Message

    'module' object has no attribute 'fix_code'

    Configuration

    Virtualenv........: None
    RPC Python........: 2.7.10 (/usr/bin/python)
    Interactive Python: python (/usr/bin/python)
    Emacs.............: 24.4.1
    Elpy..............: 1.10.0
    Jedi..............: 0.9.0
    Rope..............: 0.10.2 (0.10.3 available)
    Importmagic.......: 0.1.3
    Autopep8..........: 0.1.3
    Syntax checker....: flake8 (/usr/local/bin/flake8)

    Traceback

    Traceback (most recent call last):
      File "/home/edt/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
        result = method(*params)
      File "/home/edt/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 255, in rpc_fix_code
        return fix_code(source)
      File "/home/edt/.emacs.d/elpa/elpy-20151101.401/elpy/auto_pep8.py", line 21, in fix_code
        return autopep8.fix_code(code, apply_config=True)
    AttributeError: 'module' object has no attribute 'fix_code'
    ```

If there are any additional information you need, please let me know.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

> `Autopep8..........: 0.1.3`

There's a newer version (1.2.1) available, could you try if that works? `M-x elpy-config` should tell you about it and provide an example command on how to install it. :-)

**Comment by edt-devel** [comment]
Hi,

I just switched to the version provided by pip and it works!
Sorry for wasting your time.
The older version was installed through apt (debian testing), so others could also have this problem.

Thank you for your time and this piece of software. :-)

**Comment by jorgenschaefer** [comment]
Glad to hear it works! Enjoy Elpy :-)
