### ISSUE TITLE
elpy + hideshow?

### ISSUE THREAD

**Issue by nbecker** [jorgenschaefer/elpy#731]
I use the following:
(autoload 'hideshowvis-enable "hideshowvis" "Highlight foldable regions")

(autoload 'hideshowvis-minor-mode
  "hideshowvis"
  "Will indicate regions foldable with hideshow in the fringe."
  'interactive)

(dolist (hook (list 'emacs-lisp-mode-hook
                    'c++-mode-hook
		    'python-mode-hook))
  (add-hook hook 'hideshowvis-enable))

(hideshowvis-symbols)

But the symbols that should be shown in the left fringe are not visible when elpy is used.  For example, at the start of a for loop, there should be a '-' shown in the left fringe that is clickable.  The symbol is not visible (although it is still clickable).

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!
This is weird – Elpy does not do anything special for hide-show-mode. If you disable Elpy, does it work then?

**Comment by nbecker** [comment]
I think it may be covering up the fringe symbol

**Comment by nbecker** [comment]
After changing the color of the fringe, I think it's OK.

**Comment by jorgenschaefer** [comment]
Great, glad to hear it works now! Enjoy Elpy! :-)
