### ISSUE TITLE
Autocompletion only works on the first member imported

### ISSUE THREAD

**Issue by runekaagaard** [jorgenschaefer/elpy#732]
Hi

My apologies if this is already a known issue, I searched but nothing popped up. When i type e.g. ``from itertools import M-TAB`` I get all the members in itertools to choose from, but when another member is imported before on the same line I don't. See the second screenshot.

![screen shot 2015-12-05 at 8 30 52 pm](https://cloud.githubusercontent.com/assets/378464/11609749/9f00d154-9b8f-11e5-8486-850b4a6c4776.png)

![screen shot 2015-12-05 at 8 31 29 pm](https://cloud.githubusercontent.com/assets/378464/11609750/a3030448-9b8f-11e5-88dc-63f3d93083fe.png)

I'm using this version: ``GNU Emacs 24.5.1 (x86_64-apple-darwin12.6.0, NS apple-appkit-1187.40)``.

And my init.el file looks like:

    (require 'package)
    (add-to-list 'package-archives
             '("elpy" . "http://jorgenschaefer.github.io/packages/"))
    (package-initialize)
    (elpy-enable)
    (setq elpy-rpc-backend "jedi")

Do you have any insights why this is? Thanks!

**Comment by jorgenschaefer** [comment]
Thanks for the report! Elpy does not do anything special here, it just asks Jedi for possible completions, so this is a bug/missing feature in Jedi. I filed a bug report against Jedi to track this.

**Comment by runekaagaard** [comment]
Thanks for the reply, let's hope it's an easy fix for Jedi :)

**Comment by jonmoore** [comment]
This has been closed upstream and is working in elpy now.

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by runekaagaard** [comment]
Thanks a lot!
