### ISSUE TITLE
Python shell prompts not detected

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#733]
I am using ubuntu 14.04 and here is my config

```
Elpy Configuration

Virtualenv........: exp (/home/anand/.virtualenvs/exp)
RPC Python........: 2.7.6 (/home/anand/.virtualenvs/exp/bin/python)
Interactive Python: python (/home/anand/.virtualenvs/exp/bin/python)
Emacs.............: 24.5.2
Elpy..............: 1.9.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: pyflakes (/home/anand/.virtualenvs/exp/bin/pyflakes)

```

When trying to open a .py file, it is throwing these warning

```
Warning (emacs): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with `keyboard-quit' and then try fixing the
interactive flag for your interpreter by adjusting the
`python-shell-interpreter-interactive-arg' or add regexps
matching shell prompts in the directory-local friendly vars:
  + `python-shell-prompt-regexp'
  + `python-shell-prompt-block-regexp'
  + `python-shell-prompt-output-regexp'
Or alternatively in:
  + `python-shell-prompt-input-regexps'
  + `python-shell-prompt-output-regexps'
```

**Comment by jorgenschaefer** [comment]
Hello! This warning is issued by `python-shell-prompt-detect`. What are the values of `python-shell-interpreter` and `python-shell-interpreter-interactive-arg`?

You can avoid this warning by either setting either `python-shell-prompt-detect-enabled` or `python-shell-prompt-detect-failure-warning` to `nil`.

**Comment by ChillarAnand** [comment]
```
python-shell-interpreter is a variable defined in `python.el'.
Its value is "python"

python-shell-interpreter-interactive-arg is a variable defined in `python.el'.
Its value is "-i"
```
These are existing values.


```
  (setq python-shell-prompt-detect-failure-warning nil)
```
This solved the issue. I am wondering why it suddenly started showing that warning.

**Comment by jorgenschaefer** [comment]
> This solved the issue. I am wondering why it suddenly started showing that warning.

python.el runs the following Python code and parses the response as JSON:

```Python
import sys
ps = [getattr(sys, 'ps%s' % i, '') for i in range(1,4)]
ps_json = '\\n[\"%s\", \"%s\", \"%s\"]\\n' % tuple(ps)
print (ps_json)
sys.exit(0)
```

What happens when you run that in a `python -i` shell?

**Comment by ChillarAnand** [comment]
Output:

```

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> >>> >>> \n[">>> ", "... ", ""]\n

Process Python finished

```

**Comment by jorgenschaefer** [comment]
Strange. No idea why that would fail. :-(

**Comment by ChillarAnand** [comment]
Nah, forget it. Thanks :-)

**Comment by Will-W** [comment]
I've just upgraded to a new machine so am now running emacs 24.5 and I have the same issue. I did some digging.
The command executed is:
`process-file("python" "c:/Users/xxxx/AppData/Local/Temp/py5012-xx" (t nil) nil "-i")`

The contents of that file is what you'd expect:
```
import sys
ps = [getattr(sys, 'ps%s' % i, '') for i in range(1,4)]
ps_json = '\n["%s", "%s", "%s"]\n' % tuple(ps)
print (ps_json)
sys.exit(0)
```

If I run that file directly from the command line as `python path-to-file -i` (or for that matter `python -i path-to-file`), the output I get is `["", "", ""]`.

This isn't hugely suprising if you look in the docs (https://docs.python.org/2.7/library/sys.html). It says that ps1 and ps2 are only defined in interactive mode, and yet we're running a file.

I'm happy to do any further investigation you need.

**Comment by jorgenschaefer** [comment]
Hm. I can reproduce that behavior. Ironically, `M-: (python-shell-prompt-detect)` returns the correct values. Indeed, evaluating the following gives the correct prompt string for me:

```Lisp
(let ((code (concat "import sys\n"
                    "print(sys.ps1)")))
  (with-temp-buffer  
    (let ((code-file (python-shell--save-temp-file code)))
      (call-process "python" code-file '(t nil) nil "-i")
      (delete-file code-file))
    (buffer-string)))
```

I guess this is wrong for you?

**Comment by Will-W** [comment]
If I eval that I get:
```
">>> 
"
```

Which is what I'd expect.

**Comment by jorgenschaefer** [comment]
Yep, me, too. Does `M-: (python-shell-prompt-detect)` work?

**Comment by Will-W** [comment]
No, `M-: (python-shell-prompt-detect)` doesn't work - that's how I was debugging earlier.

I've done a bit more digging and have narrowed it down to "python-shell-calculate-process-environment" in the full function that's causing the problem. Specifically - PYTHONUNBUFFERED. If I set `python-shell-unbuffered` to nil, then everything works properly (I can eval `(python-shell-prompt-detect)` and get the right result).

I realise I haven't included the important bit of context here - I'm running on Windows. I wonder if it's because unbuffered also sets binary mode on the files and so newline handling changes?

**Comment by jorgenschaefer** [comment]
It's possible that Python on Windows detects non-interactivity differently … it works fine here with `python-shell-unbuffered` set.

What confuses me is that the code I gave you does not work. It's pretty much what Emacs runs underneath of `python-shell-prompt-detect`. Does the following also work fine? (Note the use of `process-file` instead of `call-process`)

```Lisp
(let ((code (concat "import sys\n"
                    "print(sys.ps1)")))
  (with-temp-buffer
    (let ((code-file (python-shell--save-temp-file code)))
      (process-file "python" code-file '(t nil) nil "-i")
      (delete-file code-file))
    (buffer-string)))
```

**Comment by Will-W** [comment]
The code snipped provided above **did** work. Eval'ing this:
```
(let ((code (concat "import sys\n"
                    "print(sys.ps1)")))
  (with-temp-buffer  
    (let ((code-file (python-shell--save-temp-file code)))
      (call-process "python" code-file '(t nil) nil "-i")
      (delete-file code-file))
    (buffer-string)))
```

Produced:
```
">>> 
"
```
Your second version with process-file instead of call-process produces exactly the same output.

It's when you add the call to process-environment that it breaks. This:
```
(let* ((process-environment (python-shell-calculate-process-environment))
       (code (concat "import sys\n"
                    "print(sys.ps1)")))
  (with-temp-buffer
    (let ((code-file (python-shell--save-temp-file code)))
      (process-file "python" code-file '(t nil) nil "-i")
      (delete-file code-file))
    (buffer-string)))
```

Produces an empty string as the result. Changing `process-file` to `call-process` makes no difference.

**Comment by jorgenschaefer** [comment]
Ok. I _think_ the only thing `python-shell-calculate-process-environment` adds is the `PYTHONUNBUFFERED` setting you already found. So I presume the following yields an empty string?

```Lisp
(let ((code (concat "import sys\n"
                    "print(sys.ps1)"))
      (process-environment (cons "PYTHONUNBUFFERED=1"
                                 process-environment)))
  (with-temp-buffer
    (let ((code-file (python-shell--save-temp-file code)))
      (call-process "python" code-file '(t nil) nil "-i")
      (delete-file code-file))
    (buffer-string)))
```

If so, this is worth a bug report in Emacs itself – they apparently have to bind `python-shell-unbuffered` to `nil` on windows (or everywhere, it does not seem to have any averse effects on Unix).

**Comment by Will-W** [comment]
Agreed. I'll file the bug now.

**Comment by jorgenschaefer** [comment]
Thank you very much for the excellent debugging work here!

**Comment by zhihuiFan** [comment]
I'm starting to build my dev in docker, and I run into this issue also.  do we have a solution here?

**Comment by jorgenschaefer** [comment]
Hello @zhihuiFan – I am not sure if this is the same error you encounter when running in Docker, as this seems to be Windows-specific, but you can try setting `python-shell-unbuffered` to `nil`.

**Comment by rsuhada** [comment]
I have a similar problem after upgrading to emacs 25.1 - I use tramp to ssh to a remote machine and use a shell there. emacs 24.1 always asks me which shell I want and I give it the path on the remote machine, everything works great. Same setup on 25.1 however gives the no promp detected error.

Any help would be much appreciated, I really depend on being able to execute the code remotely :)

**Comment by fredRos** [comment]
I ran into the same issue as @zhihuiFan  with emacs 24.5 on Ubuntu 16.04 and tramp. I added
```lisp
  (setq python-shell-unbuffered nil)
```
to my `.spacemacs`. Now I can open python files remotely w/o being prompted to set the `python-shell-prompt-regexp`

**Comment by jorgenschaefer** [comment]
`python-shell-unbuffered` prevents `PYTHONUNBUFFERED=1` from being put into the environment. Not sure why that does not work for you.

I am not sure this has anything to do with Elpy – does this happen without Elpy? Which part of Elpy's config affects this?
