### ISSUE TITLE
Emacs can't load pep8

### ISSUE THREAD

**Issue by TomKealy** [jorgenschaefer/elpy#734]
Dear Jorgen,

I get the following error when I open emacs:

Warning (initialization): An error occurred while loading `/home/tk12098/.emacs':

File error: Cannot open load file, python-pep8

I started emacs with the --debug flag and this was my stack trace:

Debugger entered--Lisp error: (error "Can't find a workon home directory, set $WORKON_HOME")
  signal(error ("Can't find a workon home directory, set $WORKON_HOME"))
  error("Can't find a workon home directory, set $WORKON_HOME")
  pyvenv-virtualenv-list()
  (mapcar (lambda (venv) (vector venv (\` (pyvenv-workon (\, venv))) :style (quote radio) :selected (\` (equal pyvenv-virtual-env-name (\, venv))))) (pyvenv-virtualenv-list))
  (lambda (&optional ignored) (mapcar (lambda (venv) (vector venv (\` (pyvenv-workon (\, venv))) :style (quote radio) :selected (\` (equal pyvenv-virtual-env-name (\, venv))))) (pyvenv-virtualenv-list)))(nil)
  (easy-menu-filter-return ((lambda (&optional ignored) (mapcar (lambda (venv) (vector venv (\` (pyvenv-workon ...)) :style (quote radio) :selected (\` (equal pyvenv-virtual-env-name ...)))) (pyvenv-virtualenv-list))) menu) "Workon")
  (lambda (menu) (easy-menu-filter-return ((lambda (&optional ignored) (mapcar (lambda (venv) (vector venv (\` ...) :style (quote radio) :selected (\` ...))) (pyvenv-virtualenv-list))) menu) "Workon"))(nil)
  redisplay_internal\ \(C\ function\)()
  message("%s" "[yas] Prepared just-in-time loading for /home/tk12098/.emacs.d/elpa/elpy-20141031.945/snippets/")
  yas--message(3 "Prepared just-in-time loading for %s" "/home/tk12098/.emacs.d/elpa/elpy-20141031.945/snippets/")
  yas--load-snippet-dirs(nil)
  byte-code("\306\307\310\311 \"\2031)
  yas-reload-all()
  elpy-module-yasnippet(global-init)
  apply(elpy-module-yasnippet global-init nil)
  elpy-modules-run(global-init)
  elpy-modules-global-init()
  elpy-enable()
  eval-buffer(#<buffer  *load*> nil "/home/tk12098/.emacs" nil t)  ; Reading at buffer position 309
  load-with-code-conversion("/home/tk12098/.emacs" "/home/tk12098/.emacs" t t)

I'm sorry I've got no idea how to fix it.

Tom

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> `File error: Cannot open load file, python-pep8`

This is unrelated to Elpy – `python-pep8` is an independent package you installed yourself.

> `Debugger entered--Lisp error: (error "Can't find a workon home directory, set $WORKON_HOME")`

This is from `pyvenv` while trying to create a menu entry for your existing virtualenvs. This looks like an older bug – what version of `pyvenv` are you using? Try upgrading, that might fix it already!

**Comment by TomKealy** [comment]
Dear Jorgen,

I'm not currently using a virtual env - but I've installed pyvenv and upgraded pep8.

The error about $WORKON_HOME has gone away, but I'm still get an error about loading pep8. 

I'll look into it.

Thanks for your help.

Yours

Tom

**Comment by jorgenschaefer** [comment]
Glad it the other problem is gone!

> but I'm still get an error about loading pep8.

Your init file tries to load `python-pep8` which is not installed. This is entirely unrelated to Elpy, though, Elpy does not use an Emacs extension called `python-pep8`. You will either have to to remove that code from your init file, or install that package (whatever it might be).

**Comment by TomKealy** [comment]
Dear Jorgen,

I've just deleted all offending lines from my .emacs, and it works like a charm now. Thanks for your help!

Yours

Tom

**Comment by jorgenschaefer** [comment]
Glad it works now, and enjoy Elpy! :-)
