### ISSUE TITLE
'Required feature pyenv was not provided'

### ISSUE THREAD

**Issue by chechoRP** [jorgenschaefer/elpy#737]
Hi, on emacs boot up I am getting a message:

    'error: Required feature 'pyvenv' was not provided'

If I go through the list of packages installed I can see 'pyvenv'. 
Any clues?

**Comment by chechoRP** [comment]
I will reply to myself. I found the answer at https://github.com/jorgenschaefer/elpy/issues/674 ... an odd one though, you have to remove pyvenv and elpy, and then reinstall elpy.

**Comment by jorgenschaefer** [comment]
That's very strange. Any idea how that could have happened?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this is resolved. Please do not hesitate to open a new issue if you have further problems, and enjoy Elpy!

**Comment by mamcode** [comment]
Thanks @chechoRP You saved my day!

**Comment by francoijs** [comment]
`'error: Required feature 'pyvenv' was not provided'`

Solved the same problem with GNU Emacs 25.1.1 by doing:
M-x package-reinstall pyvenv
M-x package-reinstall elpy
