### ISSUE TITLE
Where to put the test_*.py files? 

### ISSUE THREAD

**Issue by yitang** [jorgenschaefer/elpy#738]
Hi, thanks for writing this awesome package. It helps me to pick up python quicker. 

I have a config.py file in the src folder, and the unite test code is saved in **src/tests/test_config.py**. In the config.py buffer, I press C-c C-t, it runs a unit test and get this output: 

```
Compilation started at Thu Dec 10 21:16:24

python -m unittest discover

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Compilation finished at Thu Dec 10 21:16:24
```

I don't know what elpy did in this case but I am sure it doesn't run the src/tests/test_config.py file. 

If I move the test_config.py to src folder (**src/test_config.py**), then pressing C-c C-t runs the right unit testing.

Is there a configurable variable that is used to tell elpy where the testing folder is? I don't want the src folder is full of test_* files.

**Comment by jorgenschaefer** [comment]
Hello and thanks for the question! Elpy does not do anything particularly special, it just runs `python -m unittest discover` as you can see in the output. This is [documented in the Python docs](https://docs.python.org/2/library/unittest.html#test-discovery). The output should also tell you which directory Elpy runs the command in, so you can use this feature:

> In order to be compatible with test discovery, all of the test files must be modules or packages importable from the top-level directory of the project

I _suspect_ all you are missing is a `src/tests/__init__.py` file to make it a real package.

Does this help?

**Comment by yitang** [comment]
Yes it does! I added the __init__.py file in the src/tests folder and it works now! (although I get loads of errors)

**Comment by yitang** [comment]
It seems elpy use python2 to run the testing although the `elpy-rpc-python-command` variable is set to `python3`.

I added 
```
alisn python="python3" 
```
to `.bashrc` but it don't solve the problem.

**Comment by jorgenschaefer** [comment]
> It seems elpy use python2 to run the testing although the `elpy-rpc-python-command` variable is set to `python3`.

You can adjust `elpy-test-discover-runner-command` to tell Elpy which Python command to run, although I can highly recommend using virtualenvs to make `python` run the correct interpreter for each project! :-)

**Comment by yitang** [comment]
Hi, thanks for your promptly responses. `elpy-test-discover-runner-command` gives solution to my problem, and I'd quite happy to use it for now. I'd definitely looking into the `virtualenvs` when I free up a bit.

Thanks.
