### ISSUE TITLE
Does elpy support jump to error in python shell?

### ISSUE THREAD

**Issue by nbecker** [jorgenschaefer/elpy#740]
I'm enjoying elpy, but one thing I'm missing.  I'm working on a python script in a buffer.  I start the interpreter with C-c C-z.  Then I run the script with C-c C-c.  There is a traceback.  But I don't see a way to jump to the line that caused the error.

**Comment by ChillarAnand** [comment]
You can switch back and forth between scipt buffer and python process  buffer(which has  traceback) using `C-c C-z`.

When you  are in process buffer with traceback, lines  which as path and line number will be highlighted. You can  use mouse and click on or go to that line and press enter,  it  should take you to corresponding file and  line  number.

Demo: https://youtu.be/Y5VhOAa9sqM

For this to work, you should use normal python  shell not ipython. If you have this line

       (elpy-use-ipython)

in your  config,  please  remove  it and try again.

**Comment by jorgenschaefer** [comment]
@nbecker, you should be able to hit RET on the lines that start with `File ...` - does that not work?

**Comment by nbecker** [comment]
I think it only works with python, not with ipython?

On Tue, Dec 15, 2015 at 8:32 AM, Jorgen Schäfer <notifications@github.com>
wrote:

> @nbecker <https://github.com/nbecker>, you should be able to hit RET on
> the lines that start with File ... - does that not work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jorgenschaefer/elpy/issues/740#issuecomment-164765520>
> .
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by jorgenschaefer** [comment]
Hm. Possibly, yes – I do not use ipython. Does ipython use a different traceback format than standard python? If so, `python-shell-compilation-regexp-alist` might need adjusting. How does a traceback in ipython look like?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this problem is resolved. Please do not hesitate to re-open this issue or create a new one if there are further problems, and enjoy Elpy.
