### ISSUE TITLE
need to set PYTHONPATH on activate

### ISSUE THREAD

**Issue by nbecker** [jorgenschaefer/elpy#742]
Is there a good way I can set PYTHONPATH from my python shell when I activate a virtualenv?

Within my virtualenv, I have a directory of utilities I need PYTHONPATH set to.

**Comment by jorgenschaefer** [comment]
I usually just use virtualenvwrapper´s `add2virtualenv`, though I also have set up a postactivate script to source and `.env` file in my project homes, where you can set environment variables.

Does this help?

**Comment by nbecker** [comment]
Not sure virtualenvwrapper works with anaconda.  I found out about .pth
files - that does it.

On Tue, Dec 15, 2015 at 8:36 AM, Jorgen Schäfer <notifications@github.com>
wrote:

> I usually just use virtualenvwrapper´s add2virtualenv, though I also have
> set up a postactivate script to source and .env file in my project homes,
> where you can set environment variables.
>
> Does this help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jorgenschaefer/elpy/issues/742#issuecomment-164766685>
> .
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by jorgenschaefer** [comment]
Ah, not sure about anaconda, either. Glad it works now, though! Enjoy Elpy :-)
