### ISSUE TITLE
Syntax checker runs after autosave

### ISSUE THREAD

**Issue by gambyte** [jorgenschaefer/elpy#743]
Currently the syntax checker runs whenever emacs autosaves the python file I am editing. This puts syntax error marks all over what I am currently editing for no reason; I know it is not correct because I haven't finished typing it. I would like to be able to stop the syntax checker for autosaves, and only run when I initiate the save. Is there a way of doing this of which I am unaware?

**Comment by jorgenschaefer** [comment]
Elpy uses flymake and actually already configures it not to run until after a save - by default, it runs every few seconds, which I found to be highly annoying for exactly the same reasons as you do here! :-)

Try and set `flymake-no-changes-timeout` to a larger value in `elpy-mode-hook`, maybe something like 500 or so?
