### ISSUE TITLE
importmagic orders relative imports before third-party imports

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#746]
Here [it is mentioned](https://github.com/jorgenschaefer/elpy/issues/493#issuecomment-115305032), that importmagic should  sort imports.

Here is a test file

```python
import os
from .forms import Foo
from django.contrib.auth.decorators import login_required


os.path
Foo()
login_required
```

When i run import fixup, it changes to 

```python
import os

from .forms import Foo

from django.contrib.auth.decorators import login_required


os.path
Foo()
login_required
```

But it should be 

```python
import os

from django.contrib.auth.decorators import login_required

from .forms import Foo


os.path
Foo()
login_required
```

However,  isort is correctly ordering in this case.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is a bug in importmagic and should be fixed there. Could you report this upstream?

**Comment by ChillarAnand** [comment]
I have already reported it upstream, forgot to mention it here https://github.com/alecthomas/importmagic/issues/28

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by ChillarAnand** [comment]
Upstream issue https://github.com/alecthomas/importmagic/issues/29

**Comment by jonmoore** [comment]
I think this can be closed here - it has been closed upstream.
