### ISSUE TITLE
Add a custom option to disable import reordering with importmagic

### ISSUE THREAD

**Issue by el-ethan** [jorgenschaefer/elpy#747]
Is there any way to configure elpy/importmagic (outside of the modules where the importing is being done) to not rearrange but simply add new imports, or at least decide in some way how they get rearranged?

`elpy-importmagic-add-import` is extremely useful, but my issue with it is that it rearranges pre-existing imports (in some cases, seemingly in a way that is not pep-8 compliant as mentioned in issue #746 ). 

This makes the command unusable to me when coding for work because each time I add a new import, multiple changes show up in version control from the rearranged imports which adds unnecessary clutter to our code reviews, and the inevitable question from my manager "Why did you rearrange the imports?" Also, there are some cases in our project where, as mentioned in issue #493, things will break if not imported in certain order. 

I have recently switched over completely from PyCharm to Emacs for writing Python, and this would not have been possible without Elpy, but auto-import is one area where I have not been able to match PyCharm's functionality (Pycharm will not rearrange existing imports).

 I have asked about this on  emacs.stackexchange.com, but since I haven't gotten any response, I am assuming it is not currently an option. I am sorry if this is not the proper way to request/inquire about such a feature. If there is a better way to go about this, please let me know for future reference. Thank you.

**Comment by whirm** [comment]
@el-ethan do you know about `# importmagic: manage`? It should do what you want, but in some cases importmagic seems to ignore it.

**Comment by el-ethan** [comment]
Thanks @whirm. Yes, I do know about that from the discussion in issue #493. Unfortunately, this doesn't work in my situation, because it means having to always check the top of a module to make sure I have used that comment, then going back where I was to do the auto-import (taking about as much time as it would to add the import manually). Also, it adds cruft to our code that is only useful for me and no one else on my team (everyone else uses PyCharm). This is why I would like something that can be configured outside of whatever module I am working on. Thank you for the suggestion though!

**Comment by jorgenschaefer** [comment]
Yes, I can totally see why disabling re-arranging imports would be a great feature. I'll see if importmagic supports setting the "manage" thing via the API instead of in the file.

**Comment by gopar** [comment]
Closing. importmagic has been removed from elpy
