### ISSUE TITLE
Change squiggly line "font-face" to different color rather than squiggly line?

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#749]
Is it possible to customize how warnings/errors look like?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Does customizing the faces `flymake-errline` and `flymake-warnline` do what you want?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this problem is resolved. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
