### ISSUE TITLE
Document usage of elpy-nav-forward-block etc. better

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#753]
So I'm wondering why `elpy-nav-forward-block` does not fallback to forward-paragraph? 

It's very frustrating when I want to "scroll" through my file, but I get stuck.

I understand that it is was probably a choice, but perhaps it would make sense to fall back?

If people would like it, I could add the feature.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the idea! This is interesting – I actually use `elpy-nav-forward-block` regularly to stay within a class or function, so I find the current behavior very useful. Also, falling back to forward-paragraph would break the feature that `elpy-nav-backward-block` would undo a prior forward-block call.

Out of curiosity, why are you not using forward/backward paragraph to begin with? Or just the normal scrolling functions?

I could see forward/backward-block to display a message when they can't move further, and fall back to a different command on a second invocation (a bit like `C-s` does at the end of the buffer). But is forward-paragraph really the best for this, then? Wouldn't "move forward to the next line with the same indentation as the current one" make more sense?

**Comment by my8bird** [comment]
I think this might be the bug/issue I am wrestling with currently.  I just added elpy to my emacs setup and have been loving it.  I had to turn some of the `flake8` checks off do to my companies coding standard but that was fine.

My issue is that `C-<up>` and `C-<down>` are doing nothing for me.  The cursors position does not move at all.  When I disable elpy and fallback on regular python mode those commands will jump the cursor up and down the file by blocks.

I can make a different ticket if this is the wrong one,

**Comment by jorgenschaefer** [comment]
In Elpy, <C-up> and <C-down> will move to the previous/next line with the indentation where point is. Can you go to column 0 and see whether they indeed do not do anything? They should move between `class` and `import` lines (or `def` lines for global functions). `<C-right>` and `<C-left>` will move by indentation, so you can be in column 0, move to a class of your interest, use `<C-right>`, and use `<C-down>` to move between methods of this class. The movement will not take you out of the current class.

If this is not what you want, set the keys to `nil` in `elpy-mode-map`.

**Comment by my8bird** [comment]
Thanks that worked perfectly.

**Comment by jorgenschaefer** [comment]
Great to hear! This probably should be in the documentation somewhere …
