### ISSUE TITLE
Add config option to disable backend error displays entirely

### ISSUE THREAD

**Issue by asvetlov** [jorgenschaefer/elpy#763]
I use python 3.4/3.5 for my projects (asyncio based).
Jedi raises exception on editing buffer with constructions like `yield from`, `async def`, `await` etc.

elpy reflects these errors by raising a buffer with bug report containing comprehensive report about the bug, but it's very annoying.

I use layout with two vertically separated buffers. As result the bug report appears in other (nonactive) buffer and focus is switched to it.

Is there an option to disable the annoying buffer flicker in case of Jedi errors?
I can live with partial autocomplete support.

Sorry, my knowledge of emacs list is close to zero and I have no time/intention to *contribute* into elpy and jedi. I just want to *use elpy with pleasure*.
So I just politely asking for elpy option which will make my life much easier.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is a good idea – until then, try setting `elpy-rpc-error-timeout` to a large value and see if that helps?

**Comment by asvetlov** [comment]
Yes, increasing `elpy-rpc-error-timeout` helps.
Thanks for making quick fix #764
