### ISSUE TITLE
Add elpy-goto-definition-other-window

### ISSUE THREAD

**Issue by maximvl** [jorgenschaefer/elpy#767]
Hi, It would be really helpful to have analogue to `elpy-goto-definition` which would open definition in another window to read code side-by-side. For now one have to go to definition, then open another window, switch to it and then switch back to the initial buffer.

**Comment by jorgenschaefer** [comment]
Nice idea, thank you!

**Comment by emacsway** [comment]
There is some other idea, allow to make choice in config for user:

(advise-tag-function find-tag)
(advise-tag-function find-tag-other-window)
(advise-tag-function find-tag-other-frame)

https://raw.githubusercontent.com/sigma/dotfiles/master/_emacs.d/lib/sure-tags.el
