### ISSUE TITLE
run the test for current script only

### ISSUE THREAD

**Issue by yitang** [jorgenschaefer/elpy#770]
Hello, 

I wonder if there's a way to run the test_x.py only when I hit 'C-c C-t' in the x.py buffer? Currently, it runs all the tests in the tests/ folder.

Thanks.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question/suggestion!

There is currently no way of doing that. Implementing such a feature would require a lot of guesswork as to where that test file might be located to determine which file to run. I'm not sure if that's worth the hassle.

I'm open for suggestions on this, though :-)

**Comment by yitang** [comment]
this feature was implemented a long time ago.
