### ISSUE TITLE
Return correct form of Super() depending on Python version

### ISSUE THREAD

**Issue by gopar** [jorgenschaefer/elpy#771]
So in Python2 when you use `super`, it would be used like the following:
```python
super(ClassName, self).some_method()
```

But in Python3 you can simply do:
```python
super().some_method()
```
Well that's as far as I've seen. If I'm wrong feel free to correct me and close the issue.

But anyways, I modified the [func](https://github.com/jorgenschaefer/elpy/blob/fd1716883c36208078df30a578ff32b872751969/snippets/python-mode/.yas-setup.el#L49) responsible for helping the yas-snippet. Forgive my emacs lisp fu, but this is the general idea and it seems to work for me.
```lisp
(defun elpy-snippet-super-form ()
  "Return (Class, first-arg).method" 
  (let* ((defun-info (elpy-snippet-current-method-and-args))
         (class (nth 0 defun-info))
         (method (nth 1 defun-info))
         (args (nth 2 defun-info))
         (first-arg (nth 0 args))
         ;; Get the python version that is given when you run "python -v" in terminal. Either 2 or 3
         (py-version-num (substring (nth 1 (split-string (shell-command-to-string (concat elpy-rpc-python-command " -V")))) 0 1)))
    (if (string-match py-version-num "2")
        (format "(%s, %s).%s" class first-arg method)
      (format "().%s" method))))
```
If this seems like a good idea, maybe we could create a PR for it? Well let me know. Thanks for the work guys :)

**Comment by jorgenschaefer** [comment]
Sounds good to me, thanks for the suggestion!

Would it be worthwhile to add an RPC call to Elpy to get the Python version for this?

**Comment by gopar** [comment]
@jorgenschaefer not sure if I'm the right person to be asking :p 

Would you want a func just for getting the py version and then calling it into the other one? like this:

```lisp
(defun elpy-get-python-version ()
    "Return the python version"
  (nth 1 (split-string (shell-command-to-string (concat elpy-rpc-python-command " -V")))))

(defun elpy-snippet-super-form ()
  "Return (Class, first-arg).method" 
  (let* ((defun-info (elpy-snippet-current-method-and-args))
         (class (nth 0 defun-info))
         (method (nth 1 defun-info))
         (args (nth 2 defun-info))
         (first-arg (nth 0 args))
         (py-version-num (substring (elpy-get-python-version) 0 1)))
    (if (string-match py-version-num "2")
        (format "(%s, %s).%s" class first-arg method)
      (format "().%s" method))))
```

or just as is from the original version?

**Comment by jorgenschaefer** [comment]
What I mean is that Elpy uses an RPC interface to talk to the running RPC process. There is no need to start a shell command, you can just ask the already-running Python process. I wonder if it's worthwhile to add the corresponding code to check the Python (major) version or not.

I'm fine with your initial code for now, no need to split this out for now. :-)

**Comment by gopar** [comment]
Ahh I gotcha. 

So do you want me to create a PR with the first implementation?

**Comment by jorgenschaefer** [comment]
> So do you want me to create a PR with the first implementation?

Yes please. Though you might want to use a more robust check – how about `python -c 'import sys ; print(sys.version_info.major)'`?

**Comment by gopar** [comment]
Closing since PR was already merged.
