### ISSUE TITLE
Switching between python 2 and python 3?

### ISSUE THREAD

**Issue by souvik1997** [jorgenschaefer/elpy#775]
Is there some way to automatically switch between python 2 and python 3 depending on the file being edited? By switching I mean updating the values of `elpy-rpc-backend` and `python-shell-interpreter`.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! You can use [file-local](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html) or [directory-local](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) variables to set those. Though I would suggest using virtualenvs and just always using `python` as the interpreter. :-)

Does this answer your question?

**Comment by souvik1997** [comment]
Yes, thank you!
