### ISSUE TITLE
syntax checker not found in virtualenv

### ISSUE THREAD

**Issue by JayDeeDev** [jorgenschaefer/elpy#789]
Hi - I have been very happily using elpy for many months. Recently moved to a new machine (details at end).
I enable elpy, use my virtual env, and run elpy-config - which reports:
_Syntax checker....: Not found (install pyflakes, pylint or something else)_
It offers to run "pip install flake8" for me. I do so:
_Requirement already satisfied (use --upgrade to upgrade): flake8 in ./.virtualenvs/p34/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyflakes<1.1,>=0.8.1 in ./.virtualenvs/p34/lib/python3.4/site-packages (from flake8)
Requirement already satisfied (use --upgrade to upgrade): pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 in ./.virtualenvs/p34/lib/python3.4/site-packages (from flake8)
Requirement already satisfied (use --upgrade to upgrade): mccabe<0.4,>=0.2.1 in ./.virtualenvs/p34/lib/python3.4/site-packages (from flake8)_

but still reports it missing.

Question: why doesn't elpy see that flake8 is already installed in the virtualenv? It finds other things:
_Virtualenv........: p34 (/home/jeffrey/.virtualenvs/p34)
RPC Python........: 3.4.3 (/home/jeffrey/.virtualenvs/p34/bin/python)
Interactive Python: ipython (/home/jeffrey/.virtualenvs/p34/bin/ipython)
Emacs.............: 25.1.50.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3_

My current workaround is to start emacs from inside a shell that has the virtual environment activated, then elpy finds syntax checker:
_Syntax checker....: flake8 (/home/jeffrey/.virtualenvs/p34/bin/flake8)_

Elpy version 1.10.0
GNU Emacs version 25.1.50.1
Ubuntu 15.10

**Comment by jorgenschaefer** [comment]
Hello! What's the value of `python-check-command` when this fails?

**Comment by JayDeeDev** [comment]
describe-variable reports:
Its value is "install pyflakes, pylint or something else"
Original value was 
"/home/jeffrey/.virtualenvs/p34/bin/pyflakes"

**Comment by jorgenschaefer** [comment]
That's the problem … Elpy does not set `python-check-command` if it can't find `flake8`, so it retains the default value (this is suboptimal, Elpy should be smarter). You can fix this by adding `(setq python-check-command "flake8")` to your init file. Does that solve the problem?

**Comment by JayDeeDev** [comment]
Yes, that solves the problem, danke schon!

**Comment by jorgenschaefer** [comment]
Gerne! Glad it works now. Please do not hesitate to open a new issue if you have any further problems, and enjoy Elpy :-)

**Comment by JayDeeDev** [comment]
Added to my init file:
(use-package elpy
  :config
  (setq python-check-command "flake8"))
