### ISSUE TITLE
C-M-x (python-shell-send-defun) not working in elpy

### ISSUE THREAD

**Issue by teymuri** [jorgenschaefer/elpy#793]
The `C-M-x` does not work allways for evaluating single statements. As a conceret example:

```
def divi(a, b):
try:
    print a / b
except ZeroDivisionError:
    print "oooops! I don't like zero!"
```

Now i want to call the function and see the result in the shell. I go to the line where the function is called and do `C-M-x`:

`divi(8, 4)`
nothing happens, i see in the mini buffer: 

> Sent: def divi(a,b):.... 

So i mostly end up sending the whole buffer to the shell by `C-c C-c `which of course works fine. What am i doing wrong?

**Comment by jorgenschaefer** [comment]
Hello! In Emacs' Python mode, `C-M-x` will send the current _function definition_, not the current top-level statement. So when you have the following piece of code:

```Python
def foo(a):
    return a

foo("Hi")
```

And hit `C-M-x` on the last line, Emacs will send the function definition of `def foo ...`, not the function call. Elpy has a function to send the current statement, by default bound to `<C-return>` – does that do what you want here?

**Comment by teymuri** [comment]
Yes! Thats exactly what i needed! 
Thank you many times for your great support.

**Comment by jorgenschaefer** [comment]
Glad it works! You are very welcome, and enjoy Elpy :-)
