### ISSUE TITLE
Command not found: flake8

### ISSUE THREAD

**Issue by gregnewman** [jorgenschaefer/elpy#795]
I'm using pyenv to manage multiple python installations for my virtualenv and running into and issue with flake8.

When running `elpy-check` I get the error `zsh:1: command not found: flake8`

I have flake8 installed both globally and in my virtualenv and have my virtualenv activated.

Here's the output of `elpy-config`

```
Elpy Configuration

Virtualenv........:  (/Users/greg/code/eldarion-courses/eldoc/courses/)
RPC Python........: 3.5.1 (/Users/greg/.pyenv/shims/python)
Interactive Python: python (/Users/greg/.pyenv/shims/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/Users/greg/.pyenv/shims/flake8)
```

for some reason, and I can't recall now why, I had to add this to my init.  I know it was when I switched to using pyenv.
`(add-to-list 'exec-path "~/.pyenv/shims")`

Yet it still says it can't find flake8.

**Comment by gregnewman** [comment]
UPDATE:

I added the following to my init and it resolved the problem.  However, I'd like to understand _why_ i needed to do that when `elpy-config` had the exact same path.

`(setq python-check-command (expand-file-name "/Users/greg/.pyenv/shims/flake8"))`

**Comment by jorgenschaefer** [comment]
Hello! This sounds vaguely familiar, but I can't find the other issue right now. The only thing I can think of that would explain the behavior is that your zsh rc files change `PATH`. Syntax checks are run using `compile`, which uses your shell to run a command, while Elpy checks for the presence of `flake8` without the shell.

Can you try `M-x compile RET echo $PATH RET` and check whether `~/.pyenv/shims` is in there?

**Comment by gregnewman** [comment]
I see that problem now

```
echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin
```

Yet my `.zshrc` has
```
export PATH=~/.pyenv/shims:/usr/local/bin:/usr/local/sbin:$PATH
```

**Comment by gregnewman** [comment]
Using `exec-path-from-shell` package fixes my path issues with zshrc

**Comment by jorgenschaefer** [comment]
Hm. Probably `exec-path` not being passed on to subprocesses, because `PATH` differs. Or something?

**Comment by gregnewman** [comment]
well, in doing research it seems zshrc is a problem for emacs gui instead of shell.  I've confirmed the above package does fix the issue and also allowed me to clean up my init some.  Hopefully this helps someone else too.

**Comment by phamthang** [comment]
I got the same problem, this solution also worked for me . Thanks you so much.

**Comment by gopar** [comment]
Closing since solved
