### ISSUE TITLE
Elpy does not recognize Jedi, Rope, Importmagic, autopep8, Yapf, Syntax checker

### ISSUE THREAD

**Issue by CSRaghunandan** [jorgenschaefer/elpy#799]
Hello,

I just installed emacs on OSx el capitan and trying to set up to work on python. I installed the latest version of python2.7 and python3.5 using homebrew. Installed the required packages for Elpy using pip install command, but Elpy is not recognising the installed packages.
<img width="570" alt="screen shot 2016-02-05 at 9 32 27 pm" src="https://cloud.githubusercontent.com/assets/5226809/12851530/70a7ad90-cc50-11e5-897d-27e3dd6b0d16.png">

Is there any way I could manually set up the path for the required Elpy packages, if not is there any other way I could fix this issue? Where could have I possibly gone wrong with setting up Elpy ? 
The packages are in the location :- /usr/local/lib/python2.7/site-packages/

Thanks

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! Are you sure the packages you installed are for `/usr/bin/python`? If not, could you set `elpy-rpc-python-command` (and likely `python-shell-interpreter`) to the actual Python interpreter you want to use? Or adjust `PATH`/`exec-path` accordingly?

**Comment by CSRaghunandan** [comment]
I installed  the packages using "pip install command". 
/usr/bin/python brings up the homebrew python2.7 (homebrew).  So I guess they are for the same python interpreter ? (if not, how can I make sure? really sorry, I am relatively a rookie to programming).

I guess the problem is arising due to the fact i've two interpreters for python2.7 (one the OSx built in version, the other installed view homebrew).

**Comment by jorgenschaefer** [comment]
You have to set the two variables to the Python intepreter that allows you to do `import jedi` :-)

**Comment by CSRaghunandan** [comment]
Thanks a lot for the info :) much appreciated. 
Changed the default interpreter to homebrew and everything is working fine, except for Syntax checker. I have flakes8 (pyflakes) installed using pip yet Elpy is not recognising it. 
Is there any workarounds for this ?

**Comment by jorgenschaefer** [comment]
Elpy tries to run the `flake8` program to do syntax checks. Make sure it is in your `PATH` or set `python-check-command` to the full path.

**Comment by CSRaghunandan** [comment]
got it to work :) Thanks a lot for the replies. 

Regards

**Comment by jorgenschaefer** [comment]
You're welcome, and glad it works now. Enjoy Elpy! :-)
