### ISSUE TITLE
Occur Definitions for Class only

### ISSUE THREAD

**Issue by gopar** [jorgenschaefer/elpy#800]
I find myself just looking for class definitions on files often. I use `elpy-occur-definitions` to look at the overview of the file but method/function definitions are mixed in too. My personal opinion is to maybe have another function that just displays class defs (call it `elpy-occur-definitions-class` or something?).

The only thing that would have to be changed is the regex of `elpy-occur-definitions`. I can submit a PR, if you think it's worth having.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion! The main reason `elpy-occur-definitions` is particularly useful is because the regexp is non-trivial. Is your use case so frequent that a new command is a particular bonus over `M-x occur RET ^class RET`?

(I wish Emacs had good folding support …)

**Comment by gopar** [comment]
For me at least, I call it 2x as much as just the regular `elpy-occur-definitions`. I have a func in my config that is basically the same as `elpy-occur-definitions` except for the regex of course.

Well this is just my preference, and maybe others don't have this "problem". But yeah, a single keybinding is nice instead of typing the whole thing out.

**Comment by emacsway-qarea** [comment]
@gopar, try also [Speedbar](https://www.gnu.org/software/emacs/manual/html_node/emacs/Speedbar.html) or install SrSpeedbar to browse classes.

**Comment by gopar** [comment]
@emacsway-qarea ohhh nice. I didn't know about speedbar (I've only heard of it, never bothered to check it out)
Thanks.

**Comment by jorgenschaefer** [comment]
I'm not opposed to such a change, but I don't think it warrants a default key binding. Thanks for the suggestion in any case! :-)
