### ISSUE TITLE
Set PYTHONPATH variable

### ISSUE THREAD

**Issue by maximvl** [jorgenschaefer/elpy#801]
Hello, I want to set `PYTHONPATH` to allow elpy search definitions in external directories, but I haven't found any docs about this. Is it possible to add search paths now?

**Comment by emacsway-qarea** [comment]
use (setenv "PATH" ...) and (setq exec-path ...). See also [.dir-locals.el](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html). See [example](https://bitbucket.org/emacsway/.emacs.d/src/ab7f8eb70f3ae24f683a39aadca75b8395f3b42a/init.el?fileviewer=file-view-default#init.el-14).

**Comment by maximvl** [comment]
@emacsway-qarea very nice, thank you!

**Comment by jorgenschaefer** [comment]
Also note that if you use virtualenvwrapper, you can use that normally – e.g. you can use the [postactivate](https://virtualenvwrapper.readthedocs.org/en/latest/scripts.html#postactivate) hook to set environment variables, or you can use `add2virtualenv` directly.

**Comment by mambolevis** [comment]
`Also note that if you use virtualenvwrapper, you can use that normally – e.g. you can use the postactivate hook to set environment variables, or you can use add2virtualenv directly.` 

In my espy-config there is one thing that I am not using : **Virtualenv**.

Virtualenv........: None
RPC Python........: 3.5.2 (c:/Data/Anaconda3/envs/py35/pythonw.exe)
Interactive Python: ipython (c:/Data/Anaconda3/envs/py35/Scripts/ipython.exe)
Emacs.............: 25.1.1
Elpy..............: 1.14.1
Jedi..............: 0.10.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.7
Autopep8..........: 1.3.1
Yapf..............: 0.16.0
Syntax checker....: flake8.exe (c:/Data/Anaconda3/envs/py35/Scripts/flake8.exe)

Questions:
1) How can I setup the elpy Virtulenv option?
2) Can you give an example with the environment variables configuration PYTHONPATH to setup a python module or project?

Thanks,

**Comment by jorgenschaefer** [comment]
> How can I setup the elpy Virtulenv option?

`M-x pyvenv-activate` or `M-x pyvenv-workon`

> Can you give an example with the environment variables configuration PYTHONPATH to setup a python module or project?

Ideally, you should not need to set `PYTHONPATH` at all when using virtualenvs.
