### ISSUE TITLE
Single jedi / importmagic / yapf / autopep8 installation

### ISSUE THREAD

**Issue by rakanalh** [jorgenschaefer/elpy#804]
Hello,

Do i have to install these packages on every project's virtualenv i create? or is it possible to just install it once globally and use the same packages for all my projects?

Thanks!

**Comment by jorgenschaefer** [comment]
They have to be importable to the RPC Python process. Python allows this via a number of ways.

- Install them in each virtualenv (you install mocking tools, test runners, etc. in each, too)
- Install them user-globally or site-globally and enable site packages in your virtualenvs
- Install them in a single virtualenv and use virtualenvwrapper's `add2virtualenv` or `.pth` files to include that single virtualenv in each other virtualenv
- Install them in a single virtualenv and use `PYTHONPATH` to make them available

**Comment by rakanalh** [comment]
Excellent! Thanks for the suggestions.
