### ISSUE TITLE
Auto-complete UI issue

### ISSUE THREAD

**Issue by rakanalh** [jorgenschaefer/elpy#813]
When auto complete is triggered in elpy, i think both company and auto-complete are competing to show completion options:
![Imgur](http://i.imgur.com/iQcpRSw.png)

I've checked that elpy is using company for auto complete... is there a way to disable auto-complete when using elpy?

**Comment by rakanalh** [comment]
I was able to fix this using:
```
(defadvice auto-complete-mode (around disable-auto-complete-for-python)
  (unless (eq major-mode 'python-mode) ad-do-it))

(ad-activate 'auto-complete-mode)
```

Which will disable auto-complete for python-mode

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! An easier approach would be to remove `python-mode` from `ac-modes` – e.g. `(setq ac-modes (delq 'python-mode ac-modes))`. That variable holds the list of modes in which `global-auto-complete-mode` enables auto-complete.

I hope this helps, and enjoy Elpy! :-)

**Comment by rakanalh** [comment]
Thank you for the much easier suggestion!

**Comment by humitos** [comment]
I had the same problem, and the `setq ac-modes` was a solution. Thanks!

I'm wondering why do you prefer `company-mode` instead of `auto-complete`. I found `ac` too much complete than `company`, don't you?

Maybe I'm missing something on my configuration or I'm not seeing the power of company. Can you explain it to me?

**Comment by jorgenschaefer** [comment]
> Maybe I'm missing something on my configuration or I'm not seeing the power of company. Can you explain it to me?

We used auto-complete in the past. Reasons for changing are explained e.g. [here](https://github.com/jorgenschaefer/elpy/issues/268#issuecomment-47425048).
