### ISSUE TITLE
newb installation question

### ISSUE THREAD

**Issue by wonbyte** [jorgenschaefer/elpy#815]
I have followed the directions on the github site and everything installs correctly. Where I am having issues is when I run elpy-config I see:

Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: Not found (0.9.0 available)
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (1.2.2 available)
Yapf..............: Not found (0.6.2 available)
Syntax checker....: Not found (pyflakes)

I have all of these installed via pip3. I installed python3 using home-brew so I figure I just need to tell emacs where these files are but i'm not sure how.

I appreciate any help!

**Comment by ChillarAnand** [comment]
> RPC Python........: 2.7.10 (/usr/bin/python)

You are using python 2 rpc.

```
(setq elpy-rpc-python-command "python3")
```
Add this to your elpy config and restart to use python 3.

**Comment by wonbyte** [comment]
Added it and I get "elder error: (error can't find Python command, configure `elpy-rpc-python-command)

I have (setq elpy-rpc-python-command "python3") in my init.el

**Comment by wonbyte** [comment]
did the following:

(defun prelude-python-mode-defaults ()
    (elpy-mode)
    (setq elpy-rpc-python-command "python3")
)

It seems to work now expect it can't find 'pyflakes'. I have it installed in the same location as all the other py packages it is finding. Any ideas?

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/local/Cellar/python3/3.5.1/bin/python3)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 1.2.2
Yapf..............: 0.6.2
Syntax checker....: Not found (pyflakes)

**Comment by wonbyte** [comment]
so I went ahead and set everything up in a pyvenv. I then install all the required pip packages into the venv.  When I activate it via emacs I see

Output from the virtualenvwrapper hook post_activate:

Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!
     PYTHONPATH is currently: "/usr/local/lib/python3.5/site-packages"
     You should `unset PYTHONPATH` to fix this.

I also see this from elpy-config:

Virtualenv........:  (/Users/gps/src/python/test/blah/)
RPC Python........: 3.5.1 (/usr/local/Cellar/python3/3.5.1/bin/python3)
Interactive Python: python (/Users/gps/src/python/test/blah/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: Not found (0.9.0 available)
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (1.2.2 available)
Yapf..............: Not found (0.6.2 available)
Syntax checker....: pyflakes (/Users/gps/src/python/test/blah/bin/pyflakes)

So it found pyflakes and ipython from my venv but not the others. Any thoughts?

**Comment by wonbyte** [comment]
removed

(defun prelude-python-mode-defaults ()
(elpy-mode)
(setq elpy-rpc-python-command "python3")
)

and it all works.

Thanks!

**Comment by jorgenschaefer** [comment]
Heh. :-) Glad you found a way to make this work, and enjoy Elpy!
