### ISSUE TITLE
elpy-goto-definition across different buffer

### ISSUE THREAD

**Issue by petrux** [jorgenschaefer/elpy#816]
Here is my feature request. When I type `M-.` over a symbol and the file in which it is defined is already open in another visible buffer¸ I would like to get there without opening  the file in the current buffer. So, would it be possible to add such feature with a different function and a different key binding? (e.g. `M-S-.` as the default key binding)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion! Does `C-x 4 M-.` do what you want? (That is `elpy-goto-definition-other-window`, you can of course bind it to whatever key you like)

**Comment by petrux** [comment]
I have updated elpy and, yes, it works. At this point, should this feature be documented [here](http://elpy.readthedocs.org/en/latest/ide.html#navigation)? -- let me know, I could do that. :-)

**Comment by jorgenschaefer** [comment]
Oh, that would be awesome!

**Comment by petrux** [comment]
I'll try to do it today.

**Comment by petrux** [comment]
Done and pull request issued.

**Comment by jorgenschaefer** [comment]
Thank you very much! :-)
