### ISSUE TITLE
Importmagic does not respect PEP8 import ordering

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#822]
The new tests in cf4b857 show that importmagic does not respect PEP8 ordering of imports, but instead mixes up all types of imports (local, third-party, standard library) into one list:

```
import logging
import time
from mymod import AnUncommonName
```

instead of

```
import logging
import time

from mymod import AnUncommonName
```

and

```
import logging
import mymod
import time
```

instead of

```
import logging
import time

import mymod
```

That's a regression to earlier behavior.

**Comment by alecthomas** [comment]
@jorgenschaefer I'm unable to replicate this as a regression, in that the classification of package location in 0.1.5 seem to be identical to 0.1.3. I do note that it misclassifies some packages, but I have pushed 0.1.7 that will (hopefully) fix that.

The basic issue is that it's difficult to know whether a package is 3rd party or local. I've added some heuristics to hopefully fix this.

**Comment by jorgenschaefer** [comment]
@alecthomas Thank you very much for your work! :-)
