### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by jmercouris** [jorgenschaefer/elpy#826]
Really Doesn't like my piece of code, crashes on it every time when I'm writing

journal_file.write(next_ ...)

[debug.txt](https://github.com/jorgenschaefer/elpy/files/169505/debug.txt)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! I'm afraid that `debug.txt` link is not leading anywhere – what output do you get from Elpy when it crashes? :-)

**Comment by jmercouris** [comment]
Hey, I'm sorry that's all the details I could get, it would just open up in
a new buffer and had that output, is there some log that I can check? If I
recreate the crash, what should I do?

**Comment by jorgenschaefer** [comment]
Usually, when Elpy encounters a problem, it pops up a debug window with more information.

What exactly do you mean with "crashes"? Does your Emacs actually crash, as in, terminate?

**Comment by jmercouris** [comment]
Emacs did not terminate. What I did when it crashed was open up a scratch
buffer, copy all the text from the debug window and yank it into the
scratch buffer, that is what I attached. Is there another log I should look
for, or a different way to pull the data?

**Comment by jorgenschaefer** [comment]
Ah, there we go … when I first tried to download that debug.txt, the link was broken.

```
Traceback (most recent call last):
  File "/Users/jmercouris/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", 
line 100, in call_rope
    **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.
7/site-packages/rope/contrib/codeassist.py", line 101, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.
7/site-packages/rope/contrib/codeassist.py", line 569, in get_calltip
    result = self._get_function_signature(pyobject, add_module=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.
7/site-packages/rope/contrib/codeassist.py", line 619, in _get_function_signatur
e
    return '%s(%s)' % (location + pyfunction.get_name(),
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

This is a bug in Rope I'm afraid. As a workaround, you can either set `elpy-disable-backend-error-display` to `t` to avoid this display, or try using Jedi instead of Rope. I'll report this upstream.

Thanks for the report!

**Comment by jorgenschaefer** [comment]
Actually, looks like this is the same error as #805 – I'll close this issue so we can keep the discussion in one spot. In any case, it was good to have this report. Thank you!

**Comment by jmercouris** [comment]
No problem! Good luck!
