### ISSUE TITLE
Remove flymake from elpy modules

### ISSUE THREAD

**Issue by wonbyte** [jorgenschaefer/elpy#828]
I am trying to remove flymake from elpy-modules and I am using the following lisp

`(with-eval-after-load 'elpy-mode
  (remove-hook 'elpy-modules 'elpy-module-flymake)
  (add-hook 'elpy-mode-hook 'flycheck-mode))`

however,
when I check the value of elpy-modules it displays the following

`(elpy-module-sane-defaults elpy-module-company elpy-module-eldoc elpy-module-flymake elpy-module-highlight-indentation elpy-module-pyvenv elpy-module-yasnippet)`

any ideas what I am missing?

I don't enable elpy until i'm in python-mode so

`(add-hook 'python-mode-hook 'elpy-mode)`

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! Have you tried `(with-eval-after-load 'elpy ...)`?

**Comment by wonbyte** [comment]
So use 'elpy instead of 'elpy-mode? I'll give it a shot this evening.

**Comment by jorgenschaefer** [comment]
Yeah – the file and feature is called `elpy`, not `elpy-mode`, and I believe `with-eval-after-load` wants a feature name, not a mode name …

**Comment by wonbyte** [comment]
so I tried it and now I have:

`(elpy-module-sane-defaults elpy-module-company elpy-module-eldoc elpy-module-highlight-indentation elpy-module-pyvenv elpy-module-yasnippet)`

even though it's not showing flycheck, it still appears to be active. So i'm not sure why it isn't listed in elpy-modules?

**Comment by jorgenschaefer** [comment]
> even though it's not showing flycheck, it still appears to be active.

I assume you mean flymake? Did you restart Emacs after the changes? How do you know it's active?

**Comment by wonbyte** [comment]
<img width="612" alt="screen shot 2016-03-14 at 5 13 18 pm" src="https://cloud.githubusercontent.com/assets/681965/13761663/1ccf658e-ea08-11e5-958d-6fd2e77ff13c.png">


I realize my code just removes flymake from the elpy-modules and then it activates flycheck mode. Is that the correct way to do it? Basically, I don't need to add flycheck to elpy-modules correct?

**Comment by jorgenschaefer** [comment]
> I don't need to add flycheck to elpy-modules correct?

Correct – flycheck-mode does not follow the Elpy module API convention, so it can't be on that list.

**Comment by gopar** [comment]
Solved. Closing
