### ISSUE TITLE
elpy fix company-idle-delay to 0.01

### ISSUE THREAD

**Issue by vgrimmer** [jorgenschaefer/elpy#832]
With my setting it always try to give me completion when typing comments and made moving around rather sluggish. The local variable setting overwrites my global company settings. 

What is the best way to customize/fix it?

Thanks!

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! You can use `(setq company-idle-delay ...)` in `elpy-mode-hook`, for example. Does that help?

**Comment by gongliyu** [comment]
I got the same problem. Actually, I tried to add (setq company-idle-delay 5) in my .emacs. But still the value is 0.01 when I look into it. It seems elpy changes it. I don't understand why? It is really annoying.

**Comment by gopar** [comment]
@vgrimmer  Did this help?

**Comment by vgrimmer** [comment]
Sorry for the delay. I somehow missed the original message. I ended up with a much higher value that avoided the constant pop up.
