### ISSUE TITLE
Elpy Package List

### ISSUE THREAD

**Issue by wonbyte** [jorgenschaefer/elpy#833]
Just wondering if you have a list of all the packages in https://jorgenschaefer.github.io/packages/ ? I've searched the repo trying to find them but have not come across anything yet.

**Comment by jorgenschaefer** [comment]
Hello! Does https://jorgenschaefer.github.io/packages/archive-contents help? :-)

Elpy will likely officially recommend MELPA stable in the next release, so my own archive will go dormant over time.

**Comment by wonbyte** [comment]
thanks! I currently like to pin my packages so i would like to do the same with these. I assume these don't change much other than possibly newer versions

**Comment by jorgenschaefer** [comment]
Indeed, there shouldn't be much movement at all.

Keep an eye out on Elpy release announcements, though, in case the repo moves again :-)

**Comment by wonbyte** [comment]
I'm still relatively new to emacs (came from vim) is that format just a emacs package archive? Not sure I am fully interpreting it correctly

**Comment by jorgenschaefer** [comment]
Yes, that's just the archive index used by `package.el` to figure out what is available in the archive. It maps packages to a vector with 4 elements: The version of the package, an alist of dependencies, a package description, and the format, either "tar" or "single".

**Comment by gopar** [comment]
solved
