### ISSUE TITLE
Support bpython?

### ISSUE THREAD

**Issue by xuhdev** [jorgenschaefer/elpy#835]
Is there any plan to support [bpython](http://bpython-interpreter.org/) as an interactive shell besides ipython? According to my personal experience, bpython is much more user-friendly than ipython for pure python purposes (not plotting things :) ).

**Comment by jorgenschaefer** [comment]
Hello and thanks for the question :-) I do not know bpython, but you can easily change the Python program used for the interactive shell, e.g. using `(setq python-shell-interpreter "bpython")`.

If bpython does a lot of interaction with the terminal, though, the way Emacs interacts with interactive shells does not really work well there. If that is what you're looking for, I'm afraid that would require a whole lot of work on the Emacs side of things to combine `comint-mode` and `ansi-term-mode`, which I am not sure anyone is working on …

**Comment by xuhdev** [comment]
I see, I've no problem with that. Maybe, this is another suggest, that `elpy` can support calling the interactive shell using an embedded terminal with the [XWidgets feature](https://www.emacswiki.org/emacs/EmacsXWidgets)?

**Comment by jorgenschaefer** [comment]
If Emacs ever implements such a mode, Elpy will be happy to use it for Python! :-)
