### ISSUE TITLE
Improper rendering of popups

### ISSUE THREAD

**Issue by shirindora86** [jorgenschaefer/elpy#837]
Hi Jorgen,

Thanks for your work on Elpy. I am running into a strange problem in terms of autocomplete suggestiong. I am not sure its because of elpy or not. Please hae a look at the following screenshots of the autocomplete suggestions I get. In the first picture, the suggestions are fine, but, when I type the next letter ('a') I think the new popup overlaps the previous one. By the way, I am trying to type random.

I am a very new user of emacs so it maybe possible I am doing something wrong here. Any help would be great. Thanks.
![popup1](https://cloud.githubusercontent.com/assets/13193171/13873627/a2e6f07e-ed2d-11e5-81ad-6c74749ec05a.png)
![popup2](https://cloud.githubusercontent.com/assets/13193171/13873634/adef0a1a-ed2d-11e5-9b53-4741d8f07f65.png)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! :-) This looks like as if you are using both company-mode (which Elpy uses) and auto-complete-mode (another completion package, indicated by AC in the mode line) at the same time.

Try adding the following to your `init.el` or `.emacs` and see if that fixes things for you:

```Lisp
(with-eval-after-load 'auto-complete
  (setq ac-modes (delq 'python-mode ac-modes)))
```

**Comment by shirindora86** [comment]
Thanks for the prompt reply. This does solve my issue. On the same note, may I ask how do people usually use the two nodes together. Whats the usual/correct workflow (way to setup emacs)?

I mean AC mode is a kind of general thing that emacs uses everywhere and company mode is used by elpy for python. I need both the modes to play well together. Thanks.

**Comment by jorgenschaefer** [comment]
Both company-mode and auto-complete are general, third-party completion packages used by different packages. If you as the user install them both, you also have to make sure they do not interfere with each other. The code I showed you tells auto-complete to stay out of Python buffers because you use something else there. So that's just how you do it in general. :-)

**Comment by shirindora86** [comment]
Thank you for the clarification.

**Comment by jorgenschaefer** [comment]
You're welcome, and enjoy Elpy! :-)
