### ISSUE TITLE
Hi, is it can be used to open a remote python shell with tramp?

### ISSUE THREAD

**Issue by nannanmath** [jorgenschaefer/elpy#841]
Hi:
I am a new one in emacs. I want to use it to develop python in remote host but I face some problem. you can visit: http://stackoverflow.com/questions/36118022/using-tramp-in-python-shell-from-cygwin-emacs24-5 to find details.
I also want to know if elpy can be used with tramp to develop python in a remote host?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! I'm afraid Elpy does not support tramp for various reasons. You'd have to install all the support (virtualenvs etc.) remotely to begin with, and I also found tramp to be very unreliable and buggy.

I can highly recommend developing locally and using automation to deploy to servers.
