### ISSUE TITLE
elpy-mode not enabled when opening a .py file.

### ISSUE THREAD

**Issue by MadsJensen** [jorgenschaefer/elpy#843]
Hi, 
For some reason  elpy-mode is not autocratically enabled when I open a .py file. I can enable it with M-x elpy-mode without any errors. I have elpy-enable in my init.el and 

```
Virtualenv........: None
RPC Python........: 2.7.11 (/home/mje/Toolboxes/anaconda/bin/python)
Interactive Python: ipython (/home/mje/Toolboxes/anaconda/bin/ipython)
Emacs.............: 25.1.50.2
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.2
Yapf..............: 0.6.3
Syntax checker....: flake8 (/home/mje/Toolboxes/anaconda/bin/flake8)
```

I sorry but I am not sure what if any information that is relavant to post as well.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! What's the value of `major-mode` in that .py file, and what's the value of `python-mode-hook`?

**Comment by MadsJensen** [comment]
Pardon  my ignorance but how do I find those values?

**Comment by jorgenschaefer** [comment]
Oh, sorry – you can check the value of variables with `C-h v`. :-)

**Comment by MadsJensen** [comment]
Thanks :)

major-mode is:
```
major-mode is a variable defined in ‘C source code’.
Its value is ‘python-mode’
```
python-mode-hook:
```
python-mode-hook’s value is ((lambda nil
   (set
    (make-local-variable 'yas-indent-line)
    'fixed))
 smartparens-mode nil elpy-mode)
```

**Comment by jorgenschaefer** [comment]
Hm. That `nil` n `python-mode-hook` is probably breaking things. Any idea how that got in there? Probably something that happens in your init file between `elpy-enable` and the way you enable smartparens :-)

**Comment by MadsJensen** [comment]
I tried to disable smartparens and yasnippet, but I still have the `nil`

`python-mode-hook’s value is (nil elpy-mode)`

**Comment by jorgenschaefer** [comment]
What does your init file look like?

**Comment by MadsJensen** [comment]
A dire need of a clean up but: [init file](https://github.com/MadsJensen/dotfiles/blob/master/init.el)

**Comment by MadsJensen** [comment]
Hi, 
The problem is fixed now. I think there might have been an issue with another package, as I have updated some packages (I'm sorry I cannot remember which) and now it works again. 

Thanks you very much for taking your time helping me!

**Comment by jorgenschaefer** [comment]
This is good to hear. Glad it works now, and enjoy Elpy! :-)
