### ISSUE TITLE
Can't jump back after [M-.] elpy-goto-definition

### ISSUE THREAD

**Issue by stardiviner** [jorgenschaefer/elpy#849]
After I press `[M-.]` to jump to definition, but I can't press `[M-,]` to jump back.

**Comment by ChillarAnand** [comment]
If you want to jump back you need to call `pop-tag-mark` which is bound to `M-*`.

If you want to use `M-,`, you need to bind it like this

    (define-key elpy-mode-map (kbd "M-,") 'pop-tag-mark)

**Comment by stardiviner** [comment]
@ChillarAnand thanks
