### ISSUE TITLE
Wrong "unused import"

### ISSUE THREAD

**Issue by swapnilsm** [jorgenschaefer/elpy#852]
`elpy-importmagic-fixup` command on following code snippet assumes `requests` as unused and hence removes it. 
```
import requests

def f(client=requests):
    client.get('http://google.com')
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Could you report this upstream at https://github.com/alecthomas/importmagic ?

**Comment by ChillarAnand** [comment]
Hi @swapnilsm ,

Can you update your importmagic and try again?
With latest version, it is working fine.

**Comment by swapnilsm** [comment]
Upgraded the importmagic. And yes it works. Thanks.
