### ISSUE TITLE
pip install flake8

### ISSUE THREAD

**Issue by Xparx** [jorgenschaefer/elpy#853]
Hello,
Think I have a related issue to issue #494 but not sure if it appropriate to reopen that.
I'm running GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.16.7)
Elpy 1.11.0
Python 2.7
I'm running in a virtual environment
currently I have flake8 installed in both .local/bin and 
and ~/.virtualenvs/default/bin/

Typing this out I just now noticed something weird... The following when asking for info on the variable
```
python-check-command’s value is
"install pyflakes, pylint or something else"
Original value was 
"/home/user/.virtualenvs/default/bin/pyflakes"
```
The original value seems to be the correct one. But for some reason it does not stick.
This seems to be the case if I run ``pyvenv-workon default`` -> ``run-python`` -> ``elpy-config``
Now this is the output from the command `elpy-config`
```
Elpy Configuration

Virtualenv........: default (/home/andreas/.virtualenvs/default)
RPC Python........: 2.7.10 (/home/andreas/.virtualenvs/default/bin/python)
Interactive Python: ipython (/home/andreas/.virtualenvs/default/bin/ipython)
Emacs.............: 25.1.50.2
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.2
Yapf..............: 0.6.3
Syntax checker....: Not found (install pyflakes, pylint or something else)

The configured syntax checker could not be found. Elpy uses this
program to provide syntax checks of your programs, so you might
want to install one. Elpy by default uses flake8.

[run] pip install flake8
```

Now if I run ``pyvenv-workon default`` -> ``elpy-config`` -> ``run-python`` the following is my output from elpy-config, both before and after run-python
```
Elpy Configuration

Virtualenv........: default (/home/andreas/.virtualenvs/default)
RPC Python........: 2.7.10 (/home/andreas/.virtualenvs/default/bin/python)
Interactive Python: ipython (/home/andreas/.virtualenvs/default/bin/ipython)
Emacs.............: 25.1.50.2
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.2
Yapf..............: 0.6.3
Syntax checker....: flake8 (/home/andreas/.virtualenvs/default/bin/flake8)
``` 

The problem seems to be that I need to run elpy-config before initiating any python instance which is a bit odd. Even though I now figured out a workaround for my original issue,
any help appreciated.
Is there something to point to that seems like an obvious culprit?

**Comment by Xparx** [comment]
An update,
It seems the different behaviours are related to how I launch emacs, If I use the launcher to launch an emacs --daemon I get the first behaviour while launching emacs in ay other way seems to cause the correct behaviour. 
I think I need to check what is happening using an ubuntu launcher and starting a daemon.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! When Elpy starts up, it tries to see if you have flake8 installed. If not, it won't touch settings. So if you start Elpy when flake8 is not in the path, you get the default value from Emacs, which is the weird string you see there.

You can force using flake8 even if you don't have it in your environment on startup by just doing `(setq python-check-command "flake8")` in your init file, e.g. right after `(elpy-enable)`.

Does that help? :-)

**Comment by Xparx** [comment]
Thanks for getting back to me!
That is indeed helping. Thanks!

PS:
I also realised now that adding `Terminal=true` in the `.desktop` (launcher) file for entries where the deamon is run, makes it use my environment variables, it seems. Not sure what is happening under the hood here and how robust this solution is.

**Comment by jorgenschaefer** [comment]
I suspect the `Terminal=true` means that Emacs is run with a shell, which also reads `.bashrc` and such.

Glad it works now. I'll close this issue, but don't hesitate to open a new issue if you have further problems or questions. And enjoy Elpy! :-)
