### ISSUE TITLE
key bindings

### ISSUE THREAD

**Issue by spluque** [jorgenschaefer/elpy#854]
I don't see a section for customizing key bindings for elpy.  I would like to remove and change some of the existing ones as they interfere with others I'm used to, and it would be nice to have a section where all the key bindings defined by elpy are collected. For now, do we do this with the regular Emacs tools outside of elpy?
## 

Seb

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! Elpy runs in Emacs, Emacs tools are Elpy tools, they are not "outside" of Elpy – so yes, you can see the key bindings of Elpy using `C-h m`, and you can change Elpy's key bindings by using `define-key` on `elpy-mode-map` just as usual in Emacs. No magic involved. :-)

Does that help?

**Comment by spluque** [comment]
On Fri, 01 Apr 2016 11:45:21 -0700,
Jorgen Schäfer <notifications@github.com> wrote:

> Hello, and thanks for the question! Elpy runs in Emacs, Emacs tools
> are Elpy tools, they are not "outside" of Elpy

Depends on how large one makes the universe - Emacs is a very big one!
;-)

> – so yes, you can see the key bindings of Elpy using C-h m, and you
> can change Elpy's key bindings by using define-key on elpy-mode-map
> just as usual in Emacs. No magic involved. :-)

> Does that help?

Yes, thanks, I have already redefined the keybindings myself within
`eval-after-load`.  I still think it would be nice to have a customize
section with all the keybindings that Elpy defines, a bit like Icicles
does to simplify this and avoid having yet more code to maintain on my
init file.

-- 
Seb

**Comment by jorgenschaefer** [comment]
I understand that you feel that way, but I'm a bit friend of convention over configuration. Elpy is already big enough, I'd prefer that part of the universe not to be even bigger. :-)
