### ISSUE TITLE
Automatic pep8 checking

### ISSUE THREAD

**Issue by el-ethan** [jorgenschaefer/elpy#857]
I have been using Emacs and Elpy for all my Python development for some time now. Just recently I noticed that my setup no longer seems to apply pep8 checking to my Python files. It will still do some checking, for example, it will warn me about unused imports, and syntax errors, but it won't warn me about, e.g., lines that are too long, not leaving enough space before a class definition - which are things that it always used to warn me about. I have been digging through my configuration to try to figure out how this got changed and how to get the functionality back, but haven't been able to track it down. Is this something that has been changed/can be configured in Elpy, or should I be looking elsewhere for the solution? Below is a screen shot where you can see the `!` and red underlining indicating that I have an unused import, but no such indication for my pep8 violations, which used to be highlighted in the same way.

![screenshot from 2016-04-05 22-02-52](https://cloud.githubusercontent.com/assets/10249884/14304644/35dd8866-fb7a-11e5-95ad-3fb1328d61bc.png)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report :-)

Does `C-c C-v` show those errors?
What's the value of `python-check-command`?

**Comment by el-ethan** [comment]
`python-check-command` is set to "/usr/local/bin/pyflake", and when I run`C-c C-v` it only reports the unused import. However, when I run `elpy-autopep8-fix-code`, it fixes pep8 violations as expected (e.g., puts two lines before class definitions, changes `foo=123` to `foo = 123`, etc.). Shouldn't `pyflakes` catch the pep8 violations as well? If not, I am not opposed to using a different linter/formatter, but I fell like something else is going on here.

**Comment by jorgenschaefer** [comment]
Elpy usually recommends `flake8` as the linter, which combines both pyflakes and pep8 into a single one. The autodetection of the linter is a bit brittle, you can use `(setq python-check-command "flake8")` to hardcode your choice.

Does flake8 make things work as you expect?

**Comment by el-ethan** [comment]
Well, things just got a little stranger...I actually already have `(setq python-check-command "flake8")` set in my init file, but the value seems to be getting changed elsewhere. Also, when I do `describe-variable` on `python-check-command` it says: 

`Its value is "/usr/local/bin/pyflakes"
Original value was "pyflakes"`

which strikes me as odd as well. I tried starting Emacs with the `-Q` option, running `package-initialize`, and then `elpy-enable`, then visiting a Python file, and in this case the pep8 checking works as expected! Also, when I check the value of `python-check-command` after starting Emacs this way, I get:

`Its value is "flake8"
Original value was "pyflakes"`

So it would seem that it is something in my configuration, but I tried commenting out all of my Elpy configuration code except for `elpy-enable` but it doesn't fix the problem.

**Comment by jorgenschaefer** [comment]
`elpy-enable` will change `python-check-command` under certain circumstances, but it should only ever change it to `flake8` … can you share your configuration?

**Comment by el-ethan** [comment]
My elpy-specific configuration is here: 

https://github.com/el-ethan/.emacs.d/blob/master/settings.org#elpy

But it is probably coming from elsewhere in my configuration (the rest of the configuration can be seen at that link as well of course). I thought it might be related to changing `PYTHONPATH`, but getting rid of the `setenv` line in my elpy configuration doesn't make a difference for the problem.

I am working on bisecting to see what I can find...

**Comment by jorgenschaefer** [comment]
Hm. :-( Nothing that I can see there. (You should modify `elpy-modules` before calling `elpy-enable`, but that's totally unrelated)

**Comment by el-ethan** [comment]
Well, I found what was causing the issue (although I don't understand why it causes the issue). After using `git bisect` on my init file, I found that the problem was introduced when I added [smart-mode-line](https://github.com/Malabarba/smart-mode-line/blob/master/smart-mode-line.el) to my configuration. Specifically, calling [`sml/setup`](https://github.com/Malabarba/smart-mode-line/blob/master/smart-mode-line.el#L983) for some reason causes the pep8 warnings to go away.

**Comment by el-ethan** [comment]
Also, just out of curiosity, why/how should I modify `elpy-modules` before calling `elpy-enable`? I thought that `elpy-modules` is not created until `elpy-enable` is called.

**Comment by jorgenschaefer** [comment]
That is some seriously weird side effect there. Nice work tracking it down!

> Also, just out of curiosity, why/how should I modify `elpy-modules` before calling `elpy-enable`? I thought that `elpy-modules` is not created until `elpy-enable` is called. 

`elpy-enable` will run the global initialization code of all configured modules. `elpy-modules` is defined as soon as Elpy is loaded. Installing the `elpy` package will mark `elpy-enable` as a function that auto-loads Elpy, so calling it will work even without Elpy loaded beforehand; but you can of course load Elpy manually first, e.g. `(load "elpy") (setq elpy-modules ...) (elpy-enable)`

**Comment by el-ethan** [comment]
Thanks for the tip! Anyway, I will mark this as closed since it is clearly not an issue with Elpy.

**Comment by YichaoCaiDBS** [comment]
Dear all, sorry to bother you guys again for this issue.

I am having a similar issue that the pep8 check is no longer showing up in the minibuffer (e.g. line too long; no space near "=").  Instead, the minibuffer only shows something like this:
![git-issue-elpy](https://user-images.githubusercontent.com/24425664/49365273-506b7080-f721-11e8-92dd-88406729ddf1.png)
It should show some warnings from pep8 checking like 'arg.wd is not defined', but it didn't.


The value of `python-check-command` is:
`python-check-command is a variable defined in ‘python.el’.
Its value is "flake8"
Original value was 
"/home/yichao/anaconda3/bin/pyflakes"`

Do you have any idea how this would happen? 
Thanks!

This is my elpy config:
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.4 (/home/yichao/anaconda3/bin/python)
Interactive Python: python (/home/yichao/anaconda3/bin/python)
Emacs.............: 26.1
Elpy..............: 1.17.0
Jedi..............: 0.10.2 (0.13.1 available)
Rope..............: 0.10.5
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: 1.3.3 (1.4.3 available)
Yapf..............: 0.18.0 (0.25.0 available)
Syntax checker....: flake8 (/home/yichao/anaconda3/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

```
