### ISSUE TITLE
elpy-rpc-python-command defcustom uses system-type as string

### ISSUE THREAD

**Issue by ilohmar** [jorgenschaefer/elpy#858]
Starting with elpy, on win7 and on debian linux no less :)  I noticed that `elpy-rpc-python-command`'s `defcustom` default value depends on `system-type`, but does a *string* comparison (which will always be false).

It should read
```
(if (eq system-type 'windows-nt) "pythonw" "python")
```
just as it does in other places.  Thanks!

**Comment by jorgenschaefer** [comment]
Good catch! Thank you :-)
