### ISSUE TITLE
Package cannot be found

### ISSUE THREAD

**Issue by screwed99** [jorgenschaefer/elpy#860]
I'm on Ubuntu Wily (15.10) with a fresh install of Emacs trying to have a look at the elpy package. Been troubleshooting for a day now (reinstalling Emacs, trying to get older versions installed from source with no success, reading elsewhere etc.)

Main problem is that I put just this github package list in my .emacs file and when I try to package-refres-contents it hangs on:
Contacting host: jorgenschaefer.github.io:80

Think I found a similar issue here but no fix (https://www.reddit.com/r/emacs/comments/44awl7/emacs_hanging_on_packagerefreshcontents/).

Version information from inside Emacs:
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.6) of 2015-09-17 on lgw01-52, modified by Debian

Any help appreciated

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! I assume you can reach http://jorgenschaefer.github.io/ from your computer normally. Could you try to `M-x toggle-debug-on-quit` and hit `C-g` when it hangs? You should get a backtrace that shows what Emacs was doing when it was showing that message, if you post that I might be able to help trying to figure out what's going on. :-)

**Comment by screwed99** [comment]
Hello, thank-you for the speedy reply.

I'm not exactly sure what happened as I can no longer reproduce the problem but after another half-day of head-scratching it appears I can now install elpy from a fresh emacs install without any issues! When I tried to do `M-x toggle-debug-on-quit` it made all the output from my actions much less consistent but something eventually made it all work. I cannot get `M-x package-install` to work as it always says it cannot find the package but `M-x package-list-packages` was fine in the end.

I am now stuck/confused on the use of virtual environments for python within elpy. I need both of these two lines in my .emacs file to have `M-x run-python` give me the ipython REPL from my specific conda virtual environment (called 'emacs'):

(setq python-shell-interpreter "ipython")
(setq python-shell-virtualenv-path "/PATH-TO/anaconda2/envs/emacs")

In addition in order to execute `M-x elpy-config` I need to use `M-x pyvenv-activate` to point to virtual environment (as my base python doesn't have all the necessary libraries installed).

When I run `M-x python-mode` it is unclear what version of python is being used to execute elpy IDE features, I'm not sure how to change this or even check which version is being used.

So it seems I may have as many as three different python references (python shells, python-mode and elpy-config)? In addition to understanding what is going on I am looking for a simple way to initialise emacs to run in one virtual env and then setup a function in my .emacs file to be able to switch to other virtual environments at will.

Thank-you in advance.

**Comment by jorgenschaefer** [comment]
Elpy uses two different variables to configure the Python interpreter to use: `python-shell-interpreter` is used (by Emacs' built-in python-mode) to run the _interactive_ Python for `M-x run-python`. In addition to this, Elpy needs a non-interactive Python, which is configured as `elpy-rpc-python-command`.

I would recommend leaving the latter as `"python"` and simply using `M-x pyvenv-activate` to switch the virtualenv. You do not need to set `python-shell-virtualenv-path`, the `pyvenv` library takes care of everything that does.

`M-x elpy-config` simply tells you which Python interpreter Elpy would use right now in your current environment.

Elpy starts an RPC process when you open a Python file. If you switch the current virtualenv after you opened a Python file, you can use `M-x elpy-rpc-restart` to get a new RPC process in the correct virtualenv.

Does this help?

**Comment by screwed99** [comment]
OK yes that helps significantly and I have managed to update my .emacs file with my own function now so that I don't need to type in the whole path each time I use `M-x pyvenv-activate`. (Sorry for the delay I'm very new to elisp).

I am still slightly confused as to what versions of python elpy is using. I think I want the value of `elpy-rpc-python-command` to always point to the same place so that I don't need to install 'jedi', 'rope' etc. into each of my project virtual environments. Is this a wise idea? I feel I at least need one of these environments for python2.7 and another for python3?

I have a virtual environment called `emacs` just for elpy RPC to use but when I run `M-x elpy-config` it suggests pyflakes/flake8 is not installed when it is. It appears maybe that the "Syntax checker" does not use the RPC python but actually uses the virtual environment version?

Thanks in advance.

**Comment by jorgenschaefer** [comment]
> Is this a wise idea?

Tricky. To complete symbols from your project, Jedi and such need access to your code. If you install them into a different virtualenv, they will not see your packages. There are [some alternatives](https://github.com/jorgenschaefer/elpy/issues/629#issuecomment-131714290) to installing them in every virtualenv, but those alternatives are all more elaborate – I found just installing them in the virtualenvs to work quite ok.

> it suggests pyflakes/flake8 is not installed when it is.

Does `C-c C-v` work? If not, what is the error?

**Comment by screwed99** [comment]
OK I think I see your point with regards to the virtual environments. As I understand it Jedi will still see all my code in the current project but if I have external packages imported into the code then there is clearly going to be trouble. Not sure I fully understand all the solutions in the issue you've linked to but I will install the dependencies everywhere for now.

`C-c C-v` gives the following output:

`-*- mode: compilation; default-directory: "DIR" -*-
Compilation started at Mon Apr 11 13:29:05

pyflakes /PATH/TO/file.py
/bin/bash: pyflakes: command not found

Compilation exited abnormally with code 127 at Mon Apr 11 13:29:05`

**Comment by jorgenschaefer** [comment]
Could you add `(setq python-check-command "flake8")` to your init file and see if that fixes things? Elpy tries to walk a tricky line between setting things up nicely but not overriding your configurations, and can get confused at times.

**Comment by screwed99** [comment]
Unfortunately that hasn't changed anything as I as I can make out

**Comment by jorgenschaefer** [comment]
Does `C-h v python-check-command` show the new value, and if so, what error does `C-c C-v` show?

**Comment by screwed99** [comment]
`C-h v python-check-command` shows the new value `flake8`, the error is the same as before:

```
-*- mode: compilation; default-directory: "DIR" -*-
Compilation started at Wed Apr 13 08:35:16

pyflakes /PATH/TO/file.py
/bin/bash: pyflakes: command not found

Compilation exited abnormally with code 127 at Wed Apr 13 08:35:16
```

Just to recap I've got `elpy-rpc-python-command` set to the venv with all the modules installed and then used `pyvenv-activate` to change my main python to another venv without the modules installed.

**Comment by jorgenschaefer** [comment]
This is weird. `C-c C-v` uses `python-check-command`. If this is set to `"flake8"`, then `C-c C-v` should run `"flake8"` (the command line tool, this has nothing to do with `elpy-rpc-python-command`). Why does it run `"pyflakes"`? Do you set `python-check-command` buffer-local somewhere?

**Comment by screwed99** [comment]
I'm not sure what buffer-local is, I just have a .emacs file to set stuff. This is the full output from the variable value:
```
python-check-command is a variable defined in `python.el'.
Its value is "flake8"
Original value was "pyflakes"

  This variable may be risky if used as a file-local variable.

Documentation:
Command used to check a Python file.

You can customize this variable.
```

**Comment by jorgenschaefer** [comment]
Are you running ths `C-h v python-check-command` in the same Python buffer where you run `C-c C-v`?
What's the output `C-h k C-c C-v`?

**Comment by screwed99** [comment]
OK sorry for the long delay on this, now happy to continue troubleshooting if you are.

I now get output from `C-h v python-check-command`:

```
python-check-command is a variable defined in `python.el'.
Its value is "flake8"
Original value was "pyflakes"

  This variable may be risky if used as a file-local variable.

Documentation:
Command used to check a Python file.

You can customize this variable.
```
Output of error from `C-c C-v` when run in the same buffer is now I believe as you expected:
```
-*- mode: compilation; default-directory: "/path-to-file/" -*-
Compilation started at Sat Apr 30 15:26:20

flake8 /path-to-file/file.py
/bin/bash: flake8: command not found

Compilation exited abnormally with code 127 at Sat Apr 30 15:26:20
```

Output from `C-h k C-c C-v`:
```
C-c C-v runs the command elpy-check, which is an interactive compiled
Lisp function in `elpy.el'.

It is bound to C-c C-v, <menu-bar> <Elpy> <Syntax Check> <Check
Syntax>.

(elpy-check &optional WHOLE-PROJECT-P)

Run `python-check-command' on the current buffer's file,

or the project root if WHOLE-PROJECT-P is non-nil (interactively,
with a prefix argument).
```
You've mentioned that flake8 is a command-line-tool, I don't have any version of it installed on my default system search path. When I use `pyvenv-activate` to change to a virtual environment that has it installed, I can to in the config that it is pointing there but when the virtual environment does not have it installed then it cannot be found. I guess I want 'Syntax checker' to keep looking in the same directory as 'RPC Python' rather than being tied to 'Virtualenv'. Am I making sense?

**Comment by jorgenschaefer** [comment]
I am not sure whether I fully understand, but … `elpy-rpc-python-command` is by default `"python"` so it finds the default python interpreter in the current virtualenv. `python-check-command` is by default `"flake8"` so it finds `flake8` in the current virtualenv. If you change `elpy-rpc-python-command` to point somewhere else, you can at the same time change `python-check-command`.

**Comment by screwed99** [comment]
OK I've re-read earlier comments and I think I understand it all now. I was trying to get my interactive python to come from a different virtual environment than the RPC python but it appears that it's not simple to do that. Your patience has been much appreciated anyhow and I have enjoyed continuing to use elpy so thank-you!

**Comment by jorgenschaefer** [comment]
You're welcome. You should be able to set the respective variables to different Python interpreters, but you will get weird behavior because different modules are available in each … If you want, you can try and share what problem you were trying to solve with all of this? Otherwise, I'll close this report and hope you enjoy Elpy :-)

**Comment by screwed99** [comment]
I think I was just trying to limit the number of packages i.e. flake8 that would need to be installed in each of my virtual environments going forwards. If it is cumbersome to do this and maybe sounds likely to cause me problems down the line I'm not really an expert troubleshooting those kind of experts and would rather keep it simple. I think yea you can close this now!
