### ISSUE TITLE
A list of classes, methods and global variables similar to jedi-direx?

### ISSUE THREAD

**Issue by xuhdev** [jorgenschaefer/elpy#866]
[jedi-direx](https://github.com/tkf/emacs-jedi-direx) is really cool -- if `elpy-occur-definitions` can be used to display something like this, even for the whole project, it would be awesome.

**Comment by jorgenschaefer** [comment]
Thank you for the suggestion! Yeah, a project browser would be awesome. Sadly, I have not found a good one yet. :-( See #242 for the ticket to track that.

**Comment by ChillarAnand** [comment]
If you are using helm, You can use `helm-semantic` function, it will show a nice tree view of imports, global/local variables, functions/classes (only for current buffer).

![el](https://cloud.githubusercontent.com/assets/4463796/14558829/512be3d8-0322-11e6-9ae4-a9ab783a0849.png)

**Comment by whirm** [comment]
I use `help-semantic` + `helm-etags-select` for a project-wide view.
