### ISSUE TITLE
[question] C-c C-c send with arguments

### ISSUE THREAD

**Issue by MortalCatalyst** [jorgenschaefer/elpy#867]
HI

Looking at the docs for

```bash
http://elpy.readthedocs.org/en/latest/ide.html#interactive-python
http://elpy.readthedocs.org/en/latest/ide.html#command-python-shell-send-defun
```

Is there a way to send to ipython interpreter include command line arguments that would be supplied to the script?

Thanks for a great package.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! The interactive shell is just that, an interactive shell – it does not run a script, it interprets Python code (basically) as if you copy and pasted it into the shell.

If you want to run a script with arguments, look at `M-x compile` and `M-x recompile`.

Does that help?

**Comment by MortalCatalyst** [comment]
Perhaps this is more along the lines of what I was thinking [http://stackoverflow.com/a/2906371/461887](http://stackoverflow.com/a/2906371/461887l)

Where created a function to accept sys.argv

```lisp
(defun python-send-buffer-with-my-args (args)
  (interactive "sPython arguments: ")
  (let ((source-buffer (current-buffer)))
    (with-temp-buffer
      (insert "import sys; sys.argv = '''" args "'''.split()\n")
      (insert-buffer-substring source-buffer)
      (python-send-buffer))))
```

Then if bound

```lisp
(global-set-key "\C-c\C-a" 'python-send-buffer-with-my-args)
```
I would have a function to send to intrepreter C-c C-c just the script or C-c C-a script with arguments.

**Comment by jorgenschaefer** [comment]
This seems a bit unconventional, but if it solves your problem and works for you, great! Does that solve your problem?

**Comment by MortalCatalyst** [comment]
Yes I was sad to have to leave emacs to run a script now more emacs for me. thanks.

**Comment by jorgenschaefer** [comment]
Glad to hear it, and enjoy Elpy! :-)
