### ISSUE TITLE
elpy-check with prefix argument should make invocation configurable

### ISSUE THREAD

**Issue by jsandovalc** [jorgenschaefer/elpy#876]
Hi.
I use elpy with pylint and I'm trying to run elpy-check (C-c C-v) with a prefix argument but I'm getting this output:

> pylint /home/ark/repositorios/rest-service/ --exclude=.bzr,CVS,.git,.hg,.svn,.tox,build,dist,.cask
> Warning: option profile is obsolete and it is slated for removal in Pylint 1.6.
> Warning: option include-ids is obsolete and it is slated for removal in Pylint 1.6.
> Warning: option symbols is obsolete and it is slated for removal in Pylint 1.6.
> Warning: option comment is obsolete and it is slated for removal in Pylint 1.6.
> Warning: option zope is obsolete and it is slated for removal in Pylint 1.6.
> Warning: option ignore-iface-methods is obsolete and it is slated for removal in Pylint 1.6.
> Warning: option required-attributes is obsolete and it is slated for removal in Pylint 1.6.
> Usage:  pylint [options] module_or_package
> 
>   Check that a module satisfies a coding standard (and more !).
> 
>     pylint --help
> 
>   Display this help message and exit.
> 
>     pylint --help-msg <msg-id>[,<msg-id>]
> 
>   Display help messages about given message identifiers and exit.
> 
> 
> pylint: error: no such option: --exclude
> 
> Compilation exited abnormally with code 32 at Thu May  5 14:45:53
> 

Apparently, pylint does not support exclude, but ignote. Is there a way to customize this easily?.

Man thanks.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question. How did you configure Emacs to use pylint for syntax checks?

**Comment by jsandovalc** [comment]
Well, it's been a while since I configured it but I think I did it with elpy-config by setting "Python Check Command" to pylint. I have pylint installed in a virtualenv, and when I do pyvenv-activate (or workon), it shows the correct path (in elpy-config) in the virtualenv. I have multiple projects and when I switch between virtualenvs pylint works fine with C-c C-v and with flymake.

**Comment by jorgenschaefer** [comment]
Ah. I see what you mean, sorry for the confusion. No, there is currently no way to configure the special invocation for `C-u C-c C-v` I'm afraid :-( Looks like I made that pretty flake8-specific.

That's a bug.

**Comment by jsandovalc** [comment]
Oh, I see. No such a big deal. I'll try to customize it with a little elisp (a good reason to learn).

By the way, thanks for such a great extension to emacs :)

**Comment by jorgenschaefer** [comment]
Thank you for the kind words! :-)
