### ISSUE TITLE
elpy not recognizing new python version

### ISSUE THREAD

**Issue by kirk86** [jorgenschaefer/elpy#877]
Hi everyone, I was wondering if anyone could help me out resolve the issue below.

OS: OS X 10.11.4
emacs 24.5

Comes bundled with python2.7.10 and matplotlib 1.3.x pre-installed. I wanted to use the newer version which is python2.7.11 so that I can also upgrade matplotlib to 1.5.x. Thus, I installed via brew both python2.7.11 and python3.5 and matplotlib 1.5.x for poth python versions. Now configured my `/etc/paths` in the following way.

`/usr/local/bin`
`/usr/local`
`/Users/xxxx/Library/Python/2.7/bin`
`/Users/xxxx/Library/Python/2.7/share`
`/Users/xxxx/Library/Python/3.5/bin`
`/Users/xxxx/Library/Python/3.5/share`
`/usr/bin`
`/bin`
`/usr/sbin`
`/sbin`

Whenever I call python or ipython from terminal I always get the correct version.

My `elpy-config:` is configured as follows:

`Virtualenv........: None`
`RPC Python........: 2.7.11 (/usr/local/bin/python)`
`Interactive Python: ipython (/Users/xxxx/Library/Python/2.7/bin/ipython)`
`Emacs.............: 24.5.1`
`Elpy..............: 1.12.0`
`Jedi..............: 0.9.0`
`Rope..............: 0.10.3`
`Importmagic.......: 0.1.7`
`Autopep8..........: 1.2.2`
`Yapf..............: 0.7.1`
`Syntax checker....: pyflakes (/Users/xxxx/Library/Python/2.7/bin/pyflakes)`

But ,whenever I execute some code that contains calls to matplotlib 1.5.x version via `C-c C-c` I notice that in the ipython terminal python2.7.10 is being called which was the default pre-installed in the osx system by apple instead of the python2.7.11 version which I have installed and even though `elpy-config` shows that it picks up the correct version, nevertheless, every time I execute some code the old python version keeps being called by elpy.

Any suggestions?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question!

> `Interactive Python: ipython (/Users/xxxx/Library/Python/2.7/bin/ipython)`

The `ipython` shell you use is that one – is that the correct interpreter? If so, could you kill the existing ipython buffer and try `C-c C-c` again?

**Comment by kirk86** [comment]
Hi and thanks for the suggestion. Yeah, that's the right one, it points to ipython 4.2.0 which is the most current release.
If I invoke it directly from terminal everything works perfect. Somehow when it is invoked within emacs-elpy with `C-c C-c` it does call the same version of ipython 4.2.0 but this time is invoked with the wrong python version 2.7.10 instead of python 2.7.11 which is the correct version that is being loaded every time that I fire up terminal and call `ipython`.

**Comment by jorgenschaefer** [comment]
I have no idea how ipython works that it can find a different python depending on where you call it from, I'm afraid. :-(

**Comment by kirk86** [comment]
Is there a way to point elpy-config to particular python version? Can you do something like that? If so where should I look?

Thanks!

**Comment by jorgenschaefer** [comment]
> Is there a way to point elpy-config to particular python version?

Which part of `elpy-config` shows a wrong Python version?

I thought it shows it is using the right version, but somehow starting that ipython runs the wrong Python – I do not know how to configure ipython, as I said.

**Comment by kirk86** [comment]
Now that I am double checking it again. Your comment about `Interactive `Python: ipython (/Users/xxxx/Library/Python/2.7/bin/ipython)`, was correct. If I invoke it with the absolute path in the terminal I get the following result:
`
Python 2.7.10 (default, Oct 23 2015, 19:19:21) `
`Type "copyright", "credits" or "license" for more information.`

`IPython 4.2.0 -- An enhanced Interactive Python.`
`?         -> Introduction and overview of IPython's features.`
`%quickref -> Quick reference.
`help      -> Python's own help system.`
`object?   -> Details about 'object', use 'object??' for extra details.
`
Instead if I just type `ipython` in the terminal without the absolute path I get:

`
Python 2.7.11 (default, Oct 23 2015, 19:19:21) `
`Type "copyright", "credits" or "license" for more information.`

`IPython 4.2.0 -- An enhanced Interactive Python.`
`?         -> Introduction and overview of IPython's features.`
`%quickref -> Quick reference.
`help      -> Python's own help system.`
`object?   -> Details about 'object', use 'object??' for extra details.
`
That happens because I had put in my `.bashrc` the following alias `alias ipython=python -m IPython`, thus the above absolute path in elpy-config is pointing to the wrong version.

Now since I installed both `python2.7.11 and python3.5` via brew and then I installed ipython via `pip2 and pip3` I was looking where the actual binaries for ipython are but could find them even though during installation I specified the user folder.

**Comment by jorgenschaefer** [comment]
`which ipython` in a shell would give you the full path.

You can configure the interactive Python interpreter being used by customizing `python-shell-interpreter`.

Though it sounds like your `PATH` is weird inside Emacs. Make sure it's as you expected. You can check using `C-h v exec-path`.

**Comment by kirk86** [comment]
here is the weird thing that is bothering me.
`which ipython`
gives:
`/Users/jm/Library/Python/2.7/bin/ipython`
if I just run that in the terminal I get ipython being loaded with python 2.7.10
instead if I run in the terminal python -m IPython I get ipython loaded with python 2.7.11
It seems that somehow if I invoke ipython via the desired python version I get the outcome that I want but if I invoke it through the installed directory `/Users/jm/Library/Python/2.7/bin/ipython` it always peeks the default python version 2.7.10 which apple had pre-installed.

**Comment by kirk86** [comment]
Finally managed to solve it.
`which python`
`/usr/local/bin/python`

`which ipython`
`/Users/xxxx/Library/Python/2.7/bin/ipython`

Looking into the above ipython file. I see that it is calling `/usr/bin/python` in the first line. Change that to `/usr/local/bin/python` and voila we now have ipython working along with the desirable python version.
