### ISSUE TITLE
Elpy does not support static type annotations in python (PEP 0484)

### ISSUE THREAD

**Issue by cmpis** [jorgenschaefer/elpy#879]
I tried to run Elpy today on code that uses annotations extensively. I was hoping the default configuration would support indentation on that code better than `python-mode.el`.

However, not only does it not support it, but it flags every line with the type annotations as invalid syntax even though the virtual environment should be in python 3.

What package in Elpy does the syntax checking and indentation? Is it possible we could use flymake-mypy which supports type checking?

**Comment by jorgenschaefer** [comment]
Elpy uses the built-in `python.el` in Emacs. If that does not support type annotations, please file a bug report with Emacs core (`M-x report-emacs-bug`).

By default, Elpy uses `flake8` for syntax checks. You can get the full output and the command being run with `C-c C-v`. You can configure which syntax checker is used by customizing `python-check-command`.

Does that help? :-)

**Comment by cmpis** [comment]
I think it will. I will try that out. 

Also to further clarify: the main issue is with *function annotation* not type annotation. It has issues when I try to specify some code like this 

``` python
def processor(percent: Decimal, l: Iterable) -> Iterable:
    """
    Generator....
    """
    for i in l:
        yield i
```

**Comment by jorgenschaefer** [comment]
I can totally believe that Emacs' `python.el` does not support function annotations. It has been pretty slow in keeping up with Python 3 improvements, sadly. :-(

**Comment by cmpis** [comment]
Looking to flake8 more and I found this on SO: https://stackoverflow.com/questions/23600614/how-to-use-flake8-for-python-3

You need to run flake8 in python 3 to get python 3 features.

I'm not sure where I read Jedi can't run in py3 but according to their docs they do support Python 3.4 and function annotations. https://jedi.readthedocs.io/en/latest/docs/features.html

Is there any reason or way to get elpy using Python 3 instead? I think it's using py2.7 now

**Comment by jorgenschaefer** [comment]
The easiest way is to use a virtualenv with Python 3, and install flake8 in there. If you do not use virtualenvs for some strange reason, you have to:

- Set `elpy-rpc-python-command` to the full path of the non-interactive Python 3 program
- Set `python-shell-interpreter` to the full path of the interactive Python 3 interpreter of your choice
- Set `python-check-command` to the full path of the `flake8` program that is using Python 3

**Comment by cmpis** [comment]
Ah I see the problem. I needed to *not* install flake and the other utils in the global environment. Everything works again.

**Comment by jorgenschaefer** [comment]
Great! I'll close this issue, then. Outside of the function annotations (which would be something for Emacs to support), if you have any further problems, please do not hesitate to open a new issue. And enjoy Elpy. :-)
