### ISSUE TITLE
evaluating main()

### ISSUE THREAD

**Issue by teymuri** [jorgenschaefer/elpy#882]
I am testing how to use elpy+emacs for python (i am new to using emacs). I have the following test using pygame:

    import pygame

    def main():
        pygame.init()

        screen = pygame.display.set_mode((500, 500))
        pygame.display.set_caption("test main")
        pygame.display.flip()

        runs = True

        while runs:
            for e in pygame.event.get():
                if e.type == pygame.QUIT:
                    runs = False
        pygame.quit()

    if __name__ == "__main__":
        main()

When i evaluate the `if__nam__` part using `C-M-x` nothing happens, i try to eval the whole file with `C-c C-c` again no success. By using `C-M-x` the `main()` function is sent to the python shell, so i can call `main()` there, the window gets opened and everything is fine. But i couldn't have success with key shortcuts. At the same time the code is working as expected in other editors and also by calling it from terminal. How should can it work also in elpy so that i can evaluate the code to see the result faster and not by having to call main from the python-shell-processor?

**Comment by jorgenschaefer** [comment]
Hello! Elpy (or rather, Emacs' python-mode) tries to be smart here and escapes the `if __name__ == "__main__"` test under the assumption that you just want to send your file to the shell and test it manually there. You can pass a prefix argument to `C-c C-c` to prevent this escaping, so `C-u C-c C-c` should work. See the docstring under `C-h k C-c C-c`.

Does this help?

**Comment by teymuri** [comment]
Yes this does the work. So would you suggest to have the code not packed inside of main() function and rather just have a file (without main()) for using `C-c C-c` while working on the code?
Thank you.

**Comment by jorgenschaefer** [comment]
I'm afraid I have no experience with pygame. If you do not require the interactive shell there, I would suggest to use `M-x compile` to run the program using a full command (and `M-x recompile` to run it again; I have the latter on `<f5>`).

**Comment by teymuri** [comment]
1. I don't use the interactive shell while in pygame. When i run `M-x compile` in the minibuffer i see: `Compile command: make -k`, i hit enter and get this message: 

        make -k
        make: *** No targets specified and no makefile found. Stop.
        Compilation exited abnormally with code 2.
But i think i could also live with `C-c C-c`.

2. My second question is about the `C-c RET`: when i for example am in a line with `print "Hello Elpy!"` on the word `Elpy!` and hit the RETURN i see in the minibuffer a prompt: `Object to import: Elpy`, hit the return:  `No import candidate found`. Is this the correct way of sending simple statements to the shell?

**Comment by jorgenschaefer** [comment]
Regarding, 1), `M-x compile` asks for a command to run. You can use `python yourscript.py`.

As for 2), `C-c RET` is `elpy-importmagic-add-import`. Did you mean `<C-return>`, `elpy-shell-send-current-statement`?

**Comment by teymuri** [comment]
`C-return` moves to the new line, just as a normal `return`

**Comment by jorgenschaefer** [comment]
I assume you are on a terminal, and not in the GUI version of Emacs? Terminals can not distinguish `<C-return>` from `RET`, I'm afraid, so you will have to find a different key for that command. You can find out what command a given key runs by using `C-h k`.

**Comment by teymuri** [comment]
Yes i was on a terminal, i have changed to the GUI and all is perfect! Thank you again for your help and the beautiful Elpy! :-)

Herzliche Grüße aus Freiburg

**Comment by jorgenschaefer** [comment]
Glad to hear it works and that you enjoy Elpy! I'll close this issue, but please do not hesitate to open a new one if you have further problems :-)

Und viele Grüße in den Süden :-D
