### ISSUE TITLE
elpy-config not showing pip packages

### ISSUE THREAD

**Issue by wonbyte** [jorgenschaefer/elpy#885]
Hi,
I'm using python3 on Mac and in my init.el (https://gist.github.com/wonbyte/94bd93004af33b1282184b4bb5bb688e) I have installed and setup elpy using the following:

;; ELPY

(add-hook 'python-mode-hook 'elpy-mode)
(with-eval-after-load 'elpy
  (remove-hook 'elpy-modules 'elpy-module-flymake)
  (add-hook 'elpy-mode-hook 'flycheck-mode)
  (add-hook 'elpy-mode-hook 'elpy-use-ipython)
  (add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save))

I also created a pyvenv and installed all the pip packages per the github page. I activate the pyvenv in emacs and when I run elpy-config I get the below:

Elpy Configuration

Virtualenv........:  (/Users/gsieran/src/github/nflgame/)
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: Not found (0.9.0 available)
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.2.2 available)
Yapf..............: Not found (0.8.0 available)
Syntax checker....: Not found (pyflakes)

Any ideas why none of the pip packages are available?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! The problem is here:

> Virtualenv........: (/Users/gsieran/src/github/nflgame/)
> RPC Python........: 2.7.10 (/usr/bin/python)

You have a virtualenv active, but the virtualenv is not in `exec-path`. It seems that `pyvenv` added the relevant path to `exec-path`, but then it got removed again. This looks remarkably like a problem another used had a while ago. Are you using `exec-path-from-shell` perchance?

And just to verify the problem for sure:
- Is `/Users/gsieran/src/github/nflgame/` a virtualenv?
- Is `/Users/gsieran/src/github/nflgame/bin/` in your `exec-path`?
- If not, try to `M-x pyvenv-deactivate` and `M-x pyvenv-activate` again, is it in your `exec-path` then?

**Comment by wonbyte** [comment]
Thanks, for the response. 

nflgame is a virtual env that I created with pyvenv3.5. 

How can I check the exec-path? 

In emacs I activated my virtual env with pyvenv-activate. Is that the correct command to use or is there a python3 one I should be using?

**Comment by jorgenschaefer** [comment]
You can check the value of a variable with `C-h v` :-)

**Comment by wonbyte** [comment]
Great, I'll give this a try tonight!

**Comment by wonbyte** [comment]
Looks like all is working! One other question, when I try to use tab completion is says it needs an inferior python process to run. So I manually do m-x run-python. Is there a way to automatically start one when I use elpy?

**Comment by wonbyte** [comment]
So if I create a new dir, make it a pyvenv and install the required pip packages then elpy finds everything with no problem. But I am forking the nflgame dir, doing pyvenv-3.5 nflgame/ and then activating it in emacs. Elpy is unable to find the pip packages.

My exec-path is:

("/Users/gsieran/src/github/nflgame//Scripts" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs/24.5/libexec/emacs/24.5/x86_64-apple-darwin15.0.0")

I'm not doing anything with exec-path. I am just trying to active the pyvenv

**Comment by jorgenschaefer** [comment]
> "/Users/gsieran/src/github/nflgame//Scripts"

This looks strange. Is there a directory `Scripts` in that virtualenv directory? If so, do you know why?

**Comment by wonbyte** [comment]
There is, if you want to take a quick glance at what's in the repo it's here: https://github.com/BurntSushi/nflgame


What's weird to me is why using the exact same steps, elpy works fine on a brand new dir, but I'm having issues on an existing one. I'm sure it's something I'm doing just not sure what

**Comment by jorgenschaefer** [comment]
You should not make your virtualenv the same directory as your project directory, really.

**Comment by wonbyte** [comment]
Yeah, that dawned on me after I re-read my last comment. Let me try that

**Comment by wonbyte** [comment]
> Hi,
> I'm using python3 on Mac and in my init.el (https://gist.github.com/wonbyte/94bd93004af33b1282184b4bb5bb688e) I have installed and setup elpy using the following:
> 
> ;; ELPY
> 
> (add-hook 'python-mode-hook 'elpy-mode)
> (with-eval-after-load 'elpy
>   (remove-hook 'elpy-modules 'elpy-module-flymake)
>   (add-hook 'elpy-mode-hook 'flycheck-mode)
>   (add-hook 'elpy-mode-hook 'elpy-use-ipython)
>   (add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save))
> 
> I also created a pyvenv and installed all the pip packages per the github page. I activate the pyvenv in emacs and when I run elpy-config I get the below:
> 
> Elpy Configuration
> 
> Virtualenv........:  (/Users/gsieran/src/github/nflgame/)
> RPC Python........: 2.7.10 (/usr/bin/python)
> Interactive Python: python (/usr/bin/python)
> Emacs.............: 24.5.1
> Elpy..............: 1.12.0
> Jedi..............: Not found (0.9.0 available)
> Rope..............: Not found (0.10.3 available)
> Importmagic.......: Not found (0.1.7 available)
> Autopep8..........: Not found (1.2.2 available)
> Yapf..............: Not found (0.8.0 available)
> Syntax checker....: Not found (pyflakes)
> 
> Any ideas why none of the pip packages are available?
> 

Probably can close this?

**Comment by wonbyte** [comment]
Can this be closed?
