### ISSUE TITLE
pep8 not removing syntax warning/error after fix?

### ISSUE THREAD

**Issue by vinhdizzo** [jorgenschaefer/elpy#886]
Hi,

When I open a python file, I get the "!" flag on the left side of a buffer to indicate a syntax error/warning (pep8).  For example, I get the message `E231 missing whitespace after ','`.  When I fix it, the warning/message doess not go away.  If I close the buffer and re-open, then the warning goes away.  Is there a way to have the message go away automatically?  Thank you.

**Comment by jorgenschaefer** [comment]
Hello! Did you try to save the file after making the change?

**Comment by vinhdizzo** [comment]
You are correct, saving does indeed force the syntax checker to update.  Not possible to make it update immediately?  Thank you.

**Comment by jorgenschaefer** [comment]
> Not possible to make it update immediately?

You can configure flymake to do so (see `flymake-no-changes-timeout` and `flymake-start-syntax-check-on-newline`; change them in `elpy-mode-hook`, as `elpy-module-flymake` sets them), but this basically means that the line you are editing at the moment will almost always be highlighted as bad, which I found annoying. Your taste can of course differ.
