### ISSUE TITLE
(elpy-goto-definition) fails with relative import

### ISSUE THREAD

**Issue by yitang** [jorgenschaefer/elpy#891]
Hi, I have following folder strcutre, 

- project_dir
   - Data
   - python_pkg 
      - \_\_init\_\_.py
      - add.py
      - config.py 

inside of add.py, I have 

```python
from .config import try_load
```

M-. fails to find the definition of `try_load`. I tried elpy-set-project-root to python-pkg and also project_dir, both doesn't works.

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report! What's the output of `M-x elpy-config`?

**Comment by yitang** [comment]
Hello, I am unable to reproduce this error. M-. works on both relative and absolute imports. apologies for my mistake.

**Comment by jorgenschaefer** [comment]
No worries – I'd rather get too many bug reports than too few :-)

**Comment by humitos** [comment]
> No worries – I'd rather get too many bug reports than too few :-)

I like your attitude :)

Thanks to your answers when someone else open an issue, I started doing the same. I got excellent answers not just about elpy but emacs configuration in general and today I have my own "very tweaked" configuration with a lot of plugins and crazy hotkeys.

Thanks again!
