### ISSUE TITLE
FAQ entry for "do I have to install all of this into each virtualenv?"

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#894]
This has been asked frequently, so make it an FAQ in the documentation somewhere.

Basic outline of an answer here: https://github.com/jorgenschaefer/elpy/issues/888#issuecomment-221493305

**Comment by gopar** [comment]
Added this to the [Elpy wiki](https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-do-i-have-to-install-all-these-packages-every-time)

**Comment by jorgenschaefer** [comment]
Nice, thank you!
