### ISSUE TITLE
ipython not found

### ISSUE THREAD

**Issue by kapil0187** [jorgenschaefer/elpy#895]
I have anaconda's python distribution  installed on my system. I can access the ipython console from my terminal, howevere, `(elpy-use-ipython)` raises an error.

`elpy-use-ipython: Command "ipython" not found`

Do you have any ideas what I am missing?

EDIT:

I am working on OSX with python 2.7 with anaconda installed in ~/anaconda

**Comment by jorgenschaefer** [comment]
Hello! I suspect your `ipython` is only available in the shell, and not in your global environment (OS X makes a difference there), so you have to set your `PATH` accordingly. See e.g. https://stackoverflow.com/questions/16676826/making-the-path-and-other-environment-variables-available-in-emacs

Does that help?

**Comment by kapil0187** [comment]
Thanks! yeah it was a problem with my `$PATH` variable not being read by emacs. `exec-path-from-shell` emacs package helped with that.

**Comment by kapil0187** [comment]
For anyone who stumbles on to this thread: 

I have in my `~/.bash_profile`

`export PATH="/Applications/anaconda/bin:$PATH"
`
and in my `~/.emacs.d/init.el`

```
(package-initialize)
(exec-path-from-shell-copy-env "PATH")
(elpy-enable)
(elpy-use-ipython)
```
