### ISSUE TITLE
Getting error when loading .py files 

### ISSUE THREAD

**Issue by crappyoats** [jorgenschaefer/elpy#899]
Getting error int the linked gist when I first open a .py file in emacs

https://gist.github.com/crappyoats/c849d83143a1ad2968fe945d1efa79bc

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

This is not so much an error, but some output from Python Elpy did not expect – it does ignore it, though, so you everything else should keep working.

Looks like you have some MPI library installed (or are using it) which writes a lot to stdout/stderr?

**Comment by crappyoats** [comment]
I'm not sure about the MPI libs (I'm pretty new to the whole emacs config thing), but I am getting a lot of the error message "error in process sentinel: elpy-rpc--default-error-callback: peculiar error: "exited abnormally with code 1"
error in process sentinel: peculiar error: "exited abnormally with code 1" popping up.

**Comment by jorgenschaefer** [comment]
> I'm not sure about the MPI libs (I'm pretty new to the whole emacs config thing)

This is unrelated to Emacs, it's Python.

You can try `python -m elpy` in a terminal. It should also emit these warnings.

**Comment by jorgenschaefer** [comment]
Added: You'll also need `export PYTHONPATH=$HOME/.emacs.d/elpa/elpy-1.12.0/`

**Comment by crappyoats** [comment]
I get `elpy-rpc ready (1.12.0)` and then a blinking cursor.

**Comment by jorgenschaefer** [comment]
That's the correct initial handshake. You did not do anything after opening the .py file before those warnings appear?

Also, what's the output of `M-x elpy-config`?

**Comment by crappyoats** [comment]
No, it pops up after loading a .py file. If I kill the buffer that its in, the message pops up again in a new buffer.

https://gist.github.com/crappyoats/52ed6651ccbdcd00bc94effa1f3e05a8

Thanks again for walking me through this. Like I said I am a super noob!

**Comment by jorgenschaefer** [comment]
You are using the system-wide Python interpreter. Which means you likely have a library installed system-wide that emits messages to stdout/stderr even though Elpy redirects those elsewhere. Elpy uses stdout/stderr for subprocess communication. The messages you see are Elpy telling you "hey, I got this stuff I did not expect, I have no problem with this, but maybe you want to see it". You don't. Bury the buffer, ignore it, and just keep working. Nothing is wrong, except those libraries acting badly.

If you want to get rid of this completely, I can recommend using virtualenvs and not installing these libraries in the virtualenv you work in. :-)

Does this help?

**Comment by crappyoats** [comment]
I tried wiping elpy and reinstalling, then I changed elpy's python to python3 and that seemed to get rid of the issue. I also added ~/.local/bin to my PATH and I haven't had any problems since.

Thanks Jorgen!

**Comment by jorgenschaefer** [comment]
Awesome! Glad things work now. :-)

**Comment by zjag43** [comment]
Hi Jorgen, I am getting a similar problem and have not been able to find the issue: below is my .init.el file 

I am fairly new to emacs, and running on a Windows7 64-bit system.  Thank you in advance!

(server-start)
(require 'ido)
(require 'cc-mode)
(ido-mode t)
(load-theme 'wombat t)
(linum-mode)
(setq-default fill-column 80)
(setq-default auto-fill-function 'do-auto-fill)
(require 'package)

(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/")
	     t)

(add-to-list 'package-archives
	     '("marmalade" . "http://marmalade-repo.org/packages/")'
	     t)

(require 'elpy)
(elpy-enable)
(package-initialize)

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(global-set-key (kbd "M-x") 'smex)

(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)

(ac-config-default)

(autopair-global-mode)

(global-undo-tree-mode)

(global-set-key (kbd "M-/") 'undo-tree-visualize)

(global-set-key (kbd "C-M-z") 'switch-window)

(global-set-key (kbd "C->") 'ace-jump-mode)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Helm
(require 'helm-mode)
(require 'helm-config)

(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)

(global-set-key (kbd "M-i") 'helm-swoop)
(global-set-key (kbd "C-x b") 'helm-buffers-list)
(global-set-key (kbd "C-x r b") 'helm-bookmarks)
(global-set-key (kbd "C-x m") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x C-f") 'helm-find-files)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Conda Packages

(require 'conda)
;; if you want interactive shell support, include:
(conda-env-initialize-interactive-shells)
;; if you want eshell support include:
;(conda-env-initialize-eshell)
;; if you want auto-activation (see below for detail), include:
(conda-env-autoactivate-mode t)
 
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(conda-anaconda-home "C:\\ProgramData\\Anaconda2")
 '(helm-mode t)
 '(package-selected-packages
   (quote
    (helm-swoop auto-complete-auctex auctex virtualenvwrapper pyenv-mode conda helm minimap elpy jedi csharp-mode ein ace-jump-mode switch-window undo-tree autopair nlinum monokai-theme auto-complete smex)))
 '(winner-mode t))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; py3
(setq elpy-rpc-python-command "ipython")
(setq python-shell-interpreter "ipython")
(remove-hook 'python-mode-hook 'wisent-python-default-setup)
;; Fixing a key binding bug in Elpy
(define-key yas-minor-mode-map (kbd "C-c k") 'yas-expand)

;(setq python-shell-interpreter "C:\\Users\\joel.gongorra\\AppData\\Local\\Continuum\\anaconda2\\python")
;(setq python-shell-interpreter "C:\\ProgramData\\Anaconda2\\python")

;; company
(require 'company)

;; keybindings for company mode
(define-key company-active-map (kbd "C-n") 'company-select-next)
(define-key company-active-map (kbd "C-p") 'compnay-select-previous)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
