### ISSUE TITLE
Matplotib plots not displaying in Emacs from elpy with Python 2.7

### ISSUE THREAD

**Issue by brettmichael9** [jorgenschaefer/elpy#909]
I've been unsuccessful viewing my plots in Elpy.

    >>> import matplotlib.pyplot as plt

    >>> data = [1, 2, 3, 4, 5]
    >>> plt.plot(data)
    [<matplotlib.lines.Line2D object at 0x00000000054FA550>]
    >>> plt.show()

Nothing shows up anywhere. I also cannot run anything in the python shell after.

I've tried:

    >>> plt.ion()

before the `plt.plot` but it did not work.

I've tried changing my `.emacs` file to:

    (setq python-shell-interpreter "C:\\Myfile\\python.exe"
             python-shell-interpreter-args "-i C:\\Myfile\\Scripts\\ipython-script.py console --pylab")

This also did not work. Instead it says

    [TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be      removed in future versions.
    [TerminalIPythonApp] WARNING | You likely want to use `jupyter console`... continue in 5 sec. Press Ctrl-C to quit now.    

and then further down says

    [ZMQTerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
    [ZMQTerminalIPythonApp] CRITICAL | Unrecognized flag: '--pylab'

I tested this code directly in ipython in the command line and it shows the plot as a `.png`. So that works.

I am working on a Windows machine.

I am familiar with #80 but the solution it proposed also did not work for me.

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report! I do not know matplotlib – what does it use to display plots?

**Comment by brettmichael9** [comment]
In terms of output, it outputs a `.png` file. Since it worked in the Ipython shell outside of Emacs I thought maybe it had something to do with Elpy or maybe my Elpy/Emacs configuration.

**Comment by kapil0187** [comment]
This should work if ipython is in your PATH

```
(elpy-enable)
(elpy-use-ipython)

```

You might have to load your `$PATH` env variable in emacs as well. This should be run before loading elpy.
`
(exec-path-from-shell-copy-env "PATH")
`

**Comment by brettmichael9** [comment]
Excellent! Works perfectly. Thank you!

**Comment by kapil0187** [comment]
Great! Happy to help.

**Comment by DrWaleedAYousef** [comment]
this statement `(exec-path-from-shell-copy-env "PATH")` does not help me. I am not able to plot within emacs

**Comment by fluencer** [comment]
Hi there. I can not get the matplotlib plots to be displayed. I tried (elpy-use-ipython), but it has been deprecated.

This is my current code for using ipython
`(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")
`
