### ISSUE TITLE
How to stop elpy from displaying vertical lines demarcating indentation

### ISSUE THREAD

**Issue by mdk2029** [jorgenschaefer/elpy#910]
In elpy mode, emacs displays a lot of vertical lines that demarcate indentation. I would like it to not do so. What elpy variable controls this?

**Comment by humitos** [comment]
I think there is no a specific variable for this, but I think you can disable `highlight-indentation` by using a hook with something like this:

```lisp
(add-hook 'elpy-mode-hook (lambda () (highlight-indentation-mode -1)))
```

**Comment by mdk2029** [comment]
Yes, That did it. Thanks a lot!

**Comment by humitos** [comment]
Maybe a better solution, in the FAQ ;)

https://github.com/jorgenschaefer/elpy/wiki/FAQ#q-can-i-tell-elpy-not-to-load-one-of-the-minor-modes-it-enables-by-default

**Comment by jorgenschaefer** [comment]
@humitos, you've been very active helping people in issues here – thank you very much for your work, it is greatly appreciated!

**Comment by humitos** [comment]
@jorgenschaefer I try to do what I can when I _think I know_ the answer. When I started configuring my emacs I felt the frustration...

You are the author of elpy but not the only user ;-)
