### ISSUE TITLE
pyvenv error

### ISSUE THREAD

**Issue by gozes** [jorgenschaefer/elpy#911]
after installing elpy I try to start it in my confing when I enter in to python-mode but notice that when I open a python file so I tryed M-x elpy-enable, the same thing that is on my config, but got the following error "Required feature 'pyvenv' was not provided." I don't care for pyvenv, i don't use it, so I look at the docs and added pyvenv-deactivate after elpy-enable and try again. Same error.

for reference here is the relevant fort of my config 
https://github.com/gozes/.emacs.d/blob/master/config.org#python

that setup used to work fine now I'm not sure what is going on.

for references I am on Arch Linux both  jedi and rope are install

**Comment by jorgenschaefer** [comment]
Elpy depends on pyvenv. You will have to install the pyvenv package to use Elpy, I'm afraid. You can remove `elpy-module-pyvenv` from `elpy-modules` if you really don't want to use pyvenv at all, but all that does is show a current virtualenv in the mode line if there is one. If you don't use virtualenvs, there is no other effect.

**Comment by gozes** [comment]
I have it installed but still getting the error

this is what I have on my config for elpy

``` emcas-lisp
(use-package python-mode
  :ensure t
  :defer t
  :init
  (progn
    (use-package pyvenv :ensure t :defer t)
    (use-package elpy
      :ensure t
      :defer t
      :config
      (progn
        (elpy-enable)))))
```

**Comment by jorgenschaefer** [comment]
I'm afraid I do not know `use-package` – maybe ask the author of that package as to how to use it correctly in this case?

**Comment by ChillarAnand** [comment]
@gozes You shouldn't use elpy with python-mode package.

You can try this config

    (use-package elpy
        :ensure t
        :config
        (elpy-enable))

**Comment by gozes** [comment]
@ChillarAnand that did it. Not sure what was going on.

**Comment by ChillarAnand** [comment]
Elpy uses python.el from emacs and doesn't need python-mode package. Enjoy elpy :-)

**Comment by gopar** [comment]
Is this resolved?

**Comment by gozes** [comment]
Yes it is. Sorry i forgot to close the issue. I will do so as soon as i get
back to my system
