### ISSUE TITLE
Autocompletion & Output from Backend

### ISSUE THREAD

**Issue by AccPy** [jorgenschaefer/elpy#913]
I've been trying to get emacs to work with elpy for the past couple of hours and whenever I take two steps forward, I end up taking one step back (and now I'm really stuck). Each article I looked up tried to fix the same problems in different ways so I don't know where I went wrong. As of right now, I can't seem to get emacs to show the drop down of autocompletion possibilities. It did show a drop down when I put 
```
(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:complete-on-dot t)
```
in my ~/.emacs file; however, the only items it showed in the drop down were about 5 items and I think they were just variables in the .py file. I'm also now getting an error whenever I put a period (like if I put a period after a list ex. list.append().) The period would make another window appear saying output from backend. 

Here is the error message:
```
Output from Backend

There was some unexpected output from the Elpy backend. This is
usually some module that does not use correct logging, but might
indicate a configuration problem.

Output
objc[18753]: Class SDLApplication is implemented in both /Users/jal/Library/Python/3.5/lib/python/site-packages/pygame/sdlmain_osx.cpython-35m-darwin.so and /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib. One of the two will be used. Which one is undefined.
objc[18753]: Class SDLTranslatorResponder is implemented in both /usr/local/opt/sdl/lib/libSDL-1.2.0.dylib and /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib. One of the two will be used. Which one is undefined.
```

And here is my ~/.emacs file:
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes (quote (tango-dark)))
 '(gud-gdb-command-name "gdb --annotate=1")
 '(large-file-warning-threshold nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(font-lock-function-name-face ((((class color) (min-colors 88) (background light)) (:foreground "purple1"))))
 '(font-lock-keyword-face ((((class color) (min-colors 88) (background light)) (:foreground "red2"))))
 '(font-lock-string-face ((((class color) (min-colors 88) (background light)) (:foreground "white")))))


(setq tab-width 4)

(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory)))

(require 'package)

(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/")
             '("elpy" . "http://jorgenschaefer.github.io/packages/"))

(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))

(defvar myPackages
  '(better-defaults
    elpy
    flycheck
    material-theme
    py-autopep8))

(mapc #'(lambda (package)
    (unless (package-installed-p package)
      (package-install package)))
      myPackages)

;; BASIC CUSTOMIZATION
;; --------------------------------------

(setq inhibit-startup-message t) ;; hide the startup message
(load-theme 'material t) ;; load material theme
(global-linum-mode t) ;; enable line numbers globally

;; PYTHON CONFIGURATION
;; --------------------------------------

(elpy-enable)
(elpy-use-ipython)

;; use flycheck not flymake with elpy
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

;; enable autopep8 formatting on save
(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

(setq ring-bell-function 'ignore)

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                     ("marmalade" . "http://marmalade-repo.org/packages/")
                     ("melpa" . "http://melpa.org/packages/")))

(setq elpy-rpc-python-command "python3")
```

I'm running Python 3 on OS X.

**Comment by AccPy** [comment]
Oh, and can I just delete the colors for the faces at the top since I'm not using them anymore? There's a warning there not to so I was wondering if there was maybe another way to get rid of them to clean it up.

**Comment by AccPy** [comment]
The drop down autocomplete now works properly (I copied and pasted the .emacs file information back inside it after trying to play around with a few items and now it works even though it's the exact same content in the file lol). The unexpected output from the backend still persists though.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> (add-hook 'python-mode-hook 'jedi:setup)

`jedi:setup` is the `emacs-jedi` package which is unrelated to and conflicting with Elpy.

Not to be confused with the `jedi` Python package. The naming of the `emacs-jedi` package is unfortunate, yes.

> Here is the error message:

This is not an error message. As the message says, this _might_ indicate a configuration problem. In this case, some module your Python installation is using is printing spurious stuff to stdout while it should not. Elpy does not know if this output is relevant to you or not, so it shows you the output. If it's not relevant to you, ignore it. That's what you'd do when your program emits these messages, too.

Does this help? :-)

**Comment by AccPy** [comment]
Yes, thank you.
