### ISSUE TITLE
elpy-test-django-runner-command is a risky variable

### ISSUE THREAD

**Issue by humitos** [jorgenschaefer/elpy#914]
Hi,

I don't know why but for some reason `elpy-test-django-runner-command` is marked as a risky variable when I try to set it in my `.dir-locals.el` file and it's not consider inside the `!` option to be added as a safe variable by emacs by adding it to the `'safe-local-variable-values`.

*Only* this variable is marked as `risky (**)` and I don't know how to mark it as a safe local variable. Can you help me?

My `.dir-locals.el` looks like this:

```elisp
((python-mode
  . (
     ;; This is used to fill the paragraph in 120 columns when pressing M-q
     ;; because in the Mozio project we use 120 columns
     (fill-column . 120)
     
     ;; Use 4 spaces to indent in Python
     (python-indent-offset . 4)
     ;; autopep8 global configurations
     (py-autopep8-options . ("--global-config=~/mozio/autopep8rc"))
     ;; FlyCheck global configurations
     (flycheck-flake8rc . "~/mozio/flake8rc")

     ;; docformatter global options
     (py-docformatter-options . ("--wrap-summaries=120" "--wrap-descriptions=120" "--pre-summary-newline" "--no-blank"))

     ;; use our own virtualenv for this project
     (eval . (pyvenv-workon 'mozio-ondemand))

     ;; run proper test when hitting C-c C-t
     (elpy-test-runner . elpy-test-django-runner)
     (elpy-test-django-runner-command . ("/home/humitos/mozio/ondemand/manage.py" "test" "--noinput" "--keepdb" "--failfast"))
     )
  ))
```

What has this variable that is different from the other ones?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question!

Elpy runs the command in that variable. If a repository you clone from somewhere included a specially-crafted .dir-locals.el, it would be very easy to introduce backdoors and security problems this way. Hence, this variable should not be set from file variables.

I'm afraid I do not know why `safe-local-variable-values` is ignored, though.

**Comment by humitos** [comment]
> I'm afraid I do not know why safe-local-variable-values is ignored, though.

Yeah, I couldn't find the *why* of this yet. I will keep researching and let you know.

On the other hand, how do you mark that variable as risky? or... How emacs identifies it as risky?

**Comment by jorgenschaefer** [comment]
> On the other hand, how do you mark that variable as risky? or... How emacs identifies it as risky?

It's buffer-local and not marked as safe, so it's risky. White-listing, as opposed to black-listing. :-)

**Comment by humitos** [comment]
After reading a little bit, without understanding the whole picture, I have a close answer, but not the solution. For that, I think I will need your help or keep reading for a couple of days more :)

I tried to create an scenario similar to what I have in `elpy.el`

Elisp program with custom variables, one safe and the other *risky*, supposed:
```elisp
;; my-program.el
(defcustom my-safe-variable 6
  "Declare a safe variable"
  :type 'integer
  :safe #'integerp)

(defcustom my-risky-variable '("We are going to delete all your" "files")
  "Declare a risky variable"
  :type '(repeat string))
```

Local variable settings for the whole directory:
```elisp
;; .dir-locals.el
((python-mode
  . (
     (fill-column . 120)
     (my-safe-variable . 5)  ;; no problem with this
     (my-safe-variable . ("Non" "integer" "data"))  ;; risky variable because of its value
     (my-risky-variable . ("Remove all your data" "¡Sure!"))
     )
  ))
```

Simple python file inside the directory with the `.dir-locals.el`
```python
# a simple python script with nothing, just to load the "python-mode" from .dir-locals.el
```

Here, when I open the python file I'm alarmed by emacs about the `my-safe-variable` because it has a value that is not integer and also about the `my-risky-variable` because it has no `:safe` on its declaration BUT it says "may not be safe (*)" on both of them and gives me the option to use `!` and forget about this warning.

So, I wasn't able to create a *risky* variable yet and I don't know why. On the other hand, I don't have other clue about how to keep the research. Maybe, keep reading will give me more paths to follow.

If you know something about this, please share ;-)

**Comment by jorgenschaefer** [comment]
I suspect it's this ([link](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html)):

> In addition, any variable whose name ends in any of ‘-command’, ‘-frame-alist’, ‘-function’, ‘-functions’,  ‘-hook’, ‘-hooks’, ‘-form’, ‘-forms’, ‘-map’, ‘-map-alist’, ‘-mode-alist’, ‘-program’, or ‘-predicate’ is automatically considered risky. The variables ‘font-lock-keywords’, ‘font-lock-keywords’ followed by a digit, and ‘font-lock-syntactic-keywords’ are also considered risky.

**Comment by humitos** [comment]
Nice!

The solution is to add it *manually* to your `~/.emacs` file with the proper values for all the files by marking them as safe. Here are mines

```elisp
(custom-set-variables
 '(safe-local-variable-values
   (quote
    ((eval pyvenv-workon
	   (quote emacs-default))
     (eval pyvenv-workon
	   (quote mozio-commons))
     (eval pyvenv-workon
	   (quote mozio))
     (eval pyvenv-workon
	   (quote mozio-ondemand))
     (py-docformatter-options "--wrap-summaries=120" "--wrap-descriptions=120" "--pre-summary-newline" "--no-blank")
     (py-autopep8-options "--global-config=/home/humitos/mozio/autopep8rc")
     (elpy-test-django-runner-command "/home/humitos/mozio/ondemand/manage.py" "test" "--noinput" "--keepdb" "--failfast")
     (elpy-test-django-runner-command "/home/humitos/mozio/mozio/manage.py" "test" "--noinput" "--keepdb" "--failfast")))))
```

With the two last lines I'm not more alarmed about elpy *risky variables*.

Thanks a lot for your help!

**Comment by jorgenschaefer** [comment]
Nice. Glad it works for you, and enjoy Elpy :-)
