### ISSUE TITLE
Autocomplete for desktop emacs

### ISSUE THREAD

**Issue by b505d987** [jorgenschaefer/elpy#915]
Hi.

I use desktop emacs on OS X and I have don't working elpy autocomplete.
In terminal mode is working, but in desktop not...

My config here - [https://gist.github.com/b505d987/522708a0dca6bfb299a00c9ee09ba82a](https://gist.github.com/b505d987/522708a0dca6bfb299a00c9ee09ba82a)

What's wrong with my config?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! It is difficult to tell what the problem is without any error message. What's the output of `M-x elpy-config`?

**Comment by b505d987** [comment]
Jorgen, thank you for quick response. 
I think, problem with wrong python interpreter in desktop version, [screenshot (left desktop, right terminal)](https://www.dropbox.com/s/pl0f5kmqtruuxgk/Screenshot%202016-06-13%2020.51.05.png?dl=0).
What is right way specify python for elpy?

**Comment by jorgenschaefer** [comment]
This looks like a problem with `PATH` not being set in your desktop environment, but only in a terminal. You can use the `exec-path-from-shell` package to fix this problem.

**Comment by b505d987** [comment]
It's working. Thank you very much!

**Comment by jorgenschaefer** [comment]
Glad to hear this! Enjoy Elpy :-)
