### ISSUE TITLE
Elpy on OS X with NLTK leads to Transient Failures

### ISSUE THREAD

**Issue by jmercouris** [jorgenschaefer/elpy#919]
When you have the NLTK library installed (which uses tkinter modules) you get the following error:
http://stackoverflow.com/questions/34515333/applepersistenceignorestate-error-started-just-after-wxpython-installation

This leads to a open python window that is frozen that you must force quit. This is a problem because every save in elpy triggers this window opening for some reason. This happens periodically.

The current workaround for this is to simply install all of NLTK dependencies as normal, but when you wish to actually install NLTK install it into a virtual env created with the --system-site-packages flag.

**Comment by jmercouris** [comment]
Issue was persistent even after removing NTLK, I believe it may be related to sic-kit learn. The issue is when you are using import magic with elpy because it appears to do some package loading which creates a window or something, I don't know I couldn't figure it out. But removing import magic fixes the issue.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! I'm a bit unsure what you would like Elpy to do here?

**Comment by jmercouris** [comment]
Elpy relies on importmagic which breaks for some imports, elpy should blacklist modules that cause this behavior because it binds the system

**Comment by jorgenschaefer** [comment]
If you can't even import some module, that sounds like a bug in that module.
If importmagic breaks some modules, that sounds like a bug in importmagic.

Could you report this problem with either the broken module, or importmagic? :-)

**Comment by jmercouris** [comment]
I would if I could figure this out, I still want to believe that it is an elpy problem of some sort though because, when running a normal python interpreter, my system works fine with every module installed. The spawned process always reports being forked from emacs. It is possibly an import magic issue, I’m not sure. But it breaks elpy, so I figured it is quite relevant to the project

**Comment by jorgenschaefer** [comment]
Can you try and run the following code, in the same environment as Elpy is?

```Python
import importmagic.index

index = importmagic.index.SymbolIndex(blacklist_re=None)
index.build_index(["...value of elpy-library-root..."])
```

Does this produce the same behavior?

**Comment by jmercouris** [comment]
Hello I ran the following:

Python 3.4.4 (default, Mar  2 2016, 03:31:27)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importmagic.index
>>> index = importmagic.index.SymbolIndex(blacklist_re=None)
>>> index.build_index(["~/.emacs.d/elpa/elpy-20160131.118/“])

this did not reproduce the same behavior. But sure enough, soon as I did ‘pip install importmagic’ and restarted emacs, it started freezing.

**Comment by jorgenschaefer** [comment]
What's the value of `elpy-library-root` in your Python file?

**Comment by jmercouris** [comment]
I ran it again, substituting the path returned from putting

(espy-library-root) in one of my python files, and then executing C-x C-e to evaluate it.

I re ran the sequence

>>> import importmagic.index
>>> index = importmagic.index.SymbolIndex(blacklist_re=None)
>>> index.build_index(["~/Documents/TUB/Transnational/source/“])

still, no problems.

**Comment by jorgenschaefer** [comment]
Could you try the full path there? This function does not do tilde expansion as far as I know.

**Comment by jmercouris** [comment]
Still no problems.
I’m sorry, but I had to recreate my environment and am somehow no longer able to reproduce this bug! I wish I could have figured it out, sorry once again!

**Comment by jorgenschaefer** [comment]
Well, that's a good solution for me – this sounded like that pretty strange error. Glad it works now! Please don't hesitate to open a new issue (or re-open this) if there are further problems, and enjoy Elpy :-)
