### ISSUE TITLE
how to manually install and config elpy on a CentOS machine without internet access

### ISSUE THREAD

**Issue by galactica147** [jorgenschaefer/elpy#920]
I'm working on a restricted env without any internet access but tried to download the source package into ~/.emacs.d/ and tried something like this in ~/.emacs

```
(require 'package)
(add-to-list 'package-archives
             '("elpy" . "~/.emacs.d/elpy_src/"))
```

however it failed when loading it:

```
(package-initialize)
(elpy-enable)                  
```

`"symbol's function definitin is void: elpy-enable"`

Also tried to refresh-content in the scratch buffer but got the error:

`"Failed to download gnu archive"`
--seems it tried to download from web although I've tried to pointed elpy to my local download. 

Is there a way to fix this without online installation?
Emacs version 24.5.1
Thanks!

**Comment by jorgenschaefer** [comment]
Hello! There are a number of ways you can do that, but all of them involve actually understanding how Emacs and Emacs packages work. The easiest solution might be to just install them outside of the restricted environment, and then move the `.emacs.d/elpa` directory over.

Alternatively, you can download the packages (`.tar` and `.el` files) from the package archives directly and `M-x package-install-file` in the correct order. You can also try to install them using the packages' git repositories, but that's a lot of work. Or, maybe even just clone the https://github.com/jorgenschaefer/jorgenschaefer.github.io repo and try to add that as a package archive somehow.

**Comment by galactica147** [comment]
Hi Jorgen,

Thanks for the suggestions! I was trying the 'easiest' solution by copying from an installed version where ~/.emacs.d/elpa/ also contains a number of other packages. And this seems to fix the elpy-enable problem but introduced others like syntax highlight/checks, etc. 

Could you please list the packages that elpy depends on? I would copy correspondingly each of them along with ~/.emacs.d/elpa/elpy/. I knew there is .emacs.d/elpa/complete/ needed. 

my .emacs setup related to elpy is:

```
(package-initialize)
(elpy-enable)

;; better syntax checking on the fly
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

;; setup jedi
(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:complete-on-dot t)                 ; optional

```

Please advise.
Jin

**Comment by jorgenschaefer** [comment]
You can use `HOME=/some/tmp/directory emacs` to start an Emacs instance with a fresh environment, use `M-x package-install` there, and then copy `/some/tmp/directory/.emacs.d/elpa/` over.

> Could you please list the packages that elpy depends on?

I can give you a list of packages that Elpy depends on directly. I can not give you a full list of all packages those depend on.

> (add-hook 'python-mode-hook 'jedi:setup)

This is the emacs-jedi package, which is unrelated and conflicting with Elpy.

**Comment by galactica147** [comment]
Thank you Jorgen! I finally got it working as you suggested!

**Comment by jorgenschaefer** [comment]
Great to hear! Enjoy Elpy :-)
