### ISSUE TITLE
I do not get that activates when open a _.py_

### ISSUE THREAD

**Issue by tanrax** [jorgenschaefer/elpy#929]
I do not get that activates when open a _.py_ . What if enabled me is the _python-mode_, but not the _elpy-mode_. I intendo with:
```
(elpy-enable)
(setq elpy-rpc-backend "jedi")
(add-hook 'python-mode 'elpy-mode)
```

**Comment by tanrax** [comment]
Fix!
_(add-hook 'python-mode-hook 'elpy-mode)_

**Comment by jorgenschaefer** [comment]
Hello! Glad you fixed it, but this is strange – `elpy-enable` already adds `elpy-mode` to `python-mode-hook` …
