### ISSUE TITLE
elpy emacs emitting error messages related to "not running as root"

### ISSUE THREAD

**Issue by ssefick** [jorgenschaefer/elpy#934]
Hello:

I am using system python 2.7.5 on Scientific Linux 7.2. I am using system emacs 24.3.1. I am using elpy 1.12.0.

I am using elpy and receiving this message when ever I try to move around in the buffer:
dm.c: 1693: not running as root returning empty list
** Message: pygobject_register_sinkfunc is deprecated (GstObject)

I will provide any information that is germane to helping troubleshoot this error. I appreciate all of the help.

**Comment by ssefick** [comment]
Bump

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. I am sorry for the delayed response, but I only have time to work on this project roughly once a week.

> dm.c: 1693: not running as root returning empty list
> ** Message: pygobject_register_sinkfunc is deprecated (GstObject)

This means that some module you have installed emits these messages. That's unrelated to Elpy, it just tells you that it received these messages in case they are helpful to you. I do not know what module emits these. You can safely ignore the buffer with those messages, as far as Elpy is concerned.

Does this help?

**Comment by ssefick** [comment]
Hello, and I appreciate your response. I am sorry for being impatient. This is helpful, but is there anyway to mute these warnings within elpy? The warning buffer pops up and covers the interactive python session. Thank you again for all of the help!
kindest regards,

Stephen

**Comment by jorgenschaefer** [comment]
> The warning buffer pops up and covers the interactive python session.

If you bury the buffer (just switch back to the interactive python) after it appears for the first time, as opposed to killing it, it should not pop up again. If it does, that's a bug. Can you try and see if that works?

**Comment by ssefick** [comment]
I am sorry for the late reply. switching back to the interactive buffer does fix this problem. 

I will report back if this does not work when I am working on a larger project.

Thank you for all of the help.

**Comment by jorgenschaefer** [comment]
Glad to hear it works now. I'll close this issue, but please do not hesitate to re-open it or open a new one if you have further problems. Enjoy Elpy! :-)
