### ISSUE TITLE
Fail to activate python

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [jorgenschaefer/elpy#939]
Hi, I am a total newbie in Emacs. I encountered a problem when installing elpy. 

My computer is macbook with OSX 10.11.6.

I install python use pyenv and anaconda. Actually, I install pyenv first and then install anaconda in it. So my python's path is `/Users/apple/.pyenv/versions/anaconda2-4.0.0/bin/python`. Everytime when I use python, I need to type `pyenv shell anaconda2-4.0.0` in terminal. The following is my elpy config:

```
Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: Not found (0.9.0 available)
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.2.4 available)
Yapf..............: Not found (0.11.0 available)
Syntax checker....: Not found (flake8)
```

I install all the dependencies in anaconda2 and elpy always directs to the system python. I am wondering how to config this setting?

If possible, could any one give me a specific statement of init.el?

Thanks a lot!

**Comment by jorgenschaefer** [comment]
Hello! You can use `elpy-rpc-python-command` to tell Elpy the full path to the Python interpreter. Alternatively, you can set `exec-path` to point to the right environment. There's a `pyenv` package for Emacs that allows you to use different pyenv environments from within Emacs.

Does this help?

**Comment by Xiaoming-Zhao** [comment]
@jorgenschaefer 

Hi Jorgen, thanks a lot for your kind reply. I tried type `(elpy-rpc-python-command '/Users/apple/.pyenv/versions/anaconda2-4.0.0/bin/python)` in my `init.el` but it told me `Symbol's function definition is void: elpy-rpc-python-command`. The list is my `init.el`, which is set following this [tutorial](https://realpython.com/blog/python/emacs-the-best-python-editor/). I would really appreciate it if you could tell me where to insert the config statement:

```
;; init.el --- Emacs configuration

;; INSTALL PACKAGES
;; --------------------------------------

(require 'package)

(add-to-list 'package-archives
       '("melpa" . "http://melpa.org/packages/") t)

(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))

(defvar myPackages
  '(better-defaults
    ein
    elpy
    flycheck
    material-theme
    py-autopep8))

(mapc #'(lambda (package)
    (unless (package-installed-p package)
      (package-install package)))
      myPackages)

;; BASIC CUSTOMIZATION
;; --------------------------------------

(setq inhibit-startup-message t) ;; hide the startup message
(load-theme 'material t) ;; load material theme
(global-linum-mode t) ;; enable line numbers globally

;; PYTHON CONFIGURATION
;; --------------------------------------

(elpy-enable)
(elpy-rpc-python-command '/Users/apple/.pyenv/versions/anaconda2-4.0.0/bin/python)
(elpy-use-ipython)

;; use flycheck not flymake with elpy
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

;; enable autopep8 formatting on save
(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

;; init.el ends here
```

PS. About pyenv, do you mean that I need to install the package in order to use pyenv?

Thanks a lot!

**Comment by jorgenschaefer** [comment]
Can you try `(setq elpy-rpc-python-command "/Users/apple/.pyenv/versions/anaconda2-4.0.0/bin/python")` instead? It's a variable and expects a string :-)

> PS. About pyenv, do you mean that I need to install the package in order to use pyenv?

You don't need to, but it helps. It provides the equivalent of `pyenv shell ...` command for Emacs.

**Comment by Xiaoming-Zhao** [comment]
@jorgenschaefer 
Hi Jorgen, thans a lot for your quick reply! However, it also failed and told me the same error `Symbol's function definition is void: elpy-rpc-python-command` when I tried your statement. Could you give me some suggestion? Thanks a lot!

**Comment by jorgenschaefer** [comment]
That means you still have `(elpy-rpc-python-command ...)` in your init file somewhere. It's not a function, it should not be used right after an opening parenthesis. :-) If you can't find the problem, post your full init file contents.

**Comment by Xiaoming-Zhao** [comment]
@jorgenschaefer 
Hi Jorgen, because I have just installed emacs, I deleted all the contents in `init.el` and want to reinstall `elpy`. I follow your Quick Installation guide. However, when I type `M-x package-refresh-contents`, it just hang on the procedure `Contacting host: elpa.gnu.org:80`:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Mark set
Contacting host: jorgenschaefer.github.io:443
Opening TLS connection to `jorgenschaefer.github.io'...
Opening TLS connection with `gnutls-cli --insecure -p 443 jorgenschaefer.github.io'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 jorgenschaefer.github.io --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect jorgenschaefer.github.io:443 -no_ssl2 -ign_eof'...done
Opening TLS connection to `jorgenschaefer.github.io'...done
Contacting host: melpa.org:443
Opening TLS connection to `melpa.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof'...done
Opening TLS connection to `melpa.org'...done
Contacting host: elpa.gnu.org:80
```

I searched but could not solve it. Do you have any ideas? Thanks a lot!

**Comment by jorgenschaefer** [comment]
Is Emacs unresponsive after that? If so, your network connection to GNU ELPA is not responsive. I do not know why.

**Comment by Xiaoming-Zhao** [comment]
@jorgenschaefer 
Hi Jorgen. I install `elpy` successfully now. However, I direct the python to my anaconda version, see the `config` below:

```
Virtualenv........: None
RPC Python........: 2.7.12 (/Users/apple/.pyenv/versions/anaconda2-4.0.0/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0
Rope..............: 0.9.4 (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.11.0
Syntax checker....: Not found (flake8)
```

However, when I try something, the version is not right, see the screenshot below:
<img width="591" alt="screen shot 2016-07-22 at 12 56 42" src="https://cloud.githubusercontent.com/assets/9215584/17066263/deba3f2a-500b-11e6-92b9-d6a2b23fa2aa.png">

Any ideas? Thanks a lot!

**Comment by jorgenschaefer** [comment]
You are showing the interactive Python interpreter in that screenshot, not the RPC process (the Python Elpy talks to):

> `Interactive Python: python (/usr/bin/python)`

You can change that similarly to the other using the variable `python-shell-interpreter`.

**Comment by Xiaoming-Zhao** [comment]
@jorgenschaefer 

Thank you very much from the bottom of my heart! You really do me a big favour! One last thing, when I use `(elpy-use-ipython)`, it told me `error: Command "ipython" not found`. However, I truly install python in my anaconda version. Is it possible to fix it? Thanks a lot for your patience!

**Comment by jorgenschaefer** [comment]
You're running into the same problem over and over again – you do not set your PATH correctly, so Emacs won't find any programs installed there :-) Again, you can either set `python-shell-interpreter` to the full path to your ipython program, or you set your `PATH` and `exec-path` correctly. The pyenv package (and pyvenv for virtualenvs) can do that for you.

**Comment by Xiaoming-Zhao** [comment]
Actually, there are something weird. Please look the two images below. The first is the start screen and it tells the `ipython` fails. However, when I type `C-c C-c`, it works. I have no ideas about this.

<img width="584" alt="screen shot 2016-07-22 at 13 45 26" src="https://cloud.githubusercontent.com/assets/9215584/17067771/e1ea5552-5012-11e6-8f7c-c2652840c492.png">
<img width="585" alt="screen shot 2016-07-22 at 13 45 52" src="https://cloud.githubusercontent.com/assets/9215584/17067774/e49dc2ac-5012-11e6-8d67-d87bd7824799.png">

**Comment by jorgenschaefer** [comment]
Yes, `elpy-use-ipython` tries to make sure you have ipython installed. As you do not have the PATH set correctly, it does not find it. You can tell `elpy-use-ipython` where to find it, by using `(elpy-use-ipython "/full/path/to/ipython")`.

**Comment by Xiaoming-Zhao** [comment]
@jorgenschaefer 

Thank you very much! Sincere thanks for your patience to help such a green bird! Best regards!

**Comment by jorgenschaefer** [comment]
You are welcome! Glad it works now, and enjoy Elpy. :-)
