### ISSUE TITLE
Quite unclear how to add arguments to e.g. yapf and pytest

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#943]
I was wondering how I could add --pdb and -x to the pytest command?
"elpy-test" seems nicer than "pytest-pdb-all", but I would really like elpy-test to drop into pdb on some mistake.

**Comment by jorgenschaefer** [comment]
You can customize `elpy-test-pytest-runner-command` like `(setq elpy-test-pytest-runner-command '("py.test" "--pdb" "-x"))`.

Does this help? :-)

**Comment by kootenpv** [comment]
That helps, thanks!

**Comment by jorgenschaefer** [comment]
Glad to hear that. I'll close this issue then, but please do not hesitate to open a new one if you have any further problems or questions. Enjoy Elpy! :-)
