### ISSUE TITLE
elpy-config stuck in an infinite loop

### ISSUE THREAD

**Issue by spraharsh** [jorgenschaefer/elpy#945]
Hello, I've just started trying to use emacs. when I installed elpy and tried to see it's configuration using elpy-config it gets stuck in an infinite loop. any solutions

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Could you run `M-x toggle-debug-on-quit` and hit `C-g` when Elpy is stuck? This should produce a backtrace you can post here.

Elpy tries to fetch the latest versions from pypi when you run `M-x elpy-config`. Could that be the problem? Can Elpy access the internet from your system?

**Comment by ajsteven130** [comment]
Hello - how long did you wait for something to happen? For me `elpy-config` takes around 2 minutes (I just timed it) and locks up emacs while it is working. 

Note: this is not a complaint, just an observation that, maybe, its not actually in an infinite loop but instead just taking a long time.

**Comment by jorgenschaefer** [comment]
_I_ would complain about that locking up Emacs for 2 minutes! :-D Created #950 to track possibly making this non-blocking.

**Comment by spraharsh** [comment]
yep, thanks. I thought it was stuck since emacs seemed(I thought) down.

**Comment by mbtuckersimm** [comment]
First, thanks so much for your work on elpy, it is much appreciated.

I'm experiencing the same issue described above: `elpy-config` seems to never complete (it used to be working fine, and I don't think I changed anything relevant in my config). On a couple of occasions it has finished after a few minutes, but usually I run out of patience first. Here's the relevant info I can gather, please let me know if anything else is needed:

Emacs version: 26.1
Elpy version: 20190416.1701
Elpy (python package) version: 1.28
Python version: 3.6.7 (in a virtual environment, which I activated before calling `elpy-config`)

Elpy configuration in `init.el`:
```
(use-package elpy
  :config
  (elpy-enable)
  ;; disable flymake since we use flycheck instead
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  :ensure t)
```

And here is the backtrace when I turn on debug-on-quit and quit after `elpy-config` runs for a couple minutes:
```
Debugger entered--Lisp error: (quit)
  call-process("python" nil #<buffer  *temp*> nil "-c" "import json\nimport sys\nimport warnings\n\nwarnings.filterwarnings('ignore', category=FutureWarning)\n\ntry:\n    import xmlrpclib\nexcept ImportError:\n    import xmlrpc.client as xmlrpclib\n\nfrom distutils.version import LooseVersion\n\n\ndef latest(package, version=None):\n    try:\n        with xmlrpclib.ServerProxy('https://pypi.python.org/pypi') as pypi:\n            latest = pypi.package_releases(package)[0]\n        if version is None or LooseVersion(version) < LooseVersion(latest):\n            return latest\n        else:\n            return None\n    except:\n        return None\n\n\nconfig = {}\nconfig['python_version'] = ('{major}.{minor}.{micro}'\n                            .format(major=sys.version_info[0],\n                                    minor=sys.version_info[1],\n                                    micro=sys.version_info[2]))\n\ntry:\n    import elpy\n    config['elpy_version'] = elpy.__version__\nexcept:\n    config['elpy_version'] = None\n\ntry:\n    import jedi\n    if isinstance(jedi.__version__, tuple):\n        config['jedi_version'] = '.'.join(str(x) for x in jedi.__version__)\n    else:\n        config['jedi_version'] = jedi.__version__\n    config['jedi_latest'] = latest('jedi', config['jedi_version'])\nexcept:\n    config['jedi_version'] = None\n    config['jedi_latest'] = latest('jedi')\n\ntry:\n    import rope\n    config['rope_version'] = rope.VERSION\n    if sys.version_info[0] <= 2:\n        config['rope_latest'] = latest('rope', config['rope_version'])\n    else:\n        config['rope_latest'] = latest('rope_py3k', config['rope_version'])\nexcept:\n    config['rope_version'] = None\n    config['rope_latest'] = latest('rope')\n\ntry:\n    import autopep8\n    config['autopep8_version'] = autopep8.__version__\n    config['autopep8_latest'] = latest('autopep8', config['autopep8_version'])\nexcept:\n    config['autopep8_version'] = None\n    config['autopep8_latest'] = latest('autopep8')\n\ntry:\n    import yapf\n    config['yapf_version'] = yapf.__version__\n    config['yapf_latest'] = latest('yapf', config['yapf_version'])\nexcept:\n    config['yapf_version'] = None\n    config['yapf_latest'] = latest('yapf')\n\ntry:\n    import black\n    config['black_version'] = black.__version__\n    config['black_latest'] = latest('black', config['black_version'])\nexcept:\n    config['black_version'] = None\n    config['black_latest'] = latest('black')\n\njson.dump(config, sys.stdout)\n")
  elpy-config--get-config()
  elpy-config()
  funcall-interactively(elpy-config)
  call-interactively(elpy-config record nil)
  command-execute(elpy-config record)
  helm-M-x(nil #("elpy-config" 0 11 (match-part "elpy-config")))
  funcall-interactively(helm-M-x nil #("elpy-config" 0 11 (match-part "elpy-config")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```
I do not have installed in the virtualenv all of the packages that it's trying to import. In particular, I don't have `xmlrpclib`, `rope`, `autopep8`, or `black`.

I have a suspicion that the problem may lie in fetching latest versions from `pypi`, since `pip search <blah>` seems to take an inordinately long amount of time on my machine. So even if you can't solve that problem, it would be nice to make `elpy-config` not block the rest of emacs from working while it's doing its thing.

Once again, thanks for all your work, and let me know if there's anything I can do here.

**Comment by galaunay** [comment]
Hi,

Fetching versions of packages on Pypi can indeed be quite long.
It is annoying, but I personally only use this function on rare occasions, so I never bothered to find a proper solution.

We could make fetching the version asynchronous or optional if necessary.
I am curious, how often (and what for) do you use `elpy-config` ?

**Comment by mbtuckersimm** [comment]
I use `elpy-config` fairly often to explore the vast number of options that elpy presents. I know it's not necessary for everyday use of elpy, but for discovering options and setting them temporarily it's much simpler than editing config files.

**Comment by gopar** [comment]
This PR might solve your issues #1585

**Comment by mbtuckersimm** [comment]
Is that going to be merged into the main branch and released?

**Comment by gopar** [comment]
@mbtuckersimm just merged. Should show up in the next  melpa build

**Comment by Xunius** [comment]
Hi all,
I'm having the same problem, running `elpy-config` seems to stuck for at least 15 mins for me, and I've tried multiple times, none finished unless I type `C-g`. First time running `C-g` shows `Waiting for process to die...(type C-g again to kill it instantly)`. But the wait never finishes, I've to `C-g` again.

I also toggled `M-x toggle-debug-on-quit`, but when quitting the `elpy-config` command, I don't know where to look for the debug info, it is supposed to be in a "backtrace" buffer, isn't it? But I don't see any such buffer in my buffer list. (I'm very new to emacs so I apologize for my innocent about it).

**Comment by gopar** [comment]
Hey thanks for filing a bug report.

Can you try `M-x toggle-debug-on-error` instead? (Notice how it's not `toggle-debug-on-quit`)

Run the cmd before doing `elpy-config`, that should open up a buffer named `*Backtrace*`, once that happens please copy and paste the buffer onto here so we can take a look at it :)

Thanks!

**Comment by Xunius** [comment]
@gopar Thanks for the suggestion. I tried `toggle-debug-on-error` alone and `toggle-debug-on-error` with `toggle-debug-on-quit`, doesn't seem to make a difference, I still don't see `*Backtrace*` buffer.

**Comment by galaunay** [comment]
As the issues are probably related, I think we can continue this discussion in #1588.
