### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by cladonia** [jorgenschaefer/elpy#946]
Hi Jorgen, 

I appreciate your help setting up elpy. 
I followed your instructions on https://github.com/jorgenschaefer/elpy/wiki/Installation. 
Everything seems fine up to the point `M-x package-install RET elpy RET`, when I receive the error 
`Symbol's function definition is void: autocompile `. Interestingly, I find no results when I google this error. 

I attached the error log and the content of my .emacs to help track down the problem. 
I am running Aquamacs 3.2 GNU Emacs 24.4.51.2
(x86_64-apple-darwin14.0.0, NS apple-appkit-1343.14)
on OS X 10.11.6

[emacs_log.txt](https://github.com/jorgenschaefer/elpy/files/406942/emacs_log.txt)
[dot_emacs.txt](https://github.com/jorgenschaefer/elpy/files/406940/dot_emacs.txt)

**Comment by cladonia** [comment]
After rebuilding my .emacs from scratch, I realized that I had the stray line `(add-hook 'after-save-hook 'autocompile)` that caused all the trouble. Your package works great. Thank you!

**Comment by jorgenschaefer** [comment]
Happy to hear this solved itself :-) And also glad you like Elpy, enjoy!
