### ISSUE TITLE
Using ipython with Elpy

### ISSUE THREAD

**Issue by wonbyte** [jorgenschaefer/elpy#949]
Hi,
I am trying to get ipython to be my default interpreter with ELPY.

Here is my current ELPY config:
```

(add-hook 'python-mode-hook 'elpy-mode)
(with-eval-after-load 'elpy
  (remove-hook 'elpy-modules 'elpy-module-flymake)
  (add-hook 'elpy-mode-hook 'elpy-rpc-python-command "python3")
  (add-hook 'elpy-mode-hook 'flycheck-mode)
  (add-hook 'elpy-mode-hook 'elpy-use-ipython)
  (add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save))
```

After I start emacs, I use the pyvenv-activate command to load my virtualenv with all the required pip packages for ELPY.

I then have to run M-x run-python to get the elpy RPC process to start (Does it not automatically start up?)

When I run C-c C-C to send my code to the REPL it is using the standard Python 3 REPL and not the IPython one. 

I am not sure what I am doing wrong to get IPython to be my default REPL.

Here is my ELPY Config

Elpy Configuration
```

Virtualenv........:  (/Users/gsieran/src/python/dive-into-python3/)
RPC Python........: 3.5.2 (/Users/gsieran/src/python/dive-into-python3/bin/python)
Interactive Python: ipython (/Users/gsieran/src/python/dive-into-python3/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.11.0
Syntax checker....: flake8 (/Users/gsieran/src/python/dive-into-python3/bin/flake8)
```

Thank you for the help

**Comment by yitang** [comment]
'(elpy-use-ipython "ipython3")' would do

**Comment by wonbyte** [comment]
Thanks @yitang . I added that to my init.el like so:

```
(add-hook 'python-mode-hook 'elpy-mode)
(with-eval-after-load 'elpy
  (remove-hook 'elpy-modules 'elpy-module-flymake)
  (add-hook 'elpy-mode-hook 'flycheck-mode)
  (add-hook 'elpy-mode-hook 'elpy-use-ipython "ipython3")
  (add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save))
```

Strangely, my ipython REPL that pops up looks like this:
<img width="1436" alt="screen shot 2016-08-11 at 11 59 19 am" src="https://cloud.githubusercontent.com/assets/681965/17597321/d90ee56c-5fba-11e6-9d23-28c6c94c0243.png">


Any ideas what is going on here?

**Comment by yitang** [comment]
are you using ipython3 5.0?  if so, add this 
`  (setq python-shell-interpreter "ipython3"
    python-shell-interpreter-args "--simple-prompt --pprint")`

**Comment by wonbyte** [comment]
Thanks @yitang that fixed my prompt. Just curious why this is now needed to make the prompt display correctly?

**Comment by yitang** [comment]
ipython 5 use new terminal interface, see http://emacs.stackexchange.com/questions/24453/weird-shell-output-when-using-ipython-5

Best wishes, 

Yi Tang

**Comment by wonbyte** [comment]
Thanks @yitang , last question. Every time I start up emacs I need to run M-x run-python so the ELPY RPC process can use it (I believe), is there a way to automatically start this up?

**Comment by yitang** [comment]
emmmmm. I always have a running Python process when I edit/browser Python scrip, if there's not one, I'd hit c + RET to start one, this would solve the problem.  

there are ways to automatically call run-Python but I am not sure this is a good idea in practise. plz check with the author, maybe open a new issue? 

Best wishes, 

Yi Tang

**Comment by wonbyte** [comment]
Big thanks for all the help!

**Comment by jorgenschaefer** [comment]
Nice to see this was handled even without me looking, thanks a lot! :-)

Just a quick note:

> Every time I start up emacs I need to run M-x run-python so the ELPY RPC process can use it (I believe), is there a way to automatically start this up?

Elpy's RPC process is completely unrelated to the Python shell start with `M-x run-python`. You do not need to do `M-x run-python` to use anything in Elpy.

**Comment by yitang** [comment]
hey @jorgenschaefer, that's awesome, thanks for letting us know!
