### ISSUE TITLE
error in process filter: Symbol's value as variable is void: --cl---cl-var--38800--

### ISSUE THREAD

**Issue by kennychen614** [jorgenschaefer/elpy#960]
Emacs got hanging when typing, in my example

```
class A(object):
  __slot             **--> when hit here, it hang and print error message**                       
```   

Elpy configuration as below:

Virtualenv........: None
RPC Python........: 2.7.12 (/home/ken/myworkspace/localinstallation/bin/python)
Interactive Python: ipython (/home/ken/myworkspace/localinstallation/bin/ipython)
Emacs.............: 24.3.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.11.0 (0.11.1 available)
Syntax checker....: flake8 (/home/ken/myworkspace/localinstallation/bin/flake8)

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report! Could you run `M-x toggle-debug-on-error` and reproduce this to get a backtrace you can post here? Thanks!

**Comment by kennychen614** [comment]
Debugger entered--Lisp error: (void-variable --cl---cl-var--38800--)
  signal(void-variable (--cl---cl-var--38800--))
  elpy-rpc--default-error-callback((void-variable --cl---cl-var--38800--))
  elpy-promise-reject([*elpy-promise* #[257 "\303 \210\301\203 \304\300\"\202  \300G\nV\203 \305\306\307\300\"!\202  \310!\207" [#("__sl" 0 4 (fontified t)) #[257 "\211\203 \301@\307=\204 \301\240\207\306\f\300\310!BC
\311\312DC\216\313\302\303\304\305$)\207" [#("__sl" 0 4 (fontified t)) (done) #<buffer slots.py> #<window 3 on slots.py> 114 81 elpy-company-backend done company--preprocess-candidates funcall #[0 "?\205\n \303\211\211\207" [company-candidates company-backend company-candidates-cache nil] 3 "\n\n(fn)"] company-idle-begin company-backend company-candidates-cache] 6 "\n\n(fn CANDIDATES)"] company-minimum-prefix-length elpy-company--cache-clear elpy-company--cache-completions elpy--sort-and-strip-duplicates company-dabbrev-code candidates nil] 6 "\n\n(fn RESULT)"] elpy-rpc--default-error-callback #<buffer slots.py> nil] (void-variable --cl---cl-var--38800--))
  #[257 "\301\300\"\207" [[*elpy-promise* #[257 "\303 \210\301\203 \304\300\"\202  \300G\nV\203 \305\306\307\300\"!\202  \310!\207" [#("__sl" 0 4 (fontified t)) #[257 "\211\203 \301@\307=\204 \301\240\207\306\f\300\310!BC
\311\312DC\216\313\302\303\304\305$)\207" [#("__sl" 0 4 ...) (done) #<buffer slots.py> #<window 3 on slots.py> 114 81 elpy-company-backend done company--preprocess-candidates funcall #[0 "?\205\n \303\211\211\207" [company-candidates company-backend company-candidates-cache nil] 3 "\n\n(fn)"] company-idle-begin company-backend company-candidates-cache] 6 "\n\n(fn CANDIDATES)"] company-minimum-prefix-length elpy-company--cache-clear elpy-company--cache-completions elpy--sort-and-strip-duplicates company-dabbrev-code candidates nil] 6 "\n\n(fn RESULT)"] elpy-rpc--default-error-callback #<buffer slots.py> nil] elpy-promise-reject] 4 "\n\n(fn ERR)"]((void-variable --cl---cl-var--38800--))
  funcall(#[257 "\301\300\"\207" [[*elpy-promise* #[257 "\303 \210\301\203 \304\300\"\202  \300G\nV\203 \305\306\307\300\"!\202  \310!\207" [#("__sl" 0 4 (fontified t)) #[257 "\211\203 \301@\307=\204 \301\240\207\306\f\300\310!BC
\311\312DC\216\313\302\303\304\305$)\207" [#("__sl" 0 4 ...) (done) #<buffer slots.py> #<window 3 on slots.py> 114 81 elpy-company-backend done company--preprocess-candidates funcall #[0 "?\205\n \303\211\211\207" [company-candidates company-backend company-candidates-cache nil] 3 "\n\n(fn)"] company-idle-begin company-backend company-candidates-cache] 6 "\n\n(fn CANDIDATES)"] company-minimum-prefix-length elpy-company--cache-clear elpy-company--cache-completions elpy--sort-and-strip-duplicates company-dabbrev-code candidates nil] 6 "\n\n(fn RESULT)"] elpy-rpc--default-error-callback #<buffer slots.py> nil] elpy-promise-reject] 4 "\n\n(fn ERR)"] (void-variable --cl---cl-var--38800--))
  elpy-promise-resolve([*elpy-promise* #[257 "\303 \210\301\203 \304\300\"\202  \300G\nV\203 \305\306\307\300\"!\202  \310!\207" [#("__sl" 0 4 (fontified t)) #[257 "\211\203 \301@\307=\204 \301\240\207\306\f\300\310!BC
\311\312DC\216\313\302\303\304\305$)\207" [#("__sl" 0 4 (fontified t)) (done) #<buffer slots.py> #<window 3 on slots.py> 114 81 elpy-company-backend done company--preprocess-candidates funcall #[0 "?\205\n \303\211\211\207" [company-candidates company-backend company-candidates-cache nil] 3 "\n\n(fn)"] company-idle-begin company-backend company-candidates-cache] 6 "\n\n(fn CANDIDATES)"] company-minimum-prefix-length elpy-company--cache-clear elpy-company--cache-completions elpy--sort-and-strip-duplicates company-dabbrev-code candidates nil] 6 "\n\n(fn RESULT)"] elpy-rpc--default-error-callback #<buffer slots.py> nil] nil)
  elpy-rpc--handle-json(((id . 540) (result)))
  elpy-rpc--filter(#<process  *elpy-rpc [project:~/myworkspace/github/worktools/practice/ python:/home/ekaiqch/myworkspace/localinstallation/bin/python]*> "{\"result\": [], \"id\": 540}\n")

**Comment by jorgenschaefer** [comment]
Uh. That should never happen. Did you at some point recently upgrade Elpy (or some other package) and did not restart Emacs?

**Comment by kennychen614** [comment]
I did have restarted emacs, issue still exist.
I have tried to do package-refresh-contents and install elpy again, restart emacs, still have same issue.

**Comment by jorgenschaefer** [comment]
This really looks like a problem with incompatible byte-compiled files, i.e. elisp files compiled with a different Emacs than they are run with. I do not understand how Elpy could cause this error I'm afraid.

**Comment by kennychen614** [comment]
Right! I remove all elisp files and re-install, now it works! Thanks!

**Comment by jorgenschaefer** [comment]
Great to hear! Enjoy Elpy :-)
