### ISSUE TITLE
Changing default-directory for compilation

### ISSUE THREAD

**Issue by fresheed** [jorgenschaefer/elpy#963]
Hello and thank for your effort in Elpy!
When I try to launch my tests with C-c C-t, first line of *compilation* output tells me that default-directory is wrong (specifically, it's one level upper than project dir). 
Doing eval of default-directory in any Python buffer gives me correct path, but in *compilation* it still wrong. I can change it with (setq ...), but after relaunching tests it reloads to wrong value.
What is the correct way to specify default-directory?

**Comment by jorgenschaefer** [comment]
Elpy runs tests in the library root. If your current directory has an `__init__.py` file, Elpy assumes this directory is a package and moves up one directory. Does this help?

**Comment by fresheed** [comment]
Yes, thank you so much!
