### ISSUE TITLE
semantic-decoration-on-unknown-includes

### ISSUE THREAD

**Issue by jave** [jorgenschaefer/elpy#964]
Hello,

I have a trivial program:

import logging
logging.warn("a warning!")

"import logging" gets decorated by emacs with the face semantic-decoration-on-unknown-includes.

However, company manages to complete logging.w to logging.warn, which is good.

The reason i bring this up is that i have another more complex project, where completion does not work, so im suspecting this semantic problem.

**Comment by gopar** [comment]
@jave Is there anything that might turn semantic mod on when you enter a Python Buffer?

**Comment by jave** [comment]
@gopar : isnt semantic mode supposed to be on while entering a python buffer?

If semantic isnt needed, I can disable it

**Comment by gopar** [comment]
@java Do you need semantic mode on when using python? If not then I recommend you turn it off when entering python-mode.

**Comment by jave** [comment]
okay i will turn it off

**Comment by gopar** [comment]
Did that help? 

Elpy already does the things Semantic does(search, navigation, completion, etc)  plus more, so no reason to have semantic on unless you have a specific purpose for it.

**Comment by FredJiang** [comment]
```
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 ; '(semantic-decoration-on-unknown-includes ((t (:background "black" :foreground "red" :underline t))))
 ; '(semantic-decoration-on-unknown-includes ((t (:background "red")))))
 '(semantic-decoration-on-unknown-includes   ((t (:background nil)))))
```

![image](https://user-images.githubusercontent.com/1418862/56466293-577deb80-6442-11e9-9828-1583891dd6ff.png)

![image](https://user-images.githubusercontent.com/1418862/56466296-5cdb3600-6442-11e9-8478-805bab2715a2.png)
