### ISSUE TITLE
Try it! mode

### ISSUE THREAD

**Issue by humitos** [jorgenschaefer/elpy#967]
Hi,

I showed my emacs configuration to many people during last months a most of them got exited because all the shortcuts and hotkeys that I use everyday. So, the question is immediate:
- How I can configure that in my PC?

as you may know, the answer is not so simple for a developer that used to use Sublime, PyCharm or something like that.

Because of that, I've created a simple script in my emacs configuration called `tryit.sh` that runs all the needed commands to setup it without touching anything about your previous emacs configuration (in case you already have one). So, it's useful for two different case of uses:
1. the person doesn't know anything about emacs.
2. the person has his/her own emacs config but just want to try mine to see one of the features and decide if it's a wanted one.

This is my configuration: https://github.com/humitos/emacs-configuration
This is the `tryit.sh` script: https://github.com/humitos/emacs-configuration/blob/master/tryit.sh

What do you think? I think it's a good idea to implement something similar here because `elpy` is very popular on the internet and it's the first approach for those people that want a Python "IDE".

Thanks!

**Comment by jorgenschaefer** [comment]
I like quick and easy setups! I'm just not sure what such a shell script would do for Elpy. Adding `(elpy-enable)` to the init file is not too exciting. And non-interactively installing Emacs packages is not trivial, either. But I'm open to ideas.

**Comment by humitos** [comment]
Mmm... Well... The 'Quick Installation' from the readme file is more than that :)

What I did in my script is:

* suggest how to install emacs >= 24.4 if you have an old version in ubuntu (it could be more intelligent)
* create a virtualenv for emacs
* suggest how to fix the ubuntu and py3 venv module problem 
* install all the python packages using pip in the virtualenv created
* run emacs with all my own configuration and enable the just created venv
  * compile helm
  * load default yasnippets
  * etc...

**Comment by jorgenschaefer** [comment]
> Mmm... Well... The 'Quick Installation' from the readme file is more than that :)

If the rest was automateable, `elpy-enable` would do it :-)

> create a virtualenv for emacs

Virtualenvs should be per project, not one for Emacs.

> suggest how to fix the ubuntu and py3 venv module problem

I am not aware of this problem, do you have a link?

> compile helm

If Elpy ever depends on Helm, that'll happen automatically. Until then, Elpy does not provide Helm.

> load default yasnippets

That should happen by default already.

**Comment by humitos** [comment]
> Virtualenvs should be per project, not one for Emacs.

Yes, I do that in my configuration but if you want just to try it one venv is enough :)

>>    suggest how to fix the ubuntu and py3 venv module problem

> I am not aware of this problem, do you have a link?

This is what Ubuntu tells you.

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/humitos/.emacs.d/emacsenv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

**Comment by jorgenschaefer** [comment]
> This is what Ubuntu tells you.

I am using Debian. I have never seen this message. What are you doing to get that message?

**Comment by humitos** [comment]
```
[18:22] humitos: tmp> python3 -m venv tmp-env
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/tmp-env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

[18:22] humitos: tmp> 
```

**Comment by jorgenschaefer** [comment]
`python3 -m venv tmp-env` works without errors here on Debian, without `python3-venv` installed. Is this an Ubuntu-only problem?

**Comment by humitos** [comment]
Yes

**Comment by humitos** [comment]
Today, I built a Docker image using Alpine Linux and with all my configuration already setup. So, just run one command and you get everything configured without touching the user's computer.

    docker run --rm -it -e DISPLAY -v $(pwd):/src -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v $XAUTHORITY:/root/.Xauthority --net=host humitos/emacs-x11-alpine

I think it's a good thing to consider, otherwise, just close the issue :)

Reference: https://github.com/humitos/emacs-configuration

**Comment by ChillarAnand** [comment]
@humitos It is better to just install emacs and setup elpy. All other configurations are not required.

**Comment by jorgenschaefer** [comment]
@humitos I love the  idea of an Elpy-enabled Emacs as a docker image to test things. The file system separation is a bit of an annoyance for everyday use. I'd prefer not to recommend docker images I do not control at all in the official documentation, though. But that should not stop you from recommending this to others. :-)

Thank you for your work! As I'm not sure how I would provide a sensible "try it!" mode without too much effort, I'll close this issue. Please do not hesitate to open new ones if you have other good ideas, though!

**Comment by humitos** [comment]
> Please do not hesitate to open new ones if you have other good ideas

Don't worry. I'll do it :)

Thanks for your work in this amazing plugin, again.
