### ISSUE TITLE
elpy-enable not work?

### ISSUE THREAD

**Issue by smallst** [jorgenschaefer/elpy#968]
i used to use (elpy-mode 1) to enable elpy and everything goes well.
and recently i find when i change my config to (elpy-enable), it seems elpy not work? at least flymake won't check the error.

then i open a python file, call the elpy-enable , nothing happend. if i call elpy-mode, everything goes well. how can i find the mistake ?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! Some steps:

- After `elpy-enable`, `python-mode-hook` should contain `elpy-mode`. Does it? You can check with `C-h v python-mode-hook`
- Are Python files in `python-mode`?  You can check with `C-h v major-mode`
- Start Emacs with `emacs -Q`, run `M-x elpy-enable`, and open a Python file. Does that enable Elpy? If so, your config file has some problems. For example, it might override `python-mode-hook` after `elpy-enable`

**Comment by smallst** [comment]
thanks for reply.
follow your step i find something interesting:
1. after `elpy-enable`, `python-mode-hook` contains `elpy-mode`
2. python files are in `python-mode`

3.1:  i run `emacs -Q` , `package-initialize`, `elpy-enable` and open a python file. elpy works well.
3.2: i run `emacs -Q`, open a python file, `package-initialize`, `elpy-enable`, elpy not work, after close and reopen python file, elpy works well
3.3: so i try my config again, `emacs`, open python file. elpy not work , and i close buffer, reopen file, elpy works.


i use this config for python-mode(require in init.el):
````lisp
(setq interpreter-mode-alist
      (cons '("python" . python-mode) interpreter-mode-alist))

(defun python-mode-hook-setup ()
  (unless (is-buffer-file-temp)
    ;; run command `pip install jedi flake8 importmagic` in shell,
    ;; or just check https://github.com/jorgenschaefer/elpy
    (if (fboundp 'elpy-enable) (elpy-enable) (elpy-mode 1))
    ;; http://emacs.stackexchange.com/questions/3322/python-auto-indent-problem/3338#3338
    ;; emacs 24.4 only
    (setq electric-indent-chars (delq ?: electric-indent-chars))))

(add-hook 'python-mode-hook 'python-mode-hook-setup)

(provide 'init-python-mode)
````
i think elpy-enable should exec before python file open, is this right?  if so, how can i edit my config so that elpy would work when i first open a python file?

**Comment by jorgenschaefer** [comment]
> i think elpy-enable should exec before python file open, is this right?

Yes.

> if so, how can i edit my config so that elpy would work when i first open a python file?

Put `(elpy-enable)` at the top level of the file, not inside a function that runs in a mode hook.

**Comment by smallst** [comment]
Thanks a lot!

**Comment by kprojiang** [comment]
I'm wondering, why does it happen that `(add-hook 'python-mode-hook 'elpy-mode)` works, even if  my init.el doesn't contain `(elpy-enable)`?
