### ISSUE TITLE
Feature Request - Django - sr-speedbar

### ISSUE THREAD

**Issue by MortalCatalyst** [jorgenschaefer/elpy#97]
Hi

Now that most os's have updated to emacs 24.3 and now use new python.el iwas wondering if you would incorporate python -django into elpy 
Link http://from-the-cloud.com/en/emacs/2013/01/28_emacs-as-a-django-ide-with-python-djangoel.html

Also as a nice addition in emacs sr-speedbar.

Cheers 

Sayth

**Comment by gopar** [comment]
Elpy now has some Django support
