### ISSUE TITLE
`elpy-nav-indent-shift-left` is useless and hijacks a useful binding

### ISSUE THREAD

**Issue by sam-s** [jorgenschaefer/elpy#970]
`elpy-nav-indent-shift-left` and `elpy-nav-indent-shift-right` are useless because `TAB` and `C-x TAB` (`indent-rigidly`) can do everything they can and are standard in Emacs.

At the same time, they hijack the important keys:
* `<M-left>` runs the command `left-word`
* `<M-right>` runs the command `right-word`

I strongly suggest that you make the bindings optional.
I also suggest that you remove both functions.
Less is sometimes more!

**Comment by jorgenschaefer** [comment]
> `elpy-nav-indent-shift-left` and `elpy-nav-indent-shift-right` are useless because `TAB` and `C-x TAB` (`indent-rigidly`) can do everything they can and are standard in Emacs.

This is incorrect. shift-left/shift-right work quite differently from TAB, especially with active selections.

You can disable Elpy's key bindings by setting them to `nil` in `elpy-mode-map` if you don't like them.

I also strongly suggest that you work on the way you phrase your issues. Being less hostile is sometimes more useful for communication.

**Comment by sam-s** [comment]
I am sorry if I came through as hostile.
I am not, and I do not intend to.

However, IMHO, `C-x TAB` with prefix arguments can do everything `C-<left>` and `C-<right>` can. (If this is not the case, I would love to hear what they offer).

Thanks for the hint, I now disabled the binding.

**Comment by jorgenschaefer** [comment]
You can use M-left/M-right in Elpy to move the current selection interactively back and forth until it is where you want it to be. With `indent-rigidly`, you have to figure out (count!) where to move it first.

The difference is much the same as between C-up/C-down and `goto-line` (or even `goto-char`).

**Comment by sam-s** [comment]
Hmm, I guess you are right.
I am too old school - I know where I want my code to be :-)
