### ISSUE TITLE
elpy error after upgrading to ipython 5.1.0

### ISSUE THREAD

**Issue by kirk86** [jorgenschaefer/elpy#973]
Hello, I've notice the following errors when launching the elpy ipython buffer session, after upgrading to ipython 5:

```
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

[J[?7h[?12l[?25h[?2004l
[?12l[?25h
[J[?7h[?12l[?25h[?2004l
[?12l[?25h
[J[?7h[?12l[?25h[?2004l
[?12l[?25h
[J[?7h[?12l[?25h[?2004l
[?12l[?25h print('test')
[J[?7h[?12l[?25h[?2004ltest

[?12l[?25h
```

Any idea on how to resolve them?

Thanks in advance!

**Comment by kirk86** [comment]
Solved it by re-installing some missing packages from `elpy-config`. One question though. In my espy-config it shows that is using python instead of ipython even-though I specified in `init.el` to use ipython via `elpy-use-ipython`. Any ideas?

**Comment by kirk86** [comment]
I guess I spoke too fast. The issue is not present if one uses python bind to `C-c C-c` but it is persistent if you use ipython with `C-c C-c`....

**Comment by jorgenschaefer** [comment]
This is a misfeature in IPython 5, see #908 – could you add `(setenv "IPY_TEST_SIMPLE_PROMPT" "1")` to your config file and see if that solves things?

**Comment by kirk86** [comment]
@jorgenschaefer Thanks a lot the magic happened. Just to note for others maybe also interested I also tried `(setenv "JUPYTER_CONSOLE_TEST" "1") ` but in my case it didn't work. `(setenv "IPY_TEST_SIMPLE_PROMPT" "1")` did the trick for me 👍.

**Comment by jorgenschaefer** [comment]
Glad to hear it worked! Enjoy Elpy :-)
