### ISSUE TITLE
Elpy missing function signatures

### ISSUE THREAD

**Issue by vikigenius** [jorgenschaefer/elpy#975]
I am using elpy with company here is the output of my elpy-config

`Elpy Configuration`

`Virtualenv........:  (/home/vikash/lpackages/anaconda3/envs/droidtest/)`
`RPC Python........: 2.7.12 (/home/vikash/lpackages/anaconda3/envs/droidtest/bin/python)`
`Interactive Python: ipython (/home/vikash/lpackages/anaconda3/envs/droidtest/bin/ipython)`
`Emacs.............: 24.3.1`
`Elpy..............: 1.12.0`
`Jedi..............: 0.9.0`
`Rope..............: Not found (0.10.3 available)`
`Importmagic.......: 0.1.7`
`Autopep8..........: 1.2.4`
`Yapf..............: 0.11.1`
`Syntax checker....: flake8 (/home/vikash/lpackages/anaconda3/envs/droidtest/bin/flake8)`

`[+]-- Group Elpy`
`[+]-- Group Python`
`[+]-- Group Virtual Environments (Pyvenv)`
`[+]-- Group Completion (Company)`
`[+]-- Group Call Signatures (ElDoc)`
`[+]-- Group Inline Errors (Flymake)`
`[+]-- Group Snippets (YASnippet)`
`[+]-- Group Directory Grep (rgrep)`
`[+]-- Group Search as You Type (ido)`

Now i installed a package AndroidViewClient:

look at the following lines of code:

`vc = viewclient(device, serialno)`

vc is now an object of class viewclient
Now typing **vc.** only shows few function signatures of the class viewclient, there are many more functions in the class which are not shown, what  is the possible reason for this?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question :-)

> what is the possible reason for this?

Python is a highly dynamic language, and providing auto-completion, member lists, etc. relies on heuristics and some good guesswork. Jedi is doing a great job at that, but it's not perfect, and can sometimes (regularly) get things wrong. This is especially true for native libraries not written in Python.

I hope that explains things?

**Comment by vikigenius** [comment]
Thanks, i understand, i guess i have just gotten used to really good auto-completion till now, this is the first time i am noticing an issue, do you have any idea if using rope might give better completion?

**Comment by jorgenschaefer** [comment]
> do you have any idea if using rope might give better completion?

Sometimes. And sometimes, Jedi has more completions. It's really a coin toss between the two, sadly.

> And can you point me to the part of the source which handles the completion, i would like to see how the completions work.

Which part? Part of Elpy is written in Emacs Lisp which talks to a separate Elpy process written in Python. Which again uses the jedi/rope libraries.

**Comment by vikigenius** [comment]
Oh, so the entire completions is handled by jedi as a backend, i will look into their project then, thanks for the info anyway.

**Comment by gopar** [comment]
Closing since answered and is not an elpy issue
