### ISSUE TITLE
Making python3 default

### ISSUE THREAD

**Issue by amirteymuri** [jorgenschaefer/elpy#979]
I have made python3 the default version for my system (i have put `alias python=python3` in ~/.bashrc file). Now when i run python in terminal i get python 3.4.2, but starting the interpreter for elpy runs still python2. How can i change it to be python3 there too?

**Comment by gopar** [comment]
You can set the python version by

```python
(setq elpy-rpc-python-command "python3")
```

**Comment by amirteymuri** [comment]
I suppose i should put it in my `init.el`? But doing `C-c C-z` still trigger the 2.7.9. What am i doing wrong?

**Comment by gopar** [comment]
There are different variables. The `elpy-rpc-python-command` is for the interpreter that the RPC backend will use (Elpy) and then what shell you want to run which is `python-shell-interpreter`.

So all together it should look like this in your `init.el`
```elisp
;; For elpy
(setq elpy-rpc-python-command "python3")
;; For interactive shell
(setq python-shell-interpreter "python3")
```

**Comment by gopar** [comment]
Did that solve the question you had?

**Comment by gopar** [comment]
Closing since no updates
