### ISSUE TITLE
Make C-c C-z remember the location jumped from to jump back to

### ISSUE THREAD

**Issue by JunnanZ** [jorgenschaefer/elpy#984]
Hi,

When I'm in the inferior python buffer and press C-c C-z, it should jump to the last viewed python script buffer, but it seems to jump to any buffer I last viewed. The elisp code also proves that:
```
(defun elpy-shell-switch-to-buffer ()
  "Switch from inferior Python process buffer to recent Python buffer."
  (interactive)
  (pop-to-buffer (other-buffer (current-buffer) 1)))
```
I think it would be easy to filter the buffer list and only pop to the first item in the list which is python mode, or something like that. However, I'm not familiar with elisp, so would you mind providing a refined version of this function?

Many thanks.

**Comment by gopar** [comment]
@jorgenschaefer Perhaps an idea is to have a custom variable that lets the user decide if they want to go back to the most recent python buffer or just any arbitrary buffer? 

@JunnanZ 
This little snippet of code should do what you want
```lisp
(defun elpy-shell-switch-to-buffer ()
  "Switch from inferior Python process buffer to recent Python buffer."
  (interactive)
  (let ((buffers (buffer-list)))
  (while buffers
    (when (with-current-buffer (car buffers) (string= "python-mode" major-mode))
      (pop-to-buffer (car buffers))
      (setq buffers nil))
    (setq buffers (cdr buffers)))))
```

**Comment by JunnanZ** [comment]
@gopar Thanks! That's exactly what I want! BTW, elisp is so verbose and hard to learn:(

**Comment by gopar** [comment]
@JunnanZ Hey!

Elisp takes a little getting used too (I know it took me a while) but just practice reading source code for smaller packages and work your way up to bigger packages. \o/

**Comment by jorgenschaefer** [comment]
Making `C-c C-z` save the last location and use that sounds like a good idea to me. :-)

**Comment by JunnanZ** [comment]
@jorgenschaefer I'm a little bit confused, but did the original function exactly do that? I still think jumping back to the last python buffer is better, maybe because I'm used to the C-c C-z functionality in ESS/iESS mode.

**Comment by jorgenschaefer** [comment]
@JunnanZ, no, the old behavior jumps to the last buffer.

Workflow:

- You are in `foo.py` and hit `C-c C-z`
- Now you are in `*Python*`
- You switch to `bar.py`
- Then you switch to `baz.txt`
- Then you switch back to `*Python*`
- Then you hit `C-c C-z` again. Where do you end up?

1) Old behavior: In `baz.txt`
2) Your described behavior: In `bar.py`
3) Behavior I describe: In `foo.py`

I agree that (1) is not desirable. I'm unsure about (2) vs. (3). (3) is easier to implement, (2) is ok to do (similar to what @gopar describes above).

**Comment by JunnanZ** [comment]
@jorgenschaefer 

Yeah you are right, and I'm not sure either. Both are ok for me as long as I know what it does.  ESS uses the (2) approach though.

**Comment by gopar** [comment]
Personally, I'd prefer (3) since if you're calling the shell from a py buffer, you most likely want to jump back to it. I can create an PR if interested.

**Comment by jorgenschaefer** [comment]
PRs are always great, thank you! :-)
