### ISSUE TITLE
Inferior Python Strangeness

### ISSUE THREAD

**Issue by Gastove** [jorgenschaefer/elpy#985]
Hello, and apologies for the vague title, but I'm simply not sure how else to put it. Here's what I've got: 

I'm using Emacs 25.1 on OSX with homebrew-installed python 3.5. My python setup is [mostly elpy](https://github.com/Gastove/orary/blob/master/modules/orary-python.el). I've recently gone back to cpython for my interpreter (thanks IPython 5). I'm having the same strange behavior as detailed in #887. Additionally, every time I start the interpreter, I get this warning:

```
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 
```

But wait: now things get _really_ weird. Here's an excerpt of a cpython session:

```
>>> if 2 == 3:
... print('oh no')
oh no
>>> if False:
... print('???')
???
```

So honestly: I've got no idea if Elpy is the problem. All of this *does* go away if I disable Elpy -- but I cannot see where or how Elpy could possibly be causing the issue. Maybe someone else has seen this? Maybe someone has even a vague, hand-wavy guess about what's going on here?

**Comment by Gastove** [comment]
_HNGGGG_. I decided to do an almost ritualistic update everything/restart everything, and nowwwww I can't consistently reproduce this. Sorry for the noise -- I'll close this for now (though I still haven't got a *clue* what happened).

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! I'm glad this solved itself. Never hesitate to file a report, I'd rather get too many bug reports than too few :-)

**Comment by Yossarian0916** [comment]
I've come across the same issue, but when I disable python-shell-completion, the interpreter works normally.
```Lisp
(setq python-shell-completion-native-enable nil)
```
