### ISSUE TITLE
elpy-importmagic-add-import aborts with error "symbol index failed to build"

### ISSUE THREAD

**Issue by JosefAtmin** [jorgenschaefer/elpy#986]
Hello!

My elpy-config reads

```
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.11.1
Syntax checker....: pyflakes (/home/wiskott/.local/bin/pyflakes)

You have not activated a virtual env. While Elpy supports this, it is often a good idea
to work inside a virtual env. You can use M-x pyvenv-activate or M-x pyvenv-workon to
activate a virtual env.

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button to invoke its
action.  Invoke [+] to expand a group, and [-] to collapse an expanded group.  Invoke the
[Group], [Face], and [Option] buttons below to edit that item in another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[+]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[+]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
```
When I am in a .py file and type 'C-c RET cos RET' to see where to import the cos function from, I get the error message:
`Elpy warning: symbol index failed to build: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages'`
The permissions read in emacs:
```
/usr/local/lib/python2.7:
  total used in directory 16 available 5290208
  drwxrwsr-x 4 root staff 4096 Aug 26  2015 .
  drwxr-xr-x 5 root root  4096 Sep  2 11:39 ..
  drwx--S--- 4 root staff 4096 Aug 26  2015 dist-packages
  drwxrwsr-x 2 root staff 4096 Jun 26  2015 site-packages
```
Except for [https://github.com/jorgenschaefer/elpy/pull/400]( https://github.com/jorgenschaefer/elpy/pull/400) I have found little info on that and I don't understand enough to proceed in any way.

Best, Josef.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is two problems in one.

The first is that your `/usr/local/lib/python2.7/dist-packages` directory is not readable. importmagic tries to read the packages in there and fails. That's the error you see. You can use `sudo chmod 755 /usr/local/lib/python2.7/dist-packages` to fix this problem (the permissions you have there look pretty broken).

The second is that importmagic should probably not simply throw an exception in this case. I'm unsure about this, but that's a problem with importmagic and should probably be reported there.

Let me know if this helps!

**Comment by JosefAtmin** [comment]
Changing the permissions and restarting emacs did the trick.

Thanks a lot.

Josef.

**Comment by jorgenschaefer** [comment]
Glad it works now, and enjoy Elpy :-)
