### ISSUE TITLE
How to make elpy-multiedit-python-symbol-at-point save files automatically

### ISSUE THREAD

**Issue by JosefAtmin** [jorgenschaefer/elpy#987]
Hello!

When I use elpy-multiedit-python-symbol-at-point, elpy asks me for all modified files whether it should save them.  That sounds reasonable, but when I rename a lot of names that are distributed over several files, it is rather cumbersome, because each edit modifies several files. Thus, I was looking for a way to tell elpy that it should not ask me whether to save an open file, just save them, ideally temporarily.

I have found no hint on that on the internet.

A solution I came up with is the following: I added

```
(fset 'elpy-multiedit-python-symbol-at-point-without-questions
   [?\C-u ?\C-x ?s escape ?x ?e ?l ?p ?y ?- ?m ?u ?l tab ?- ?p tab return])
```
to my .emacs file.  This runs first 'C-u Cx s' to save all open files without question, and then it runs 'elpy-multiedit-python-symbol-at-point'.  When I have a major editing job to do, I can simply define this as a macro with 'C-x ( M-x elpy-multiedit-python-symbol-at-point-without-questions C-x )' and use 'C-x e' instead of 'C-c C-e', or I could permanently bind this to 'C-c C-e', but then I don't have the option to use either of the two versions anymore.

I post this problem together with my solution, because it might be useful for others.  I hope that is ok.

Best,

Josef.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion. Yes of course this is ok :-) I'm afraid I don't think there is a good way to make this the default in Elpy that would not pose problems for others, so I'll close this issue. I hope you enjoy Elpy!

**Comment by JosefAtmin** [comment]
PS: An alternative to the solution above is to type '!' to the question, whether a file should be saved. That also saves all remaining files without further questions. I found this useful in cases, where I rename only a few names.

PPS: In principle it would be good if elpy would not ask to save all modified files but only those that are relevant to the project.
