### ISSUE TITLE
highlight indentation can't be disabled

### ISSUE THREAD

**Issue by valentjedi** [jorgenschaefer/elpy#995]
Hi, I try to disable highlight indentation which came from `elpy-module-highlight-indentation` and I can't do that.
I tried to disable it through `elpy-config` or manually delete it from `elpy-modules` but indentation is still highlighted. 

The only way I can disable it is to issue `M-x highlight-indentation-mode` manually in current buffer.
For some reason even putting `(highlight-indentation-mode 0)` in config doesn't work. I think that elpy initialize it's module after that.

P.S. I feel like it's a very newbie question :/

**Comment by kootenpv** [comment]
No, it's a very big concern for me as well. This highlight mode quite "misbehaves". I'd be very interested to see someone with a nice setup, because it just looks very ugly in my experience.

**Comment by valentjedi** [comment]
@kootenpv I did this and it didn't help me. Indentation still showing up until I completely switch off `highlight-indentation-mode`

**Comment by gopar** [comment]
Do you have any other places were you might be using `highlihght-indentation`? I only added this line to my `init.el`, restarted emacs, and it works.

``` lisp
(delete `elpy-module-highlight-indentation elpy-modules)
```

**Comment by valentjedi** [comment]
@gopar I don't think so, putting `(delete `elpy-module-highlight-indentation elpy-modules)` didn't helped either :( I haven't even mention highlight-indentation in my `init.el`. Here is it just in case: https://github.com/valentjedi/emacsd/blob/master/init.el

**Comment by jorgenschaefer** [comment]
What's the value of `elpy-modules` (C-h v elpy-modules) after restarting Emacs? It should not include highlight-indentation-mode. Also, make sure to restart Emacs, changing Elpy's config won't affect already opened Python buffers.

**Comment by valentjedi** [comment]
```
(elpy-module-company elpy-module-eldoc elpy-module-pyvenv elpy-module-yasnippet elpy-module-sane-defaults)
```
So it means that there must be something else enabled highlighting?

**Comment by jorgenschaefer** [comment]
Yes – elpy does only enable those modules when it starts up.

**Comment by valentjedi** [comment]
Hmm. yeah, I just remove elpy and nothing changed. So I guess problem in something else. I think I'll close this issue. Thank you all for help and suggestions.
