### ISSUE TITLE
Using elpy from a .bat started emacs

### ISSUE THREAD

**Issue by Modestio1** [jorgenschaefer/elpy#997]
I use  a .bat file to add qgis to python path then open that environnement in emacs. I am unable to find or set or install elpy in the .emacs file or the bat file. 

The modules are installed but Emacs don't find them. I saw a similar post, but couldn't find an answer. 

My bat file is the following:

@echo off
SET OSGEO4W_ROOT=C:\OSGeo4W
call "%OSGEO4W_ROOT%"\bin\o4w_env.bat
call "%OSGEO4W_ROOT%"\apps\grass\grass-6.4.4\etc\env.bat
@echo off
path %PATH%;%OSGEO4W_ROOT%\apps\qgis\bin
path %PATH%;%OSGEO4W_ROOT%\apps\grass\grass-6.4.4\lib
set PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\qgis\python;
set PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\Python27\Lib\site-packages
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT%\apps\qgis
start "Emacs aware of Quantum GIS" /B "C:\tool\emacs\bin\runemacs.exe" %*

My emacs is the following:

;http://ergoemacs.org/emacs/emacs_package_system.html
;http://emacs.stackexchange.com/questions/16831/using-package-el-to-install-and-update-but-use-package-for-loading-and-configuri

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.

(require 'package)
(setq package-enable-at-startup nil)   ; To prevent initialising twice
(add-to-list 'package-archives
	     '("melpa" . "https://stable.melpa.org/packages/"))
(add-to-list 'package-archives
	     '("gnu" . "https://elpa.gnu.org/packages/"))
(add-to-list 'package-archives
	     '("elpy" . "http://jorgenschaefer.github.io/packages/"))		

(package-initialize t)

        ;("marmalade" . "https://marmalade-repo.org/packages/")
                         

(package-refresh-contents)
(package-install 'use-package))

(eval-when-compile
  (require 'use-package))

;; Elpy, the Emacs Lisp Python Environment
;; Initialize package mode along with all the installed packages

(use-package elpy                     ; The one and only Git frontend
  :ensure t
  :bind (("C-c v c" . elpy-jedi)
         ("C-c v v" . elpy-importmagic)
         ("C-c v g" . elpy-autopep8)
         ("C-c v l" . elpy-yapf)
         ("C-c v p" . elpy-pyflakes)
	 ("C-c v p" . elpy-pyenv))
   :config (setq elpy-save-repository-buffers 'dontask))

(elpy-enable)
(setq elpy-rpc-backend "jedi")

(elpy-mode)
  ;; Jedi backend                                                                                       
(jedi:setup)
(setq jedi:complete-on-dot t)                                                              
  

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.

 '(company-auto-complete t)
 '(elpy-mode-hook (quote (subword-mode hl-line-mode)))
 '(package-selected-packages (quote (## elpy))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

I know there are issues in my emacs file. 

When I open emacs normally. Elpy is listed in package list as installed but is not available (M-x elpy returns [no match].¸

More precisely if I use package-refresh-contents then package-list packages. elpy is listed as installed but no match. 

If I uninstall and reinstall it I get the following elpy-config:

Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.11 (c:/OSGeo4W/apps/Python27/pythonw.exe)
Interactive Python: python (c:/OSGeo4W/apps/Python27/python.exe)
Emacs.............: 25.1.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.12.0
Syntax checker....: pyflakes.exe (c:/OSGeo4W/apps/Python27/Scripts/pyflakes.exe)

Also : Package list packages tells me pyenv is installed but not elpy. 

  elpy               1.12.0        installed             Emacs Python Development Environment
  company            0.9.0         dependency            Modular text completion framework
  find-file-in-pr... 3.3           dependency            Find files in a project quickly.
  highlight-inden... 0.6.0         dependency            Function for highlighting indentation
  pyvenv             1.9           dependency            Python virtual environment interface
  yasnippet          0.10.0        dependency  

When I use my bat file to open emacs. The emacs file is not read and no modules are available. 

So I have multiple issues:

I can't use elpy in a normally started emacs session. 

How do I get it to work?

And I can't get it to work when started from my bat file. 

I want an emacs environment in which I can use Qgis being auto-completed by elpy in emacs. I had big troubles getting Qgis to work outside the GUI... The bat file is how I managed it.

Thanks in advance. 

I hope my issue is clear.

**Comment by jorgenschaefer** [comment]
I'm afraid I have no idea about Windows. I'm not even sure if this is an Elpy question – isn't this a problem with Emacs in general?

**Comment by Modestio1** [comment]
From what I managed to understand since the question, the issue is with my emacs init file. I, more or less, fixed the issue with a new init file. The issue could be closed or removed.

**Comment by jorgenschaefer** [comment]
Oh, great to hear :-) Enjoy Elpy!
