### ISSUE TITLE
Cannot connect to jorgenschaefer

### ISSUE THREAD

**Issue by alextinng** [jorgenschaefer/elpy#998]
I am trying to install elpy using this way:

(require ‘package) 
(add-to-list ‘package-archives 
‘(“elpy” . “https://jorgenschaefer.github.io/packages/“))
but it does not work, emacs showed this:
![image](https://cloud.githubusercontent.com/assets/17078980/18979757/6060b8f8-8700-11e6-8b0f-b6490eef5ecb.png)

**Comment by gopar** [comment]
Would you happen to be in windows? I remember I had similar issues regarding TLS with it. I never did resolved it though.

**Comment by jorgenschaefer** [comment]
You could try running that command line shown there (`openssl s_client ...`) by hand and see if that gives a better error.

**Comment by alextinng** [comment]
@gopar Yes, I am using windows.

**Comment by gopar** [comment]
@alextinng were you able to resolve it? and if you did, what was the solution?
